### ISSUE TITLE
t-swiper 组件滑动过程中，明显感觉要比原生卡顿

### ISSUE THREAD

**Issue by synctimes163** [Tencent/tdesign-miniprogram#1002]
### tdesign-miniprogram 版本

0.9.0

### 重现步骤

t-swiper 组件滑动过程中，明显感觉要比原生卡顿 

![image](https://user-images.githubusercontent.com/78259973/201290770-073b1780-7148-41eb-a903-ea2d38776f92.png)

操作过程中，从右边滑动到左边，基本要手机释放位置较贴近左边释放才有效，过早释放手势，又滑动回归到原位置。体验感很不好，对比其他框架的Swiper 比如 uView ， vant 也会有所差异发现

### 期望结果

滑动感更顺畅，

**Comment by skerhub** [comment]
针对题主所说的滑动不灵敏问题。补充一点：t-swiper开启自动播放，播放到最后一屏，然后回到第一屏时：呈现的视觉效果是快速的从最后一屏回滚到第一屏，这种方式存在的问题就是当项很多时，快速复位在视觉上看就是闪动的。建议像原生swiper一样支持circular衔接滑动
