### ISSUE TITLE
[t-textarea] 关于在小程序使用t-textarea组件confirm-type属性的建议

### ISSUE THREAD

**Issue by fqz199** [Tencent/tdesign-miniprogram#1005]
### 这个功能解决了什么问题

我在使用t-textare这个组件的时候需要用到边输入内容边换行的功能, 经测试发现t-textarea设置右下角按钮并没有这个属性.  但是小程序原生的textarea的右下角按钮是有换行属性

### 你建议的方案是什么

希望可以在confirm-type属性中添加可换行的功能

**Comment by LeeJim** [comment]
confirm-type 可以直接用 return。
不过确实应该保持和原生组件一致的默认值，文档也缺少了 return 这个可选值。
感谢反馈～
