### ISSUE TITLE
Cell 组件 jump-type 使用与文档不匹配

### ISSUE THREAD

**Issue by vhxubo** [Tencent/tdesign-miniprogram#101]
**Describe Framework**

tdesign-miniprogram

**Describe Environment**

fc003c6d91ba76126bedaa0b0bc71e37a3ba8a03

**Describe the bug**
```html
<!-- 在为 Cell 组件设置 url 后, 点击组件报错: `TypeError: wx[jumpType] is not a function` -->

<t-cell title="添加" hover arrow url="/pages/meeting/staff/index" ></t-cell>

<!-- 按照文档同时设置 url 和 jump-type 后, 依旧报错 `TypeError: wx[jumpType] is not a function` -->

<t-cell title="添加" hover arrow url="/pages/meeting/staff/index" jump-type="navigate-to"></t-cell>
```

根据代码定义, 目前使用的方案:
```html
<t-cell title="添加" hover arrow url="/pages/meeting/staff/index" jump-type="navigateTo"></t-cell>
```

**Additional context**
https://github.com/Tencent/tdesign-miniprogram/blob/fc003c6d91ba76126bedaa0b0bc71e37a3ba8a03/src/cell/README.md#L96
https://github.com/Tencent/tdesign-miniprogram/blob/fc003c6d91ba76126bedaa0b0bc71e37a3ba8a03/src/cell/cell.ts#L45-L52

**Comment by LeeJim** [comment]
我来跟进一下。
