### ISSUE TITLE
[Navbar] 高度及padding-top没有使用组件初始化时从系统获取的值

### ISSUE THREAD

**Issue by dongfg** [Tencent/tdesign-miniprogram#1015]
### 重现链接
https://codesandbox.io/s/tdesign-miniprogram-navbar-0-26-cfue7r

### 重现步骤
使用自定义导航栏

### 期望结果
navbar高度及padding-top使用组件初始化时从系统获取的值进行覆盖

### 实际结果
navbar高度及padding-top没有使用组件初始化时从系统获取的值

![image](https://user-images.githubusercontent.com/5753141/201807227-cbe9110c-157b-4afc-92c6-e30c3379997a.png)

| Environment | Info |
|---|---|
| 相关版本 | 0.26.0 |
| 框架版本 / 基础库版本 | 小程序(2.27.0) |
| 系统、浏览器 | macOS(12.6) |
| Node版本 | v19.0.1 |

**Comment by dongfg** [comment]
看了下代码一个是 ts 里 [`boxStyle`](https://github.com/Tencent/tdesign-miniprogram/blob/cff92d994b90686377e24cb5d2c4d3e75f1d6885/src/navbar/navbar.ts#L80) 里变量的名称与less文件里不匹配；
另外一个是 wxml 里 [`boxStyle`](https://github.com/Tencent/tdesign-miniprogram/blob/cff92d994b90686377e24cb5d2c4d3e75f1d6885/src/navbar/navbar.wxml#L4) 的位置也覆盖不了 `&__placeholder` 里引用的变量

**Comment by lixunhui** [comment]
有解决办法吗，我升级了之后也出这问题了

**Comment by lixunhui** [comment]
<img width="445" alt="image" src="https://user-images.githubusercontent.com/4917509/202836112-8e40d596-9481-48ed-8801-40d5f645143e.png">


`<t-navbar  class="navbar_cus" title="{{appName}}"  />`
`
.navbar_cus {
	--td-navbar-color: #fff; 
	--td-navbar-bg-color: #0052d9; 
}
`

**Comment by LeeJim** [comment]
下周一发版本前处理一下
