### ISSUE TITLE
Rate 组件没有实现 描边类型，官网示例 Demo 没有看到

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-miniprogram#103]
**Describe Framework**

tdesign-miniprogram

**Describe the bug**

![image](https://user-images.githubusercontent.com/11605702/148919305-0dd5b9a9-6731-4e8e-9cf5-4590f7221ac8.png)

**Additional context**

**Comment by LeeJim** [comment]
@zhenzhencai 麻烦 zhenzhen 看一下

**Comment by LeeJim** [comment]
对应的实现是有的，只是缺了示例代码而已，后续补充一下即可。

**Comment by zhenzhencai** [comment]
示例Demo已补充

**Comment by jin0209** [comment]
https://github.com/Tencent/tdesign-miniprogram/pull/189/commits
