### ISSUE TITLE
[Textarea] 最多只能输入140个字符

### ISSUE THREAD

**Issue by cosmo2097** [Tencent/tdesign-miniprogram#1033]
### tdesign-miniprogram 版本

0.26.0

### 重现步骤

引入Textarea组件并不断输入文字，对maxlength进行各种值的测试，如：-1，500

### 期望结果

可以输入更多的字符

### 实际结果

只能最多输入140个字符

### 补充说明

根据小程序textarea组件的官方文档，在maxlength不设置时，默认maxlength=140，设置为-1时不限制。t-textarea好像并未给内部的textarea设置maxlength。

**Comment by anlyyao** [comment]
我来处理～

**Comment by ZS1994** [comment]
我也发现同样问题，如果我设置maxlength大于140时，无论有多大，实际上最多也只能输入140个字符
