### ISSUE TITLE
「技术向善，助力 TDesign 无障碍改造」主题活动开始啦

### ISSUE THREAD

**Issue by LeeJim** [Tencent/tdesign-miniprogram#1045]
### Discussed in https://github.com/Tencent/tdesign-miniprogram/discussions/1044

<div type='discussions-op-text'>

<sup>Originally posted by **tdesign-helper** November 17, 2022</sup>

## 本期活动

技术向善，助力 TDesign 无障碍改造

## ⏲ 持续时间

**2022 年 11 月 15 日起至 2023 年 1 月 15 日**

## 📃 活动简介

TDesign 牵手适老化&无障碍 Oteam 发起“技术向善，助力 TDesign 无障碍改造” 活动，聚焦无障碍领域，以技术赋能，助力无障碍建设进程与服务质量，2022 年 11 月 15 日至 2023 年 1 月 15 日期间，参与无障碍改造活动，解决 issue，不仅可以结识兴趣伙伴，还可获得丰厚奖励，让我们一起来做公益好事吧！

## ⛳️ 贡献路径

1. 认领相关任务（见下文）
1. 共建开始
1. 在 GitHub 提交 PR
1. 发布者采纳
1. 完成任务
1. 获得积分与奖励

## 🔥 活动任务

点击下面链接，查看无障碍改造相关 issue

👇👇👇

https://github.com/Tencent/tdesign-miniprogram/issues

👆👆👆

## 🎁 活动礼品

TDesign 为本次活动提供了 TDesign 官方证书、京东卡、TDesign 新款定制T恤/鼠标垫/定制贴纸/工卡套/口罩等。

### 奖励规则说明

本次活动将采用积分兑换奖励制，即完成 issue 即可获得相应的贡献力积分，贡献者可凭所获的贡献力积分来兑换 TDesign 丰富的周边礼品。

后续会将详细的贡献力积分兑换礼品规则公布在 GitHub 上 TDesign 的主仓库 [discussions](https://github.com/Tencent/tdesign/discussions) 中，敬请期待。

除可获得上述活动奖励外，还有机会：

- 参加 TDesign 不定期活动，获得丰厚周边礼品
- 了解开源项目运行机制，参与 TDesign 日常维护，结识技术大咖
- 成为 TDesign 的核心贡献者，参与组件库产品开发讨论，永久展示在官网 GitHub 等处
- 入选开源协同 PMC、参与评选开源协同个人即时激励奖/优秀个人奖，赢取官方丰厚礼品

## 📧 联系我们

了解更多活动详情，请扫描下方二维码
<img width="178" alt="了解更多活动详情二维码" src="https://user-images.githubusercontent.com/4988284/203562374-a061c0b7-0953-4b92-9cae-0c59c0080404.png">

加入TDesign官方活动群，请扫描下方二维码
<img width="177" alt="TDesign官方活动群二维码" src="https://user-images.githubusercontent.com/4988284/203562805-52022742-5886-4242-ada7-8a548e08baf2.png">

## 📌 温馨提示

1、所有任务不限制认领人数，TDesign 官方最终以提交 PR 为准，欢迎大家共建~

## 🏷 活动海报

<img width="1500" alt="活动海报" src="https://user-images.githubusercontent.com/96863479/202382949-e66fe731-5834-480f-9283-fc0d059a99c6.png">
</div>

**Comment by siaa2005** [comment]
这个issue的内容就挺不无障碍的。如果可以将活动详情图片中的内容，另外提供纯文字的表述，可以让更多人阅读和参与了解这个活动。

**Comment by syxysszyw** [comment]
感谢 @siaa2005 的建议，抱歉带来不好的体验，我们已将活动海报整理成文字版，以后会多加注意避免出现类似问题，欢迎一起参与共建：）
