### ISSUE TITLE
[Swiper] 无障碍支持

### ISSUE THREAD

**Issue by anlyyao** [Tencent/tdesign-miniprogram#1056]
## 优先级
> P0 最高，数字越小优先级越高

P1

### iOS 表现
> 测试机：iPhone 11Pro（iOS 15.2） + 旁白

1. 视频定位00：01——轮播图像没有替代文本
2. 视频定位00：14示例中左右2个箭头按钮无法获取焦点

ps：示例中的“开关”“滑块”问题不在本组件处理

### Android 表现

> 测试机：nova 5 pro，HarmonyOS 2.0.0 + 屏幕朗读<与TalkBack可能存在细小差异>
主要补充与iOS表现存在差异的地方

图像未能获取焦点

## 参考信息

录屏：https://share.weiyun.com/DTLGxYDq

## 改造建议

无

## 改造参考示例
> 截图或录屏链接（参考 WeUI Web、小程序组件库、手机原生系统应用等）

https://share.weiyun.com/nRJ63Atq

## 验收标准

真机效果是无障碍改造验收通过的依据之一，请开发者在发起 `pull request` 时附上相应组件示例页分别在 iOS、Android下录屏效果，录屏示例及要求可分别查看 [iOS录屏指引](https://docs.qq.com/sheet/DRnBBVFFBWmZuYmRh?tab=ti9wxn)、[Android录屏指引](https://docs.qq.com/sheet/DRnBBVFFBWmZuYmRh?tab=icmj6f)。

最终 `pull request` 验收通过会以 iOS、Android 两个平台都满足无障碍要求为准，**同时**这两个平台的录屏链接有助于加快 `pull request` 通过效率哦：） 

## 常见无障碍 Q&A

[点我查看](https://docs.qq.com/sheet/DRnBBVFFBWmZuYmRh?tab=7b6unt&u=ebb77e942ee0425d878186af79e5ec6d)

## 其他说明
如果您准备修复此问题，请您在发起 `pull request` 之前先在 issue 中评论，以便其他开发者知道这个问题已经有人在跟进：）

最终激励以实际提交 `pull request` 并合并为准

## TDesign 开发者交流群
![待补充二维码](https://camo.githubusercontent.com/81e382234a4be1d5e773af94e298bcc50aec70fa85ecd5a84f29044415566ac7/68747470733a2f2f6f7465616d2d7464657369676e2d313235383334343730362e636f732e61702d6775616e677a686f752e6d7971636c6f75642e636f6d2f736974652f646f632f5444657369676e253230494d2e706e67)

## IssueShoot
- 预估时长: 10
- 期望完成时间: 2023-4-10
- 开发难度: 高
- 参与人数: 1
- 验收标准: 实现期望改造效果，提MR并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by syxysszyw** [comment]
### iOS
1、视频定位00：22，打开选择器后，单指滑动焦点无反应（视频打开后有较长时间停顿，现实中在不停左右滑动，但焦点依旧保留在原位置），触摸能切换焦点位置；
2、视频定位00：44开始，可以看到每一列当前选中选项发生改变以后，焦点往回走依旧是聚焦在列的第一个元素上（预期是聚焦在当前选中的选项上），虽然点击“确认”选中的确实是当前视觉看到的选项，但会对视障用户造成困扰
https://user-images.githubusercontent.com/4988284/226610194-47a6cc19-33c7-46d9-931f-13ea1d3f044e.MP4

https://user-images.githubusercontent.com/4988284/226612233-a6db35c0-7886-4b62-a592-4fc8bcfc80b9.MP4


### Android
1、存在焦点穿透问题
2、切换选项时未有实时播报，无法得知当前选中的选项
3、每一列会有2次焦点（整个列的容器一次，读为“列表框”；当前选中的选项一次），焦点在这2个元素上均可拖动切换选项，前者焦点位置固定，后者焦点位置跟随打开时当前列被选中的选项

https://user-images.githubusercontent.com/4988284/226613341-f2f89317-8581-4618-88c0-70e06e8df8fd.mp4

https://user-images.githubusercontent.com/4988284/226613772-9d3cee0d-0517-4414-8707-1ce6f11d8728.mp4





### 共性问题
“确认”虽然在视觉上是在最顶部，但是实际操作过程中，选完最后一列需要将焦点往回切（列数越多困扰越大），才能聚焦在“确定”按钮并完成选择，建议在保持现有视觉效果的同时，将“确认”按钮的顺序调在选项的最后面（需要调整“确定”按钮的代码结构）
