### ISSUE TITLE
checkbox checked 属性 配合 change 事件使用时 无法支持 组建受控

### ISSUE THREAD

**Issue by wutianSweet** [Tencent/tdesign-miniprogram#106]
<t-checkbox
              checked="{{item.selected}}"
              t-class="cart-item-select"
              color="#07C160"
              value="{{item.skuId}}"
              wx:for="{{cartList}}"
              wx:key="index"
              content-disabled="{{true}}"
              bind:change="onSelectCartChange"
              data-cart="{{item}}"
            ></t-checkbox>

**Comment by amberlwan** [comment]
最新版本将会支持，年前发布版本

**Comment by LeeJim** [comment]
v0.5.0 已支持
