### ISSUE TITLE
Button 组件支持纯图标按钮

### ISSUE THREAD

**Issue by vhxubo** [Tencent/tdesign-miniprogram#108]
**你想要的特性**

![image](https://user-images.githubusercontent.com/17352372/149063033-6747bc10-1c9a-435f-a483-99d662642920.png)

**你想要的解决方案**

Button 组件支持纯图标按钮, 而不仅仅是带图标按钮

**你考虑过的替代方案**

使用 external-classes 覆盖原有样式

**Comment by LeeJim** [comment]
收到诉求，确实应该补充改一下，已和设计师沟通。
后面有进展我会在下面补充
