### ISSUE TITLE
[DropdownMenu] 无法进行下滑滚动操作

### ISSUE THREAD

**Issue by chundonghan** [Tencent/tdesign-miniprogram#1081]
### tdesign-miniprogram 版本

0.26.0

### 重现步骤

问题组件：
    DropdownMenu组件
问题描述：
    苹果7 使用`npm i tdesign-miniprogram -S --production` 安装的组件库 ，在使用 DropdownMenu 下拉菜单组件时 无法进行下滑滚动操作；
补充：
    但是用TDesign模板创建的项目是可以进行下滑滚动操作

### 期望结果

希望能够得到回复，辛苦了

**Comment by china-live** [comment]
我也遇到这个问题，在电脑模拟器中用鼠标可以滚动，在手机上无法滑动。

**Comment by LeeJim** [comment]
我来处理下
