### ISSUE TITLE
[search] 左图标插槽

### ISSUE THREAD

**Issue by nenio1949** [Tencent/tdesign-miniprogram#1084]
### tdesign-miniprogram 版本

0.26.0

### 重现步骤

搜索框左侧图标插槽无效

<img width="1529" alt="image" src="https://user-images.githubusercontent.com/37364223/202981906-7eacd7b8-212a-4448-83f2-40ae0e0abc24.png">

**Comment by LeeJim** [comment]
明天发布版本，处理一下
