### ISSUE TITLE
[Navbar] 背影色异常

### ISSUE THREAD

**Issue by quxiaodong** [Tencent/tdesign-miniprogram#1092]
### tdesign-miniprogram 版本

0.27.0

### 重现步骤

`.t-navbar__content`这个class类无法继承`.t-navbar`的背影色，导致页面滚动的时候，透过navbar看到下面的内容，0.26.0没有此问题，更新0.27.0后出来

**Comment by lixunhui** [comment]
是啊，页面滚动的时候，背景色就跟着滚动出页面了。fixed 将控件固定到页面也没用。Navbar从0.25版本到现在每发布一个版本都有问题，发版之前不用测试是吗

**Comment by LeeJim** [comment]
尽快处理下，最近在视觉改版，可能测试不够充分
