### ISSUE TITLE
[t-cell] 字体大小问题

### ISSUE THREAD

**Issue by wengxiaoxiong** [Tencent/tdesign-miniprogram#1095]
### 这个功能解决了什么问题

这个T-cell的字体有没有可能让他可以设置大小呢，还是说可以直接用什么办法设置呢？不好意思，我是新手

### 你建议的方案是什么

搞一个变量

**Comment by LeeJim** [comment]
新增支持 CSS Variables 了。
可以通过修改 `--td-cell-font-size` 来调整字体大小
