### ISSUE TITLE
[Grid]  建议Grid组件增加自自定义图标写法

### ISSUE THREAD

**Issue by lixunhui** [Tencent/tdesign-miniprogram#1101]
### 这个功能解决了什么问题

目前t-icon数量不足一满足所有需求，项目开发中需要用到如iconfont等自定义图表，但是目前grid组件无法满足使用自定义图标的需求

### 你建议的方案是什么

增加配置自定义图标的属性或者solt

**Comment by anlyyao** [comment]
1. slot用法参考：
`<t-grid-item text="标题文字" image="slot" >
    <t-image slot="image" src="{{img}}" width="32px" height="32px"/>
  </t-grid-item>`

2. 已新增 iconProps 用于配置图标属性，可以配合 icon 使用自定义图标

**Comment by lixunhui** [comment]
@anlyyao 👍可否完善文档并在文档中提供相应示例

**Comment by lixunhui** [comment]
新版本中取消了iconProps,是不支持自定义图标写法了吗
