### ISSUE TITLE
[Calendar] confirm-btn 设置null无效，select event无效

### ISSUE THREAD

**Issue by lixunhui** [Tencent/tdesign-miniprogram#1108]
### tdesign-miniprogram 版本

0.27.0

### 写法1，confirm-btn 在js中定义
`<t-calendar visible="{{calendar_visible}}" bind:confirm="handleSelect" type="single" confirm-btn="{{confirm_btn}}"/>`
JS中代码
   ` confirm_btn:null`
结果无效
<img width="461" alt="image" src="https://user-images.githubusercontent.com/4917509/203732563-25c30472-d742-4c18-9cfb-bd7ec20b7c66.png">

### 写法2，confirm-btn=null，报错
`<t-calendar visible="{{calendar_visible}}" bind:confirm="handleSelect" type="single" confirm-btn=null/>`
<img width="748" alt="image" src="https://user-images.githubusercontent.com/4917509/203732747-6ad0010f-f394-4dc8-91c9-5a09c274b405.png">

### 写法3，confirm-btn=“null”，确认按钮显示，只是不显示确认文字
`<t-calendar visible="{{calendar_visible}}" bind:confirm="handleSelect" type="single" confirm-btn="null"/>`
效果如下
<img width="474" alt="image" src="https://user-images.githubusercontent.com/4917509/203732671-eade0cc7-9a70-4435-bcfa-3cb10ac054af.png">

----
### bind:select 无效
`<t-calendar visible="{{calendar_visible}}" bind:select="handleSelect" type="single"/>`
`	handleSelect(e) {
		console.log(e.detail.value);
		this.hideCalendar();
	}`
日历上点击选择后不触发事件

### 期望结果

1. 日历支持隐藏确认按钮
2. 日历支持select事件

### 实际结果

1. 日历不支持隐藏确认按钮【bug】
2. 日历不支持select事件【bug】

### 补充说明

npm: '8.18.0',
node: '18.8.0',
v8: '10.2.154.13-node.11',
tdesign-miniprogram@0.27.0

**Comment by lixunhui** [comment]
另外，设置最大时间和最小时间后，打开日历默认界面能否停留在value值的地方，目前设置最大最小时间之后，默认停留在最小可选择日期的月份

**Comment by LeeJim** [comment]
感谢反馈，我来定位下问题

**Comment by LeeJim** [comment]
> 另外，设置最大时间和最小时间后，打开日历默认界面能否停留在value值的地方，目前设置最大最小时间之后，默认停留在最小可选择日期的月份

感谢反馈，我来支持下

**Comment by LeeJim** [comment]
> 另外，设置最大时间和最小时间后，打开日历默认界面能否停留在value值的地方，目前设置最大最小时间之后，默认停留在最小可选择日期的月份

对应 PR：#1119 ，预计下周一发布
