### ISSUE TITLE
[DropdownMenu]下拉菜单change事件只返回了value值，没法回显对应的label值

### ISSUE THREAD

**Issue by Thinksheep** [Tencent/tdesign-miniprogram#1112]
### 这个功能解决了什么问题
选择下拉值之后，没法对用户显示label能看懂的值

### 你建议的方案是什么？
可以将返回的value改成获得已选项的索引值

**Comment by LeeJim** [comment]
我来处理下

**Comment by LeeJim** [comment]
options 是你提供的，value 对应的 label 也是可以获得的。
不过是提供 label 这个操作如果我们提供了，会更便捷一些。

**Comment by LeeJim** [comment]
#1265 增加了特性，可通过 value 和 options 自动切换 label
