### ISSUE TITLE
[Navbar] left-arrow 返回事件，在 delta="0"的时候无法触发 go-back方法，文档中event方法名称go-back 在js中不支持此类方法命名方式

### ISSUE THREAD

**Issue by lixunhui** [Tencent/tdesign-miniprogram#1114]
### tdesign-miniprogram 版本

0.27.0

### 文档中，event go-back方法命名在js中报错不支持
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/4917509/204020449-14757db2-6872-4400-aae4-c188cb8bc5dc.png">

### 期望结果

修改go-back方法名为goback

**Comment by LeeJim** [comment]
我来处理

**Comment by LeeJim** [comment]
我知道问题了，你应该用的是 bindgo-back 这样的写法，小程序可能解析有点问题。
使用 `bind:go-back` 即可

**Comment by lixunhui** [comment]
@LeeJim  感谢感谢，原来是这个原因，是我疏忽了，抱歉给你增加工作量

**Comment by LeeJim** [comment]
没事，感谢反馈。我们这边增加下示例
