### ISSUE TITLE
[Image] 无法加载 cloud file id 路径

### ISSUE THREAD

**Issue by hasassnz** [Tencent/tdesign-miniprogram#1118]
### 这个功能解决了什么问题

如题，t-image 无法加载cloud file id 路径图片，image 是可以的，t-image不可以？

### 你建议的方案是什么

求助

**Comment by LeeJim** [comment]
我来看看

**Comment by hasassnz** [comment]
是不是在做路径规则的时候没把cloud单独写？小程序的安全规则没添加白名单，加载不了是正常的，我想cloud不至于的

**Comment by LeeJim** [comment]
t-image没有对 src 做特殊处理，直接透传给了 image 组件，不明白为啥有问题？
我这没有云环境，因此测试不了，是不是这个 cloud file 不存在？

**Comment by hasassnz** [comment]
我也说不明白，tdesign有一个云开发实例，直接吧cloud的file id写入src，是无法加载的，应该是你说的“不存在”吧。直接用原生image是可以的
&nbsp;


该邮件从移动设备发送


&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2022年12月6日(星期二) 下午2:57
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [Tencent/tdesign-miniprogram] t-image 无法加载 cloud file id 路径 (Issue #1118)





 
t-image没有对 src 做特殊处理，直接透传给了 image 组件，不明白为啥有问题？
 我这没有云环境，因此测试不了，是不是这个 cloud file 不存在？

**Comment by anlyyao** [comment]
@hasassnz @LeeJim  好像和 #1525 问题一样

**Comment by LeeJim** [comment]
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/7017290/224460957-b6d7942a-84eb-4ec3-ac8d-57054bf86e3d.png">
刚测试了一下，是OK的。
提供下你的基础库版本 以及 TDesign 版本号
