### ISSUE TITLE
[Tabs] TabPanel 的panel属性不起作用

### ISSUE THREAD

**Issue by csshjh** [Tencent/tdesign-miniprogram#1122]
### tdesign-miniprogram 版本

最新版本也有此问题

**Comment by anlyyao** [comment]
@csshjh 贴一下你的代码？

**Comment by csshjh** [comment]
> @csshjh 贴一下你的代码？

 <t-tabs defaultValue="{{0}}" sticky stickyProps="{{stickyProps}}" bind:click="onTabsClick" t-class="custom-tabs">
            <t-tab-panel wx:for="{{tabList}}" wx:for-index="index" wx:key="text" label="{{item.text}}{{item.statistics}}" value="{{item.key}}"></t-tab-panel>
            <t-tab-panel label="筛选" value="" panel="{{ss}}">
                <view class="" slot="panel">
                qweqeqw
                    <t-icon name="filter" size="48rpx" bind:click="onIconTap" />
                </view>
            </t-tab-panel>
            
        </t-tabs>

**Comment by csshjh** [comment]
> @csshjh 贴一下你的代码？

![微信图片_20221128130021](https://user-images.githubusercontent.com/11305847/204198271-57893b4f-fed4-4318-aea0-8866fb0e1f7e.png)

**Comment by anlyyao** [comment]
@csshjh 感觉是使用的问题～， 换成下面这段试试

`<t-tab-panel label="标签页一" value="0" panel="双括号表示变量"></t-tab-panel>
  <t-tab-panel label="标签页二" value="1" >
    <view>
      插槽实现panel内容
    </view>
  </t-tab-panel>
  <t-tab-panel label="标签页三" value="2" panel="3"></t-tab-panel>
  <t-tab-panel label="标签页四" value="3" panel="4"></t-tab-panel>`

**Comment by LeeJim** [comment]
看起来没什么问题，如果还有问题，可以 reopen 这个 issue
