### ISSUE TITLE
[checkbox] 自定义图标不显示

### ISSUE THREAD

**Issue by china-live** [Tencent/tdesign-miniprogram#1134]
### tdesign-miniprogram 版本

0.28.0

### 补充说明

从0.27.0升级到0.28.0后，自定义的checkbox图标消失不显示了。
![QQ截图20221129092922](https://user-images.githubusercontent.com/12002799/204416498-150d926f-07e8-41dd-936d-88ddca6f1333.png)

**Comment by LeeJim** [comment]
我看看

**Comment by china-live** [comment]
一般单选框是圆形的，多选框是方框，为什么这里默认是圆形的，用户怎么区分是单选还是多选。

**Comment by LeeJim** [comment]
默认圆形是为了和之前保持一致。
因为语法的差异，导致数组无法识别，现在已经修复了，发个 beta 版本试试

**Comment by LeeJim** [comment]
可以重新安装下 0.28.0-beta.0
