### ISSUE TITLE
搜索框组件，获取搜索的内容显示undefined

### ISSUE THREAD

**Issue by Antik1991** [Tencent/tdesign-miniprogram#114]
**对应的组件**

Button

**相关环境**

基础库版本：最新

运行环境：开发者工具 / iOS / Android 

**出现的问题**

搜索框组件，获取搜索的内容显示undefined

**Comment by Perisiguiendo** [comment]
方便放出代码吗？

**Comment by Perisiguiendo** [comment]
你好，方便放出代码吗？我这边是可以获取的
![image](https://user-images.githubusercontent.com/58724530/149890335-7e195b57-a053-4b9d-8372-176172dae246.png)

**Comment by Perisiguiendo** [comment]
你好，方便放出代码吗？有可能是取值的参数不对，通过e.detail.value拿到输入框的值
![image](https://user-images.githubusercontent.com/58724530/149890685-f6bb069d-a81f-48a1-826b-c634bbf7a21f.png)

**Comment by Antik1991** [comment]
blur 事件
<img width="593" alt="WechatIMG2479" src="https://user-images.githubusercontent.com/15007688/150058795-7444a7f0-4697-48d3-abc6-d96906a97a3d.png">

**Comment by Perisiguiendo** [comment]
收到，正在处理中，感谢反馈
