### ISSUE TITLE
[t-input] suffixIcon无效

### ISSUE THREAD

**Issue by 645638180** [Tencent/tdesign-miniprogram#1146]
### tdesign-miniprogram 版本

0.28.0

### 重现步骤

t-input label="标签文字" placeholder="请输入文字" suffixIcon="slot"
 t-icon slot="suffixIcon" name="edit"></t-icon>
/t-input

### 期望结果

出现图标

### 实际结果

未出现图标

**Comment by 645638180** [comment]
<t-input label="标签文字" placeholder="请输入文字" suffixIcon="slot">
 <t-icon slot="suffixIcon" name="edit"></t-icon>
</t-input>

**Comment by anlyyao** [comment]
@645638180 试试这样～
`<t-input label="标签文字" placeholder="请输入文字" >
  <t-icon slot="suffixIcon" name="edit"></t-icon>
</t-input>`

**Comment by 645638180** [comment]
你的效果能截个图吗？谢谢

**Comment by 645638180** [comment]
> @645638180 试试这样～ `<t-input label="标签文字" placeholder="请输入文字" > <t-icon slot="suffixIcon" name="edit"></t-icon> </t-input>`

能截个效果图吗？谢谢

**Comment by anlyyao** [comment]
@645638180 
![image](https://user-images.githubusercontent.com/51158141/205677583-86d98261-b2c2-4366-a354-75b61a062aaa.png)
