### ISSUE TITLE
Dialog弹出框 external-classes不能进行修改样式

### ISSUE THREAD

**Issue by whc167** [Tencent/tdesign-miniprogram#115]
**对应的组件**

Button

**相关环境**

基础库版本：最新

运行环境：开发者工具 / iOS / Android 

**出现的问题**

**附加信息**

**Comment by LeeJim** [comment]
我来处理一下

**Comment by oneronaner** [comment]
![image](https://github.com/Tencent/tdesign-miniprogram/assets/41769420/e8687f51-2c22-4fd9-813c-b5dfe19cae7b)
你试试这样，我这样解决了，我服了，折腾了好久
