### ISSUE TITLE
[Cascader] 重新置空options报错

### ISSUE THREAD

**Issue by qinglinyi** [Tencent/tdesign-miniprogram#1154]
### tdesign-miniprogram 版本

0.27.0

### 重现步骤

1. 设置options
2. 进行选项选择
3. 重置options=[]
4. 报错，并且没有清空选项

错误信息：

TypeError: Cannot read property 'id' of undefined
    at Vo.selectedIndexesOptions (cascader.js? [sm]:46)

**Comment by LeeJim** [comment]
收到，我来处理下
