### ISSUE TITLE
[Cell] 怎么添加客服按钮？

### ISSUE THREAD

**Issue by SheepYang1993** [Tencent/tdesign-miniprogram#1161]
### 这个功能解决了什么问题

想要用Cell的样式，然后点击跳转客服消息。
知不知道要怎么添加这个按钮
`<button open-type="contact" bindcontact="handleContact"></button>`

### 你建议的方案是什么

RT

**Comment by LeeJim** [comment]
可以看官网的示例：https://tdesign.tencent.com/miniprogram/components/cell

```
<t-cell title="单行标题">
  <button open-type="contact" bindcontact="handleContact" slot="note"></button>
</t-cell>
```

**Comment by SheepYang1993** [comment]
> 可以看官网的示例：https://tdesign.tencent.com/miniprogram/components/cell
> 
> ```
> <t-cell title="单行标题">
>   <button open-type="contact" bindcontact="handleContact" slot="note"></button>
> </t-cell>
> ```

感谢，已解决
```
<button class="btn-contact" open-type="contact" bindcontact="handleContact" slot="title">
    <t-cell title="联系客服" hover arrow />
</button>
```
```
.btn-contact {
    padding: 0;

    view {
        z-index: 100;
    }
}
```
