### ISSUE TITLE
[Icon 图标]  引入iconfont自定义图标不显示

### ISSUE THREAD

**Issue by lixunhui** [Tencent/tdesign-miniprogram#1162]
### tdesign-miniprogram 版本

0.28.0

### 重现步骤

1、confront添加图标到项目，打开项目，查看在线链接，点击复制代码
http://[at.alicdn.com/t/c/font_3780105_yvgziehuzw9.css](http://at.alicdn.com/t/c/font_3780105_yvgziehuzw9.css)
2、下载到本地，添加到项目中，并修改文件名为font_3780105.wxss
FontClass/Symbol前缀 及部分图标定义如下：
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/4917509/205349578-682eb090-9591-42e7-9a44-45bc7855a9ba.png">

3、app.wxss中引入
<img width="547" alt="image" src="https://user-images.githubusercontent.com/4917509/205349442-05ccc5e4-ef7c-415c-b3fc-feef88bd625f.png">

4、小程序页面使用自定义图标代码：
  <t-icon prefix="icon" name="dianzixue" size="48"  color="red" />
<img width="1851" alt="image" src="https://user-images.githubusercontent.com/4917509/205350088-d50f203e-dc70-46ff-90e7-638e1831fd73.png">
代码及显示效果如上图

### 期望结果

能够正常显示图标

### 实际结果

图标有占位空间，但是显示空白

**Comment by anlyyao** [comment]
@lixunhui 看上去是使用错误，建议跟随官网指引进行。如果是阿里图标库，这两项可以在“项目设置”里，直接设置～
<img width="754" alt="截屏2022-12-05 23 30 35" src="https://user-images.githubusercontent.com/51158141/205676609-4bcddd73-11c4-4b16-9dc8-3e5748b2dac9.png">

**Comment by lixunhui** [comment]
> @lixunhui 看上去是使用错误，建议跟随官网指引进行。如果是阿里图标库，这两项可以在“项目设置”里，直接设置～ <img alt="截屏2022-12-05 23 30 35" width="754" src="https://user-images.githubusercontent.com/51158141/205676609-4bcddd73-11c4-4b16-9dc8-3e5748b2dac9.png">

是完全按照官网指引做的呀
> 将 .wxss 文件中的 FontClass/Symbol前缀 与 Font Family 两项内容保持一致
**如issues中代码截图所示,FontClass/Symbol前缀为`icon-`,Font Family 为` icon`**
页面中使用`prefix ="icon" `

看不出来用法中哪里有问题.而且页面中图标的占位空间也有

**Comment by anlyyao** [comment]
@lixunhui 那个占位是t-icon组件的占位，和你是否正确引入图标没有关系。建议看下实际渲染出来的dom结构～ 另外官网给出了自定义图标示例，你可以试试拿我们的文件去渲染，排除下是否是组件的问题。

将 `.iconfont` 改成 `.icon` 试试
<img width="448" alt="企业微信截图_b5089e4d-27e6-49d2-875f-f9bae7dd2fc7" src="https://user-images.githubusercontent.com/51158141/206172966-dc917738-5deb-485a-b453-e09ebe07a122.png">

<img width="1245" alt="截屏2022-12-07 19 52 35" src="https://user-images.githubusercontent.com/51158141/206173033-3473db70-0e56-47db-8a53-1d77f1bf206f.png">

**Comment by lixunhui** [comment]
>  将 .iconfont 改成 .icon 试试
按照您的方法,这样改可以了
感谢感谢
