### ISSUE TITLE
[Upload] 能不能支持选择完以后裁剪图片？

### ISSUE THREAD

**Issue by SheepYang1993** [Tencent/tdesign-miniprogram#1169]
### 这个功能解决了什么问题

支持选择完图片以后裁剪图片，能设置裁剪宽高比

### 你建议的方案是什么

或者是单独提供裁剪的api或组件？

**Comment by LeeJim** [comment]
upload 支持 click 事件，可以配合 `wx.editImage` 完成你的需求。
目前暂不考虑内置该特性
