### ISSUE TITLE
[小程序日历组件] 构建打包后日历组件丢失

### ISSUE THREAD

**Issue by Skye-0505** [Tencent/tdesign-miniprogram#1175]
### tdesign-miniprogram 版本

0.11.2

### 重现步骤

npm安装
![image](https://user-images.githubusercontent.com/33588563/205873371-f44ec3b7-4e95-4f83-8e63-d058ed5973ea.png)

构建后没有calendar
![image](https://user-images.githubusercontent.com/33588563/205873691-f0454775-3aaa-4d4f-9690-1ec344eb1013.png)

### 期望结果

calendar组件正常使用

### 实际结果

calendar组件丢失

### 框架版本

"tdesign-miniprogram": "^0.11.2"

**Comment by LeeJim** [comment]
0.22.0 之后才支持 Calendar，我这边完善一下文档～
