### ISSUE TITLE
[tabs] tabs动态设置defaultValue不起作用

### ISSUE THREAD

**Issue by csshjh** [Tencent/tdesign-miniprogram#1190]
### tdesign-miniprogram 版本

最新版本也有此问题

### 期望结果

可以动态设置属性值

**Comment by jastby** [comment]
t-collapse 也是一样。
因为t-collapse-panel数据是动态生成的，所以defaultValue也是动态生成的，可能渲染后再set进去就失效啦？

**Comment by LeeJim** [comment]
如果要动态设置值的话，使用 value 而不是 defaultValue

**Comment by jastby** [comment]
> 

使用 value 是可以默认展开了，但是点击所有标题栏没任何反应了（正常可以折叠或者展开）。

**Comment by LeeJim** [comment]
使用 value 的话，就属于受控属性了，需要手动更改 value 的值
