### ISSUE TITLE
[t-input] 升级到 0.29.0 版本后，t-input 组件出现问题

### ISSUE THREAD

**Issue by wrcwind** [Tencent/tdesign-miniprogram#1209]
### tdesign-miniprogram 版本

0.29.0

### 重现步骤

t-input 中增加 focus 属性，输入文本的位置出现了边框，而且输入完成后依然存在。
<img width="1199" alt="截屏2022-12-11 17 18 37" src="https://user-images.githubusercontent.com/4671996/206895743-1d4df503-b540-4d13-a015-279bb8e93abd.png">
![Uploading 截屏2022-12-11 17.19.47.png…]()

### 期望结果

无边框

### 实际结果

有边框

**Comment by anlyyao** [comment]
@wrcwind 收到反馈 我这边跟进一下～
