### ISSUE TITLE
[轮播图] 对比小红书轮播图，轮播图的滑动功能不够流畅，手指滑动具体过长，建议优化

### ISSUE THREAD

**Issue by Antik1991** [Tencent/tdesign-miniprogram#1211]
### 这个功能解决了什么问题

对比小红书轮播图，轮播图的滑动功能不够流畅，手指滑动距离过长，建议优化

### 你建议的方案是什么

轮播图多图查看时，建议缩短手指滑动的距离

**Comment by LeeJim** [comment]
感谢反馈，我来跟进下
