### ISSUE TITLE
[按钮] 描边样式失效

### ISSUE THREAD

**Issue by Skye-0505** [Tencent/tdesign-miniprogram#1213]
### tdesign-miniprogram 版本

0.11.2

### 重现步骤

描边按钮 打包wxss文件中 无outline样式
![image](https://user-images.githubusercontent.com/33588563/206954805-d0142987-01f5-444c-b2d5-1a799a316b34.png)

### 期望结果

描边样式正常显示

### 实际结果

无描边样式显示

### 框架版本

"tdesign-miniprogram": "^0.11.2"

**Comment by LeeJim** [comment]
0.17.0 之后的版本修复了这个问题

**Comment by LeeJim** [comment]
需要升级到 0.17.0 以上。
