### ISSUE TITLE
Dialog 多按钮透传open-type无效

### ISSUE THREAD

**Issue by 916422** [Tencent/tdesign-miniprogram#1233]
### tdesign-miniprogram 版本

0.30.0

### 重现步骤

open-type,openType 写法都无效 
multiBtnList: [
      { name: '关闭', primary: false },
      { name: '1', primary: false},
      { name: '2', primary: true,openType:"share"},
    ]
 
    visible="{{showMultiBtn}}"
    title="对话框标题"
    content="告知当前状态、信息和解决方法，等内容。描述文案尽可能控制在三行内"
    button-layout="vertical"
    actions="{{ multiBtnList }}"
    bind:action="actionDialog"
 

### 期望结果

支持open-type

### 实际结果

无效

### 框架版本

小程序v2.280

### 系统版本

MacOS 12.5

**Comment by LeeJim** [comment]
我来跟进一下，周一发版
