### ISSUE TITLE
[radio] 真机演示上，对号的样式不正常

### ISSUE THREAD

**Issue by Zlianxin** [Tencent/tdesign-miniprogram#1251]
### tdesign-miniprogram 版本

0.30.0

### 重现步骤

就是文档上的代码，
<t-radio default-checked="{{true}}" icon="line" label="单选" />

### 期望结果

真机演示时，期望是显示正常的。

### 实际结果

但是实际的真机演示时，对号的下方不是闭口的，有间隙。

### 框架版本

小程序

**Comment by LeeJim** [comment]
可以提供下机型和系统版本么，我来调试一下

**Comment by Zlianxin** [comment]
> 
手机是mate40，harmony3.0。正常的安卓应该也行。
之后，在级联的那个组件也发现了这个问题，级联那个的对号，下面也不是闭口的。
