### ISSUE TITLE
Loading 没有默认主题色（显示为黑色）

### ISSUE THREAD

**Issue by CrossLee** [Tencent/tdesign-miniprogram#129]
**对应的组件**

Loading

**相关环境**

基础库版本：最新

运行环境：开发者工具 / iOS / Android 

**出现的问题**

Loading没有显示正确的颜色

**附加信息**

![image](https://user-images.githubusercontent.com/4584905/150055994-1af8672b-8fc9-4c0f-b462-7bc20ce81842.png)

**Comment by LeeJim** [comment]
初始样式没实现好，我来跟进下
