### ISSUE TITLE
[Button] 按钮内边距样式调整；展示demo需对照设计稿排列；部分按钮尺寸&颜色问题

### ISSUE THREAD

**Issue by pageee1021** [Tencent/tdesign-miniprogram#1291]
### tdesign-miniprogram 版本

最新版

### 重现链接

https://tdesign.tencent.com/miniprogram-live/m2w/program/miniprogram/#!pages/button/button.html

### 重现步骤

1.设计稿更新了不同尺寸下对应图标尺寸；并且调整了大按钮的内边距数值（24>20）；调整了按钮内图标与文字的间距（统一为4）。具体详见设计稿
<img width="995" alt="image" src="https://user-images.githubusercontent.com/94840745/209649533-82005971-258b-4713-ab9e-3d26296f39da.png">

另外其他尺寸实现的内边距也没有对应设计稿，麻烦对照最新设计稿一并调整下
<img width="371" alt="image" src="https://user-images.githubusercontent.com/94840745/209650660-cdf0e11d-e320-4a6c-90fb-9595e55e57e2.png">

2.demo展示设计稿已更新，更改了命名，优化了布局展示方式，请对照最新设计稿看下哈：https://codesign.qq.com/s/RG6X0kXNObZxEPB/ALwE9VKNv8O0X1D/inspect

3.缺少最小按钮28

4.light主题背景颜色有误
<img width="390" alt="image" src="https://user-images.githubusercontent.com/94840745/209650321-6f112e26-e224-41bd-b64e-ca00911afa7f.png">

**Comment by pageee1021** [comment]
@LeeJim 上述问题已确认，补充几个小问题～

1.图标按钮部分，如果需要展示加载按钮的话，能否如图展示，简洁一些
![Image](https://user-images.githubusercontent.com/94840745/210566014-34d89fb1-49b7-43e2-be55-e87a8dbc76e7.png)

另外图标按钮部分建议统一使用48的尺寸，与button demo中其他默认尺寸保持一致
![Image](https://user-images.githubusercontent.com/94840745/210566168-79951d20-262f-4f2e-b260-2529c5f65141.png)

2.按钮demo的背景色应为纯白色

3.主题中，default的填充按钮不应有描边
![Image](https://user-images.githubusercontent.com/94840745/210566416-a42566e5-3710-49bf-a330-0e697ded19d7.png)

**Comment by anlyyao** [comment]
@pageee1021  收到，已在 #1413  处理补充问题

**Comment by pageee1021** [comment]
@anlyyao 上述问题已确认无误，补充最后一个小问题~
![Image](https://user-images.githubusercontent.com/94840745/211463398-b224083e-a8c4-4745-b3b2-e61bd189a446.png)

**Comment by caixuan29** [comment]
“文字按钮”的点击态颜色错误

**Comment by anlyyao** [comment]
@caixuan29 不是 #ECF2FE  ？？？

![Image](https://user-images.githubusercontent.com/51158141/212625102-6aa7344e-dd99-40fa-89b1-21e23b7d584f.png)

**Comment by pageee1021** [comment]
@anlyyao 补充说明下，是指主题中default和error的文字按钮点击态颜色，色值为Gray1:F3F3F3，Error1:FDECEE
![Image](https://user-images.githubusercontent.com/94840745/212634590-d6a3d3c1-c958-4f05-a737-6908ff0938c5.png)
![Image](https://user-images.githubusercontent.com/94840745/212635124-ce884f10-4258-49ca-bc34-6c22fbd880b6.png)

**Comment by anlyyao** [comment]
@pageee1021 辛苦page提供一下outline四个主题激活态下的背景和边框颜色～ 我一并调整了

![Image](https://user-images.githubusercontent.com/51158141/215385422-a1276db5-261a-46c2-80b1-e43c192ef8c1.png)
