### ISSUE TITLE
[Fab] 图标加文字悬浮按钮，对应大尺寸按钮调整了样式

### ISSUE THREAD

**Issue by pageee1021** [Tencent/tdesign-miniprogram#1293]
### tdesign-miniprogram 版本

最新版

### 重现链接

https://tdesign.tencent.com/miniprogram-live/m2w/program/miniprogram/#!pages/fab/fab.html

### 重现步骤

图标加文字悬浮按钮，对应大尺寸按钮调整了图标与文字间距（8>4）以及按钮内边距（24>20）
<img width="218" alt="image" src="https://user-images.githubusercontent.com/94840745/209667566-22c2914e-d725-497c-a141-baabdf4dbd3a.png">

**Comment by anlyyao** [comment]
@LeeJim @pageee1021 该问题为button组件附带， 已在button组件进行处理～
