### ISSUE TITLE
[BackTop] 半圆形返回顶部文字样式有误

### ISSUE THREAD

**Issue by pageee1021** [Tencent/tdesign-miniprogram#1294]
### tdesign-miniprogram 版本

最新版

### 重现链接

https://tdesign.tencent.com/miniprogram-live/m2w/program/miniprogram/#!pages/back-top/back-top.html

### 重现步骤

<img width="399" alt="image" src="https://user-images.githubusercontent.com/94840745/209668050-debddff9-1965-4c73-9fb1-136a4678b59f.png">

**Comment by LeeJim** [comment]
我们这个字体的大小 10px 但 PC 的 chrome 限制了最小字体为 12 px 导致的。
可以在 chrome://settings/fonts 设置。后续考虑把在线预览的字体放大到 12px 就 OK 了

**Comment by caixuan29** [comment]
页面占位元素错位
