### ISSUE TITLE
[NavBar] 组件高度问题；占位图替换；类型问题

### ISSUE THREAD

**Issue by pageee1021** [Tencent/tdesign-miniprogram#1299]
### tdesign-miniprogram 版本

最新版

### 重现链接

https://tdesign.tencent.com/miniprogram-live/m2w/program/miniprogram/#!pages/navbar/navbar.html

### 重现步骤

1. 所有标签栏默认高度应为48px（目前为44）
2. 左侧按钮高度问题，应为32px（目前为20）
<img width="381" alt="image" src="https://user-images.githubusercontent.com/94840745/209750733-a93f9374-2186-44ef-acf9-fa9fa9e04eb5.png">
3. 带图片标签栏配图可替换下，cod及figma均已更新切图
<img width="523" alt="image" src="https://user-images.githubusercontent.com/94840745/209748171-56ca955a-5fbe-481b-9708-47a5f747a852.png">
4. 没看到大尺寸标题的类型？
<img width="294" alt="image" src="https://user-images.githubusercontent.com/94840745/209748482-426b4072-b2ba-4bae-982e-bdbb9ae5dae2.png">

**Comment by LeeJim** [comment]
大尺寸标题，不适合做到 navbar 里面，结构已经属于页面级别的了。

**Comment by pageee1021** [comment]
@LeeJim 上述问题已确认，大标题类型待讨论～另补充一个新增问题

搜索框中开始输入内容的时候，搜索框长度会变化；期望输入时搜索框保持固定宽度不变

![Image](https://user-images.githubusercontent.com/94840745/210569747-19657238-2ad4-4fb7-93f4-3e51ceeb33b5.png)
![Image](https://user-images.githubusercontent.com/94840745/210569787-c9f9cccb-9fff-4f44-acda-f0e468a649b4.png)

**Comment by caixuan29** [comment]
1、基础小程序导航栏左侧胶囊按钮缺少上面的border


![Image](https://user-images.githubusercontent.com/96420688/212625044-bab312e6-32ae-400f-9285-80d33ba0560e.png)



2、自定义颜色没有变更展示颜色


![Image](https://user-images.githubusercontent.com/96420688/212625088-6d23391e-c446-40bc-9cb2-b8b80260d9cf.png)
