### ISSUE TITLE
[NoticeBar] icon换成面性的

### ISSUE THREAD

**Issue by Jayclelon** [Tencent/tdesign-miniprogram#1302]
### tdesign-miniprogram 版本

最新版

### 重现链接

https://tdesign.tencent.com/miniprogram-live/m2w/program/miniprogram/#!pages/notice-bar/notice-bar.html

### 重现步骤

<img width="488" alt="企业微信截图_61a16f34-ed20-4fc1-a0ab-2ee2aa3add18" src="https://user-images.githubusercontent.com/104408991/209752245-0e89ea7f-3eee-402e-a556-8949d68e4eff.png">

icon麻烦换成面性的

**Comment by anlyyao** [comment]
@Jayclelon  视觉稿中也存在使用非面性图标，而且sound图标目前还没有对应面性的，这个sound图标主要用于demo展示，非组件内置图标，是否可以保留？

**Comment by Jayclelon** [comment]
> @Jayclelon 视觉稿中也存在使用非面性图标，而且sound图标目前还没有对应面性的，这个sound图标主要用于demo展示，非组件内置图标，是否可以保留？

好的那先关闭这条吧谢谢～
