### ISSUE TITLE
[Drawer] 底部插槽位置问题；类型问题

### ISSUE THREAD

**Issue by pageee1021** [Tencent/tdesign-miniprogram#1304]
### tdesign-miniprogram 版本

最新版

### 重现链接

https://tdesign.tencent.com/miniprogram-live/m2w/program/miniprogram/#!pages/drawer/drawer.html

### 重现步骤

1.底部插槽位置贴底了，缺少底部间距
<img width="435" alt="image" src="https://user-images.githubusercontent.com/94840745/209755458-e4aa3277-3397-493d-9a00-d833fbc27f4c.png">

2.带图标抽屉缺少按钮入口
<img width="410" alt="image" src="https://user-images.githubusercontent.com/94840745/209755505-4d224702-7318-45f5-8333-492765223558.png">

3.缺少大标题&右侧出现的类型？

**Comment by LeeJim** [comment]
标题位置是自定义内容，没有内置大标题这样的 api，因此就不展示这样的类型。
左右位置也是比较简单的 API 替换，过于简单就不展示对应的示例了。

**Comment by caixuan29** [comment]
1、带操作时的滚动区域范围问题


![Image](https://user-images.githubusercontent.com/96420688/212624184-85a326fa-6761-4057-aa0a-2d7563a4a6b5.png)


2、实机体验时，背景滚动没有ban掉
