### ISSUE TITLE
[Sidebar] 字号、间距、类型问题

### ISSUE THREAD

**Issue by pageee1021** [Tencent/tdesign-miniprogram#1305]
### tdesign-miniprogram 版本

最新版

### 重现链接

https://tdesign.tencent.com/miniprogram-live/m2w/program/miniprogram/#!pages/side-bar/side-bar.html

### 重现步骤

1. 选项应该允许文本换行展示（可参考最新figma文件中的布局方式）
<img width="157" alt="image" src="https://user-images.githubusercontent.com/94840745/209757422-d9a7f019-6b50-4a20-952c-9256b57a1cde.png">

2.锚点展示切换时，标题顶边了
<img width="395" alt="image" src="https://user-images.githubusercontent.com/94840745/209757667-bf7357ca-a3be-40b5-a405-b04ff551a02f.png">

3.占位素材可以参照设计稿，更换为品牌素材
Figma：https://www.figma.com/file/pc6iUYkkyHgfelIRoFdRl0/TDesign-for-mobile-new-version?node-id=24891%3A18510&t=ucLePyP0lykJZ0fp-4
CoD：https://codesign.qq.com/s/RG6X0kXNObZxEPB/2kY5j3A3o3k0ExN/inspect

4.demo中的按钮高度有误
<img width="396" alt="image" src="https://user-images.githubusercontent.com/94840745/209757707-62ba49bf-646e-4ae9-8155-5ab0b150cdac.png">

5.设计稿新增了一种非通栏的选项样式类型
<img width="379" alt="image" src="https://user-images.githubusercontent.com/94840745/209759113-47c93369-306c-47da-8a0b-6198263c1bda.png">

6.如果要表现可自定义颜色，可以在demo中新增一种展示（目前的类型直接点进去发现选中颜色和圆角不一样，有点怪）
<img width="437" alt="image" src="https://user-images.githubusercontent.com/94840745/209759383-093ed343-a2bd-4663-ba7a-111f8378e52b.png">

**Comment by LeeJim** [comment]
这里不建议加一个状态的示例，
因为只有一个禁用态，不需要单独拉出一个示例，可以混在其他示例里

**Comment by LeeJim** [comment]
非通栏的选项样式
这个样式优先级放低一些，后面再实现。
辛苦 page 记录一下～

**Comment by pageee1021** [comment]
@LeeJim 上述问题已确认无误，非通栏选项样式后续再实现没问题的，另再补充一个问题：

1、切页用法能否按照设计稿使用带图片的单元格，展示效果更好~
![Image](https://user-images.githubusercontent.com/94840745/211464682-d25f47d0-b090-48c0-bc75-d8782712bee8.png)

2、建议禁用选项放在最后一个，也比较符合真实场景（禁用选项通常后置）
![Image](https://user-images.githubusercontent.com/94840745/211464773-bf8710b7-3006-447a-8219-244b7efb0850.png)

**Comment by anlyyao** [comment]
@pageee1021  sidebar 也可以重新验收了～

**Comment by caixuan29** [comment]
实机体验时，打开会默认定位到了第二个bar，往下滑动时定位会先回到第一个bar
