### ISSUE TITLE
[PullDownRefresh] 圆角、对齐、文字内容

### ISSUE THREAD

**Issue by Jayclelon** [Tencent/tdesign-miniprogram#1307]
### tdesign-miniprogram 版本

最新版

### 重现链接

https://tdesign.tencent.com/miniprogram-live/m2w/program/miniprogram/#!pages/pull-down-refresh/pull-down-refresh.html

### 重现步骤

详情见图
<img width="822" alt="image" src="https://user-images.githubusercontent.com/104408991/209767784-ce2f11fb-f269-41fc-80cf-fa66d95f0201.png">

**Comment by Jayclelon** [comment]
底部不需要遮罩


![Image](https://user-images.githubusercontent.com/104408991/210500526-c9e2f365-189e-481b-b11a-7927d2d1a8c7.png)

**Comment by anlyyao** [comment]
@Jayclelon 我这边没能复现遮挡问题，辛苦在确认一下问题~ 
真机（13pro）效果：
![WechatIMG92](https://user-images.githubusercontent.com/51158141/210740673-81d2d039-1ce0-4ab9-9b37-8b61e37b2864.jpeg)


官网效果：
<img width="402" alt="截屏2023-01-05 16 58 38" src="https://user-images.githubusercontent.com/51158141/210741025-976b708c-891e-4261-98fa-d0e967c7a94c.png">

**Comment by anlyyao** [comment]
@Jayclelon  这里也是预览二维码没更新的问题～
