### ISSUE TITLE
[Tag] 间距、“可点击标签”需要更改文字

### ISSUE THREAD

**Issue by Jayclelon** [Tencent/tdesign-miniprogram#1308]
### tdesign-miniprogram 版本

最新版

### 重现链接

https://tdesign.tencent.com/miniprogram-live/m2w/program/miniprogram/#!pages/tag/tag.html

### 重现步骤

详情见图
<img width="640" alt="image" src="https://user-images.githubusercontent.com/104408991/209768759-4f85e10b-1b74-41e5-8c8c-d1e582ba5f52.png">

**Comment by caixuan29** [comment]
demo展示还原有问题


![Image](https://user-images.githubusercontent.com/96420688/212630509-3e3d0d34-2e4b-4edd-bc30-0b1a3346af0d.png)
