### ISSUE TITLE
[Steps] 对齐问题

### ISSUE THREAD

**Issue by pageee1021** [Tencent/tdesign-miniprogram#1309]
### tdesign-miniprogram 版本

最新版

### 重现步骤

1. 纵向步骤条线条未居中
<img width="407" alt="image" src="https://user-images.githubusercontent.com/94840745/209768420-7d21b025-00cf-4492-a948-b214bbdf52db.png">
<img width="400" alt="image" src="https://user-images.githubusercontent.com/94840745/209768581-71b52469-7f95-4337-a7ff-64d165ca6c46.png">

2.替换占位图，CoD设计稿已上传切图
https://codesign.qq.com/s/RG6X0kXNObZxEPB/5l429l7Ve2ejdYD/inspect
<img width="417" alt="image" src="https://user-images.githubusercontent.com/94840745/209768802-1e039782-d376-40f6-a6aa-fc723efe56eb.png">

**Comment by pageee1021** [comment]
@LeeJim 上述问题已确认~另新增一个小问题

此处引用的按钮貌似样式没有与按钮组件保持一致？可以应用40高度默认的按钮（目前这个按钮高度42，字号为17，偏大了）
![Image](https://user-images.githubusercontent.com/94840745/210570814-151c8ccb-4785-4aec-96e3-49724ff10b05.png)

**Comment by LeeJim** [comment]
引用的是 button，应该是 button 本身的问题，我看已经修复了
