### ISSUE TITLE
[TabBar] 高度、对齐问题

### ISSUE THREAD

**Issue by pageee1021** [Tencent/tdesign-miniprogram#1311]
### tdesign-miniprogram 版本

最新版

### 重现链接

https://tdesign.tencent.com/miniprogram-live/m2w/program/miniprogram/#!pages/tab-bar/tab-bar.html

### 重现步骤

1. 图标带文字标签栏，实际位置需要对照设计稿稍作调整，肉眼上看才是视觉对齐的~（目前肉眼看偏上了）
<img width="709" alt="image" src="https://user-images.githubusercontent.com/94840745/209772631-399ba3d2-0cb7-4674-beb4-2afa73b63819.png">
设计稿实际位置：
<img width="929" alt="image" src="https://user-images.githubusercontent.com/94840745/209772563-dac3a755-bf7b-4c23-b392-e983819ad929.png">

2.文字10px对应的行高应该为16px（现在是18）

3.所有底部标签栏高度均为56px，目前纯文字的高度有误

4.标签栏选项文本可以全部统一，如下
<img width="376" alt="image" src="https://user-images.githubusercontent.com/94840745/209773082-e7bfce97-ceb5-4b3e-8ad7-9713a71bcbab.png">

5.自定义样式的分割线建议使用Grey3分割线色，更美观~
<img width="426" alt="image" src="https://user-images.githubusercontent.com/94840745/209773348-cba550c9-62ac-410a-b774-364140f2d39b.png">

**Comment by LeeJim** [comment]
1 是因为小程序限制，无法判断label和icon是否同时存在，因此都统一垂直居中处理了。
其他已修复
