### ISSUE TITLE
[Tabs] 文案、demo展示、分割线等问题

### ISSUE THREAD

**Issue by pageee1021** [Tencent/tdesign-miniprogram#1312]
### tdesign-miniprogram 版本

最新版

### 重现链接

https://tdesign.tencent.com/miniprogram-live/m2w/program/miniprogram/#!pages/tabs/tabs.html

### 重现步骤

1. 展示的类型和方式没有对应最新设计稿，麻烦对应设计稿展示哈
（包括展示的类型、去掉竖向的样式等等，以设计稿为准）

2. tabs上文案保持统一为【选项】，特殊的另外描述，具体请以设计稿为准

3.初始状态下第一个选中条歪了
<img width="386" alt="image" src="https://user-images.githubusercontent.com/94840745/209775670-210771c6-6032-4736-b587-81402f9353d2.png">

4.文案问题
<img width="382" alt="image" src="https://user-images.githubusercontent.com/94840745/209775833-ae37dcb7-18ef-4b63-a917-267999b9f811.png">

5.卡片样式不需要底部分割线
<img width="435" alt="image" src="https://user-images.githubusercontent.com/94840745/209777193-70780f90-8aa2-409c-b6a2-6ff10d43863d.png">

6.选项超出一行时，中间部分的选项希望做一个保持在中间显示的定位
<img width="383" alt="image" src="https://user-images.githubusercontent.com/94840745/209777305-2207b010-8bf2-4d96-8bf7-2dbd3fdc2df8.png">

**Comment by LeeJim** [comment]
第一点是官网的问题，在实机没有这个问题

**Comment by pageee1021** [comment]
@LeeJim 其他问题确认无误，补充一个小问题~

此处带内容区选项卡的文案，是否可以用选项+序号的描述，与其他描述保持一致
![Image](https://user-images.githubusercontent.com/94840745/210797247-d7b78b6c-05ec-4edb-a753-8faa3be0cda1.png)

**Comment by caixuan29** [comment]
线段样式的选中条跟分割线有一小部分重合


![Image](https://user-images.githubusercontent.com/96420688/212625636-62d7e80f-b37f-409d-a00d-cf471a318200.png)
