### ISSUE TITLE
[Swiper] 圆角、间距问题

### ISSUE THREAD

**Issue by Jayclelon** [Tencent/tdesign-miniprogram#1315]
### tdesign-miniprogram 版本

最新版

### 重现链接

https://tdesign.tencent.com/miniprogram-live/m2w/program/miniprogram/#!pages/swiper/swiper.html

### 重现步骤

详情见图

<img width="982" alt="image" src="https://user-images.githubusercontent.com/104408991/209809093-86a2bfbe-3d87-4969-a2c7-5b161b4b2537.png">

**Comment by Jayclelon** [comment]
圆角消失啦，麻烦再看看

**Comment by Jayclelon** [comment]
第一个点状的轮播图，还是没有圆角～

**Comment by caixuan29** [comment]
1、替换品牌素材图
2、图片被压缩变形
3、第一个轮播图没有圆角
