### ISSUE TITLE
[Skeleton] 间距问题

### ISSUE THREAD

**Issue by Jayclelon** [Tencent/tdesign-miniprogram#1316]
### tdesign-miniprogram 版本

最新版

### 重现链接

https://tdesign.tencent.com/miniprogram-live/m2w/program/miniprogram/#!pages/skeleton/skeleton.html

### 重现步骤

组与组之间的间距应为24

<img width="444" alt="image" src="https://user-images.githubusercontent.com/104408991/209809593-ee8d4dee-0ff1-4315-a2bb-a45e695bb6fc.png">

**Comment by anlyyao** [comment]
@Jayclelon 这里已经顺带处理了， 处理后效果如下：
<img width="374" alt="企业微信截图_fb376537-119a-4ccb-9b62-0f4156f700b1" src="https://user-images.githubusercontent.com/51158141/209904065-44ac40f2-ca06-4d47-b113-f4163bee7a13.png">
