### ISSUE TITLE
[Result] 间距、文字问题

### ISSUE THREAD

**Issue by Jayclelon** [Tencent/tdesign-miniprogram#1318]
### tdesign-miniprogram 版本

最新版

### 重现链接

https://tdesign.tencent.com/miniprogram-live/m2w/program/miniprogram/#!pages/result/result.html

### 重现步骤

1. 不要序号，文字改为「组件类型」
<img width="457" alt="image" src="https://user-images.githubusercontent.com/104408991/209810029-4a208fe6-68f0-4392-86ac-8801a6c7045b.png">

2. 应该面性图形居中对齐
<img width="438" alt="企业微信截图_457daa65-8a75-4bb5-a2da-fd101aa9bd2d" src="https://user-images.githubusercontent.com/104408991/209810235-64fbe56e-6e35-45ac-b1c4-2f0114ccbb87.png">

**Comment by anlyyao** [comment]
@Jayclelon 第二个点需要确认一下，因为事实上目前的效果就是图片文字居中对齐。
视觉稿如下，图片右对齐，下方的文字左对齐，需要完全对齐视觉吗？
<img width="444" alt="截屏2022-12-29 10 35 08" src="https://user-images.githubusercontent.com/51158141/209895881-3bb84439-7423-44f9-bfe0-75c4389650ff.png">

**Comment by Jayclelon** [comment]
预览

**Comment by Jayclelon** [comment]
自定义结果的切图麻烦换一下哈

**Comment by anlyyao** [comment]
@Jayclelon 已更新占位图片，辛苦重新验收确认～

**Comment by Jayclelon** [comment]
突然发现介绍的文字不对哈哈，麻烦再更新下“用于反馈不同结果的展示。”


![Image](https://user-images.githubusercontent.com/104408991/211454549-bf66afc9-446e-43bf-aca8-0819dd1b6216.png)

**Comment by anlyyao** [comment]
补充问题在 #1474 修复
