### ISSUE TITLE
[Cascader] 间距、分割线、弹窗字号等问题

### ISSUE THREAD

**Issue by pageee1021** [Tencent/tdesign-miniprogram#1322]
### tdesign-miniprogram 版本

最新版

### 重现链接

https://tdesign.tencent.com/miniprogram-live/m2w/program/miniprogram/#!pages/cascader/cascader.html

### 重现步骤

1. 此处距离略小，应为16px
<img width="390" alt="image" src="https://user-images.githubusercontent.com/94840745/209815669-e825b016-6e6d-4591-a484-dd87a7da7c6c.png">

2.分割线设计稿样式更新，改为0.5px粗细
<img width="397" alt="image" src="https://user-images.githubusercontent.com/94840745/209815883-b2cc2a06-d28b-4e60-a1f3-9de824052965.png">

3.弹窗标题应为字号18px，行高26px

4.弹窗拉起时，背景是否不应滚动？
<img width="448" alt="image" src="https://user-images.githubusercontent.com/94840745/209816014-f31e7a5b-d304-436d-a1a0-8c10dbd43003.png">

5.再次打开弹窗时，列表应该自动定位显示当前的选中项
<img width="411" alt="image" src="https://user-images.githubusercontent.com/94840745/209816207-6e57d8c2-7c1c-47ab-af1d-9a41dc19ff51.png">
<img width="436" alt="image" src="https://user-images.githubusercontent.com/94840745/209816330-accc8ede-01e8-44c9-b5b5-af3f00c45b9e.png">

**Comment by LeeJim** [comment]
4 是因为你用的是滚动，实际情况在手机上是触摸滑动，已禁止
