### ISSUE TITLE
[Checkbox] 组件高度问题；另横向多选的布局规则辛苦确认下

### ISSUE THREAD

**Issue by pageee1021** [Tencent/tdesign-miniprogram#1323]
### tdesign-miniprogram 版本

最新版

### 重现链接

https://tdesign.tencent.com/miniprogram-live/m2w/program/miniprogram/#!pages/checkbox/checkbox.html

### 重现步骤

1.横向多选高度应为56px，且选项未居中
<img width="413" alt="image" src="https://user-images.githubusercontent.com/94840745/209817215-6b677923-e7e9-487b-be0a-1186f883e176.png">

2.横向多选时，需要确认下是否有实现不同个数时的布局规则：

大于等于3个时，两边留出16px内边距后，剩下的内容根据选项长度均分排列
<img width="1075" alt="企业微信截图_a0397334-35a5-4766-942c-9b66a59ed0f5" src="https://user-images.githubusercontent.com/94840745/209817674-d84f06c7-cc1c-4e9b-b3c2-d8c9bb3539b8.png">

仅有两个时，均分宽度效果不是很好，所以两个的时候划分了两块区域，保持16px等间距，内容左对齐
<img width="841" alt="企业微信截图_534e507c-9fd6-45b7-a2f0-482f7d7c4b44" src="https://user-images.githubusercontent.com/94840745/209817747-af097b9b-d05c-4d7b-bfe0-a1d1ee849fad.png">

**Comment by caixuan29** [comment]
特殊样式小卡片中间那个圆角有问题


![Image](https://user-images.githubusercontent.com/96420688/212626204-895b86a6-1a6f-44e8-ba72-82c456f505bb.png)
