### ISSUE TITLE
[Input] demo展示类型、元素尺寸问题

### ISSUE THREAD

**Issue by pageee1021** [Tencent/tdesign-miniprogram#1329]
### tdesign-miniprogram 版本

最新版

### 重现链接

https://tdesign.tencent.com/miniprogram-live/m2w/program/miniprogram/#!pages/input/input.html

### 重现步骤

1.根据现有内容调整了demo展示的类型，请尽可能的参照设计稿来（包括是否有标题等等），让demo看起来更规整
https://codesign.qq.com/s/RG6X0kXNObZxEPB/Yyg5Zp24KkD92lK/inspect

（1）不可编辑请参照设计稿放到02组件状态中
<img width="413" alt="image" src="https://user-images.githubusercontent.com/94840745/209900403-3a2f1098-c6ed-4ac7-9b31-12728115725b.png">
（2）新增字符限制的展示，可以用这种带描述的类型展示限制
<img width="519" alt="image" src="https://user-images.githubusercontent.com/94840745/209903445-bf74600e-9da0-4656-b68d-cc2a0bcf6ef3.png">
（3）03组件样式部分调整
<img width="390" alt="image" src="https://user-images.githubusercontent.com/94840745/209903672-079a4451-2767-4057-9187-7ada93452d61.png">

2.所有标题文案以设计稿为准，全部为【输入框】

3.此类型加上标签；按钮样式尺寸有误
<img width="393" alt="image" src="https://user-images.githubusercontent.com/94840745/209900339-554db59b-07dd-4117-8f13-ea20015cac52.png">

4.所有输入框缺少分割线
<img width="900" alt="image" src="https://user-images.githubusercontent.com/94840745/209903846-6ee1d0fd-a54c-484c-bff6-69d2f9489aa6.png">

**Comment by pageee1021** [comment]
上述问题已确认，另补充几个问题：

1、所有分割线粗细应为0.5px（现在是1px哈）请统一检查处理下
![Image](https://user-images.githubusercontent.com/94840745/211465198-9d74e214-9476-4e4f-a347-a78c724f1ec9.png)

2、标签外置样式请以设计稿为准，目前缺少了背景以及输入框的标签（另这种样式是没有底部分割线的，麻烦去掉）
![Image](https://user-images.githubusercontent.com/94840745/211465324-2f1df084-fa8d-4808-9f30-8ba0c4e6557a.png)
![Image](https://user-images.githubusercontent.com/94840745/211465480-95169d10-54f6-459f-9c23-ec169e569542.png)

**Comment by anlyyao** [comment]
补充问题在 #1474  修复

**Comment by caixuan29** [comment]
1、带输入按钮的行高和文字错位


![Image](https://user-images.githubusercontent.com/96420688/212626894-d0dd25a3-7a7e-44fc-ba0e-4da3cfec462e.png)


2、数量和价格的输入框，填写时应该限制只能输入数字，且默认拉起数字键盘


![Image](https://user-images.githubusercontent.com/96420688/212626946-c60e2562-3667-4de7-99d7-bab920c2c97e.png)
