### ISSUE TITLE
[Radio] 辛苦确认水平多选中的布局规则

### ISSUE THREAD

**Issue by pageee1021** [Tencent/tdesign-miniprogram#1330]
### tdesign-miniprogram 版本

最新版

### 重现链接

https://tdesign.tencent.com/miniprogram-live/m2w/program/miniprogram/#!pages/radio/radio.html

### 重现步骤

水平多选时，需要确认下是否有实现不同个数时的布局规则：

大于等于3个时，两边留出16px内边距后，剩下的内容根据选项长度均分排列
![image](https://user-images.githubusercontent.com/94840745/209919852-b71d7035-4a7e-40ba-bfb4-b663dd033317.png)

仅有两个时，均分宽度效果不是很好，所以两个的时候划分了两块区域，保持16px等间距，内容左对齐
![image](https://user-images.githubusercontent.com/94840745/209919866-cc19fe49-b3d6-41bf-a019-a28f23fa56dd.png)

**Comment by LeeJim** [comment]
水平布局的时候，样式随用户控制的了，没有内置样式了

**Comment by caixuan29** [comment]
特殊样式小卡片中间那个圆角有问题


![Image](https://user-images.githubusercontent.com/96420688/212626204-895b86a6-1a6f-44e8-ba72-82c456f505bb.png)
