### ISSUE TITLE
[Demo] 设计稿中间距规则统一

### ISSUE THREAD

**Issue by pageee1021** [Tencent/tdesign-miniprogram#1331]
### tdesign-miniprogram 版本

最新版

### 重现步骤

统一说明下Demo间距规则：
1、一级模块为大类的内容分类，模块间间距为32px（一级标题前）
2、二级模块为具体组件的类型，模块间间距为24px（二级标题前）
3、二级模块内所有元素间距为16px

![image](https://user-images.githubusercontent.com/94840745/209915424-c3a7134e-ffa2-49be-9b14-fd2dac837ba9.png)

**Comment by anlyyao** [comment]
@pageee1021 已经按照视觉稿统一处理了，官网还没更新。目前的效果如下：

<img width="393" alt="企业微信截图_71906530-07c4-4195-a5a3-a2060b5b3826" src="https://user-images.githubusercontent.com/51158141/209917401-ddc1509b-cd1d-4645-8242-5598b55bd635.png">

**Comment by anlyyao** [comment]
@pageee1021 官网已更新，辛苦重新验收确认～
