### ISSUE TITLE
[Tabs 选项卡] 希望新增支持icon功能

### ISSUE THREAD

**Issue by suleilei** [Tencent/tdesign-miniprogram#1332]
### 这个功能解决了什么问题

Tabs 在项目展示分类上非常实用，期待加入icon功能，加入icon可以让使用者轻松的分辨选项卡。如果只提供一排排文字，会减少用户操作意愿，期待TD团队的采纳（如果可以小程序端先哦），谢谢。
![2022-12-21 00 14 53](https://user-images.githubusercontent.com/37729616/209916260-f7b1f5fe-7da2-4b9b-9bdb-32593e00752e.gif)

### 你建议的方案是什么

在Tabs 选项卡Theme属性line/tag/card增加icon 类型，有支持传人 t-icon 属性的支持，主要是prefix 和 icon name。

**Comment by LeeJim** [comment]
感谢反馈，我们这边研究下

**Comment by suleilei** [comment]
新版本可以传入icon 了，感谢TDesign 团队
