### ISSUE TITLE
[Rate] 星星间距、样式、组件文案问题

### ISSUE THREAD

**Issue by pageee1021** [Tencent/tdesign-miniprogram#1334]
### tdesign-miniprogram 版本

最新版

### 重现链接

https://tdesign.tencent.com/miniprogram-live/m2w/program/miniprogram/#!pages/rate/rate.html

### 重现步骤

1、星星图标之间的间距为8px

2、组件文案可以依照设计稿，统一在组件中使用当前类型的描述；避免有的是描述，有的是【请评分】哈
<img width="389" alt="image" src="https://user-images.githubusercontent.com/94840745/209917895-9b2cbd7a-3f22-4f76-b755-40b482721367.png">
<img width="434" alt="image" src="https://user-images.githubusercontent.com/94840745/209917921-72a0f67e-da36-40ac-a853-bfcd6a1cf1fa.png">

3、此处星星为实星样式
<img width="388" alt="image" src="https://user-images.githubusercontent.com/94840745/209917993-dbb270c3-8329-421c-90bf-c37745dc2c7b.png">

4、仅展示的样式看起来区分不大，是不是用默认橙色做仅展示也可以？不允许点击就行
<img width="389" alt="image" src="https://user-images.githubusercontent.com/94840745/209918123-d6975fac-c134-427e-8783-b5005c6d751a.png">

**Comment by pageee1021** [comment]
上述问题已确认，补充一个问题：

交互展示部分，滑动交互需要默认展示带半星的交互
![Image](https://user-images.githubusercontent.com/94840745/211257286-1565c2ce-92ae-43f7-9688-54f4e5bd5609.png)
设计稿有示意
![Image](https://user-images.githubusercontent.com/94840745/211256969-2b1cc2e7-dac8-452f-8c20-c58dc4dcb964.png)

**Comment by pageee1021** [comment]
上述问题已确认无误~发现一个之前没有出现的新问题，特殊样式中星星间距丢失
![Image](https://user-images.githubusercontent.com/94840745/212026434-729d5153-c89b-4c71-8307-4c79b05a120c.png)

**Comment by caixuan29** [comment]
实机体验时，第一次滑动到最后时，上面的星星数指示的框无法自动消失


![Image](https://user-images.githubusercontent.com/96420688/212627513-e2e99896-8874-4a20-8241-86c065602b24.png)
