### ISSUE TITLE
[Search] demo中类型展示缺少二级标题

### ISSUE THREAD

**Issue by pageee1021** [Tencent/tdesign-miniprogram#1335]
### tdesign-miniprogram 版本

最新版

### 重现链接

https://tdesign.tencent.com/miniprogram-live/m2w/program/miniprogram/#!pages/search/search.html

### 重现步骤

<img width="899" alt="image" src="https://user-images.githubusercontent.com/94840745/209918803-b5442be6-dc04-40b8-a275-f064e0347951.png">

**Comment by pageee1021** [comment]
上述问题已确认，补充一个关于交互状态的问题：
所有搜索框组件的交互状态都是保持一致的，如下图（即输入框激活时都会出现右边的取消按钮）
![Image](https://user-images.githubusercontent.com/94840745/211503155-cf27fcbb-a468-4720-808e-a02749bcaed2.png)

**Comment by LeeJim** [comment]
其实激活才出现这样的交互是不合理的。因为一旦点击取消，不管取消有任何操作都会直接消失，因为此时input不是激活状态了。

因此，此处的 取消按钮 是通过配置了对应的属性才出现的。

**Comment by pageee1021** [comment]
已沟通，取消可以作为可配置项，但是取消的交互还是期望可以激活输入框才出现（不建议常驻使用），因此demo需要对应调整下展示：
![Image](https://user-images.githubusercontent.com/94840745/212027905-5d609975-0d7e-4ae0-86ee-c89afb0be319.png)

状态部分展示可以参考AntD的前两个交互的展示：https://mobile.ant.design/zh/components/search-bar
