### ISSUE TITLE
[Stepper] 禁用态背景色问题、操作联动问题

### ISSUE THREAD

**Issue by pageee1021** [Tencent/tdesign-miniprogram#1337]
### tdesign-miniprogram 版本

最新版

### 重现链接

https://tdesign.tencent.com/miniprogram-live/m2w/program/miniprogram/#!pages/stepper/stepper.html

### 重现步骤

1、禁用背景色有误
<img width="387" alt="image" src="https://user-images.githubusercontent.com/94840745/209923747-170ec457-1d55-4894-8321-969278a1c515.png">

2、最大尺寸的操作联动了
<img width="385" alt="image" src="https://user-images.githubusercontent.com/94840745/209923810-c604f10e-6351-4a88-946f-b2b017feae7f.png">

**Comment by pageee1021** [comment]
以上问题已确认无误，补充一个小问题：
![Image](https://user-images.githubusercontent.com/94840745/211502322-c4d1fc66-a3bd-408e-9886-857e61d11fba.png)

**Comment by anlyyao** [comment]
我这边继续跟进～

**Comment by caixuan29** [comment]
点击热区是否可以再大一点
