### ISSUE TITLE
[Slider] 滑块对齐问题

### ISSUE THREAD

**Issue by pageee1021** [Tencent/tdesign-miniprogram#1338]
### tdesign-miniprogram 版本

最新版

### 重现链接

https://tdesign.tencent.com/miniprogram-live/m2w/program/miniprogram/#!pages/slider/slider.html

### 重现步骤

带刻度时，头尾节点都带有刻度，且能否让操作滑块与刻度居中对齐？
<img width="387" alt="image" src="https://user-images.githubusercontent.com/94840745/209926374-81471d0f-1001-46d5-a443-5aa17f50754b.png">
<img width="387" alt="image" src="https://user-images.githubusercontent.com/94840745/209926350-fe6c4648-cdc8-4ed3-aedf-24db852d168c.png">

**Comment by pageee1021** [comment]
上述问题已确认，补充一个遗留问题~

所有文字应遵循token，使用@font-size-bodyMedium:14px，对应行高应为22px（目前行高不准确）

**Comment by LeeJim** [comment]
在只有单行文字的时候，行高可以忽略，只要视觉对齐就OK了

**Comment by caixuan29** [comment]
操作点的热区有点不好点，是否能再加大一点
