### ISSUE TITLE
[Textarea] 默认样式用横排的标签；demo展示请对照设计稿

### ISSUE THREAD

**Issue by pageee1021** [Tencent/tdesign-miniprogram#1341]
### tdesign-miniprogram 版本

最新版

### 重现步骤

1、为了方便用户把多行文本框和我们的输入框拼接使用，麻烦参照下设计稿，默认情况下提供横排标签的样式
<img width="965" alt="image" src="https://user-images.githubusercontent.com/94840745/209929497-9be6eed2-d773-4010-bedb-28dabfa492f6.png">
标签竖排是作为一种样式选择，放在组件样式里
<img width="411" alt="image" src="https://user-images.githubusercontent.com/94840745/209929574-2d18d8f6-bf51-44cc-9dad-6270236caed6.png">

2、带字数限制的类型，不用重复展示描述，看着信息比较冗杂
<img width="403" alt="image" src="https://user-images.githubusercontent.com/94840745/209929724-0deef51c-9e0b-4234-bceb-d83b4da0ef95.png">

3、标题文案修改
<img width="384" alt="image" src="https://user-images.githubusercontent.com/94840745/209929787-6741131e-009f-4c5e-8757-ac50aead2eb2.png">

4、缺少非通栏卡片样式
<img width="423" alt="image" src="https://user-images.githubusercontent.com/94840745/209930066-985cb08f-050e-4648-8217-a1edd18b1d02.png">

**Comment by anlyyao** [comment]
@pageee1021  小程序原生的textarea组件placeholder不支持自定义行高，横排布局label和placeholder行高不一致会出现如下：
<img width="383" alt="企业微信截图_c92f2a36-1c92-49e6-b73c-18506a7d1286" src="https://user-images.githubusercontent.com/51158141/210035839-15aff78e-c923-477e-b64b-39a0023030f6.png">

讨论下看怎么处理？？

这里有一条建议是，横向布局时候，label垂直居中？效果如下：
<img width="404" alt="截屏2022-12-30 12 56 42" src="https://user-images.githubusercontent.com/51158141/210036001-e26ff265-5dfe-4543-8839-f2153c844289.png">

**Comment by pageee1021** [comment]
@anlyyao 第一点已沟通，其他问题确认无误，另补充两个小问题：

1.发现所有Textarea中预设文字的位置和已输入内容的起点位置不一样，预设文字位置更靠上
![Image](https://user-images.githubusercontent.com/94840745/210799878-66f1f1da-aefd-4324-bbe2-03d4bd1c3c70.png)

2.内容自动增高时，是否自然向下延伸高度，不应有首行文字切到的效果？
![Image](https://user-images.githubusercontent.com/94840745/210800121-19d3e1ec-6b72-4373-b327-4989b5c2db40.png)

**Comment by anlyyao** [comment]
@pageee1021  补充问题1和补充问题2均属于小程序原生textarea组件问题，问题1出现原因仍然是 placeholder 行高不能自定义。

详细说明：补充问题1出现在「安卓真机」、「模拟器，「iOS真机」正常；补充问题2出现在「模拟器」，「安卓真机」和「iOS真机」正常
