### ISSUE TITLE
[Link] 基础文字链接颜色样式为黑色

### ISSUE THREAD

**Issue by pageee1021** [Tencent/tdesign-miniprogram#1343]
### tdesign-miniprogram 版本

最新版

### 重现链接

https://tdesign.tencent.com/miniprogram-live/m2w/program/miniprogram/#!pages/link/link.html

### 重现步骤

<img width="372" alt="image" src="https://user-images.githubusercontent.com/94840745/209931443-2c2ba4d4-f85b-44a0-8368-74625cbd3a6b.png">

**Comment by caixuan29** [comment]
需新增link的点击反馈样式

**Comment by alhaidarykhalid** [comment]
Khalid
