### ISSUE TITLE
[Indexes] 吸顶样式问题；索引贴住了页面边缘；缺少类型

### ISSUE THREAD

**Issue by pageee1021** [Tencent/tdesign-miniprogram#1344]
### tdesign-miniprogram 版本

最新版

### 重现链接

https://tdesign.tencent.com/miniprogram-live/m2w/program/miniprogram/#!pages/indexes/base/index.html

### 重现步骤

1、吸顶背景颜色为白色，右侧应有8px间距
<img width="417" alt="image" src="https://user-images.githubusercontent.com/94840745/209931999-bb9c0042-0d5b-4466-9959-e8b4e6f0cbb8.png">
<img width="529" alt="image" src="https://user-images.githubusercontent.com/94840745/209932243-6ac76f98-c258-4a4a-81ef-fa6e58831a2b.png">

2、缺少胶囊样式
<img width="790" alt="image" src="https://user-images.githubusercontent.com/94840745/209932277-f40cd40f-6161-444a-85a7-ca4aaae71280.png">

**Comment by pageee1021** [comment]
补充几个问题：

1、demo展示的类型能否准确对应设计稿展示？

2、胶囊样式未对齐设计稿，具体问题见图
![Image](https://user-images.githubusercontent.com/94840745/211462882-97c4b033-bb6c-4af7-8f47-066be9d6692a.png)

**Comment by LeeJim** [comment]
1 数字索引是多余的，因为索引内容是自定义的，不需要纯粹区分字母和数字。所以改成了 基础用法

**Comment by caixuan29** [comment]
1、【通用问题】单元格最下面一个不应该有分割线

2、下图单元格间距样式问题


![Image](https://user-images.githubusercontent.com/96420688/212624739-cf5178d1-ee17-4bd5-bb7f-a5232fefd71c.png)
