### ISSUE TITLE
[ActionSheet] 列表高度问题、宫格型填入预设场景

### ISSUE THREAD

**Issue by pageee1021** [Tencent/tdesign-miniprogram#1346]
### tdesign-miniprogram 版本

最新版

### 重现链接

https://tdesign.tencent.com/miniprogram-live/m2w/program/miniprogram/#!pages/action-sheet/action-sheet.html

### 重现步骤

1、列表型高度为56px一行
<img width="390" alt="image" src="https://user-images.githubusercontent.com/94840745/209934645-a66d74da-4f26-44f2-a8b8-db2f377f6b28.png">

2、宫格型缺少部分展示类型（如带描述、多行滚动等），且宫格型可以依照设计稿，填入常见的预设内容
https://codesign.qq.com/s/RG6X0kXNObZxEPB/VbAE955amwP9Plz/inspect
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/94840745/209934910-34d6392b-a166-4d4e-9ee5-97e3d606bc6e.png">

3、宫格型顶部间距过大，且轮播点位置距离内容过近
<img width="452" alt="image" src="https://user-images.githubusercontent.com/94840745/209935027-84a61b2b-df04-4c6c-b3c2-2d223be29d44.png">

4、左对齐显示统一为带图标的吧，混排展示不符合真实场景
<img width="436" alt="image" src="https://user-images.githubusercontent.com/94840745/209935189-a4d511de-b5ce-485b-9461-307a7b78573c.png">

**Comment by LeeJim** [comment]
多行滚动宫格类型，暂不支持着先。要考虑下是否单独拆分成另外的组件。

**Comment by pageee1021** [comment]
再补充几个问题~


1、所有列表型动作面板，顶部多出了额外的内边距，辛苦去掉~
![Image](https://user-images.githubusercontent.com/94840745/211463622-f5e21cce-00ee-4245-908f-cf206386ab42.png)
![Image](https://user-images.githubusercontent.com/94840745/211463863-1732480e-187d-47b2-a08f-4bfd44a0e48b.png)
![Image](https://user-images.githubusercontent.com/94840745/211463909-fa4b8cb3-879b-461a-b9b4-81c39dc7b1e9.png)

2、文案问题
![Image](https://user-images.githubusercontent.com/94840745/211464134-7939f1ce-1ef4-45db-9584-af88ecc216a0.png)
