### ISSUE TITLE
[TreeSelect] 滚动条应默认隐藏

### ISSUE THREAD

**Issue by pageee1021** [Tencent/tdesign-miniprogram#1348]
### tdesign-miniprogram 版本

最新版

### 重现链接

https://tdesign.tencent.com/miniprogram-live/m2w/program/miniprogram/#!pages/tree-select/tree-select.html

### 重现步骤
TreeSelect设计稿已补充：https://codesign.qq.com/s/RG6X0kXNObZxEPB/6W3G0mMkr6q0lOw/inspect

1、滚动条应默认隐藏
<img width="416" alt="image" src="https://user-images.githubusercontent.com/94840745/209947194-b7f7e200-af12-4057-99d9-420d9fc21486.png">

2、默认双列和三列的第一列，宽度保持一致
<img width="448" alt="image" src="https://user-images.githubusercontent.com/94840745/209947423-34cc7a27-ffd8-4a16-b9d3-fe03aeaf2ab2.png">

**Comment by caixuan29** [comment]
第二级选中的蓝色字没有加粗


![Image](https://user-images.githubusercontent.com/96420688/212628040-3e7e863c-cf19-43a3-8273-7bba07931ffd.png)
