### ISSUE TITLE
[t-grid-item] 通过external class设置字体样式无效

### ISSUE THREAD

**Issue by 952795** [Tencent/tdesign-miniprogram#1349]
### tdesign-miniprogram 版本

8.5.0

### 重现步骤

（1）WXML如下：
`<t-grid border="{{border}}" column="{{3}}">
          <t-grid-item t-class="griditem" t-class-text="griditem-text"  t-class-description="griditem-desc"  text="15" description="测试1" />
          <t-grid-item t-class="griditem" t-class-text="griditem-text" text="32" t-class-description="griditem-desc"  description="测试2"/>
          <t-grid-item t-class="griditem" t-class-text="griditem-text" text="32" t-class-description="griditem-desc"  description="测试3"/>
</t-grid>`
（2）WXSS如下：
.griditem-text{
  font-weight: 500;
  font-size: 30px;
  color: #366ef4;
}

.griditem-desc{
  font-weight: 800;
  font-size: 30px;
  color: #366ef4;
}

### 期望结果

通过external class设置text和description的样式，调整字体的weight、size和color

### 实际结果

仅font-weight生效，其余无效

### 框架版本

微信开发者工具基础库2.28.0

### 浏览器版本

无

### 系统版本

无

### Node版本

v16.14.2

**Comment by anlyyao** [comment]
@952795 先确认一下当前使用组件库的版本号（推荐使用最新版本），如果版本无误，使用外部样式建议加上 !important，确保覆盖默认样式，最后效果如下：
<img width="1248" alt="截屏2022-12-29 23 27 23" src="https://user-images.githubusercontent.com/51158141/209974755-d9cc470f-3c94-4b8a-9a51-a9aeea4cf2c2.png">

**Comment by 952795** [comment]
@anlyyao 收到，十分感谢您的回复，尝试添加!important后，样式生效。
