### ISSUE TITLE
[Cell] url Props带参数或增加传参Props

### ISSUE THREAD

**Issue by qiuzhangsaer** [Tencent/tdesign-miniprogram#1361]
### 这个功能解决了什么问题

Cell的url Props带参数，或者增加一个传参Props

### 你建议的方案是什么

Cell的url Props带参数，或者增加一个传参Props

**Comment by anlyyao** [comment]
@qiuzhangsaer 是需要自定义链接跳转类型？能说下具体业务场景吗～

**Comment by qiuzhangsaer** [comment]
@anlyyao 用cell展示人员列表，url跳转进去之后是各自的详细信息，但是现在只能跳转页面无法传参数，所以没法实现这个功能

**Comment by qiuzhangsaer** [comment]
> @qiuzhangsaer 没 get 到你的需求，能说下具体业务场景吗～

@anlyyao 用cell展示人员列表，url跳转进去之后是各自的详细信息，但是现在只能跳转页面无法传参数，所以没法实现这个功能
![Uploading image.png…]()

**Comment by anlyyao** [comment]
@qiuzhangsaer  明白了～ 感谢反馈，我这边跟进一下

**Comment by anlyyao** [comment]
@qiuzhangsaer 
你好，如果仅仅是跳转携带参数问题，建议按照微信官网文档说明来， reLaunch，redirectTo，navigateTo要求一致。这里就不特意增加传参props了，意义不大。

文档说明如下：
<img width="745" alt="截屏2023-01-09 12 59 45" src="https://user-images.githubusercontent.com/51158141/211243557-d0a7b7bf-e7b7-4dd8-818b-b8ff672d7383.png">


参考示例：
<img width="1123" alt="企业微信截图_960a7bfb-2c14-4c9e-8895-4d5f246c0f02" src="https://user-images.githubusercontent.com/51158141/211243353-289d3ebd-cb19-4d31-a468-f89d7d281ca5.png">

**Comment by LeeJim** [comment]
如 @anlyyao 所述，url 上直接可以加参数
