### ISSUE TITLE
[collapse] 收起点击后延时反应

### ISSUE THREAD

**Issue by q8018414** [Tencent/tdesign-miniprogram#1375]
### tdesign-miniprogram 版本

0.32.0

### 重现步骤

![image](https://user-images.githubusercontent.com/70793915/210179310-e96154db-d93f-4870-ae82-9c750a614e93.png)
![image](https://user-images.githubusercontent.com/70793915/210179326-ac0bb910-6e2c-4e27-b03e-9098bcb41053.png)
![image](https://user-images.githubusercontent.com/70793915/210179383-968e4cc3-85ee-4137-abd8-cc77abe5452b.png)
点击展开状态点击后，延迟1-3s才会开始反应。仅在真机出现这个情况。真机机型:IQOO-安卓

**Comment by q8018414** [comment]
建议考虑一下，是否需要必须在t-collapse以数组形式控制,能否在t-collapse-panel以bool直接进行控制呢？

**Comment by q8018414** [comment]
特意测试了一下官方小程序。依旧有延迟。。
![Screenshot_2023_0102_012639](https://user-images.githubusercontent.com/70793915/210179605-885a871c-3d11-4995-8ca0-ef6113e404df.gif)

**Comment by LeeJim** [comment]
好奇怪，在 iOS 不会延迟

**Comment by LeeJim** [comment]
根据研究，发现是基础库的动画问题，需要使用 animation 改造一下
