### ISSUE TITLE
[t-textarea] model:value失效

### ISSUE THREAD

**Issue by china-live** [Tencent/tdesign-miniprogram#1380]
### tdesign-miniprogram 版本

0.32.0

### 重现步骤

<t-textarea label="备注" placeholder="请输入文字" model:value="{{mark}}" autosize="true" />

data{
mark:''
}

### 补充说明

版本是从0.28升级过来的，使用0.32.0 、0.33.0 均未绑定成功。
翻了一下提交记录，应该是在 修复 #1280 时引入的（fix(textarea): support responsive update of value #1280 ）

**Comment by anlyyao** [comment]
🫡～ 我来跟进
