### ISSUE TITLE
[PullDownRefresh ] PullDownRefresh与BackTop有配合方案吗？如果没有,是否有计划在PullDownRefresh添加属性设置滚动条位置？

### ISSUE THREAD

**Issue by q8018414** [Tencent/tdesign-miniprogram#1389]
### 这个功能解决了什么问题

现有场景,订单列表过多时,PullDownRefresh的高度好几屏,
位置复位必须要手动滑动好一会儿。没有方法调整滚动条位置。

### 你建议的方案是什么

建议PullDownRefresh添加两个属性来控制整个PullDownRefresh的当前滚动条位置：
1、当前位置(是否添加对应非受控属性,有待考虑)
2、当前高度(避免动态设置当前位置是,避免超过了PullDownRefresh的当前高度)

**Comment by LeeJim** [comment]
感谢反馈 :)

这边打算支持 backtop 和 pulldownRefresh 的联动。

另外，是支持 iOS 点击顶部状态栏、安卓双击标题栏时，滚动条返回顶部。

还有，可以通过获取 pulldownRefresh 的实例，调用 `setScrollTop(top: number)` 方法设置 滚动条位置。
