### ISSUE TITLE
[Swiper] 轮播图自动轮播时有时会左右抖动

### ISSUE THREAD

**Issue by zhou133712** [Tencent/tdesign-miniprogram#1391]
### tdesign-miniprogram 版本

0.32.0

### 重现步骤

![ac684fed3883cbd8bb1ff12a139a2d7f](https://user-images.githubusercontent.com/15623053/210497371-0bae87d7-a6f4-4fda-b248-dd50bf838cbe.gif)
不知道什么情况引起的，这个轮播图自动轮播时有时会左右抖动

### 补充说明

开发环境通过扫码预览时出现的，并不是一直有这种情况，有时会出现

**Comment by LeeJim** [comment]
没有触摸 自动抖动吗

**Comment by zhou133712** [comment]
是的，没有触摸，自动轮播时

**Comment by yuwenzhuifeng** [comment]
> 没有触摸 自动抖动吗

在小程序页面上（带轮播图页面）先压进程，切换至其它app，大约10s后，恢复至小程序，轮播图则出现小幅度高频率左右抖动，基本如楼主gif图所示。此时轮播图切换不再受控（手指touch）。

手机系统：鸿蒙
tdesign-miniprogram 版本：0.34.0
