### ISSUE TITLE
[SwipeCell] 滑动后右侧出现边距

### ISSUE THREAD

**Issue by Jayclelon** [Tencent/tdesign-miniprogram#1393]
### tdesign-miniprogram 版本

最新版

### 重现链接

http://ty.tdesign.woa.com/miniprogram-live/m2w/program/miniprogram/#!pages/swipe-cell/swipe-cell.html

### 重现步骤

「带图标的滑动操作」这两个右侧都会出现边距，麻烦去掉下

<img width="501" alt="企业微信截图_fcb9e18d-8cc7-4498-b57a-062a077dab99" src="https://user-images.githubusercontent.com/104408991/210503499-22835f3b-a6bf-4609-ac25-f7b8092ea22d.png">

**Comment by Jayclelon** [comment]
表格的链接下看起来还是有边距

**Comment by anlyyao** [comment]
问题已经修复了的。 稍等啊  预览二维码正在更新～

**Comment by caixuan29** [comment]
没有做二次确认的样式，不用toast，需要参考设计稿


![Image](https://user-images.githubusercontent.com/96420688/212625897-328d0c48-9de7-4fcf-9e94-d00c3a161e4c.png)
