### ISSUE TITLE
[Dialog] 滚动条遮挡、文字跳变等问题

### ISSUE THREAD

**Issue by Jayclelon** [Tencent/tdesign-miniprogram#1394]
### tdesign-miniprogram 版本

最新版

### 重现链接

http://ty.tdesign.woa.com/miniprogram-live/m2w/program/miniprogram/#!pages/dialog/dialog.html

### 重现步骤

1. 滚动条遮挡文字
<img width="469" alt="image" src="https://user-images.githubusercontent.com/104408991/210504051-76b08e91-690c-4b5e-b1f5-998120cf2e5a.png">

2. 输入类对话框，占位符文字会有跳变（从偏高的位置跳下来）
<img width="458" alt="image" src="https://user-images.githubusercontent.com/104408991/210504381-92f68002-cb1b-4c4b-95bc-eee5ee4bfc6f.png">

3. 开放能力按钮，不要空格
<img width="478" alt="image" src="https://user-images.githubusercontent.com/104408991/210505113-ee673563-6a0c-47cf-942c-60b94201c303.png">

**Comment by LeeJim** [comment]
2 是小程序原生的问题，暂没办法处理

**Comment by Jayclelon** [comment]
「02 组件状态」的小标题，出现了缩进


![Image](https://user-images.githubusercontent.com/104408991/211454071-ed9e2bb1-d266-40cc-a992-e5ae896d1794.PNG)

**Comment by anlyyao** [comment]
补充问题在 #1474 修复
