### ISSUE TITLE
[Grid] 对齐、文案问题

### ISSUE THREAD

**Issue by Jayclelon** [Tencent/tdesign-miniprogram#1396]
### tdesign-miniprogram 版本

最新版

### 重现链接

http://ty.tdesign.woa.com/miniprogram-live/m2w/program/miniprogram/#!pages/grid/grid.html

### 重现步骤

1. 文字没有左对齐
2. 徽章改为徽标

<img width="488" alt="企业微信截图_7e26e6dd-2e14-4d6f-a3aa-620f05126e6c" src="https://user-images.githubusercontent.com/104408991/210509137-81c151c1-7e88-4515-89ff-1c041b0ddb3f.png">

**Comment by anlyyao** [comment]
@Jayclelon 
问题1是官网预览二维码没更新，新版本无该问题，需等发布新版后更新二维码；
问题2已处理，示例占位图已更新，文字已修正

**Comment by caixuan29** [comment]
增加可以调整垂直间距的属性
