### ISSUE TITLE
[Footer] 品牌页脚更换TDesign品牌

### ISSUE THREAD

**Issue by Jayclelon** [Tencent/tdesign-miniprogram#1397]
### tdesign-miniprogram 版本

最新版

### 重现链接

http://ty.tdesign.woa.com/miniprogram-live/m2w/program/miniprogram/#!pages/footer/footer.html

### 重现步骤

品牌页脚的图片，麻烦更换TDesign品牌

**Comment by anlyyao** [comment]
@Jayclelon  辛苦提供下对应切图哦～ 设计稿里面是占位图片 我好像不能直接下载
<img width="316" alt="截屏2023-01-04 23 26 03" src="https://user-images.githubusercontent.com/51158141/210589390-1f355548-1cdc-470a-8b1b-7cb77aa654e5.png">
