### ISSUE TITLE
[Image Viewer] 全屏展示、退出交互

### ISSUE THREAD

**Issue by Jayclelon** [Tencent/tdesign-miniprogram#1398]
### tdesign-miniprogram 版本

最新版

### 重现链接

http://ty.tdesign.woa.com/miniprogram-live/m2w/program/miniprogram/#!pages/image-viewer/image-viewer.html

### 重现步骤

1. 去掉顶bar，全屏展示图片，单击或向下拖拽退出预览模式（可参考微信）
<img width="841" alt="image" src="https://user-images.githubusercontent.com/104408991/210510950-e03d1207-964d-439a-aac2-16b905018e35.png">

2. 图片麻烦换几个质量更好的
<img width="497" alt="image" src="https://user-images.githubusercontent.com/104408991/210511053-f4abbeea-2df0-4491-b6b0-b53c4dbbc99f.png">

3. 不需要这种toast
<img width="304" alt="image" src="https://user-images.githubusercontent.com/104408991/210511156-455c887c-d796-45db-a94a-78a418b58759.png">

**Comment by caixuan29** [comment]
1、预设配图替换为品牌配图

2、删除点击时需要拉起一个动作面板二次确认（参考微信朋友圈）
