### ISSUE TITLE
[通用] NavBar标题的写法麻烦统一

### ISSUE THREAD

**Issue by Jayclelon** [Tencent/tdesign-miniprogram#1400]
### tdesign-miniprogram 版本

最新版

### 重现步骤

只展示纯英文，请注意大小写
如「footer 页脚」改为「Footer」
<img width="354" alt="企业微信截图_a15ee22d-0e64-4702-bfee-82e45d0d66e8" src="https://user-images.githubusercontent.com/104408991/210513078-336f5070-1b7a-42d7-ace6-840a036c16bd.png">

**Comment by pageee1021** [comment]
补充一个关于小程序导航的通用问题，除了小程序导航文案需要使用组件的纯英文名，导航背景颜色麻烦关注下，跟页面的背景颜色保持一致（目前看到部分组件的头部颜色与页面分割开了）

**Comment by anlyyao** [comment]
这里我关注一下～
