### ISSUE TITLE
[PullDownRefresh] 动效卡顿

### ISSUE THREAD

**Issue by q8018414** [Tencent/tdesign-miniprogram#1406]
### tdesign-miniprogram 版本

0.32.0

### 重现步骤

真机环境下拉动效卡顿,真机型号：IQOO

### 期望结果

动效优化

**Comment by LeeJim** [comment]
这个问题，后续通过 wxs 动画来解决，可能没这么快

**Comment by LeeJim** [comment]
和 #1275 是同个问题，后续可以关注那个 issue
