### ISSUE TITLE
[Badge] 对齐、不要左右拖动等问题

### ISSUE THREAD

**Issue by Jayclelon** [Tencent/tdesign-miniprogram#1415]
### tdesign-miniprogram 版本

最新版

### 重现步骤

1. 这一页可以被左右拖动
<img width="401" alt="企业微信截图_a63d1440-5a12-4cd2-a8de-76d230b14056" src="https://user-images.githubusercontent.com/104408991/210736994-89cf14bc-ff08-44be-95ed-97d29c1335bd.png">

2. 徽标中的字符都偏高了，请上下居中对齐
<img width="322" alt="企业微信截图_67d525b9-732e-41d3-8486-fade0a872158" src="https://user-images.githubusercontent.com/104408991/210737181-0cf6eab8-dfed-479d-a023-4e384a0888c1.png">

3. NEW标签有浅浅的白线
<img width="78" alt="image" src="https://user-images.githubusercontent.com/104408991/210737347-d74e1d94-9dbd-4105-a416-02cdb5e5d02a.png">

4. 和头像的压盖再多一些
<img width="375" alt="企业微信截图_6c290732-60c2-4486-a760-6946d8ba53ee" src="https://user-images.githubusercontent.com/104408991/210737532-fb39ffc4-c97b-4b0e-af16-8de8ef09e12c.png">

**Comment by Jayclelon** [comment]
第二个问题看起来还存在，文字偏高，麻烦再看下～

**Comment by caixuan29** [comment]
补充第二个问题截图


![Image](https://user-images.githubusercontent.com/96420688/212628854-ac630ebd-960a-4d19-9268-29bef6c26124.png)
