### ISSUE TITLE
[ActionSheet] 谜一样的焦点边框

### ISSUE THREAD

**Issue by q8018414** [Tencent/tdesign-miniprogram#1421]
### tdesign-miniprogram 版本

0.33.0

### 重现步骤

![image](https://user-images.githubusercontent.com/70793915/210837970-7afe4dee-c074-4136-9cd5-9df8fc105070.png)
开发工具

![Screenshot_20230106_010110](https://user-images.githubusercontent.com/70793915/210838107-123b520c-b744-4f32-bd29-0ca558c56699.jpg)
真机

疑似在非无障碍模式下出现无障碍边框。部分时候，点击蒙版只会切换焦点，不会自动关闭。

### 实际结果

部分时候，点击蒙版只会切换焦点，不会自动关闭。

### 基础库版本

2.27.3

**Comment by LeeJim** [comment]
感谢反馈，我这边尽快跟进处理下
