### ISSUE TITLE
[popup] 在popup中存在文本框的时候，唤起时，安卓真机下显示会有问题

### ISSUE THREAD

**Issue by Zlianxin** [Tencent/tdesign-miniprogram#1423]
### tdesign-miniprogram 版本

0.33.0

### 重现链接

https://gitee.com/jinyun0927/question_20230126

### 重现步骤

在popup中加入文本输入框，点击按钮后唤起popup

### 期望结果

显示正常

### 实际结果

iOS下，显示正常，
但是在Android下，唤起是popup会全屏显示

### 框架版本

小程序

**Comment by LeeJim** [comment]
可以提供下机型吗

**Comment by anlyyao** [comment]
@Zlianxin 造成该问题的原因是，input组件内嵌在窗体组件中时，安卓机型上 focus=“{{false}}” 会失效，这个问题在组件层上我目前还没有找到合适的方法。但是在业务处理上，我可以提供一个简易的解决方案，你可以 在input组件上，加上 disabled="{{!visible}}"， 利用 disabled 禁止 input 在页面初始化时的自动聚焦。

```html
<t-popup visible="{{visible}}" bind:visible-change="onVisibleChange" placement="bottom" close-btn="{{true}}">
  <view class="popup">
    <view class="popup-title">充值金额</view>
    <view class="moneyinput">
      <t-input cursor-spacing="50" disabled="{{!visible}}" label="slot" type="digit" bindchange="onlyNumber" bindfocus="focusHandle" borderless="{{false}}" placeholder="请输入金额">
      </t-input>
    </view>
    <view><button class="submit-btn" catchtap="onconfirmPay">确定</button></view>
  </view>
</t-popup>
```

**Comment by LeeJim** [comment]
fixed by #2209 
升级至 1.1.14 以上版本即可
