### ISSUE TITLE
t-check-tag click事件点击无效

### ISSUE THREAD

**Issue by yinhexianyin** [Tencent/tdesign-miniprogram#1431]
### tdesign-miniprogram 版本

0.33.0

### 重现步骤

index.wxml

\<t-check-tag size="large" variant="light" content="{{ ['安装', '安装'] }}" click="selectPrjType"/>

index.ts
selectPrjType() {
    console.log('select project type')
  }

### 期望结果

点击tag便签，调用selectPrjType方法

### 实际结果

日志没有任何输出，方法貌似没有调用。查看源码check-tag.js，onClick调用了this._trigger('click');，小程序组件中一般使用this.triggerEvent('click', { })，不知道是我对组件的使用方法有问题还是trigger调用的问题。

### 基础库版本

2.25.2

**Comment by q8018414** [comment]
呃呃，如果我没有记错。事件的绑定方式是`bind:click="selectPrjType"`??

**Comment by LeeJim** [comment]
确实是的，应该用 `bind:click="selectPrjType"`
