### ISSUE TITLE
[Collapse]折叠面板是否考虑内容面板在上？

### ISSUE THREAD

**Issue by q8018414** [Tencent/tdesign-miniprogram#1438]
### 这个功能解决了什么问题

底部固定view内的折叠面板，在往下撑开会导致header向上移动，但整体固定的情况下导致header与content同时移动。感觉挺怪异的。。在结合之前提出的BUG。折叠面板真机动效卡顿。直接废了。。

https://user-images.githubusercontent.com/70793915/211050696-00c746a5-ba4a-4f08-8d5f-95bc5ea11abe.mp4

### 你建议的方案是什么

增加属性控制面板选择向上或向下展开。

**Comment by q8018414** [comment]
https://user-images.githubusercontent.com/70793915/211052513-6c9d82f0-6600-4d82-b860-d8cdf05b6da0.mp4

**Comment by LeeJim** [comment]
已支持，预计周一发布 0.34.0 带上
