### ISSUE TITLE
[CollapsePanel] header插槽引入时,出现了一个比较迷惑的事情

### ISSUE THREAD

**Issue by q8018414** [Tencent/tdesign-miniprogram#1439]
### tdesign-miniprogram 版本

0.33.0

### 重现步骤

![image](https://user-images.githubusercontent.com/70793915/211059479-c6ead4d2-73f3-45d1-b820-77f4b1c98909.png)
![image](https://user-images.githubusercontent.com/70793915/211060154-f3f1b1e4-a300-4ee7-84cc-10204a39217d.png)
这个比较迷惑的一个情况。header插槽引入就嗨起来了。。

**Comment by LeeJim** [comment]
panel 的 header 本身是使用 cell 的，你又用 cell 就导致了嵌套。
panel 的属性 header 其实本意是 title。

**Comment by q8018414** [comment]
> panel 的 header 本身是使用 cell 的，你又用 cell 就导致了嵌套。 panel 的属性 header 其实本意是 title。

但是下面那张图.里面是用的badge也会出现嵌套的情况。我明天在测试一下,其它组件试试吧。。。
