### ISSUE TITLE
花那么多精力出那么UI组件，不如好好搞一搞小程序的CSS兼容

### ISSUE THREAD

**Issue by langziyang** [Tencent/tdesign-miniprogram#144]
小程序的css选择器兼容如果能好好搞一搞，完全兼容所有css选择器的话，比出再多的UI组件都好

**Comment by 94dreamer** [comment]
@langziyang  是指「小程序」本身的 CSS 解析问题吗?

**Comment by lixingdecai** [comment]
@langziyang 如果你说css选择器兼容是指的小程序本身的兼容和扩展的功能的话，那和组件库就是两个维度的事情；组件库是为了业务快速迭代，目的是降本提效。本质是不冲突的。
