### ISSUE TITLE
[Indexes]索引导航无法选中的问题

### ISSUE THREAD

**Issue by chundonghan** [Tencent/tdesign-miniprogram#1469]
### tdesign-miniprogram 版本

0.33.0

### 重现步骤

使用【Indexes】组件按拼音首字母展示高校列表，数据量为800+；页面渲染之后，右侧的导航偶尔会出现无法锁定字母，只能定位开头的A和末尾的Z。

### 期望结果

期望能得到有效的回复，十分感谢。

**Comment by LeeJim** [comment]
昨晚刚发布了， 0.34.0？可以试试有没问题

**Comment by chundonghan** [comment]
> 昨晚刚发布了， 0.34.0？可以试试有没问题

更新后仍然有同样的问题，时好时不好；并且从git显示的文件状态来看，【indexes】UI控件中没有显示修改过的文件

**Comment by AURWQTyCle0u** [comment]
> 按拼音首字母展示高校列表，数据量为800+；页面渲染之后，右侧的导航偶尔会出现无法锁定字母，只能定位开头的A和末尾的Z。

你好，请问你会出现在 wx,request 里同时 setData : list 和 indexList 导致 sidebar 没有效果（只显示字母无法定位）的问题吗？

**Comment by AURWQTyCle0u** [comment]
> > 昨晚刚发布了， 0.34.0？可以试试有没问题
> 
> 更新后仍然有同样的问题，时好时不好；并且从git显示的文件状态来看，【indexes】UI控件中没有显示修改过的文件

好像在 wx.request 里同时 setData: list 和 indexList 会有问题，我的 sidebar 动不了。
