### ISSUE TITLE
[SideBar] SideBar 没有将TabBar高度减去，导致下拉和内容页面 在分页后点不了及显示不全

### ISSUE THREAD

**Issue by kinkim** [Tencent/tdesign-miniprogram#1472]
### tdesign-miniprogram 版本

0.32.0

### 重现链接

微信小程序  益辰辰 

### 重现步骤

SideBar 超过一页后，最下方的两个分类点不到。
内容超过一页也存在同样的问题。 
看起来是 SIDEBAR没有去掉TABBAR的高度。
![imgalt](https://test.5dhj.com/huij-fs/file/common/issuse/2.png "1")

### 期望结果

期望能显示全部。

### 框架版本

3.2

### 基础库版本

2.23.1

**Comment by LeeJim** [comment]
sidebar 外面的容器的高度你控制一下就好了

**Comment by kinkim** [comment]
解决了。padding-bottom: calc(env(safe-area-inset-bottom) + 96rpx); 
``` js 
page { 
  background-color: #fff; 
  box-sizing: border-box; 
  padding-bottom: calc(env(safe-area-inset-bottom) + 96rpx); 
} 
```
