### ISSUE TITLE
[Dialog] confim-btn 传入string类型显示样式错误

### ISSUE THREAD

**Issue by zsying** [Tencent/tdesign-miniprogram#1475]
### tdesign-miniprogram 版本

0.34

### 重现步骤

<t-dialog
  visible="{{showConfirm}}"
  title="调整"
  content="当天数目将会重新计算，请确认"
  confirm-btn="确定"
  cancel-btn="取消"
  bind:confirm="clickOkDialog"
  bind:cancel="clickCancelDialog"
/>

### 期望结果

取消、  确认 正常显示

### 实际结果

 取消、确认按钮只显示一半， 一半被挤压到界面外头

### 框架版本

miniprogram(0.34)

### 补充说明

<t-dialog
  visible="{{showConfirm}}"
  title="调整"
  content="调整级别后，当天学习数目将会重新计算，请确认"
  confirm-btn="{{ { content: '确定', variant: 'base' } }}"
  cancel-btn="取消"
  bind:confirm="clickOkDialog"
  bind:cancel="clickCancelDialog"
/>

传入 object 显示正常！ ， 必须添加variant: 'base' 属性。

**Comment by anlyyao** [comment]
@zsying  感谢反馈 我来看看～
