### ISSUE TITLE
[框架] 在Typescript下使用组件，编译后在手机端报大量为Null的警告信息

### ISSUE THREAD

**Issue by zsying** [Tencent/tdesign-miniprogram#1476]
### tdesign-miniprogram 版本

0.34

### 重现步骤

在typescript中使用tdesign（ button，overlay，icon） 等组件，编译后，推送体验版到手机端， 开启vconsole查看， 出现大量警告信息。

### 期望结果

不出现大量警告

### 实际结果

![image](https://user-images.githubusercontent.com/239268/211498144-6ec88fa6-a09e-4505-8338-26924a6ffa13.png)
![image](https://user-images.githubusercontent.com/239268/211498236-2f00b30d-2c15-4868-8124-cbbb31ca0a5f.png)
![image](https://user-images.githubusercontent.com/239268/211498320-3d2e7811-3f70-4ef8-9812-d9dce308e951.png)
![image](https://user-images.githubusercontent.com/239268/211498400-4734a749-d478-47b8-8a90-4aee7d8e5507.png)

**Comment by anlyyao** [comment]
@LeeJim 看上去是因为组件部分API缺少默认值。是不是可以考虑给目前所有组件没有默认值的API补充默认值？  `String`类型API默认值置 `''`，`Object`类型默认值置`{}`，其他同理～
