### ISSUE TITLE
[Indexes] 当小程序有顶部自定义导航栏时，显示有问题

### ISSUE THREAD

**Issue by zhou133712** [Tencent/tdesign-miniprogram#1478]
### tdesign-miniprogram 版本

0.32.0

### 重现步骤

小程序顶部有自定义导航栏（fixed绝对定位），刚刚进入页面显示是正常的，当往下滚动再回到A索引时，索引A的那一行的偏移位置就不对了，顶到了导航栏上面去了
![1673341708092](https://user-images.githubusercontent.com/15623053/211512328-cbf1877a-d314-4428-8d63-361f1722b105.jpg)

### 基础库版本

2.27.3

**Comment by LeeJim** [comment]
新增了 stickyOffset 属性，可以处理你这种情况

**Comment by zhou133712** [comment]
好的，那我换下版本
