### ISSUE TITLE
[Input] 输入框底部默认有下划线并且borderless无效果

### ISSUE THREAD

**Issue by ElanYoung** [Tencent/tdesign-miniprogram#1480]
### tdesign-miniprogram 版本

0.34.0

### 重现步骤

<img width="375" alt="image" src="https://user-images.githubusercontent.com/39727435/211583504-f7c1e74b-c5cc-4cb2-bf2a-6e3d8bfac3c3.png">

`borderless`属性`true`或者`false`，效果一样，我记得0.33.0版本是好的

### 期望结果

希望突如其来的下划线能去除，并且`borderless`生效，想要实现有边框效果，之前不需要通过自定义样式实现

### 实际结果

0.34.0版本出现下划线并且`borderless`失效

### 基础库版本

2.29.2

**Comment by anlyyao** [comment]
@ElanYoung  0.34.0版本中 borderless 默认值变更为 false，所以默认是有分割线的，如果要去除，可以令borderless为true。

版本： 0.34.0
borderless效果如下， ：
![image](https://user-images.githubusercontent.com/51158141/211594852-f3b90169-62cf-47e0-aafd-f9ba065ff7ba.png)

**Comment by ElanYoung** [comment]
> 



> @ElanYoung 0.34.0版本中 borderless 默认值变更为 false，所以默认是有分割线的，如果要去除，可以令borderless为true。 关于“borderless生效，想要实现有边框效果”，目前只能通过自定义样式实现了，这里确实是一个不兼容更新，关于borderless的问题，因为底部分割线在移动端场景更常见，和设计沟通后，也是决定将borderless属性给底部分割线，外边框用自定义样式实现。
> 
> 版本： 0.34.0 borderless效果如下， ： ![image](https://user-images.githubusercontent.com/51158141/211594852-f3b90169-62cf-47e0-aafd-f9ba065ff7ba.png)

感谢回复！
