### ISSUE TITLE
[Message 消息通知] 使用时存在大量警告

### ISSUE THREAD

**Issue by hmwdt** [Tencent/tdesign-miniprogram#1488]
### tdesign-miniprogram 版本

0.34.0

### 重现步骤

按照官网demo
https://tdesign.tencent.com/miniprogram/components/message
一样的代码，message组件出现大量警告
加载时出现
![image](https://user-images.githubusercontent.com/27841545/211956684-0ac783bf-4498-4c68-9ce8-b5cd93fb464a.png)

点击任意按钮出现以下警告
![image](https://user-images.githubusercontent.com/27841545/211956488-4018b1b8-a9cc-40dc-9162-b8eff14efed7.png)

### 期望结果

修复警告问题

### 基础库版本

2.29.1

**Comment by hmwdt** [comment]
@anlyyao 好的，确实不影响使用，就是看着闹心

**Comment by evanlong0926** [comment]
不仅仅是这个一个组件，我发现很多组件都有这个问题，建议你们逐一排查一下。我看着也挺闹心的。。。
