### ISSUE TITLE
[t-cell] 下边框样式问题

### ISSUE THREAD

**Issue by QJvic** [Tencent/tdesign-miniprogram#1502]
### tdesign-miniprogram 版本

0.34.0

### 重现步骤

  ```html
<t-cell title="我的"></t-cell>
```

### 期望结果

下边框距离左侧边距，与距离右侧边距一致

### 实际结果

下边框距离左侧有一定边距，右侧直接到边了

### 框架版本

0.34.0

### 基础库版本

2.27.3

**Comment by LeeJim** [comment]
设计如此，不过可以提供 CSS Variables 来调整这个
