### ISSUE TITLE
[Collapse] CollapsePanel多个组件间存在冲突,内容无法隐藏

### ISSUE THREAD

**Issue by q8018414** [Tencent/tdesign-miniprogram#1504]
### tdesign-miniprogram 版本

0.34.0

### 重现步骤

https://user-images.githubusercontent.com/70793915/212335901-88b64544-881e-4bb4-9c94-c54f953c1954.mp4

![image](https://user-images.githubusercontent.com/70793915/212335988-1a0d6d0d-38fb-4493-bb41-9b48a115792b.png)

CollapsePanel里面的内容view不论是否定义slot="content"都会出现这样的情况与cell存在冲突。

https://user-images.githubusercontent.com/70793915/212336597-afa211c7-2fab-4ae3-b6b2-6f7ad9a9b5f7.mp4

剔除掉cell单独使用badge又出现了不一样的情况。

input的
https://user-images.githubusercontent.com/70793915/212337378-03c9c55c-83c8-4abf-ac56-a8053d6a6dd9.mp4

progress的
https://user-images.githubusercontent.com/70793915/212338402-0785e32d-8277-44d9-a3ea-83b934f79929.mp4

**Comment by LeeJim** [comment]
视频看不到，能否重新上传 or 提供一些图片看看

**Comment by q8018414** [comment]
> 视频看不到，能否重新上传 or 提供一些图片看看

视频下载地址：http://nas.scwyc.com:5000/sharing/h5CmMtdyx

大致情况截图：

![image](https://user-images.githubusercontent.com/70793915/212662453-c654dfe7-7611-4ec2-ac3a-738aade4b278.png)
![image](https://user-images.githubusercontent.com/70793915/212662507-c7f7bbd0-c2d1-4d1c-bc72-2fde777f4fd9.png)

**Comment by LeeJim** [comment]
感觉和之前修复的是同个问题；fixed by #1477 
建议升级至 1.0.0-rc 以上
