### ISSUE TITLE
[result] `image` 属性无法使用相对路径读取本地图片

### ISSUE THREAD

**Issue by evanlong0926** [Tencent/tdesign-miniprogram#1506]
### tdesign-miniprogram 版本

1.0.0-rc

### 重现步骤

```json
"usingComponents":  {
   "t-result": "tdesign-miniprogram/result/result"
}
```

```wxml
<view>
  <t-result title="暂无数据" image="../../common/assets/noData.png" />
</view>
```

### 期望结果

可以显示本地的图片，并且可以通过css调整图片展示的样式

### 实际结果

始终显示小叉叉，并没有本地图片出现

### 基础库版本

2.29.2

**Comment by LeeJim** [comment]
这个相对路径变成了 node_modules 里面的相对路径了，建议使用绝对路径

**Comment by evanlong0926** [comment]
> 这个相对路径变成了 node_modules 里面的相对路径了，建议使用绝对路径

```wxml
<view class="demo-section__content" wx:else>
  <t-result title="暂无数据" image="/miniprogram/common/assets/noData.png"></t-result>
</view>
```
这样使用也报错 `Failed to load local image resource /miniprogram/common/assets/noData.png 
 the server responded with a status of 500 (HTTP/1.1 500 Internal Server Error) 
(env: macOS,mp,1.06.2301040; lib: 2.29.1)`

**Comment by LeeJim** [comment]
> > 这个相对路径变成了 node_modules 里面的相对路径了，建议使用绝对路径
> 
> ```
> <view class="demo-section__content" wx:else>
>   <t-result title="暂无数据" image="/miniprogram/common/assets/noData.png"></t-result>
> </view>
> ```
> 
> 这样使用也报错 `Failed to load local image resource /miniprogram/common/assets/noData.png the server responded with a status of 500 (HTTP/1.1 500 Internal Server Error) (env: macOS,mp,1.06.2301040; lib: 2.29.1)`

需要提供下你的项目结构，猜测一下应该不需要 `/miniprogram`，直接用 `/common/assets/noData.png`

**Comment by evanlong0926** [comment]
> > > 这个相对路径变成了 node_modules 里面的相对路径了，建议使用绝对路径
> > 
> > 
> > ```
> > <view class="demo-section__content" wx:else>
> >   <t-result title="暂无数据" image="/miniprogram/common/assets/noData.png"></t-result>
> > </view>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这样使用也报错 `Failed to load local image resource /miniprogram/common/assets/noData.png the server responded with a status of 500 (HTTP/1.1 500 Internal Server Error) (env: macOS,mp,1.06.2301040; lib: 2.29.1)`
> 
> 需要提供下你的项目结构，猜测一下应该不需要 `/miniprogram`，直接用 `/common/assets/noData.png`

确实是这样，非常感谢，这个地方可能需要在文档中做出提示，不然很容易陷进去

**Comment by LeeJim** [comment]
确实可以的，这边就先关闭了
