### ISSUE TITLE
[cell] 需要 `open-type` 开放能力

### ISSUE THREAD

**Issue by evanlong0926** [Tencent/tdesign-miniprogram#1510]
### 这个功能解决了什么问题

有些时候获取手机号需要这样的设计

### 你建议的方案是什么

添加 `open-type` 的支持

**Comment by evanlong0926** [comment]
业务设计上不允许使用按钮，这个功能很着急，我应该怎么办

**Comment by LeeJim** [comment]
这个问题，你可以用一个 button 透明背景覆盖在上面来处理。
内置到 cell 这样的诉求，是不合理的

**Comment by evanlong0926** [comment]
> 这个问题，你可以用一个 button 透明背景覆盖在上面来处理。 内置到 cell 这样的诉求，是不合理的

我是看到有这样一个案例的

微信小程序 -> 微信服务市场 -> 首页 -> 去挑选 -> 去定制小程序 -> 联系方式

https://user-images.githubusercontent.com/52912949/213103567-8fcbbeed-172f-47a6-bdd4-5abf23b5f784.mp4

**Comment by Mr-Pro** [comment]
> ### 这个功能解决了什么问题
> 有些时候获取手机号需要这样的设计
> 
> ### 你建议的方案是什么
> 添加 `open-type` 的支持

可以暂时先用button包裹，然后样式覆盖button吧
![image](https://user-images.githubusercontent.com/26507179/221364723-d5a5ba18-cf96-49e0-8458-102398015706.png)
![image](https://user-images.githubusercontent.com/26507179/221364730-252bc98b-593a-45e9-97a1-bebb92c22512.png)

**Comment by evanlong0926** [comment]
> > ### 这个功能解决了什么问题
> > 有些时候获取手机号需要这样的设计
> > ### 你建议的方案是什么
> > 添加 `open-type` 的支持
> 
> 可以暂时先用button包裹，然后样式覆盖button吧 ![image](https://user-images.githubusercontent.com/26507179/221364723-d5a5ba18-cf96-49e0-8458-102398015706.png) ![image](https://user-images.githubusercontent.com/26507179/221364730-252bc98b-593a-45e9-97a1-bebb92c22512.png)

好的

**Comment by evanlong0926** [comment]
好的

**Comment by LeeJim** [comment]
都是通过包裹一个透明的 button 来处理的。
