### ISSUE TITLE
[tdesign-miniprogram] 希望支持 `useExtendedLib` 引入

### ISSUE THREAD

**Issue by evanlong0926** [Tencent/tdesign-miniprogram#1511]
### 这个功能解决了什么问题

1. 支持[扩展库](https://developers.weixin.qq.com/miniprogram/dev/reference/configuration/app.html#useExtendedLib)引入，不占用小程序包体积
2. 使用组件库时无需升级，永远保持最新版本，开发者无需考虑版本问题
3. 省去在 `微信开发者工具` 中手动构建npm

### 你建议的方案是什么

```json
"useExtendedLib": {
  "weui": true,
  "tdesign": true
}
```

**Comment by LeeJim** [comment]
和 #1102 是相同的。
暂时还不能成为扩展库，等 TDesign 更成熟之后希望可以成为。
