### ISSUE TITLE
[Avatar] image 不支持云开发的 cloud:// 类型的图片地址

### ISSUE THREAD

**Issue by CrossLee** [Tencent/tdesign-miniprogram#1525]
### tdesign-miniprogram 版本

1.0.0-rc.1

### 重现步骤

在云存储中添加一张图片
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/4584905/214324351-8a6c57de-198c-4954-be35-c71e3cac23f0.png">

将图片的 cloud:// 格式 url 放入 t-avatar 显示不了图片
`  <t-avatar bindtap="avatarClick" shape="circle" alt="1" icon="user" image="cloud://xxx.xxx/.../1617886478402543617.jpg" />`

### 期望结果

正确显示图片

### 实际结果

未显示图片

**Comment by anlyyao** [comment]
@CrossLee 用 https 那个地址～

**Comment by anlyyao** [comment]
@CrossLee  如果是在小程序自己的云存储中， fileID是没问题的，应该不存在你说的原生 image可以，t-avatar组件不行，因为t-avatar组件就是基于image实现的，如果是共享云环境， fileID 就不支持了，cloud//会被识别成本地地址，这应该是云开发环境限制。共享环境下 建议用url，或者用 getTempFileURL 去获取真实链接、

实际测试结果如下：
![image](https://user-images.githubusercontent.com/51158141/215942765-3b041055-65a6-457b-bc01-af897cfe865d.png)

**Comment by CrossLee** [comment]
@anlyyao 

原来是这样，用共享环境测试了一下确实按本地图片去获取了 ```/images/cloud://``` 。。

不过官方的 image 组件文档关于 src 也没描述清楚（只是说支持 fileID），共享环境那边的文档也没有涉及到这个使用限制，sad。

感谢你的回复。

**Comment by anlyyao** [comment]
@CrossLee 好的，那我这边先关闭该 issue 了。 如果有新问题，欢迎一起讨论～
