### ISSUE TITLE
[Calendar]奇怪的加粗边框

### ISSUE THREAD

**Issue by q8018414** [Tencent/tdesign-miniprogram#1537]
### tdesign-miniprogram 版本

1.0.0-rc.1

### 重现步骤

用Popup包裹Calendar弹出就会在Calendar的title上加粗一圈。
如图:
![image](https://user-images.githubusercontent.com/70793915/215443861-ebbd67b4-c27d-4ca7-9d9a-01d4858866cf.png)
因场景需求,需要一些额外信息。
没法用Calendar自带的弹出。
在这样的弹窗方式下。Popup的closeBtn层级不够。会被Calendar给挡住，当然这个可以自行处理，随带一嘴。上面的边框有点迷惑。

**Comment by anlyyao** [comment]
@q8018414 感谢反馈 辛苦提供一下完整的可复现代码片段～

**Comment by q8018414** [comment]
> @q8018414 感谢反馈 辛苦提供一下完整的可复现代码片段～
代码截图,你们辛苦了,我们是享受的,嘿嘿:
![image](https://user-images.githubusercontent.com/70793915/217531835-f58b8ec7-9e3a-4ea8-a4eb-abd8a5d3a5af.png)

**Comment by anlyyao** [comment]
@q8018414 我这边试了一下用Popup包Calendar， 日历组件的title和body之间没有出现不明分割线，使用正常，未能复现。你看你能不能通过微信开发工具上传代码片段，并提供链接

ps: 从图片来看，可以考虑下是不是层级问题

**Comment by q8018414** [comment]
应该不是层级问题，感觉有点像是无障碍的识别框。在焦点切换的时候就消失了。代码片段晚上下班弄一个。
真机效果图:



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月9日(周四) 下午2:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Tencent/tdesign-miniprogram] [Calendar]奇怪的加粗边框 (Issue #1537)




 
@q8018414 我这边试了一下用Popup包Calendar， 日历组件的title和body之间没有出现不明分割线，使用正常，未能复现。你看你能不能通过微信开发工具上传代码片段，并提供链接
 
ps: 从图片来看，可以考虑下是不是层级问题

**Comment by anlyyao** [comment]
@q8018414 是安卓机吗？

**Comment by q8018414** [comment]
对，安卓手机



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月9日(周四) 下午3:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Tencent/tdesign-miniprogram] [Calendar]奇怪的加粗边框 (Issue #1537)




 
@q8018414 是安卓机吗？

**Comment by syxysszyw** [comment]
请问 @q8018414 具体是什么安卓的机型，issue 所附的“加粗边框”的截图是否开启了读屏软件（根据“感觉有点像是无障碍的识别框。在焦点切换的时候就消失了”描述猜测），方便的话，辛苦提供一下录屏

**Comment by q8018414** [comment]
录屏，不知道能不能看见。
确定没有开其他软件。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月9日(周四) 下午4:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Tencent/tdesign-miniprogram] [Calendar]奇怪的加粗边框 (Issue #1537)




 
请问 @q8018414 具体是什么安卓的机型，issue 所附的“加粗边框”的截图是否开启了读屏软件（根据“感觉有点像是无障碍的识别框。在焦点切换的时候就消失了”描述猜测），方便的话，辛苦提供一下录屏

**Comment by q8018414** [comment]
https://user-images.githubusercontent.com/70793915/217759724-a3fbe0e5-ab54-4050-972e-100f905d251a.mp4

**Comment by q8018414** [comment]
> @q8018414 我这边试了一下用Popup包Calendar， 日历组件的title和body之间没有出现不明分割线，使用正常，未能复现。你看你能不能通过微信开发工具上传代码片段，并提供链接
> 
> ps: 从图片来看，可以考虑下是不是层级问题
代码片段连接，我本地测试还是有边框
https://developers.weixin.qq.com/s/Az99QUmZ7qFS

**Comment by q8018414** [comment]
@anlyyao 麻烦帮忙看看
