### ISSUE TITLE
Button 组件 disabled="true", bindtap 绑定的事件还是执行

### ISSUE THREAD

**Issue by CrossLee** [Tencent/tdesign-miniprogram#154]
**对应的组件**

Button

**相关环境**

基础库版本：最新

运行环境：开发者工具 / iOS / Android 

**出现的问题**

Button 组件 disabled="true", bindtap 绑定的事件还是执行

**附加信息**

https://user-images.githubusercontent.com/4584905/151180277-db37673d-6d2e-43d8-9c76-473923019f3e.MP4

**Comment by LeeJim** [comment]
#134  已修复此问题，今天或明天会发个版本
