### ISSUE TITLE
[calendar] 设置 min-date 后视图不停留在今天

### ISSUE THREAD

**Issue by yakiang** [Tencent/tdesign-miniprogram#1541]
### tdesign-miniprogram 版本

^1.0.0-rc.1

### 重现步骤

```
  <t-calendar 
      use-popup="{{false}}" 
      first-day-of-week="{{1}}"
      min-date="{{946684800000}}" 
      max-date="{{1675209600000}}"
      bind:confirm="handleConfirm" 
    />
```

### 期望结果

日历视图停留在今天，而不是 `min-date` 那个月份。
ps 尝试过设置 `value`/`default-value`，也不行

### 实际结果

日历视图默认停留在 `min-date` 那个月

**Comment by yakiang** [comment]
看了下源码，这应该是 `scroll-into-view` 的 bug。暂时可以通过主动调用一下 `scrollIntoView()` 解决，不过日历还是会先去到最早的日期再来到最新日期。

```
const calendar = this.selectComponent('#calendar')
    setTimeout(() =>{
      calendar.scrollIntoView();
    }, 100)    
```

**Comment by LeeJim** [comment]
因为没有设置 value 值就默认去 minDate 的值了。
另外 Calendar 有个特性，就是回自动定位到 value 对应的月份

**Comment by yakiang** [comment]
> 

我上面提到了，设置了 `value` 也不行

**Comment by LeeJim** [comment]
我知道问题了，这边使用的是 use-popup = false 的场景，我来解决下
