### ISSUE TITLE
[Input] 在popup里面时,input设置focus无效

### ISSUE THREAD

**Issue by q8018414** [Tencent/tdesign-miniprogram#1542]
### tdesign-miniprogram 版本

1.0.0-rc.1

### 重现步骤

![image](https://user-images.githubusercontent.com/70793915/215942610-fe189469-de15-465b-a6f6-224111d9a0f7.png)
WXML结构如图。在弹出popup后。input自动获取焦点。设置focus为FALSE无效。

**Comment by anlyyao** [comment]
@q8018414 是安卓机型吗？我今天在复现 #1423 问题时也发现了，在安卓中 如果将input组件内嵌在窗体组件中，focus=“{{false}}”失效

**Comment by samxxxxx** [comment]
## 我也是同样的问题

安卓机，打开popup弹出来键盘，超级恶心。input就自动获取焦点，设置focus、auto-focus为false都无效！

**Comment by LeeJim** [comment]
fixed by #2209 
更新至 1.1.14 以上版本即可
