### ISSUE TITLE
[Badge] shape为ribbon时,color会导致部分颜色不一样

### ISSUE THREAD

**Issue by q8018414** [Tencent/tdesign-miniprogram#1543]
### tdesign-miniprogram 版本

1.0.0-rc.1

### 重现步骤

![image](https://user-images.githubusercontent.com/70793915/216004312-e7ab6cdb-2f10-472e-a8d3-d6946dc8a8f0.png)
如图,设置颜色后,两个小三角的颜色不同步

**Comment by q8018414** [comment]
![image](https://user-images.githubusercontent.com/70793915/216005336-732c6181-73db-44c1-bcd9-7043dd2f80a9.png)

必须要用css变量she设置才行。。

**Comment by lclichen** [comment]
时间来到2025年，又出现了这个问题呢（）
