### ISSUE TITLE
Toast 组件样式没有

### ISSUE THREAD

**Issue by CrossLee** [Tencent/tdesign-miniprogram#155]
**对应的组件**

Toast

**相关环境**

基础库版本：最新

运行环境：开发者工具 / iOS / Android 

**出现的问题**

Toast 组件样式没有

**附加信息**

![image](https://user-images.githubusercontent.com/4584905/151180516-317c35d1-4276-4fe8-ae7e-bdcded87012c.png)

**Comment by LeeJim** [comment]
我来定位下问题

**Comment by LeeJim** [comment]
我在 v0.5.0 上试了下，没有样式问题。
麻烦更新试试

**Comment by CrossLee** [comment]
> 我在 v0.5.0 上试了下，没有样式问题。 麻烦更新试试

版本发了吗？
