### ISSUE TITLE
[Swiper] 希望可以轮播的内容不只是图片，可以是其他内容

### ISSUE THREAD

**Issue by Zlianxin** [Tencent/tdesign-miniprogram#1550]
### 这个功能解决了什么问题

新版组件把swiper-item去掉之后，好像没办法自定义轮播的内容，只可以轮播图片。
但如果出现视频用例中的需求，现在的组件应该是实现不了的。

[使用场景的视频用例](https://cjbtest.mynatapp.cc/statics/temp/WeChat_20230203103345.mp4)

### 你建议的方案是什么

看了一眼现在的组件源码，依赖原生swiper实现，swiper-item在组件内部去写，循环的是参数list，基于现有的代码，确实也没啥建议的方案。。。

**Comment by anlyyao** [comment]
@Zlianxin @LeeJim 把swiper-item也抽成一个组件？ 这样swiper-item的内容就能支持自定义了

**Comment by huhuang03** [comment]
突然把swiper-item去掉了。我代码里面用到了。还要改造之后才能升级，比较麻烦呢。。

**Comment by nightmaring** [comment]
同样需要自定义内容
