### ISSUE TITLE
[cell] 遇见中文句号无法自动换行

### ISSUE THREAD

**Issue by hmwdt** [Tencent/tdesign-miniprogram#1557]
### tdesign-miniprogram 版本

0.34.0

### 重现步骤

    <t-cell title="任务内容" description="你手机睡觉觉。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。嫁鸡随啊男生女生你是你是男是女男生女生，。，。，。，。，。，。，。，。，。，。，。，。》是、·#+？%" hover />

### 期望结果

遇见句号或者其他特殊符号，可完成自动换行，目前无论添加多少个句号，都无法自动换行

**Comment by anlyyao** [comment]
@hmwdt 感谢反馈 我这边跟进一下～

**Comment by hmwdt** [comment]
@anlyyao 感谢你意见，我先按照这个思路进行修改，目还是可以满足我的需求的
