### ISSUE TITLE
[Swiper] current 属性传入数字控制台报警告提示传入的不是数字

### ISSUE THREAD

**Issue by rico0808** [Tencent/tdesign-miniprogram#1560]
### tdesign-miniprogram 版本

1.0.0-rc.1

### 重现步骤

<img width="299" alt="image" src="https://user-images.githubusercontent.com/21149432/217419773-b89e3ffd-2ca9-4be0-bdbd-e89df65affb9.png">
<img width="268" alt="image" src="https://user-images.githubusercontent.com/21149432/217419792-b7a538de-d631-47e2-bce0-1846fd623372.png">
<img width="830" alt="image" src="https://user-images.githubusercontent.com/21149432/217419846-fe373373-2d62-426f-9163-726733f0533a.png">

current 传入数字提示传入的不是数字。

### 期望结果

警告消失

### 基础库版本

2.30.2

**Comment by anlyyao** [comment]
@rico0808 告警问题集中处理过一次，先等一下新版本哦～
