### ISSUE TITLE
Upload 上传组件的size-limit属性在使用SizeLimitObj对象时无效

### ISSUE THREAD

**Issue by yinhexianyin** [Tencent/tdesign-miniprogram#1569]
### tdesign-miniprogram 版本

1.0.0-rc.1

### 重现步骤

order.wxml
\<t-upload
        media-type="{{['image']}}"
        files="{{originFiles}}"
        grid-config="{{gridConfig}}"
        bind:success="handleSuccess"
        bind:remove="handleRemove"
        max="{{6}}"
        size-limit="{{ sizeLimitObj }}"
      />

order.ts
sizeLimitObj: {size: 2, unit: 'KB', message: '图片大小不超过 2 KB'}

### 期望结果

提醒要上传的图片大小超过限制

### 实际结果

没有任何提醒和限制，任何大小的图片文件都可以被选中

### 基础库版本

2.30.0

### 补充说明

事实上我改用size-limit="{{ 2000 }}"的方式就可以弹出”图片大小超过限制“的提醒，并且图片不会被加入上传列表。查看该组件的源代码没有找到对SizeLimitObj类型的处理，不知道是否只是开发文档中定义，实际上还没有实现，或者是需要自己扩展实现

**Comment by sohow** [comment]
mark

**Comment by xiaodongning** [comment]
遇到同样的问题

**Comment by ven-y** [comment]
tdesign-miniprogram 版本^1.0.1该问题依旧存在，请问有修复计划吗？

**Comment by ven-y** [comment]
@anlyyao tdesign-miniprogram 版本1.0.1 该问题依旧存在，请问有修复计划吗？

**Comment by LeeJim** [comment]
下周的版本带上，我来处理
