### ISSUE TITLE
t-pull-down-refresh 组件的external-classes 属性不生效，样式并没有给到实际wxml上

### ISSUE THREAD

**Issue by qiaoshi123** [Tencent/tdesign-miniprogram#1571]
### tdesign-miniprogram 版本

1.0.0-rc.1

**Comment by anlyyao** [comment]
@qiaoshi123 麻烦提供一下你的代码片段～

**Comment by q8018414** [comment]
我感觉是用了官网说明的方式，直接用了external-classes赋值了一个数组。并没有直接赋值到后面说明的t-class里面
![image](https://user-images.githubusercontent.com/70793915/220283784-416ff564-eeef-4637-8578-b329f9fdba74.png)

**Comment by anlyyao** [comment]
> 我感觉是用了官网说明的方式，直接用了external-classes赋值了一个数组。并没有直接赋值到后面说明的t-class里面 ![image](https://user-images.githubusercontent.com/70793915/220283784-416ff564-eeef-4637-8578-b329f9fdba74.png)
试试这样，
```html
<t-pull-down-refresh t-class="test-class"></t-pull-down-refresh>
```

**Comment by oneronaner** [comment]
![image](https://github.com/Tencent/tdesign-miniprogram/assets/41769420/0ee92351-78c0-4b30-8912-1789fae05795)
```css
.test-class {
  color: red !important; 
}
```
试试这样，应该能解决，我刚刚解决了
