### ISSUE TITLE
[t-input] 代码演示与右侧预览内容不一致，缺少示例代码

### ISSUE THREAD

**Issue by Tomorrowxxy** [Tencent/tdesign-miniprogram#1577]
### tdesign-miniprogram 版本

1.0.0-rc.1

### 重现链接

https://tdesign.tencent.com/miniprogram/components/input?tab=demo

### 期望结果

预览内容中的代码应该完整的出现在代码演示中

### 实际结果

代码演示缺少内容

**Comment by china-live** [comment]
补充两个小问题
1.  align  和 tips 的文本方向应当一致，即：align非默认时，'right' 时，对应的 tips 也应该为 ‘right’，居中时同样。
2. 是否应当考虑集成 required  属性，否则就只有嵌入t-cell中或自定义label插槽

**Comment by china-live** [comment]
补充：编译器有警告提示
Two-way binding does not support complex data paths currently. This two-way binding is ignored.

**Comment by anlyyao** [comment]
@china-live  补充问题 2 ，我们讨论一下 看需不需要组件内部支持， 其余均修复在 #1585
