### ISSUE TITLE
[button] 自定义主题下，hover状态UI异常

### ISSUE THREAD

**Issue by WangBaoCaiGitHub** [Tencent/tdesign-miniprogram#1580]
### tdesign-miniprogram 版本

^1.0.0-rc.1

### 重现步骤

设置颜色

  --td-button-primary-bg-color: green;
  --td-button-primary-border-color: green;
--td-button-primary-active-bg-color: red;
--td-button-primary-active-border-color: red;

### 期望结果

hover状态按钮 背景和 border都为红色

### 实际结果

hover状态按钮 背景为红，border为绿

### 补充说明

.t-button--primary.t-button--hover::after 未支持border设置

两种解决方案：（个人偏向第一种）
1.  去除--hover::after的相关设置，然后新增 .t-button--primary.t-button--hover{ opacity: var(--td-button-primary-opacity, 0.4); }
2. 增加hover状态的 border，背景 以及文字颜色设置

**Comment by anlyyao** [comment]
@WangBaoCaiGitHub 已在pr #1530 补充 border 相关变量
