### ISSUE TITLE
t-grid 组建样式class控制

### ISSUE THREAD

**Issue by yhostc** [Tencent/tdesign-miniprogram#1582]
### tdesign-miniprogram 版本

1.0.0-rc.1

### 重现链接

官方示例

### 重现步骤

t-grid官网示例中，根据`class='block'`定义了样式，但是API描述中并无class属性的描述，翻阅了组建的props代码，亦无关于此属性。对于另外两个属性external-classes和custom-style，进行了尝试，但亦无办法控制。虽然可以直接覆盖`t-grid`样式，但这样的成本和用法，后期代码就没法看了。

### 期望结果

期望可以通过class属性控制样式

### 实际结果

无效

**Comment by LeeJim** [comment]
#1587 已修复此问题，欢迎升级至 1.0.0-rc.3
