### ISSUE TITLE
Swiper 无法指定点的颜色与选中颜色

### ISSUE THREAD

**Issue by computer-idol** [Tencent/tdesign-miniprogram#1592]
### 这个功能解决了什么问题

Swiper现在选中只有白色，不符合UI设计，需要改颜色

### 你建议的方案是什么

增加传入prop: indicator-color(指示点颜色),indicator-active-color(选中指示点颜色

**Comment by LeeJim** [comment]
有 CSS Variables 可用。
`--td-swiper-nav-dot-color`
`--td-swiper-nav-dot-active-color`
