### ISSUE TITLE
[Image] 组件状态自定义插槽状态有误

### ISSUE THREAD

**Issue by ElanYoung** [Tencent/tdesign-miniprogram#1596]
### tdesign-miniprogram 版本

1.0.0-rc.2

### 重现步骤

![WX20230214-213554@2x](https://user-images.githubusercontent.com/39727435/218754548-70d5e928-a8c4-4443-bbb8-8ed38880b246.png)

### 期望结果

1.0.0-rc.1版本没有此问题

### 实际结果

升级1.0.0-rc.2出现slot字眼

### 基础库版本

2.54.4

**Comment by LeeJim** [comment]
示例有误，已修改
