### ISSUE TITLE
[swiper] 圆角不能自定义

### ISSUE THREAD

**Issue by circlexia** [Tencent/tdesign-miniprogram#1597]
### 这个功能解决了什么问题

希望轮播图的圆角可以自定义数值

### 你建议的方案是什么

希望轮播图的圆角可以自定义数值

**Comment by LeeJim** [comment]
提供了 CSS Variables：`--td-swiper-radius`，可以修改这个试试

**Comment by bergkamp** [comment]
//取消圆角

page{
    --td-swiper-radius: 0px;
}
