### ISSUE TITLE
[DropdownMenu] 是否可以取消默认的下边框线条

### ISSUE THREAD

**Issue by Skye-0505** [Tencent/tdesign-miniprogram#1599]
### 这个功能解决了什么问题

会有和别的组件组合使用的场景，不太灵活。
![image](https://user-images.githubusercontent.com/33588563/218980724-77aca04b-e11f-48a4-9b16-2b50d897bd89.png)

### 你建议的方案是什么

是否可以考虑取消下拉菜单的下分割线。并且已经提供了分割线组件，如有需要，由使用者进行组装

**Comment by LeeJim** [comment]
我来跟进
