### ISSUE TITLE
DropdownMenu 下拉菜单-重置按钮

### ISSUE THREAD

**Issue by ysshull** [Tencent/tdesign-miniprogram#1603]
### 这个功能解决了什么问题

multiple设为多选时，重置按钮事件监听。close-on-click-overlay无效

### 你建议的方案是什么

1.建议增加重置按钮事件监听。
2.建议可以支持多列单选。
3.multiple设为多选时close-on-click-overlay 无效

**Comment by LeeJim** [comment]
1 可以直接增加
2 需要设计师介入，进度没这么快
3 和 #1613 重复，已修复

**Comment by LeeJim** [comment]
剩余的问题就是 单选多列，关注 #1303 就好
