### ISSUE TITLE
[back-top] 并不是滚动后显示，而是一直显示

### ISSUE THREAD

**Issue by deajax** [Tencent/tdesign-miniprogram#1604]
### tdesign-miniprogram 版本

^1.0.0-rc.1

### 重现链接

https://developers.weixin.qq.com/s/KgXwh3m276G2

### 重现步骤

代码片段：
[https://developers.weixin.qq.com/s/KgXwh3m276G2](https://developers.weixin.qq.com/s/KgXwh3m276G2)

没有步骤，随便放在一个能滚动的页面上就能重现

### 期望结果

一开始是隐藏的，页面滚动到某个阈值时才显示返回顶部按钮。且阈值可设置

### 实际结果

一直显示

### 基础库版本

2.30.0

**Comment by LeeJim** [comment]
好建议，确实可以内嵌这个能力。

**Comment by liuliuzx** [comment]
这个组件很有问题，样式没有。。而且定义theme也没用

> 👋 @deajax，感谢给 TDesign 提出了 issue。 请根据 issue 模版确保背景信息的完善，我们将调查并尽快回复你。

这个组件很有问题，样式没有。。而且定义theme也没用

**Comment by q8018414** [comment]
我一直以为本身就是这样设计的。。。

**Comment by ChaneyZhao** [comment]
认领back-top组件

**Comment by ChaneyZhao** [comment]
认领back-top组件
