### ISSUE TITLE
[Indexes 索引] 右侧快捷索引加载不出来，修改任何代码后才会加载出来

### ISSUE THREAD

**Issue by Obacm** [Tencent/tdesign-miniprogram#1605]
### tdesign-miniprogram 版本

1.0.0-rc.2

### 基础库版本

1.0.0-rc.2

**Comment by LeeJim** [comment]
感觉像是开发者工具的bug，重启即可

**Comment by Obacm** [comment]
还有个问题，现在加载出来右侧的索引了，点击事件也能打印出数据的，但是没有点击后产生的页面效果，没有选中效果，数据也没跟着索引走发自我的 iPhone在 2023年2月16日，21:39，leejimqiu ***@***.***> 写道：﻿
感觉像是开发者工具的bug，重启即可

**Comment by LeeJim** [comment]
麻烦提供下代码才能定位问题了。

**Comment by AURWQTyCle0u** [comment]
一直很难用，不但锚点组件没法用。现在捆绑cell-group，显示更慢，不用cell-group，代码质量还会报“不应存在无使用的组件 cell-group”。

**Comment by AURWQTyCle0u** [comment]
一样，这组件一直很怪。都是一样后台请求处理完数据，用官方、Vant啥的都没问题。这次1.0版本又试一下，现在还加上cell-group和cell，不用cell-group代码质量还会警告存在未使用的组件。
