### ISSUE TITLE
[t-tabs] 微信小程序使用了scroll-view 并开启自定义下拉后  吸顶失效

### ISSUE THREAD

**Issue by Abyss-QAQ** [Tencent/tdesign-miniprogram#1606]
### tdesign-miniprogram 版本

最新版本

### 重现步骤

<scroll-view refresher-enabled="true">
 <t-tabs value="{{activeTab}}" space-evenly="{{false}}" t-class="custom-tabs" bind:change="onTabsChange" swipeable sticky>
 </t-tabs>
</scroll-view>

refresher-enabled未开启时吸顶正常

### 基础库版本

2.30.0

**Comment by LeeJim** [comment]
需要通过 sticky-props 的 contianer 传入 scroll-view 这个节点
