### ISSUE TITLE
[image] image的error-slot必须输入空值是否有点多此一举？

### ISSUE THREAD

**Issue by q8018414** [Tencent/tdesign-miniprogram#1608]
### tdesign-miniprogram 版本

1.0.0-rc.2

### 重现步骤

在rc.2之前，image的error使用插槽必须定义error="slot",
在rc.2的更新中,
![image](https://user-images.githubusercontent.com/70793915/219365955-e516e2e4-0430-4b83-af4c-511c88763cee.png)
可是,实际情况中,若不传入slot值会加载默认值,导致与error的插槽并排显示。
![image](https://user-images.githubusercontent.com/70793915/219366371-b72179e5-6639-48ab-a795-58de805d1505.png)
感觉这样的赋值。更容易出问题。

**Comment by LeeJim** [comment]
那将默认值改成 '' 如何呢

**Comment by q8018414** [comment]
![image](https://user-images.githubusercontent.com/70793915/219380313-d665ab60-be32-4cf7-80f7-f99fa7535203.png)
![image](https://user-images.githubusercontent.com/70793915/219380368-fd9eb1a0-220b-45fe-9dfd-7c3e751a6eef.png)
本身是有一个默认值的。不知道微信小程序可以检测slot是否插入了没。如果能检测,这个应该需要多一个判断才行吧。。。现在传入空值就是为了走下面那个elif,将内容置空.

**Comment by q8018414** [comment]
> ''

@LeeJim 默认值为''就怎么都没有default的默认报错显示了吧。。。

**Comment by LeeJim** [comment]
我思考之后，确实原来的方式会更方便一些
