### ISSUE TITLE
[Tabs 选项卡] badge-props 只生效data初始化定义的值，this.setData设置该值 页面没变化

### ISSUE THREAD

**Issue by Obacm** [Tencent/tdesign-miniprogram#1612]
### tdesign-miniprogram 版本

^1.0.0-rc.2

### 基础库版本

1.0.0-rc.2

**Comment by LeeJim** [comment]
知道问题了，我来处理下。

**Comment by CorvusYe** [comment]
@Obacm @LeeJim 非常感谢，我今天也碰到了。更新到 v1.0.0-rc.3 没问题了，哈哈哈哈，很及时。
