### ISSUE TITLE
[DateTimePicker] 时间选择器组件能否支持过滤选项

### ISSUE THREAD

**Issue by haml-707** [Tencent/tdesign-miniprogram#1621]
### 这个功能解决了什么问题

![37d2f65b43a2f90c4334ea6c05259c1](https://user-images.githubusercontent.com/83055826/220239244-1083469a-f4ed-43a3-965f-3b01702dce89.png)
期望过滤掉不必要的选项，比如我只需要 10分钟为间隔，期望可以自定义。

### 你建议的方案是什么

提供filter 函数可以自己过滤选项。

**Comment by LeeJim** [comment]
感谢反馈。
间隔这个特性，我们有规划实现的。敬请期待

**Comment by LeeJim** [comment]
fixed by #1961
