### ISSUE TITLE
[navbar] capsule插槽屏蔽内部绑定的点击事件？

### ISSUE THREAD

**Issue by q8018414** [Tencent/tdesign-miniprogram#1622]
### tdesign-miniprogram 版本

1.0.0-rc.3

### 重现步骤

在rc.2版本中是可以点击的,更新到rc.3之后就不行了,经过重启工具,清除缓存,真机调试,上传体验版测试都不行。代码见图：
![1676966034166](https://user-images.githubusercontent.com/70793915/220282199-55b73fe8-3732-4b76-a7ce-fa1ee46358f9.png)
切换至left进行插入就能点击了。
![image](https://user-images.githubusercontent.com/70793915/220282693-4272136b-bb71-4ba8-8bcc-5fd0542a9813.png)

**Comment by LeeJim** [comment]
我来看看

**Comment by LeeJim** [comment]
已定位到问题，简单的处理方式：在 `custom-capsule` 上增加 `z-index: 1` 即可。

引发这个问题的原因是，原本使用 1rpx 的边框，但在一些机型会导致边框消失，因此 rc.3 的版本使用了 `:after` 的伪类来实现的，结果被这个伪类遮挡住了，无法触发点击事件。

**Comment by q8018414** [comment]
辛苦
