### ISSUE TITLE
使用 t-cell || t-stepper 时，报错：加载 woff 文件报错

### ISSUE THREAD

**Issue by CrossLee** [Tencent/tdesign-miniprogram#164]
**对应的组件**

t-cell 还是 t-stepper

**相关环境**

基础库版本：最新

运行环境：开发者工具 / iOS / Android 

**出现的问题**

见下图

**附加信息**

![image](https://user-images.githubusercontent.com/4584905/152687379-15d8369e-43d3-4d66-9d6d-81ef630b64f7.png)

**Comment by LeeJim** [comment]
字体是正常渲染的，这个错误是小程序官方的问题。
具体可以看官网描述：https://developers.weixin.qq.com/miniprogram/dev/api/ui/font/wx.loadFontFace.html
![image](https://user-images.githubusercontent.com/7017290/152946797-92b830aa-1aa0-47ac-924a-ab3cb8cd6489.png)
