### ISSUE TITLE
[t-input] 基础库2.18.1（在macos下最新版）外置样式描边下会在input的左上角，左下角出现短竖线

### ISSUE THREAD

**Issue by blackhu** [Tencent/tdesign-miniprogram#1640]
### tdesign-miniprogram 版本

1.0.0-rc.3

### 重现步骤

`<view>
  <t-input cursor-spacing="{{20}}" placeholder="输入消息..." borderless="{{true}}" clearable="{{true}}" style="border: 2rpx solid rgba(220,220,220,1);border-radius: 30rpx;height:20rpx;margin:40rpx;" />
</view>
`

### 实际结果

<img width="281" alt="image" src="https://user-images.githubusercontent.com/5728454/220578264-a4fbe941-ce04-40c6-8632-9abf14c11690.png">

<img width="463" alt="image" src="https://user-images.githubusercontent.com/5728454/221124511-b855bd7e-371a-46ab-bce9-d324f8f35edd.png">

### 框架版本

1.0.0-rc.3

### 基础库版本

2.18.1

### 补充说明

去掉t-input 自定义的css，border: 2rpx solid rgba(220,220,220,1); 就会无此故障，另外安卓与苹果均没有问题

**Comment by anlyyao** [comment]
@blackhu 基础库为2.18.1时，不会开启[virtualHost](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#%E8%99%9A%E6%8B%9F%E5%8C%96%E7%BB%84%E4%BB%B6%E8%8A%82%E7%82%B9)， style不仅会作用于自定义组件本身的那个节点（t-input）上，同时还会作为 properties 属性传递到组件根节点，于是就出现了你截图中的非预期结果。
这里提供2个解决思路，1. 提高基础调试库到2.19.2以上，开启virtualHost；2. 禁止使用style，改用customStyle

**Comment by blackhu** [comment]
收到，之前dom排查问题的时候就发现是这个问题，t-input本身也被自定义style渲染导致。也尝试过使用t-class-input="t-class-input-custom" 进行input原生组件的style（.input-example {
    --td-input-vertical-padding: 24rpx;

    background-color: #fff;
    padding: 32rpx 32rpx 16rpx;
}

.input-example__label {
    color: rgba(0, 0, 0, 0.9);
    font-size: 24rpx;
    line-height: 40rpx;
    margin: 0 8rpx 16rpx;
}

.t-class-input-custom{
    border: 2rpx solid rgba(220,220,220,1)  !important;
    border-radius: 12rpx  !important;
}）自定义，虽然多余的线条消失了。但是大部分的input原来的样式丢失了，效果不好。

目前升级基础库的主要痛点在于，影响用户群体主要集中在PC端，此端的基础库版本过低。

**Comment by anlyyao** [comment]
@blackhu 那建议 style的部分可以改用 customStyle实现，目前这两个API都是全量支持的
