### ISSUE TITLE
官网页面路径跳转有BUG

### ISSUE THREAD

**Issue by shiyuhefeng** [Tencent/tdesign-miniprogram#1650]
### tdesign-miniprogram 版本

1.0.0-rc.3

### 重现链接

https://tdesign.tencent.com/miniprogram/overview  

### 重现步骤

官网页面中组件概览  https://tdesign.tencent.com/miniprogram/overview  ，side-bar跳转出现问题  

### 期望结果

跳转到side-bar 侧边导航栏页面

### 实际结果

在原页面没跳转
猜测可能是路径错误，自动重定向到本页面了

### 补充说明

点开控制台中  路径中写的是 /miniprogram/components/sidebar
实际路径是 /miniprogram/components/side-bar
导致跳转有误

**Comment by anlyyao** [comment]
@shiyuhefeng 确实是路径错了， 感谢反馈，我这边尽快处理～
