### ISSUE TITLE
[CountDown] 除theme=default模式下不支持展示天数

### ISSUE THREAD

**Issue by LingWuYa** [Tencent/tdesign-miniprogram#1653]
### tdesign-miniprogram 版本

1.0.0-rc.2

### 重现步骤

<t-count-down time="{{ endCountTime }}" splitWithUnit format="DD天HH时mm分ss秒" t-class="end-count-down" theme="square"> </t-count-down>

### 期望结果

期望展示方块底的倒计时，如01天10时58分59秒

### 实际结果

10时58分59秒,无法展示天，将theme改成default则可以展示出天数

### 基础库版本

2.29.0

### 补充说明

无

**Comment by LingWuYa** [comment]
代码没发成功，再贴下~
<t-count-down time="{{ endCountTime }}" splitWithUnit format="DD天HH时mm分ss秒" t-class="end-count-down" theme="square"> </t-count-down>

**Comment by LingWuYa** [comment]
这里贴代码好像会被吞啊，
组件属性这么写没法展示天数：
format="DD天HH时mm分ss秒" theme="square"

**Comment by anlyyao** [comment]
> 这里贴代码好像会被吞啊， 组件属性这么写没法展示天数： format="DD天HH时mm分ss秒" theme="square"
```html
// 试试下面这段
<t-count-down format="DD:HH:mm:ss" content="default" time="{{time}}" theme="square"> </t-count-down>
```

**Comment by LeeJim** [comment]
正确用法：`<t-count-down format="DD:HH:mm:ss" content="default" time="{{time}}" theme="square" splitWithUnit />`

**Comment by LingWuYa** [comment]
> 正确用法：`<t-count-down format="DD:HH:mm:ss" content="default" time="{{time}}" theme="square" splitWithUnit />`

这位朋友，你自己试试填个大点的数字，看天数出不出得来

**Comment by anlyyao** [comment]
> > 正确用法：`<t-count-down format="DD:HH:mm:ss" content="default" time="{{time}}" theme="square" splitWithUnit />`
> 
> 这位朋友，你自己试试填个大点的数字，看天数出不出得来

哪里有问题？？

```html
    <t-count-down format="DD:HH:mm:ss" content="default" time="{{time}}" theme="square" />
    <view style="height: 20px"></view>
    <t-count-down format="DD:HH:mm:ss" content="default" time="{{time}}" theme="square" splitWithUnit />
```

```js
  data: {
    time: 96 * 60 * 1000 * 60 * 60,
  },
```

效果：
<img width="288" alt="截屏2023-03-08 10 14 12" src="https://user-images.githubusercontent.com/51158141/223602150-a4d7fe6b-034f-46e4-8bc5-2700bda2a87a.png">
