### ISSUE TITLE
t-stepper 样式问题

### ISSUE THREAD

**Issue by CrossLee** [Tencent/tdesign-miniprogram#166]
**对应的组件**

t-stepper & t-cell

**相关环境**

基础库版本：最新

运行环境：开发者工具 / iOS / Android 

**出现的问题**

t-cell 里的文字覆盖了 t-stepper 的 「➖」，无法点击减号。如下图

**附加信息**

![image](https://user-images.githubusercontent.com/4584905/152991790-75c10686-d185-47fb-88ab-cdf42e6903b0.png)

**Comment by LeeJim** [comment]
收到，这边尽快处理

**Comment by GAOGAO1994** [comment]
@CrossLee 将slot="note"改为slot="right-icon"可以解决覆盖问题
`<t-cell title="标题文字（单位）">
      <view class="cell-badge-wrap" slot="right-icon">
        <t-stepper defaultValue="0" step="2" />
      </view>
    </t-cell>`

**Comment by CrossLee** [comment]
> right-icon

@GAOGAO1994 谢谢，可以的。文档上没有关于这个 slot 属性说明，是否可以更新一下文档。

**Comment by LeeJim** [comment]
已修复，发布于 0.5.2
