### ISSUE TITLE
[button] 高亮颜色值字段错误

### ISSUE THREAD

**Issue by WangBaoCaiGitHub** [Tencent/tdesign-miniprogram#1662]
### tdesign-miniprogram 版本

^1.0.0-rc.3

### 重现步骤

.t-button--outline.t-button--primary.t-button--hover {
  color: var(--td-button-primary-outline-active-border-color, var(--td-primary-color-9, #0034b5));
}

### 期望结果

此处应该是： --td-button-primary-outline-active-color

**Comment by anlyyao** [comment]
@WangBaoCaiGitHub   `variant='outline'`情况下 文本和边框色一样，这里是直接共用一个变量了、

**Comment by horsley** [comment]
1.1.1 版本 outline 边框直接不显色 @anlyyao

**Comment by LeeJim** [comment]
> 1.1.1 版本 outline 边框直接不显色 @anlyyao

目前看没问题的了。如果还有问题麻烦 reopen 这个 issue
