### ISSUE TITLE
Textarea 多行文本框[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by biangwua** [Tencent/tdesign-miniprogram#1665]
### tdesign-miniprogram 版本

^1.0.0-rc.3

### 重现链接

这个Textarea Events到底应该怎么用？？我用bind:change根本监听不到这个事件啊！

### 期望结果

这个Textarea Events到底应该怎么用？？我用bind:change根本监听不到这个事件啊！

### 补充说明

这个Textarea Events到底应该怎么用？？我用bind:change根本监听不到这个事件啊！

**Comment by q8018414** [comment]
请贴上你的代码。我自己的项目目前正常监听。。

**Comment by biangwua** [comment]
> 请贴上你的代码。我自己的项目目前正常监听。。

你好 昨天我将工具回退到了Stable版本 可以正常监听了 目前来说是Nightly工具的Bug 所有自定义组件在json文件当中添加之后需要删除编译缓存后才能被注入界面 所有自定义组件的Events必须重启工具后才能生效 很麻烦

**Comment by q8018414** [comment]
确实。我也退回了。昨天老是要清理编译缓存。。。
&nbsp;


『無』
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月26日(星期天) 中午11:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tencent/tdesign-miniprogram] Textarea 多行文本框[组件名称] 描述问题的标题 (Issue #1665)





  
请贴上你的代码。我自己的项目目前正常监听。。
  
你好 昨天我将工具回退到了Stable版本 可以正常监听了 目前来说是Nightly工具的Bug 所有自定义组件在json文件当中添加之后需要删除编译缓存后才能被注入界面 所有自定义组件的Events必须重启工具后才能生效 很麻烦

**Comment by LeeJim** [comment]
看起来没什么问题，就先关闭了
