### ISSUE TITLE
[Tag] close与click一起触发了

### ISSUE THREAD

**Issue by Obacm** [Tencent/tdesign-miniprogram#1668]
### tdesign-miniprogram 版本

^1.0.0-rc.3

**Comment by Obacm** [comment]
准确的说是点击关闭按钮时点击事件也触发了

**Comment by anlyyao** [comment]
@Obacm  收到反馈，今天处理掉～

**Comment by zhangruofei** [comment]
现在还有这个问题

**Comment by zhangruofei** [comment]
问题是tag中点击x号的右侧才能监听到close，点击x号或者x号左侧都是click和close同时监听
