### ISSUE TITLE
 action-sheet  

### ISSUE THREAD

**Issue by Chenbicheng** [Tencent/tdesign-miniprogram#1670]
### tdesign-miniprogram 版本

0.33.0

### 重现步骤

微信小程序+ts 
1.import ActionSheet, { ActionSheetTheme } from 'tdesign-miniprogram/action-sheet/index';报错
2.
![截屏2023-02-27 11 52 07](https://user-images.githubusercontent.com/31608549/221470315-eb86e75d-d6db-4674-9bf7-0c475589c595.png)
![截屏2023-02-27 11 52 34](https://user-images.githubusercontent.com/31608549/221470355-ef434530-2e26-49e1-876a-84bbf24f8c29.png)

**Comment by LeeJim** [comment]
需要在 wxml 里补上：
`<t-action-sheet id="t-action-sheet" />`
