### ISSUE TITLE
[几乎所有交互组件] mac 桌面端小程序，弹出层后，没有阻止鼠标滚轮滚动底部页面

### ISSUE THREAD

**Issue by xiaweiss** [Tencent/tdesign-miniprogram#1684]
### tdesign-miniprogram 版本

最新版

**Comment by LeeJim** [comment]
由于目前小程序的设计是移动端的操作，所以只有触屏相关的事件，没有提供其他的操作事件。

**Comment by xiaweiss** [comment]
移动端小程序，是支持桌面版打开的。建议考虑

**Comment by LeeJim** [comment]
> 

问题在于小程序底层没有提供相关的事件，所以暂时是无法做到的
