### ISSUE TITLE
button 设置disabled 和 type=submit 还是会提交form表单的submit事件

### ISSUE THREAD

**Issue by xiaodongning** [Tencent/tdesign-miniprogram#1689]
### 重现链接
https://github.com/xiaodongning/pic/blob/main/image.png?raw=true

### 重现步骤
button 设置disabled 和 type=submit 还是会提交form表单的submit事件

### 期望结果
type=submit  设置disabled 后form 表单不提交submit事件

### 实际结果
按钮仍然会触发submit事件

| Environment | Info |
|---|---|
| 相关版本 | 1.0.0 |
| 框架版本 / 基础库版本 | 小程序 |
| 系统、浏览器 | 小程序开发者工具 |
| Node版本 |  |

**Comment by anlyyao** [comment]
@xiaodongning  收到反馈，我来跟进～
