### ISSUE TITLE
[input] 输入框clear事件当软键盘弹起是点击无效，无需要点击两次，第一次关闭软键盘

### ISSUE THREAD

**Issue by xiaodongning** [Tencent/tdesign-miniprogram#1702]
### tdesign-miniprogram 版本

1.0.0

### 期望结果

在软件盘弹起时 clear事件有效。是否可以参考vant 使用touchstart事件

### 实际结果

在软件盘弹起时 clear事件无效

**Comment by anlyyao** [comment]
@xiaodongning 感谢反馈 我看看哈～

**Comment by anlyyao** [comment]
@xiaodongning 我刚刚试了一下，没有复现“软键盘弹起时clear无效问题”，真机效果如下：另外 tap 是否要改成touchstart，这里我需要和交互设计师讨论一下，因为这里使用tap带来的交互是，手指触摸到clear图标并离开时，清除input内容，收起软键盘，而tuchstart的交互是，手指触摸即清除内容，软键盘不收起

**Comment by xiaodongning** [comment]
@anlyyao
好的，感谢。刚刚试一下确实是好的，是因为blur和clear事件一起用然后赋值问题导致的。版本是1.0.1。当时对比了是vant使用的是touchstart事件以为是这个问题。

**Comment by anlyyao** [comment]
@xiaodongning 已和设计师确认完毕，改用 touchstart，感谢你的反馈～，改动点会在下个版本带上，欢迎升级体验～。
