### ISSUE TITLE
[Message] Message 应该是独立关闭的

### ISSUE THREAD

**Issue by JQiue** [Tencent/tdesign-miniprogram#1708]
### tdesign-miniprogram 版本

1.0.0-rc.3

### 实际结果

每一个弹出的 Message 关闭时，都不应该影响后续弹出的 Message

**Comment by JQiue** [comment]
期望效果应该是新弹出的 Message 盖在前一个上面，而实际情况是，如果上一个 Message 关闭时，会影响新的 Message，时间够短的情况下

**Comment by anlyyao** [comment]
@JQiue 新上了一个 single 属性， single 为 false 时，支持同时开启多个message～
