### ISSUE TITLE
[ActionSheet] 触发selected 事件报错

### ISSUE THREAD

**Issue by JQiue** [Tencent/tdesign-miniprogram#1709]
### tdesign-miniprogram 版本

1.0.1

### 实际结果

![image](https://user-images.githubusercontent.com/45145407/222414687-00948626-1a88-4cf3-8459-329c1c69fe87.png)

### 基础库版本

2.30.1

**Comment by ElanYoung** [comment]
+1

**Comment by Xiaojiju** [comment]
+1

**Comment by LeeJim** [comment]
fixed by #1726
