### ISSUE TITLE
[Upload组件] 请问config这个设置应该怎么定义？有没有示例？只会JS 不太会TS 看不懂里面的interface

### ISSUE THREAD

**Issue by biangwua** [Tencent/tdesign-miniprogram#1712]
### tdesign-miniprogram 版本

^1.0.0

### 基础库版本

2.19.4

**Comment by anlyyao** [comment]
@biangwua 

```
// image
config: {
  count: 4,
  sizeType: 'original', 
  sourceType: 'album' 
}

**Comment by LeeJim** [comment]
可以理解是传入 `wx.chooseMedia` 的参数，具体可以通过官网查看支持的参数： https://developers.weixin.qq.com/miniprogram/dev/api/media/video/wx.chooseMedia.html
