### ISSUE TITLE
[textarea] 高度设置无效

### ISSUE THREAD

**Issue by gwokwong** [Tencent/tdesign-miniprogram#1713]
### tdesign-miniprogram 版本

微信开发者工具创建的最新版本

### 重现链接

No response

### 重现步骤

高度设置无效，在16.3的ios系统中。设置314rpx无效。至少有几千rpx

  .external-class {
    height: 312rpx;
  }
<view class="textarea-example" style="margin-top: 24rpx;">
    <t-textarea t-class="external-class" label="详细描述" placeholder="选填项" maxlength="200" indicator value="{{desc}}" bind:change="onDescInput" data-key="desc" disableDefaultPadding="{{true}}" style="{{style}}" />
</view>

### 期望结果

![image](https://user-images.githubusercontent.com/13887297/222499270-d542a904-3dd3-41d6-95f1-69133e71eb43.png)

### 实际结果

![image](https://user-images.githubusercontent.com/13887297/222499786-938d5a7c-1b1f-4399-bee4-d898c32d0392.png)

### 框架版本

3.2.0

### 基础库版本

2.11.3

**Comment by anlyyao** [comment]
@gwokwong  我使用了官网的“卡片样式”示例，在我的开发工具/预览/真机上一切正常，请确认您使用的是我们完整的示例吗？

测试机型： 13 pro， 16.3.1
![IMG_3419](https://user-images.githubusercontent.com/51158141/223377507-f8823996-0a5a-4547-9bc4-a7f0df768c2c.PNG)

**Comment by gwokwong** [comment]
class 样式冲突了
