### ISSUE TITLE
[非组件问题] 更新至1.0.1之后,有没有同学开启按需注入？报错。

### ISSUE THREAD

**Issue by q8018414** [Tencent/tdesign-miniprogram#1717]
### tdesign-miniprogram 版本

1.0.1

### 重现步骤

开启按需注入后,一直报错。之前的版本，报错一次就可以加载出来了。这次完全加载不出来了。。
微信开发工具版本号:1.06.2301160
项目基础库版本:2.27.3
不知道是我本地的问题还是代码的问题。真机调试没有问题。正常显示。。
`"lazyCodeLoading": "requiredComponents"`
![image](https://user-images.githubusercontent.com/70793915/222734127-088f5342-ff7e-4392-a578-b02f0b4cde7e.png)
有没有办法处理的呀？难道开发就只有关闭按需注入，发布的时候在加上？

**Comment by anlyyao** [comment]
@q8018414  把基础调试库多降几个版本试试

**Comment by anlyyao** [comment]
> @q8018414 把基础调试库多降几个版本试试
你是不是使用了一些微信提供的接口之类？ 我这边在mac在试了一下 没能复现你的问题

**Comment by q8018414** [comment]
就离谱，虽然啥代码没动。切换几次基础库之后它就好了。。用最新版本也可以了。太离谱了。。。
