### ISSUE TITLE
button组件使用primary主题loading动画不可见

### ISSUE THREAD

**Issue by 952795** [Tencent/tdesign-miniprogram#1718]
### tdesign-miniprogram 版本

1.0.1

### 重现步骤

在wxml中添加按钮如下：
`<t-button theme="primary"  size="large" loading="{{true}}" >加载中</t-button>`

### 期望结果

如图所示：
<img width="162" alt="7739ddc449b84530d57b2454f3cf5a3" src="https://user-images.githubusercontent.com/31022351/222755623-87401672-771c-44be-be3d-1bfe345852e3.png">

### 实际结果

实际结果表现为loading动画颜色未变为白色，动画不可见；当点击按钮时，可见较浅的动画出现

https://user-images.githubusercontent.com/31022351/222755698-2b5bc7eb-b67e-4011-ad14-d8107fac7963.mp4

### 框架版本

miniprogram4.4.0

### 基础库版本

229.2

**Comment by anlyyao** [comment]
@952795 我也试了一下 我这边是正常的 你能通过开发工具上传一下你的可复现代码片段吗

测试1.0.1版本：

https://user-images.githubusercontent.com/51158141/222763557-6bf477ea-b5c4-4ce4-b0bf-2f4147c864f6.mov

**Comment by 952795** [comment]
您好，我用代码片段试了一下，也是正常的，没有复现出来。查看原项目文件内全局设置没有相关的设置，laoding颜色在登录页时也正常，其他页面就是蓝色了。我再分析看看，感谢您的回复。

**Comment by 952795** [comment]
仍然没有找到颜色变为主题色#0052d9的原因，通过设置loading的color的方式暂时解决，再次感谢您的回复。

**Comment by lolhezihehe** [comment]
复现了一下，usingComponentsy引入组件时 `t-loading` 在 `t-button` 之前会出现  `t-button__loading--indicator` 被 `t-loading__spinner` 覆盖
```json
"usingComponents": {
    "t-loading": "tdesign-miniprogram/loading/loading",
    "t-button": "tdesign-miniprogram/button/button"
}
```
![image](https://user-images.githubusercontent.com/18699939/233837484-5b5586b5-014c-46e0-bbbe-7976c194c28d.png)

不过 `t-button__loading--indicator` 白色还是会出现 **variant=outline** 或者其他背景白色时也看不到，loading 应该始终和文本颜色保持一致，即 **inheritColor** 默认应该是true
