### ISSUE TITLE
[footer] 文档案例缺少them标签

### ISSUE THREAD

**Issue by echome123** [Tencent/tdesign-miniprogram#1719]
### tdesign-miniprogram 版本

1.0.0

### 重现链接

https://tdesign.tencent.com/miniprogram/components/footer

### 重现步骤

所有代码案例演示都没有them标签，复制案例过去执行一直都是空白，最后才发现是缺少了them标签。

### 期望结果

希望可以将案例文档补充完整

**Comment by anlyyao** [comment]
@echome123 footer的 theme 属性在1.0.0中已经移除了～ ， 其中logo属性优先text

**Comment by LeeJim** [comment]
@anlyyao 文档需要更新下，属性变更了，文档没有描述
