### ISSUE TITLE
[t-tabs] 左右滚动，安卓手机出现滚动条

### ISSUE THREAD

**Issue by WangBaoCaiGitHub** [Tencent/tdesign-miniprogram#1720]
### tdesign-miniprogram 版本

t-tabs

### 重现步骤

引用组件，组件项多设置一些，使其可左右滚动，
1. 从其他页面进入当前页面，会看到滚动条出现 并未消失
2. 左右滚动切换之后滚动条消失（滚动中也会出现）

### 期望结果

希望可以设置隐藏滚动条

**Comment by LeeJim** [comment]
duplicated of #1555
