### ISSUE TITLE
[image-viewer] 图片展示不全

### ISSUE THREAD

**Issue by hezhi3f** [Tencent/tdesign-miniprogram#1721]
### tdesign-miniprogram 版本

1.0.1

### 重现步骤

image-viewer图片不能完全展示

### 期望结果

<img width="201" alt="image" src="https://user-images.githubusercontent.com/58511226/222948843-e742075a-e11c-48b7-bea0-aee24b5eefc8.png">

### 实际结果

<img width="300" alt="image" src="https://user-images.githubusercontent.com/58511226/222948832-4722fb3a-c677-4e40-a7ef-e45fa407f561.png">

### 补充说明

图片不能按照原始大小进行展示

**Comment by anlyyao** [comment]
@hezhi3f   #1656 修复了，正在cr中，下个版本会带上～
