### ISSUE TITLE
[action-sheet ] 点击选项时报错 `this.trigger is not a function`

### ISSUE THREAD

**Issue by lxmfly123** [Tencent/tdesign-miniprogram#1724]
### tdesign-miniprogram 版本

1.0.1

### 重现步骤

完全按照官网文档编写，当点击 sheet 中的任意 item 时，控制台即可看到 `this.trigger is not a function` 的错误信息。

实际上，直接与官网的示例交互，也会产生这个错误。

**Comment by LeeJim** [comment]
和 #1709 是同个问题
