### ISSUE TITLE
[action-sheet] 点击项报错

### ISSUE THREAD

**Issue by WangBaoCaiGitHub** [Tencent/tdesign-miniprogram#1725]
### tdesign-miniprogram 版本

1.0.1

### 重现步骤

![image](https://user-images.githubusercontent.com/26473180/223051603-02a932be-6b34-4ff3-a5f7-d55202f0e468.png)
官方示例，点击选项报错，点击取消无法关闭

**Comment by LeeJim** [comment]
和 #1724 是同个问题
