### ISSUE TITLE
[t-tabs] 莫名其妙堵塞了程序，导致内容不能渲染

### ISSUE THREAD

**Issue by JQiue** [Tencent/tdesign-miniprogram#1729]
### tdesign-miniprogram 版本

1.0.1

### 重现步骤

在官网示例中也又出现

![image](https://user-images.githubusercontent.com/45145407/223315949-8ad70968-d023-4fc1-a39b-7ecc1d697d21.png)

### 基础库版本

2.30.2

**Comment by JQiue** [comment]
似乎是没有设置`defaultValue`属性有关

**Comment by LeeJim** [comment]
官网的示例是默认不展示内容的，如果问题还没解决，建议贴上代码
