### ISSUE TITLE
[Radio]直接引用与通过嵌套组件引用展示效果不同

### ISSUE THREAD

**Issue by snowtigersoft** [Tencent/tdesign-miniprogram#1741]
### 重现链接
https://github.com/snowtigersoft/tdesign_miniprogram

### 重现步骤
直接用微信开发工具打开仓库，替换appid。首页可以看到两组单选框展示出来不同的样式。上面一组的创建方式是引用了一个自定义组件“special”（复制的示例代码），下面一组是直接将radio组件写在wxml文件内。两个单选框组的代码内容完全一致，但是显示效果不同

### 期望结果
希望两种方式都能得到相同的显示效果

### 实际结果
参见图片：结果
<img width="425" alt="结果" src="https://user-images.githubusercontent.com/3327253/223582818-f1476dd9-bca4-4489-8121-2dbbcfcad789.png">

| Environment | Info |
|---|---|
| 相关版本 | 1.0.2 |
| 框架版本 / 基础库版本 | 小程序(2.20.2) |
| 系统、浏览器 | MacOS(13.2.1) |
| Node版本 | v16.9.1 |

**Comment by LeeJim** [comment]
应该是 icon 的样式没有正确赋值

**Comment by snowtigersoft** [comment]
可能不只是icon，排列也从横排变成了竖排

**Comment by LeeJim** [comment]
special 的样式复制完全了么

**Comment by LeeJim** [comment]
有问题再 reopen 吧，基于长时间没有回复，先关闭了
