### ISSUE TITLE
[popup] prevent-scroll-through 属性不能防止popup中的内容滚动穿透

### ISSUE THREAD

**Issue by GeraltWang** [Tencent/tdesign-miniprogram#1743]
### 重现链接
https://codepen.io/GeraldWang/pen/RwYLLrM

### 重现步骤
prevent-scroll-through 设置为true overlay可以防止滚动穿透 但是content区域不行

### 期望结果
prevent-scroll-through 属性能够防止popup中的内容滚动穿透，而不是只防止overlay

### 实际结果
prevent-scroll-through 属性不能防止popup中的内容滚动穿透（content区域）

### 补充说明
<t-popup visible="{{visible}}" prevent-scroll-through="{{true}}" close-on-overlay-click="{{false}}" bind:visible-change="onVisibleChange" placement="bottom">
  <view class="popup-block">
    <view class="popup-title">
      请选择
    </view>
    <view class="popup-content">
      <view wx:for="{{ popupItemList }}" wx:key="index" class="nav-item" bind:tap="onTapItem" data-item="{{item}}">
        <view class="nav-item-text">
          <view class="primary-text">
            <text class="primary">{{ item.primaryText }}</text>
            <t-icon name="chevron-right" size="48rpx"></t-icon>
          </view>
          <text class="secondary">{{ item.secondaryText }}</text>
        </view>
        <image class="logo" src="{{item.imgUrl}}" mode="aspectFill" />
      </view>
    </view>
  </view>
</t-popup>

| Environment | Info |
|---|---|
| 相关版本 | 1.0.2 |
| 框架版本 / 基础库版本 | 小程序(v2.30.2) |
| 系统、浏览器 | 微信小程序 |
| Node版本 |  |

**Comment by LeeJim** [comment]
内容区域的滚动穿透很难处理

**Comment by nightmaring** [comment]
被popup包裹的组件也有这个问题，如：日历。

通过已下方法可以解决，打开弹窗时设置wx.setPageStyle隐藏滚动条

```javascript
 wx.setPageStyle({
    style: {
      overflow: 'hidden'
    }
 })
```

关闭弹窗时，显示滚动条

```javascript
 wx.setPageStyle({
    style: {
      overflow: 'auto'
    }
 })
```

<br/>

开发者工具：1.06.2301160

微信：8.0.23

开发工具和苹果12测试效果正常，官网文档找不到wx.setPageStyle任何说明，所以不清楚兼容性如何，解决方法仅供参考。

**Comment by GeraltWang** [comment]
感谢回复，尝试了你描述的方法，在 popup 组件中结合 visible-change 事件和你提供的代码确实可以防止滚动穿透
想请问一下 在其他被popup包裹的组件 例如 Calendar / Picker 中需要怎么处理，这两个组件并没有 visible-change 事件，要如何判断切换时机？

**Comment by nightmaring** [comment]
> 感谢回复，尝试了你描述的方法，在 popup 组件中结合 visible-change 事件和你提供的代码确实可以防止滚动穿透 想请问一下 在其他被popup包裹的组件 例如 Calendar / Picker 中需要怎么处理，这两个组件并没有 visible-change 事件，要如何判断切换时机？

日历也一样，打开弹窗的时候overflow: 'hidden'，选中日期，或者关闭弹窗的时候overflow: 'auto'

**Comment by de1ck** [comment]
> 

这个方法为啥在官方文档里未找到，目前是通过page-meta组件实现的

**Comment by de1ck** [comment]
> 被popup包裹的组件也有这个问题，如：日历。
> 
> 通过已下方法可以解决，打开弹窗时设置wx.setPageStyle隐藏滚动条
> 
> ```js
>  wx.setPageStyle({
>     style: {
>       overflow: 'hidden'
>     }
>  })
> ```
> 
> 关闭弹窗时，显示滚动条
> 
> ```js
>  wx.setPageStyle({
>     style: {
>       overflow: 'auto'
>     }
>  })
> ```
> 
> 
> 开发者工具：1.06.2301160
> 
> 微信：8.0.23
> 
> 开发工具和苹果12测试效果正常，官网文档找不到wx.setPageStyle任何说明，所以不清楚兼容性如何，解决方法仅供参考。


这个方法为啥在官方文档里未找到，目前是通过page-meta组件实现的
