### ISSUE TITLE
[Tabs] 选项卡，选项超出页面宽度二页后，先滚动选项条，再点击无法自动滚动居中。

### ISSUE THREAD

**Issue by v10258** [Tencent/tdesign-miniprogram#1745]
### 重现链接
https://github.com/

### 重现步骤
			<t-tabs
				defaultValue=""
				space-evenly="{{false}}"
				bind:change="handleTopicChange"
			>
				<t-tab-panel label="推荐" value="" />
				<t-tab-panel  label="类目1" value="1" />
<t-tab-panel  label="类目2" value="2" />
<t-tab-panel  label="类目3" value="3" />
<t-tab-panel  label="类目4" value="4" />
<t-tab-panel  label="类目5" value="5" />
<t-tab-panel  label="类目6" value="6" />
<t-tab-panel  label="类目7" value="7" />
<t-tab-panel  label="类目8" value="8" />
<t-tab-panel  label="类目9" value="9" />
<t-tab-panel  label="类目10" value="10" />
<t-tab-panel  label="类目11" value="11" />
<t-tab-panel  label="类目12" value="12" />
<t-tab-panel  label="类目13" value="13" />
<t-tab-panel  label="类目14" value="14" />
<t-tab-panel  label="类目15" value="15" />
<t-tab-panel  label="类目16" value="16" />
<t-tab-panel  label="类目17" value="17" />
<t-tab-panel  label="类目18" value="18" />
<t-tab-panel  label="类目19" value="19" />
<t-tab-panel  label="类目20" value="20" />
			</t-tabs>

### 期望结果
拖动选项卡，点击选中子项后，自动居中，或出现在可视范围内。

### 实际结果
拖动选项卡，点击子项，选中未出现在可视范围内。

### 补充说明
图片名称

| Environment | Info |
|---|---|
| 相关版本 | 1.0.2 |
| 框架版本 / 基础库版本 | 小程序(2.17.1) |
| 系统、浏览器 | 小程序 |
| Node版本 |  v16.15.1 |

**Comment by v10258** [comment]
你好，请问这个bug什么时候能fixed? @LeeJim

**Comment by LeeJim** [comment]
现在处理下
