### ISSUE TITLE
[t-action-sheet] 多个选项未兼容

### ISSUE THREAD

**Issue by WangBaoCaiGitHub** [Tencent/tdesign-miniprogram#1756]
### tdesign-miniprogram 版本

1.0.2

### 重现步骤

设置选项过多，展示数据 无滚动，超出展示区域，且看不到取消按钮

### 期望结果

有最大高度显示，超出高度可以滚动选择

**Comment by pageee1021** [comment]
hello~在使用列表型动作面板时，我们不建议提供太多操作项，若过选项过多在小屏手机中导致需纵向滚动，体验并不是特别理想；类似情况可以考虑使用宫格展示以兼容更多选项，并且尽量控制选项数量
