### ISSUE TITLE
[ActionSheet] 在page页面使用报错 

### ISSUE THREAD

**Issue by luohc92** [Tencent/tdesign-miniprogram#1760]
### tdesign-miniprogram 版本

1.0.2

### 基础库版本

2.19.6

### 补充说明

在page页面引入  import ActionSheet, { ActionSheetTheme } from 'tdesign-miniprogram/action-sheet/index'; 后报错
Uncaught FrameworkError   APP-SERVICE-Engine:Please do not register multiple Pages in pages/*.js

**Comment by LeeJim** [comment]
看起来像是开发者工具的问题，重启开发者工具试试

**Comment by hmwdt** [comment]
碰到相同的问题，清空缓存，重启重装都试了

**Comment by luojh** [comment]
也碰到一样问题了，只要import了就报错
import ActionSheet, { ActionSheetTheme } from '/tdesign-miniprogram/action-sheet/action-sheet';
![image](https://user-images.githubusercontent.com/819119/230834741-1be18292-1b23-4a6a-befd-5efe592d44d8.png)

**Comment by LeeJim** [comment]
> 也碰到一样问题了，只要import了就报错 import ActionSheet, { ActionSheetTheme } from '/tdesign-miniprogram/action-sheet/action-sheet'; ![image](https://user-images.githubusercontent.com/819119/230834741-1be18292-1b23-4a6a-befd-5efe592d44d8.png)

地址错误了，正确的是：`import ActionSheet, { ActionSheetTheme } from 'tdesign-miniprogram/action-sheet/index';`
