### ISSUE TITLE
[NoticeBar] content为Slot时高度异常

### ISSUE THREAD

**Issue by q8018414** [Tencent/tdesign-miniprogram#1762]
### tdesign-miniprogram 版本

1.0.2

### 重现步骤

变量传入文本，高度正常22
![%CN@D~AC1G`~@{0Q{EEJTDP](https://user-images.githubusercontent.com/70793915/224476621-6399138d-29e8-4ccd-99bb-9c6808467fd5.png)
Slot传入View无class，无style，view高度为22，但t-notice-bar__content-wrap,t-class-content高度都为44
![P OPBHTEDG{PKV73`QZN5B](https://user-images.githubusercontent.com/70793915/224476623-2d56653c-7c0d-4c7c-8c69-daf17ea1292c.png)

**Comment by q8018414** [comment]
![P OPBHTEDG{PKV73`QZN5B](https://user-images.githubusercontent.com/70793915/224476742-7321517c-d4c9-422b-9ca6-c10dd9b997c1.png)
Slot传入时,高度异常

**Comment by q8018414** [comment]
![%CN@D~AC1G`~@{0Q{EEJTDP](https://user-images.githubusercontent.com/70793915/224476784-956cb1be-8dd3-4499-aca8-c3924c87c45a.png)
变量传入时正常。麻了，提交的时候丢了数据了？怎么跟我编辑的不一样呀。。

**Comment by anlyyao** [comment]
@q8018414 使用content插槽的时候，改用行内元素，别用块元素

**Comment by websHen-create** [comment]
> @q8018414 使用content插槽的时候，改用行内元素，别用块元素

使用行内元素高度更离谱了 设置样式display: inline-block  可以暂时解决高度问题，亲测有效

**Comment by anlyyao** [comment]
> > @q8018414 使用content插槽的时候，改用行内元素，别用块元素
> 
> 使用行内元素高度更离谱了 设置样式display: inline-block 可以暂时解决高度问题，亲测有效

我原来想说的是 可以用 p span 这些标签去包文本

**Comment by anlyyao** [comment]
那我这边先关闭issue啦～
