### ISSUE TITLE
[t-input] 粘贴长文本被截断了

### ISSUE THREAD

**Issue by sampsonliu** [Tencent/tdesign-miniprogram#1765]
### tdesign-miniprogram 版本

1.0.2

### 重现链接

https://tdesign.tencent.com/miniprogram/components/input

### 重现步骤

<img width="582" alt="image" src="https://user-images.githubusercontent.com/15682051/224532137-facad31d-67b3-4992-aac3-7db7ae42bced.png">
手机扫描这个二维码，将下面的长文本复制到第一个input输入框，发现被截断了一部分

**【“二战”期间，为了加强对战机的防护，英美军方调查了作战后幸存飞机上弹痕的分布，决定哪里弹痕多就加强哪里，然而统计学家沃德力排众议，指出更应该注意弹痕少的部位，因为这些部位受到重创的战机，很难有机会返航，而这部分数据被忽略了。事实证明，沃德是正确的。
要求：综合材料内容及含意，选好角度，确定立意，明确文体，自拟标题；不要套作，不得抄袭；不少于800字。】**

![image](https://user-images.githubusercontent.com/15682051/224532375-3fa0574d-5dc9-4a5e-a919-0e92b9ee3c95.png)

发现粘贴到“选好”就截止了

**Comment by anlyyao** [comment]
@sampsonliu 感谢反馈，二维码指向的是线上版本，我们的线上版本还处在1.0.1，忘记更新了。 这个问题在1.0.2版本已处理，可放心使用组件库～

**Comment by sampsonliu** [comment]
升级了版本，尝试了一下，没问题了
![image](https://user-images.githubusercontent.com/15682051/225261022-9f19b73c-5805-4163-8925-e183b8c8d940.png)
![image](https://user-images.githubusercontent.com/15682051/225262704-951278a6-8e05-407f-b90e-0809147223fc.png)
![image](https://user-images.githubusercontent.com/15682051/225262750-c3dd9f21-4524-4511-90b2-b3575e782114.png)

**Comment by anlyyao** [comment]
那我这边先关闭issue了，有问题在讨论～
