### ISSUE TITLE
自定义主题到底应该如何使用，可不可以提供一个demo

### ISSUE THREAD

**Issue by websHen-create** [Tencent/tdesign-miniprogram#1767]
### tdesign-miniprogram 版本

1.0.0

### 重现步骤
![image](https://user-images.githubusercontent.com/59082934/224599087-f628ac94-3236-4239-899e-a88a8bedc239.png)
![image](https://user-images.githubusercontent.com/59082934/224599137-f29b7cfe-4247-47eb-b38e-cc1e961c75e4.png)

### 期望结果

希望官方能提供一个自定义主题的demo（wxss/less）

### 基础库版本

2.26.0

**Comment by websHen-create** [comment]
刚才看了文档，是组件库版本的问题，升级了版本后，样式就生效了。官方文档 自定义主题部分--td-primary-color 最好添加个备注。比如：1.0.0之后的版本改为--td-brand-color，一目了然，没有必要去翻更新日志查找了

**Comment by LeeJim** [comment]
@websHen-create 感谢提议，我来处理下
