### ISSUE TITLE
[cell]  cell中 icon 添加 badge , badge 被遮挡

### ISSUE THREAD

**Issue by zhengchalei** [Tencent/tdesign-miniprogram#1768]
### tdesign-miniprogram 版本

1.0.2

### 重现步骤

``` html
 <t-cell>
      <view slot="description">
        {{user.description}}
      </view>
      <view slot="title">
        {{user.name}}
      </view>
      <view bindtap="handleClickUserInfo"  slot="left-icon">
        <t-avatar size="medium" image="{{user.avatar}}" />
      </view>
      <view slot="note">
        <t-badge count="{{messageCount}}" >
          <t-icon name="notification" size="70rpx" />
        </t-badge>
      </view>
    </t-cell>

```

### 期望结果

徽章上的count 正常显示出来

### 实际结果

![image](https://user-images.githubusercontent.com/31665079/224623825-7df77dfd-86e7-4381-9b53-5621d47f7233.png)

### 框架版本

"tdesign-miniprogram": "^1.0.2"

**Comment by anlyyao** [comment]
@zhengchalei 收到反馈，我这边处理一下～

**Comment by anlyyao** [comment]
@zhengchalei 已处理，会在下个版本带上，如果比较着急，可以先通过外部样式类 t-class-note 进行修改。

```html
<t-cell t-class-note="external-class-note" />
```

```css
.external-class-note{
  overflow: visible !important;
}
```

**Comment by zhengchalei** [comment]
> @zhengchalei 已处理，会在下个版本带上，如果比较着急，可以先通过外部样式类 t-class-note 进行修改。
> 
> ```html
> <t-cell t-class-note="external-class-note" />
> ```
> 
> ```css
> .external-class-note{
>   overflow: visible !important;
> }
> ```

好的。谢谢
