### ISSUE TITLE
[textarea] 设置 `autosize` 弹起键盘的时，文字被遮挡一部分

### ISSUE THREAD

**Issue by leon-fong** [Tencent/tdesign-miniprogram#1773]
### tdesign-miniprogram 版本

1.0.2

### 重现步骤

末尾加上 `autosize`

```html
<t-textarea label="标签文字" placeholder="请输入文字" disableDefaultPadding="{{true}}" autosize />
```

微信小程序搜索 【TDesign 组件库】选择 `输入` -> `Textarea 多行文本框` 
在 **自动增高多行文本框** 中 focus 文本框，此时文本框中的 placeholder 文字会向上移动一点距离并且会出现以下结果：

- placeholder 文字会被遮挡一部分（顶部）
- 同理，如果继续输入文字，也会被遮挡一部分（顶部）

<img height="365" align="center" alt="image" src="https://user-images.githubusercontent.com/45456105/224918619-c0f07317-997f-4b2c-8fd1-1b83f6085c36.png">

### 期望结果

不再遮挡文字

**Comment by fatchai1994** [comment]
相同问题，当键盘弹起时，textarea内的文字向上移动了半格

**Comment by anlyyao** [comment]
@fatchai1994 感谢反馈，已处理～
