### ISSUE TITLE
[Tarbar]在PC微信下样式异常

### ISSUE THREAD

**Issue by yhostc** [Tencent/tdesign-miniprogram#1776]
### tdesign-miniprogram 版本

^1.0.3

### 重现链接

https://github.com/yhostc/tdesign-tarbar-demo

### 重现步骤

1、clone 项目到本地
2、npm install
3、工具 > 构建npm
4、上传到公众号
5、手机扫码预览小程序，转发小程序到朋友或文件助手
6、通过电脑打开刚才转发的小程序，则看到样式异常。

### 期望结果

1、样式同手机一致
![WechatIMG4](https://user-images.githubusercontent.com/1823025/224952850-63c234dc-318f-4f12-b1a2-704aae833ee0.jpeg)

### 实际结果

样式失效，导致按钮挤压（疑似flex失效）

### 补充说明

同样的问题，在button组件上也存在
<img width="804" alt="Screenshot 2023-03-14 at 17 15 22" src="https://user-images.githubusercontent.com/1823025/224953343-c89a226e-dc00-4b47-92c4-44b3be197ac7.png">
<img width="787" alt="Screenshot 2023-03-14 at 17 15 34" src="https://user-images.githubusercontent.com/1823025/224953354-1886a547-6463-4869-9c0d-23821f61d249.png">

**Comment by yhostc** [comment]
若兼容pc，button 样式必须增加width属性，已经解决

**Comment by LeeJim** [comment]
感谢反馈哈，如果有解决方案，欢迎直接给我们提 PR

**Comment by horsley** [comment]
mac 开发者工具模拟器中出现同样异常

**Comment by vioao** [comment]
还是有这个问题

**Comment by LeeJim** [comment]
最新版已测试过，没有问题。欢迎升级看看，如果还有问题，麻烦 reopen 这个 issue。
<img width="492" alt="image" src="https://user-images.githubusercontent.com/7017290/236106463-a639f048-5dd4-4c86-b111-b8436069ed49.png">

**Comment by LeeJim** [comment]
已定位到问题的原因，应该是基础库版本低于 2.19.2 无法开启 virtualHost 导致的。
目前已在 1.1.7 版本中兼容修复了此问题
