### ISSUE TITLE
[loading] loading组件报错 str.slice is not a function 官方提供的demo也会

### ISSUE THREAD

**Issue by xiaodongning** [Tencent/tdesign-miniprogram#1777]
### tdesign-miniprogram 版本

1.0.2

### 重现步骤

使用 loading组件 开发者工具控制台会报错  str.slice is not a function。官方提供的demo也会

**Comment by cyuxlif** [comment]
碰到了同样的问题

**Comment by websHen-create** [comment]
使用loading组件到现在还真没遇到过，会不会是IDE版本或者基础库版本导致的？

**Comment by guohui1301** [comment]
更到到1.0.3，同样是loading后出现了这个问题
