### ISSUE TITLE
t-upload组件click事件不触发

### ISSUE THREAD

**Issue by 952795** [Tencent/tdesign-miniprogram#1778]
### tdesign-miniprogram 版本

1.0.3

### 重现链接

https://developers.weixin.qq.com/s/E98NXJmw7fGx

### 重现步骤

1.安装tdesign-miniprigram
2.导入代码片段
3.在handleclick处加断点
3.点击已选文件
4.查看断点是否触发

### 期望结果

点击已选图片可触发handleClick事件

### 实际结果

未触发handleClick事件

### 框架版本

4.4.0

### 基础库版本

2.30.3

**Comment by yaogengzhu** [comment]
晚点fix

**Comment by 952795** [comment]
收到，谢谢回复！
