### ISSUE TITLE
[Loading] 使用组件后，控制台报错

### ISSUE THREAD

**Issue by Zlianxin** [Tencent/tdesign-miniprogram#1785]
### tdesign-miniprogram 版本

1.0.3

### 重现步骤

引用 t-loading 组件之后，控制台就会报错。

### 期望结果

没有问题

### 实际结果

控制台报错，错误信息是
[渲染层错误] TypeError: str.slice is not a function
    at endsWith
    at anonymous function
    at Array.map
    at _style
    at ./miniprogram_npm/tdesign-miniprogram/loading/loading.wxml:3:9(env: Windows,mp,1.06.2301160; lib: 2.19.4)

### 框架版本

小程序

### 补充说明

应该是 wxs 有问题

**Comment by yaogengzhu** [comment]
duplicate #1777
