### ISSUE TITLE
[t-radio] placement属性失效

### ISSUE THREAD

**Issue by Zlianxin** [Tencent/tdesign-miniprogram#1786]
### tdesign-miniprogram 版本

1.0.2

### 重现步骤

```
<t-radio-group>
  <t-radio icon="line" placement="right">
    这是一个选项
  </t-radio>
</t-radio-group>
```

### 期望结果

radio的对号可以显示在右侧

### 实际结果

radio的对号显示在左侧

### 框架版本

小程序

### 补充说明

看了一下源码，发现是在 t-radio-group 层，给 placement 设置了默认值 left，之后在 t-radio 层设置 placement 没有生效，两者的优先级有问题，t-radio的优先级要比t-radio-group高才对

**Comment by yaogengzhu** [comment]
都存在默认值的情况下，这个优先级判断有点难顶呀？
groupRadio  right      子组件默认是left  无法知道是用户传递了left

**Comment by LeeJim** [comment]
我来处理下
