### ISSUE TITLE
[DateTimePicker] 该组件能否增加控制时间间隔步进的参数

### ISSUE THREAD

**Issue by Richuanwu** [Tencent/tdesign-miniprogram#1789]
### 这个功能解决了什么问题

选择时间情况下，是否可以考虑使用自定义步进间隔，这样就不用一分钟一分钟的滑动。

### 你建议的方案是什么

增加可控制参数

**Comment by china-live** [comment]
我也需要这个功能，我们做了一个企业车辆预约使用的功能，大多数时候不需要精确到分钟，不要分以整数小时又太长，一般设置步长为10分钟或5分钟。
