### ISSUE TITLE
[t-button] 最新版本 1.0.3 disableb 对 控制tap无效

### ISSUE THREAD

**Issue by benbenbingbing** [Tencent/tdesign-miniprogram#1797]
### tdesign-miniprogram 版本

1.0.3

### 重现步骤

原因为这个地方应该加个单引号

## IssueShoot
- 预估时长: 1
- 期望完成时间: 2023-03-23 00:00:00 +0000 UTC
- 开发难度: 低
- 参与人数: 1
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by benbenbingbing** [comment]
![image](https://user-images.githubusercontent.com/42106540/225833302-b3269882-2f73-4057-b58f-328e49f3a73c.png)

**Comment by speauty** [comment]
我也遇到这个问题了，正说提个issue呢
