### ISSUE TITLE
[t-swiper] 希望支持：轮播图点击后放大手动切换查看图片，类似ImageViewer

### ISSUE THREAD

**Issue by CrossLee** [Tencent/tdesign-miniprogram#1811]
### 这个功能解决了什么问题

轮播图一般限制版面大小，若查看图片细节需要点击轮播图图片放大查看。

### 你建议的方案是什么

结合 ImageViewer 默认实现。

**Comment by LeeJim** [comment]
swiper 已经支持 click 事件。可以自行结合 `wx. previewImage` 使用。
组件内部是不适合做这个封装的
