### ISSUE TITLE
[t-input]type='nickname'时，用户点击微信昵称，但是input的value没有更新

### ISSUE THREAD

**Issue by GeraltWang** [Tencent/tdesign-miniprogram#1814]
### tdesign-miniprogram 版本

1.0.3

### 重现链接

https://codepen.io/GeraldWang/pen/LYJBKrE

### 重现步骤

使用t-input type='nickname' 时，用户点击键盘上方的微信昵称，昵称会出现在input框中，但是input绑定的value并没有值。

### 期望结果

用户点击昵称后，input绑定的value值应当更新

### 实际结果

用户点击昵称后，input绑定的value并没有更新

### 基础库版本

2.30.2

## IssueShoot
- 预估时长: 1
- 期望完成时间: 2023-03-23 00:00:00 +0000 UTC
- 开发难度: 低
- 参与人数: 1
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by haochenli** [comment]
这个case我觉着没啥问题。。。

**Comment by labidc** [comment]
我也有这个问题， tdesign-miniprogram 版本 1.0.0 ，基础库也是 2.30.2
双向绑定，表单提交，都是以前的值。
也就是说，input 视图上展示是 type='nickname' 弹窗选择的值，但是通过双向绑定或者表单提交都无法获取正确值。

**Comment by GeraltWang** [comment]
我是郁闷，微信原生的input组件点击用户昵称就能获取到数据，为何t-design的就不行。。。

**Comment by labidc** [comment]
我昨天确定的，微信开发者工具里面有这个问题，但是真机调试没有这个问题，你可以试试看，如果真机没问题，暂时先不管他。

**Comment by haochenli** [comment]
@LeeJim 这个可以关了应该

**Comment by LeeJim** [comment]
@haochenli 感谢
