### ISSUE TITLE
input输入框左侧label无法使用

### ISSUE THREAD

**Issue by HavocZhang** [Tencent/tdesign-miniprogram#182]
**对应的组件**

input

**相关环境**

基础库版本：最新

运行环境：开发者工具 / iOS / Android 

**出现的问题**

label solt无法使用

**Comment by zhenzhencai** [comment]
使用方法参考，记得加slot="name"
<t-input name="slot" placeholder="请输入文字">
      <text slot="name">标签文字<text style="color: #e34d59"> *</text> </text>
</t-input>

**Comment by zhenzhencai** [comment]
已处理
