### ISSUE TITLE
[框架支持] 支持 kbone

### ISSUE THREAD

**Issue by liudonghua123** [Tencent/tdesign-miniprogram#1824]
### 这个功能解决了什么问题

目前使用原生的小程序开发略显繁琐，一些基于vue、react的小程序开发框架很多，例如腾讯官方的[kbone](https://github.com/Tencent/kbone)、京东的[taro](https://github.com/NervJS/taro)、[taro-ui](https://github.com/NervJS/taro-ui)等等，如果可以支持kbone，那么开发起来就会方便很多。

### 你建议的方案是什么

提供类似于[kbone-ui](https://github.com/wechat-miniprogram/kbone-template-kboneui)的 `kbone-ui-tdesign`

**Comment by LeeJim** [comment]
目前暂无计划支持 kbone，目前主要精力在完善组件库的基础能力
