### ISSUE TITLE
[t-grid] 关于t-class-image不能正常修改图片大小的问题。

### ISSUE THREAD

**Issue by KaleidosChen** [Tencent/tdesign-miniprogram#1829]
### tdesign-miniprogram 版本

1.0.4

### 重现步骤

```
<view class="com_container">
  <view class="com_title">评测相关</view>
  <t-grid class="block com_item" column="{{2}}" theme="card">
    <t-grid-item image="{{item.img}}" wx:for="{{foodsList}}" wx:key="index" bindtap="goToPage" data-url="{{item.url}}" t-class-image="icon" />
  </t-grid>
</view>
```

.icon {
  width: 300rpx !important;
  height: 300rpx !important;
}

### 期望结果

能正常修改gird-item的图片大小，实现一排2个图片都已300rpx宽高。

### 实际结果

一排2个图片都为96rpx宽高，而图片的父元素有.icon类和.t-class-image,图片的父元素有300rpx宽高，图片image标签没有icon类，image标签的宽高都为96rpx

### 基础库版本

2.30.2

**Comment by LeeJim** [comment]
这个问题我来修复一下。
另外提供个别的方式给你，可以修改 css variables 来实现你的需求：
```css
--td-grid-item-image-width
--td-grid-item-image-height
```

**Comment by lolhezihehe** [comment]
> 

`--td-grid-item-image-width` 是无效的，会被 `.t-grid-item__image--middle` 重置，应该提供 `--td-grid-item-image-middle-width`
