### ISSUE TITLE
[button] type="submit"时，disabled未生效

### ISSUE THREAD

**Issue by WangBaoCaiGitHub** [Tencent/tdesign-miniprogram#1848]
### tdesign-miniprogram 版本

1.1.0

### 重现步骤

<img width="578" alt="image" src="https://user-images.githubusercontent.com/26473180/228105913-eb655d2c-7081-45b5-89b0-327e91a1509c.png">
type未考虑禁用的情况，open-type 考虑了

## IssueShoot
- 预估时长: 1
- 期望完成时间: 2023-03-31 00:00:00 +0000 UTC
- 开发难度: 低
- 参与人数: 1
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by meiqi502** [comment]
认领
