### ISSUE TITLE
[t-picker] 绑定value属性，选中值后再次打开时选中状态未保留在options中

### ISSUE THREAD

**Issue by Skye-0505** [Tencent/tdesign-miniprogram#1850]
### tdesign-miniprogram 版本

1.1.0

### 重现步骤

选中“纠正性维护”，再次打开时，option的选中项非“纠正性维护”
![image](https://user-images.githubusercontent.com/33588563/228150140-f9383f43-4c76-4e92-a6f3-a75bb8d80a45.png)

### 期望结果

再次打开时，“纠正性维护”为选中态

### 实际结果

再次打开时，默认options的第一项为选中态

### 基础库版本

2.25.2

**Comment by ChenJiaJian96** [comment]
+1 遇到了同样的问题
