### ISSUE TITLE
[navbar] 可以内容区之上渲染到页面，但是是无法替换原有的navbar

### ISSUE THREAD

**Issue by blackhu** [Tencent/tdesign-miniprogram#1852]
### tdesign-miniprogram 版本

1.0.4

### 重现链接

#

### 重现步骤

nav.json
`{
  "component": true,
  "usingComponents": {
    "t-navbar": "tdesign-miniprogram/navbar/navbar",
    "t-image": "tdesign-miniprogram/image/image",
    "t-icon": "tdesign-miniprogram/icon/icon"
  }
}`

nav.wxml
`<t-navbar class="custom-navbar" title="自定义标题"></t-navbar>`

### 实际结果

<img width="381" alt="image" src="https://user-images.githubusercontent.com/5728454/228411443-59f5b1d5-9c06-4115-8872-9687e2d8f109.png">

### 基础库版本

2.30.0

**Comment by LeeJim** [comment]
需要修改 app.json 的配置。
<img width="979" alt="image" src="https://user-images.githubusercontent.com/7017290/228417525-8a8c3ffe-3fca-4a30-aa07-1b9c43efbed7.png">
