### ISSUE TITLE
[t-textarea] iOS下单行内容没有垂直居中

### ISSUE THREAD

**Issue by zxz054321** [Tencent/tdesign-miniprogram#1859]
### 重现链接
https://github.com/zxz054321/chatgpt-miniprogram/blob/58b94989b3b72b68f7d89b45361c9f4eb0501f3b/miniprogram/pages/index/index.wxml#L55

### 重现步骤
1、在微信开发者工具编译构建小程序：https://github.com/zxz054321/chatgpt-miniprogram
2、使用iOS真机调试功能
3、定位到textarea的内层元素，发现内容只有单行时，由于行高比文字大，文字顶端对齐了行高
（TDesign官方的演示小程序中的textarea也有同样问题）

### 期望结果
文字垂直居中对齐行高

### 实际结果
文字顶端对齐了行高
![image](https://user-images.githubusercontent.com/7540550/228728275-457f80e8-6759-46be-a64c-a1f91c7526e2.png)
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/7540550/228728155-20bb1901-e063-4acb-bc6c-da0db147d53e.png">

| Environment | Info |
|---|---|
| 相关版本 | 1.1.0 |
| 框架版本 / 基础库版本 | 小程序(v2.19.6) |
| 系统、浏览器 | iOS(16.3.1) |
| Node版本 |  |

**Comment by anlyyao** [comment]
@zxz054321 我这边看了一下，应该是button将容器的高度撑开了，而textarea会去自适应容器高度，所以在视觉上出现了行高问题，你可以试着将button的尺寸改小一些

**Comment by zxz054321** [comment]
> @zxz054321 我这边看了一下，应该是button将容器的高度撑开了，而textarea会去自适应容器高度，所以在视觉上出现了行高问题，你可以试着将button的尺寸改小一些

将button的尺寸改小一些的做法很多时候不能满足业务需求，但根据您的提示，我把textarea包进了一个container，再用flex居中，问题成功解决，感谢。
https://github.com/zxz054321/chatgpt-miniprogram/commit/ac6c084795f6aca78d3438ab0b2c58a7518bece9
