### ISSUE TITLE
Tabs 选项卡切换问题

### ISSUE THREAD

**Issue by dofuer** [Tencent/tdesign-miniprogram#1862]
### tdesign-miniprogram 版本

1.1.0

### 重现步骤

使用tab切换或者默认value时，页面都会显示之前的内容，直接覆盖上去，前面的panel内容并不会消失，使用value或者defaultValue都是如此，使用动态参数也是如此，代码如下：
  <t-tabs value="{{1}}" bind:change="onTabsChange" bind:click="onTabsClick" t-class="custom-tabs">
    <t-tab-panel label="选项" value="0">123</t-tab-panel>
    <t-tab-panel label="选项" value="1">333</t-tab-panel>
  </t-tabs>

### 基础库版本

2.30.2

**Comment by dofuer** [comment]
退回到1.0.4的版本是好的

**Comment by holys** [comment]
我也遇到了，tab1 的内容会跑到 tab2 去。

**Comment by LeeJim** [comment]
非常抱歉，已经在 #1853 解决了这个问题

**Comment by holys** [comment]
手动 PATCH 了代码，我这边没问题了，感谢~

**Comment by LeeJim** [comment]
更新到 1.1.1  即可

**Comment by c1ngular** [comment]
1.1.2 问题依旧存在

**Comment by michaellee123** [comment]
问题依然存在
