### ISSUE TITLE
[t-row/t-col] props支持传入单位

### ISSUE THREAD

**Issue by lolhezihehe** [Tencent/tdesign-miniprogram#1869]
### 这个功能解决了什么问题

前端开发时有可能使用的是rpx布局，gutter只支持px不能满足设计需求

### 你建议的方案是什么

支持传入单位

**Comment by LeeJim** [comment]
布局组件可以理解是栅格系统，24等分的，如果需要具体 rpx 的话就不建议使用这个组件了

**Comment by lolhezihehe** [comment]
> 布局组件可以理解是栅格系统，24等分的，如果需要具体 rpx 的话就不建议使用这个组件了

如果是h5就自己转px->rem了，小程序可以传rpx的话更方便
