### ISSUE TITLE
[t-navbar] 标题无法居中 并且高度塌陷

### ISSUE THREAD

**Issue by nanhupatar** [Tencent/tdesign-miniprogram#1874]
### tdesign-miniprogram 版本

1.1.1

### 重现步骤

"tdesign-miniprogram": "^1.1.1"
<img width="442" alt="image" src="https://user-images.githubusercontent.com/27266016/229991327-7912e647-b5c7-4b82-b4b9-e06622b88e4e.png">

**Comment by LeeJim** [comment]
麻烦提供下代码看看？

**Comment by Muse-1996** [comment]
```
<t-navbar>
  <view slot="left">
    <t-image t-class="custom-image" src="https://tdesign.gtimg.com/miniprogram/images/logo1.png" aria-label="导航栏图片" />
  </view>
</t-navbar>
<view>
 页面内容
</view>
```

![image](https://user-images.githubusercontent.com/22572439/230873130-bcba6a92-ef71-4518-a33d-44e16f73a7d5.png)

```
<t-navbar title="帖子详情">
	<view slot="capsule" class="custom-capsule">
		<t-icon
		 size="20"
		 bind:tap="onBack"
		 aria-role="button"
		 aria-label="返回"
		 name="chevron-left"
		 class="custom-capsule__icon"
		/>
		<t-icon
		 size="20"
		 bind:tap="onGoHome"
		 aria-role="button"
		 aria-label="首页"
		 name="home"
		 class="custom-capsule__icon"
		/>
	</view>
</t-navbar>
<view>
 页面内容
</view>
```
![image](https://user-images.githubusercontent.com/22572439/230873403-e1f927fa-05d3-449c-95ce-4e6f70a91cc6.png)

@LeeJim

**Comment by LeeJim** [comment]
感觉是版本问题，你重新安装了 npm 之后需要点击“构建 npm”
另外，胶囊样式需要复制示例里的 css

**Comment by Muse-1996** [comment]
![image](https://user-images.githubusercontent.com/22572439/231049485-9e8fe452-dc15-404a-9596-0f2480f3b4d3.png)

重新构建了npm，补全了样式
@LeeJim

**Comment by Muse-1996** [comment]
![image](https://user-images.githubusercontent.com/22572439/231050345-50c1a4db-f1d3-4013-b73d-f0f37c21ce91.png)
![image](https://user-images.githubusercontent.com/22572439/231050373-2c169c05-e894-48da-bba2-93701a329f5a.png)
![image](https://user-images.githubusercontent.com/22572439/231050415-c7e43989-a870-43a8-8a66-73714ce10d65.png)

**Comment by nanhupatar** [comment]
@LeeJim

**Comment by LeeJim** [comment]
垂直居中的问题，已经在 1.1.3 中修复了。
另外高度塌陷，有两个可能：
- navbar 不是最上面的元素
- fixed 不等于 true？

**Comment by L-Chris** [comment]
1.4.5还是有这个问题，神奇

**Comment by menocrat** [comment]
> 1.4.5还是有这个问题，skyline有问题，webview没问题

一样的问题
