### ISSUE TITLE
[t-sticky] 结合t-navbar时使用无法以t-navbar下边缘为吸顶位置

### ISSUE THREAD

**Issue by CrossLee** [Tencent/tdesign-miniprogram#1877]
### tdesign-miniprogram 版本

1.1.0

### 重现步骤

wxml:
```
<t-navbar title="配对成功" />
<t-sticky>
  <t-notice-bar visible="{{tip.visible && joinedScene}}" marquee="{{tip.marquee}}" content="{{tip.content}}" prefixIcon="user-talk" bind:click="click"></t-notice-bar>
</t-sticky>
```

ts:
```
data: {
    tip: {
      visible: true,
      content: "请查看对方信息并选择",
      marquee: {
        speed: 80,
        loop: 0,
        delay: 0,
      }
    }
}
```

滚动后，<t-sticky> 没有默认吸顶到 t-navbar 下方。

### 期望结果

在有 t-navbar 标签时，希望能默认吸顶至 t-navbar 底部。
ps：虽然可以通过 offset-top 手动指定，但是还是需要计算 t-navbar 高度后才能达到目的，不是很方便。

### 实际结果

https://user-images.githubusercontent.com/4584905/230355184-8cb55e2f-db45-404c-a977-91c540d1d0e9.mp4

### 补充说明

通过 t-sticky 包住 t-notice-bar 达到在页面滚动后，时刻显示提醒信息，如上述视频。

**Comment by LeeJim** [comment]
这种场景为啥要用 sticky，直接 fixed 布局不就好了？

**Comment by CrossLee** [comment]
> 这种场景为啥要用 sticky，直接 fixed 布局不就好了？

可以的

ps: tdesign 用多了，第一时间想到的居然是 sticky 组件。。

**Comment by LeeJim** [comment]
> > 这种场景为啥要用 sticky，直接 fixed 布局不就好了？
> 
> 可以的
> 
> ps: tdesign 用多了，第一时间想到的居然是 sticky 组件。。

:) 那没啥问题，就先关闭啦。
