### ISSUE TITLE
[Cell] bordered="false" doesn't take effect

### ISSUE THREAD

**Issue by CrossLee** [Tencent/tdesign-miniprogram#188]
### 重现链接
https://codepen.io/huxiweng/pen/jOazYYv

### 重现步骤
https://tva1.sinaimg.cn/large/e6c9d24egy1gzkf4dgzlrj21xd0u0qbk.jpg

### 期望结果
按 API 描述，不显示下边框

### 实际结果
显示下边款

| Environment | Info |
|---|---|
| 相关版本 | 0.5.2 |
| 框架版本 / 基础库版本 | 小程序 v2.14.1 |
| 系统、浏览器 | macOS 12.2.1/Chrome 98.0.4758.102 |
| Node版本 |  |

**Comment by LeeJim** [comment]
收到，我这边看看

**Comment by LeeJim** [comment]
你的语法错了。应该是：`bordered="{{false}}"`
