### ISSUE TITLE
征集使用 TDesign 的优秀项目

### ISSUE THREAD

**Issue by weizhiyong05** [Tencent/tdesign-miniprogram#1881]
- 小程序名称：微名帖
- 小程序码
- 
![gh_5ef726bff720_344](https://user-images.githubusercontent.com/32725718/230569281-81e2b533-522e-442d-bd3f-ec9d882bee80.jpg)
- 页面截图
![详情页页 - 副本](https://user-images.githubusercontent.com/32725718/230569838-579db5f3-ad16-4c5e-a4ba-1f2941561fef.jpg)

**Comment by LeeJim** [comment]
麻烦补充到：https://github.com/Tencent/tdesign-miniprogram/discussions/1094
