### ISSUE TITLE
[t-navbar] 安装好Tdesign之后,引入组件异常

### ISSUE THREAD

**Issue by lixunhui** [Tencent/tdesign-miniprogram#1883]
### tdesign-miniprogram 版本

 "tdesign-miniprogram": "^1.1.1"

### 重现步骤

报错信息
<img width="796" alt="image" src="https://user-images.githubusercontent.com/4917509/230736770-8e0549b5-33d1-4c67-a6b9-a22d4f37591c.png">

项目结构:
<img width="324" alt="image" src="https://user-images.githubusercontent.com/4917509/230736837-e8f5305f-f0b0-4dea-b01c-3978ddcbcfeb.png">

**Comment by ElanYoung** [comment]
微信开发者工具 -> `清缓存` -> `清除编译缓存`

**Comment by LeeJim** [comment]
看起来是开发者工具的问题

**Comment by nanhupatar** [comment]
清除了缓存依旧失败 ，反而用vant weapp没问题 ，定位一下这个吧，高度塌陷

**Comment by LeeJim** [comment]
> 清除了缓存依旧失败 ，反而用vant weapp没问题 ，定位一下这个吧，高度塌陷

能否提供个代码来看看？
