### ISSUE TITLE
[Picker] 通过visible属性控制Picker隐藏时，屏幕偶现闪烁

### ISSUE THREAD

**Issue by websHen-create** [Tencent/tdesign-miniprogram#1891]
### tdesign-miniprogram 版本

1.0.2

### 重现步骤

通过visible属性控制Picker隐藏

### 期望结果

屏幕不闪烁

### 基础库版本

2.29.2

**Comment by LeeJim** [comment]
可以录频来看看么，也麻烦提供下设备信息
