### ISSUE TITLE
需要一个自适应剩余空间的 `scroll` 组件

### ISSUE THREAD

**Issue by evanlong0926** [Tencent/tdesign-miniprogram#1892]
### 这个功能解决了什么问题
1. 自动撑满剩余空间，不需要自己每次遇到同样场景去手动计算
2. 显示友好的主题色滚动条，平滑滚动支持
3. 支持横向自动撑满、纵向自动撑满

### 没有这个功能产生了什么问题

1. 目前微信社区没有更好的实现方案
2. 自己封装很头疼
3. 经常遇到的场景

### 你建议的方案是什么

https://developers.weixin.qq.com/community/develop/article/doc/000c64fa50080829210df932056013

**Comment by LeeJim** [comment]
第1点就很难处理，作为一个组件，没办法获取外部的布局以及尺寸。
这个需求，没办法满足
