### ISSUE TITLE
[t-navbar]  slot="left"时不能设置标题最大字数

### ISSUE THREAD

**Issue by lixunhui** [Tencent/tdesign-miniprogram#1896]
### tdesign-miniprogram 版本

1.1.1

### 重现步骤

    <t-navbar class="custom-navbar" left-arrow bind:go-back="handleBack">
            <view slot="left" t-class-title="custom-navbar-title" title-max-length="{{5}}">{{navbarTitle}}</view>
        </t-navbar>

### 期望结果

 title-max-length="{{5}}" 能控制标题显示字数

### 实际结果

![image](https://user-images.githubusercontent.com/4917509/231416013-7606ca3d-adb8-4876-8767-e05c80e3bee3.png)

**Comment by LeeJim** [comment]
插槽是个独立的元素，完全由你控制的，你可以自行控制传入的🍠
