### ISSUE TITLE
[Popup] 初次加载后，点击框内任意位置或者控件，都会触发focus跳转事件

### ISSUE THREAD

**Issue by boerduosu** [Tencent/tdesign-miniprogram#1897]
### tdesign-miniprogram 版本

1.1.1

### 重现步骤

t-popup弹出框在初次加载后，点击框内任意位置或者控件，都会触发focus跳转事件。
我这边出现具体问题是，我在一个popup里面写在一个input和一个button，点击button能触发button事件，但会跳出键盘界面，
我本来还以为是手指比较大误点了，多次尝试后发现，点popup空白处，不触发button事件，也会跳出键盘，而且只有界面载入第一次的情况下会这样，把键盘界面取消掉，再次点击popup空白处，不会再次跳出键盘。
看了LOG后发现，的确是触发了onfocus。
代码如下:（亲测去除t-popup仅留view，是不会有这问题的）
<t-popup visible="{{visible}}" placement="bottom" prevent-scroll-through="{{false}}" show-overlay="{{false}}" close-on-overlay-click="{{false}}" bind:visible-change="close">
  <view class="content">
    <view class="filter-btns-wrap">
      <row class="one-line">
        <label>To:</label>
        <input style="width:100%" value="{{code}}" type="number" placeholder="指定手机号" />
      </row>
      <button class="filter-btn btn-confirm" bindtap="onWriteNFC">写入到标签</button>
    </view>
  </view>
</t-popup>

### 期望结果

界面加载完毕后，初次点击popup内的空白处，不会focus到input控件上，不会跳出键盘；
初次点击popup内的其他控件（比如按钮），也不会focus到input控件上，不会跳出键盘。
 

### 实际结果

用户没点击popup中的input控件，但是会focus到input控件上并跳出键盘

**Comment by LeeJim** [comment]
并不能复现

**Comment by boerduosu** [comment]
To:&nbsp;&nbsp;Tencent/tdesign-miniprogram


&nbsp; &nbsp; &nbsp; &nbsp;这个问题，我2个月前找了个workround绕过去了，（用了wx.showModal）
&nbsp; &nbsp; &nbsp; &nbsp;但是现在因为新的业务需求，不得不解决这个问题
&nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp;我们做了详细的测试，以便让您能复现该问题：
&nbsp; &nbsp; &nbsp; 1.&nbsp; iphone的确不能复现问题
&nbsp; &nbsp; &nbsp; 2. 安卓机均能复现该问题，测试过的机种：华为P40,vivo Y31S，红米Note 8 Pro
&nbsp; &nbsp; &nbsp; 3. 我们用了微信小程序开发工具自带的Tdesign例子，在点击购买按钮时，发现弹出的购买详细框，会自动弹出小键盘，这就是购买数量这个输入框导致的（参考本信件附带的视频附件）
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 而iphone在点击购买按钮时，只会弹出购买详细框，不会弹出小键盘
&nbsp; &nbsp; &nbsp;&nbsp;


&nbsp;&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/tdesign-miniprogram"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月27日(星期四) 下午4:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/tdesign-miniprogram] [Popup] 初次加载后，点击框内任意位置或者控件，都会触发focus跳转事件 (Issue #1897)





 
并不能复现

**Comment by boerduosu** [comment]
请查看一下，在微信公众平台的社区上有相同问题
https://developers.weixin.qq.com/community/develop/doc/0006ae98e68bd0aac0ff7c8305ec00?highLine=input%25E5%2588%259D%25E5%25A7%258B%25E8%2581%259A%25E7%2584%25A6%25E6%2597%25B6%25E4%25B8%258D%25E6%2598%25BE%25E7%25A4%25BA%25E8%25BE%2593%25E5%2585%25A5%25E6%25B3%2595

**Comment by LeeJim** [comment]
fixed by #2209 
升级至 1.1.14 以上版本即可
