### ISSUE TITLE
[ActionSheet] TS提示不存在description属性

### ISSUE THREAD

**Issue by See-Cat** [Tencent/tdesign-miniprogram#1898]
### tdesign-miniprogram 版本

1.1.1

### 重现步骤

ActionSheet.show({
      theme: ActionSheetTheme.List,
      selector: '#t-action-sheet',
      context: this,
      description: '变更性别',
      items: [{ label: '男' }, { label: '女' }],
  });Ï

### 期望结果

正确的ts类型提示

### 实际结果

ts类型报错

### 基础库版本

2.4.0

**Comment by See-Cat** [comment]
> 
基础库版本
2.12.3

**Comment by See-Cat** [comment]
企微基础库版本改成2.20.3就没有ts报错了。

**Comment by See-Cat** [comment]
问题还是存在的。 原先为了不报错，我直接修改了组件的类型。

**Comment by LeeJim** [comment]
我看看
