### ISSUE TITLE
[t-image] 希望增加多一个属性存储原图，区分缩略图和原图

### ISSUE THREAD

**Issue by xshans** [Tencent/tdesign-miniprogram#1901]
### 这个功能解决了什么问题

当我设置了这个属性为true时，show-menu-by-longpress
应该在t-image里面增加一个原图和缩略图的选项，这样我按住图片时，保存的应该是原图，而不是缩略图，目前只有一个src属性，不足以实现这个需求

### 你建议的方案是什么

期望能增加一个属性，可以区分原图和缩略图，能将原图url和缩略图url都能设置进去。

**Comment by LeeJim** [comment]
show-menu-by-longpress展示的菜单是小程序底层提供的，组件库并不能控制，所以这个需求没法实现哈。
