### ISSUE TITLE
[navbar&imageViewer] 在使用navbar组件时，imageViewer的操作区图标会被navbar 覆盖

### ISSUE THREAD

**Issue by KofiKuo** [Tencent/tdesign-miniprogram#1904]
### tdesign-miniprogram 版本

1.1.0

### 重现步骤

在使用navbar组件时，imageViewer的  deleteBtn ，closeBtn， showIndex都为true时，仍不显示，去掉navbar时才显示

**Comment by LeeJim** [comment]
我来定位下问题
