### ISSUE TITLE
[ActionSheet] 希望items配置增加value属性

### ISSUE THREAD

**Issue by See-Cat** [Tencent/tdesign-miniprogram#1905]
### 这个功能解决了什么问题

能更加方便的从事件参数中获取到当前选择的选项

### 你建议的方案是什么

export interface ActionSheetItem {
    value: string | number
    label: string;
    color?: string;
    disabled?: boolean;
}

**Comment by LeeJim** [comment]
感谢反馈，确实应该加一个

**Comment by LeeJim** [comment]
后面思考了一下，这个value没有多大意义，因为 items 是由你传进来的，点击的时候也返回了对应的 index，你完全可以自行获取对应的value

**Comment by See-Cat** [comment]
> 后面思考了一下，这个 value 没有多大意义，因为 items 是由你传进来的，点击的时候也返回了对应的 index，你完全可以自行获取对应的 value

现实场景是，得额外在维护一份value数组，去对应items，再通过index去获取对应的value。数据就有点分离了。items很可能是从后端数据过来，数据本身就是 label, value 的形式。这种情况下就得拆数据，一份是label的给actionSheet用，一份保存为value数组
