### ISSUE TITLE
[button] variant属性为outline时样式不正常。没有边框。

### ISSUE THREAD

**Issue by dyx359** [Tencent/tdesign-miniprogram#1908]
### tdesign-miniprogram 版本

1.0.4

### 重现链接

-

### 重现步骤

<t-button theme="primary" size="large" variant="outline">描边按钮</t-button>
更新到1.1.1也依然如此，不显示边框

### 基础库版本

2.30.4

**Comment by LeeJim** [comment]
麻烦提供下机型和系统版本信息

**Comment by dyx359** [comment]
目前暂未正式上线，真机【预览】；开发者工具模拟器中 皆是如此，其他几个属性都是正常的。iPhone14PM，iOS16.3.1

**Comment by anlyyao** [comment]
@dyx359 试试将 app.json 中的 "style": "v2" 去除，小程序的[新版基础组件](https://developers.weixin.qq.com/miniprogram/dev/reference/configuration/app.html#style)上加的样式，很难被覆盖，不关掉就会造成部分组件样式混乱
<img width="704" alt="截屏2023-04-19 10 57 14" src="https://user-images.githubusercontent.com/51158141/232955267-4b9d9c67-5b47-4430-bf9a-ce80973a82dd.png">

**Comment by dyx359** [comment]
这个是一开始就去掉了的

**Comment by anlyyao** [comment]
> 这个是一开始就去掉了的

我上传了一个片段：https://developers.weixin.qq.com/s/oFUVmBmg7SHs

下面是引入组件库之后，去除 app.json 中的 "style": "v2" 后的效果，
<img width="1322" alt="截屏2023-04-20 12 10 59" src="https://user-images.githubusercontent.com/51158141/233256265-61c4e6da-a33d-4fb7-8e58-c6d1f959552e.png">

**Comment by dyx359** [comment]
@anlyyao 谢谢，此段代码在我的运行环境中也的确是正常的，我再仔细核对查找一下原因

**Comment by anlyyao** [comment]
> @anlyyao 谢谢，此段代码在我的运行环境中也的确是正常的，我再仔细核对查找一下原因

好的。如果需要帮助，也可以上传一个可复现代码片段，可以一起看看问题原因～

**Comment by LeeJim** [comment]
暂时先关闭了，有问题再 reopen 吧

**Comment by akinocccc** [comment]
> @anlyyao 谢谢，此段代码在我的运行环境中也的确是正常的，我再仔细核对查找一下原因

兄弟，找到什么原因了吗？我也碰到这个问题

**Comment by vaint** [comment]
遇到了同样的问题，把"style": "v2" 去掉后可以了
