### ISSUE TITLE
[Radio] 使用自定义图标 disabled=true 不生效

### ISSUE THREAD

**Issue by See-Cat** [Tencent/tdesign-miniprogram#1913]
### tdesign-miniprogram 版本

1.1.1

### 重现步骤

<t-radio
    id="app-radio"
    label="{{label}}"
    checked="{{checked}}"
    value="{{value}}"
    disabled="{{true}}" 
    icon="{{['checked.png', 'unchecked.png'}}"
    bind:change="handleChange" 
 />

### 期望结果

disabled=true时，有禁用的样式，并且点击不可选中

### 实际结果

没有禁用样式，点击可选中

### 基础库版本

2.30.2

### 补充说明

微信小程序

**Comment by See-Cat** [comment]
> ### tdesign-miniprogram 版本
> 1.1.1
> 
> ### 重现链接
> _No response_
> 
> ### 重现步骤
> ### 期望结果
> disabled=true时，有禁用的样式，并且点击不可选中
> 
> ### 实际结果
> 没有禁用样式，点击可选中
> 
> ### 框架版本
> _No response_
> 
> ### 基础库版本
> 2.30.2
> 
> ### 补充说明
> 微信小程序

<t-radio id="app-radio" label="{{label}}" checked="{{checked}}" value="{{value}}" disabled="{{true}}" icon="{{['checked.png', 'unchecked.png']}}" block="{{block}}" bind:change="handleChange"  />

**Comment by LeeJim** [comment]
没法提供下代码，方便定位问题

**Comment by See-Cat** [comment]
不是bug。disabled=true还能点击是我的代码逻辑问题。而没有禁用的样式是因为 t-radio 会给默认图标添加disabled样式，而自定义图标就没有这么处理了。。顺便提个小需求呗，可以在 icon 配置多增加一个禁用样式的图标，或者给自定义图标也一起加个禁用样式。

**Comment by See-Cat** [comment]
不是bug。disabled=true还能点击应该是我的代码问题。而没有禁用的样式是因为 t-radio 会给默认图标添加disabled样式，而自定义图标就没有这么处理了。。顺便提个小需求呗，可以在 icon 配置多增加一个禁用样式的图标，或者给自定义图标也一起加个禁用样式。
