### ISSUE TITLE
[tabs] 选项卡切换问题，1.1.2 重现 issue id : 1862

### ISSUE THREAD

**Issue by c1ngular** [Tencent/tdesign-miniprogram#1915]
### tdesign-miniprogram 版本

1.1.2

### 重现步骤

#1862 复现

1.1.2 问题依旧存在，我这边可以确认

官网手册上的示例也一样，切换tab的时候没有切换tab panel .

**Comment by minr** [comment]
一样出现问题。

**Comment by LeeJim** [comment]
fixed by #1931
