### ISSUE TITLE
[Input 输入框] vertical布局方式显示错误

### ISSUE THREAD

**Issue by deajax** [Tencent/tdesign-miniprogram#1918]
### tdesign-miniprogram 版本

^1.1.2

### 重现链接

https://developers.weixin.qq.com/s/2ZAY4DmX7YHA

### 重现步骤

无需重现步骤

### 期望结果

vertical布局方式默认应为左对齐，或增加可配置左、居中、右的选项

### 实际结果

vertical布局方式现在为居中对齐

**Comment by anlyyao** [comment]
@deajax 收到反馈，现在处理
