### ISSUE TITLE
[Toast] 提供一个属性在 页面onHide时，自动关闭Toast未销毁的定时Toast

### ISSUE THREAD

**Issue by de1ck** [Tencent/tdesign-miniprogram#1921]
### 这个功能解决了什么问题

小程序在SwitchBar的时候，页面组件不会被销毁，这会导致页面切换Tab时，上一个页面的Toast提示在存在。

### 你建议的方案是什么

目前我的一种方案是重写 Page的onHide事件

```js
let onHide = context.onHide;
// eslint-disable-next-line no-unused-vars
context.onHide = function (...arg) {
  // console.log('onHide#######');
  onHide.apply(this, arg);
 // 手动关闭 Toast
  toast.clear();
  context.onHide = onHide;
};
```

**Comment by LeeJim** [comment]
这个 toast 是 wx.showToast 吧？应该不是 t-toast？

**Comment by de1ck** [comment]
> 这个 toast 是 wx.showToast 吧？应该不是 t-toast？

wx.showToast切换页面还会在，级别比较高，类似root节点下的t-toast ，t-toast在切换页面是不会显示的，但是切换回来可能还会存在。

**Comment by LeeJim** [comment]
这个就属于业务自己的逻辑了，组件库底层不适合做这样的处理。
