### ISSUE TITLE
[Upload] 多选上传组件ios点击失效，安卓选择图片失败

### ISSUE THREAD

**Issue by a1501255708** [Tencent/tdesign-miniprogram#1923]
### tdesign-miniprogram 版本

1.1.1

### 重现步骤

IOS多选upload组件官方示例点击失效
安卓官方示例多选提示"最多只能选择-1个图片或者视频"

**Comment by LeeJim** [comment]
fixed by #1914

**Comment by a1501255708** [comment]
@LeeJim 现在[https://tdesign.tencent.com/miniprogram/components/upload](url)官网文档中的upload多选图片功能扫码进小程序测试，ios就点不了上传图标，是因为官网示例没更新么？因为我本地项目在微信开发者工具里面能正常点击上传，iOS和安卓实机都有问题。也更新到最新的1.1.2了

**Comment by a1501255708** [comment]
ios系统是16.4.1，ios微信是最新版
