### ISSUE TITLE
修改当前选中的标签页结果不一致

### ISSUE THREAD

**Issue by YangRucheng** [Tencent/tdesign-miniprogram#1924]
### tdesign-miniprogram 版本

1.1.2

### 重现步骤

我修改`value`的值来实现类似切换标签页的效果, 但只在特定情况下生效.

示例一  ( 仅修改`value`的值 )
```js
Page({
    data: {
        nowTab: "签到",
        allTab: ['签到', '管理']
    },

    changeTab(e) {
        this.setData({
            'nowTab': e.detail.value,
            'allTab': ['签到', '✋🏼管理']
        })
    }
})
```
```wxml
<t-tab-bar value="{{value}}" bindchange="changeTab" theme="tag" value="{{nowTab}}">
    <t-tab-bar-item wx:for="{{allTab}}" wx:key="index" value="{{item}}">{{item}}</t-tab-bar-item>
</t-tab-bar>
```

示例二  ( 修改`value`的值和`allTab`列表 )
```js
Page({
    data: {
        nowTab: "签到",
        allTab: ['签到', '管理']
    },

    changeTab(e) {
        this.setData({
            'nowTab': e.detail.value,
            'allTab': ['签到', '管理', '测试']
        })
    }
})
```
```wxml
<t-tab-bar value="{{value}}" bindchange="changeTab" theme="tag" value="{{nowTab}}">
    <t-tab-bar-item wx:for="{{allTab}}" wx:key="index" value="{{item}}">{{item}}</t-tab-bar-item>
</t-tab-bar>
```

### 期望结果

点击其他标签时, **当前选中标签**都切换, 或者都不切换

### 实际结果

示例一的运行结果:
点击其他标签时, **当前选中标签**不改变

示例二的运行结果:
点击其他标签时, **当前选中标签**改变

### 基础库版本

2.4.0

### 补充说明

我发现如果标签页的数量改变, 当前选择的页面就会在视图层改变, 否则就不会改变.

因为功能需要, 需要实现类似标签页切换的效果.

**Comment by lolhezihehe** [comment]
这个是小程序的bug，多个tabbar切换会闪烁，应该是一个tab页面加载一个tabbar，可以attached打印一下
```js
attached() {
  console.log('tabbar attached',  this.data.nowTab) // 新进一个tab页会打印1次
}
```
可以在tab页使用 **getTabBar** **setData** 选中状态
[getTabBar 回调函数](https://developers.weixin.qq.com/miniprogram/dev/framework/ability/custom-tabbar.html#_2-getTabBar-%E5%9B%9E%E8%B0%83%E5%87%BD%E6%95%B0)

**Comment by LeeJim** [comment]
建议直接使用 custom-tabbar。参考这个模板：https://github.com/LeeJim/miniprogram-starter
