### ISSUE TITLE
[tabs] t-tabs是否支持超出屏幕部分，滑动显示，不会全部挤在一个屏幕空间。

### ISSUE THREAD

**Issue by KaleidosChen** [Tencent/tdesign-miniprogram#1929]
### 这个功能解决了什么问题

适用于tab栏中，tab个数多或者每个tab的字数过多。

### 你建议的方案是什么

超出的部分可以通过滑动查看tab，而不是全部固定在可视屏幕中。

**Comment by LeeJim** [comment]
不懂你的问题，现在的实现就是超出滚动的？
