### ISSUE TITLE
[t-tab-bar] 无法自定义选中颜色，icon无法正常显示

### ISSUE THREAD

**Issue by wuguang1** [Tencent/tdesign-miniprogram#1941]
### tdesign-miniprogram 版本

"tdesign-miniprogram": "^1.1.3"

### 重现步骤

 <view class="custom-wrapper">
  <t-tab-bar value="{{active}}" bindchange="onChange" shape="round" theme="tag" split="{{false}}">
    <t-tab-bar-item wx:for="{{list}}" wx:key="index" value="{{item.value}}" icon="{{item.icon}}">
      <view class="custom-tab-bar-wrapper">
        <t-icon prefix="wr" name="{{item.icon}}" size="48rpx" />
        <view class="text">{{ item.text }}</view>
      </view>
    </t-tab-bar-item>
  </t-tab-bar>
</view>

.custom-wrapper {
  --td-tab-bar-border-color: #e7e7e7;
  --td-tab-bar-bg-color: #ffffff;
  --td-tab-bar-hover-color: #ff0a0a;
  --td-tab-bar-item-color: #28da10;
  --td-tab-bar-item-active-color: #333;
}

**Comment by wuguang1** [comment]
<view class="custom-wrapper">
  <t-tab-bar value="{{active}}" bindchange="onChange" shape="round" theme="tag" split="{{false}}">
    <t-tab-bar-item wx:for="{{list}}" wx:key="index" value="{{item.value}}" icon="{{item.icon}}">
      <view class="custom-tab-bar-wrapper">
        <t-icon prefix="wr" name="{{item.icon}}" size="48rpx" />
        <view class="text">{{ item.text }}</view>
      </view>
    </t-tab-bar-item>
  </t-tab-bar>
</view>

**Comment by wuguang1** [comment]
<view class="custom-wrapper">
  <t-tab-bar value="{{active}}" bindchange="onChange" shape="round" theme="tag" split="{{false}}">
    <t-tab-bar-item wx:for="{{list}}" wx:key="index" value="{{item.value}}" icon="{{item.icon}}">
      <view class="custom-tab-bar-wrapper">
        <t-icon prefix="wr" name="{{item.icon}}" size="48rpx" />
        <view class="text">{{ item.text }}</view>
      </view>
    </t-tab-bar-item>
  </t-tab-bar>
</view>

**Comment by wuguang1** [comment]
。<view class="custom-wrapper">
  <t-tab-bar value="{{active}}" bindchange="onChange" shape="round" theme="tag" split="{{false}}">
    <t-tab-bar-item wx:for="{{list}}" wx:key="index" value="{{item.value}}" icon="{{item.icon}}">
      <view class="custom-tab-bar-wrapper">
        <t-icon prefix="wr" name="{{item.icon}}" size="48rpx" />
        <view class="text">{{ item.text }}</view>
      </view>
    </t-tab-bar-item>
  </t-tab-bar>
</view> 。

**Comment by wuguang1** [comment]
![image](https://user-images.githubusercontent.com/51358709/234752130-6c49a48c-d27d-427b-a24b-77d323b9c6e4.png)

**Comment by LeeJim** [comment]
正确的变量：
```css
.custom-wrapper {
  --td-tab-bar-color: #28da10;
  --td-tab-bar-active-color: #333;
}
```
