### ISSUE TITLE
希望可以增加样式参数，可以灵活调整修改组件样式以满足需求

### ISSUE THREAD

**Issue by DisciplineAndCalm-yy** [Tencent/tdesign-miniprogram#1942]
### 这个功能解决了什么问题

满足定制化样式需求

### 你建议的方案是什么

加样式参数

**Comment by LeeJim** [comment]
什么是样式参数？

**Comment by DisciplineAndCalm-yy** [comment]
抱歉，是我描述出问题了。是希望您能让每个组件都支持传入类名，然后通过类目可以调整一些样式。比如我遇到一个需求就是，小程序内drop-down-menu下多个item，要做不同颜色区分。尝试给组件直接上class，传入class，t-class-content都不行。想去改下源码，奈何本人才疏学浅，没改成功。希望不只是这一个组件支持传入类目，其他也可以。

**Comment by LeeJim** [comment]
大概理解你的意思，提 issue 的话还是建议具体问题具体分析，像这样大而笼统的问题，我们没有办法解决。
如果是非常定制化的样式，也很难满足，通用组件很难做到这么灵活的。

这个 issue 我就先关闭了，你可以将 dropdownmenu 下多个 item 需要不同颜色区分这的需求，通过具体的代码和期望的效果展示描述一下
