### ISSUE TITLE
[自定义主题] 自定义主题色 修改 -td-brand-color ， 各透明度无法同时变化

### ISSUE THREAD

**Issue by hihuangwei** [Tencent/tdesign-miniprogram#1952]
### tdesign-miniprogram 版本

1.1.4

### 基础库版本

2.31.0

**Comment by LeeJim** [comment]
什么各透明度？--td-primray-color-1（、2、3、4）?

**Comment by hihuangwei** [comment]
> 
![image](https://user-images.githubusercontent.com/3166799/236176511-edd0ebd4-03e0-4421-8b8a-88cbf46a0a24.png)

全局自定义主题色
--td-brand-color: #00a1e9;
禁用状态的按钮 未能同步变化

**Comment by LeeJim** [comment]
色彩的颜色都是通过复杂的算法得出的，不是通过一个主题色来简单计算的。
如果需要调整禁用态的颜色，需要更改：`--td-brand-color-disabled`
