### ISSUE TITLE
[Loading 加载] 希望增加通过图片形式自定义加载图标

### ISSUE THREAD

**Issue by highmind** [Tencent/tdesign-miniprogram#1955]
### 这个功能解决了什么问题

一般项目中会有项目logo等做为loading的情况，希望可以通过图片形式自定义加载图标

### 你建议的方案是什么

希望可以通过图片形式自定义加载图标

**Comment by LeeJim** [comment]
```html
<t-loading indicator="{{false}}">
  <t-image src="logo" />
</t-loading>
```

这样是不是就可以满足你的需求了

**Comment by highmind** [comment]
> ```
> <t-loading indicator="{{false}}">
>   <t-image src="logo" />
> </t-loading>
> ```
> 
> 这样是不是就可以满足你的需求了

感谢您，这样应该可以实现

**Comment by LeeJim** [comment]
> > ```
> > <t-loading indicator="{{false}}">
> >   <t-image src="logo" />
> > </t-loading>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这样是不是就可以满足你的需求了
> 
> 感谢您，这样应该可以实现

试了下这样没有自转的效果，我这边支持一下。

**Comment by highmind** [comment]
> > > ```
> > > <t-loading indicator="{{false}}">
> > >   <t-image src="logo" />
> > > </t-loading>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 这样是不是就可以满足你的需求了
> > 
> > 
> > 感谢您，这样应该可以实现
> 
> 试了下这样没有自转的效果，我这边支持一下。

不支持动画也可以，目前如果使用图片作为icon的情况，一般图片不需要动画，或者图片使用了项目logo并且是gif，此时不需要动画

**Comment by LeeJim** [comment]
那你为啥要用 loading 组件，直接 image 不行吗？

**Comment by LeeJim** [comment]
fixed by 3577c0a67bb039e31f094953a0cc21608d2f6ad1
