### ISSUE TITLE
[cell] 使用wx:for生成的cell样式有问题

### ISSUE THREAD

**Issue by moreluck1** [Tencent/tdesign-miniprogram#1957]
### tdesign-miniprogram 版本

1.1.4

### 重现步骤

这两种写法产生的样式不一样
`<t-cell-group  theme="card">`
`  <t-cell   title="0" hover arrow  />`
`  <t-cell   title="1" hover arrow  />`
`</t-cell-group>`

下面这种写法border没了，相邻的cell出现圆角。
` <t-cell-group wx:for="{{ 2}}" theme="card">`
`    <t-cell title="{{item}}" hover arrow />`
`  </t-cell-group> `

这是为什么呢？
或许不是bug，我刚学小程序，对这个很困惑。
是我哪里错了吗？

自己测试
t-cell-group换成view就border就出现了
或者json文件里的 usingComponents 去掉 "t-cell-group": "tdesign-miniprogram/cell-group/cell-group"
但是theme="card"的样式没了

**Comment by moreluck1** [comment]
t-cell-group换成view就border就出现了

**Comment by LeeJim** [comment]
`wx:for` 应该放在 cell 上而不是 cell-group
