### ISSUE TITLE
[backTop] ios平台，正在滚动中（滚动没有结束）点击backTop，会发生白屏现象，无法显示scroll-list的内容

### ISSUE THREAD

**Issue by ksy2019** [Tencent/tdesign-miniprogram#1963]
### tdesign-miniprogram 版本

1.1.4

### 重现步骤

在滚动没有结束的时候点击backTop,会发生白屏现象；

### 期望结果

在滚动没有结束的时候点击backTop,不会发生白屏现象；

### 补充说明

拼夕夕小程序的实现是滚动中点击backTop，先将滚动停止，再次点击backTap才返回顶部

**Comment by anlyyao** [comment]
@anlyyao 感谢反馈 我这边跟进处理一下～

**Comment by ksy2019** [comment]
谢谢；解决问题了。仔细研究了我们的代码和实例，back-top插件是针对整个界面的；在我们的组件中使用了scroll-view;通过back-top的事件控制来控制scroll-top的值，在android中是正常的，在ios中滚动中设置scroll-top就会白屏；但是如果不使用scroll-view； 滚动条的位置比较奇怪且数据过滤栏需要使用绝对定位固定；鱼和熊掌不可兼得🤦‍♂️
