### ISSUE TITLE
loading能提供自定义提示词颜色及图标的功能吗

### ISSUE THREAD

**Issue by wanhencheng** [Tencent/tdesign-miniprogram#197]
### 这个功能解决了什么问题
方便自定义loading组件的提示颜色及图标，在pullDownRefresh组件中也应该可以使用loading中的建议的新特性。

### 你建议的方案是什么？
给loading组件给一个color属性来控制提示文本的颜色状态，并提供一个iconSrc属性以方便填写自定义加载图标

**Comment by JJunYang** [comment]
<img width="903" alt="image" src="https://user-images.githubusercontent.com/50793382/155516006-9f751249-2d0c-4383-a935-7b4c62ed5b25.png">
展示文本的颜色状态可以用外部样式类设置哈，具体字段是t-class-text

关于自定义加载图标的需求，我们会纳入后期规划。

谢谢您的意见，当然也欢迎向我们贡献代码。

**Comment by wanhencheng** [comment]
在这之前已经在开发中使用t-class-text类名完成设置文本属性，有可能的话还是希望提供直接在组件标签属性设置颜色及常用属性的便捷方法。
