### ISSUE TITLE
[stepper] 输入框无法清空

### ISSUE THREAD

**Issue by feng520ckx** [Tencent/tdesign-miniprogram#1970]
### tdesign-miniprogram 版本

1.0.2

### 期望结果

设置最小值为1，希望可以删掉输入框的数据，可以直接输入8或者9，类似于这种，但是实际是删掉1后，又回调了change事件，携带过来的value还是1

**Comment by anlyyao** [comment]
@feng520ckx  收到反馈 我处理一下～
