### ISSUE TITLE
[action-sheet] 设置全局配置"lazyCodeLoading": "requiredComponents"后报错

### ISSUE THREAD

**Issue by moreluck1** [Tencent/tdesign-miniprogram#1972]
### tdesign-miniprogram 版本

1.1.4

### 重现步骤

app.json配置"lazyCodeLoading": "requiredComponents"
在页面js文件使用官方示例代码。
import ActionSheet, { ActionSheetTheme } from 'tdesign-miniprogram/action-sheet/index';
会报好多错，需要去掉lazyCodeLoading才不会报错，能想办法兼容这个配置吗？

报错的代码：
Please do not register multiple Pages in pages/index/index.js
Component is not found in path "miniprogram_npm/tdesign-miniprogram/action-sheet/action-sheet
Failed to set the 'body' property on 'Document':

**Comment by xionHung** [comment]
我遇到的是引用这个组件报同样的错误，懵逼半天，试下去掉lazyCodeLoading，确实好使，但是这个就不生效了，等待官方回复。。。
