### ISSUE TITLE
[t-button] 不支持自定义颜色，如何传入自定义颜色color

### ISSUE THREAD

**Issue by nanhupatar** [Tencent/tdesign-miniprogram#1973]
### tdesign-miniprogram 版本

1.1.1

**Comment by anlyyao** [comment]
@nanhupatar [微信小程序提供了多种方式可以实现样式覆盖](https://tdesign.tencent.com/miniprogram/custom-style)，先看下文档哈～

**Comment by Swarz** [comment]
是不是只能自定义style，不能添加自定义class？？
加个颜色 要写背景加边框色~
