### ISSUE TITLE
后续是否考虑支持百度小程序和抖音小程序

### ISSUE THREAD

**Issue by highmind** [Tencent/tdesign-miniprogram#1977]
### 这个功能解决了什么问题

有一些项目只有百度小程序或者抖音小程序，在通过转换工具转换以后，一些组件无法使用，通过修改可以兼容，但是有一些组件，在百度小程序中仍然无法使用，发现是使用了 relation，组件关系，而百度小程序的自定义组件，不支持组件关系，导致转换以后，也无法实现

### 你建议的方案是什么

是否考虑支持百度小程序和抖音小程序

**Comment by LeeJim** [comment]
暂不考虑直接支持，可以期待一下后续社区版本的 taro
