### ISSUE TITLE
[下拉菜单] 单选选项行高不一致

### ISSUE THREAD

**Issue by hihuangwei** [Tencent/tdesign-miniprogram#1980]
### tdesign-miniprogram 版本

1.1.5

### 重现步骤

![image](https://user-images.githubusercontent.com/3166799/236843843-a497a8bd-324b-42dd-a7f2-5399b25dea4c.png)

![image](https://user-images.githubusercontent.com/3166799/236844014-417eb417-7329-4065-afa7-efeccffda9b8.png)

## IssueShoot
- 预估时长: 1
- 期望完成时间: 2023-05-14 00:00:00 +0000 UTC
- 开发难度: 低
- 参与人数: 1
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by LeeJim** [comment]
我来看下
