### ISSUE TITLE
[pull-down-refresh] 升级到1.1.4版本后，属性value值的赋值时机不能放到 refresh或者change事件了，不做判断很容易会导致死循环， 请大佬确认一下这个问题是不是设计缺陷

### ISSUE THREAD

**Issue by luojh** [Tencent/tdesign-miniprogram#1987]
### tdesign-miniprogram 版本

1.1.4

### 重现步骤

我的使用场景是在下拉时，也就是refresh事件触发时，会给 value属性手动setData为true， 升级了1.1.4之后，发现会出现死循环，看了下代码变更，发现是加了doRefresh的调用，而doRefresh里面又触发了 change和refresh事件。
![image](https://github.com/Tencent/tdesign-miniprogram/assets/819119/caf09d00-089e-4316-88b3-8a06d0f1dcd0)

我就疑惑了，pull-down-refresh 的value赋值时机应该在什么时候？不可能是在ready或者onLoad，onShow吧？

为了临时解决这问题，我在refresh事件里面加了 pullDownValue==false 的判断，但是这个事件会触发两次，第二次触发是我setData pullDownValue: true触发的
![image](https://github.com/Tencent/tdesign-miniprogram/assets/819119/2117c539-293b-463a-bb2f-44635e410863)

请大佬确认一下这个问题是不是设计缺陷？ 谢谢

### 基础库版本

2.31.1

**Comment by LeeJim** [comment]
我等会看看
