### ISSUE TITLE
[Upload 上传 组件] 多图上传无法选择本地图片，安卓只能弹起拍摄和相册选择，但是点进去没法选择图片，提示是只能选择-1张照片或视频，iPhone x没法弹出拍摄和相册选择

### ISSUE THREAD

**Issue by libai-lab** [Tencent/tdesign-miniprogram#1989]
### tdesign-miniprogram 版本

1.1.2

### 重现步骤

点击官方关于upload组件进行多图上传

### 期望结果

可以选择本地图片和拍摄

### 实际结果

iPhonex无法弹起拍摄和选择本地相册的弹窗，安卓弹起，进入相册显示数量为-1无法选择相册

**Comment by LeeJim** [comment]
我来看下

**Comment by LeeJim** [comment]
1.1.3 修复了 max 的bug，升级看看？

**Comment by LeeJim** [comment]
duplicated with #1923
