### ISSUE TITLE
[tab-bar-item] 显示异常

### ISSUE THREAD

**Issue by ljquan** [Tencent/tdesign-miniprogram#2009]
### tdesign-miniprogram 版本

1.1.6

### 重现步骤

  <t-tab-bar defaultValue="label1" split="{{false}}">
  <t-tab-bar-item badge-props="{{ {count: 16} }}" ariaLabel="首页，有16条消息" value="label1" icon="home"
    >首页</t-tab-bar-item
  >
  <t-tab-bar-item badge-props="{{ { dot: true } }}" ariaLabel="软件，有新的消息" value="label2" icon="app"
    >软件</t-tab-bar-item
  >
  <t-tab-bar-item badge-props="{{ {count: 'New'} }}" ariaLabel="聊天，New" value="label3" icon="chat"
    >聊天</t-tab-bar-item
  >
  <t-tab-bar-item badge-props="{{ {count: '···'} }}" ariaLabel="我的，有很多消息" value="label4" icon="user"
    >我的</t-tab-bar-item
  >
</t-tab-bar>

### 期望结果

<img width="379" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/3754268/8d2c7376-6f66-4112-adc7-6c37767e31af">

### 实际结果

<img width="321" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/3754268/696ddb6c-37ec-4552-804f-87d66dc777a4">

**Comment by ljquan** [comment]
在微信开发者工具中

**Comment by LeeJim** [comment]
感谢反馈，是不是基础哭版本低于 2.19.2

**Comment by ljquan** [comment]
> 感谢反馈，是不是基础库版本低于 2.19.2

对的。低于 2.19.2，下拉菜单也有问题，出不来。
