### ISSUE TITLE
[t-dropdown-menu] 下拉菜单插槽自定义内容无法控制下拉菜单显隐

### ISSUE THREAD

**Issue by QHSsss** [Tencent/tdesign-miniprogram#2015]
### 这个功能解决了什么问题

t-dropdown-menu下拉菜单自定义的时候没法主动关闭下拉菜单。。。
比如我在下拉菜单中首先是单选，然后我通过插槽直接塞东西进去，再加两个按钮用来重置数据以及确认数据，确认数据时没有方法可以让我关闭下拉菜单，我只能点击遮罩层将他关闭，多选属性开启后，虽然组件有重置以及确认按钮，但是暴露出来的事件confirm以及reset都是不生效的

### 你建议的方案是什么

下拉菜单的显隐通过props中的一个值来控制

**Comment by trojanyao** [comment]
@QHSsss 根据 @Xrd888 提供的方法，看了下源码，官方虽然没有暴露相关的 props 或 methods，但其实有方法实现。也供后来的有类似问题的朋友参考。

### 调用 `<t-dropdown-menu>` 的 [`toggle()`](https://github.com/Tencent/tdesign-miniprogram/blob/abca5d323030d99a030fa18060655ab53ff84a8f/src/dropdown-menu/dropdown-menu.ts#L75) 方法

t-dropdown-menu 组件中有个 `toggle()` 方法，具体没看明白；但是当传入值为 null 的时候，会将所有已打开的下拉菜单关闭。

使用 `this.selectComponent('#<t-dropdown-menu的id>').toggle(null)` 即可全部关闭。

<img width="590" alt="Xnip2023-10-17_20-56-13" src="https://github.com/Tencent/tdesign-miniprogram/assets/22811809/f2f9eda7-e933-4e56-89fc-f5101f10a311">

### 调用 `<t-dropdown-item>` 的 [`closeDropdown()`](https://github.com/Tencent/tdesign-miniprogram/blob/abca5d323030d99a030fa18060655ab53ff84a8f/src/dropdown-item/dropdown-item.ts#L101) 方法

同上，使用 `this.selectComponent('#<t-dropdowm-item的id>')` 即可单独关闭具体的菜单项。

<img width="592" alt="Xnip2023-10-17_21-01-17" src="https://github.com/Tencent/tdesign-miniprogram/assets/22811809/0083114d-e914-4760-9cd7-6011c28f8e6a">
