### ISSUE TITLE
[t-icon] 1.1.6图标与旧版本图标对不上

### ISSUE THREAD

**Issue by lolhezihehe** [Tencent/tdesign-miniprogram#2019]
### tdesign-miniprogram 版本

1.1.6

### 重现步骤

升级1.1.6图标错乱，官网文档和右侧效果对应不上
![image](https://github.com/Tencent/tdesign-miniprogram/assets/18699939/2b8a79d9-9c09-46c7-a64d-f06a4291add8)

**Comment by anlyyao** [comment]
@lolhezihehe 收到反馈，我这边确认一下问题～

**Comment by anlyyao** [comment]
> @lolhezihehe 收到反馈，官网的是正确的。我这边确认一下问题～

已处理在 #2020

**Comment by acpplife** [comment]
1.1.8图标也都错乱了
<img width="285" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/13010800/57b28db7-6efb-4ae1-aacf-b1b7da3e6730">
@nanhupatar

**Comment by kocokolo** [comment]
远离tdesign，回归vant是正道
