### ISSUE TITLE
[dialog] 防止滚动穿透，在遮罩层滚动时可防止，在dialog内容区滚动时依然穿透

### ISSUE THREAD

**Issue by v10258** [Tencent/tdesign-miniprogram#2024]
### tdesign-miniprogram 版本

是

### 重现步骤

  <t-dialog
    visible="true"
    data-key="showCloseBtn"
    title="资料未完善"
    close-btn
    content="完善个人信息，以确保为您提供完整服务"
    confirm-btn="{{ confirmBtn }}"
    bind:confirm="handleAuth"
    bind:cancel="handleClose"
  />

**Comment by v10258** [comment]
<t-dialog
    visible="{{visible}}"
    data-key="showCloseBtn"
    title="资料未完善"
    close-btn
    content="完善个人信息，以确保为您提供完整服务"
    confirm-btn="{{ confirmBtn }}"
    bind:confirm="handleAuth"
    bind:cancel="handleClose"
  />

**Comment by v10258** [comment]
`  <t-dialog
    visible="{{visible}}"
    data-key="showCloseBtn"
    title="资料未完善"
    close-btn
    content="完善个人信息，以确保为您提供完整服务"
    confirm-btn="{{ confirmBtn }}"
    bind:confirm="handleAuth"
    bind:cancel="handleClose"
  />`

**Comment by nightmaring** [comment]
> ` <t-dialog visible="{{visible}}" data-key="showCloseBtn" title="资料未完善" close-btn content="完善个人信息，以确保为您提供完整服务" confirm-btn="{{ confirmBtn }}" bind:confirm="handleAuth" bind:cancel="handleClose" />`

参考https://github.com/Tencent/tdesign-miniprogram/issues/1743#issuecomment-1552954669
