### ISSUE TITLE
[t-stepper] 配合t-popup弹出层真机上会自动弹起键盘

### ISSUE THREAD

**Issue by Markniconico** [Tencent/tdesign-miniprogram#2026]
### tdesign-miniprogram 版本

1.1.6

### 重现步骤

点击加入购物车显示t-popup弹出层，弹出层内嵌套t-tepper，自动弹起了键盘遮挡了显示区域

### 基础库版本

2.32.0

### 补充说明

真机是小米13

**Comment by Markniconico** [comment]
看了下其他issues，#1897好像也是这个问题

**Comment by feng520ckx** [comment]
好像会在部分安卓机上会出现这个问题

**Comment by Markniconico** [comment]
我也遇到这个问题，小米13，t-popup组件内部只要包含input（包括原生组件），就会自动聚焦。不知道是t-popup的问题还是input组件在小米手机上的Bug.
