### ISSUE TITLE
[badge] 徽标右上角内容不能展示小数

### ISSUE THREAD

**Issue by csshjh** [Tencent/tdesign-miniprogram#2027]
### tdesign-miniprogram 版本

新版本同样会出现此问题

### 基础库版本

2.27.0

**Comment by LeeJim** [comment]
<img width="70" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/7017290/c6fc0c1b-649f-45d5-9bfe-dd0910b9bc8b">

```html
<t-badge count="8.1" content="消息" offset="{{ [-8] }}" class="wrapper" />
```
