### ISSUE TITLE
[t-uploud] 能不能支持 media/messageFile 合并，以实现多种从客户端上传方式

### ISSUE THREAD

**Issue by nanhupatar** [Tencent/tdesign-miniprogram#2028]
### 这个功能解决了什么问题

目前仅支持 media/messageFile 二选一

### 你建议的方案是什么

建议合并方法按数组传入，如['album','camera','messageFile']支持三种方式上传，或者提供自定义方式上传

**Comment by LeeJim** [comment]
这个是微信底层API的限制，没办法这样实现
