### ISSUE TITLE
tabs组件取消space-evenly后标签栏无法滚动

### ISSUE THREAD

**Issue by silence1996** [Tencent/tdesign-miniprogram#2030]
### tdesign-miniprogram 版本

1.1.6

### 重现步骤

`<t-tabs defaultValue="{{0}}" space-evenly="{{false}}">
    <t-tab-panel wx:for="{{8}}" wx:key="index" label="选项" value="{{index}}" />
  </t-tabs>`

### 期望结果

取消space-evenly后，<t-tab-panel>组件超过一定数量后标签栏可以滚动

### 实际结果

无法滚动

### 基础库版本

2.19.4

### 补充说明

应该是tabs组件的标签栏的sticky组件没有设定铺满，直接修改样式width: 100%为后发现，点击标签能对应滚动居中，但是滑动的时候整个标签栏会出现莫名奇妙的跳动

**Comment by LeeJim** [comment]
应该是 sticky 的问题，已经修复了。参见 #2047
