### ISSUE TITLE
[Rate评分] 希望扩展一个触发方式

### ISSUE THREAD

**Issue by SuniceTop** [Tencent/tdesign-miniprogram#2040]
### 这个功能解决了什么问题

目前评分触发，是通过长按然后滑动触发。目前我这了很多用户都会先问怎么触发，操作都是点击。。

### 你建议的方案是什么

希望添加一个触发方式，如 默认是 当前的 滑动 slide，也可以设置为 click 点击；

**Comment by LeeJim** [comment]
默认滑动和点击都是支持的

**Comment by SuniceTop** [comment]
额，点击触发不是很灵敏，点好几次才能成功一次。。。

**Comment by LeeJim** [comment]
我跟进处理下

**Comment by zephyr404** [comment]
现在还没有解决吗？

**Comment by LiaoLiaoCiShengXuDu** [comment]
请问这个点击的问题 发版了吗, 我发现 我集成的代码 还是只能滑动选值。并不能点击选择呢

**Comment by LiaoLiaoCiShengXuDu** [comment]
> 

点击真的可以吗? 在你们 https://tdesign.tencent.com/miniprogram/components/rate 网页的示例中确实能点击
但是小程序中 无法点击,只能滑动选值
