### ISSUE TITLE
[tabs] 过多tabs-item 页面宽度不正确，而且无法自动滚动

### ISSUE THREAD

**Issue by cxjhk** [Tencent/tdesign-miniprogram#2053]
### tdesign-miniprogram 版本

^1.1.7

### 实际结果

![image](https://github.com/Tencent/tdesign-miniprogram/assets/23472375/b8af7340-31b3-4369-8ebe-f0ab589fdde8)

**Comment by anlyyao** [comment]
@cxjhk 升级到 1.1.8 试试

**Comment by hongkb24** [comment]
1.1.8似乎并没有解决该问题,tabs-item过多依然无法滚动
