### ISSUE TITLE
[slider] 样式兼容性

### ISSUE THREAD

**Issue by dnjat** [Tencent/tdesign-miniprogram#2054]
### tdesign-miniprogram 版本

1.1.8

### 重现步骤

初始化状态是隐藏时,带刻度滑动选择器,所有刻度重叠在一起,需要点击选择一次才会重新正常排列.
刻度描述是数字与英文时,可以一行显示. 如果是中文将会挤在一起成垂直显示.
官方demo中,https://tdesign.tencent.com/miniprogram/components/slider?tab=demo 带刻度滑动选择器例子预览中也是第一次刻度重叠在一起. chrom浏览器会有这问题,在frifox下又不会

# 找到原因,简单复现:
data{
  marks: {
        0: '无',
        20: '小',
        40: '中',
        60: '大',
        80: '圆角',
      }
}

`<view hidden="{{!isEnable}}">
  <t-slider defaultValue="{{60}}" marks="{{marks}}" step="{{20}}"/>
</view>`

业面初始值isEnable=false,控件在计算maxRange时为0, 导至初始化并没有成功.
而第一次是显示时,maxRange计算是正常的第一次是显示时,maxRange计算是正常的

**Comment by dnjat** [comment]
怎么感觉没一点人气

**Comment by LeeJim** [comment]
我看看

**Comment by LeeJim** [comment]
这个问题是用法的问题，hidden 的时候还是会执行组件的生命周期，所以需要在 hidden =false的时候手动调用下组件内部的方法`getInitialStyle`

**Comment by LeeJim** [comment]
added by 162b1c964c579bf06efa820917a99d427b00e882

**Comment by dnjat** [comment]
谢谢,明白了
