### ISSUE TITLE
[Tabs] 宽度错误

### ISSUE THREAD

**Issue by dramxia** [Tencent/tdesign-miniprogram#2055]
### tdesign-miniprogram 版本

1.1.7

### 期望结果

![image](https://github.com/Tencent/tdesign-miniprogram/assets/102667353/716296b4-ae6c-4902-96e5-3061061855d3)

### 实际结果

![image](https://github.com/Tencent/tdesign-miniprogram/assets/102667353/03905cff-456b-48cd-bdf0-f0299f776e63)

### 基础库版本

2.30.2

**Comment by anlyyao** [comment]
@dramxia 在1.1.8版本已处理，升级版本即可
