### ISSUE TITLE
[action-sheet] 当使用自定义tabbar时，组件内的action-sheet会被遮挡导致看不到最下面一行（取消）

### ISSUE THREAD

**Issue by blackhu** [Tencent/tdesign-miniprogram#2058]
### tdesign-miniprogram 版本

1.1.8

### 重现链接

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

_No response_

### 基础库版本

2.19.4
### 补充说明

mac端模拟 好像就正常，iphone13 pro就有遮挡

_No response_

**Comment by LeeJim** [comment]
我用了下 iPhone 13 并不能复现。看下你的微信版本和和基础库版本

**Comment by akinocccc** [comment]
> 我用了下 iPhone 13 并不能复现。看下你的微信版本和和基础库版本

@LeeJim 我也碰到了，自定义tabbar会遮挡“取消”，基础库是最新的，iphone14和模拟器俊复现

![image](https://github.com/Tencent/tdesign-miniprogram/assets/64176534/f6bfc573-9335-4806-9e52-9e9c2b0d588f)

**Comment by akinocccc** [comment]
我测了一下，用了自定义tabbar后，定位的bottom: 0从最底部开始算了，而用原生的 tabbar bottom:0 从tabbar的顶部开始算
