### ISSUE TITLE
[tab-bar组件] 按照官方文档写的tab-bar 增加icon，不生效，提示依赖的icon组件找不到

### ISSUE THREAD

**Issue by anming-john** [Tencent/tdesign-miniprogram#2064]
### tdesign-miniprogram 版本

1.1.8

### 重现步骤

![image](https://github.com/Tencent/tdesign-miniprogram/assets/15686326/5b86488b-98b8-464a-ae5c-e65ebd55413d)

### 期望结果

按照官方的文档写
![image](https://github.com/Tencent/tdesign-miniprogram/assets/15686326/472fee2a-e22c-4bb6-ad73-28fbe6879561)

应该会显示icon和名称

### 实际结果

实际结果，开发者工具提示没有找到icon
![image](https://github.com/Tencent/tdesign-miniprogram/assets/15686326/71e847e8-ccee-47f4-a3af-6a3782e4edef)

看了下 小程序 打包npm 后才发现并没有正确引入icon组件
![image](https://github.com/Tencent/tdesign-miniprogram/assets/15686326/39d48b44-0385-4092-b5a6-b789e2b59dd8)

原始的npm包确实有template文件夹， 但是通过小程序打包后， 并不会把template拷贝过去， 导致功能失效

### 基础库版本

2.16.0

### 补充说明

我们项目是通过 gulp-mp-npm 方式打包进去的。

**Comment by anlyyao** [comment]
@anming-john 
这个插件其实并不会对依赖进行编译与打包，所以还是需要通过微信开发工具的“构建 npm”进行编译，但从你的截图来看确实缺少了很多common下的公共template、样式等等，辛苦在确定一下你的构建过程。

下面是通过工具的“构建 npm”的产物：
![image](https://github.com/Tencent/tdesign-miniprogram/assets/51158141/f1ea4430-290a-47f4-bd70-eb4327e6bba5)
