### ISSUE TITLE
[Tab] label 动态响应问题

### ISSUE THREAD

**Issue by wiidz** [Tencent/tdesign-miniprogram#2066]
### tdesign-miniprogram 版本

"tdesign-miniprogram": "^0.30.0"

### 重现链接

  <t-tab-panel label="待出餐" value="0" badge-props="{{ {count: preparingAmount,offset: ['-14rpx', '4rpx']} }}">

### 重现步骤

this.setData() 修改preparingAmount的数值，wxml不会发生变化，是不是没有进行绑定

### 期望结果

页面中的徽标数量跟随数据变化

### 实际结果

未跟随数据变动

**Comment by wiidz** [comment]
```wxml
  <t-tab-panel label="待出餐" value="0" badge-props="{{ {count: preparingAmount,offset: ['-14rpx', '4rpx']} }}">
```

**Comment by wiidz** [comment]
目前有一个很傻逼的解决办法是，把prepareingAmount写到label中，会触发更新
```wxml
<t-tab-panel label="待出餐{{preparingAmount}}" value="0" badge-props="{{ {count: preparingAmount,offset: ['-14rpx', '4rpx']} }}">
```

**Comment by LeeJim** [comment]
这个问题已经修复过了的，建议升级至最新版本哈
