### ISSUE TITLE
[t-calendar] 日历无法选择区间, type=range无效

### ISSUE THREAD

**Issue by Sonweir** [Tencent/tdesign-miniprogram#2067]
### tdesign-miniprogram 版本

1.1.5

### 重现步骤

日历无法选择区间, type=range无效
但是修改源码t-calendar组件文件夹下的props.js中的type默认值改为range就能选中区间，props.js中的type原默认值为single

### 期望结果

期望日历type=range能正常

### 实际结果

无法选择区间
![image](https://github.com/Tencent/tdesign-miniprogram/assets/93140868/bdde6efb-7bac-4580-9405-50ff8c15f778)
但是修改源码t-calendar组件文件夹下的props.js中的type默认值改为range就能选中区间，就很离谱
![image](https://github.com/Tencent/tdesign-miniprogram/assets/93140868/92c4f6f1-7fd1-4cf5-a39a-0bda3768477f)

**Comment by LeeJim** [comment]
1.1.6 已经修复

**Comment by Sonweir** [comment]
> 1.1.6 已修复

我更新了1.1.8版本，发现还是一样的，range、multiple都无效，只能single
