### ISSUE TITLE
[tab-bar] badge-props="{{ { dot: true } }}" 没生效

### ISSUE THREAD

**Issue by Obacm** [Tencent/tdesign-miniprogram#2069]
### tdesign-miniprogram 版本

1.1.8

### 重现步骤

```
<t-tab-bar-item badge-props="{{ { dot: true } }}" ariaLabel="软件，有新的消息" value="label2" icon="app"
    >软件</t-tab-bar-item
  >
```

**Comment by betavs** [comment]
![image](https://github.com/Tencent/tdesign-miniprogram/assets/34408516/3a5343e8-7b89-4c72-aa95-d7bacb44284c)
![image](https://github.com/Tencent/tdesign-miniprogram/assets/34408516/abee3407-9d29-475c-9ff9-aebc511b8a3a)

**Comment by LeeJim** [comment]
`badge-props` 是不是异步修改的？

**Comment by Obacm** [comment]
是的发自我的 iPhone在 2023年6月12日，14:13，leejimchill ***@***.***> 写道：﻿
badge-props 是不是异步修改的？

**Comment by LeeJim** [comment]
试了下也没有问题，请确认下版本对不对
