### ISSUE TITLE
[t-radio-group] options将value=0的放到最后，选中状态的显示不正常

### ISSUE THREAD

**Issue by CanvaChen** [Tencent/tdesign-miniprogram#2078]
### tdesign-miniprogram 版本

1.1.8

### 重现步骤

界面引入t-radio-group，options将value=0的放到最后，即可复现。

index.wxml如下：
```
<t-radio-group bind:change="onChange" value="{{current}}" options="{{options}}" />
```

index.js如下：
```
Page({
  data: {
    current: 1,
    options: [
      { value: 1, label: '单选value=1' },
      { value: 0, label: '单选value=0' },
    ],
  },
  onChange(event) {
    const { value } = event.detail;
    this.setData({ current: value });
  }
});
```

### 期望结果

被选中那行显示选中状态

### 实际结果

1. 点击“单选value=1”选中了两个
![image](https://github.com/Tencent/tdesign-miniprogram/assets/18375123/7fa50007-f40f-4d02-8794-699ec78c4a90)

2. 点击“单选value=0”一个都没选中
![image](https://github.com/Tencent/tdesign-miniprogram/assets/18375123/c503d2f5-8fa3-4d07-91c1-b248b16cc216)

### 基础库版本

2.31.0

### 补充说明

以服务端定义的枚举值做为value，且显示顺序不按0/1/2/3...

**Comment by betavs** [comment]
@CanvaChen 
![企业微信截图_3e521194-6286-44ef-adf7-295e5b979373](https://github.com/Tencent/tdesign-miniprogram/assets/34408516/faf30d56-f2e1-474e-a2e2-51974e6e83df)
