### ISSUE TITLE
[tabs] 能不能实现一个类似于锚点定位的功能

### ISSUE THREAD

**Issue by csshjh** [Tencent/tdesign-miniprogram#2086]
### 这个功能解决了什么问题

能不能实现一个类似于锚点定位的功能，点击哪个选项卡，滑动到对应选项卡下的内容
![image](https://github.com/Tencent/tdesign-miniprogram/assets/11305847/960b35e2-54c1-461e-a68d-28f633623a03)

### 你建议的方案是什么

能不能实现一个类似于锚点定位的功能，点击哪个选项卡，滑动到对应选项卡下的内容
![image](https://github.com/Tencent/tdesign-miniprogram/assets/11305847/960b35e2-54c1-461e-a68d-28f633623a03)

**Comment by LeeJim** [comment]
因为 tab-panel 的内容是自定义的，组件上没办法实现你说的功能。
