### ISSUE TITLE
[t-textarea] indicator显示文本计数器，设置了maxlength 为大于140的数时，文本域只能输入最多140个字符个数

### ISSUE THREAD

**Issue by guochong1** [Tencent/tdesign-miniprogram#2087]
### tdesign-miniprogram 版本

Version：1.1.8

### 重现链接

  <t-textarea     t-class="external-class"     label="备注"     placeholder="请输入备注信息"     maxlength="200"     disableDefaultPadding="{{true}}"     adjust-position="{{true}}"     indicator     value="{{ signParams.remark }}"   />

### 重现步骤

引入t-textarea示例中的设置最大字符个数组件，设置maxlength为大于140的数

### 期望结果

t-textarea可以输入maxlength值个数的字符个数

### 实际结果

最多只能输入140个字符个数

**Comment by anlyyao** [comment]
@guochong1 辛苦在确认一下版本，我这边测试没问题～

**Comment by guochong1** [comment]
"dependencies": {
    "tdesign-miniprogram": "^0.23.1"
  },
我用的这个版本的，我今天试了下还是不行

**Comment by guochong1** [comment]
<t-textarea
    t-class="external-class"
    label="备注"
    placeholder="请输入备注信息"
    maxlength="200"
    disableDefaultPadding="{{true}}"
    adjust-position="{{true}}"
    indicator
    value="{{ signParams.remark }}"
    bind:change="remarkChange"
  />

**Comment by guochong1** [comment]
<t-textarea
    t-class="external-class"
    label="备注"
    placeholder="请输入备注信息"
    maxlength="200"
    disableDefaultPadding="{{true}}"
    adjust-position="{{true}}"
    indicator
    value="{{ signParams.remark }}"
    bind:change="remarkChange"
  />

**Comment by anlyyao** [comment]
> 
你需要升级版本～， 可以关注一下我们的更新日志：https://tdesign.tencent.com/miniprogram/changelog
