### ISSUE TITLE
cell-group 设置 bordered 无法生效

### ISSUE THREAD

**Issue by FFIB** [Tencent/tdesign-miniprogram#2088]
cell-group 设置bordered无法生效。

查看源码。
<img width="837" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/17595093/81b23377-6df7-45c9-baab-be8357f833be">
<img width="686" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/17595093/1660fa91-a994-4619-8e3f-3fa8ff0505c9">

由于在cls方法中，value是对应的判断值，而key是生成对应的class样式，其中bordered传参和字符串'bordered'传参的顺序反了

在本地将代码进行如下修改，可正常显示上下边框。
```
<view
  style="{{_._style([style, customStyle])}}"
  class="{{_.cls(classPrefix, [['bordered', bordered], theme])}} class {{prefix}}-class">
```

**Comment by anlyyao** [comment]
@FFIB 感谢反馈，确实疏忽了。（欢迎给我们提 pr～）
