### ISSUE TITLE
[组件名称] icon 能加两个新chevron图标么 

### ISSUE THREAD

**Issue by rzshuo** [Tencent/tdesign-miniprogram#2095]
### 这个功能解决了什么问题

缺少上下的双剪头

### 你建议的方案是什么

现在只有chevron-right-double 和 chevron-left-double，希望能加上 chevron-down-double 和  chevron-up-double

**Comment by LeeJim** [comment]
下个版本会覆盖这两个图标

**Comment by LeeJim** [comment]
更新至 1.2.0 版本即可
