### ISSUE TITLE
[Grid] t-grid组件的align的 left 属性不生效

### ISSUE THREAD

**Issue by deajax** [Tencent/tdesign-miniprogram#2102]
### tdesign-miniprogram 版本

1.1.9

### 重现步骤

`<t-grid  align="left">
    <t-grid-item icon="share" text="剩余商品数量"></t-grid-item>
</t-grid>`
这个align="left"是不生效的

t-grid-item view 的 class 名是 **t-grid-item__content--left**，
但是在/tdesign-miniprogram/miniprogram_dist/grid-item/grid-item.wxss内第91 和 95 行
的命名却为 **t-grid-item--left**

所以样式不生效，因为命名错了。

### 期望结果

align="left" 左对齐

### 实际结果

align="left" 读不到 css

**Comment by anlyyao** [comment]
@deajax 收到反馈，今天处理～
