### ISSUE TITLE
[t-input] value值为0时不显示值，而显示placeholder

### ISSUE THREAD

**Issue by nanhupatar** [Tencent/tdesign-miniprogram#2103]
### tdesign-miniprogram 版本

1.1.9

### 重现步骤

```wxml
    <t-input label="起始数值" placeholder="请输入数字" maxlength="{{3}}" align="right" suffixIcon="edit" type="number" bind:change="inputChange" value="{{0}}" />
```

**Comment by nanhupatar** [comment]
判断是 https://github.com/Tencent/tdesign-miniprogram/blob/5caf7f835e08e5c34182340e8b28e5ece8a637b1/src/input/input.ts#LL39C7-L39C52 有误

**Comment by nanhupatar** [comment]
按照逻辑，永远无法输入0 因为会被转译为'' 不符合输入数字的情况

**Comment by anlyyao** [comment]
@nanhupatar 收到反馈，今天处理～
