### ISSUE TITLE
[upload] 希望给upload加一个自定义样式名的属性

### ISSUE THREAD

**Issue by slxzlx** [Tencent/tdesign-miniprogram#2104]
### tdesign-miniprogram 版本

1.1.9

### 期望结果

自定义样式类名方便做区分

### 补充说明

希望尽快

**Comment by anlyyao** [comment]
@slxzlx 方便说一下更具体一点的需求或者实际场景吗～

**Comment by SimpleZhl** [comment]
![Uploading 微信截图_20231215191753.png…]()
像这样的，你这个要怎么布局使用呢

**Comment by anlyyao** [comment]
@SimpleZhl 图片加载错误，暂时关闭，后续有需求可以再重新开帖
