### ISSUE TITLE
[t-stepper] 引入组件，随便放一个页面，样式都是乱的，跟演示的不一样，没被其他样式覆盖，放一个空页面也是一样

### ISSUE THREAD

**Issue by xiaohugg** [Tencent/tdesign-miniprogram#2112]
### tdesign-miniprogram 版本

0.3

### 基础库版本

2.28.0

**Comment by LeeJim** [comment]
版本是 `0.3`?

**Comment by xiaohugg** [comment]
是的，默认安装的版本好像是0.3，我现在改成1.1.9了
&nbsp;


魏春虎
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月20日(星期二) 下午3:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tencent/tdesign-miniprogram] [t-stepper] 引入组件，随便放一个页面，样式都是乱的，跟演示的不一样，没被其他样式覆盖，放一个空页面也是一样 (Issue #2112)





 
版本是 0.3?

**Comment by LeeJim** [comment]
那还有问题吗

**Comment by hrpc** [comment]
清理一下缓存
