### ISSUE TITLE
[Calendar] format属性无法获取data中的值

### ISSUE THREAD

**Issue by guluuwater** [Tencent/tdesign-miniprogram#2120]
### tdesign-miniprogram 版本

1.1.8

### 重现步骤

format函数为什么设置在data中？
在format函数中，需要使用data域中的值，该值需要从网络中获取。
那么在使用的过程中，就会遇到format函数中获取不到数据值的情况。
可能是我对前端不是很了解，但目前我确实遇到了这个问题。
请反馈该问题是bug还是使用方式不对，若是使用方式不对，可否告知正确姿势？

### 期望结果

能够获取到data中的值

### 实际结果

获取不到

### 基础库版本

2.19.4

**Comment by horsley** [comment]
基础库 2.21.4 使用 1.1.1版本 tdesign，按照文档放置data里面个格式化函数，直接报错 set property 'format' of undefined。就像函数类型的data字段被过滤掉了一样

**Comment by LeeJim** [comment]
我懂你的意思了。
你的 format 函数里会依赖异步的数据。
那你可以再获取数据之后，再重复设置一下 format

**Comment by guluuwater** [comment]
> 我懂你的意思了。 你的 format 函数里会依赖异步的数据。 那你可以再获取数据之后，再重复设置一下 format

请问您说的重置一下是什么意思？可以给个实例代码吗？谢谢

**Comment by LeeJim** [comment]
> > 我懂你的意思了。 你的 format 函数里会依赖异步的数据。 那你可以再获取数据之后，再重复设置一下 format
> 
> 请问您说的重置一下是什么意思？可以给个实例代码吗？谢谢

就是重新setData(format: () => {})

**Comment by icetofyt** [comment]
请问这个问题最后是怎么解决的？

**Comment by guluuwater** [comment]
> 请问这个问题最后是怎么解决的？
根据前面老哥的提示，我是这样整的，你可以参考下：
1、data中正常定义format，可以让他什么也不做，只返回day
data: {
   format(day) { return day }
}
2、从服务端拿到数据后的处理方式：
fetchData() {
   // 获取数据
  ...
  this.setData({
      format: function(day) {
          // 对指定的day进行处理
        ...
         // 处理后返回
        return day;
     }
  })
}

**Comment by icetofyt** [comment]
> 
在fetchData获取到后端数据后，需要循环数组，这个循环是在format外层还是在format里面。fetchData里面的format传的day这个参数是怎么传的

**Comment by landhuang** [comment]
我试了，达不到预期的效果，照着样例的写法，把format的内容写到按钮里面，点击按钮，调用成功，没有提示错误，但是样式没有任何变化。

**Comment by bo-hw** [comment]
> 我试了，达不到预期的效果，照着样例的写法，把format的内容写到按钮里面，点击按钮，调用成功，没有提示错误，但是样式没有任何变化。

我也碰到了这个问题。不过switch-mode=none时，这个写法是有效的，如果等于month，需要切换一下月份才生效。

**Comment by anlyyao** [comment]
@bo-hw 辛苦重开一个 issue 反馈 switch-mode="month" 场景下无效，我来跟进处理
