### ISSUE TITLE
[t-navbar] 位置显示问题

### ISSUE THREAD

**Issue by xiaohugg** [Tencent/tdesign-miniprogram#2128]
### tdesign-miniprogram 版本

1.1.10

### 重现步骤

引入该组件，位置靠下，放入到内容里了，不是文档上说的位于内容区的上方，系统状态栏的下方。

### 期望结果

位于内容区的上方，系统状态栏的下方

### 基础库版本

2.32.2

**Comment by LeeJim** [comment]
使用 navbar 需要开启 navigationStyle: "custom"

**Comment by xiaohugg** [comment]
好的 我改好了，忘了关闭issue
