### ISSUE TITLE
[Checkbox] 文档描述错误

### ISSUE THREAD

**Issue by bulanzade** [Tencent/tdesign-miniprogram#2134]
### tdesign-miniprogram 版本

1.1.10

### 重现链接

https://tdesign.tencent.com/miniprogram/components/checkbox?tab=api

### 重现步骤

CheckboxGroup Events 的参数描述与实际不符
![image](https://github.com/Tencent/tdesign-miniprogram/assets/45328811/bc9cadb2-cd57-42eb-ae95-4812b44974f4)
实际并没有 context 参数
```ts
this._trigger('change', { value: newValue });
```
https://github.com/Tencent/tdesign-miniprogram/blob/b40609d3f0573067afc002e4058d3067f52aa4e7/src/checkbox-group/checkbox-group.ts#L113C7-L113C7

**Comment by ftxz233** [comment]
@bulanzade this.triggerEvent和this._trigger，这2个有什么区别。
`this.triggerEvent('timeout');
 this._trigger('change', { value: false });`
