### ISSUE TITLE
[t-toast] close事件

### ISSUE THREAD

**Issue by xiaohugg** [Tencent/tdesign-miniprogram#2138]
### tdesign-miniprogram 版本

1.1.10

### 重现步骤

t-ttoast有个隐藏事件，提示消失后会调用close事件方法，但是会触发两次，不知道什么原因？

### 期望结果

t-toast关闭时，只触发一次close

**Comment by xiaohugg** [comment]
另外，小程序组件t-toast  没有回调函数，我表单提交校验用的t-toast，成功后也是t-toast,但是我想要成功后跳转到新页面去，目前t-toast只有关闭和销毁事件，使用这两个导致校验提示结束的时候，也会跳转到新页面，希望加个回调函数

**Comment by LeeJim** [comment]
我来看下问题

**Comment by LeeJim** [comment]
提供下你的代码来看看。目前暂无复现

**Comment by xiaohugg** [comment]
![image](https://github.com/Tencent/tdesign-miniprogram/assets/41934719/286dd0cc-b8b7-46b5-bfbc-4c1f7f327198)
![image](https://github.com/Tencent/tdesign-miniprogram/assets/41934719/f9c30a26-fbe2-4b0a-9f79-c9f8ace2da4e)
![image](https://github.com/Tencent/tdesign-miniprogram/assets/41934719/6639d7d1-a710-45f2-82c1-3138a8e61906)

**Comment by xiaohugg** [comment]
我养殖地区没选提交，提示我养殖地区没选，提示结束后触发两次close事件，跳转登录页跳转了两次

**Comment by LeeJim** [comment]
好 我处理下

**Comment by xiaohugg** [comment]
请问这个是改好了吗？下个版本才能升级？
