### ISSUE TITLE
[popup,stepper] 两个组件同时使用是，stepper总是自动聚焦

### ISSUE THREAD

**Issue by csshjh** [Tencent/tdesign-miniprogram#2142]
### tdesign-miniprogram 版本

1.1.10

### 期望结果

不想让stepper的input自动聚焦

## IssueShoot
- 预估时长: 3
- 期望完成时间: 2023-07-17 00:00:00 +0000 UTC
- 开发难度: 中
- 参与人数: 1
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by LeeJim** [comment]
没懂你的问题，可以补充下代码和场景吗

**Comment by csshjh** [comment]
<view bindtap="addCartHandle">sdsddfssdfsdf</view>


<t-popup visible="{{visible}}" bind:visible-change="onVisibleChange" placement="top" close-btn>
    <view style="height: 200rpx;"></view>
    <t-stepper defaultValue="{{defaultValue}}" value="{{buyCount}}" bind:change="goodsAddShopcar" theme="grey" inputWidth="{{72}}"  /> 
</t-popup>


当我执行addCartHandle这个事件时，popup弹出来的时候，stepper里面的input输入框，光标会自动聚焦，导致手机上输入数字的软键盘会自动弹出来，我想实现的是，popup弹出来的时候，光标不自动聚焦到stepper里面，当我手动点击stepper的时候，软键盘再出来

**Comment by LeeJim** [comment]
我这边按你说的试了一下，并不会出现。
还需要提供更多信息，你的机型和系统版本，以及代码

**Comment by csshjh** [comment]
<view bindtap="addCartHandle">sdsddfssdfsdf</view>


<t-popup visible="{{visible}}" bind:visible-change="onVisibleChange" placement="top" close-btn>
    <view style="height: 200rpx;"></view>
    <t-stepper defaultValue="{{defaultValue}}" value="{{buyCount}}" bind:change="goodsAddShopcar" theme="grey" inputWidth="{{72}}"  /> 
</t-popup>

```````js``````
 addCartHandle(){
    this.setData({
      visible:true
    })
  },

当我执行addCartHandle这个事件时，popup弹出来的时候，stepper里面的input输入框，光标会自动聚焦，导致手机上输入数字的软键盘会自动弹出来，我想实现的是，popup弹出来的时候，光标不自动聚焦到stepper里面，当我手动点击stepper的时候，软键盘再出来

**Comment by feng520ckx** [comment]
这个问题好像跟 #2026 是一个问题

**Comment by csshjh** [comment]
> 我这边按你说的试了一下，并不会出现。 还需要提供更多信息，你的机型和系统版本，以及代码

我用的是安卓系统，红米手机，麻烦用安卓系统的手机测试下
![image](https://github.com/Tencent/tdesign-miniprogram/assets/11305847/0b5f5c25-4170-4aa6-a817-c391f9086798)

**Comment by Markniconico** [comment]
我也遇到这个问题，小米13，t-popup组件内部只要包含input（包括原生组件），就会自动聚焦。不知道是t-popup的问题还是input组件在小米手机上的Bug.

**Comment by LeeJim** [comment]
已经确认问题所在，正在处理

**Comment by Doriathrin** [comment]
> 已经确认问题所在，正在处理

哈喽，这个您这边解决了吗？
