### ISSUE TITLE
[Swiper] 无法加载本地图片

### ISSUE THREAD

**Issue by weizwz** [Tencent/tdesign-miniprogram#2143]
### tdesign-miniprogram 版本

1.1.8

### 重现步骤

![image](https://github.com/Tencent/tdesign-miniprogram/assets/28059498/121c204f-500f-4131-8e40-ec9e24d01e22)
![image](https://github.com/Tencent/tdesign-miniprogram/assets/28059498/9c16e8eb-31ae-48b9-870b-f5bf8db1d910)

### 期望结果

轮播加载本地图片

### 实际结果

本地图片加载报错

**Comment by LeeJim** [comment]
应该是相对路径的问题
