### ISSUE TITLE
[TabBar] external-classes不生效，无法修改tabbar的文字颜色

### ISSUE THREAD

**Issue by Nightsky-Dec** [Tencent/tdesign-miniprogram#2144]
### tdesign-miniprogram 版本

1.1.10

### 重现步骤

<t-tab-bar>成功引用并生效，功能正常使用，但external-classes不生效。且无法修改文字颜色。

### 期望结果

能生成class，能修改文字和icon颜色

**Comment by anlyyao** [comment]
@Nightsky-Dec 请先确认外部样式类用法无误 https://tdesign.tencent.com/miniprogram/custom-style，若用法正确但仍然无效，请贴出可复现代码片段～

**Comment by LeeJim** [comment]
建议使用 css variable 而不是外部样式类
