### ISSUE TITLE
[未知] 微信小程序组件内部报错Cannot read properties of null (reading 'style')

### ISSUE THREAD

**Issue by w-xiaoyang** [Tencent/tdesign-miniprogram#2145]
### tdesign-miniprogram 版本

1.1.6

### 重现步骤

项目内部全局搜索，仅在构建后的miniprogram-npm下的组件中有对应的style取值，如图
<img width="463" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/110385083/b1475ade-5693-4004-849d-22fa59ebc0e3">
微信后台告警如下图，仅Android端出现，且在官方的sourcemap文件中不能正常映射到报错位置
<img width="1096" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/110385083/3c6735d6-4f8e-4b6b-afab-28b6be39f039">

### 期望结果

烦请官方帮忙定位一下，如果确实是组件中取值问题，期望添加空值判断

### 基础库版本

2.32.3

**Comment by LeeJim** [comment]
能否看下你用到了哪些组件？
