### ISSUE TITLE
[DateTimePicker ] 无法选择/变更时间

### ISSUE THREAD

**Issue by china-live** [Tencent/tdesign-miniprogram#2160]
### tdesign-miniprogram 版本

1.1.11

### 重现链接

https://tdesign.tencent.com/miniprogram/components/date-time-picker?tab=demo

### 重现步骤

https://tdesign.tencent.com/miniprogram/components/date-time-picker?tab=demo
官网示例可见，上下滑动改变时间后又回到原点

**Comment by imp2002** [comment]
在电脑上？电脑上是拖拽事件，移动设备是触摸滑动事件，手机上是没问题的
<img width="561" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/41513919/0accf5e1-d9c7-4092-805e-bc8010e777db">

**Comment by china-live** [comment]
我在小程序开发者工具中使用二维码预览也不能选择

**Comment by lankunyao** [comment]
我也遇到这个问题了

**Comment by GeraltWang** [comment]
tdesign mp 1.10.11  同样遇到问题 开发者工具 真机 都无法切换时间

**Comment by china-live** [comment]
怎么办，有什么解决办法？

**Comment by china-live** [comment]
![QQ截图20230707133503](https://github.com/Tencent/tdesign-miniprogram/assets/12002799/20159d31-682b-4a38-8aa3-f777c387c4bd)
修改源码这样可以解决

**Comment by china-live** [comment]
[fix(picker): observe value #2156 ](https://github.com/Tencent/tdesign-miniprogram/pull/2156/files#top)
 
![QQ截图20230707143122](https://github.com/Tencent/tdesign-miniprogram/assets/12002799/954c5c31-0d7f-4a49-845d-e1c331672651)
这个可以解决，希望官方尽快合并并发布新版本。
