### ISSUE TITLE
CheckBox多选框 external-classes不生效

### ISSUE THREAD

**Issue by boyxu** [Tencent/tdesign-miniprogram#217]
### 重现链接
https://github.com/boyxu/boyxu.github.io/blob/master/assets/images/tdesign-issue-20220306.png

### 重现步骤
参考图片，类似的其他几个external-classes也没生效

### 期望结果
修复

### 实际结果

| Environment | Info |
|---|---|
| 相关版本 | 0.5.4 |
| 框架版本 / 基础库版本 | 小程序(v2.21.4) |
| 系统、浏览器 | macOS(12.2.1) |
| Node版本 |  |

**Comment by LeeJim** [comment]
已修复，预计本周内的随着 0.6.0 发布
