### ISSUE TITLE
[DateTimePicker] 选中值发生变化时界面上显示的时间无变化

### ISSUE THREAD

**Issue by codeboytj** [Tencent/tdesign-miniprogram#2171]
### tdesign-miniprogram 版本

1.1.11

### 重现链接

https://tdesign.tencent.com/miniprogram/components/date-time-picker?tab=demo

### 重现步骤

打开页面示例中的 datetimepicker，选择一个新的时间

### 期望结果

datetimepicker中展示的时间发生变化

### 实际结果

没有任何变化

### 补充说明

用户选择时间

**Comment by china-live** [comment]
@codeboytj  前几天我发这个了（#2160），有人已经提交了修补补丁，等合并到发布版本了，暂时只有只有改源码解决。

**Comment by LeeJim** [comment]
duplicated with #2160
