### ISSUE TITLE
[Dialog & Popup]: 滚动穿透问题

### ISSUE THREAD

**Issue by de1ck** [Tencent/tdesign-miniprogram#2184]
### tdesign-miniprogram 版本

1.1.12

### 重现步骤

Overlay 遮罩层处理了滚动穿透问题，但是手指滚动弹窗内部容器时还是会出现滚动穿透现象。

### 期望结果

滚动无法被穿透

### 实际结果

滚动穿透

**Comment by GeraltWang** [comment]
#1743

**Comment by GeraltWang** [comment]
@de1ck  之前我提过 #1743 😂

**Comment by de1ck** [comment]
> @de1ck 之前我提过 #1743 😂

好，我这边关了
