### ISSUE TITLE
[Stepper] 使用该组件安卓会自动获得焦点

### ISSUE THREAD

**Issue by codersunyang** [Tencent/tdesign-miniprogram#2193]
### tdesign 版本

Miniprogram for WeChat 

### 重现步骤

[Stepper] 使用该组件安卓会自动获得焦点
使用代码：
<t-stepper value="{{buyNum}}" min="{{1}}" max="{{buyMax}}" theme="filled" bind:change="handleBuyNumChange" />

### 期望结果

默认不应获取输入框焦点

### 框架版本

1.1.10

**Comment by LeeJim** [comment]
是在 popup 里面嵌套使用吗

**Comment by codersunyang** [comment]
是的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/tdesign-miniprogram"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月21日(星期五) 上午10:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/tdesign-miniprogram] [Stepper] 使用该组件安卓会自动获得焦点 (Issue #2193)





 
是在 popup 里面嵌套使用吗

**Comment by LeeJim** [comment]
fixed #2209 
升级至 1.1.14 以上版本即可
