### ISSUE TITLE
[DatePicker] 标题样式无法修改

### ISSUE THREAD

**Issue by hspjxm** [Tencent/tdesign-miniprogram#2198]
### 这个功能解决了什么问题

对于产品需求 or 客户的审美 ，目前我们DatePicker 组件虽然已经很优秀了，但是 不同的人有着不同的审美 ，目前DatePicker  暂时没有对于 
1：DatePicker  的标题样式 修改的 api
2: DatePicker  的 圆角 的样式是无法修改 
麻烦 贵司在有空闲的时候 是否可以进行 这个控件给予我们修改的权限or api呢

### 你建议的方案是什么

对于1：圆角样式问题 我们是否可以提供  border-radius  的一个参数呢  比如 参数 是一个number或者string 
2：标题样式问题 我们是否可以提供  style 的参数呢 用于设定标题的样式  有的时候 字体 字大小   加粗  文本布局方向 这些都是有不一样的看法

**Comment by hspjxm** [comment]
问题背景 为 我们在开发过程中 对于 标签和圆角我们有自己的一个设定的样式  目前控件的样式 不符合我们需求 ，目前是用的原生初始的一个选择器的形势 自定义了一个日期时间选择器 ，期待Tencent 可以在样式方面进行一个 提供对外的 api

**Comment by LeeJim** [comment]
你用的是哪个框架？看起来不是小程序？

**Comment by hspjxm** [comment]
> 

很抱歉 这个问题 是之前 写 微信原生的时候  弄的一个问题  最近看到 tdesign 中 开始有小程序的组件了 就进行提需求 没有具体的查看到 我目前这个需求在贵司中已经有这方面的api接口了
