### ISSUE TITLE
[slider] 滑块滑不动

### ISSUE THREAD

**Issue by zavatar** [Tencent/tdesign-miniprogram#2199]
### tdesign-miniprogram 版本

1.1.10

### 重现步骤

demo页面里的组件就拖不动。https://tdesign.tencent.com/miniprogram/components/slider?tab=demo

### 期望结果

滑块随着拖动滑动

### 实际结果

滑块不随拖动滑动

**Comment by LeeJim** [comment]
<img width="869" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/7017290/0cd7a7e5-cb6b-4ffd-b70d-4fe15fb1b927">

是不是这个问题
