### ISSUE TITLE
[DateTimePicker]mode属性从年切换到日时 无法滚动月、日

### ISSUE THREAD

**Issue by chwan97** [Tencent/tdesign-miniprogram#2203]
### tdesign-miniprogram 版本

^1.1.12

### 重现步骤

1. t-date-time-picker   mode=year 切换为 mode=date
2. 随后滚动月、日选项

   

 

### 期望结果

月、日选项可以滚动，并且正确选择日期

### 实际结果

月、日选项无法滚动

**Comment by LeeJim** [comment]
这个问题已经修复了，升级至 1.1.13 试试

**Comment by monsterxwx** [comment]
> 这个问题已经修复了，升级至 1.1.13 试试

实测并未修复，最新版本测试的
