### ISSUE TITLE
[cell] t-cell-group内部最后一个t-cell指定bordered=true时也无法显示下边框

### ISSUE THREAD

**Issue by china-live** [Tencent/tdesign-miniprogram#2204]
### tdesign-miniprogram 版本

1.1.12

### 重现步骤

表单内t-cell-group内有2个t-cell 和1个t-input，t-cell 在前，t-input在后、第二个t-cell 无法显示下边框。即使指定bordered=true也无法显示下边框。

### 基础库版本

2.30.0

**Comment by deajax** [comment]
这个问题确实比较困扰，不止cellgroup，cell也是，应该是哪怕是lastchild，也应该可以通过判断border或其他什么属性来强制控制它的

**Comment by anlyyao** [comment]
@china-live @deajax 收到反馈，我来跟进一下～

**Comment by anlyyao** [comment]
> 这个问题确实比较困扰，不止cellgroup，cell也是，应该是哪怕是lastchild，也应该可以通过判断border或其他什么属性来强制控制它的

cell 的border是受bordered控制哈，只是在cellGroup中，最后一项cell取消了border

**Comment by anlyyao** [comment]
@china-live 我刚刚重新看了一下视觉和API实现，也参考了其他业务组件库，目前cellGroup内最后一项cell取消border是比较合理的，也符合更多的场景需要，这不是一个bug。如果你的场景最后一项必须带border，建议自己包cell，弃用cellGroup。
