### ISSUE TITLE
[Fab] 横屏尺寸

### ISSUE THREAD

**Issue by prprprPro** [Tencent/tdesign-miniprogram#2207]
### tdesign-miniprogram 版本

1.1.11

### 重现步骤

横屏模式下fab的尺寸过于巨大。

### 期望结果

缩小横屏模式下fab的尺寸。

### 基础库版本

2.19.4

**Comment by LeeJim** [comment]
应该是小程序 rpx 单位切换的问题，和组件库无关

**Comment by LeeJim** [comment]
<img width="487" alt="企业微信截图_8896db18-3a3a-4c71-8620-c40090c7ad2b" src="https://github.com/Tencent/tdesign-miniprogram/assets/7017290/70fe95e1-dfa5-4fbd-860c-f4a773d6a04d">

是基础库的问题，调整至 2.32.3 以上即可
