### ISSUE TITLE
编译报错，无法使用

### ISSUE THREAD

**Issue by Tinaltt** [Tencent/tdesign-miniprogram#2212]
### tdesign-miniprogram 版本

1.1.13

### 重现步骤

按照官方文档 npm install 后，执行 构建 npm 控制台报错如下图，无法正常使用
<img width="881" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/11289790/158bf584-7c9a-414b-b96e-2958b48ea691">

### 期望结果

能正常使用

### 实际结果

控制台报错各种找不到
<img width="881" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/11289790/a5832f40-847a-499f-a42f-8f03fd0d1805">

### 基础库版本

2.33.0

**Comment by LeeJim** [comment]
<img width="565" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/7017290/cf7f674b-bda4-4c09-ba41-c5469a1a5a45">
是不是忘了构建

**Comment by FuGuangzhi1** [comment]
打开终端-> cd 到miniprogram目录下面-> npm init-y -> npm i tdesign-miniprogram -S --production->点击小程序编辑器最上面的工具->构建npm 还有注意事项如图
![image](https://github.com/Tencent/tdesign-miniprogram/assets/87634542/fdba109a-5441-42bd-8870-8f6e29dff18f)

**Comment by 6lszxz** [comment]
我所有的步骤都是按照文档中的注意事项进行的，但是依然出现了同样的错误
