### ISSUE TITLE
[sticky] 组件不停销毁和创建 onScroll一直在叠加执行

### ISSUE THREAD

**Issue by Markniconico** [Tencent/tdesign-miniprogram#2213]
### tdesign-miniprogram 版本

1.1.13

### 重现步骤

发现pageScrollMixin里的detached清除组件滚动函数的过程，scroller 和bind(this)之后的scroller 不相等，导致filter过滤不掉组件的scroller 。

detached() {
            var _a;
            const page = getCurrentPage();
            if (!page) return;
            page.pageScroller = ((_a = page.pageScroller) === null || _a === void 0 ? void 0 : _a.filter(item => item !== scroller)) || [];
        },

**Comment by LeeJim** [comment]
我来研究下是否存在这个问题
