### ISSUE TITLE
[Radio] disabled=true，样式生效，点击事件不生效

### ISSUE THREAD

**Issue by CrossLee** [Tencent/tdesign-miniprogram#222]
### 重现链接
https://codepen.io/huxiweng/pen/jOaRVRE

### 重现步骤
CODEPEN里写了关键部分代码，就是判断页面加载进来后，此用户（cuser）的profile.age 是否有值，有值则不让切换 Radio（disable=true）。

### 期望结果
disable后就不让切换值

### 实际结果
还是可以切换值

| Environment | Info |
|---|---|
| 相关版本 | 0.5.2 |
| 框架版本 / 基础库版本 | 小程序 v2.14.1 |
| 系统、浏览器 | MacOS 12.2.1 微信开发者工具 1.05 |
| Node版本 |  |

**Comment by CrossLee** [comment]
https://user-images.githubusercontent.com/4584905/157054695-a22188eb-366e-4beb-8d34-766c7fc1b63a.mov

**Comment by LeeJim** [comment]
看起来，感觉应该是使用错误的问题。
`disabled` 的值应该放在 `radio-group` 而不是 `radio`

**Comment by CrossLee** [comment]
> 看起来，感觉应该是使用错误的问题。 `disabled` 的值应该放在 `radio-group` 而不是 `radio`

@LeeJim 直接在 `radio-group`标签上写死 disabled="{{true}}"，不会生效

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/4584905/157215118-6ab494c2-995b-440e-8207-153815225f66.png">

**Comment by LeeJim** [comment]
是原生组件，不是 TDesign 组件
