### ISSUE TITLE
[Link] 设置 navigator-props open-type 无效

### ISSUE THREAD

**Issue by qianxuu** [Tencent/tdesign-miniprogram#2222]
### tdesign-miniprogram 版本

1.1.13

### 重现步骤

参考官网 API 设置 `open-type` 无法生效

![image](https://github.com/Tencent/tdesign-miniprogram/assets/62287903/ccf9f224-4b1d-45ff-bd59-4cacff76af26)
![image](https://github.com/Tencent/tdesign-miniprogram/assets/62287903/7a9a6447-ca36-46f7-9902-43ade06bb482)
![image](https://github.com/Tencent/tdesign-miniprogram/assets/62287903/fcea8d3a-bf59-4b78-bf5f-66666f6610d3)
![image](https://github.com/Tencent/tdesign-miniprogram/assets/62287903/ab844c20-4cdf-47d6-886c-44b31f433917)

### 基础库版本

3.0.0

**Comment by qianxuu** [comment]
查看源码发现，实际使用时需要将键名改为使用小驼峰，建议在文档中补充说明，此外，设置 `open-type` 为 `navigateBack` 但没有设置 `url`，样式为无效状态的样式，这种情况应该为正常状态样式更好？
![image](https://github.com/Tencent/tdesign-miniprogram/assets/62287903/367d66dc-49d2-4843-89fa-57e7e670d6cd)

**Comment by LeeJim** [comment]
fixed by #2227
