### ISSUE TITLE
[Swiper] 能否更新一下文档？

### ISSUE THREAD

**Issue by WBBB0730** [Tencent/tdesign-miniprogram#2248]
### tdesign-miniprogram 版本

1.1.15

### 基础库版本

2.33.0

### 补充说明

文档太混乱了，外部样式类也没有说明

**Comment by WBBB0730** [comment]
卡片式（cards）轮播图
示例代码与其他代码不统一，且没有对应的解释

**Comment by WBBB0730** [comment]
是否有一些属性已经废弃了，但没有在文档中更新？例如height、--td-swiper-radius等

**Comment by WBBB0730** [comment]
如何自定义图片的高度？在 t-swiper 组件中添加属性 height: "318rpx"时，报错 unexpected attribute name, near `"318rpx...`

**Comment by betavs** [comment]
> 如何自定义图片的高度？在 t-swiper 组件中添加属性 height: "318rpx"时，报错 unexpected attribute name, near `"318rpx...`

```height="318rpx"```

**Comment by LeeJim** [comment]
应该是遗漏了，我来处理下

**Comment by WBBB0730** [comment]
> 应该是遗漏了，我来处理下

好的，辛苦了~ ❤
