### ISSUE TITLE
toast api 调用, 多次调用时，之前传入的参数比如： direction  placement icon 会固化在组件内部。 不符合预期。

### ISSUE THREAD

**Issue by scshsy** [Tencent/tdesign-miniprogram#225]
### 重现链接
https://github.com/Tencent/tdesign-miniprogram

### 重现步骤
比如在当前页面，第一次调用：

Toast({
  context: this,
  selector: '#t-toast',
  message: '带图标竖向',
  icon: 'star',
  direction: 'column',
});

第二次调用：
Toast({
  context: this,
  selector: '#t-toast',
  message: 'xxxxxxx',
});

第二次调用时，icon 和 direction 会使用第一次传入的值。

### 期望结果
第二次调用时toast不应该出现星星图标，以及应该是横向排列

### 实际结果
第二次调用时toast时出现了 星星图标和纵向排列

| Environment | Info |
|---|---|
| 相关版本 | 0.5.4 |
| 框架版本 / 基础库版本 | 小程序 |
| 系统、浏览器 | 小程序 |
| Node版本 |  |

**Comment by LeeJim** [comment]
收到，我跟进处理一下
