### ISSUE TITLE
[TabBar] 教程错误，组件中“纯图标标签栏”中WXML中代码不包含icon内容，实际显示为“纯文本标签栏”

### ISSUE THREAD

**Issue by YuanCY** [Tencent/tdesign-miniprogram#2255]
### tdesign-miniprogram 版本

1.1.15

### 重现链接

https://tdesign.tencent.com/miniprogram/components/tab-bar

### 重现步骤

![image](https://github.com/Tencent/tdesign-miniprogram/assets/31584588/d7bae4be-0d7b-4b4b-8484-e09ae0b6ea2c)
官网教程错误，组件tabbar中，题为“纯图标标签栏”中wxml代码无icon相关内容，实际显示效果为“纯文本标签栏”。
复现步骤：
1、打开官网基础组件-微信小程序，tabbar标签栏。url:https://tdesign.tencent.com/miniprogram/components/tab-bar
2、找到“纯图标标签栏”，其中WXML代码中，无icon相关内容，所以实际显示只有文本没有图标。为教程错误。

### 期望结果

tabbar纯图标标签栏处显示WXML代码正确，t-tab-bar-item中加入icon属性，并在js中为每个item加入icon属性实际内容。删除t-tab-bar-item中{{ item.label }}文本。

### 实际结果

纯图标标签栏处代码为纯文本标签栏处代码一样，实际显示效果只有文字没有图标

### 补充说明

教程错误，文档书写不细心啊。

**Comment by anlyyao** [comment]
@YuanCY 感谢反馈，已处理
