### ISSUE TITLE
[Collapse] default-expand-all 首次要点击两次才能收缩。

### ISSUE THREAD

**Issue by synctimes163** [Tencent/tdesign-miniprogram#2267]
### tdesign-miniprogram 版本

^1.1.15

### 重现步骤

t-collapse  组件使用 default-expand-all 属性，首次要点击两次才能收缩。

![image](https://github.com/Tencent/tdesign-miniprogram/assets/78259973/b8b038d4-0306-40cb-9ace-96589c80ad6c)

### 期望结果

首次点击一次就能收缩
      <t-collapse default-expand-all>
        <t-collapse-panel expandIcon>
          <t-link slot="header" theme="primary" content="{{ item.Label }}" />
          <block wx:for="{{ item.Children }}">
            <t-tag class="margin-16" variant="light">{{ item.Label }}</t-tag>
          </block>
        </t-collapse-panel>
      </t-collapse>

**Comment by LeeJim** [comment]
我跟进看看问题
