### ISSUE TITLE
[t-cell-group] Cell Group 组件包裹非单元格（t-cell）组件是否会产生潜在的问题

### ISSUE THREAD

**Issue by narukeu** [Tencent/tdesign-miniprogram#2268]
因为 t-cell-group 可以通过设置 theme="card" 属性变成圆角的卡片效果，我觉得这样很好看，然后经过尝试发现可以在里面包裹非单元格（t-cell）组件，但因为 t-cell-group 组件设置的本意是为了包裹单元格，所以我不知道包裹非单元格组件是否会产生一些潜在的问题。
希望可以得到解答，谢谢。

**Comment by LeeJim** [comment]
没有
