### ISSUE TITLE
[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by QxQxZhou** [Tencent/tdesign-miniprogram#2275]
### tdesign-miniprogram 版本

上传视频选择来源无效

### 重现步骤

 config: {
      count: 1,
      sourceType:'camera', 
      maxDuration: 60, // 拍摄视频最长拍摄时间，
      camera:'back', // 仅在 sourceType 为 camera 时生效，使用前置或后置摄像头
    },，如此传参，sourceType:'camera',  仅能拍摄无效，还是可以选择从相册上传

### 基础库版本

2.33.0

**Comment by LeeJim** [comment]
<img width="380" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/7017290/b02fcbd0-30f8-4cb5-8bcd-6f6e2807d13c">

请看清楚 API 类型，要传入 `['camera']` 才是有效的。
