### ISSUE TITLE
官网为啥不能访问了

### ISSUE THREAD

**Issue by lixunhui** [Tencent/tdesign-miniprogram#2278]
### tdesign-miniprogram 版本

官网

### 重现链接

https://tdesign.tencent.com/miniprogram

### 重现步骤

https://tdesign.tencent.com/miniprogram 官方无法访问

### 期望结果

https://tdesign.tencent.com/miniprogram

### 实际结果

https://tdesign.tencent.com/miniprogram

**Comment by LeeJim** [comment]
可以正常访问哈，有可能是cdn短暂出问题了，换个网络试试
