### ISSUE TITLE
[Radio] 文档问题

### ISSUE THREAD

**Issue by wanghui2021** [Tencent/tdesign-miniprogram#2282]
### tdesign-miniprogram 版本

1.1.15

### 重现链接

https://tdesign.tencent.com/miniprogram/components/radio?tab=api

### 重现步骤

官网Radio 外部样式类 t-class-border 的旁边多了个字符

<img width="538" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/37385554/dede9468-45e3-4d71-8fc8-1398e7b7542a">

### 基础库版本

2.33.0

**Comment by LeeJim** [comment]
fixed by acfbb30b627ce6332b90c31e2a9fe94fc95a3f9e
