### ISSUE TITLE
[Divider] 分割线都不显示

### ISSUE THREAD

**Issue by Cyclonecat** [Tencent/tdesign-miniprogram#2296]
### tdesign-miniprogram 版本

1.1.15

### 重现步骤

![图片](https://github.com/Tencent/tdesign-miniprogram/assets/17287309/ef497221-4a18-4ea0-ac0e-8d4ddded382e)

![图片](https://github.com/Tencent/tdesign-miniprogram/assets/17287309/ce7c8b31-c77e-4966-92b3-f99e2a270bc7)

### 基础库版本

2.23.1

**Comment by LeeJim** [comment]
麻烦提供下设备信息，我这边是正常的。

<img width="383" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/7017290/d69ad0ac-8f89-4fcf-8b1f-f11fdf7318cf">

**Comment by Cyclonecat** [comment]
设备信息：
![图片](https://github.com/Tencent/tdesign-miniprogram/assets/17287309/ae18e3b2-3992-4004-bda4-8c5e46198f82)
浏览器信息
![图片](https://github.com/Tencent/tdesign-miniprogram/assets/17287309/176b6dc0-c4a9-49af-9364-cc1a00fc1713)
微信开发者工具信息
![图片](https://github.com/Tencent/tdesign-miniprogram/assets/17287309/784b4857-8b11-452a-9959-925743c9f55b)
在火狐浏览器和微信开发者工具都不显示。

**Comment by Cyclonecat** [comment]
经过验证，本电脑的Safari、Google Chrome、Microsoft Edge的这三个浏览器都能显示出分割线，火狐和微信开发者工具不能显示
