### ISSUE TITLE
[button] block 属性无效

### ISSUE THREAD

**Issue by rxshan** [Tencent/tdesign-miniprogram#2346]
### tdesign-miniprogram 版本

1.2.2

### 重现链接

[bug-reproduction](https://github.com/rxshan/bug-reproduction.git)

### 期望结果

设置 block 属性能撑满整个容器。

### 实际结果

宽度没有撑满

### 基础库版本

3.0.1

### 补充说明

可能受 button:not([size=mini])样式影响，button 固定宽度为 184px, 但微信开发者工具显示 block 的样式并没有被覆盖。

_No response_

**Comment by betavs** [comment]
无法复现，能否提供示例代码

**Comment by rxshan** [comment]
> 无法复现，能否提供示例代码

@betavs https://github.com/rxshan/bug-reproduction.git

**Comment by betavs** [comment]
![image](https://github.com/Tencent/tdesign-miniprogram/assets/34408516/e73fbdb5-3635-4d5d-897c-a220efa58d89)
