### ISSUE TITLE
[check-tag] `shape="round"` 失效   

### ISSUE THREAD

**Issue by Moln** [Tencent/tdesign-miniprogram#2364]
### tdesign-miniprogram 版本

1.2.3

### 重现步骤

```html
<t-check-tag  variant="light" shape="round"   />
```

### 期望结果

`shape="round"` 生效

### 实际结果

`shape="round"` 无效

**Comment by betavs** [comment]
![image](https://github.com/Tencent/tdesign-miniprogram/assets/34408516/09638d04-0a04-4092-81c2-df56bbf7a41e)

**Comment by Moln** [comment]
@betavs   谢谢回复
有其它建议的替代实现方式吗？

**Comment by betavs** [comment]
> @betavs 谢谢回复 有其它建议的替代实现方式吗？

可以自定义组件，内部引入 `check-tag` 自定义样式实现；不知道官方基于什么考量废弃，目前已提pr
