### ISSUE TITLE
[TabBar 标签栏]中 wx.switchTab({url}) 与 that.setData({         value: value,       }); 共存会导致显示异常

### ISSUE THREAD

**Issue by ryiot** [Tencent/tdesign-miniprogram#2378]
### tdesign-miniprogram 版本

1.2.3

### 重现步骤

<img width="424" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/78907118/832e51d2-dc25-45fb-b6f0-4db83111f124">

Component({
  data: {
    value: 'home',
    list: [
      { value: 'home', label: '首页', icon: 'home' },
      { value: 'family', label: '家庭', icon: 'app' },
      { value: 'me', label: '我的', icon: 'user' },
    ],
  },
  methods: {
    onChange(e) {
      let that = this;
      const value = e.detail.value;
      that.setData({
        value: value,
      });
      const url = '/pages/' + that.data.value + '/index';
      wx.switchTab({url})
    },
  },
});

<t-tab-bar value="{{value}}" bindchange="onChange" theme="tag" split="{{false}}">
  <t-tab-bar-item wx:for="{{list}}" wx:key="index" value="{{item.value}}" icon="{{item.icon}}">
    {{item.label}}
  </t-tab-bar-item>
</t-tab-bar>

{
  "component": true,
  "usingComponents": {
    "t-tab-bar": "tdesign-miniprogram/tab-bar/tab-bar",
    "t-tab-bar-item": "tdesign-miniprogram/tab-bar-item/tab-bar-item"
  }
}

<img width="279" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/78907118/2c7d3874-49d3-460c-80c6-8e31808369ad">

### 期望结果

<img width="304" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/78907118/c0358a88-b3a5-4fad-ac78-79453c1b54bf">

### 实际结果

<img width="279" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/78907118/2c7d3874-49d3-460c-80c6-8e31808369ad">

### 基础库版本

2.19.6

**Comment by ryiot** [comment]
<img width="550" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/78907118/521721a2-c0c3-4d7f-8baf-faa14bba20c9">
<img width="469" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/78907118/f9c72269-79bb-4c96-99a6-6274b46b45f8">
<img width="1012" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/78907118/869dc059-36a5-43dd-b018-8dbf2b2ae92b">

**Comment by ryiot** [comment]
> 查看是否有报错信息
> 
> ```ts
> wx.switchTab({
>   url,
>   complete: (res) => {
>     console.log(res);
>   },
> });
> ```

<img width="604" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/78907118/80be044e-7dbc-4cc0-b2c3-1a79de4d94d3">

**Comment by ryiot** [comment]
> 看看是否有报错信息
> 
> ```ts
> wx.switchTab({
>   url,
>   complete: (res) => {
>     console.log(res);
>   },
> });
> ```

无报错信息

**Comment by betavs** [comment]
可以的话，请提供复现代码仓库

**Comment by betavs** [comment]
可以的话，请提供复现代码仓库

**Comment by betavs** [comment]
[自定义 tabBar](https://developers.weixin.qq.com/miniprogram/dev/framework/ability/custom-tabbar.html)

**Comment by Copy-Hao** [comment]
> [自定义 tabBar](https://developers.weixin.qq.com/miniprogram/dev/framework/ability/custom-tabbar.html)
> 
> ![image](https://user-images.githubusercontent.com/34408516/270849677-62e4651f-c172-4e8d-9a59-1151aa25d8d2.png)

我试过了用getTabBar()方法去setData还是不行，你可以拉下我的代码去试一下 `git clone https://github.com/Copy-Hao/TDesign-TabBar-Issue.git` 另外 这个官方文档中的例子是没有这种问题的https://developers.weixin.qq.com/s/ouJiKgm67cHk

**Comment by ryiot** [comment]
![image](https://github.com/Tencent/tdesign-miniprogram/assets/78907118/e2cc3d4b-a93b-46a4-a010-e6abf6c45d88)
这种方式也可以解决问题

**Comment by SYH0323** [comment]
https://github.com/Tencent/tdesign-miniprogram/issues/903#issuecomment-1635520819

参考这层楼，在图标不变更的那个界面的onShow函数加上这段代码就可以了。

`onShow() {
if (typeof this.getTabBar === 'function' && this.getTabBar()) {
this.getTabBar().setData({ value: ‘具体 value’})
}
}`
