### ISSUE TITLE
[Upload]建议增加disabled

### ISSUE THREAD

**Issue by Markniconico** [Tencent/tdesign-miniprogram#2379]
### 这个功能解决了什么问题

某些场景需要禁用

### 你建议的方案是什么

增加disabled属性

**Comment by Wen1kang** [comment]
disabled状态：图片叠加55%透明度的white，add的icon颜色修改为--text-color-disabled
<img width="423" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/89069385/efb01197-fc5a-4b47-9be5-d3bb601aa3df">
