### ISSUE TITLE
[Navbar] 导航栏问题

### ISSUE THREAD

**Issue by wosinkong** [Tencent/tdesign-miniprogram#2383]
### tdesign-miniprogram 版本

1.2.3

### 重现步骤

调试设备：iPhone12
系统版本：iOS16.6
微信版本：8.0.42
代码样本：https://tdesign.tencent.com/miniprogram/components/navbar#%E8%83%B6%E5%9B%8A%E6%A0%B7%E5%BC%8F%E5%AF%BC%E8%88%AA%E6%A0%8F
使用的是TDesign演示代码
对应的CSS风格代码也使用了

### 实际结果

开启左侧胶囊效果 结果胶囊位置不对
就算关闭胶囊显示 也会有胶囊阴影

### 基础库版本

3.1.2

### 补充说明

![IMG_0725](https://github.com/Tencent/tdesign-miniprogram/assets/102869711/58a48276-b794-4cd2-9c3f-4d23964d5097)

**Comment by alhaidarykhalid** [comment]
K

**Comment by anlyyao** [comment]
1.6.2 版本未能复现上述问题
