### ISSUE TITLE
[cell] 使用t-cell-group包裹t-cell 下边框显示问题

### ISSUE THREAD

**Issue by xia930425** [Tencent/tdesign-miniprogram#2385]
### tdesign-miniprogram 版本

1.1.0

### 重现步骤

微信开发工具不显示下边框，使用真机调试可以看到下边框，但是一直延申到最右侧。
![image](https://github.com/Tencent/tdesign-miniprogram/assets/78598847/6efeabca-2c13-4215-baf7-69f6cf42f629)
![9df40b5cbb8607320994e6676f6dd5a](https://github.com/Tencent/tdesign-miniprogram/assets/78598847/7c72074c-8708-4c50-b353-f05e92257c72)

## IssueShoot
- 预估时长: 1
- 期望完成时间: 2023-10-21 00:00:00 +0000 UTC
- 开发难度: 低
- 参与人数: 1
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by xia930425** [comment]
问题已解决。使用--td-cell-border-right-space修改边框右侧距离，开发工具看不见是因为边框太细。不知道用什么变量修改边框粗细呢？

**Comment by betavs** [comment]
https://github.com/Tencent/tdesign-miniprogram/blob/6ec8a35ac2a835ce145ce41b483b55165559aec3/src/common/style/mixins/_hairline.less#L29-L36

目前暂无变量控制

**Comment by anlyyao** [comment]
> https://github.com/Tencent/tdesign-miniprogram/blob/6ec8a35ac2a835ce145ce41b483b55165559aec3/src/common/style/mixins/_hairline.less#L29-L36
> 
> 目前暂无变量控制

可以暴露一个css variable 出去，大佬有空支持一下嘎🤣？
