### ISSUE TITLE
[input] 可以考虑做一个车牌号的键盘吗？

### ISSUE THREAD

**Issue by Zlianxin** [Tencent/tdesign-miniprogram#2391]
### 这个功能解决了什么问题

对于和汽车相关的小程序，不可避免的需要输入车牌号，如果可以有一个专门的车牌号键盘，使用起来体验会好很多。

### 你建议的方案是什么

可以在 type 属性里面添加一个 car，当为car的时候，呼出一个虚拟键盘，里面是车牌号。

**Comment by anlyyao** [comment]
@Zlianxin 算是业务场景了，暂时不考虑哈～

**Comment by Zlianxin** [comment]
> @Zlianxin 算是业务场景了，暂时不考虑哈～

好吧，那我就自己手画一个了~
