### ISSUE TITLE
[Icon 图标 ] 微信小程序引入iconfont图标之后无法修改图标颜色

### ISSUE THREAD

**Issue by HuPengCheng1994** [Tencent/tdesign-miniprogram#2396]
### tdesign-miniprogram 版本

1.2.3

### 重现步骤

![image](https://github.com/Tencent/tdesign-miniprogram/assets/34332093/b072936a-e4d9-4ba9-9e69-7d391e8ecd3a)

![image](https://github.com/Tencent/tdesign-miniprogram/assets/34332093/0e9d8b98-80dc-4a24-8904-6551884751d5)

### 期望结果

图标颜色

### 实际结果

没有颜色

### 基础库版本

1.2.3

**Comment by anlyyao** [comment]
@HuPengCheng1994 我这边测试可以正常修改，

代码片段：https://developers.weixin.qq.com/s/Gs8P63mH72M8
<img width="381" alt="截屏2023-10-18 10 27 45" src="https://github.com/Tencent/tdesign-miniprogram/assets/51158141/81392a2a-92c2-4a6f-a5d2-17ec281cf30d">

**Comment by HuPengCheng1994** [comment]
> @HuPengCheng1994我的金字塔可以测试修改正常，请在确认一下，如果还是有问题，可以提供可复现的代码片段。
> 
> 代码片段：https://developers.weixin.qq.com/s/Gs8P63mH72M8 <img alt="截屏2023-10-18 10 27 45" width="381" src="https://user-images.githubusercontent.com/51158141/276058898-81392a2a-92c2-4a6f-a5d2-17ec281cf30d.png">



> @HuPengCheng1994我的金字塔可以测试修改正常，请确认一下，如果还是有问题，可以提供可恢复的代码片段。
> 
> 代码片段：https://developers.weixin.qq.com/s/Gs8P63mH72M8 <img alt="截屏2023-10-18 10 27 45" width="381" src="https://user-images.githubusercontent.com/51158141/276058898-81392a2a-92c2-4a6f-a5d2-17ec281cf30d.png">

我用我的自己生成的在线链接就不能修改颜色了，其他代码完整用你的代码片段，不知道是哪里出了问题。
//at.alicdn.com/t/c/font_4290114_hqld5jyl98q.css

**Comment by HuPengCheng1994** [comment]
> @HuPengCheng1994 我这边测试可以正常修改，请在确认一下，如果还是有问题，可以提供可复现代码片段。
> 
> 代码片段：https://developers.weixin.qq.com/s/Gs8P63mH72M8 <img alt="截屏2023-10-18 10 27 45" width="381" src="https://user-images.githubusercontent.com/51158141/276058898-81392a2a-92c2-4a6f-a5d2-17ec281cf30d.png">

**Comment by HuPengCheng1994** [comment]
我用我的自己生成的在线链接就不能修改颜色了，其他代码完整用你的代码片段，不知道是哪里出了问题。
//at.alicdn.com/t/c/font_4290114_hqld5jyl98q.css

**Comment by anlyyao** [comment]
> @anlyyao 我用我的自己生成的在线链接就不能修改颜色了，其他代码完整用你的代码片段，不知道是哪里出了问题。 //at.alicdn.com/t/c/font_4290114_hqld5jyl98q.css

来个代码片段吧～ 👀

**Comment by HuPengCheng1994** [comment]
@anlyyao 麻烦啦 https://developers.weixin.qq.com/s/SRoz73m470Mk

**Comment by anlyyao** [comment]
> @anlyyao 麻烦啦 https://developers.weixin.qq.com/s/SRoz73m470Mk

不确定是不是转base64的问题，你换成在线链接👀

**Comment by HuPengCheng1994** [comment]
> > @anlyyao 麻烦啦 https://developers.weixin.qq.com/s/SRoz73m470Mk
> 
> 不确定是不是转base64的问题，你换成在线链接👀

用的就是在线链接，只不过我勾选了iconfont项目设置里面的一个base64选项。
![image](https://github.com/Tencent/tdesign-miniprogram/assets/34332093/d6966db2-4765-4638-80fc-02dafa748f15)

**Comment by anlyyao** [comment]
彩色不勾。

我试了下在线连接，https://developers.weixin.qq.com/s/9pKHY4mC7wMC
效果： <img width="376" alt="截屏2023-10-19 12 00 58" src="https://github.com/Tencent/tdesign-miniprogram/assets/51158141/80fe62f5-5b14-4f5a-9cfb-362e6c870e2e">

**Comment by HuPengCheng1994** [comment]
> @HuPengCheng1994 彩色不勾。
> 
> 我试了下在线连接，https://developers.weixin.qq.com/s/9pKHY4mC7wMC 效果： <img alt="截屏2023-10-19 12 00 58" width="376" src="https://user-images.githubusercontent.com/51158141/276480349-80fe62f5-5b14-4f5a-9cfb-362e6c870e2e.png">

可以了，居然是因为我勾选了彩色！ 感谢耐心解答！
