### ISSUE TITLE
[t-checkbox] 中的 checked 属性不生效，无法选中

### ISSUE THREAD

**Issue by zhangstore** [Tencent/tdesign-miniprogram#2400]
### tdesign-miniprogram 版本

^1.2.2

### 重现步骤

<t-checkbox-group>
    <t-cell wx:for="{{memberList}}" wx:for-item="member" wx:key="index" aria-role="button">
      <view slot="left-icon">
        <t-checkbox 
          block="{{false}}"       
          value="{{member.id}}" 
          borderless="{{true}}" 
          label="{{member.name}}"
          checked="{{member.id == '10'}}"
          content="{{member.position.name}}" 
        />
      </view>
    </t-cell>
  </t-checkbox-group>

### 期望结果

这里循环 checkbox，希望在某个 item 的 id 等于特定值时选中此选项。

### 实际结果

不选中，同样的判断，但是 disabled 属性可以出现禁用效果。

## IssueShoot
- 预估时长: 1
- 期望完成时间: 2023-11-30
- 开发难度: 低
- 参与人数: 1
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by zhangstore** [comment]
<t-checkbox-group>
    <t-cell wx:for="{{memberList}}" wx:for-item="member" wx:key="index" aria-role="button">
      <view slot="left-icon">
        <t-checkbox 
          block="{{false}}"       
          value="{{member.id}}" 
          borderless="{{true}}" 
          label="{{member.name}}"
          checked="{{member.id == '10'}}"
          content="{{member.position.name}}" 
        />
      </view>
    </t-cell>
  </t-checkbox-group>

**Comment by zhangstore** [comment]
`
<t-checkbox-group>
    <t-cell wx:for="{{memberList}}" wx:for-item="member" wx:key="index" aria-role="button">
      <view slot="left-icon">
        <t-checkbox 
          block="{{false}}"       
          value="{{member.id}}" 
          borderless="{{true}}" 
          label="{{member.name}}"
          checked="{{member.id == '10'}}"
          content="{{member.position.name}}" 
        />
      </view>
    </t-cell>
  </t-checkbox-group>
`

**Comment by pei-han** [comment]
好issue,困扰了我一下午，v-for遍历，绑定始终不生效，颠覆认知
