### ISSUE TITLE
[DropdownMenu] 展开后向上滚动，菜单栏和展开项分离了

### ISSUE THREAD

**Issue by vicorn** [Tencent/tdesign-miniprogram#2401]
### tdesign-miniprogram 版本

1.2.3

### 重现步骤

1. 代码如下
```
<view>
  <scroll-view scroll-y
    style="height:2000px;background-color: gray;">
    <view style="height: 200px;"></view>
    <t-dropdown-menu>
      <t-dropdown-item label="筛选"
        bindchange="onChange">
        <t-tree-select options="{{options}}"
          value="{{value}}"
          bind:change="onChange" />
      </t-dropdown-item>
      <t-dropdown-item label="全部" />
    </t-dropdown-menu>
  </scroll-view>
</view>
```
2. 向上滚动
3. 效果如下
![企业微信截图_20231019102017](https://github.com/Tencent/tdesign-miniprogram/assets/30787425/ddb80821-f26d-4d97-b96f-6c903ff5a700)

### 期望结果

展开项跟随菜单栏一起滚动上去

### 实际结果

向上滚动后，菜单栏向上滚动，展开项原地不动。
ps: 另外还有两个问题
1. 此时TreeSelect的左侧栏，在真机中溢出不能滚动，右侧可以，推测是左侧高度设置了100%原因。
2. 此时按住菜单栏也可以滚动，发生滚动穿透，这种该如何解决。

## IssueShoot
- 预估时长: 3
- 期望完成时间: 2024-02-27
- 开发难度: 中
- 参与人数: 1
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by TANGYC-CS** [comment]
确实  发现后偶然点进来一看就看到了这条issue

**Comment by Wen1kang** [comment]
展开菜单栏后，是不允许滑动的遮罩固定
如果滑动，菜单栏则收起
