### ISSUE TITLE
[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by YingchenWang007** [Tencent/tdesign-miniprogram#2407]
### 这个功能解决了什么问题

什么时候可以支持 vue3  vite ts uni-app 去开发微信小程序呢？

### 你建议的方案是什么

什么时候可以支持 vue3  vite ts uni-app 去开发微信小程序呢？

**Comment by anlyyao** [comment]
@YingchenWang007 tdesign-miniprogram是一个原生小程序组件库，加上目前人力有限，所以官方暂时不考虑去适配其他框架。
