### ISSUE TITLE
[Navbar] 带搜索的导航栏，文字字体错误

### ISSUE THREAD

**Issue by xiaweiss** [Tencent/tdesign-miniprogram#2413]
### tdesign-miniprogram 版本

1.2.3

### 重现链接

tdesign示例小程序

### 重现步骤

<img width="414" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/17960084/8366740a-9826-4a84-9522-5bf19716cbc4">

### 期望结果

带搜索的导航栏，文字字体期望系统字体

### 实际结果

带搜索的导航栏，文字字体是宋体

### 基础库版本

3.1.5

**Comment by anlyyao** [comment]
tip : input 组件是一个原生组件，字体是系统字体，所以无法设置 font-family

see: https://developers.weixin.qq.com/miniprogram/dev/component/input.html
