### ISSUE TITLE
[Navbar] 大标题尺寸，点击「返回」文字无反应，标题和返回不在同一行

### ISSUE THREAD

**Issue by xiaweiss** [Tencent/tdesign-miniprogram#2414]
### tdesign-miniprogram 版本

1.2.3

### 重现链接

tdesign示例小程序

### 重现步骤

![image](https://github.com/Tencent/tdesign-miniprogram/assets/17960084/fb9d1ba4-52e4-402f-b86a-f051ed784063)

### 期望结果

[Navbar] 大标题尺寸，点击「返回」文字有反应，标题和返回在同一行

### 实际结果

[Navbar] 大标题尺寸，点击「返回」文字无反应，标题和返回不在同一行

### 基础库版本

3.1.5

**Comment by anlyyao** [comment]
@xiaweiss 大兄弟，我们只是提供一个参考示例🤣，很多跟场景相关的交互不会全部完成的。非bug和feature外的需求，可能需要自己处理一下～

**Comment by xiaweiss** [comment]
<img width="810" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/17960084/2e0d28f1-b063-49a4-ab6b-fc0a47bb3524">
理解，「返回」这两个字不是用户配置的，那么点击「返回」文字时，预期是能返回的，现在无反应。算是 bug 吧？
@anlyyao

**Comment by anlyyao** [comment]
> <img alt="image" width="810" src="https://private-user-images.githubusercontent.com/17960084/284875621-2e0d28f1-b063-49a4-ab6b-fc0a47bb3524.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MzYzOTUsIm5iZiI6MTcyOTczNjA5NSwicGF0aCI6Ii8xNzk2MDA4NC8yODQ4NzU2MjEtMmUwZDI4ZjEtYjA2My00OWE0LWFiNmItZmMwYTQ3YmIzNTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDAyMTQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliOTg4MjQ0ZTcyZTQwMzA5NmIxZjZhNmY2YTBjMzA5NDYwNGYxOWQ0MDUwYTY2YTA2NzIxNGYxMDhmYjc3MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.N43_j3kLM6KysEsPSE4Qgen679PTbFNUpEGYYl6o_TA"> 理解，「返回」这两个字不是用户配置的，那么点击「返回」文字时，预期是能返回的，现在无反应。算是 bug 吧？ @anlyyao

组件的返回功能是加在left-arrow上面。 算是示例不严谨吧，我补充一下示例、
