### ISSUE TITLE
[Tabbar] 弱选中标签栏，红色气泡遮住了底部图标

### ISSUE THREAD

**Issue by xiaweiss** [Tencent/tdesign-miniprogram#2416]
### tdesign-miniprogram 版本

1.2.3

### 重现链接

tdesign示例小程序

### 重现步骤

<img width="412" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/17960084/2833274e-5269-44eb-bf4f-e1d80bf8d96d">

### 期望结果

[Tabbar] 弱选中标签栏，红色气泡靠右一些，不遮住底部图标

### 实际结果

[Tabbar] 弱选中标签栏，红色气泡遮住了底部图标

### 基础库版本

3.1.5

## IssueShoot
- 预估时长: 1
- 期望完成时间: 2023-11-30
- 开发难度: 低
- 参与人数: 1
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by anlyyao** [comment]
@xiaweiss badge-props 属性可以透传给Badge组件，你可以自行调整 offset 属性来调整徽标位置
```
badge-props="{{ {count: 16, offset: [-5,-5]} }}"
```

**Comment by xiaweiss** [comment]
@anlyyao 看起来是 right top 定位的，建议使用 left top 来定位。
如果字数不确定的情况下，left top 能自适应宽度。而 right top 则需要先计算文字宽度，再自定调整 offset。
建议考虑下开发者体验

**Comment by anlyyao** [comment]
@xiaweiss 收到反馈，确实可以优化一下。 欢迎你一起来共建🏹呀～
