### ISSUE TITLE
[Switch] 开关，按钮大小不一致

### ISSUE THREAD

**Issue by xiaweiss** [Tencent/tdesign-miniprogram#2418]
### tdesign-miniprogram 版本

最新版

### 重现链接

tdesign示例小程序

### 重现步骤

<img width="414" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/17960084/d1129953-9503-4b1f-96fc-8d1152ad03df">

### 基础库版本

3.1.5

**Comment by anlyyao** [comment]
@xiaweiss 我这边看[官网](https://tdesign.tencent.com/miniprogram-live/m2w/program/miniprogram/#!pages/switch/switch.html)是正常的呀？ 你用的什么浏览器呢？

**Comment by xiaweiss** [comment]
@anlyyao 请看截图，我说的是按钮🔘里头的白色圆形。不过看起来设计图就是如此。

**Comment by anlyyao** [comment]
> @anlyyao 请看截图，我说的是按钮🔘里头的白色圆形。不过看起来设计图就是如此。

设计如此。
