### ISSUE TITLE
[t-fab] 怎么修改t-fab按钮的背景色以突出显示重点，例如按钮的theme="primary"

### ISSUE THREAD

**Issue by wuyunfeng8** [Tencent/tdesign-miniprogram#2419]
### 这个功能解决了什么问题

[t-fab] 怎么修改t-fab按钮的背景色以突出显示重点，例如按钮的theme="primary"

### 你建议的方案是什么

[t-fab] 怎么修改t-fab按钮的背景色以突出显示重点，例如按钮的theme="primary"

**Comment by anlyyao** [comment]
@wuyunfeng8 修改样式相关问题，请查看官网[文档](https://tdesign.tencent.com/miniprogram/custom-style)

**Comment by wuyunfeng8** [comment]
谢谢，找到解决办法了，利用button-props设置fabButton: {
      theme: "light",
    },即可

**Comment by anlyyao** [comment]
> 谢谢，找到解决办法了，利用button-props设置fabButton: { theme: "light", },即可

也行吧 但这可能不是最佳方案，如果需要随时可控建议查看官网文档，我这里先 close 了，若有新问题，欢迎随时提issue~
