### ISSUE TITLE
[cell] 外部样式类t-class-title划分不合理

### ISSUE THREAD

**Issue by Oreslok** [Tencent/tdesign-miniprogram#2428]
### tdesign-miniprogram 版本

2.8.3-1

### 重现步骤

`<t-cell title="我是标题">`
`  <view slot="note">`
`    <t-button>选择1</t-button>`
`    <t-button>选择2</t-button>`
`  </view>`
`</t-cell>`

上述代码，在微信开发者工具中，将解析为

`<view class="t-class t-cell t-middle">`
`  <view class="t-cell__left t-class-left"></view>`
`  <view class="t-cell__title">`
`    <view class="t-cell__title-text t-class-title"></view>`
`  </view>`
`  <view class="t-cell__note t-class-note"></view>`
`  <view class="t-cell__right t-class-right"></view>`
`</view>`
`</view>`

这么一看发现问题了吗？ t-class-left t-class-note  t-class-right 都位于第二层，但偏偏 t-class-title在第三层
如果我想控制title这一层的样式，依靠t-class-title可不行，得使用t-cell__title，所以建议把t-class-title放到t-cell__title后

**Comment by anlyyao** [comment]
@Oreslok 微信开发工具解析出来的结构只是一部分，整个组件的dom结构建议查看源码，整体上看位置暂时不会调整。然后，你直接使用`t-class-title`无效的本质原因和位置无关，是优先级问题。 组件中title样式写在 `x__title-text`选择器上，而外部样式类`t-class-title`和`x__title-text`优先级是未定义的。所以建议你提高`t-class-title`的优先级，这边提供一个[代码片段](https://developers.weixin.qq.com/s/dZ3flzmd7YMP)给可供参考。

**Comment by Oreslok** [comment]
@anlyyao 我觉得你可能没有理解我意思。我目的就是控制title区域的样式。举个例子吧，我想调整title的flex。

<t-cell title="详细地址" t-class-title="my-title"></t-cell>
.my-title { flex: none !important; }

你看，基于上述代码，并不能达到我设置flex: none的目的，我必须通过.t-cell__title才能实现

**Comment by anlyyao** [comment]
> @anlyyao 我觉得你可能没有理解我意思。我目的就是控制title区域的样式。举个例子吧，我想调整title的flex。
> 
> ```
> <t-cell title="详细地址" t-class-title="my-title"></t-cell>
> .my-title { flex: none !important; }
> ```
> 
> 你看，基于上述代码，并不能达到我设置flex: none的目的，我必须通过.t-cell__title才能实现

![image](https://github.com/Tencent/tdesign-miniprogram/assets/51158141/8bff221d-2cd1-4cb8-9e21-a1bb1df18bd4)
我想表达的是源码中类`__title`包含的不止是title内容，t-class-title的位置没有问题不会做出调整，你这个需求应该是在新增一个外部样式 `t-class-center` ，让你外部可控中间整块内容

**Comment by Oreslok** [comment]
> > @anlyyao 我觉得你可能没有理解我意思。我目的就是控制title区域的样式。举个例子吧，我想调整title的flex。
> > ```
> > <t-cell title="详细地址" t-class-title="my-title"></t-cell>
> > .my-title { flex: none !important; }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 你看，基于上述代码，并不能达到我设置flex: none的目的，我必须通过.t-cell__title才能实现
> 
> ![image](https://user-images.githubusercontent.com/51158141/283028836-8bff221d-2cd1-4cb8-9e21-a1bb1df18bd4.png) 我想表达的是源码中类`__title`包含的不止是title内容，t-class-title的位置没有问题不会做出调整，你这个需求应该是在新增一个外部样式 `t-class-center` ，让你外部可控中间整块内容

点赞！
