### ISSUE TITLE
[Search] 搜索框自动完成

### ISSUE THREAD

**Issue by wuyunfeng8** [Tencent/tdesign-miniprogram#2432]
### 这个功能解决了什么问题

搜索框自动完成

### 你建议的方案是什么

搜索框自动完成
## IssueShoot
- 预估时长: 3
- 期望完成时间: 2023-11-30
- 开发难度: 中
- 参与人数: 1
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by anlyyao** [comment]
@wuyunfeng8 自动完成是什么意思？ 展开说说🤔️？

**Comment by fatindeed** [comment]
> @wuyunfeng8 自动完成是什么意思？ 展开说说🤔️？

https://weui.io/#searchbar
应该是这个吧，search框内输入内容后，出现若干相关结果，可以直接选取。
我也想要这个实现。
