### ISSUE TITLE
[PullDownRefresh 下拉刷新] scroll-view滚动scrollTop不准确

### ISSUE THREAD

**Issue by KwongSum** [Tencent/tdesign-miniprogram#2435]
### tdesign-miniprogram 版本

1.2.3

### 重现步骤

```html
<t-pull-down-refresh
  value="{{enable}}"
  bind:scroll="onScroll"
>
</t-pull-down-refresh>
``` 
bindscroll="onScroll"  检测滚动距离
```javascript
onScroll(e) {
    console.log('滚动距离：'+e.detail)
},

"disableScroll": true,
``` 

在快速滑动的情况下，明明已经到顶了但是scrollTop还显示为10~100，
缓慢滑动没有问题，但是快速滚动的时候scrollTop会出现非常大的误差。
![微信截图_20231115110751](https://github.com/Tencent/tdesign-miniprogram/assets/23690174/cb019327-9578-42f9-b1f6-2d371a4f2369)

**### 先说我的解决方法**

因为每次滚动监听事件都会被调用比较耗费资源系统会默认节流可以在scroll-view 加一个 throttle=“{{false}}” 关闭节流
来源：[微信小程序scroll-view滚动scrollTop不准确](https://blog.csdn.net/woshiabc111/article/details/130708519)

### 期望结果

返回准确scrollTop位置，让我实现动态为Navbar导航栏设置背景颜色
```javascript
onScroll(e) {
    let opacity = e.detail / 140
    opacity = opacity > 1 ? 1 : opacity
    this.setData({
        opacity : opacity 
      })
},
``` 
```html
<view  style="opacity: {{opacity}};"></view>
``` 

![微信截图_20231115111459](https://github.com/Tencent/tdesign-miniprogram/assets/23690174/9279e74c-aec0-4645-b1a5-96f61d9e04b6)
![微信截图_20231115111450](https://github.com/Tencent/tdesign-miniprogram/assets/23690174/92f94728-eb94-45ff-952b-f7f809fbbbe9)
![微信截图_20231115111758](https://github.com/Tencent/tdesign-miniprogram/assets/23690174/f024f4ff-7979-46aa-a147-e00f459db2e0)

## IssueShoot
- 预估时长: 3
- 期望完成时间: 2023-11-30
- 开发难度: 中
- 参与人数: 1
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by anlyyao** [comment]
@KwongSum 感谢反馈，下个版本带上。 另外，我这边看到你已经查阅有了解决方案，要不要来个🤣，一起共建🏹呢～
