### ISSUE TITLE
swiper  图片传入本地图片 无法加载

### ISSUE THREAD

**Issue by dongshihao666** [Tencent/tdesign-miniprogram#2442]
### tdesign-miniprogram 版本

1.2.4

### 重现链接

<MSwiper imgList="{{imgList}}" />      data: {         imgList: [       './images/pic_1_1.png',       './images/pic_1_1.png',       './images/pic_1_1.png',       './images/pic_1_1.png'     ]   },

### 重现步骤

传入本地图片无法加载  传入cdn图片就可以

### 期望结果

传入本地图片一样可以加载

## IssueShoot
- 预估时长: 1
- 期望完成时间: 2023-11-30 
- 开发难度: 低
- 参与人数: 1
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by anlyyao** [comment]
@dongshihao666 小程序里面的二封过的image组件，使用相对地址时要格外注意，因为你传入的相对路径是相对二封组件不是相对原生image组件的，所以无法正确获取图片路径。这不是一个bug，但是我们这边可以优化处理一下，感谢反馈～

**Comment by anlyyao** [comment]
@byq1213 @dongshihao666  #2493
