### ISSUE TITLE
[Grid] grid-item使用image-props透传属性到Image，报错

### ISSUE THREAD

**Issue by tankle0** [Tencent/tdesign-miniprogram#2443]
### tdesign-miniprogram 版本

1.2.3

### 重现步骤

![image](https://github.com/Tencent/tdesign-miniprogram/assets/63094764/e08ffbfd-94f6-4c83-9116-41788107ba71)

### 期望结果

希望可以传递图片属性到image组件

### 实际结果

文档描述需要传递Object类型，但实际传递后报错
![image](https://github.com/Tencent/tdesign-miniprogram/assets/63094764/bd0d3f7c-2936-4165-85e2-7e38b332373d)
![image](https://github.com/Tencent/tdesign-miniprogram/assets/63094764/e08ffbfd-94f6-4c83-9116-41788107ba71)

### 基础库版本

3.2.0

**Comment by anlyyao** [comment]
@tankle0  试试 imageProps="{{ { showMenuByLongpress: true} }}"

**Comment by tankle0** [comment]
> @tankle0 试试 imageProps="{{ { showMenuByLongpress: true} }}"

可以~
