### ISSUE TITLE
[Upload 上传] 建议增加拖动排序功能

### ISSUE THREAD

**Issue by wyz-zy** [Tencent/tdesign-miniprogram#2444]
### 这个功能解决了什么问题

是使用过upload上传的功能确实好用，用来上传轮播图或者商品详图。但是很多情况都需要给这些图片排序。还有编辑时可能要在之前上传的图片中间插入一张图。目前只能全部删除了重新按顺序上传一次。十分不方便。

### 你建议的方案是什么

做一个拖动排序的功能，长按图片拖动调换顺序。同时在上传的时候把图片顺序返回。我目前自己把这个组件修改出来这样的效果，长按震动，拖动排序。只是建议直接在原框架上增加这样的功能
## IssueShoot
- 预估时长: 5
- 期望完成时间: 2023-01-15
- 开发难度: 高
- 参与人数: 1
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by china-live** [comment]
我也想要这个功能+1
