### ISSUE TITLE
[icon] 急需修复~更新iOS最新的17.1.1版本之后icon展示不出来

### ISSUE THREAD

**Issue by luchanghong** [Tencent/tdesign-miniprogram#2446]
### tdesign-miniprogram 版本

1.2.4

### 重现步骤

小程序开发工具正常显示：
<img width="320" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/1669377/efc0d775-d154-4a5b-a3f0-f56bf06c3d72">
iOS 真机异常
![image](https://github.com/Tencent/tdesign-miniprogram/assets/1669377/c9f58c9b-e2b8-4a0d-b237-f2922a43f736)
你们的官方小程序也显示不出来
![image](https://github.com/Tencent/tdesign-miniprogram/assets/1669377/562bcb02-f84b-479b-9211-94acd38454f1)

**Comment by anlyyao** [comment]
@luchanghong 和系统版本应该没啥关系，我这边17.1， 13 pro， 目前一切正常，请确认一下你的网络情况，或者切换个网络试试
![image](https://github.com/Tencent/tdesign-miniprogram/assets/51158141/c585e042-2108-493f-a1ef-e67aee9f92d6)
