### ISSUE TITLE
[indexes] 希望索引可以有点击跳转功能

### ISSUE THREAD

**Issue by HungryFlo** [Tencent/tdesign-miniprogram#2477]
### 这个功能解决了什么问题

以城市为例，当用户点击一个城市时，可以检测点击的城市，并做出相应的操作（如跳转到相应城市对应的页面）

### 你建议的方案是什么

添加该功能或在文档中说明如何实现

**Comment by HungryFlo** [comment]
请问如何区分点击不同cell的不同业务逻辑，是使用下标吗？

**Comment by anlyyao** [comment]
> 请问如何区分点击不同cell的不同业务逻辑，是使用下标吗？

都可以。 如果你想同步拿到当前子项更多信息，可以用data-* 属性协助标示

**Comment by HungryFlo** [comment]
明白啦，谢谢！
