### ISSUE TITLE
[upload] 显示样式出错

### ISSUE THREAD

**Issue by CRECOHE** [Tencent/tdesign-miniprogram#2481]
### tdesign-miniprogram 版本

1.2.4

### 重现步骤

![image](https://github.com/Tencent/tdesign-miniprogram/assets/57332732/faf2ecc3-0c6d-4903-a572-f9f57d751a36)
默认应用，出现样式的问题，在真机上查看，同样的问题，只有column为1，才显示正常
`gridConfig: {
      column: 1,
      width: 160,
      height: 160,
    },`
### 期望结果

期望像示例一样的样式

### 基础库版本

3.2.3

**Comment by betavs** [comment]
感谢反馈，貌似已在 #2449 中修复，将在下一个版本体现

**Comment by betavs** [comment]
该问题已处理，可以更新版本至1.2.5，查看是否正常
