### ISSUE TITLE
[Calendar] 在苹果手机真机上use-popup未设定值或设定true，都会直接显示出来。开发工具正常

### ISSUE THREAD

**Issue by mustars** [Tencent/tdesign-miniprogram#2483]
### tdesign-miniprogram 版本

1.2.4和1.2.5

### 重现步骤

直接复制官网代码即可复现
wxml
<t-calendar visible="{{visible}}" bind:confirm="handleConfirm" bind:close="onClose" />
<t-cell arrow title="单个选择日历" bind:tap="handleCalendar" note="{{note}}" />

js
Component({
  data: {
    visible: false,
    note: '',
  },
  methods: {
    handleCalendar() {
      this.setData({ visible: true });
    },
    handleConfirm(e) {
      const { value } = e.detail;
      const format = (val) => {
        const date = new Date(val);
        return `${date.getFullYear()}-${date.getMonth() + 1}-${date.getDate()}`;
      };

      this.setData({
        note: format(value),
      });
    },
    onClose({ detail }) {
      console.log(detail.trigger);
    },
  },
});

### 期望结果

真机上正常点击cell后显示calendar

### 实际结果

真机上cell和calendar都直接显示了
![da4fee683f781078300f97fcab79c86](https://github.com/Tencent/tdesign-miniprogram/assets/26319610/3371a664-3dd5-4787-8719-9b2d24e32ad0)

### 基础库版本

2.15.0、3.2.4

```[tasklist]
### Tasks
```

**Comment by mustars** [comment]
这个bug什么时候能修复啊。着急

**Comment by jarmywang** [comment]
> 这个bug什么时候能修复啊。着急

已到位到原因，小程序glass-easel框架真机环境<include>节点上不支持 wx: 指令，处理中，会尽快发版修复
