### ISSUE TITLE
[Calendar] 在苹果手机真机上use-popup未设定值或设定true，都会直接显示出来。开发工具正常

### ISSUE THREAD

**Issue by mustars** [Tencent/tdesign-miniprogram#2484]
### tdesign-miniprogram 版本

1.2.4和1.2.5

### 重现步骤

![image](https://github.com/Tencent/tdesign-miniprogram/assets/26319610/47abcb2c-9247-4a96-b5ba-94c23c934b65)
![1702114220972](https://github.com/Tencent/tdesign-miniprogram/assets/26319610/d5ac0404-3d1a-44ba-b42f-66fa22b4c815)
未设定use-popup属性为false，但在手机预览时直接铺在页面上。iphone13，微信版本8.0.44

### 期望结果

未设定use-popup，或设定为true时，真机点击cell后日历应在popup里显示

### 实际结果

页面直接显示calendar

### 基础库版本

3.2.4

**Comment by anlyyao** [comment]
duplicate #2483
