### ISSUE TITLE
[Grid] hover 属性设置为true 点击貌似没有效果显示

### ISSUE THREAD

**Issue by pyzworld** [Tencent/tdesign-miniprogram#2501]
### tdesign-miniprogram 版本

能

### 重现链接

  <t-grid class="block" column="{{ 3 }}" theme="card" hover="{{ true }}">   <t-grid-item text="标题文字" image="https://user-images.githubusercontent.com/15634204/157386871-bf84c2ea-a02f-4c1c-b6fd-577450cdbcf7.png" url="/pages/graphics/taper/index"/> </t-grid>

### 重现步骤

点击grid item 没有hover 效果

### 基础库版本

3.0.2

**Comment by pyzworld** [comment]
`  <t-grid class="block" column="{{ 3 }}" theme="card" hover="{{ true }}">
  <t-grid-item text="标题文字" image="https://user-images.githubusercontent.com/15634204/157386871-bf84c2ea-a02f-4c1c-b6fd-577450cdbcf7.png" url="/pages/graphics/taper/index"/>
</t-grid>`

**Comment by pyzworld** [comment]
`
<t-grid class="block" column="{{ 3 }}" theme="card" hover="{{ true }}">
      <t-grid-item text="标题文字" image="https://user-images.githubusercontent.com/15634204/157386871-bf84c2ea-a02f-4c1c-b6fd-577450cdbcf7.png" url="/pages/graphics/taper/index"/>
</t-grid>

`

**Comment by pyzworld** [comment]
`  <t-grid class="block" column="{{ 3 }}" theme="card" hover="{{ true }}">
  <t-grid-item text="标题文字" image="https://user-images.githubusercontent.com/15634204/157386871-bf84c2ea-a02f-4c1c-b6fd-577450cdbcf7.png" url="/pages/graphics/taper/index"/>
</t-grid>`

**Comment by betavs** [comment]
```css
--td-grid-item-bg-color: transparent
```
暂时可以设置 `item` 的背景色为透明以解决此问题
