### ISSUE TITLE
[t-cell] leftIcon属性无法使用自定义图标

### ISSUE THREAD

**Issue by ch-zms** [Tencent/tdesign-miniprogram#2506]
### 这个功能解决了什么问题

leftIcon属性无法使用自定义图标

### 你建议的方案是什么

希望支持使用自定义图标

**Comment by anlyyao** [comment]
@ch-zms 可能leftIcon需要扩展一下Object类型，支持全量传入icon  props 🤔，这个问题我们全局处理一下。 建议你这边先用slot方式使用自定义图标～
