### ISSUE TITLE
[Button] 当 open-type="share" 时，组件上绑定的自定义数据无法获取

### ISSUE THREAD

**Issue by CrossLee** [Tencent/tdesign-miniprogram#251]
### tdesign-miniprogram 版本

0.5.2

### 重现链接

https://codepen.io/huxiweng/pen/GRyRgQP

### 重现步骤

按照 codepen 上代码就可以复现。

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/4584905/158010352-9da516b3-2695-48ec-a696-080b17ef20c9.png">

### 期望结果

和原生组件一样，能正常获取绑定的自定义参数值。

### 实际结果

不能正常获取绑定的自定义参数值。

### 框架版本

小程序 2.14.1

### 补充说明

原生组件是可以获取到的。

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/4584905/158010249-c0289f4e-8a25-4eef-b967-6dcd5aeff18b.png">

**Comment by LeeJim** [comment]
关联错了
