### ISSUE TITLE
@waney  是指，选中后，滑动tabs，仍希望选中项在可视区域内吗？

### ISSUE THREAD

**Issue by li-b-y** [Tencent/tdesign-miniprogram#2515]
@waney  是指，选中后，滑动tabs，仍希望选中项在可视区域内吗？

_Originally posted by @anlyyao in https://github.com/Tencent/tdesign-miniprogram/issues/759#issuecomment-1214560947_

请问这个目前好像也没有实现是吗

**Comment by anlyyao** [comment]
Duplicate of #759
