### ISSUE TITLE
[Tabs 选项卡] 希望增加内容对齐方式，现在默认上下居中，希望可以增加顶部对齐，底部对齐方式

### ISSUE THREAD

**Issue by 315574925** [Tencent/tdesign-miniprogram#2517]
### 这个功能解决了什么问题

[Tabs 选项卡] 希望增加内容对齐方式，现在默认上下居中，希望可以增加顶部对齐，底部对齐方式

### 你建议的方案是什么

增加内容对齐CSS变量

**Comment by jarmywang** [comment]
此类场景比较少见，建议通过t-class-item自行实现
