### ISSUE TITLE
[Grid 宫格] 当column(每一行的列数量)设置为0时，可滚动状态下，存在scroll-view组件默认滚动条，未提供api控制是否显示滚动条

### ISSUE THREAD

**Issue by 315574925** [Tencent/tdesign-miniprogram#2518]
### 这个功能解决了什么问题

如果横向存在滚动条，界面非常不美观

### 你建议的方案是什么

建议通过组件传参方式，设置 scroll-view 组件的 enhanced 和 show-scrollbar 属性，控制滚动条是否显示

**Comment by jarmywang** [comment]
经过内部讨论与真机体验，暂不提供此api，滚动条可以提示用户此处可滑动，然后滑一下滚动条会自动消失是符合规范的，你可以通过一些hook的方式尝试去掉滚动条

**Comment by 315574925** [comment]
那可以美化下那个原生的滚动条下不呢，那个原生滚动条太丑了，比如这样
![511f035900b9a073ba635e74155412e](https://github.com/Tencent/tdesign-miniprogram/assets/34641313/51927ff0-6919-404c-bc2e-b396e9e530de)

有些场景下可能不需要显示滚动条呢，灵活控制不更好吗
