### ISSUE TITLE
[t-swipe-cell] 在 IOS 真机上无法滑动，开发者工具模拟器中正常滑动

### ISSUE THREAD

**Issue by Logosww** [Tencent/tdesign-miniprogram#2524]
### tdesign-miniprogram 版本

1.2.6

### 期望结果

TSwipeCell 能正常滑动

### 实际结果

TSwipeCell 在 IOS 真机上不能滑动

### 基础库版本

3.3.0

### 补充说明

在真机上调试，console 中有如下警告信息：
![IMG_1225(20231228-231252)](https://github.com/Tencent/tdesign-miniprogram/assets/87473526/b817e10d-8cef-4157-a1c8-a2ad67c050da)

**Comment by Logosww** [comment]
找到原因了，项目开了 lazyCodeLoading，才会出现这种情况，关掉后就正常了。麻烦定位一下问题在哪里？

**Comment by anlyyao** [comment]
> 找到原因了，项目配置了 `“lazyCodeLoading”： “requiredComponents"`，才会出现这种情况（顺带一提，`componentFramework`我配置的是新版的`glass-easel`，跟这个有关系嘛？），关掉后就正常了。麻烦定位一下问题在哪里？

初步怀疑和 glass-easel 有关，然后绑定来自WXS事件的类型没判对，函数当字符串处理了。已反馈给微信官方，还没收到回复～

**Comment by Nero978** [comment]
> @vant/weapp

你好，我也遇到了同样的问题。请问现在这个issue有进展吗？或者有没有临时的解决方案呢？🤔
![image](https://github.com/Tencent/tdesign-miniprogram/assets/63546553/294de28e-62a3-4a9e-9cb7-c000bfa47fcd)

**Comment by anlyyao** [comment]
目前只能移除配置项: componentFramework: glass-easel

**Comment by anlyyao** [comment]
Duplicate #2668
