### ISSUE TITLE
[picker] picker在IOS真机下出下被遮住问题，可能与scroll-view有关

### ISSUE THREAD

**Issue by mipaifu328** [Tencent/tdesign-miniprogram#2526]
### tdesign-miniprogram 版本

1.2.6

### 重现链接

https://developers.weixin.qq.com/s/BCY7kUmu7JNK

### 重现步骤

picker在IOS真机下出下被遮住问题，可能与scroll-view有关

### 期望结果

<img width="382" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/12646930/be964a67-1d6e-4522-9a86-5ec3d4817e7b">

### 实际结果

<img width="494" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/12646930/da6df2c2-48da-4c10-a370-d0f314d7c1fd">

### 基础库版本

3.2.5

**Comment by mipaifu328** [comment]
发现ios popup相关的都会被遮挡

**Comment by mipaifu328** [comment]
发现ios popup相关的都会被遮挡

**Comment by ZHUBoer** [comment]
同样的问题，这个能否解决呢？还是有方法去规避？t-picker的弹窗会被页面元素遮挡。

**Comment by mipaifu328** [comment]
> 同样的问题，这个能否解决呢？还是有方法去规避？t-picker的弹窗会被页面元素遮挡。

只能把popup类的弹窗全部放到scroll-view外面

**Comment by anlyyao** [comment]
@mipaifu328 @ZHUBoer 微信小程序中的原生组件层级是最高的，不受 z-index 控制。 root-portal 可以解决你的问题，详情见[文档](https://developers.weixin.qq.com/miniprogram/dev/component/root-portal.html)

**Comment by mipaifu328** [comment]
> @mipaifu328 @ZHUBoer 微信小程序中的原生组件层级是最高的，不受 z-index 控制。 root-portal 可以解决你的问题，详情见[文档](https://developers.weixin.qq.com/miniprogram/dev/component/root-portal.html)

感谢回复，确实可以，学到了！

**Comment by anlyyao** [comment]
> > @mipaifu328 @ZHUBoer 微信小程序中的原生组件层级是最高的，不受 z-index 控制。 root-portal 可以解决你的问题，详情见[文档](https://developers.weixin.qq.com/miniprogram/dev/component/root-portal.html)
> 
> 感谢回复，确实可以，学到了！

👌 那我这边就先关闭 issue 了，如果有新问题欢迎重新开贴讨论～
