### ISSUE TITLE
[TabBar] 微信开发者工具警告 Some selectors are not allowed in component wxss

### ISSUE THREAD

**Issue by Oreslok** [Tencent/tdesign-miniprogram#2528]
### tdesign-miniprogram 版本

1.2.3

### 重现步骤

在微信小程序中，使用TabBar后，微信开发者工具警告：
Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./custom-tab-bar/index.wxss:7:1)

index.wxss中相关代码
`@keyframes tdesign-fade-out {
  from {
    opacity: 1;
  }
  to {
    opacity: 0;
  }
}
`

### 基础库版本

3.2.5

**Comment by betavs** [comment]
貌似是你本地代码的问题，能否提供 `./custom-tab-bar/index.wxss:7:1` 代码

**Comment by Oreslok** [comment]
> 貌似是你本地代码的问题，能否提供 `./custom-tab-bar/index.wxss:7:1` 代码

准备搞个复现的demo给你，没想到还真是本地代码的问题 冏
