### ISSUE TITLE
[Button ] formType文档中与插件中属性名不一样，导致formType失效

### ISSUE THREAD

**Issue by xteabag** [Tencent/tdesign-miniprogram#253]
### tdesign-miniprogram 版本

0.6.1

### 重现链接

https://github.com/Tencent/tdesign-miniprogram/blob/develop/src/button/button.wxml

### 重现步骤
![微信图片_20220313181818](https://user-images.githubusercontent.com/101502341/158055176-e35ec882-5813-4df2-9ce6-b10821508573.png)
![微信图片_20220313181825](https://user-images.githubusercontent.com/101502341/158055178-81d4a457-feee-4aa7-a476-a1e5c9876556.png)
![微信图片_20220313181830](https://user-images.githubusercontent.com/101502341/158055180-78b54302-cec6-4c4c-b469-9d1e9a546cdc.png)

[Button ] formType文档中与插件中属性名不一样，导致formType失效

**Comment by LeeJim** [comment]
same as #248
