### ISSUE TITLE
[Guide 引导] 逐步骤进行指引或解释说明的组件

### ISSUE THREAD

**Issue by 315574925** [Tencent/tdesign-miniprogram#2538]
### 这个功能解决了什么问题

逐步骤进行指引或解释说明的组件，常用于用户不熟悉的或需进行特别强调的页面

### 你建议的方案是什么

[参考](https://tdesign.tencent.com/vue/components/guide?tab=design)
## IssueShoot
- 预估时长: 8
- 期望完成时间: 2024-07-04 00:00:00 +0000 UTC
- 开发难度: 高
- 参与人数: 1
- 需求对接人: jeannehuang;anlyyao;jarmywang
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by anlyyao** [comment]
@RADWIMPS426 有空帮忙评估一下，是否需要支持噶🤣～

**Comment by RADWIMPS426** [comment]
@Wen1kang
