### ISSUE TITLE
[Checkbox] change时只会显示当前选中的

### ISSUE THREAD

**Issue by ARotterGoodMan** [Tencent/tdesign-miniprogram#2544]
### tdesign-miniprogram 版本

重现

**Comment by ARotterGoodMan** [comment]
![临沂外国语学校规划指导群](https://github.com/Tencent/tdesign-miniprogram/assets/73062083/cf0d3131-60e5-40ad-bc7f-0b7f495958aa)

**Comment by ARotterGoodMan** [comment]
![Uploading this.png…]()

**Comment by ARotterGoodMan** [comment]
![Uploading this.png…]()

**Comment by ARotterGoodMan** [comment]
> 不太清楚你的问题🤔

![image](https://github.com/Tencent/tdesign-miniprogram/assets/73062083/e542237e-e53b-481f-8f93-9018b0b39cec)

**Comment by betavs** [comment]
在 `CheckboxGroup` 中触发 `change` 事件，会返回选中的所有结果。目前测试无法复现，方便提供复现代码吗 🤔

**Comment by ARotterGoodMan** [comment]
> 在 `CheckboxGroup` 中触发 `change` 事件，会返回选中的所有结果。目前测试无法复现，方便提供复现代码吗 🤔

![1704880311693](https://github.com/Tencent/tdesign-miniprogram/assets/73062083/8343b2d9-e8f1-404d-9528-b0268913248d)
![image](https://github.com/Tencent/tdesign-miniprogram/assets/73062083/abcea3db-5db7-4c49-ba64-a8a5eedea80b)

**Comment by betavs** [comment]
https://github.com/Tencent/tdesign-miniprogram/blob/da48df50510ffdfa2d1147682af9b447049121f4/src/checkbox/_example/horizontal/index.wxml#L1-L5

在当前版本1.2.6中测试效果如下

![image](https://github.com/Tencent/tdesign-miniprogram/assets/34408516/2042f9d9-2279-490e-85ea-d093d3bc4ebb)

由此看来，此问题还是无法复现，可以的话将整个项目提交到GitHub
