### ISSUE TITLE
[t-input] model:value 模拟器中双向绑定没问题，但是真机双向绑定就没用

### ISSUE THREAD

**Issue by zhaoranguang** [Tencent/tdesign-miniprogram#2545]
### tdesign-miniprogram 版本

1.2.5

### 重现步骤

1.点击微信的真机调试

### 期望结果

希望真机和模拟器效果一致

### 实际结果

instantiationDecorator.js:1 For developer:"xxxx" is not an assignable expression. This two-way binding is ignored.

### 补充说明

我不太明白，是我用法不对吗？

**Comment by zhaoranguang** [comment]
不是你们的问题，把app.json中的
 "lazyCodeLoading": "requiredComponents"
 配置删除就行，可以关闭了，谢谢，给你们添麻烦了。

**Comment by hqzh** [comment]
> 不是你们的问题，把app.json中的 "lazyCodeLoading": "requiredComponents" 配置删除就行，可以关闭了，谢谢，给你们添麻烦了。

兄弟你小程序可以？

**Comment by hqzh** [comment]
https://github.com/Tencent/tdesign-miniprogram/issues/2810
