### ISSUE TITLE
[Slider] 希望 Slider 支持 vertical 属性 

### ISSUE THREAD

**Issue by ronger-x** [Tencent/tdesign-miniprogram#2547]
### 这个功能解决了什么问题

实现调音效果或者类似仅支持前后遥控的滑条需要实现垂直属性

### 你建议的方案是什么

有赞 vant-weapp 的[实现方案](https://github.com/youzan/vant-weapp/blob/dev/packages/slider/index.ts#L87C52-L87C52)
## IssueShoot
- 预估时长: 5
- 期望完成时间: 2024-02-06 00:00:00 +0000 UTC
- 开发难度: 高
- 参与人数: 1
- 需求对接人: jeannehuang;anlyyao;jarmywang
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by anlyyao** [comment]
@RADWIMPS426 有空帮忙评估一下，是否需要支持噶🤣～

**Comment by ronger-x** [comment]
希望增加兼容性测试, 目前找的开源实现在安卓端无法同时滑动

iOS 端:

https://github.com/Tencent/tdesign-miniprogram/assets/29698602/94baa9bf-78c2-483b-b862-74e6e5b81c99

安卓端:

https://github.com/Tencent/tdesign-miniprogram/assets/29698602/84148378-68eb-48f9-848c-1becb536b17a

**Comment by RADWIMPS426** [comment]
@Wen1kang
