### ISSUE TITLE
[Fab 悬浮按钮] 可移动悬浮按钮按住拖动后逐渐会偏移触点

### ISSUE THREAD

**Issue by xliez** [Tencent/tdesign-miniprogram#2548]
### tdesign-miniprogram 版本

1.2.6

### 重现链接

组件库官方预览小程序

### 重现步骤

环境：iOS 16.7.2 & 微信8.0.45
步骤：
1. 扫码打开组件库官方预览小程序
2. 预览Fab悬浮按钮，选择可移动悬浮按钮，拖动悬浮按钮上下移动，悬浮按钮会逐渐偏移远离手指触点。

### 期望结果

悬浮按钮跟随触点

### 实际结果

悬浮按钮逐渐偏移触点

**Comment by anlyyao** [comment]
@xliez 感谢反馈🫡，下个版本带上～
