### ISSUE TITLE
[组件名称] 图标全部变成方块了

### ISSUE THREAD

**Issue by liuxing133** [Tencent/tdesign-miniprogram#2557]
### tdesign-miniprogram 版本

2.8.3-1

### 重现步骤

官网demo组件图片都变成小方块了
![image](https://github.com/Tencent/tdesign-miniprogram/assets/117614329/ac1b69ce-0fe1-47c0-b914-90b6439ceab0)

**Comment by anlyyao** [comment]
@liuxing133  😬 wait a moment ....

**Comment by feng520ckx** [comment]
着急 麻烦尽快处理

**Comment by TimLang** [comment]
有没有备份的cdn地址，老版本的，现在这个版本图标完全对不上

**Comment by drowningxj** [comment]
什么情况 icon全对不上了

**Comment by feng520ckx** [comment]
现在这个图标完全不对啊

**Comment by hongkb24** [comment]
线上项目有引用...什么时候修复?

**Comment by feng520ckx** [comment]
麻烦官方给个回复 年终奖要没了

**Comment by 17539351829** [comment]
![image](https://github.com/Tencent/tdesign-miniprogram/assets/68831786/ce7381fa-c605-437d-9691-9abd535c0cd4)
怎么回事 chevron-left 变成了箭头

**Comment by chenhaizano** [comment]
![image](https://github.com/Tencent/tdesign-miniprogram/assets/6965133/97ce653e-bc92-4f8d-937e-b2c669d7bd55)

全乱了，这个问题修复的也太慢了吧？

**Comment by yanzhengui** [comment]
这里也开始摆烂了？

**Comment by uyarn** [comment]
CDN资源出现了异常  目前已恢复

**Comment by hongkb24** [comment]
> CDN资源出现了异常 目前已恢复

旧版本icon怎么替换了...

**Comment by saberrty** [comment]
> CDN资源出现了异常 目前已恢复

并没有，图标都错乱了，请尽快解决

**Comment by liuqingfei946** [comment]
图标全错乱了。。。难受

**Comment by pht1991** [comment]
还没有恢复好，赶紧！！

**Comment by cibaGitHub** [comment]
这个真的很急，线上项目在用

**Comment by DianaYako** [comment]
还没修复好吗

**Comment by anlyyao** [comment]
现在试试，修复了～

**Comment by feng520ckx** [comment]
搞的我不敢用了

**Comment by TimLang** [comment]
修复了？又改坏了，老哥。赶紧修复下。

**Comment by pht1991** [comment]
我这边的已经正常了

**Comment by feng520ckx** [comment]
图标又不对了

**Comment by cibaGitHub** [comment]
> 这个真的很急，线上项目在用

图标好了

**Comment by anlyyao** [comment]
@TimLang  hello，你清缓存重新编译试试，我这边测试零售模版（图标版本0.1.2）和官网示例（图标版本0.2.0）图标都正常了～

**Comment by mo-ocean** [comment]
![image](https://github.com/Tencent/tdesign-miniprogram/assets/38321226/331c1171-fdd2-448c-b268-51bfcceb1842)
没修复好

**Comment by GanChuanYin** [comment]
![image](https://github.com/Tencent/tdesign-miniprogram/assets/54427198/afa4b737-15a1-4561-8f35-23a64ad48ada)

没修复好，版本1.1.10

**Comment by feng520ckx** [comment]
图标版本0.1.4麻烦看一下呢 还是异常的 着急！

**Comment by GanChuanYin** [comment]
> ![image](https://private-user-images.githubusercontent.com/54427198/297302857-afa4b737-15a1-4561-8f35-23a64ad48ada.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NzgyNTEsIm5iZiI6MTcwNTQ3Nzk1MSwicGF0aCI6Ii81NDQyNzE5OC8yOTczMDI4NTctYWZhNGI3MzctMTVhMS00NTYxLThmMzUtMjNhNjRhZDQ4YWRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDA3NTIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiM2RlNGFiNDUwNjA2N2ZjZDc5YmU4NWIwN2E2NGRiYmQ3NTk4NmUyM2FmMDkwOGJiMTMxMzZiYzAxYzM5ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XYRfLBh0wWDswBNeSVSAEHA6Nub1b9BleRAwmE2snWA)
> 
> 没修复好，版本1.1.10

腾讯这么崴了吗？线上公共项目CDN 都维护不好？

**Comment by mo-ocean** [comment]
1.0.0 版本异常

**Comment by anlyyao** [comment]
> 1.0.0 版本异常

组件库1.0.0版本，使用的也是0.1.2版本的图标，组件库1.1.6版本开始使用0.1.4版本图标库，组件库1.2.0版本开始使用0.2.0版本图标

**Comment by Guoliang521** [comment]
现在 向右的箭头变成 圆圈 向左的箭头向右 X 变成 </> 哎 什么时候修复

**Comment by hh778** [comment]
大佬们，请问在哪能配置图标库啊，我这Input设置了clearable,但是点击以后没有图标显示，点击右侧可以清除输入的内容，但是图标出不来

**Comment by feng520ckx** [comment]
> > 1.0.0 版本异常
> 
> 组件库1.0.0版本，使用的也是0.1.2版本的图标，组件库1.1.6版本开始使用0.1.4版本图标库，组件库1.2.0版本开始使用0.2.0版本图标

什么时候能恢复啊？

**Comment by TimLang** [comment]
> @TimLang hello，你清缓存重新编译试试，我这边测试零售模版（图标版本0.1.2）和官网示例（图标版本0.2.0）图标都正常了～

确实有异常啊，返回按钮变右剪头了，x按钮也变了，之前有恢复过，1个多小时前又坏了。。

**Comment by xiaxind1** [comment]
线上项目 正在用啊，图标出问题了，什么时候能解决啊？ 难道真的“减猿增笑”了

**Comment by anlyyao** [comment]
真好了！！！！！！！  朋友们再试试

**Comment by anlyyao** [comment]
> > @TimLang hello，你清缓存重新编译试试，我这边测试零售模版（图标版本0.1.2）和官网示例（图标版本0.2.0）图标都正常了～
> 
> 确实有异常啊，返回按钮变右剪头了，x按钮也变了，之前有恢复过，1个多小时前又坏了。。

0.1.4版本图标库已恢复！！
