### ISSUE TITLE
icon  chevron-left 怎么变成了箭头

### ISSUE THREAD

**Issue by 17539351829** [Tencent/tdesign-miniprogram#2558]
### tdesign-miniprogram 版本

1.1.11

### 重现步骤

![image](https://github.com/Tencent/tdesign-miniprogram/assets/68831786/8ee359cd-be2b-4b3f-a948-54bb50c7780c)

**Comment by uyarn** [comment]
目前已恢复

**Comment by liuqingfei946** [comment]
好多icon都错乱了
