### ISSUE TITLE
ImageViewer 图片预览没有设置宽高限制的情况下，图片被截断了

### ISSUE THREAD

**Issue by lisashare** [Tencent/tdesign-miniprogram#2560]
### tdesign-miniprogram 版本

1.2.6

### 重现步骤

![207363f1-daf1-47cf-ada0-f3ce9775f7f8](https://github.com/Tencent/tdesign-miniprogram/assets/37070480/24e94ba0-b0f8-4cc4-8ad0-3281290afaa9)

### 期望结果

![冬至](https://github.com/Tencent/tdesign-miniprogram/assets/37070480/64f4d657-e2cf-44ca-bcd5-56ae6335814d)

## IssueShoot
- 预估时长: 1
- 期望完成时间: 2024-01-27 00:00:00 +0000 UTC
- 开发难度: 低
- 参与人数: 1
- 需求对接人: jeannehuang;anlyyao;jarmywang
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by jarmywang** [comment]
fixed，下个版本发布
