### ISSUE TITLE
[ SideBar 侧边栏] 锚点用法：按照官网锚点用法，从服务端获取数据后赋值给category，右侧滑动对应左侧菜单不起作用，且报错：TypeError: Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by GentleSevenV** [Tencent/tdesign-miniprogram#2561]
### tdesign-miniprogram 版本

1.2.7

### 重现步骤

从服务端获取category数据后，setData给了data中的category，之后在wxml中进行渲染数据，右侧滑动对应左侧菜单不起作用，且报错：TypeError: Cannot read property 'top' of undefined

### 基础库版本

3.3.1

**Comment by GentleSevenV** [comment]
补充一下：如果category数据不从服务端获取，直接写在data中，则功能正常。

**Comment by betavs** [comment]
https://github.com/Tencent/tdesign-miniprogram/blob/aba300a09ee53901be7757f75cddb61f3aa93965/src/side-bar/_example/base/index.js#L47-L56

当数据为空时，在 `onLoad` 生命周期内不用执行上面代码；等数据回来后执行即可

**Comment by GentleSevenV** [comment]
Got it！感谢！
