### ISSUE TITLE
[t-input] 当type="nickname"表单提交时，不能获取到input的value

### ISSUE THREAD

**Issue by zfw3842415** [Tencent/tdesign-miniprogram#2562]
### tdesign-miniprogram 版本

1.2.6

### 重现步骤
```
<form bindsubmit=“sumbit“>
<t-input type="nickname" name="nickname">
<t-button  type="submit"></t-button>
</form>
```

### 期望结果

表单提交时可以name为nickname的值

### 实际结果

表单获取input的值为空

**Comment by anlyyao** [comment]
@zfw3842415 请确认已经正确获取 nickname 值，我这边测试使用正常。

https://github.com/Tencent/tdesign-miniprogram/assets/51158141/9070423b-f0d6-444f-b294-aec9a75cf3f7

**Comment by zfw3842415** [comment]
在小程序开发工具里面无法获取

**Comment by anlyyao** [comment]
> 在小程序开发工具里面无法获取


<img width="753" alt="截屏2024-02-04 14 37 45" src="https://github.com/Tencent/tdesign-miniprogram/assets/51158141/49663b7e-65f4-4cab-aaf1-b3622c18d9c9">

https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/userProfile.html

**Comment by pansusu** [comment]
> > 在小程序开发工具里面无法获取
> 
> <img alt="截屏2024-02-04 14 37 45" width="753" src="https://private-user-images.githubusercontent.com/51158141/302082414-49663b7e-65f4-4cab-aaf1-b3622c18d9c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODQ0OTksIm5iZiI6MTcxNTY4NDE5OSwicGF0aCI6Ii81MTE1ODE0MS8zMDIwODI0MTQtNDk2NjNiN2UtNjVmNC00Y2FiLWFhZjEtYjM2MjJjMThkOWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDEwNTYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwM2I4OTk4NjVlYzY0NDU5ZGRiYTZjNzkxMTc5NTNjYmU3M2VlNDNjNmYwNGJjYzQ5MmNjOTMzYzg0OTcyY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vCXYFPNr_vC7lGjLzpL0JixtyK6Ha_T_Qs5WJtd57QI">
> https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/userProfile.html

最好要保持统一啊，开发者不会实时来真机模拟的

**Comment by anlyyao** [comment]
> > > 在小程序开发工具里面无法获取
> > 
> > 
> > <img alt="截屏2024-02-04 14 37 45" width="753" src="https://private-user-images.githubusercontent.com/51158141/302082414-49663b7e-65f4-4cab-aaf1-b3622c18d9c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODQ0OTksIm5iZiI6MTcxNTY4NDE5OSwicGF0aCI6Ii81MTE1ODE0MS8zMDIwODI0MTQtNDk2NjNiN2UtNjVmNC00Y2FiLWFhZjEtYjM2MjJjMThkOWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDEwNTYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwM2I4OTk4NjVlYzY0NDU5ZGRiYTZjNzkxMTc5NTNjYmU3M2VlNDNjNmYwNGJjYzQ5MmNjOTMzYzg0OTcyY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vCXYFPNr_vC7lGjLzpL0JixtyK6Ha_T_Qs5WJtd57QI">
> > https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/userProfile.html
> 
> 最好要保持统一啊，开发者不会实时来真机模拟的

TDesign 做不到啊😭。
