### ISSUE TITLE
[dialog] 添加dialog组件之后，在微信编辑器中老有警告信息

### ISSUE THREAD

**Issue by WisdomJie** [Tencent/tdesign-miniprogram#2563]
### tdesign-miniprogram 版本

最新版本也是有问题

### 重现链接

<t-dialog visible="{{isDialog}}" title="{{dialogTitle}}" content="{{dialogContent}}" confirm-btn="查看" cancel-btn="取消" bind:confirm="dialogConfirmAction">     <t-image slot="middle" src="{{dialogImg}}" /> </t-dialog>

### 重现步骤

添加dialog组件之后，微信编辑器有警告信息
[Component] slot "content" is not found (for component "miniprogram_npm/tdesign-miniprogram/popup/popup").
[Component] property "tId" of "miniprogram_npm/tdesign-miniprogram/button/button" received type-uncompatible value: expected <String> but get null value. Use empty string instead.

### 期望结果

希望不要有警告信息。

### 实际结果

添加dialog组件之后，微信编辑器有警告信息
[Component] slot "content" is not found (for component "miniprogram_npm/tdesign-miniprogram/popup/popup").
[Component] property "tId" of "miniprogram_npm/tdesign-miniprogram/button/button" received type-uncompatible value: expected <String> but get null value. Use empty string instead.

### 基础库版本

1.2.6

### 补充说明

<t-dialog visible="{{isDialog}}" title="{{dialogTitle}}" content="{{dialogContent}}" confirm-btn="查看" cancel-btn="取消" bind:confirm="dialogConfirmAction">
    <t-image slot="middle" src="{{dialogImg}}" />
</t-dialog>

**Comment by houyi** [comment]
import Dialog from '@/wxcomponents/tdesgin/dialog/index'  

vue3 + ts   中怎么 拿到  Dialog.confirm(） 小程序 提示 找不到 confirm   官网文档 没有 Vu3 ts demo,.  真的 不行啊

**Comment by anlyyao** [comment]
> import Dialog from '@/wxcomponents/tdesgin/dialog/index'
> 
> vue3 + ts 中怎么 拿到 Dialog.confirm(） 小程序 提示 找不到 confirm 官网文档 没有 Vu3 ts demo,. 真的 不行啊

不确定你这边使用的是哪一个框架，但 tdesign-miniprogram 是一个基于原生开发的 UI 组件库，未适配uniapp、taro等不能保证组件库在以上环境中使用的可行性

**Comment by houyi** [comment]
用的 uniapp vue3+ts

**Comment by houyi** [comment]
uni.showToast({ icon: 'error', title: '请填写完整信息' })    这是官方的 组件   咱们这 没有这种吗？
