### ISSUE TITLE
[NoticeBar] bind:click没有获取当前的content

### ISSUE THREAD

**Issue by Nathanielna** [Tencent/tdesign-miniprogram#2566]
### tdesign-miniprogram 版本

1.2.3

### 重现链接
`<t-notice-bar
            visible="{{true}}"
            direction="vertical"
            interval="{{3000}}"
            suffixIcon="chevron-right"
            content="{{marketlisttitle}}"
            prefixIcon="sound"
            bind:click="clicknotice"
            t-class="external-class"
            t-class-prefix-icon="external-class-prefix-icon"
          ></t-notice-bar>`

`  clicknotice(e){
   console.log(e)
  },`

### 期望结果

获取我点击时的content

### 实际结果

![image](https://github.com/Tencent/tdesign-miniprogram/assets/47273938/5eb80e69-6af6-4c86-9851-efb9db204a4d)

**Comment by betavs** [comment]
```html
<t-notice-bar
  visible="{{true}}"
  direction="vertical"
  interval="{{3000}}"
  suffixIcon="chevron-right"
  content="{{marketlisttitle}}"
  data-content="{{marketlisttitle}}"
  prefixIcon="sound"
  bind:click="clicknotice"
  t-class="external-class"
  t-class-prefix-icon="external-class-prefix-icon"
/>
```

```typescript
clicknotice(e) {
  const { content } = e.currentTarget.dataset;
  console.log(content);
},
```

通过 `dataset` 来获取即可
