### ISSUE TITLE
[t-search] 属性left-icon和默认'search'冲突

### ISSUE THREAD

**Issue by eMonkHy** [Tencent/tdesign-miniprogram#2568]
### tdesign-miniprogram 版本

^1.2.6

### 重现步骤

` <t-search model:value="{{search}}" placeholder="搜索">
          <t-icon slot="left-icon" size="18" name="search"></t-icon>
        </t-search>`

![a720f31f5ae891e5a95fbcde4b4467c](https://github.com/Tencent/tdesign-miniprogram/assets/50975886/3ddcdda2-3b2d-401b-98bc-0e9cd4cc76d9)

**Comment by tankle0** [comment]
@betavs @jarmywang 这个问题在1.4.4怎么又出现了，使用自定义图片不生效 <t-image class="searchIcon" slot="left-icon" src="/static/icons/search.png" mode="heightFix" width="48rpx" height="48rpx" />

**Comment by betavs** [comment]
@tankle0 由于 `leftIcon` 默认值为 `search` 导致，如果需要自定义 `left-icon` 需要设置 `leftIcon="{{null}}"`

**Comment by tankle0** [comment]
> @tankle0 由于 `leftIcon` 默认值为 `search` 导致，如果需要自定义 `left-icon` 需要设置 `leftIcon="{{null}}"`

好的
