### ISSUE TITLE
【t-button】新手求教，按钮样式无效？

### ISSUE THREAD

**Issue by hanxiaofeng** [Tencent/tdesign-miniprogram#2572]
### tdesign-miniprogram 版本

1.2.7

### 重现步骤

<img width="1341" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/10582931/4704003f-7fed-4faf-a0b3-7749a4d33a3d">

### 期望结果

样式正常

### 实际结果

不正常

### 基础库版本

1.2.7

**Comment by betavs** [comment]
[Docs](https://tdesign.tencent.com/miniprogram/getting-started)

将 `app.json` 中的 `"style": "v2"` 移除。

> 因为 [该配置](https://developers.weixin.qq.com/miniprogram/dev/reference/configuration/app.html#style) 表示启用新版组件样式，将会导致 TDesign 的组件样式错乱。

**Comment by betavs** [comment]
有在 `json` 文件引入 `button` 组件吗 🤔
```json
  "usingComponents": {
    "t-button": "tdesign-miniprogram/button/button",
  },
```

**Comment by betavs** [comment]
方便把项目提交到GitHub吗 🤔
