### ISSUE TITLE
[Icon] 参照官网(tdesign.tencent.com)使用book图标，无法在开发环境下显示出来

### ISSUE THREAD

**Issue by kongdf123** [Tencent/tdesign-miniprogram#2573]
### tdesign-miniprogram 版本

"libVersion": "2.23.1"

### 重现步骤

引用：
  "dependencies": {
    "dayjs": "^1.9.3",
    "tdesign-miniprogram": "^1.2.7",
    "tslib": "^1.11.1"
  },

使用：
<t-icon name="book" data-name="book" size="48rpx" />

### 期望结果

希望官网上的icon都可以在本地项目上正常显示出来

### 实际结果

有的显示有的不显示

**Comment by anlyyao** [comment]
@kongdf123 贴一下你的实际代码片段

**Comment by anlyyao** [comment]
> @kongdf123 贴一下你的实际代码片段

我这边使用正常，[代码片段](https://developers.weixin.qq.com/s/yJfw5smJ71Oa)
<img width="345" alt="截屏2024-01-24 11 06 38" src="https://github.com/Tencent/tdesign-miniprogram/assets/51158141/42da33d7-9f14-4f36-8c77-ff38ce14763c">

**Comment by kongdf123** [comment]
> @kongdf123 贴一下你的实际代码片段

谢谢，已经解决，文件夹结构问题，重新调整就好了。
