### ISSUE TITLE
希望为 TDesign 微信小程序组件库提供原生深色模式适配

### ISSUE THREAD

**Issue by Songyon** [Tencent/tdesign-miniprogram#2576]
### 这个功能解决了什么问题

希望为 TDesign 微信小程序组件库提供原生深色模式适配，而非使开发者通过自定义 CSS 配色实现手动深色模式适配。

### 你建议的方案是什么

微信小程序支持识别深色模式并应用相应主题，但需要提供相应深色配置。
## IssueShoot
- 预估时长: 20
- 期望完成时间: 2024-03-30 00:00:00 +0000 UTC
- 开发难度: 高
- 参与人数: 1
- 需求对接人: jeannehuang;anlyyao;jarmywang
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by Nero978** [comment]
确实很需要，好像 TDesign web 版本是有的，小程序啥时候能跟进一下

**Comment by anlyyao** [comment]
> 确实很需要，好像 TDesign web 版本是有的，小程序啥时候能跟进一下

正在支持中，预计3月中

**Comment by Songyon** [comment]
麻烦更新一下官网文档告知一下使用方式哦，更新 TD npm 版本后并不是自动生效。
