### ISSUE TITLE
[PullDownRefresh] 可视内容高度为固定时，滚动里边内容，现在设置scrollTop属性值为0，里边内容并没有回到最顶端显示

### ISSUE THREAD

**Issue by 315574925** [Tencent/tdesign-miniprogram#2579]
### tdesign-miniprogram 版本

v1.2.6

### 重现步骤

可视内容高度为固定时，滚动里边内容，现在设置scrollTop属性值为0，里边内容并没有回到最顶端显示

### 期望结果

应该重置到初始状态，因为比如现在滚动到列表中间，现在我从新搜索列表，搜索到的结果再列表时，应该从最顶部内容开始浏览

### 实际结果

可视内容高度为固定时，滚动里边内容，现在设置scrollTop属性值为0，里边内容并没有回到最顶端显示

**Comment by lisashare** [comment]
我也有需要回到顶部的需求，数据刷新了，列表没有回到顶部，

**Comment by lisashare** [comment]
源码中已经有回到顶部的scrollToTop函数了。修改源码，在传递组件value值的时候，值为true就设置scrollToTop()函数就好了，希望下个版本能更新或者暴露api

**Comment by 315574925** [comment]
> scrollToTop
@lisashare 
可以贴下代码不呢？好像22年就有人提过这个需求

**Comment by lisashare** [comment]
这种修改方式更改了源码，我是不想重写功能了，每次构建npm需要手动添加，坐等官方组件更新吧~
\miniprogram\miniprogram_npm\tdesign-miniprogram\pull-down-refresh\pull-down-refresh.js
this.observers = {
  value(val) {
    if (!val) {
      clearTimeout(this.maxRefreshAnimateTimeFlag);
      if (this.data.refreshStatus > 0) {
        this.setData({
          refreshStatus: 3,
        });
      }
      this.setData({ barHeight: 0 });
    }
    else {
      this.doRefresh();
     // todo
      this.scrollToTop() // 这里添加回到顶部函数（实际这个js methods中已经提供了回到顶部的方法了）
    }
  }
};

**Comment by 315574925** [comment]
> scrollToTop
@lisashare 
我看了下确实是有对应方法 建议直接获取实例调用，不要去修改他源码
this.selectComponent('.list-refresh').scrollToTop();
.list-refresh：PullDownRefresh组件的class
![image](https://github.com/Tencent/tdesign-miniprogram/assets/34641313/11b1f318-bbc9-48aa-aab0-87cf90c2719f)

**Comment by lisashare** [comment]
我试了获取 .t-pull-down-refresh  t-class="list-refresh" 这两种类名，都获取不到，原来是直接写class类名生效了，感谢，可以用

**Comment by anlyyao** [comment]
Duplicate #715
