### ISSUE TITLE
[Empty 空状态] 没有合适的图标图片表示列表为空

### ISSUE THREAD

**Issue by Zoeking5113** [Tencent/tdesign-miniprogram#2581]
### 这个功能解决了什么问题

列表为空时，有快速的表达列表为空的默认状态

### 你建议的方案是什么

icon里加一个列表空的图标或者 empty出个默认列表空的样式

**Comment by jarmywang** [comment]
error-circle、demo图放自己cdn、根据产品风格请设计师出一张图
