### ISSUE TITLE
[t-image] mode="aspectFit" 图片 radius 两侧不一致

### ISSUE THREAD

**Issue by yahuian** [Tencent/tdesign-miniprogram#2582]
### tdesign-miniprogram 版本

1.2.7

## 正常情况下圆角：

![image](https://github.com/Tencent/tdesign-miniprogram/assets/39142491/dab50e0e-7d36-4861-affd-8116a2547fa6)

![image](https://github.com/Tencent/tdesign-miniprogram/assets/39142491/c1b12f19-a5c3-4929-9084-a95660b663f9)

## mode="aspectFit" 圆角两侧不一致

![image](https://github.com/Tencent/tdesign-miniprogram/assets/39142491/72901563-e50d-434a-a03d-5c3010c0a359)

## 其他
scaleToFill/aspectFit/aspectFill/widthFix/heightFix/top/bottom/center/left/right/top left/top right/bottom left/bottom right
上述 mode 全部测试完，只有 aspectFit 有问题

### 基础库版本

3.1.1

**Comment by jarmywang** [comment]
请问方便发原图地址吗？或者请提供尺寸

**Comment by yahuian** [comment]
![海](https://github.com/Tencent/tdesign-miniprogram/assets/39142491/f6921098-2a44-4828-8335-07349d084f08)

@jarmywang 这是原图，不过其他图片应该也能复现该问题

**Comment by anlyyao** [comment]
@yahuian 看一下 aspectFit 缩放模式的规则，应该是图片宽高比和容器宽高比不匹配的问题，目前并没有好的解决方案，如果你图片包含 宽>高、宽<高 等情况，还是建议图片拉伸。
<img width="651" alt="截屏2024-02-04 11 31 07" src="https://github.com/Tencent/tdesign-miniprogram/assets/51158141/bd956109-712b-4018-97ca-f6cfc724528c">

**Comment by yahuian** [comment]
@anlyyao 非常感谢，我明白了。因为 aspectFit 不能保证图片会占满整个容器（只能保证长边完全占满容器），所以可能出现 radius 两侧不一致问题。而其他的 mode 都可以保证图片会充满整个容器，所以没问题。

![image](https://github.com/Tencent/tdesign-miniprogram/assets/39142491/7e8b1e96-2619-43a4-95a3-6a32b299b90f)
