### ISSUE TITLE
[Dialog]小程序端； vue3 + ts 中怎么 拿到 Dialog.confirm(） 小程序 提示 找不到 confirm

### ISSUE THREAD

**Issue by houyi** [Tencent/tdesign-miniprogram#2584]
### tdesign-miniprogram 版本

小程序端； vue3 + ts 中怎么 拿到 Dialog.confirm(） 小程序 提示 找不到 confirm  这个方法  应该是没以后实例化 这个对象 Dialog

TypeError: Cannot read property 'confirm  ' of undefined

### 重现步骤

import Dialog from '@/wxcomponents/tdesgin/dialog/index'

小程序端；
vue3 + ts 中怎么 拿到 Dialog.confirm(） 小程序 提示 找不到 confirm 官网文档 没有 Vu3 ts demo,. 真的 不行啊

setup  语法糖中  没有 this,   context    我该怎么写呢？

**Comment by anlyyao** [comment]
@houyi  tdesign-miniprogram 是基于原生小程序开发的组件，没有针对 uni-app、taro等 进行适配，不能保证组件在uni-app、taro等的可用性。目前，暂无适配计划。

**Comment by houyi** [comment]
e,,  建议适配啊 。 官方的 uni-ui  组件 可以参考下，都有 直接实例调用，也方便，就是 uni-ui太丑~~
