### ISSUE TITLE
在微信小程序的TS基础模板中引入组件库出错

### ISSUE THREAD

**Issue by ljbf-dao** [Tencent/tdesign-miniprogram#2591]
### tdesign-miniprogram 版本

1.2.7

### 重现步骤

使用的是微信开发者工具的TS-基础模板
![微信截图_20240205164658](https://github.com/Tencent/tdesign-miniprogram/assets/88640150/61911e41-2509-4327-a620-dd0305108e8f)
npm安装，构建都很顺利，也在tsconfig.json中指定了paths，但是在JSON 文件中引入组件就会报错，
错误信息：
![微信截图_20240205165414](https://github.com/Tencent/tdesign-miniprogram/assets/88640150/20e50bb8-4f21-4563-ad33-285675ba0b3c)

### 期望结果

在TS模板中能正确引入组件

### 实际结果

控制台报错，并且没有正确显示组件

**Comment by anlyyao** [comment]
有勾选"将JS编译成ES5"吗？

**Comment by ljbf-dao** [comment]
> 有勾选“将JS编译成ES5”吗？

哇！勾选了就可以了…………感谢大佬~
