### ISSUE TITLE
[Swiper] 轮播图意外的高频左右抖动

### ISSUE THREAD

**Issue by Nero978** [Tencent/tdesign-miniprogram#2602]
### tdesign-miniprogram 版本

 1.2.8

### 重现步骤

https://github.com/Tencent/tdesign-miniprogram/assets/63546553/9a44dcc9-d4ad-4b6b-8760-b7af4afe08e2

自动播放的轮播图组件在真机上（iPhone14Pro/iPhone13Pro）没有任何操作左右高频抖动
复现步骤：
- 打开带有轮播的页面
- 前往其他页面或退出小程序使其进入后台（轮播页面未销毁）
- 几分钟后再次回到轮播页面就会出现抖动

### 期望结果

轮播正常播放

### 基础库版本

3.3.4

### 补充说明

另外 官网的轮播组件也会出现这个问题
https://tdesign.tencent.com/miniprogram/components/swiper

开发者工具上的预览还没有遇到过这种情况

我还发现了之前就有这个issue了（已被修复）：https://github.com/Tencent/tdesign-miniprogram/issues/1391

https://github.com/Tencent/tdesign-miniprogram/assets/63546553/7d23dc57-90f1-4e83-b8c4-5d102a488c83

**Comment by Nero978** [comment]
想问一下这个bug什么时候pr呢？影响线上版本了

**Comment by jarmywang** [comment]
> 想问一下这个bug什么时候pr呢？影响线上版本了

抱歉，我们尽快处理，最快本周，最晚下周

**Comment by Nero978** [comment]
> > > 想问一下这个bug什么时候pr呢？影响线上版本了
> > 
> > 
> > 抱歉，我们尽快处理，最快本周，最晚下周
> 
> 进度咋样了，我也遇到了

已经修复了，TDesign 更新到 `1.2.9` 就可以了。

**Comment by Max0897** [comment]
> > > > 想问一下这个bug什么时候pr呢？影响线上版本了
> > > 
> > > 
> > > 抱歉，我们尽快处理，最快本周，最晚下周
> > 
> > 
> > 进度咋样了，我也遇到了
> 
> 已经修复了，TDesign 更新到 `1.2.9` 就可以了。
已经更新到1.2.9了，还是存在一样的问题

**Comment by sentangle** [comment]
1.2.9 问题同样出现
ios12

**Comment by Nero978** [comment]
> 1.2.9 问题同样出现 ios12

1.3.0 没有再发现这个问题 iOS17
