### ISSUE TITLE
微信小程序ts 版本, 引入组件报错,无法找到该组件,步骤全部安装官网走

### ISSUE THREAD

**Issue by jstbibo** [Tencent/tdesign-miniprogram#2605]
### tdesign-miniprogram 版本

1.2.8

**Comment by anlyyao** [comment]
@jstbibo 检查一下是否勾选了 “将JS编译成ES5“，如勾选了仍有错，贴一下报错截图～

**Comment by MmToon** [comment]
我也遇到过，如果首次在pages下的子文件夹下的xxx.json文件里配置就不行，
要同时在app.json下全局配置就好了，编译生效后只要保留xxx.json文件的配置，可以再删除app.json的全局配置。

**Comment by anlyyao** [comment]
> 我也遇到过，如果首次在pages下的子文件夹下的xxx.json文件里配置就不行， 要同时在app.json下全局配置就好了，编译生效后只要保留xxx.json文件的配置，可以再删除app.json的全局配置。

我这边基于开发者工具提供的“TS-基础模版”，然后引入tdesign-miniprogram能正常编译和使用。 可以展开说一下你的app.json和xxx.json的具体配置内容～

**Comment by anlyyao** [comment]
> @anlyyao 我这边基于开发者工具提供的“JS-基础模版” 在某个页面引入任何组件之前要先在app.json的usingComponents下全局引入， 否则初次在pages下的子文件夹下的xxx.json的usingComponents下引入无效。 系统windows10，微信开发者工具1.06.2401192 win32-x64

听上去有点像“按需注入”无效🤔， 我这边在重复验证一下，但目前我只有MacOS不能排除是否和系统有关～

**Comment by MmToon** [comment]
@anlyyao 是的，那我等你消息。

**Comment by xiaoyang5116** [comment]
> @jstbibo检查一下是否勾选了“将JS编译成ES5”，如勾选了错误，贴一下报错截图～

勾选了“将JS编译成ES5” 之后成功了，是否在官方文档中提示下呢🤔，困扰了我一个小时😣

**Comment by GiantappMan** [comment]
```
npm i tdesign-miniprogram -S --production
```
ts 基础模板，安装后点构建直接报错

**Comment by GiantappMan** [comment]
离谱啊，开发体感也太不好了

https://developers.weixin.qq.com/community/develop/doc/0004466081c3c034c80ec59745bc00?highLine=%2520NPM%2520packages%2520not%2520found.%2520Please%2520confirm%2520npm%2520packages%2520which%2520need%2520to%2520build%2520are%2520belong%2520to%2520%2560miniprogramRoot%2560%2520directory.%2520Or%2520you%2520may%2520edit%2520project.config.json%27s%2520%2560packNpmManually%2560%2520and%2520%2560packNpmRelationList%2560&page=2#comment-list

**Comment by GiantappMan** [comment]
[miniprogram-2.zip](https://github.com/Tencent/tdesign-miniprogram/files/14967681/miniprogram-2.zip)

![image](https://github.com/Tencent/tdesign-miniprogram/assets/80653/286bd9c0-c923-4110-9680-f8d5292bf786)

https://tdesign.tencent.com/miniprogram/getting-started

ts基础模板

**Comment by GiantappMan** [comment]
> @jstbibo 检查一下是否勾选了 “将JS编译成ES5“，如勾选了仍有错，贴一下报错截图～

源码贴上来，能不能帮忙看下

**Comment by GiantappMan** [comment]
转taro了，稳得一批

**Comment by anlyyao** [comment]
@GiantappMan 刚看到你的comment😅，来的有点晚，但处理方式如下截图所示。 建议加一下我们的用户群 ～
<img width="1224" alt="企业微信截图_3abc8fa2-86ff-4494-a641-b1d9d9fa2739" src="https://github.com/Tencent/tdesign-miniprogram/assets/51158141/c6a1c10b-9da8-4c0b-870d-68673b04d464">

**Comment by anlyyao** [comment]
> > @jstbibo检查一下是否勾选了“将JS编译成ES5”，如勾选了错误，贴一下报错截图～
> 
> 勾选了“将JS编译成ES5” 之后成功了，是否在官方文档中提示下呢🤔，困扰了我一个小时😣

官网已加入相关提示～
