### ISSUE TITLE
[count-down] 新增时间格式: HH:mm:ss/HH:mm - 支持将天数转换成小时后加到HH位上(days *24 + hours:minutes:seconds) 

### ISSUE THREAD

**Issue by zengyingbyte** [Tencent/tdesign-miniprogram#2608]
### 这个功能解决了什么问题

当前倒计时仅支持DD:HH:mm:ss:SSS/HH:mm:ss:SSS(仅展示当前小时)，在某些需求中需要展示HH:mm:ss/HH:mm并希望把天数转换成小时后加到HH位上(days *24 + hours:minutes:seconds),望官方支持。
示例如下图:
![image](https://github.com/Tencent/tdesign-miniprogram/assets/136805586/d17bbd82-d98e-4d0b-a299-a7f9ec461ee6)
![image](https://github.com/Tencent/tdesign-miniprogram/assets/136805586/4c1677dd-f228-4151-8551-cfcff737a0cf)
![image](https://github.com/Tencent/tdesign-miniprogram/assets/136805586/b9a30034-4181-4c6f-9ad1-c8fc3c1c9af9)

### 你建议的方案是什么

源码文件:count-down.js
函数: updateTime()
![image](https://github.com/Tencent/tdesign-miniprogram/assets/136805586/93f8d8df-ef45-4a62-b5fd-2ca77c4245a4)
根据format字符串判断采取parseDHMSTimeData还是parseHMSTimeData时间转换函数。

// 时间戳转换天时分秒
export const parseDHMSTimeData = function(time) {
	const days = Math.floor(time / DAY);
	const hours = Math.floor((time % DAY) / HOUR);
	const minutes = Math.floor((time % HOUR) / MINUTE);
	const seconds = Math.floor((time % MINUTE) / SECOND);
	const milliseconds = Math.floor(time % SECOND);
	return {
		DD: days,
		HH: hours,
		mm: minutes,
		ss: seconds,
		SSS: milliseconds,
	};
};

// 时间戳转换时分秒
export const parseHMSTimeData = function(time) {
	const days = Math.floor(time / DAY);
	const hours = Math.floor((time % DAY) / HOUR);
	const minutes = Math.floor((time % HOUR) / MINUTE);
	const seconds = Math.floor((time % MINUTE) / SECOND);
	const milliseconds = Math.floor(time % SECOND);
	return {
		// 添加天数的小时数入小时单位值中
		HH: days > 0 ? days * 24 + hours : hours,
		mm: minutes,
		ss: seconds,
		SSS: milliseconds,
	};
};

**Comment by jarmywang** [comment]
该方案不具备通用性，暂不考虑，你可以不加小时及天数部分，然后自己计算小时后拼接到ui
