### ISSUE TITLE
[button] 0.5 版本与 0.6 版本样式差异太大

### ISSUE THREAD

**Issue by CrossLee** [Tencent/tdesign-miniprogram#261]
### tdesign-miniprogram 版本

0.6.2

### 重现链接

https://codepen.io/huxiweng/pen/LYeEyZr

### 重现步骤

下载 0.6.2 版本，引入小程序，直接使用组件。

### 期望结果

样式和官网一致

### 实际结果

样式偏差很大，而且和0.5.2版本的样式差异很大。

### 补充说明

0.6.2：
<img width="1454" alt="image" src="https://user-images.githubusercontent.com/4584905/158174165-13804cfe-e20b-45eb-8be1-7e54d883f903.png">

0.5.2：
<img width="1499" alt="image" src="https://user-images.githubusercontent.com/4584905/158174457-36ed050f-6686-4cc7-9a61-7bcc71eeac8d.png">

官网：
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/4584905/158174234-bdabaa54-e06d-4370-819a-e51689641ad2.png">

**Comment by anlyyao** [comment]
1. icon和文本没有给默认空隙。关于icon和文本之间的距离，三种实现方式。(a.外部样式t-class-icon，给icon右边margin；b.使用slot插槽；c.使用props.content方式添加文本)
2. block为true时，宽度是100%撑满父容器
3. size的3个尺寸区别在于，button高度、水平padding、垂直padding以及文本font-size。

**Comment by CrossLee** [comment]
> 1. icon和文本没有给默认空隙。关于icon和文本之间的距离，三种实现方式。(a.外部样式t-class-icon，给icon右边margin；b.使用slot插槽；c.使用props.content方式添加文本)
> 2. block为true时，宽度是100%撑满父容器
> 3. size的3个尺寸区别在于，button高度、水平padding、垂直padding以及文本font-size。

1、这个不是框架应该给个默认的吗？0.5.2 版本那个默认样式就很合适。况且基本所有前端框架都有个默认样式很标准（看起来很美观），而不是给方案给开发者啊。要是默认样式还需要开发者去调整，这样用框架的意义在哪？好比 Element-UI 的 <el-button> 默认都是一个很好的样式。
`<el-button type="primary" icon="el-icon-search">搜索</el-button>`
<img width="949" alt="image" src="https://user-images.githubusercontent.com/4584905/158182010-1e8e9667-d823-47a8-a2f1-74a08d086b9e.png">

2、再退一步讲，版本更新肯定要兼容原有的，0.5.2 版本的样式基本和官网文档上的是一致的，升级到 0.6.2 结果小程序所有按钮样式全变了。

3、这是没错，你看上面图片 0.6.2 的，3个按钮的差距？「几乎」就是大了一点点。你们回退到 0.5.2 去测试一下，large/medium/small 的按钮大小差距。

**Comment by CrossLee** [comment]
<img width="1342" alt="image" src="https://user-images.githubusercontent.com/4584905/158183576-617d5d95-c90b-4516-b318-a5a34dbfe77a.png">
这是 0.5.2 版本按钮分别为 large / medium / small 的差距。

这是 0.6.2 版本按钮分别为 large / medium / small 的差距。
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/4584905/158183761-62c8b99b-7805-42b2-84ff-34304e92a4d2.png">
