### ISSUE TITLE
[Tabs 选项卡] Tabs 选项卡无法通过上一级传递的参数来控制tab的当前项

### ISSUE THREAD

**Issue by lingfeng-999** [Tencent/tdesign-miniprogram#2612]
### tdesign-miniprogram 版本

1.2.8

### 重现步骤

在小程序的Tabs组件中，无法通过设置上一级页面传递过来的参数来控制当前激活的选项卡值
如图1，我通过navigateTo跳转到tabs组件所在的页面，并传递了一个参数 index 用于标识当前选项应该是哪个值
![QQ截图20240229105658](https://github.com/Tencent/tdesign-miniprogram/assets/86672659/c4be35e2-0291-45c7-97ca-4e5bec9a2842)
如图2，tabs组件所在的页面在onLoad中接收上一级页面传递的参数，其中的currentIndex为标识的当前选项值，可是并没有起作用，在页面上仍然是在 data {} 中定义的当前选项值
![QQ截图20240229110126](https://github.com/Tencent/tdesign-miniprogram/assets/86672659/db41d6b3-5bdb-404d-9bee-39768013e51f)
![QQ截图20240229110215](https://github.com/Tencent/tdesign-miniprogram/assets/86672659/b39ca0f9-820f-48a0-a0ba-c87896353c21)

### 期望结果

能够通过上一级页面传递的参数来控制tab的当前项

### 基础库版本

2.25.3

**Comment by betavs** [comment]
https://github.com/Tencent/tdesign-miniprogram/blob/d49f305a717e3916da32d0cf5d121d9e932eb548/src/tabs/README.md?plain=1#L124

**Comment by myfmwei** [comment]
遇到了同样的问题，如果设置value可以实现控制tab当前页，但是设置这个属性后tab就无法再进行手动切换了

**Comment by betavs** [comment]
@myfmwei 可以监听事件来更新 `value` 值来控制

https://github.com/Tencent/tdesign-miniprogram/blob/d49f305a717e3916da32d0cf5d121d9e932eb548/src/tabs/README.md?plain=1#L132
