### ISSUE TITLE
[icon] icon 怎么按需加载

### ISSUE THREAD

**Issue by boringplay** [Tencent/tdesign-miniprogram#2618]
### 这个功能解决了什么问题

减小 icon 的体积

### 你建议的方案是什么

提供按需加载 icon 的方案

**Comment by boringplay** [comment]
使用 icon 组件后需要加载 icon 字体，icon 字体的体积有点大

**Comment by anlyyao** [comment]
@boringplay  小程序是iconfont方案，没有按需加载的解法😅😐😔
