### ISSUE TITLE
[Cell 单元格]--td-cell-group-title-font-size 不生效

### ISSUE THREAD

**Issue by fangkun1990** [Tencent/tdesign-miniprogram#2623]
### tdesign-miniprogram 版本

"^1.2.8"

### 重现步骤

.custom-cell-class {
  --td-cell-height: 90rpx;  这里生效
  --td-cell-group-title-font-size:20rpx  这里不生效
}
        <t-cell class="custom-cell-class" title="{{item.enterprise_name}}" hover arrow />

### 期望结果

期望生效

### 基础库版本

3.1.5

**Comment by fangkun1990** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我暂时无法亲自回复您的邮件。我会尽快和您取得联系。

**Comment by anlyyao** [comment]
@fangkun1990 `--td-cell-group-title-font-size` 要放在 cell-group 包裹的节点或者在外层节点上，它影响的是cell-group的title
```html
<t-cell-group theme="card" title="组标题测试" class="test">
  <t-cell title="单行标题" leftIcon="service" hover arrow />
  <t-cell title="单行标题" leftIcon="internet" hover arrow />
  <t-cell title="单行标题" leftIcon="lock-on" hover arrow />
</t-cell-group>
```
```css
.test {
  --td-cell-group-title-font-size: 60rpx;
}

```
