### ISSUE TITLE
steps 组件 构建出来的包 样式文件存在冗余

### ISSUE THREAD

**Issue by wutianSweet** [Tencent/tdesign-miniprogram#263]
### tdesign-miniprogram 版本

0.5.3

### 重现步骤

本地安装 td 小程序包  在 node_modules 中查看文件

相同的样式文件打包了三次，影响了包的体积

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/11713735/158540313-03cced20-8340-4431-aba7-e3c7fef125a4.png">

**Comment by wutianSweet** [comment]
switch、 tag 也有相同的问题  建议 用小程序开发者工具依赖图谱检查下小程序的无用文件

**Comment by LeeJim** [comment]
确实有问题。我来跟进一下
