### ISSUE TITLE
[tabs] defaultValue为0时，底部激活线条位置不正确

### ISSUE THREAD

**Issue by KaleidosChen** [Tencent/tdesign-miniprogram#2637]
### tdesign-miniprogram 版本

1.1.15

### 重现步骤

 defaultValue为0时，底部激活线条位置不正确

### 期望结果

 defaultValue为0时，底部激活线条位置应该在第一个选项的正下方

### 实际结果

底部激活线条位置在第一个选项的view的左下角

**Comment by catiwang** [comment]
目前在模拟器无法复现，方便提供一下测试代码吗？

**Comment by KaleidosChen** [comment]
> 目前在模拟器无法复现，方便提供一下测试代码吗？

是错误的使用了hidden导致底部激活线条位置不能正常的发生偏移。
问题解决了。
