### ISSUE TITLE
[t-image] 小程序版 t-image 无法设置 id

### ISSUE THREAD

**Issue by FlyAndNotDown** [Tencent/tdesign-miniprogram#2638]
### tdesign-miniprogram 版本

1.2.8

### 重现步骤

t-image 无法指定 id，无论怎么指定都是 "image"，看了下 tdegisn 的实现应该是直接写死了：

![image](https://github.com/Tencent/tdesign-miniprogram/assets/24787888/23152713-7c0f-485e-b39e-39c6dec789fd)

### 期望结果

id 可以指定

### 实际结果

id 无法指定

### 基础库版本

3.3.4

**Comment by catiwang** [comment]
@anlyyao 评估一下是否需要支持噶？

**Comment by betavs** [comment]
> 可以新增 `tId` 属性

@anlyyao 不知是否需要支持呢 🤔
