### ISSUE TITLE
[swiper] 延迟设置图片地址时，显示不正常

### ISSUE THREAD

**Issue by boyxu** [Tencent/tdesign-miniprogram#264]
### 重现链接
https://github.com/boyxu/boyxu.github.io/blob/master/assets/images/tdesign-issue-20220317.mov

### 重现步骤
TDesign demo 中，将swiper demo中，js文件data中的items数据，更改为在onLoad中延迟3秒执行setData，问题出现

### 期望结果
问题出现

### 实际结果
问题出现

| Environment | Info |
|---|---|
| 相关版本 | 0.6.2 |
| 框架版本 / 基础库版本 | 小程序(v2.11.22) |
| 系统、浏览器 | 微信 |
| Node版本 |  |

**Comment by esky** [comment]
@boyxu 
目前未响应items的变更，会在后续补丁修复。
您可以在获取到items后再渲染swiper。`<swiper wx:if="{{items&&items.length}}">`

**Comment by esky** [comment]
#305
