### ISSUE TITLE
[t-tab-bar] 支持置顶 类似position :" top"

### ISSUE THREAD

**Issue by xiaoyc** [Tencent/tdesign-miniprogram#2644]
### 这个功能解决了什么问题

design 要求 t-tabbar可以置顶显示，目前官方文档没有找到设置 position top的参数 

### 你建议的方案是什么

可以支持置顶 类似position :" top" ，或者现在是不是支持，如何设置，非常感谢。

**Comment by catiwang** [comment]
@anlyyao 评估一下是否需要支持～

**Comment by betavs** [comment]
> 新增 `placement` 属性，可选 `top | bottom` ， 默认 `bottom`

@anlyyao 是否可行呢 🤔

**Comment by jin0209** [comment]
.t-tab-bar {
    position: fixed;
    padding-bottom: 0 !important;
    top: 0 !important;
    bottom: inherit !important;
}

**Comment by jin0209** [comment]
可在页面覆盖t-tab-bar的样式，实现放在任意位置
