### ISSUE TITLE
t-pull-down-refresh 拓展 scroll-view 滚动开始及暂停事件

### ISSUE THREAD

**Issue by lisashare** [Tencent/tdesign-miniprogram#2648]
### 这个功能解决了什么问题

列表滚动开始，导航隐藏，滚动暂停，导航显示的需求

### 你建议的方案是什么

拓展 scroll-view 滚动开始及暂停事件

**Comment by lisashare** [comment]
@betavs 能给<t-pull-down-refresh></t-pull-down-refresh>组件添加一个插槽吗？这个是我的需求，顶部的头像跟随列表内容滚动，下拉刷新在头像下面进行刷新，头像固定不懂。看视频例子。
![image](https://github.com/Tencent/tdesign-miniprogram/assets/37070480/008c9364-b880-44f9-bda9-e360547e05ec)

https://github.com/Tencent/tdesign-miniprogram/assets/37070480/44ab33ed-0ee3-4edc-ba6e-5a8099640a23

**Comment by betavs** [comment]
> 能给组件添加一个插槽吗？

@lisashare 我可以理解为：添加一个固定在顶部的插槽吗？

**Comment by lisashare** [comment]
@betavs 是的，放一个在顶部的插槽，固不固定都可以根据样式调节

**Comment by betavs** [comment]
@anlyyao 看看是否需要添加一个 `header` 插槽 🤔

**Comment by lisashare** [comment]
@anlyyao 你好，下拉刷新的样式，loading-texts 提示语，不加的话，能正常展示loading 动画吗？很多时候我们不需要中文提示，只要简单的loading加载动画就好，谢谢！

**Comment by betavs** [comment]
> 下拉刷新的样式，loading-texts 提示语，不加的话，能正常展示loading 动画吗？很多时候我们不需要中文提示，只要简单的loading加载动画就好

@lisashare 如果不需要中文提示语，可以设置 `loadingTexts` 为 `['', '', '', '']` 即可

**Comment by lisashare** [comment]
@betavs 我是将提示语写成空了，可是下拉的时候，整个下拉过程，只有松开手才有加载loading，体验不是很好，应该是 ['下拉刷新', '松手刷新', '正在刷新', '刷新完成'] 整个过程都有loading在体验更好。

**Comment by lisashare** [comment]
可能是我的开发参考app是ios，交互体验细节要求高了

**Comment by betavs** [comment]
> 应该是 ['下拉刷新', '松手刷新', '正在刷新', '刷新完成'] 整个过程都有loading在体验更好

@lisashare 可只有 `'正在刷新'` 时，才会真正的触发刷新的业务

**Comment by anlyyao** [comment]
> @anlyyao 看看是否需要添加一个 `header` 插槽 🤔

我觉得可加～

**Comment by anlyyao** [comment]
> loading-texts



> @betavs 我是将提示语写成空了，可是下拉的时候，整个下拉过程，只有松开手才有加载loading，体验不是很好，应该是 ['下拉刷新', '松手刷新', '正在刷新', '刷新完成'] 整个过程都有loading在体验更好。

不显示提示文本，优化一下可以支持。全过程都有loading感觉不太适合哦🤔，我理解和@betavs一致，只有`正在刷新`才会真正触发数据请求接口，出现加载态～

**Comment by lisashare** [comment]
> > loading-texts
> 
> > @betavs 我是将提示语写成空了，可是下拉的时候，整个下拉过程，只有松开手才有加载loading，体验不是很好，应该是 ['下拉刷新', '松手刷新', '正在刷新', '刷新完成'] 整个过程都有loading在体验更好。
> 
> 不显示提示文本，优化一下可以支持。全过程都有loading感觉不太适合哦🤔，我理解和@betavs一致，只有`正在刷新`才会真正触发数据请求接口，出现加载态～

理解，感谢回复
