### ISSUE TITLE
[actionsheet] 宫格样式翻页了 tap拿到的dataset.index是当前页的 不是全部items的index，取值是个问题

### ISSUE THREAD

**Issue by TuKun33** [Tencent/tdesign-miniprogram#2655]
### tdesign-miniprogram 版本

1.2.3

### 期望结果

event.detail 把item全部返回吧, 只返回坐标 取值很费劲，

### 实际结果

![image](https://github.com/Tencent/tdesign-miniprogram/assets/22310931/5d69a5df-d6d0-455d-813e-ff9159429425)

**Comment by betavs** [comment]
https://github.com/Tencent/tdesign-miniprogram/blob/33de103e74f4efb18927bc55759e081e7cf8f6cd/src/action-sheet/README.md?plain=1#L108
