### ISSUE TITLE
[t-tab-bar] 点击选择的 tabbar 按钮后样式 t-tab-bar-item__content--checked  没有跟着过来

### ISSUE THREAD

**Issue by sundayha** [Tencent/tdesign-miniprogram#2667]
### tdesign-miniprogram 版本

1.2.9

### 基础库版本

3.3.5

### 补充说明

点击选择的 tabbar 组件按钮后样式 t-tab-bar-item__content--checked  没有跟着过来，看着像是没有选中，但是页面已经跳转了。真机预览和真机调试时都会有这个问题。在微信开发者工具中没有出现这个问题。
### 真机详情：
iPhone 14 Pro max， 
ios 16.5，
微信版本 8.0.46，
基础库 3.3.5[1179]

**Comment by betavs** [comment]
#2378

**Comment by sundayha** [comment]
汇总个靠谱一目了然的
```
app.js

App({
    globalData: {
        userInfo: null,
        value: "label_1"
      }
})

/custom-tab-bar/index.js

const app = getApp()
Component({
    data: {
      value: app.globalData.value,
      list: [
        { value: 'label_1', label: 'a', icon: 'pen-mark', url: '/pages/.../...' },
        { value: 'label_2', label: 'b', icon: 'book', url: '/pages/.../...' },
      ], 
    },
    lifetimes: {
        ready() {
            console.log('onReady', app.globalData.value)
            this.setData({
                value: app.globalData.value
            })
        },
    },

    methods: {
      onChange(e) {
        app.globalData.value = e.detail.value
        const array = this.data.list;
        const value = e.detail.value;
        array.forEach(element => {
            if (value === element.value) {
            const url = element.url;    
            wx.switchTab({ url })
            }
        });
      },
    },
  });
  
app.json

{
    "pages": [
        "pages/.../...",
        "pages/.../..."
    ],
    "window": {
        "navigationBarTitleText": "...",
        "navigationBarBackgroundColor": "#333333",
        "backgroundColor": "#d2ac67",
        "backgroundTextStyle": "light"
    },
    "tabBar": {
        "custom": true,
        "color": "#000000",
        "selectedColor": "#000000",
        "backgroundColor": "#000000",
        "list": [
          {
            "pagePath": "pages/.../..."
          },
          {
            "pagePath": "pages/.../..."
          }
        ]
      },
    "sitemapLocation": "sitemap.json",
    "lazyCodeLoading": "requiredComponents",
    "usingComponents": {
        "t-tab-bar": "tdesign-miniprogram/tab-bar/tab-bar",
        "t-tab-bar-item": "tdesign-miniprogram/tab-bar-item/tab-bar-item",
    }
}
```

**Comment by yuanyp8** [comment]
感谢老哥 ！！！！
作为后端 这个问题难了我两天了   
没有一个能用的文档 包括不靠谱的tdesign官方文档

**Comment by CSGrandeur** [comment]
> 汇总个靠谱一目了然的
> 
> ```
> app.js
> 
> App({
>     globalData: {
>         userInfo: null,
>         value: "label_1"
>       }
> })
> 
> /custom-tab-bar/index.js
> 
> const app = getApp()
> Component({
>     data: {
>       value: app.globalData.value,
>       list: [
>         { value: 'label_1', label: 'a', icon: 'pen-mark', url: '/pages/.../...' },
>         { value: 'label_2', label: 'b', icon: 'book', url: '/pages/.../...' },
>       ], 
>     },
>     lifetimes: {
>         ready() {
>             console.log('onReady', app.globalData.value)
>             this.setData({
>                 value: app.globalData.value
>             })
>         },
>     },
> 
>     methods: {
>       onChange(e) {
>         app.globalData.value = e.detail.value
>         const array = this.data.list;
>         const value = e.detail.value;
>         array.forEach(element => {
>             if (value === element.value) {
>             const url = element.url;    
>             wx.switchTab({ url })
>             }
>         });
>       },
>     },
>   });
>   
> app.json
> 
> {
>     "pages": [
>         "pages/.../...",
>         "pages/.../..."
>     ],
>     "window": {
>         "navigationBarTitleText": "...",
>         "navigationBarBackgroundColor": "#333333",
>         "backgroundColor": "#d2ac67",
>         "backgroundTextStyle": "light"
>     },
>     "tabBar": {
>         "custom": true,
>         "color": "#000000",
>         "selectedColor": "#000000",
>         "backgroundColor": "#000000",
>         "list": [
>           {
>             "pagePath": "pages/.../..."
>           },
>           {
>             "pagePath": "pages/.../..."
>           }
>         ]
>       },
>     "sitemapLocation": "sitemap.json",
>     "lazyCodeLoading": "requiredComponents",
>     "usingComponents": {
>         "t-tab-bar": "tdesign-miniprogram/tab-bar/tab-bar",
>         "t-tab-bar-item": "tdesign-miniprogram/tab-bar-item/tab-bar-item",
>     }
> }
> ```

非常好。其实就是tdesign没有支持switchtab后的状态保持，setdata又swtichtab就销毁了从而重置了tab的高亮。
就得自己在switchtab后计算现在是哪个tab，要么app全局存个变量，要么获取tab信息查找一下，但官方文档和tdesign文档就是不告诉你，气不气。
