### ISSUE TITLE
[calendar] 通过事件动态自定义文案不起作用

### ISSUE THREAD

**Issue by succeed318** [Tencent/tdesign-miniprogram#2669]
### tdesign-miniprogram 版本

1.2.9版本，在最新版本中也可以重新该问题

### 重现步骤

wxml文件
`<text>这是test页面</text>
<t-cell title="{{myName}}" note="{{myDescription}}" arrow bind:tap="handleCalendar"></t-cell>
<t-calendar visible="{{visible}}" use-popup="{{usePopup}}" minDate="{{minDate}}" maxDate="{{maxDate}}" value="{{value}}" format="{{format}}" bind:confirm="handleConfirm" />`

后台js页面

`
import { getBookingOrderList } from "../../utils/bookingApi";
Page({

    /**
     * 页面的初始数据
     */
    data: {
        myName: '本人预约',
        myDescription: "张三",
        orderDateList: [],
        usePopup: true,
        visible: false,
        value: "",
        minDate: (new Date()).getTime(),
        maxDate: (new Date()).getTime(),
        // format(day) {
        //     console.log("day", day.date.toLocaleDateString(), day.type);
        //     return day;
        // }
    },

    /**
     * 生命周期函数--监听页面加载
     */
    async onLoad(options) {
        const res = await getBookingOrderList();
        if (res.code === 0 && res.data.length > 0) {
            const minDt = new Date(res.data[0].bookingDate).getTime();
            const maxDt = new Date(res.data[res.data.length - 1].bookingDate).getTime();
            this.setData({
                orderDateList: res.data,
                minDate: minDt,
                maxDate: maxDt
            })
        }
    },
    handleCalendar() {
        // console.log("ol", this.data.orderDateList);
        this.setData({
            format(day) {
                console.log("day", day);
                if (day.type !== "disabled") {
                    console.log("day", day.date.toLocaleDateString());
                }

                return day;
            },
            visible: true
        })
    },
    handleConfirm(e) {
        console.log(e.detail.value);
    },
    /**
     * 生命周期函数--监听页面初次渲染完成
     */
    onReady() {

    },

    /**
     * 生命周期函数--监听页面显示
     */
    onShow() {

    },

    /**
     * 生命周期函数--监听页面隐藏
     */
    onHide() {

    },

    /**
     * 生命周期函数--监听页面卸载
     */
    onUnload() {

    },

    /**
     * 页面相关事件处理函数--监听用户下拉动作
     */
    onPullDownRefresh() {

    },

    /**
     * 页面上拉触底事件的处理函数
     */
    onReachBottom() {

    },

    /**
     * 用户点击右上角分享
     */
    onShareAppMessage() {

    }
})

`

![QQ截图20240327162200](https://github.com/Tencent/tdesign-miniprogram/assets/41133160/4215a344-2235-4c50-ad21-1b8b78618ca1)

### 期望结果

通过事件方式，可以动态设置日历自定义内容。

### 基础库版本

3.3.4

**Comment by succeed318** [comment]
这个功能主要是想实现预约功能，每天设置指定预约的人数，每天的人数不固定。让使用者在打开日历后可以清楚的看到相应的信息

**Comment by betavs** [comment]
```typescript
  handleCalendar() {
    this.setData(
      {
        format(day) {
          console.log("day", day);
          if (day.type !== "disabled") {
            console.log("day", day.date.toLocaleDateString());
          }

          return day;
        },
      },
      () => {
        this.setData({ visible: true });
      }
    );
  },
```

@succeed318 暂时可以这样处理

**Comment by succeed318** [comment]
![image](https://github.com/Tencent/tdesign-miniprogram/assets/41133160/ab4000d9-67ef-4b8b-924c-635a93532185)

**Comment by succeed318** [comment]
还是没有效果

**Comment by betavs** [comment]
> 还是没有效果

是的，并不会打印。但是并不会影响做业务

```typescript
interface TDate {
  date: Date;
  day: number;
  type: "selected" | "disabled" | "start" | "centre" | "end" | "";
  className?: string;
  prefix?: string;
  suffix?: string;
}

format(day: TDate) {
  return { ...day, day: 12 };
}
```

**Comment by succeed318** [comment]
js 代码

`import { getBookingOrderList } from "../../utils/bookingApi";
Page({

    /**
     * 页面的初始数据
     */
    data: {
        myName: '本人预约',
        myDescription: "张三",
        orderDateList: [],
        usePopup: true,
        visible: false,
        value: "",
        minDate: (new Date()).getTime(),
        maxDate: (new Date()).getTime(),
        // format(day) {
        //     console.log("day", day.date.toLocaleDateString(), day.type);
        //     return day;
        // }
    },

    /**
     * 生命周期函数--监听页面加载
     */
    async onLoad(options) {
        const res = await getBookingOrderList();
        if (res.code === 0 && res.data.length > 0) {
            const minDt = new Date(res.data[0].bookingDate).getTime();
            const maxDt = new Date(res.data[res.data.length - 1].bookingDate).getTime();
            this.setData({
                orderDateList: res.data,
                minDate: minDt,
                maxDate: maxDt
            })
        }
    },
    handleCalendar() {
        console.log("ol", this.data.orderDateList);
        const that = this;
        this.setData({
            format(day) {
                console.log("day1", day);
                if (day.type !== "disabled") {
                    let currentDate = day.date.toLocaleDateString();
                    that.data.orderDateList.forEach(item => {
                        let itemDate = new Date(item.bookingDate).toLocaleDateString();
                        if (currentDate === itemDate) {
                            day.suffix = `${isOrderedCount}/${totalCount}`
                            return day;
                        }
                    });
                    console.log("day11", day.date.toLocaleDateString());
                }
                console.log("day22", day.date.toLocaleDateString());
                return day;
            },

        }, () => {
            console.log("hahah");
            this.setData({
                visible: true
            })
        })
    },
    handleConfirm(e) {
        console.log(e.detail.value);
    },
    /**
     * 生命周期函数--监听页面初次渲染完成
     */
    onReady() {

    },

    /**
     * 生命周期函数--监听页面显示
     */
    onShow() {

    },

    /**
     * 生命周期函数--监听页面隐藏
     */
    onHide() {

    },

    /**
     * 生命周期函数--监听页面卸载
     */
    onUnload() {

    },

    /**
     * 页面相关事件处理函数--监听用户下拉动作
     */
    onPullDownRefresh() {

    },

    /**
     * 页面上拉触底事件的处理函数
     */
    onReachBottom() {

    },

    /**
     * 用户点击右上角分享
     */
    onShareAppMessage() {

    }
})`

后台数据
![image](https://github.com/Tencent/tdesign-miniprogram/assets/41133160/6a1e78f4-965e-4dbc-9f5f-e9caaee55236)

依旧没有变化
![image](https://github.com/Tencent/tdesign-miniprogram/assets/41133160/4064431f-7b0e-45d1-9e54-2adeb96fe9a1)

**Comment by betavs** [comment]
@succeed318 本地是可以的，可以的话还是提供完整的项目代码 🤔
