### ISSUE TITLE
Dialog中添加Input，placeholder打开时抖动

### ISSUE THREAD

**Issue by Leonxiso** [Tencent/tdesign-miniprogram#2674]
### tdesign-miniprogram 版本

项目版本1.2.9和在线文档均能重现

### 重现链接

https://tdesign.tencent.com/miniprogram/components/dialog

### 重现步骤

在线文档dialog组件输入类对话框均能重现

https://github.com/Tencent/tdesign-miniprogram/assets/53372520/79996527-83fd-49bf-9d91-2ada8f32f3a9

### 期望结果

修正后进入正常显示，不再抖动一下

**Comment by jarmywang** [comment]
微信小程序本身的问题，暂时没有好的解决办法
