### ISSUE TITLE
[tab-bar] icon slot 只有在设置了icon=true的情况下才能使用

### ISSUE THREAD

**Issue by ztr323** [Tencent/tdesign-miniprogram#2678]
### tdesign-miniprogram 版本

1.6.0

### 重现链接

<t-tab-bar-item value="home" icon="{{true}}"><view slot="icon"> 123 <view></view> 		</view>

### 重现步骤

设置icon="{{true}}"能显示123，不设置icon="{{true}}"，不能显示123

### 期望结果

不设置icon="{{true}}"也能显示123

### 实际结果

不设置icon="{{true}}"，不能显示123

**Comment by anlyyao** [comment]
@ztr323 1.x阶段，暂时不考虑调整～
