### ISSUE TITLE
[SwipeCell 滑动单元格] 微信小程序开启按需注入后在真机上无法滑动

### ISSUE THREAD

**Issue by Xic1007** [Tencent/tdesign-miniprogram#2680]
### tdesign-miniprogram 版本

1.2.9

### 重现步骤

1.index. json：
"usingComponents": {
     "t-swipe-cell": "tdesign-miniprogram/swipe-cell/swipe-cell"
}
2. wxml：
<t-swipe-cell right="{{right}}" bind:click="onActionClick">
        <t-cell title="学习计划" note="{{status}}" bordered="{{false}}" />
    </t-swipe-cell>
3. onActionClick({ detail }) {
      wx.showToast({ title: `你点击了${detail.text}`, icon: 'none' });
    },
4.app.json
"lazyCodeLoading": "requiredComponents"

### 期望结果

使用"lazyCodeLoading": "requiredComponents"时，组件在真机上也能正常使用

### 实际结果

使用"lazyCodeLoading": "requiredComponents"时，组件在真机上无法滑动
控制台报错：
Component "miniprogram_npm/tdesign-miniprogram/swipe-cell/swipe-cell" does not have a method "function(...e){const o=gdc(e,void 0===t?"nv_":void 0),r=n.apply(i,o);return gdc(r,t)}" to handle event "touchstart".
Component "miniprogram_npm/tdesign-miniprogram/swipe-cell/swipe-cell" does not have a method "function(...e){const o=gdc(e,void 0===t?"nv_":void 0),r=n.apply(i,o);return gdc(r,t)}" to handle event "touchmove".
Component "miniprogram_npm/tdesign-miniprogram/swipe-cell/swipe-cell" does not have a method "function(...e){const o=gdc(e,void 0===t?"nv_":void 0),r=n.apply(i,o);return gdc(r,t)}" to handle event "touchend".

**Comment by anlyyao** [comment]
Duplicate #2668
