### ISSUE TITLE
t-cell 的属性 description 插槽的使用方式

### ISSUE THREAD

**Issue by luoxin59420** [Tencent/tdesign-miniprogram#2687]
### tdesign-miniprogram 版本

无

### 重现链接

无

### 重现步骤

<t-cell title="进入直连" leftIcon="link" hover
        description="slot"
      >

### 期望结果

官网没有给出使用方式，求解答

**Comment by betavs** [comment]
https://github.com/Tencent/tdesign-miniprogram/blob/cb9900ba121f5e910fe90ff0751025d4b70b2819/src/cell/README.md?plain=1#L49

```html
<t-cell title="title" description="description" />
<t-cell title="title">
  <view slot="description">description</view>
</t-cell>
```
