### ISSUE TITLE
Tabs 选项卡  两个选项时 初始化 active 光条 位置计算不对啊

### ISSUE THREAD

**Issue by mayiyahei1992** [Tencent/tdesign-miniprogram#2688]
### tdesign-miniprogram 版本

1.2.9

### 期望结果

第一个文字正下方

### 实际结果

最左下角

### 基础库版本

3.4.0

### 补充说明

你官方示例也有这个问题
![微信截图_20240410155809](https://github.com/Tencent/tdesign-miniprogram/assets/48984649/f4217602-a488-46c3-bf09-48707aa1d44a)

**Comment by jarmywang** [comment]
我这里真机和ide暂未复现，麻烦给一个代码片段 @mayiyahei1992

**Comment by Little-King2022** [comment]
@jarmywang 官网的demo就有问题，必须要切换一次之后才显示正常
<img width="389" alt="截屏2024-04-21 17 34 22" src="https://github.com/Tencent/tdesign-miniprogram/assets/110970384/89423cc6-bc38-4dc7-bd5a-f115fa5ba01f">

**Comment by anlyyao** [comment]
@mayiyahei1992 更新到1.4.4在试试，以真机效果为准，如果还有该问题，请提供可复现代码片段，我这边会继续跟进的～
