### ISSUE TITLE
[t-slider] 设置默认值无法定位到指定位置，还是在初始0的位置

### ISSUE THREAD

**Issue by dongshihao666** [Tencent/tdesign-miniprogram#2691]
### tdesign-miniprogram 版本

可复现

### 重现链接

<t-slider value="{{20}}" label="${value}" bind:change="handleChange"></t-slider>

### 重现步骤

<img width="372" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/29971202/21a612af-7f2d-46c4-a534-97d9d91d9c3e">

### 期望结果

应该定位到20 

### 实际结果

还是在0的位置

**Comment by anlyyao** [comment]
@dongshihao666 辛苦贴一下你的实际使用代码哦，我们这边看初始值非0示例是正常的～

**Comment by dongshihao666** [comment]
<img width="1257" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/29971202/5ddd55a6-9569-4380-9b66-075cfe69d696">
这是官网示例  正常吗 35在最初位置

**Comment by betavs** [comment]
> <img alt="image" width="1257" src="https://private-user-images.githubusercontent.com/29971202/322686943-5ddd55a6-9569-4380-9b66-075cfe69d696.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNTg5MzYsIm5iZiI6MTcxMzI1ODYzNiwicGF0aCI6Ii8yOTk3MTIwMi8zMjI2ODY5NDMtNWRkZDU1YTYtOTU2OS00MzgwLTliNjYtMDc1Y2ZlNjlkNjk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDA5MTAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0ZTViMDI1MzRlYjI2MDQwMjA0MzM3YzZkNjE1NWZiYmMxMWU1ZjQzNThmMjFhNmZkZTUxZWU4NTdmYWEwNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S9IM-iv9VWQ0SyTK0QfliDXWK-CAaruUTL2TwV-ODe8"> 这是官网示例 正常吗 35在最初位置

这是 `miniprogram-live/m2w/program/miniprogram` 转换的问题

**Comment by betavs** [comment]
```html
<t-button bind:tap="handleClick">Slider Button</t-button>

<t-dialog visible="{{visible}}">
  <t-slider slot="content" value="{{value}}" label="${value}" bind:change="handleChange" />
</t-dialog>
```

```javascript
Component({
  data: {
    value: 35,
    visible: false,
  },
  methods: {
    handleClick() {
      this.setData({ visible: true });
    },

    handleChange(e) {
      this.setData({
        value: e.detail.value,
      });
    },
  },
});
```

@anlyyao 这种情况下可以复现

**Comment by jarmywang** [comment]
@dongshihao666 如果是在dialog/popup中设置初始值可能会有问题，因为slider初始会计算一些位置信息，而在dialog/popup中初始位置获取会有异常，加上dialog/popup的出现动画，建议如下设置初始值就没问题`this.setData({ visible: true }, () => setTimeout(() => this.setData({ value: 35 }), 350));`
