### ISSUE TITLE
[SideBar] 在切页模式下增加一个触底事件

### ISSUE THREAD

**Issue by suleilei** [Tencent/tdesign-miniprogram#2692]
### 这个功能解决了什么问题

建议在切页模式下增加一个触底事件，因为使用[Sidebar]组件后，滚动时小程序端自带的  onReachBottom 无法触发。
@大牛们：如果有其他解决方法望指教，谢谢！

### 你建议的方案是什么

建议在切页模式下增加一个触底事件，因为使用[Sidebar]组件后，滚动时小程序端自带的  onReachBottom 无法触发。
@大牛们：如果有其他解决方法望指教，谢谢！

**Comment by anlyyao** [comment]
@suleilei 你是指右侧的内容区域滚动无法触发 onReachBottom()？
<img width="389" alt="截屏2024-04-15 15 31 52" src="https://github.com/Tencent/tdesign-miniprogram/assets/51158141/ff808d86-d0bb-46b7-9a89-a763a88616d0">

**Comment by jarmywang** [comment]
SideBar只是左侧部分，右侧部分请自行实现，可参考[示例](https://github.com/Tencent/tdesign-miniprogram/blob/develop/src/side-bar/_example/base/index.wxml) ，触底通过scroll-view组件的属性
