### ISSUE TITLE
[Calendar 日历] 微信小程序confirm-btn为null还是展示了确认按钮

### ISSUE THREAD

**Issue by Memoryzzzzzz** [Tencent/tdesign-miniprogram#2701]
### tdesign-miniprogram 版本

1.2.9

### 重现链接

<t-calendar confirm-btn="null"/>

### 重现步骤

confirm-btn为null还是展示了确认按钮，并且展示null
<img width="383" alt="Snipaste_2024-04-16_22-59-52" src="https://github.com/Tencent/tdesign-miniprogram/assets/41710152/2b6103c5-8f01-4eb3-82f5-10b53a1b6dd5">

### 期望结果

如文档所说，不展示确认按钮

### 实际结果

展示按钮，并且展示null

**Comment by jarmywang** [comment]
confirm-btn="{{null}}"
