### ISSUE TITLE
[Message] offset偏移量属性在大屏幕设备上的适配

### ISSUE THREAD

**Issue by Little-King2022** [Tencent/tdesign-miniprogram#2702]
### tdesign-miniprogram 版本

"version": "1.2.9"

### 重现步骤

<img width="1055" alt="截屏2024-04-16 23 02 13" src="https://github.com/Tencent/tdesign-miniprogram/assets/110970384/3c56eccf-b351-4aed-a352-a70834e61a5d">

### 期望结果

如何设置可以让弹窗相对于<navigation-bar>偏移？

### 实际结果

Message弹窗在不同尺寸设备（iphone、ipad）上的偏离距离不同，甚至在ipad上几乎看不到了。

<img width="266" alt="截屏2024-04-16 23 05 04" src="https://github.com/Tencent/tdesign-miniprogram/assets/110970384/127cf0ab-dbf3-43c4-8aa6-392ce03f6065">

<img width="352" alt="截屏2024-04-16 23 04 32" src="https://github.com/Tencent/tdesign-miniprogram/assets/110970384/7b1d39ed-d3fb-4334-b3fa-ab6a7d5e05b6">

<img width="699" alt="截屏2024-04-16 23 05 37" src="https://github.com/Tencent/tdesign-miniprogram/assets/110970384/14b417d2-d65b-413b-82d4-7a495a4b1f87">

### 基础库版本

2.27.3

**Comment by jarmywang** [comment]
未复现，请提供一个代码片段

**Comment by Little-King2022** [comment]
> 未复现，请提供一个代码片段

https://developers.weixin.qq.com/s/yi4zqwmg7RQP

**Comment by anlyyao** [comment]
@Little-King2022 更新一下版本～
