### ISSUE TITLE
[Fab] 将可移动悬浮按钮拖到自定义标题栏区域，可以看到按钮被遮挡。如果按钮被完全遮挡后会拖不回来

### ISSUE THREAD

**Issue by ArcticFoxPro** [Tencent/tdesign-miniprogram#2717]
### tdesign-miniprogram 版本

1.3.0

### 重现链接

微信搜一搜“TDesign组件库”（即你们自家的示例小程序会复现此问题）

### 重现步骤

进入 TDesign组件库 微信小程序后：

1. 点击“基础”-“悬浮按钮”
2. 点击“可移动悬浮按钮”
3. 将“拖我”按钮拖到自定义标题栏区域，可以看到按钮被遮挡。如果按钮被完全遮挡后会拖不回来。

### 期望结果

按钮与自定义标题栏做一个碰撞判断，当屏幕触摸点碰到自定义标题栏后按钮不再跟随屏幕触摸点。

### 实际结果

当屏幕触摸点碰到自定义标题栏后按钮仍然跟随屏幕触摸点。

### 基础库版本

未知。如有需要，需要 TDesign组件库 示例小程序开发者自行查看其基础库。

### 补充说明

@anlyyao 让我填的。

**Comment by anlyyao** [comment]
anlyyao 表示收到反馈
