### ISSUE TITLE
[BackTop 返回顶部] 不符合设计稿设计，在深色模式和浅色模式下均为圆形为浅色，半圆形为深色

### ISSUE THREAD

**Issue by ArcticFoxPro** [Tencent/tdesign-miniprogram#2720]
### tdesign-miniprogram 版本

1.3.0

### 重现链接

微信搜一搜“TDesign组件库”（即你们自家的示例小程序会复现此问题）

### 重现步骤

进入 TDesign组件库 微信小程序后：

1. 点击“导航”-“BackTop 返回顶部”
2. 点击“圆形返回顶部”和“半圆形返回顶部”观察样式表现

### 期望结果

根据 TDesign 设计稿，BackTop 在深色模式和浅色模式下的 BackTop 样式表现应该有深浅切换

![mmexport1713854404742.jpg](https://github.com/Tencent/tdesign-miniprogram/assets/139336664/7885ef45-d79d-4bbd-a1cc-bb443c376027)

### 实际结果

在深色模式和浅色模式下均为 圆形为浅色，半圆形为深色。

### 基础库版本

未知。如有需要，需要 TDesign组件库 示例小程序开发者自行查看其基础库。

### 补充说明

@anlyyao 让我填的。

**Comment by anlyyao** [comment]
@ArcticFoxPro 有组件属性问题，目前的处理方案为round/half-round主题支持适配深色模式，round-dark/half-round-dark深色/浅色模式表现一致。未来 [theme枚举值取](https://github.com/Tencent/tdesign-miniprogram/discussions/1761)：round/half-round，round-dark/half-round-dark适配成暗黑模式
