### ISSUE TITLE
[swiper] swiper放入popup里无法滚动

### ISSUE THREAD

**Issue by xteabag** [Tencent/tdesign-miniprogram#274]
### tdesign-miniprogram 版本

0.6.2

### 重现步骤

1、popup的visible默认为false
2、将swiper放入popup中
3、改变popup的visible为true
此时显示swiper轮播图，但无法滚动

**Comment by esky** [comment]
@xteabag 
小程序中不可见的元素，可能导致动画异常，同时swiper初始化时依赖元素计算。若在t-popup中使用，请`t-swiper wx:if="{{visible}}"`确保正确初始化，同时也能节省资源开销（需要显示时才创建swiper）。

```html
   <t-popup visible="{{visible}}">
       <t-swiper wx:if="{{visible}}" current="{{1}}" autoplay height="{{400}}">... </t-swiper>
    </t-popup>
```

**Comment by xteabag** [comment]
谢谢耐心解答
