### ISSUE TITLE
[TDesign] 1.3.1新版本控制台大量警告问题

### ISSUE THREAD

**Issue by Nero978** [Tencent/tdesign-miniprogram#2741]
### tdesign-miniprogram 版本

1.3.1

### 重现步骤

由`1.3.0`升级到`1.3.1`，控制台出现大量警告

### 期望结果

没有警告

### 实际结果

控制台大量警告
![image](https://github.com/Tencent/tdesign-miniprogram/assets/63546553/d72810c4-cf08-4a8d-b2f3-2853ac79b2a2)

### 基础库版本

3.4.1

### 补充说明

看了下，猜测是`1.3.1`中组件的`wxss`文件中使用了tag选择器`page`
参考文档：https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#%E7%BB%84%E4%BB%B6%E6%A0%B7%E5%BC%8F

**Comment by anlyyao** [comment]
可能是 page 选择器带来的告警，这里牵扯到深/浅模式的样式问题，我这边来跟进看看哇～

**Comment by Nero978** [comment]
是不是可以随npm包一起发布light、dark主题的css token呢？
在文档中引导开发者在app.wxss中导入主题wxss，因为在实际使用组件时，也经常在组件外使用到上述css token，也避免了在控制台产生page选择器警告的问题

> 可能是 page 选择器带来的告警，这里牵扯到深/浅模式的样式问题，我这边来跟进看看哇～

**Comment by anlyyao** [comment]
> 是不是可以随npm包一起发布light、dark主题的css token呢？ 在文档中引导开发者在app.wxss中导入主题wxss，因为在实际使用组件时，也经常在组件外使用到上述css token，也避免了在控制台产生page选择器警告的问题 如果需要对主题进行自定义，或许也可以在官网开放一个css token调整的入口，在网站上调整完毕后生成css token的wxss来替代npm包中的wxss，供开发者自行导入来自定义主题
> 
> > 可能是 page 选择器带来的告警，这里牵扯到深/浅模式的样式问题，我这边来跟进看看哇～

已在 #2750 处理。 npm包中其实包含了light、dark等 design token 文件，在`miniprogram_npm/tdesign-miniprogram/common/style/theme` 路径下

**Comment by anlyyao** [comment]
> 是不是可以随npm包一起发布light、dark主题的css token呢？ 在文档中引导开发者在app.wxss中导入主题wxss，因为在实际使用组件时，也经常在组件外使用到上述css token，也避免了在控制台产生page选择器警告的问题 如果需要对主题进行自定义，或许也可以在官网开放一个css token调整的入口，在网站上调整完毕后生成css token的wxss来替代npm包中的wxss，供开发者自行导入来自定义主题
> 
> > 可能是 page 选择器带来的告警，这里牵扯到深/浅模式的样式问题，我这边来跟进看看哇～

也在计划引入主题生成器，但大概要下半年了～
