### ISSUE TITLE
[Fab 悬浮按钮] demo与示例代码不一致

### ISSUE THREAD

**Issue by YouDuckBoom** [Tencent/tdesign-miniprogram#2742]
### tdesign-miniprogram 版本

1.3.1

### 重现链接

https://tdesign.tencent.com/miniprogram/components/fab?tab=demo

### 重现步骤

demo与示例代码还有API文档说明不一致

### 期望结果

更新示例代码

**Comment by anlyyao** [comment]
官网上展示的示例不是整个 demo page，而是聚焦在组件本身上，比如 Fab，你 copy 四个文件的内容后，就会得到悬浮按钮，不会包含其他元素。
<img width="1354" alt="企业微信截图_df34b64e-e9a7-4019-88e0-365f3b36249d" src="https://github.com/Tencent/tdesign-miniprogram/assets/51158141/da40ecd4-acb1-4fae-93f0-b1755462796a">

如果你想得到整个page的示例， 请查看[源码](https://github.com/Tencent/tdesign-miniprogram/blob/develop/src/fab/_example/fab.wxml) ，拖拽按钮的代码没有暴露，我稍后补充～

**Comment by YouDuckBoom** [comment]
抱歉,我的描述不太准确,感谢补充

**Comment by anlyyao** [comment]
> 抱歉,我的描述不太准确,感谢补充

没事哈，有疑问欢迎随时反馈～
