### ISSUE TITLE
[upload] 由1.3.0升级到1.3.1点击无法弹出选择图片

### ISSUE THREAD

**Issue by ayuday** [Tencent/tdesign-miniprogram#2743]
### tdesign-miniprogram 版本

1.3.1

### 重现链接

代码片段：https://developers.weixin.qq.com/s/FwsPTZmm7WQA

### 重现步骤

由1.3.0升级到1.3.1点击无法弹出选择图片

![image](https://github.com/Tencent/tdesign-miniprogram/assets/12504837/d63c42cf-4167-483e-868e-c64ce1b11964)

**Comment by anlyyao** [comment]
1.3.0 到 1.3.1没有Upload组件相关的变更，辛苦在确认一下版本问题～

**Comment by ayuday** [comment]
> @ayuday 1.3.0 到 1.3.1没有Upload组件相关的变更，辛苦在确认一下版本问题～

我是微信开发者工具用模板新建，完了用npm安装构建成1.3.1后就无法使用upload, 
有代码片段：https://developers.weixin.qq.com/s/FwsPTZmm7WQA
![image](https://github.com/Tencent/tdesign-miniprogram/assets/12504837/da0f61a9-0527-493d-af7a-6beba9a1f7a1)

**Comment by xiaweiss** [comment]
小程序示例也失效了，稳定复现 https://github.com/Tencent/tdesign-miniprogram/issues/2760

**Comment by jarmywang** [comment]
> Tdesign 小程序示例也失效了，稳定复现 #2760

@xiaweiss 示例Upload组件均为禁用态，为了绕过隐私协议，顶部有说明

**Comment by anlyyao** [comment]
<img width="1214" alt="企业微信截图_0ecd7b94-f2b8-4bca-8eb5-7c67cbbe620e" src="https://github.com/user-attachments/assets/6b1b398b-cd09-499a-999e-dc6a365cacb2">
