### ISSUE TITLE
[Calendar 日历] 日历无法选择当天的区间吗？

### ISSUE THREAD

**Issue by LrainchenL** [Tencent/tdesign-miniprogram#2762]
### 这个功能解决了什么问题

当用户选择日期查询报表时，需要查询当天时间，例如2024/05/10 00:00:00 - 2024/05/10 23:59:59

### 你建议的方案是什么

在type=“range”时，连续两次点击相同日期，可以选择同一天，例如2024/05/10 - 2024/05/10

**Comment by jarmywang** [comment]
当前range可以只选一个然后点击确定，当只有一个的时候你可以自行实现算出0点-24点 @LrainchenL

**Comment by LrainchenL** [comment]
我现在就是选一个点击确定，然后通过返回的value值的长度去判断，长度为1的话就代表选择的是当天

> 当前range可以只选一个然后点击确定，当只有一个的时候你可以自行实现算出0点-24点 @LrainchenL
