### ISSUE TITLE
使用iconfont时，前缀加了‘-’， 导致样式不生效

### ISSUE THREAD

**Issue by ado5** [Tencent/tdesign-miniprogram#2766]
### tdesign-miniprogram 版本

1.3.1

### 重现步骤
`
<t-icon name="car-yaoqing" prefix="charteredcar" size="40rpx" color="#777" />
`

### 期望结果

`<label class="charteredcar car-yaoqing t-icon-base"></label>`

### 实际结果

`<label class="charteredcar-car-yaoqing t-icon-base"></label>
`
### 基础库版本

3.0.2

**Comment by anlyyao** [comment]
@ado5 如果你正在通过 prefix 属性来自定义图标，目前的实际结果符合预期。建议按照官网的文档来准备图[标文件 ](https://tdesign.tencent.com/miniprogram/components/icon?tab=demo)

<img width="593" alt="企业微信截图_b459fa2e-c3c7-4ea2-9ffa-d11a2325f613" src="https://github.com/Tencent/tdesign-miniprogram/assets/51158141/a4f7f01f-0d19-4d46-9bb8-3d327599bf97">
