### ISSUE TITLE
[t-indexes] 在列表数据不够一个屏幕展示情况  选择 后面的索引字母  选择状态依然停留在  第一个数据所以字母上。比如列表有  abcde 的值，默认进来a是选中样式。在点e的时候选中样式还在a上

### ISSUE THREAD

**Issue by Aholy-nn** [Tencent/tdesign-miniprogram#2769]
### tdesign-miniprogram 版本

可以

### 重现步骤

在列表数据不够一个屏幕展示情况  选择 后面的索引字母  选择状态依然停留在  第一个数据所以字母上。比如列表有  abcde 的值，默认进来a是选中样式。在点e的时候选中样式还在a上

### 期望结果

在点e的时候选中样式还在e上

**Comment by anlyyao** [comment]
@Aholy-nn sorry 是我误导你了😭。目前的表现是预期内，交互设计如此，不属于 bug。 这个组件的交互我们参考了微信通讯录等其他应用 app， 当所有索引列表数据不满一屏的情况下，不论点击哪一项，激活态都会给到第一项
