### ISSUE TITLE
[button] icon属性填写图片链接无法显示

### ISSUE THREAD

**Issue by ZiZiZiNone** [Tencent/tdesign-miniprogram#2775]
### tdesign-miniprogram 版本

1.4.0

### 重现步骤

```bash
<t-button icon="https://img2.baidu.com/it/u=3425609012,1563779818&fm=253&fmt=auto&app=138&f=JPEG?w=500&h=500" ></t-button>

用选择工具查看内部image宽高为0
```

### 实际结果

icon属性填写图片链接无法显示

### 基础库版本

3.4.2

**Comment by betavs** [comment]
名称 | 类型 | 默认值 | 说明
-- | -- | -- | --
icon | String / Object | - | 图标名称。值为字符串表示图标名称，值为 `Object` 类型，表示透传至 `icon`。

暂时无法自定义图标的

**Comment by ZiZiZiNone** [comment]
使用object类型透传到icon也无法显示
icon的name属性是可以填写图片链接的

### icon图标
属性 | 值类型 | 默认值 | 必传 | 说明
-- | -- | -- | -- | --
name | String | - | Y | 图标名称或图片链接

@betavs

**Comment by betavs** [comment]
```typescript
    icon: {
      name: 'https://img2.baidu.com/it/u=3425609012,1563779818&fm=253&fmt=auto&app=138&f=JPEG?w=500&h=500',
      size: 24,
    },
```
