### ISSUE TITLE
[T-Button] 为什么使用::after 来给按钮加边框

### ISSUE THREAD

**Issue by lizihanglove** [Tencent/tdesign-miniprogram#2776]
### tdesign-miniprogram 版本

1.4.0

**Comment by anlyyao** [comment]
<img width="879" alt="企业微信截图_78c8e2a4-8f45-4d4a-927a-8089c8eba176" src="https://github.com/Tencent/tdesign-miniprogram/assets/51158141/dad40046-3c73-4a48-908f-2816006bcd84">

原生 button 的 boder 是用 after 伪元素实现，TButton 算是重写或者覆盖吧🤔
