### ISSUE TITLE
[t-upload和t-popup]在有tabBar页面，组合使用t-upload和t-popup上传文件会闪屏

### ISSUE THREAD

**Issue by MING789852** [Tencent/tdesign-miniprogram#2777]
### tdesign-miniprogram 版本

1.4.0

### 重现步骤

在有tabBar页面，组合使用t-upload和t-popup，点击上传文件会闪屏
`  <t-popup style="height: 70vh" visible="{{popupVisible}}" bind:visible-change="onVisibleChange" close-on-overlay-click="{{true}}" placement="bottom">
  <view style="padding-left: 10px;padding-right: 10px">
    <t-upload  mediaType="{{['image']}}" max="{{0}}" files="{{receiveData.fileList}}" bind:add="handleFileAdd" bind:remove="handleFileRemove">
    </t-upload>
    <t-button style="margin-top:20px;" theme="primary" size="large" bind:tap="save" block>保存</t-button>
  </view>
</t-popup> `

主页tabBar
![image](https://github.com/Tencent/tdesign-miniprogram/assets/51882957/ade74252-3e01-4e22-a7aa-50fab3c51131)
上传文件前
![image](https://github.com/Tencent/tdesign-miniprogram/assets/51882957/924cf2d7-17a3-4168-a9b5-ea23bb28346b)
上传文件后
![image](https://github.com/Tencent/tdesign-miniprogram/assets/51882957/e330f157-732b-4c8a-aa59-9fddb81b2214)
并且鼠标移动到对应位置会一直闪屏

没有tabBar的界面就没有这个问题

### 基础库版本

2.33.0

**Comment by anlyyao** [comment]
@MING789852  辛苦贴一下完整的可复现代码或者提供一个代码片段链接？

**Comment by MING789852** [comment]
> @MING789852 辛苦贴一下完整的可复现代码或者提供一个代码片段链接？

你好，应该不是组件问题，我把GPU加速关了就不会
![image](https://github.com/Tencent/tdesign-miniprogram/assets/51882957/4fea1fc1-04c8-493a-8d40-3cd51fe90f43)

**Comment by anlyyao** [comment]
> > @MING789852 辛苦贴一下完整的可复现代码或者提供一个代码片段链接？
> 
> 你好，应该不是组件问题，我把GPU加速关了就不会 ![image](https://private-user-images.githubusercontent.com/51882957/332638617-4fea1fc1-04c8-493a-8d40-3cd51fe90f43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNDY4MDksIm5iZiI6MTcxNjM0NjUwOSwicGF0aCI6Ii81MTg4Mjk1Ny8zMzI2Mzg2MTctNGZlYTFmYzEtMDRjOC00OTNhLThkNDAtM2NkNTFmZTkwZjQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDAyNTUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhOGNjMjFlMzJiY2Y1OTBiYjM0OGE1YTRiNmEwYWE2ZmYzMmM4YzZhZWUwMjRiNTMwYmI3NzY4NjAzYjUwMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V91a1lVPbs5HLFfMYXxaPQFK9GrXAcL_QFlqiP6mNII)

好的啊，建议以真机效果为准。我这边也跟进看看～

**Comment by MING789852** [comment]
> > > @MING789852 辛苦贴一下完整的可复现代码或者提供一个代码片段链接？
> > 
> > 
> > 你好，应该不是组件问题，我把GPU加速关了就不会 ![image](https://private-user-images.githubusercontent.com/51882957/332638617-4fea1fc1-04c8-493a-8d40-3cd51fe90f43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNDY4MDksIm5iZiI6MTcxNjM0NjUwOSwicGF0aCI6Ii81MTg4Mjk1Ny8zMzI2Mzg2MTctNGZlYTFmYzEtMDRjOC00OTNhLThkNDAtM2NkNTFmZTkwZjQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDAyNTUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhOGNjMjFlMzJiY2Y1OTBiYjM0OGE1YTRiNmEwYWE2ZmYzMmM4YzZhZWUwMjRiNTMwYmI3NzY4NjAzYjUwMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V91a1lVPbs5HLFfMYXxaPQFK9GrXAcL_QFlqiP6mNII)
> 
> 好的啊，建议以真机效果为准。我这边也跟进看看～

真机目前我的Android机没问题，后面还有出现我再反馈，麻烦你了
