### ISSUE TITLE
文档  Message 消息通知组件 预览区白屏，看控制台报错了。

### ISSUE THREAD

**Issue by lightsaid** [Tencent/tdesign-miniprogram#2784]
### tdesign-miniprogram 版本

是

### 重现链接

https://tdesign.tencent.com/miniprogram/components/message?tab=demo

### 重现步骤

文档  Message 消息通知组件 预览区白屏，看控制台报错了。

**Comment by wangxiaoming-1997** [comment]
> 打包的问题，已处理，稍后重新更新官网。辛苦先用真机扫码体验～

现在是5月29日,好像官网的示例还是不行

**Comment by anlyyao** [comment]
> > 打包的问题，已处理，稍后重新更新官网。辛苦先用真机扫码体验～
> 
> 现在是5月29日,好像官网的示例还是不行

😭 是的，上个版本修复了别名的问题， message 组件还有另一个问题，我本周处理一下，不影响组件在开发工具和真机上的使用哈～
