### ISSUE TITLE
[Cascader ] 级联组件picker事件能不能返回label

### ISSUE THREAD

**Issue by liugt34** [Tencent/tdesign-miniprogram#2789]
### 这个功能解决了什么问题

当前功能只是返回了value, 但是很多时候需要label值进行展示

### 你建议的方案是什么

返回label值

**Comment by ZiZiZiNone** [comment]
Cascader Props

名称 | 类型 | 默认值 | 说明 | 必传
-- | -- | -- | -- | --
keys | Object | - | 用来定义 value / label 在 options 中对应的字段别名。TS 类型：KeysType。通用类型定义 | N

这个有value和label吧
不过如果我要返回的属性不止一个就只能把整个Object 赋值给data里面的属性了
