### ISSUE TITLE
[Tabs] 当设置tabs的字体后，底部滚动条位置有偏移

### ISSUE THREAD

**Issue by ml4165837** [Tencent/tdesign-miniprogram#2793]
### tdesign-miniprogram 版本

1.4.0

### 重现步骤

1、引入 
"t-tabs": "tdesign-miniprogram/tabs/tabs",
"t-tab-panel": "tdesign-miniprogram/tab-panel/tab-panel"
2、设置样式
.t-tabs__item--active {
  font-weight: 500;
  font-size: 36rpx;
  color: #282828;
  line-height: 50rpx;
}
3、点击tab进行切换

### 期望结果

底部滚动条居中显示

### 实际结果

底部滚动条偏移
<img width="284" alt="Snipaste_2024-05-23_10-51-49" src="https://github.com/Tencent/tdesign-miniprogram/assets/4706344/8ef181fd-d4f9-4d57-a514-4ba490678324">

### 基础库版本

3.4.2

**Comment by anlyyao** [comment]
@ml4165837 收到反馈，我来跟进～

**Comment by anlyyao** [comment]
@ml4165837 贴一下完整的代码？ 目前提供的无法复现你的问题
