### ISSUE TITLE
[Progress] 环形大小改变不了

### ISSUE THREAD

**Issue by HQ-YYK** [Tencent/tdesign-miniprogram#2805]
### tdesign-miniprogram 版本

^2.8.3-1

### 重现步骤

 <t-progress percentage="80"  theme="circle" custom-style="width: 60rpx;height: 60rpx"/> 
 
 .t-progress__canvas--circle{
  width: 60rpx !important;
  height: 60rpx !important;
}

这样都不行

**Comment by betavs** [comment]
设置 `strokeWidth` 值即可

**Comment by HQ-YYK** [comment]
设置也不行的 是整体大小 不是圆环大小

**Comment by HQ-YYK** [comment]
设置前 
![image](https://github.com/Tencent/tdesign-miniprogram/assets/54365306/85a2dd9c-a40a-4963-8315-1a65f25a892f)
![image](https://github.com/Tencent/tdesign-miniprogram/assets/54365306/a1ca3c0d-f9ca-41b4-ab49-b14d50123a7c)

设置后
![image](https://github.com/Tencent/tdesign-miniprogram/assets/54365306/5c91dd95-2acc-4b3d-a164-8c0e13bd68e0)
![image](https://github.com/Tencent/tdesign-miniprogram/assets/54365306/964237ec-0cf2-451f-bebf-8a3e5a75f4f3)

**Comment by HQ-YYK** [comment]
@anlyyao

**Comment by anlyyao** [comment]
> 设置前 ![image](https://private-user-images.githubusercontent.com/54365306/334629315-85a2dd9c-a40a-4963-8315-1a65f25a892f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NTA1NTksIm5iZiI6MTcxNjk1MDI1OSwicGF0aCI6Ii81NDM2NTMwNi8zMzQ2MjkzMTUtODVhMmRkOWMtYTQwYS00OTYzLTgzMTUtMWE2NWYyNWE4OTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDAyMzczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNDEzNWRhOTQwMDkwZjg2ZDcxNGFlNDUzZTdmZTI4NGU3MjAzN2VmNjhiM2ZkOWY2ZGM5MDE0NGVkODI4OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RQcKenc7rd772C_yYbDumvhYvsTT2J8yipOvtqBSxqg) ![image](https://private-user-images.githubusercontent.com/54365306/334629367-a1ca3c0d-f9ca-41b4-ab49-b14d50123a7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NTA1NTksIm5iZiI6MTcxNjk1MDI1OSwicGF0aCI6Ii81NDM2NTMwNi8zMzQ2MjkzNjctYTFjYTNjMGQtZjljYS00MWI0LWFiNDktYjE0ZDUwMTIzYTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDAyMzczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5MTU5NTg0MmY4OWU4OTQ2NjlkMzNlN2JiMjVkNmQxNTU5MjA5MDI0ZWM1ZWE2NzZlZGY1MGQ4N2M4YzBhYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hphm1gys_bJJF9M44jSUZL9_9a1FIEN6te32u-mVbzI)
> 
> 设置后 ![image](https://private-user-images.githubusercontent.com/54365306/334629805-5c91dd95-2acc-4b3d-a164-8c0e13bd68e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NTA1NTksIm5iZiI6MTcxNjk1MDI1OSwicGF0aCI6Ii81NDM2NTMwNi8zMzQ2Mjk4MDUtNWM5MWRkOTUtMmFjYy00YjNkLWExNjQtOGMwZTEzYmQ2OGUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDAyMzczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmYzIxYzA4YjEyNzQxNDNkYTAyOWIwNDA1Zjg4YmI1NmNiNzZjZGRkNjBjN2EyNjkxYWNmZTBmNjI3N2MzMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LrbfCJH8pKVHrb70Gedicy5t0adlU2q7_Ewi-5j16z4) ![image](https://private-user-images.githubusercontent.com/54365306/334629823-964237ec-0cf2-451f-bebf-8a3e5a75f4f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NTA1NTksIm5iZiI6MTcxNjk1MDI1OSwicGF0aCI6Ii81NDM2NTMwNi8zMzQ2Mjk4MjMtOTY0MjM3ZWMtMGNmMi00NTFmLWJlYmYtOGEzZTVhNzVmNGYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDAyMzczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxZDE4NDU1YmI3NDI1OWI4NmE2YTg1ZjVhMWVlMGNjODkxZjFjYTk4MDM3MGM4ZWJlYTg3NDk0MGYwMTQ1ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mii_POk8Fj4Lwf2319kPojHST5Z6AtuquQA2QUgbHH0)

建议方案：页面覆盖组件`t-progress__canvas--circle`类名下宽高样式值。

后续，我补充一个 --td-progress-circle-width 变量，方便调整

**Comment by HQ-YYK** [comment]
额 您的图片裂开看不了 我页面上设置过
.t-progress__canvas--circle{
width: 60rpx !important;
height: 60rpx !important;
} 没生效

**Comment by anlyyao** [comment]
我没放图片～， 我是在你的comment下方'Quote reply'

页面的JSON加一下styleIsolation配置项
```json
{
"styleIsolation": "shared",
}
```

**Comment by HQ-YYK** [comment]
哦好的谢谢
