### ISSUE TITLE
[Search] 右侧按钮点击事件 和 官网文档不一致

### ISSUE THREAD

**Issue by wutianSweet** [Tencent/tdesign-miniprogram#281]
### tdesign-miniprogram 版本

0.6.2

### 重现步骤

官网文档
action-click | ({}) | 点击右侧操作按钮文字时触发

实际中的代码实现为 
this.triggerEvent('cancel');

所以到底是以哪个为准？？

**Comment by LeeJim** [comment]
确实有问题，先补充支持一下 `action-click` 事件吧。后续择期移除 `cancel` 事件。
