### ISSUE TITLE
t-input  不能实现双向绑定 页面值无法更改

### ISSUE THREAD

**Issue by dolly1015** [Tencent/tdesign-miniprogram#2810]
### tdesign-miniprogram 版本

^1.2.9

### 重现步骤

![CleanShot 2024-05-28 at 16 52 12@2x](https://github.com/Tencent/tdesign-miniprogram/assets/53116907/a9b61938-3d04-4aa6-a7d4-77dba9a699c2)
![CleanShot 2024-05-28 at 16 54 06@2x](https://github.com/Tencent/tdesign-miniprogram/assets/53116907/b810d7fd-3def-4aeb-b143-a791cedeb895)
![CleanShot 2024-05-28 at 16 56 11](https://github.com/Tencent/tdesign-miniprogram/assets/53116907/3c64ebbe-a7f6-48cc-9f0a-1b71f9de1cd5)

t-input不支持双向绑定 又没有input事件 现在是金额输入限制 只能输入数字和小数点 type=number只针对手机默认输入法
若用户用第三方输入法就限制不了 只能写事件去限制
当我使用change事件 这样去写的时候 打印paidPrice这个字段确实是空串了 但是页面上输入的内容还在

### 期望结果

页面值根据赋值变化

### 实际结果

页面值未发生变化

### 基础库版本

3.4.4

**Comment by anlyyao** [comment]
@dolly1015 小程序中设置/更新数据依赖 setData 函数

**Comment by dolly1015** [comment]
> @dolly1015 小程序中设置/更新数据依赖 setData 函数

你好 谢谢你的回答 我使用的是uniapp 没有setData函数 最终通过修改源码 自定义了一个props解决的
