### ISSUE TITLE
[Upload 上传] 点击文件上传无任何响应

### ISSUE THREAD

**Issue by lixunhui** [Tencent/tdesign-miniprogram#2819]
### tdesign-miniprogram 版本

1.4.1

### 重现步骤

<view style="width: 100%;">
	<view class="wrapper">
		<t-upload
		  disabled
		  mediaType="{{['video','image']}}"
		  max="{{1}}"
		  files="{{fileList}}"
		  bind:add="handleAdd"
		  bind:remove="handleRemove"
		>
		</t-upload>
	  </view>
</view>
上述实现中，handleAdd方法无响应

### 期望结果

能够处理上传照片

### 实际结果

点击无响应

### 基础库版本

3.4.4

### 补充说明

**急！加急！非常急！**

**Comment by lixunhui** [comment]
![image](https://github.com/Tencent/tdesign-miniprogram/assets/4917509/63304008-ac87-494a-ad1c-78fe6d0beae8)
代码截图

**Comment by zxhans** [comment]
你这个禁用了 
![image](https://github.com/user-attachments/assets/9576e6a9-c2ee-494e-9aed-3c5f291cbd77)
