### ISSUE TITLE
[t-tab-bar-item] slot="icon" 是识别不到吗

### ISSUE THREAD

**Issue by eMonkHy** [Tencent/tdesign-miniprogram#2820]
### tdesign-miniprogram 版本

1.4.0

### 重现步骤

```

<t-tab-bar t-class="t-tab-bar" value="{{activity}}" split="{{false}}">
  <block wx:for="{{list}}" wx:key="pagePath">
    <t-tab-bar-item value="{{item.pagePath}}">
      <view slot="icon" class="tabbar-icon">
        <image src="{{item.pagePath!=activity?item.iconPath:item.selectedIconPath}}" />
      </view>
      {{item.text}}
    </t-tab-bar-item>
  </block>
</t-tab-bar>
```

slot并不能识别icon

![1717049493480](https://github.com/Tencent/tdesign-miniprogram/assets/50975886/2bb74fcf-eb63-48ab-9a68-f5b1ee7eb053)
![1717049519801](https://github.com/Tencent/tdesign-miniprogram/assets/50975886/a2d1ca83-b5af-4ce7-8e27-e06c07231604)

### 基础库版本

3.4.2

**Comment by anlyyao** [comment]
icon 设置为 true 。 后期我们优化一下～
