### ISSUE TITLE
[按钮] 新建项目直接引入组件会报错。

### ISSUE THREAD

**Issue by wzroad** [Tencent/tdesign-miniprogram#2829]
### tdesign-miniprogram 版本

1.4.1

### 重现链接

https://developers.weixin.qq.com/s/PkHetBmJ7QRv

### 重现步骤

1. 引入代码片段
2. 拉取依赖
3. 构建 npm
4. 重启开发者工具

### 期望结果

能正常使用组件。

### 实际结果

不能正常使用组件
出现如下报错：
![20240531231122](https://github.com/Tencent/tdesign-miniprogram/assets/127473365/54d68c4b-ab3d-4d02-8aa7-996d25306250)

### 基础库版本

3.4.0

**Comment by anlyyao** [comment]
@wzroad 感谢反馈，感谢提供代码片段方便我们快速定位问题，

你的问题在于开发工具上没有勾选“将JS编译成ES5”~，如下所示

<img width="1231" alt="企业微信截图_ba07067a-1fd9-4161-a250-59487c49c327" src="https://github.com/Tencent/tdesign-miniprogram/assets/51158141/a6e42ab2-527c-479c-99aa-3941768aa2fa">
