### ISSUE TITLE
[navbar] t-navbar__placeholder 占位高度有问题

### ISSUE THREAD

**Issue by laozhengfanle** [Tencent/tdesign-miniprogram#2835]
### tdesign-miniprogram 版本

1.4.1

### 补充说明

这是占位的样式：
```
.t-navbar__placeholder {
    height: var(--td-navbar-height, 48px);
    padding-top: var(--td-navbar-padding-top, 20px);
    position: relative;
    box-sizing: border-box;
}
```
这个写法会导致占位不够，要么修改成 box-sizing:content-box; 要么 height = --td-navbar-height + --td-navbar-padding-top

**Comment by anlyyao** [comment]
@laozhengfanle 收到反馈，有具体的问题截图嘛？ 我这边跟进看看

**Comment by anlyyao** [comment]
> @laozhengfanle 收到反馈，有具体的问题截图嘛？ 我这边跟进看看

是不是 skyline 环境？

**Comment by jby0107** [comment]
@laozhengfanle @anlyyao 
看看是否是这个问题：
<img width="615" alt="截屏2024-06-13 10 31 17" src="https://github.com/Tencent/tdesign-miniprogram/assets/50822648/1ecfe0dc-dc30-4fed-a645-76b9c47893b6">
t-navbar在fixed为true时使用的占位元素没有明确box-sizing，webview默认content-box显示没问题
  
<img width="313" alt="截屏2024-06-13 10 22 43" src="https://github.com/Tencent/tdesign-miniprogram/assets/50822648/4884c740-01e2-4d8d-94bf-96ccc8ee6c0e">

如果默认content-box被覆盖，比如做了全局reset border-box，就会导致占位元素高度不够，遮挡内容：
<img width="333" alt="截屏2024-06-13 10 22 09" src="https://github.com/Tencent/tdesign-miniprogram/assets/50822648/55236b6a-d104-4d90-9c0a-79c7bc4f7ffb">

**Comment by anlyyao** [comment]
> @laozhengfanle @anlyyao 看看是否是这个问题： <img alt="截屏2024-06-13 10 31 17" width="615" src="https://private-user-images.githubusercontent.com/50822648/339189280-1ecfe0dc-dc30-4fed-a645-76b9c47893b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MjM1MzUsIm5iZiI6MTcxODYyMzIzNSwicGF0aCI6Ii81MDgyMjY0OC8zMzkxODkyODAtMWVjZmUwZGMtZGMzMC00ZmVkLWE2NDUtNzZiOWM0Nzg5M2I2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDExMjAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyYzUwNzA1NjUzYjVjNzBmNzljZDI0Njg2NzFiOWJlY2UxZjZlMGViYmI0ZjM3MjA5MWVjOGI5OWJmNDUyN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8ENPPjobI118msGjVPcqt-zHcO4umLghztACNZDL_84"> t-navbar在fixed为true时使用的占位元素没有明确box-sizing，webview默认content-box显示没问题
> 
> <img alt="截屏2024-06-13 10 22 43" width="313" src="https://private-user-images.githubusercontent.com/50822648/339190728-4884c740-01e2-4d8d-94bf-96ccc8ee6c0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MjM1MzUsIm5iZiI6MTcxODYyMzIzNSwicGF0aCI6Ii81MDgyMjY0OC8zMzkxOTA3MjgtNDg4NGM3NDAtMDFlMi00ZDhkLTk0YmYtOTZjY2M4ZWU2YzBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDExMjAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3YTEyM2E4MzI5OWM3NGQxZTU0NDg3ZWNhYjFiYzQxNWZmZDI4MTY0MmJkNTlkY2JmZTM4NjUwZDQwNWVhOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s3NUKqsuJ1Pj5mvF40vU_xThjkhFy7P2k23NS-rGioo">
> 如果默认content-box被覆盖，比如做了全局reset border-box，就会导致占位元素高度不够，遮挡内容： <img alt="截屏2024-06-13 10 22 09" width="333" src="https://private-user-images.githubusercontent.com/50822648/339191106-55236b6a-d104-4d90-9c0a-79c7bc4f7ffb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MjM1MzUsIm5iZiI6MTcxODYyMzIzNSwicGF0aCI6Ii81MDgyMjY0OC8zMzkxOTExMDYtNTUyMzZiNmEtZDEwNC00ZDkwLTljMGEtNzljN2JjNGY3ZmZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDExMjAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkYzZkMWJkZDM0Y2NlZDc3NjY3ZGFhNTViMWQxNjgyMDQ1NTkzZGUyMWUyMWVkMzVlMWM5ZDRhNTk1NjIzZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tmKYbpwhlTHJ5KzdUVrsAQ4o-w0JKia-vlDKz4W_lNI">

感谢反馈，确实存在你这个场景的问题，我先显示的指定 box-sizing
