### ISSUE TITLE
[ActionSheet] grid模式只加了icon有关于image的警告

### ISSUE THREAD

**Issue by HQ-YYK** [Tencent/tdesign-miniprogram#2837]
### tdesign-miniprogram 版本

^1.4.1

### 重现步骤

export const resOperationItemsData = [
  {
    label: '预览',
    icon: 'browse',
  },
  {
    label: '下载',
    icon: 'download',
  },
];    
ActionSheet.show({
      theme: ActionSheetTheme.Grid,
      selector: '#resource-sheet',
      context: this,
      items: resOperationItemsData ,
    });
    
    
    警告信息[Component] property "image" of "miniprogram_npm/tdesign-miniprogram/grid-item/grid-item" received type-uncompatible value: expected <String> but get null value. Use empty string instead.

### 基础库版本

3.4.5

**Comment by anlyyao** [comment]
@HQ-YYK 收到反馈，我们优化一下～
