### ISSUE TITLE
[Picker 选择器] 控制台出现警告

### ISSUE THREAD

**Issue by pyzworld** [Tencent/tdesign-miniprogram#2839]
### tdesign-miniprogram 版本

1.4.1

### 重现链接

https://tdesign.tencent.com/miniprogram/components/picker

### 重现步骤

官方示例
功能正常 不影响使用，只有在2.24.4调试基础库往下一点，有这个警告。更低的版本则没有这个警告。
切换到2.25.4以上基础库则没有这个警告。

![微信截图_20240603223339](https://github.com/Tencent/tdesign-miniprogram/assets/1388386/10a1f162-cdb7-4dc7-99c2-6278044d75d9)

### 期望结果

消除警告

### 基础库版本

2.24.4

**Comment by anlyyao** [comment]
感谢反馈，这个告警非TDesign组件问题，也不是bug。实际上，框架在 2.25.2 中正式移除了关于 slot not found 的告警
 see https://developers.weixin.qq.com/miniprogram/dev/framework/release/
