### ISSUE TITLE
[Dialog] 隐私授权时确认按钮无法透传 bindagreeprivacyauthorization

### ISSUE THREAD

**Issue by xiongjinchao** [Tencent/tdesign-miniprogram#2845]
### tdesign-miniprogram 版本

1.4.0

### 重现步骤

```
<t-dialog
  visible="{{!showPrivacy}}"
  title="用户隐私保护提示"
  confirm-btn="{{ { tId:'agree-btn', content: '确定', variant: 'base', openType: 'agreePrivacyAuthorization',bindagreeprivacyauthorization: 'onAgreePrivacyAuthorization' } }}"
  cancel-btn="取消"
  bind:confirm="closeDialog"
  bind:cancel="closeDialog"
>
  <view slot="content">感谢您使用小程序，您使用小程序前应当阅井同意<text style="color:#0052d9" bindtap="onOpenPrivacyContract">《XXX小程序隐私保护指引》</text>如果你同意该指引，请点击“同意”开始使用本小程序</view>
  <t-image slot="top" t-class="dialog-image" src="https://tdesign.gtimg.com/mobile/demos/dialog1.png" />
</t-dialog>
```

这样不无法回调`onAgreePrivacyAuthorization`如果直接使用按钮则可以，或者当作SLOT 放入Dialog中 
```
<t-button slot="cancel-btn" theme="light" size="large">拒绝</t-button>
  <t-button slot="confirm-btn" theme="primary" size="large" open-type="agreePrivacyAuthorization" bindagreeprivacyauthorization="onAgreePrivacyAuthorization">同意</t-button>
```

### 期望结果

在wxml中Dialog可以透传按钮属性bindagreeprivacyauthorization，点击按钮时能响应bindagreeprivacyauthorization对应的事件

### 实际结果

Dialog中点确认时无法关闭，无法调起bindagreeprivacyauthorization对应的事件

### 基础库版本

3.4.5

**Comment by anlyyao** [comment]
@xiongjinchao  试试这样写，```js
confirmBtn: {
          openType: 'agreePrivacyAuthorization',
          content: '用户隐私协议',
          bindagreeprivacyauthorization({ detail }) {
            console.log('----', detail);
          },
        },
```

**Comment by jwang0512** [comment]
> [@xiongjinchao](https://github.com/xiongjinchao) 试试这样写
> 
> confirmBtn: {
>           openType: 'agreePrivacyAuthorization',
>           content: '用户隐私协议',
>           bindagreeprivacyauthorization({ detail }) {
>             console.log('----', detail);
>           },
>         },

这样的话this就不对了吧，比如在bindagreeprivacyauthorization()里面调用setData({})就不行了
