### ISSUE TITLE
[Tab选项卡] 初始化显示, 第一个tab的高亮下划线的定位偏移量错误, 经过手动切换tab后下划线的位置会恢复正常

### ISSUE THREAD

**Issue by zhelingwang** [Tencent/tdesign-miniprogram#2850]
### tdesign-miniprogram 版本

"tdesign-miniprogram": "^1.0.0"

### 重现链接

https://tdesign.tencent.com/miniprogram/components/tabs?tab=demo

### 重现步骤

我看官网首页第一个示例就可以复现, 是同样的问题

### 期望结果

下划线初始显示位置正常居中

### 实际结果

下划线初始显示位置偏左

### 基础库版本

2.23.1

### 补充说明

![image](https://github.com/Tencent/tdesign-miniprogram/assets/22769967/3c95fdb5-2891-4107-975f-1be2f413f0ec)
![image](https://github.com/Tencent/tdesign-miniprogram/assets/22769967/9861c257-a5af-4d21-9044-9782d2854c36)
如图

**Comment by anlyyao** [comment]
官网我这边看着是这样的：

> <img width="200" alt="截屏2024-06-06 14 24 01" src="https://github.com/Tencent/tdesign-miniprogram/assets/51158141/036b7b2a-b7c4-4c46-bee3-d5804fb3d885">


直接贴你的代码 👀 ？ 包括css 那部分～

**Comment by zhelingwang** [comment]
```
<view class="home-page-container">
  <view class="home-page-tabs">
    <t-tabs t-class="t-tabs" t-class-active="tabs-external__active" t-class-item="tabs-external__item" defaultValue="{{0}}" space-evenly="{{false}}" bind:change="tabChangeHandle" swipeable="{{true}}" sticky="{{true}}">
      <t-tab-panel wx:key="0" label="{{tabList[0].text || ''}}" value="{{tabList[0].key}}">
        <text class="topTips">饭来张口~免费配送. 有空堂食, 没空机器人派送上楼. </text>
        <view class="goodsList">
          <goods-list-new data-id="1" bindtap="navToActivityDetail" data="{{ tabEatList[0] }}" />
          <goods-list-new bindtap="navToActivityDetail" data="{{ tabEatList[1] }}" />
          <goods-list-new bindtap="navToActivityDetail" data="{{ tabEatList[2] }}" />
        </view>
      </t-tab-panel>

      <t-tab-panel wx:key="1" label="{{tabList[1].text || ''}}" value="{{tabList[1].key}}">
        <text class="topTips">楼内下午茶+小骑手</text>
        <view class="goodsList">
          <goods-list-new data="{{ tabDrinkList[0] }}" />
          <goods-list-new data="{{ tabDrinkList[1] }}" />
        </view>
      </t-tab-panel>

      <t-tab-panel wx:key="2" label="{{tabList[2].text || ''}}" value="{{tabList[2].key}}">
        <text class="topTips">外卖闪送 todo </text>
      </t-tab-panel>
    </t-tabs>

  </view>
</view>
```

css部分: 

```

.home-page-container .t-tabs {
  background: #f4f8ff !important;
}

.home-page-container .t-tabs .t-tabs-nav {
  background-color: transparent;
  line-height: 80rpx;
  font-size: 28rpx;
  color: #333;
}

.home-page-container .t-tabs .t-tabs-scroll {
  border: none !important;
}

/* 半个字 */
.home-page-container .tab.order-nav .order-nav-item.scroll-width {
  min-width: 165rpx;
}
.home-page-container .tab .order-nav-item.active {
  color: #fa550f !important;
}

.home-page-container .tab .bottom-line {
  border-radius: 4rpx;
}

.home-page-container .tab .order-nav-item.active .bottom-line {
  background-color: #fa550f !important;
}

.home-page-container .tabs-external__item {
  /* color: #666 !important; */
  font-size: 28rpx;
  background-color: #f4f8ff !important;
}

.home-page-container .tabs-external__active {
  color: #333333 !important;
  font-size: 32rpx;
}

.home-page-container .tabs-external__track {
  /* background-color: #fa4126 !important; */
  height: 6rpx !important;
  border-radius: 4rpx !important;
  width: 48rpx !important;
}

.t-tabs.t-tabs--top .t-tabs__item,
.t-tabs.t-tabs--bottom .t-tabs__item {
  height: 86rpx !important;
}
.t-tabs__nav--top {
  background-color: #f4f8ff !important;
  width: 100%;
}


.home-page-container .goods-list-container {
  background: #f5f5f5 !important;
  margin-top: 16rpx;
}

.home-page-tabs {
  --td-tab-nav-bg-color: transparent;
  --td-tab-border-color: transparent;
  --td-tab-item-color: #666;
  --td-tab-track-color: #41b881;
}
```

**Comment by zhelingwang** [comment]
> 官网我这边看着是这样的：
> 
> > <img alt="截屏2024-06-06 14 24 01" width="200" src="https://private-user-images.githubusercontent.com/51158141/337144181-036b7b2a-b7c4-4c46-bee3-d5804fb3d885.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NTU1OTYsIm5iZiI6MTcxNzY1NTI5NiwicGF0aCI6Ii81MTE1ODE0MS8zMzcxNDQxODEtMDM2YjdiMmEtYjdjNC00YzQ2LWJlZTMtZDU4MDRmYjNkODg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDA2MjgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiNmRkZTFhNjIxMzA1MDIyYzc3OTc5ZGUwNjE0ZmU3MWZkOWU2NjU2ZDY2YjAzMTMyNWE5ZTAxYzZjMmU4ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._w51ZAOdcWOyg1AxNi8PP9jIET3jFolsSlVd05Gm7ZE">
> 
> 直接贴你的代码 👀 ？ 包括css 那部分～

![image](https://github.com/Tencent/tdesign-miniprogram/assets/22769967/7c5d1869-b326-418d-86f3-f3f763adad80)
我这边的官网刷新第一次进来是有问题, chrome浏览器, 代码在上面贴了

**Comment by anlyyao** [comment]
我先给你录屏看看官网上的一个整体表现，中间的动画是符合预期的（官网和真机表现一致）：


https://github.com/Tencent/tdesign-miniprogram/assets/51158141/ce820412-8104-4e86-877f-4aaf30b1da4f

**Comment by anlyyao** [comment]
> 我先给你录屏看看官网上的一个整体表现，中间的动画是符合预期的（官网和真机表现一致）：
> 
>  2024-06-06.15.31.22.mov

然后我copy你的代码看看，稍等给你反馈～

**Comment by anlyyao** [comment]
@zhelingwang  感觉你可能和 #2793 是同一个问题🤔，改问题已修复，明天发版本会带上，辛苦明天更新版本再试试

**Comment by anlyyao** [comment]
duplicate #2793

**Comment by zhelingwang** [comment]
> @zhelingwang 感觉你可能和 #2793 是同一个问题🤔，该问题已修复，明天发版本会带上，辛苦明天更新版本再试试

好的, 谢谢, 辛苦啦

**Comment by anlyyao** [comment]
> > @zhelingwang 感觉你可能和 #2793 是同一个问题🤔，该问题已修复，明天发版本会带上，辛苦明天更新版本再试试
> 
> 好的, 谢谢, 辛苦啦

已发布1.4.2，辛苦更新版本试试，如果还有问题，可以继续反馈～

**Comment by zhelingwang** [comment]
> > > @zhelingwang 感觉你可能和 #2793 是同一个问题🤔，该问题已修复，明天发版本会带上，辛苦明天更新版本再试试
> > 
> > 
> > 好的, 谢谢, 辛苦啦
> 
> 已发布1.4.2，辛苦更新版本试试，如果还有问题，可以继续反馈～
![20240612-102718](https://github.com/Tencent/tdesign-miniprogram/assets/22769967/aac62723-9920-4bb7-b86d-b30b97022a82)
我把页面精简化, 多余的其他页面元素和样式类都移除了, 升级了版本, 好像还是有问题

**Comment by zhelingwang** [comment]
![test](https://github.com/Tencent/tdesign-miniprogram/assets/22769967/baa2598f-d48c-48bc-b129-9a43f51ff2b1)
我把页面精简化, 多余的其他页面元素和样式类都移除了, 升级了版本, 好像还是有问题

**Comment by anlyyao** [comment]
@zhelingwang 更新版本后有重新构建吗？ 

1.4.2版本未能复现你的问题。这里有一个代码片段，你在本地运行试试  https://developers.weixin.qq.com/s/t2a4ETme7KRx

**Comment by zhelingwang** [comment]
> > > @zhelingwang 感觉你可能和 #2793 是同一个问题🤔，该问题已修复，明天发版本会带上，辛苦明天更新版本再试试
> > 
> > 
> > 好的, 谢谢, 辛苦啦
> 
> 已发布1.4.2，辛苦更新版本试试，如果还有问题，可以继续反馈～

![20240612-104220](https://github.com/Tencent/tdesign-miniprogram/assets/22769967/69c25954-d8ae-4fb7-b265-92a5cf53c685)

我对页面代码进行了缩减, t-tab-panel 的 label 属性中注入变量时重新编译就会复现, 感觉像是label的值影响了宽度, 进而初始化计算偏移时有误

**Comment by anlyyao** [comment]
> > > > @zhelingwang 感觉你可能和 #2793 是同一个问题🤔，该问题已修复，明天发版本会带上，辛苦明天更新版本再试试
> > > 
> > > 
> > > 好的, 谢谢, 辛苦啦
> > 
> > 
> > 已发布1.4.2，辛苦更新版本试试，如果还有问题，可以继续反馈～
> 
> ![20240612-104220](https://private-user-images.githubusercontent.com/22769967/338804797-69c25954-d8ae-4fb7-b265-92a5cf53c685.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNjA4MTEsIm5iZiI6MTcxODE2MDUxMSwicGF0aCI6Ii8yMjc2OTk2Ny8zMzg4MDQ3OTctNjljMjU5NTQtZDhhZS00ZmI3LWIyNjUtOTJhNWNmNTNjNjg1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAyNDgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NzczZmQ2MTgzNDI2ZmM3ZjZiNWE5N2YwYjI5MjM4NzI4NjgwZTQwNjUxNjFhMDdhMTZkZTkwMTc1YThjZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eZ8g6juOoJe7jBjz-umwWtC7cVSs5wZuLY6RP91xl20) [ ![20240612-104220](https://private-user-images.githubusercontent.com/22769967/338804797-69c25954-d8ae-4fb7-b265-92a5cf53c685.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNjA4MTEsIm5iZiI6MTcxODE2MDUxMSwicGF0aCI6Ii8yMjc2OTk2Ny8zMzg4MDQ3OTctNjljMjU5NTQtZDhhZS00ZmI3LWIyNjUtOTJhNWNmNTNjNjg1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAyNDgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NzczZmQ2MTgzNDI2ZmM3ZjZiNWE5N2YwYjI5MjM4NzI4NjgwZTQwNjUxNjFhMDdhMTZkZTkwMTc1YThjZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eZ8g6juOoJe7jBjz-umwWtC7cVSs5wZuLY6RP91xl20) ](https://private-user-images.githubusercontent.com/22769967/338804797-69c25954-d8ae-4fb7-b265-92a5cf53c685.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNjA4MTEsIm5iZiI6MTcxODE2MDUxMSwicGF0aCI6Ii8yMjc2OTk2Ny8zMzg4MDQ3OTctNjljMjU5NTQtZDhhZS00ZmI3LWIyNjUtOTJhNWNmNTNjNjg1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAyNDgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NzczZmQ2MTgzNDI2ZmM3ZjZiNWE5N2YwYjI5MjM4NzI4NjgwZTQwNjUxNjFhMDdhMTZkZTkwMTc1YThjZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eZ8g6juOoJe7jBjz-umwWtC7cVSs5wZuLY6RP91xl20) [ ](https://private-user-images.githubusercontent.com/22769967/338804797-69c25954-d8ae-4fb7-b265-92a5cf53c685.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNjA4MTEsIm5iZiI6MTcxODE2MDUxMSwicGF0aCI6Ii8yMjc2OTk2Ny8zMzg4MDQ3OTctNjljMjU5NTQtZDhhZS00ZmI3LWIyNjUtOTJhNWNmNTNjNjg1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAyNDgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NzczZmQ2MTgzNDI2ZmM3ZjZiNWE5N2YwYjI5MjM4NzI4NjgwZTQwNjUxNjFhMDdhMTZkZTkwMTc1YThjZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eZ8g6juOoJe7jBjz-umwWtC7cVSs5wZuLY6RP91xl20)
> 
> 我对页面代码进行了缩减, t-tab-panel 的 label 属性中注入变量时重新编译就会复现, 感觉像是label的值影响了宽度, 进而初始化计算偏移时有误

提供一个可复现代码片段？？我来看看🤔

**Comment by anlyyao** [comment]
@zhelingwang 你之前贴的代码， 缺了js部分？ 请确保我能本地运行你的代码片段～

**Comment by zhelingwang** [comment]
@anlyyao 我先试试你上面提供的代码片段能不能复现

**Comment by zhelingwang** [comment]
@anlyyao 找到原因了, 升级后的组件本身没有问题的

**Comment by anlyyao** [comment]
> @anlyyao 找到原因了, 升级后的组件本身没有问题的

😠 问题是啥？

**Comment by zhelingwang** [comment]
> > @anlyyao 找到原因了, 升级后的组件本身没有问题的
> 
> 😠 问题是啥？
![image](https://github.com/Tencent/tdesign-miniprogram/assets/22769967/54d24059-cff9-4303-86e2-05b8181baa2d)
加个 pageLoading 判断数据是否已返回即可, 问题就解决了, 这么看的化原因应该是初始化所应用的数据源为空导致的问题.
然后我又回退到版本 1.4.1 好像也没有复现了, 和 #2793 应该不是一个问题

**Comment by anlyyao** [comment]
@zhelingwang 感谢反馈，确实和 2793 不是同一个问题。我稍微优化了一下，支持动态 label， 后面可以再试试新版本～

**Comment by zhelingwang** [comment]
> @zhelingwang 感谢反馈，确实和 2793 不是同一个问题。我稍微优化了一下，支持动态 label， 后面可以再试试新版本～

Nice
