### ISSUE TITLE
[tabbar] 深色模式下颜色错误的问题

### ISSUE THREAD

**Issue by Nero978** [Tencent/tdesign-miniprogram#2856]
### tdesign-miniprogram 版本

1.4.2

### 重现步骤

在深色模式下，通过在`app.wxss`中引入npm包内的`miniprogram_npm/tdesign-miniprogram/common/style/theme/_index.wxss`
（design token文件），`tabbar`的颜色定义有误。
![image](https://github.com/Tencent/tdesign-miniprogram/assets/63546553/7c1965b6-f86b-439f-9fd9-ef6608955dab)

原因是现阶段的token文件内定义的是`page`选择器。
<img width="624" alt="83acfeb738db3acb1d40fbc75349207" src="https://github.com/Tencent/tdesign-miniprogram/assets/63546553/0b61d4e2-dd6f-47b8-9174-2b5deeb83445">

而`tabbar`是一个特殊的组件，按照微信的文档（https://developers.weixin.qq.com/miniprogram/dev/framework/ability/custom-tabbar.html ），应该定义在`custom-tab-bar`文件夹内，这将导致`tabbar`渲染在`page`标签以外，造成深色模式下`tabbar`颜色不正确的问题。可以考虑在token文件中将加一个`view`标签解决这个问题。
![image](https://github.com/Tencent/tdesign-miniprogram/assets/63546553/c4efc0a9-aa3c-41ff-b3e5-692442043602)

### 期望结果

tabbar能够正确显示深色模式下的颜色

### 基础库版本

3.4.1

**Comment by anlyyao** [comment]
@Nero978 感谢反馈和提供修改方案～

但我可能不太倾向在 app.wxss 中通过增加 view 标签选择器的方式来规避 custom-tab-bar 、或 root-portal 组件在 webview模式下无法继承 page选择器样式的问题。
- 不推荐标签选择器
-  优先级view > page，这意味着二次覆盖组件库样式必须大于等于view

综合考虑，我更倾向新增一个 `.page` class选择器，在custom-tab-bar 或者 root-portal 组件等特殊场景中，主动引入保证design token能正确被继承

使用上大概是：
```
// 开启虚拟节点
<view class="page" >
  <t-tab-bar  />
</view>

// 不开启虚拟节点
<t-tab-bar class="page" />
```

**Comment by jarmywang** [comment]
#2857 涉及文档补充
