### ISSUE TITLE
t-radio-group  disabled无效

### ISSUE THREAD

**Issue by zhyit** [Tencent/tdesign-miniprogram#2863]
### tdesign-miniprogram 版本

1.4.2

### 重现步骤

> ### 🤔 这个 PR 的性质是？
> * [x]  日常 bug 修复
> * [ ]  新特性提交
> * [ ]  文档改进
> * [ ]  演示代码改进
> * [ ]  组件样式/交互改进
> * [ ]  CI/CD 改进
> * [ ]  重构
> * [ ]  代码风格优化
> * [ ]  测试用例
> * [ ]  分支合并
> * [ ]  其他
> 
> ### 🔗 相关 Issue
> https://github.com/Tencent/tdesign-miniprogram/pull/2643
> ### 💡 需求背景和解决方案
> ### 📝 更新日志
> * fix(组件名称): 处理问题或特性描述 ...
> * [ ]  本条 PR 不需要纳入 Changelog
> 
> ### ☑️ 请求合并前的自查清单
> ⚠️ 请自检并全部**勾选全部选项**。⚠️
> 
> * [ ]  文档已补充或无须补充
> * [ ]  代码演示已提供或无须提供
> * [ ]  TypeScript 定义已补充或无须补充
> * [ ]  Changelog 已提供或无须提供

### 期望结果

> 希望disabled生效（包括动态生效）
```
<t-radio-group bind:change="onChange" value="{{current}}" options="{{options}}" disabled="{{true}}" />
```

### 实际结果

> disabled在下面的情况生效
```
<t-radio-group defaultValue="radio1" disabled="{{true}}">
  <t-radio value="radio1" label="单选" />
  <t-radio value="radio2" label="单选" />
</t-radio-group>
```
> 但是在下面的情况就没有生效
```
<t-radio-group bind:change="onChange" value="{{current}}" options="{{options}}" disabled="{{true}}" />
```

### 基础库版本

3.3.4

**Comment by anlyyao** [comment]
@zhyit 我这边测试两种方式都有效哦，包括disabled动态变更～ （只是选中态的禁用样式有问题，样式问题我额外处理。）

**Comment by zhyit** [comment]
> @zhyit 我这边测试两种方式都有效哦，包括disabled动态变更～ （只是选中态的禁用样式有问题，样式问题我额外处理。）
> 
> 我补充一下代码片段，你可以先试试：https://developers.weixin.qq.com/s/H52mzVmy7lRX

谢谢，我试过了，真的可以，我再看看我的项目是什么问题吧

**Comment by anlyyao** [comment]
@zhyit 更新版本后 你有重新构建npm吗？
