### ISSUE TITLE
【CheckTag】可点击的标签demo文件无法点击

### ISSUE THREAD

**Issue by fangwanI** [Tencent/tdesign-miniprogram#2870]
### tdesign-miniprogram 版本

1.4.2

### 重现步骤

<view class="wrapper">
  <block wx:for="{{items}}" wx:key="index">
    <view class="block">
      <text>{{item}}</text>
      <t-check-tag class="margin-16" size="large" variant="{{item}}" content="{{ ['已选中态', '未选中态'] }}" />
      <t-check-tag
        class="margin-16"
        default-checked
        size="large"
        variant="{{item}}"
        content="{{ ['已选中态', '未选中态'] }}"
      />
    </view>
  </block>
</view>

### 期望结果

点击时会有选中效果

### 实际结果

demo中并没有实现该效果

### 基础库版本

3.1.5

**Comment by anlyyao** [comment]
@fangwanI 哪个组件？ 麻烦按照规范提问，便于我们快速定位问题～

**Comment by fangwanI** [comment]
> > @fangwanI 哪个组件？ 麻烦按照规范提问，便于我们快速定位问题～
> 
> check-tag？？？？
tdesign for 小程序 t-check-tag 组件 你们写的可点击的标签的demo 这个组件点击后，没有选中状态，我看for vue 是正常的，就小程序不行
