### ISSUE TITLE
[toast] 找不到模块“tdesign-miniprogram/toast/index”或其相应的类型声明。

### ISSUE THREAD

**Issue by matianhe3** [Tencent/tdesign-miniprogram#2878]
### tdesign-miniprogram 版本

1.4.2

### 重现步骤

import Toast from "tdesign-miniprogram/toast/index";

### 期望结果

小程序可以运行, 但是开发者工具报错.

### 实际结果

![image](https://github.com/Tencent/tdesign-miniprogram/assets/24929062/ae3abc41-29fd-4919-b64c-22d619f1eb2b)

### 基础库版本

3.4.6

### 补充说明

![image](https://github.com/Tencent/tdesign-miniprogram/assets/24929062/6a45bec0-ffda-4d3f-ab27-bdebba10a6d5)
按照示例复制代码

**Comment by anlyyao** [comment]
@matianhe3 开发工具上有勾选“将JS编译成ES5”选项吗

**Comment by matianhe3** [comment]
> @matianhe3 开发工具上有勾选“将JS编译成ES5”选项吗

勾选了 
![image](https://github.com/Tencent/tdesign-miniprogram/assets/24929062/57339da4-f926-496b-83f1-7d5534ec1945)

**Comment by anlyyao** [comment]
@matianhe3 https://developers.weixin.qq.com/s/l0azMimf7CSu 这里有个toast组件示例的代码片段，你导入开发者工具试试

**Comment by matianhe3** [comment]
> @matianhe3 https://developers.weixin.qq.com/s/l0azMimf7CSu 这里有个toast组件示例的代码片段，你导入开发者工具试试
> 
> > npm i -> 构建npm包

有没有typescript版的, 打开看是js的.

**Comment by anlyyao** [comment]
> > @matianhe3 https://developers.weixin.qq.com/s/l0azMimf7CSu 这里有个toast组件示例的代码片段，你导入开发者工具试试
> > > npm i -> 构建npm包
> 
> 有没有typescript版的, 打开看是js的.

没有本质区别

**Comment by matianhe3** [comment]
> > > @matianhe3 https://developers.weixin.qq.com/s/l0azMimf7CSu 这里有个toast组件示例的代码片段，你导入开发者工具试试
> > > > npm i -> 构建npm包
> > 
> > 
> > 有没有typescript版的, 打开看是js的.
> 
> 没有本质区别

代码片段没有报错提示

**Comment by anlyyao** [comment]
@matianhe3  所以需要你提供一个能复现报错提示的代码片段给我，可以基于上面的片段链接修改或者新建代码片段，重新提供链接

**Comment by matianhe3** [comment]
> @matianhe3 所以需要你提供一个能复现报错提示的代码片段给我，可以基于上面的片段链接修改或者新建代码片段，重新提供链接

https://developers.weixin.qq.com/s/UQqPzsmA7oSf

**Comment by anlyyao** [comment]
> > @matianhe3 所以需要你提供一个能复现报错提示的代码片段给我，可以基于上面的片段链接修改或者新建代码片段，重新提供链接
> 
> https://developers.weixin.qq.com/s/UQqPzsmA7oSf

get到你说的"报错"了 🤦，改成 import { Toast } from 'tdesign-miniprogram';

**Comment by matianhe3** [comment]
> > > @matianhe3 所以需要你提供一个能复现报错提示的代码片段给我，可以基于上面的片段链接修改或者新建代码片段，重新提供链接
> > 
> > 
> > https://developers.weixin.qq.com/s/UQqPzsmA7oSf
> 
> get到你说的"报错"了 🤦，改成 import { Toast } from 'tdesign-miniprogram';

![image](https://github.com/Tencent/tdesign-miniprogram/assets/24929062/d938b8b1-7cdb-45fc-98ad-02fb9926775d)
之前试过这样改, 会编译不成功.
