### ISSUE TITLE
[Picker 选择器] 希望增加过滤条件，以便选项过多的情况下进行检索

### ISSUE THREAD

**Issue by Amouzy** [Tencent/tdesign-miniprogram#2879]
### 这个功能解决了什么问题

Picker 选择器是WeChat MiniProgram中广泛使用的选择器，却只能用于少量选项，一旦选项过多或者选项名字相近的情况下，使用及其不友好。

### 你建议的方案是什么

为解决上述情况，只需要增加一个检索控件在选项列表上方，输入匹配内容且点击检索，通过模糊匹配，从选项列表中刷选出匹配项用于选择，即可以大大提高使用的便捷性。

**Comment by anlyyao** [comment]
@Amouzy 组件本身暂时没有这个计划。但是这个功能你可以通过 header 插槽自己去实现🤔
