### ISSUE TITLE
[t-tab-bar] 支持选中时不高亮及增加 hover 效果

### ISSUE THREAD

**Issue by narukeu** [Tencent/tdesign-miniprogram#2880]
### 这个功能解决了什么问题

对于一些需要固定在底部的功能按钮，不需要在选中时永久高亮，但需要在选中时有 hover 效果，因此提出了这个建议。

### 你建议的方案是什么

同上

**Comment by anlyyao** [comment]
@narukeu 收到反馈，我们这边拉设计同学一起讨论下，会尽快输出结论～

**Comment by RADWIMPS426** [comment]
感谢你的建议～tabbar的常见交互是以保持高亮的样式用于告知用户该模块/视图的状态变化，你所说的点击效果可以通过自行更改样式去定义
