### ISSUE TITLE
[SwipeCell] 在 glass-easel 下无法向右划动

### ISSUE THREAD

**Issue by narukeu** [Tencent/tdesign-miniprogram#2881]
### tdesign-miniprogram 版本

最新

### 重现步骤

在小程序 `app.json` 中开启 `componentFramework": "glass-easel`，然后使用这个组件。

### 期望结果

这个问题出现很久了，也有人提出 issue，但是那个 issue 的解决方案居然是去掉 `glass-easel`，`glass-easel` 现在早就是微信的新项目默认的 `componentFramework` 了，但官方一直没有修复，希望能够尽快修复。

### 基础库版本

3.4.6

**Comment by anlyyao** [comment]
@narukeu 方便问一下使用 glass-easel 的原因是什么呢？

**Comment by anlyyao** [comment]
Duplicate #2668

**Comment by narukeu** [comment]
> @narukeu 方便问一下使用 glass-easel 的原因是什么呢？

微信开发者工具里的模板就用了这个

**Comment by anlyyao** [comment]
1.x阶段SwipeCell组件去适配glass-easel/skyline成本较大，短期内无计划。

这个问题也说明 glass-easel  和 exparser 之间是有差异的，无法做到无痕过度，这个差异需要依赖微信官方抹平。如果你需要使用/依赖 glass-easel 框架的某个特性，可以借助 skyline，实现页面粒度的开启。
