### ISSUE TITLE
[遮罩层]显示异常和丢失

### ISSUE THREAD

**Issue by kustone** [Tencent/tdesign-miniprogram#2885]
### tdesign-miniprogram 版本

1.4.3

### 重现链接

https://tdesign.tencent.com/miniprogram/components/overlay

### 重现步骤

不管是小程序预览还是组件列表里，都无法正常显示遮罩层

**Comment by kustone** [comment]
![微信截图_20240622123625](https://github.com/Tencent/tdesign-miniprogram/assets/43320790/162948a4-33f7-4157-abdf-6f1aec0aa5f5)
 无法正常显示遮罩层，导致相关组件样式均显示异常，直接在TDesign预览就可以，换了几个手机进入预览小程序均存在该问题。

**Comment by suleilei** [comment]
更新后遇上同样问题

**Comment by Anzengsir** [comment]
是的是的，官方预览全部失效

**Comment by pangxiaodun** [comment]
同样的问题。希望能够尽快修复

**Comment by anlyyao** [comment]
感谢各位，已定位到问题，明天补发一个版本～

**Comment by anlyyao** [comment]
@pangxiaodun @kustone @suleilei @Anzengsir 已补发1.4.4版本，辛苦各位更新版本重新试试～
