### ISSUE TITLE
[Input] clearable 值设置无效果

### ISSUE THREAD

**Issue by CrossLee** [Tencent/tdesign-miniprogram#290]
### tdesign-miniprogram 版本

0.7.0

### 重现步骤

以下代码会正常显示清空的 x 按钮，但是点击按钮无反应。

`<t-input label="微信号" placeholder="请输入微信号" model:value="{{wechat}}" clearable="{{true}}"/>`

https://user-images.githubusercontent.com/4584905/160229134-af80f09f-c2b2-4642-801b-14e230040b99.mov

### 期望结果

正确清除 input 内容

### 实际结果

点击无法清空 input

### 框架版本

小程序 2.14.1

**Comment by anlyyao** [comment]
需要绑定一下clear事件，试试` <t-input label="微信号" placeholder="请输入微信号" model:value="{{wechat}}" clearable bind:clear="onClear" />` ， 自定义onClear，`onClear() {
    this.setData({
      wechat: '',
    });
  },`

**Comment by LeeJim** [comment]
确实有问题，我来改一下。
目前 input 是支持双向绑定，但不支持受控写法的。
