### ISSUE TITLE
[t-image] 使用云开发cloud://xxx/test/gxftmtbfnm.png  图片无法显示

### ISSUE THREAD

**Issue by huangyedie** [Tencent/tdesign-miniprogram#2906]
### tdesign-miniprogram 版本

^1.2.5

### 重现步骤

![image](https://github.com/Tencent/tdesign-miniprogram/assets/51399090/a9f542ba-c89b-4c80-9ff8-82d40f40b8f0)
为什么无故拼了地址，导致无法显示。

### 期望结果

正常显示

### 基础库版本

3.4.7

**Comment by anlyyao** [comment]
@huangyedie 参考一下 #1525，看看是不是同一个问题～

**Comment by huangyedie** [comment]
关闭把，我用了微信的Image 组件，src就可以了。

**Comment by anlyyao** [comment]
> > @huangyedie 参考一下 #1525，看看是不是同一个问题～
> > 我看了这个问题。他用了t-avatar 组件，我只用了t-image 这个也不支持吗？
> > t-upload  这个组件都支持  t-image 不支持吗？

t-avatar 的 image 属性支持图片地址就是基于 t-image 组件实现的😅，t-upload 也是基于t-image组件，最后t-image也是基于原生的image组件实现的。
