### ISSUE TITLE
[t-toast] 使用t-toast的loading  在真机上不转圈

### ISSUE THREAD

**Issue by MrSmy** [Tencent/tdesign-miniprogram#2908]
### tdesign-miniprogram 版本

1.2.4

### 重现链接

Toast({ 				theme: 'loading', 				message: '加载中', 				duration: 999999999, 				preventScrollThrough: true 			});

### 重现步骤

`Toast({
theme: 'loading',
message: '加载中',
duration: 999999999,
preventScrollThrough: true
});`

### 期望结果

在手机上也转圈

### 实际结果

在浏览器上转圈 部署到服务器上 拿手机预览不住安全

**Comment by anlyyao** [comment]
@MrSmy 先扫码预览一下官方Toast组件——“加载状态”示例，确认一下是否正常～

需要先说明的是loading的circular类型在 skyline 模式暂不支持，如果使用了skyline，可能确实存在你的问题。

<img width="200" alt="截屏2024-06-25 22 59 57" src="https://github.com/Tencent/tdesign-miniprogram/assets/51158141/637e3bf0-100d-4098-b360-ef08e275c83f">

<img width="313" alt="截屏2024-06-25 22 59 57" src="https://github.com/Tencent/tdesign-miniprogram/assets/51158141/42947c6c-37b4-41f8-bc94-8387e84bd869">

**Comment by MrSmy** [comment]
谢谢 没想到这么快 手机扫码了一下 是正常的  那skyline如何切换？







在 2024-06-25 23:05:49，"Y." ***@***.***> 写道：

@MrSmy 先扫码预览一下官方Toast组件——“加载状态”示例，确认一下是否正常～

需要先说明的是loading的circular类型在 skyline 模式暂不支持，如果使用了skyline，可能确实存在你的问题。

image.png (view on web)2024-06-25.22.59.57.png (view on web)

**Comment by anlyyao** [comment]
@MrSmy emmmm，现阶段来看，只能弃用函数式调用，使用受控的visible属性去控制显隐
```html
<t-toast visible="{{true}}" direction="column" message="带竖向图标">
  <t-loading slot="icon" theme="spinner" size="80rpx" />
</t-toast>
```

**Comment by MrSmy** [comment]
emmm  我这边是H5 不是微信小程序  然后代码上了 还是不行   









在 2024-06-27 11:22:02，"Y." ***@***.***> 写道：

@MrSmy emmmm，现阶段来看，只能弃用函数式调用，使用受控的visible属性去控制显隐

<t-toastvisible="{{true}}" direction="column" message="带竖向图标"><t-loadingslot="icon" theme="spinner" size="80rpx" />
</t-toast>

**Comment by anlyyao** [comment]
> @MrSmy emmmm，现阶段来看，只能弃用函数式调用，使用受控的visible属性去控制显隐
> 
> ```
> <t-toast visible="{{true}}" direction="column" message="带竖向图标">
>   <t-loading slot="icon" theme="spinner" size="80rpx" />
> </t-toast>
> ```

补贴一下效果和代码片段：https://developers.weixin.qq.com/s/indQKgmR7TSV
<img width="1220" alt="企业微信截图_24c11a1c-6b26-457d-97e4-00df5fbdf80c" src="https://github.com/Tencent/tdesign-miniprogram/assets/51158141/f12a637c-cc13-4ec2-9aaa-1d80136a1d00">

**Comment by anlyyao** [comment]
> emmm 我这边是H5 不是微信小程序 然后代码上了 还是不行 在 2024-06-27 11:22:02，"Y." ***@***.***> 写道： @MrSmy emmmm，现阶段来看，只能弃用函数式调用，使用受控的visible属性去控制显隐 <t-toastvisible="{{true}}" direction="column" message="带竖向图标"><t-loadingslot="icon" theme="spinner" size="80rpx" /> </t-toast> — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

tdesign-miniprogram 是一个原生UI组件库，暂时只能保证原生开发功能的完整性
