### ISSUE TITLE
[t-button] 按钮组件在skyline渲染时文字图标没有上下居中

### ISSUE THREAD

**Issue by runoob-coder** [Tencent/tdesign-miniprogram#2912]
### tdesign-miniprogram 版本

1.4.4

### 重现步骤

![WechatIMG3732](https://github.com/Tencent/tdesign-miniprogram/assets/67944641/9afc6aa6-b956-4229-a7d4-4798c561f35f)

t-button组件样式display: inline-flex;
而skyline暂不支持inline-flex，导致在skyline模式下button组件图标和文字错位，没有上下居中。

需手动将t-button组件样式改为display: flex;

### 期望结果

![WechatIMG449](https://github.com/Tencent/tdesign-miniprogram/assets/67944641/ade811eb-3dcf-4182-aba1-89bd855fcf9c)

### 实际结果

![image](https://github.com/Tencent/tdesign-miniprogram/assets/67944641/fdf0d9a8-975f-4797-a798-3f4c2f2196db)

### 基础库版本

3.4.8

### 补充说明

目前解决办法：
需手动将t-button组件样式改为display: flex;
![WechatIMG3735](https://github.com/Tencent/tdesign-miniprogram/assets/67944641/020641d3-ee9d-48b2-bca9-cd91abe53fd6)

**Comment by runoob-coder** [comment]
补充内容：

在官方的组件示例小程序中，skyline模式下复现上述问题：

![IMG_6194](https://github.com/Tencent/tdesign-miniprogram/assets/67944641/f39937b3-8154-4f15-8ce0-c64d1766e0dc)

![IMG_6195](https://github.com/Tencent/tdesign-miniprogram/assets/67944641/1e743e30-345e-4f89-81e2-c0bbd58cdea8)

**Comment by anlyyao** [comment]
已知问题，要等ios微信更新。

**Comment by Darley-Wey** [comment]
为何我在多端框架中改为flex后还是会再往左偏了一点
