### ISSUE TITLE
小程序中，如何自定义组件使用tdesign的css颜色变量

### ISSUE THREAD

**Issue by farsunset-com** [Tencent/tdesign-miniprogram#2913]
`<text style="color: var(--td-brand-color);">主题色字体</text>
`

没有生效，不知道如何引用 tdesign里面的颜色

**Comment by anlyyao** [comment]
@farsunset-com 需要把design token引入到自己的项目中，可以参考一下官网[button组件的代码片段](https://tdesign.tencent.com/miniprogram/components/button)，在app.wxss中引入主题样式相关，如 @import '/miniprogram_npm/tdesign-miniprogram/common/style/theme/_index.wxss'， 然后你贴的代码就会生效了～

**Comment by farsunset-com** [comment]
感谢 已经可以了

**Comment by farsunset-com** [comment]
> @farsunset-com 需要把design token引入到自己的项目中，可以参考一下官网[button组件的代码片段](https://tdesign.tencent.com/miniprogram/components/button)，在app.wxss中引入主题样式相关，如 @import '/miniprogram_npm/tdesign-miniprogram/common/style/theme/_index.wxss'， 然后你贴的代码就会生效了～

在skyline模式下，会默认成暗黑模式，

**Comment by anlyyao** [comment]
> > @farsunset-com 需要把design token引入到自己的项目中，可以参考一下官网[button组件的代码片段](https://tdesign.tencent.com/miniprogram/components/button)，在app.wxss中引入主题样式相关，如 @import '/miniprogram_npm/tdesign-miniprogram/common/style/theme/_index.wxss'， 然后你贴的代码就会生效了～
> 
> 在skyline模式下，会默认成暗黑模式，

未能复现你的问题。 印象里不论是webview还是skyline，开启`"darkmode": true`时，表示启用深色模式，默认跟随系统，并不能指定使用某一个模式。理论上不会出现你提出的 webview 下默认浅色模式，skyline下默认深色模式。
