### ISSUE TITLE
[t-tab-panel] label支持两行文字或者支持slot

### ISSUE THREAD

**Issue by xiongjinchao** [Tencent/tdesign-miniprogram#2919]
### 这个功能解决了什么问题

我希望label可以支持两行文字比如第一行显示星期，第二行显示几月几日。

### 你建议的方案是什么

label支持两行文字或者支持slot

**Comment by anlyyao** [comment]
组件本身的实现方式目前还做不到支持label同名插槽， 两行文字常规方式也实现不了😅， 可以看下你的视觉稿需求吗？

**Comment by xiongjinchao** [comment]
![微信图片_20240627220347](https://github.com/Tencent/tdesign-miniprogram/assets/10016730/6c7bf9de-761d-4583-9440-3e465e1cd2ca)
