### ISSUE TITLE
[Dark Mode] 深色模式无法tabbar适配

### ISSUE THREAD

**Issue by Nero978** [Tencent/tdesign-miniprogram#2920]
### tdesign-miniprogram 版本

1.4.4

### 重现步骤

**这是一个需要讨论的issue**

## 问题
按照[当前文档](https://tdesign.tencent.com/miniprogram/dark-mode#%E7%89%B9%E6%AE%8A%E7%BB%84%E4%BB%B6%E9%80%82%E9%85%8D%E6%B7%B1%E8%89%B2%E6%A8%A1%E5%BC%8F)，在`app.wxss`中引入design token，给tabbar加上`class="page"`，仍然无法使用`tabbar`的深色模式。

```
<view class="page">
  <t-tab-bar value="{{selected}}" bindchange="onChange" shape="round" theme="tag" split="{{false}}">
    <block wx:for="{{list}}" wx:key="value">
      <t-tab-bar-item value="{{item.value}}" icon="{{item.icon}}" ariaLabel="{{item.ariaLabel}}"></t-tab-bar-item>
    </block>
  </t-tab-bar>
</view>
```

## 可能原因
`app.wxss`的全局样式对`tabbar`组件不生效，导致`.page`选择器也对`tabbar`无效

## 临时解决方案
在`custom-tab-bar/index.wxml`再次引入design token，如：
```
@import '../miniprogram_npm/tdesign-miniprogram/common/style/theme/_index.wxss';
```
这样一来，design token被引入了两次，有些麻烦，是否有更好的方案来适配`tabbar`的深色模式呢？

**Comment by anlyyao** [comment]
@Nero978 custom-tab-bar 的 json 文件加一下 "styleIsolation": "apply-shared"

**Comment by dancelion** [comment]
为啥我加了"styleIsolation": "apply-shared"也不管用，1.8.2版本

**Comment by Nero978** [comment]
> 为啥我加了"styleIsolation": "apply-shared"也不管用，1.8.2版本

贴个代码看看吧
记得先看文档：https://tdesign.tencent.com/miniprogram/dark-mode

**Comment by dancelion** [comment]
> 贴个代码看看吧 记得先看文档：https://tdesign.tencent.com/miniprogram/dark-mode

json文件设置这个后，wxml文件里直接写t-tab-bar 加page类没生效，外层套一层view设置类名page生效了
```
<view class="page">
<t-tab-bar theme="tag" split="{{false}}">
...
</t-tab-bar>
</view>
```

**Comment by PeiJingbobo** [comment]
如果`custom-tab-bar` 的样式文件是scss 不是wxss `@import '../miniprogram_npm/tdesign-miniprogram/common/style/theme/_index.wxss'; `将会不起作用
但是app.scss 也是这样导入的, 页面上的内容是可以起作用的 注意在 `custom-tab-bar` 中使用`../ `开头的相对路径进行导入
