### ISSUE TITLE
[Swiper] 建议在Swiper添加可选的图片描述文字

### ISSUE THREAD

**Issue by dpy22** [Tencent/tdesign-miniprogram#2927]
### 这个功能解决了什么问题

![69f9b3e4f3bb1cbdfee34a706719786](https://github.com/Tencent/tdesign-miniprogram/assets/114906986/99ebd8fc-fc46-4a77-a444-91bb0a6dee7d)
建议在Swiper组件的下部添加可选的图片描述文字，毕竟很多情况下，只有一张Swiper图片无法较好地描述完整信息

### 你建议的方案是什么

建议在组件内添加<text>元素，使用相对位置实现，同时引出为SwiperItem组件的title属性

**Comment by jarmywang** [comment]
可以通过navigation/nav的slot实现，通过position: absolute定位，然后监听切换更换文案，示例：
`<t-swiper ...>
  <view slot="navigation" style="position: absolute; bottom: 100rpx; left: 100rpx">描述</view>
</t-swiper>`
