### ISSUE TITLE
t-picker 遮罩层顶部留白

### ISSUE THREAD

**Issue by 996wuxian** [Tencent/tdesign-miniprogram#2932]
### tdesign-miniprogram 版本

1.4.1

### 重现步骤

![2024-06-29_21-31-20](https://github.com/Tencent/tdesign-miniprogram/assets/111724629/56ddc5cc-27fd-4496-b775-b30da8bf0c61)

### 期望结果

top为0

### 实际结果

top为60

**Comment by 996wuxian** [comment]
我已发现出现该问题的原因：usingCustomNavbar，但是文档中并没有告诉我这是关于什么的，请完善文档

**Comment by anlyyao** [comment]
我们补充一下文档问题～
