### ISSUE TITLE
能否给个可用的example？ 想尝试下skyline，各种不行

### ISSUE THREAD

**Issue by wkii** [Tencent/tdesign-miniprogram#2935]
### tdesign-miniprogram 版本

1.4.4

### 重现步骤

只在github的issue里看到过一个能扫码的小程序码。
然后，仓库里的example 完全不可用啊。 修修改改配置，也不行。
有时候，门槛比门还高。。。

**Comment by anlyyao** [comment]
## 方式一：拉取源码，并在开发者工具中预览

```bash
git clone https://github.com/Tencent/tdesign-miniprogram.git

# 进入项目文件夹
cd tdesign-miniprogram

# 安装项目依赖
npm install

# 执行组件编译，此时会生成一个 _example 文件夹
npm run build
```

打开[微信开发者工具](https://mp.weixin.qq.com/debug/wxadoc/dev/devtools/download.html)，把 `_example` 目录添加进去就可以预览示例了。

**Comment by anlyyao** [comment]
@wkii 目前组件库并未全量适配 skyline，已适配组件见#2659，未适配组件暂不能保证其在skyline下功能的完整性

**Comment by anlyyao** [comment]
> 建议把 已适配组件 和 上面的生成 _example 的“快速开始” 写在 readme.md 里。

两码事吧，上面提供的“方式一：拉取源码，并在开发者工具中预览”一般是开发同学走这个流程。使用组件库的用户是通过npm包引入，预览效果除了官网提供了小程序二维码，每个组件示例页也提供了预览窗口+页面二维码
