### ISSUE TITLE
[t-input] 触发clearable事件后页面点击事件失效

### ISSUE THREAD

**Issue by xiaoshangmin** [Tencent/tdesign-miniprogram#2937]
### tdesign-miniprogram 版本

1.4.4

### 重现步骤

在skyline模式下
t-input 添加clearable属性  并在输入内容后点击清除
当前页面无报错，但是页面的其他点击事件全部失效，比如按钮的click事件无法触发

### 基础库版本

3.4.8

**Comment by anlyyao** [comment]
@xiaoshangmin 看着可能是skyline框架的问题
