### ISSUE TITLE
Calendar 日历

### ISSUE THREAD

**Issue by YangHuoSheng** [Tencent/tdesign-miniprogram#2940]
### 这个功能解决了什么问题

这个组件能选择当前日期之前的吗？ 我看官网都是当前日期之后的

### 你建议的方案是什么

如果能展示当前日期之前的日期   麻烦提示一下

**Comment by anlyyao** [comment]
@YangHuoSheng 参考代码片段中 自定义区间示例（ custom-range 文件夹）：https://developers.weixin.qq.com/s/jb5E2imk7QSV

<img width="898" alt="企业微信截图_6c7cf251-ac47-4f0e-b975-7c6aabbd7360" src="https://github.com/Tencent/tdesign-miniprogram/assets/51158141/2b6dae35-2c0f-44ab-a2f9-43c8e37ff515">

总体上，想要当前日期之前的日期就传minDate，想要当前日期之后就传maxDate

**Comment by YangHuoSheng** [comment]
![图片](https://github.com/Tencent/tdesign-miniprogram/assets/135927472/ce255078-cb23-4d96-9693-194e890fe33e)
![图片](https://github.com/Tencent/tdesign-miniprogram/assets/135927472/dddae44d-56b7-40f6-a0e1-88427e5599cd)
![图片](https://github.com/Tencent/tdesign-miniprogram/assets/135927472/c6e2955d-f9a1-465f-8247-9ef31ee7a9fc)
我怎么打开日历就是默认选中今天的日期

**Comment by YangHuoSheng** [comment]
现在就是我把value属性删除  它默认的就是minDate
![图片](https://github.com/Tencent/tdesign-miniprogram/assets/135927472/e5f66580-85bd-4b86-8c86-4b08fd31b4a3)
![图片](https://github.com/Tencent/tdesign-miniprogram/assets/135927472/30f9766d-1a22-4e59-9fb1-69c54ef95da7)
![图片](https://github.com/Tencent/tdesign-miniprogram/assets/135927472/5ad4ebc0-28e2-41a4-9b81-681cde3d5916)

现在就是我想要自定义区间  然后打开日历默认选中今天的日期

**Comment by anlyyao** [comment]
这是代码片段：https://developers.weixin.qq.com/s/s17vapmJ7GSD， 参考“自定义区间”示例， 大部分使用问题可以在官网文档和示例上找答案

**Comment by YangHuoSheng** [comment]
好的，我知道了，过于着急了，谢谢

**Comment by anlyyao** [comment]
> 好的，我知道了，过于着急了，谢谢

小问题，你先确认示例demo能不能满足你需求，如果可以满足我这边就先关闭issue，新问题随时欢迎开新帖讨论

**Comment by YangHuoSheng** [comment]
可以的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月03日 11:10 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Tencent/tdesign-miniprogram] Calendar 日历 (Issue #2940) |

好的，我知道了，过于着急了，谢谢

小问题，你先确认示例demo能不能满足你需求，如果可以满足我这边就先关闭issue，新问题随时欢迎开新帖讨论

**Comment by qianb7** [comment]
我发现日期区间跨度大，比如 2000-01-01 到今天，组件在 visible 切换打开关闭的时候相当卡，有什么解决方法吗
