### ISSUE TITLE
[toast] 最大宽度有误，且纯文本没有完全居中

### ISSUE THREAD

**Issue by esky** [Tencent/tdesign-miniprogram#295]
### tdesign-miniprogram 版本

0.6.2

### 重现步骤

```
 // 实际最大宽度只有50%，而不是max-width: 374rpx
  &__content {
    position: fixed;
    left: 50%;
    transform: translate(-50%, -50%);
    max-width: 374rpx;
  }
 // 无icon的纯文本，左侧有边距，不能水平居中
  &-text {
      margin-left: 12rpx;
    }
```

### 期望结果

1. 纯文本居中
2. 自定义最大宽度
<img width="379" alt="image" src="https://user-images.githubusercontent.com/2155775/160345004-1b67434e-1129-447a-9259-2d10fd238b3f.png">

```
   // 可参考写法，调整最大宽度
    &__content {
      max-width: 520rpx;
      // 自适应屏幕
      margin-right: -30%;
    }
```

### 实际结果

<img width="144" alt="image" src="https://user-images.githubusercontent.com/2155775/160343942-0d41b039-c54d-4e6b-af37-c06988d15543.png">

**Comment by zhenzhencai** [comment]
我确认一下
