### ISSUE TITLE
[t-piker] 设置piker-item高度后，滚动距离异常

### ISSUE THREAD

**Issue by mynoded** [Tencent/tdesign-miniprogram#2950]
### tdesign-miniprogram 版本

0.33.0

### 重现步骤

<t-picker
  visible="{{true}}"
  value="{{cityValue}}"
  usePopup="{{false}}"
  data-key="city"
  title=""
  cancelBtn=""
  confirmBtn=""
  usingCustomNavbar
  bindchange="onPickerChange"
  bindpick="onColumnChange"
  bindcancel="onPickerCancel"
>
  <t-picker-item options="{{citys}}"></t-picker-item>
</t-picker>

Page({
    data: {
      cityValue: [],
      cityTitle: '',
      citys: [
        { label: '北京市', value: '北京市' },
        { label: '上海市', value: '上海市' },
        { label: '广州市', value: '广州市' },
        { label: '深圳市', value: '深圳市' },
        { label: '成都市', value: '成都市' },
      ],
    },
  
    methods: {
      onColumnChange(e) {
        console.log('picker pick:', e);
      },
  
      onPickerChange(e) {
        const { key } = e.currentTarget.dataset;
        const { value } = e.detail;
  
        console.log('picker change:', e.detail);
        this.setData({
          [`${key}Visible`]: false,
          [`${key}Value`]: value,
          [`${key}Text`]: value.join(' '),
        });
      },
  
      onPickerCancel(e) {
        const { key } = e.currentTarget.dataset;
        console.log(e, '取消');
        console.log('picker1 cancel:');
        this.setData({
          [`${key}Visible`]: false,
        });
      },
    },
  });

page{
	--td-picker-item-height:112rpx
}

**Comment by anlyyao** [comment]
@mynoded 确实没支持，组件内部是固定以80rpx计算偏移量，我们处理一下、
