### ISSUE TITLE
[ICON] icon名称对不上，导致线上使用的图标全部改变了

### ISSUE THREAD

**Issue by ArcticRug25** [Tencent/tdesign-miniprogram#2955]
### tdesign-miniprogram 版本

1.2.3

### 重现步骤

https://tdesign.tencent.com/miniprogram/components/icon
<img width="370" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/59426182/c66a7aa7-f67a-49fd-a035-d3b59da76223">

### 期望结果

图标名称错误

**Comment by uyarn** [comment]
更新图标未同步导致 已经修复 可能还有一点CDN缓存

**Comment by ArcticRug25** [comment]
> 更新图标未同步导致 已经修复 可能还有一点CDN缓存

好的，感谢回复

**Comment by uyarn** [comment]
我这边已经恢复正常

<img width="459" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/26377630/e67ce991-ef6a-40ec-8fe8-4e019f6d4f40">

**Comment by ArcticRug25** [comment]
> 我这边已经恢复正常
> 
> <img alt="image" width="459" src="https://private-user-images.githubusercontent.com/26377630/346011825-e67ce991-ef6a-40ec-8fe8-4e019f6d4f40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNTc4NzUsIm5iZiI6MTcyMDE1NzU3NSwicGF0aCI6Ii8yNjM3NzYzMC8zNDYwMTE4MjUtZTY3Y2U5OTEtZWY2YS00MGVjLThmZTgtNGUwMTlmNmQ0ZjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDA1MzI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMDk2MWZlNWM5YjkyM2JhMTE5ZTAzOTQxNDdmOGU2OTYxZmE5MDIyODIyZjBkOWUzOTY5ZDRhYTE4MzA2ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pu-IhDI-4hS4FKZkH5hk8r_cAxOjh9qNjpUrFUMwqZE">

恩恩，我这边线上也恢复了
