### ISSUE TITLE
[Picker] 选择时无法蒙层，热更新后又无法取消

### ISSUE THREAD

**Issue by Believe688** [Tencent/tdesign-miniprogram#2961]
### tdesign-miniprogram 版本

1.4.3

### 重现步骤

编译完，无蒙层（图1）。但进行任何代码操作，热更新后，蒙层出现，点击蒙层，选择器可正常关闭，但蒙层不消失（图2）。
![图1](https://github.com/Tencent/tdesign-miniprogram/assets/62087052/521fad08-8411-4049-9e68-363166cbe05b)
![图2](https://github.com/Tencent/tdesign-miniprogram/assets/62087052/50166425-474a-4f51-83b1-2cc30f54c5a6)

`<t-grid column="{{5}}" align="center" border="{{border}}" hover>
    <t-grid-item wx:for="{{teacherGrids}}" text="{{item.value}} ∇" description="{{item.text}}" bind:click="onClickPicker" data-id="{{item.label}}" wx:key="index" />
  </t-grid> 
  <t-picker visible="{{cityVisible}}" usingCustomNavbar data-key="{{pickerKey}}" 
    cancelBtn="取消" confirmBtn="确认" bindchange="onPickerChange" bind:pick="onColumnChange">
      <t-picker-item options="{{pickers}}" />
      <t-picker-item options="{{pickers1}}" />
  </t-picker>`
JS 代码：
`  onClickPicker(e) {
    const {id} = e.target.dataset
    this.setData({
      pickVisible: true
    })}`

### 期望结果

告知原因或修复Bug

### 基础库版本

3.4.9

**Comment by anlyyao** [comment]
@Believe688 提供一下可复现代码片段链接？ 可以基于此片段复现你的问题，重新分享可生成新链接，https://developers.weixin.qq.com/s/6H70dimL7jSK

**Comment by Believe688** [comment]
demo链接：https://developers.weixin.qq.com/s/HHO8nFmT7NSD

**Comment by pdog18** [comment]
我也出现了没有蒙层的情况

**Comment by pdog18** [comment]
1.4.2 是下方 3/4 有蒙层，1.4.3 是完全没有蒙层

**Comment by jby0107** [comment]
@Believe688 @pdog18 蒙层问题在1.4.4版本更新里修复了，相关PR： #2887 。可以更新一下组件库版本，应该会解决这个问题
