### ISSUE TITLE
Dialog 命令调用 方式中 有输入框 显示不正确

### ISSUE THREAD

**Issue by DoverDee** [Tencent/tdesign-miniprogram#2968]
### tdesign-miniprogram 版本

1.2.9

### 重现步骤

`
showDialog() {
      const dialogConfig = {
        closeBtn: true,
        context: this,
        title: '确认取消',
        content: '<input class="dialog-input" placeholder="请填写取消原因" model:value="{{cancelReason}}" clearable />',
        confirmBtn: this.data.confirmBtn,
        cancelBtn: '再想想',
      };
      Dialog.confirm(dialogConfig)
        .then(() => console.log('点击了确定'))
        .catch(() => console.log('点击了取消'));
    },
`
### 期望结果

![image](https://github.com/Tencent/tdesign-miniprogram/assets/8557230/ada4e882-dbd9-4604-99d1-07f1c5988a13)

### 实际结果

![image](https://github.com/Tencent/tdesign-miniprogram/assets/8557230/54dee91b-ad22-46da-89d0-c0b9f45e354b)

### 补充说明

如果写才能实现正常的渲染效果

**Comment by jarmywang** [comment]
slot命令式不支持，需要写到wxml里
