### ISSUE TITLE
[功能] 目前小程序的开发工具，实在太共苦了。希望在 视图组件里面传递对象减少代码量

### ISSUE THREAD

**Issue by githublaohu** [Tencent/tdesign-miniprogram#2969]
### 这个功能解决了什么问题

1. 开发速度
2. 维护成本
3. 可高的可读性，同时损失了 wxml 的可读性。

### 你建议的方案是什么

支持 对象参数，60来个组件维护成本有点大，还希望目前的vue 以及 同时能支持

**Comment by jarmywang** [comment]
@githublaohu  能举个具体例子吗？

**Comment by uyarn** [comment]
这个看起来说小程序开发工具需要解决的问题吧

**Comment by githublaohu** [comment]
`
<t-pull-down-refresh
  value="{{enable}}"
  loadingProps="{{loadingProps}}"
  loadingTexts="{{['下拉刷新', '松手刷新', '正在刷新', '刷新完成']}}"
  bind:refresh="onRefresh"
  bind:scroll="onScroll"
>
</t-pull-down-refresh>
`
这里至少有5个参数。可以的话，我希望值传递一个就行了。
正常情况下，这里至少有 7 8个参数，是在太多了。一个页面有非常多的标签。也有非常多的功能。
`

<t-pull-down-refresh data_model = {{pullDownRefresh}} >
</t-pull-down-refresh>

class PullDownRefresh{
  refresh;
  scroll;
   value;
loadingProps
loadingTexts.....
}

const pullDownRefresh = new PullDownRefresh();

`

这样就干净多了。

**Comment by githublaohu** [comment]
@jarmywang

**Comment by githublaohu** [comment]
`<t-pull-down-refresh
  value="{{enable}}"
  loadingProps="{{loadingProps}}"
  loadingTexts="{{['下拉刷新', '松手刷新', '正在刷新', '刷新完成']}}"
  bind:refresh="onRefresh"
  bind:scroll="onScroll"
>
</t-pull-down-refresh>
`

这里至少有5个参数。可以的话，我希望值传递一个就行了。
正常情况下，这里至少有 7 8个参数，是在太多了。一个页面有非常多的标签。也有非常多的功能。

`
<t-pull-down-refresh data_model = {{pullDownRefresh}} />
class PullDownRefresh{
  refresh;
  scroll;
   value;
loadingProps
loadingTexts.....
}

const pullDownRefresh = new PullDownRefresh();
`

这样就干净多了。

**Comment by githublaohu** [comment]
`<t-pull-down-refresh
  value="{{enable}}"
  loadingProps="{{loadingProps}}"
  loadingTexts="{{['下拉刷新', '松手刷新', '正在刷新', '刷新完成']}}"
  bind:refresh="onRefresh"
  bind:scroll="onScroll"
>
</t-pull-down-refresh>
`

这里至少有5个参数。可以的话，我希望值传递一个就行了。
正常情况下，这里至少有 7 8个参数，是在太多了。一个页面有非常多的标签。也有非常多的功能。

`
<t-pull-down-refresh data_model = {{pullDownRefresh}} />
class PullDownRefresh{
  refresh;
  scroll;
   value;
loadingProps
loadingTexts.....
}

const pullDownRefresh = new PullDownRefresh();

`

这样就干净多了。
