### ISSUE TITLE
[t-grid] 点击grid item没有任何反应

### ISSUE THREAD

**Issue by lucas-seismic** [Tencent/tdesign-miniprogram#2982]
### tdesign-miniprogram 版本

1.4.5

### 重现步骤

```
  <t-grid class="block" column="{{2}}" align="left" border="{{true}}">
    <t-grid-item icon="building-1" text="社区管理" description="加入/退出社区" layout="horizontal" url="pages/community/community" />
    <t-grid-item icon="building-2" text="社区管理" description="加入/退出社区" layout="horizontal" url="pages/community" />
  </t-grid>

```

**Comment by anlyyao** [comment]
@lucas-seismic 点击态可开启Grid的hover，点击事件请用GridItem的click事件，[官网文档有详细描述 ](https://tdesign.tencent.com/miniprogram/components/grid?tab=api)
<img width="641" alt="企业微信截图_4bd25ab5-07cf-4c6e-872d-e1035dfbf445" src="https://github.com/user-attachments/assets/1b09a03d-6fd6-4ab0-93e9-9c85a762df90">
<img width="643" alt="企业微信截图_f5375756-49c3-4372-b044-aa9929bae781" src="https://github.com/user-attachments/assets/56cb82f0-4d3a-4092-b68d-bfdf19221739">

**Comment by lucas-seismic** [comment]
那item里的url属性有啥用呢？ url看定义是点击后跳转的路径

**Comment by anlyyao** [comment]
> 那item里的url属性有啥用呢？ url看定义是点击后跳转的路径

你贴的代码用的也不是 url 属性啊

**Comment by lucas-seismic** [comment]
sorry，那个code贴的有点问题，改过了，那个的确是不行，你也许可以轻松复现

**Comment by anlyyao** [comment]
@lucas-seismic 正是因为并没有复现你的问题，所以才需要你提供实际使用代码，而从你贴你的代码上看，是你使用问题，使用问题请查阅官网文档和示例
