### ISSUE TITLE
[t-message] 手动设置visible属性无效

### ISSUE THREAD

**Issue by AN-535** [Tencent/tdesign-miniprogram#2983]
### tdesign-miniprogram 版本

1.4.5

### 重现步骤

![QQ_1721058641372](https://github.com/user-attachments/assets/61b19f8c-ad9a-4fef-af56-d6757283d1bd)
![QQ_1721058700739](https://github.com/user-attachments/assets/ddcbe7d9-29c9-4578-8ec3-7b0dcd62cdce)
手动更改了visible属性值之后message组件没有显示，页面也没有节点，没有报错

### 期望结果

通过visible属性能正常控制message组件显示隐藏

### 实际结果

修改visible属性后，message组件没有改变显示状态

### 基础库版本

3.4.10

**Comment by anlyyao** [comment]
@AN-535 确实有问题，我们跟进一下～

暂时解决方案：Message目前只支持函数式调用，关闭使用 Message.hide()。
