### ISSUE TITLE
[ Indexes 索引]组件样式出现bug，以及滚动中标题的定位与消失等问题

### ISSUE THREAD

**Issue by RADWIMPS426** [Tencent/tdesign-miniprogram#2985]
### tdesign-miniprogram 版本

1.4.5

### 重现链接

https://tdesign.tencent.com/miniprogram/components/indexes

### 重现步骤

<img width="377" alt="image" src="https://github.com/user-attachments/assets/dd3c8566-6917-4185-bb7a-1dd62eaadd06">
<img width="380" alt="image" src="https://github.com/user-attachments/assets/f6215543-89dc-470f-9493-bf39b4fc9efb">

<img width="374" alt="image" src="https://github.com/user-attachments/assets/1f777b8e-99f7-47fa-902d-7f71ff442248">

### 实际结果

1.胶囊样式出现黑色的色块
2.胶囊样式的标题定位不准确
3.基础样式在滚动中标题模块会消失

**Comment by ArcticFoxPro** [comment]
同样的问题，能在 Xiaomi 14 Pro 真机使用 TDesign 官方 Demo 复现。

似乎#2825 也属于此问题或其连带问题

![mmexport1721114989465.jpg](https://github.com/user-attachments/assets/21a5959b-6307-4098-a0db-62883bf330bf)

https://github.com/user-attachments/assets/50b87a35-1a10-42fc-af85-3e2bcca5875c
