### ISSUE TITLE
t-slider 拉到最大值，显示不完整

### ISSUE THREAD

**Issue by luoxin59420** [Tencent/tdesign-miniprogram#2994]
### tdesign-miniprogram 版本

是

### 实际结果

![image](https://github.com/user-attachments/assets/f1b3e517-a9a2-4c22-b9ca-da187871ea88)
值到100了 但图没达到

**Comment by anlyyao** [comment]
@luoxin59420 贴一下可复现代码片段

**Comment by luoxin59420** [comment]
> @luoxin59420 贴一下可复现代码片段

是把t-slider组件嵌套在t-dialog里面，长度拉不满，出现了一个固定宽度
![image](https://github.com/user-attachments/assets/7827e083-7e52-4175-b63d-4ad1dbb8a3ae)
代码如下：

<t-dialog visible="{{true}}" close-on-overlay-click="{{ true }}" prevent-scroll-through>
  <view slot="content">
    <t-slider default-value="{{23}}" step="{{0.1}}"   bind:change="handleChange" />
  </view>
</t-dialog>

**Comment by luoxin59420** [comment]
> @luoxin59420 贴一下可复现代码片段


<t-dialog visible="{{true}}" close-on-overlay-click="{{ true }}" prevent-scroll-through>
  <view slot="content">
    <t-slider default-value="{{23}}" step="{{0.1}}"   bind:change="handleChange" />
  </view>
</t-dialog>

**Comment by anlyyao** [comment]
已知的场景问题，在官网组件页面的FAQ中有做说明，see https://tdesign.tencent.com/miniprogram/components/slider?tab=api
