### ISSUE TITLE
[t-dialog] close-on-overlay-click  prevent-scroll-through 都不生效

### ISSUE THREAD

**Issue by luoxin59420** [Tencent/tdesign-miniprogram#2995]
### tdesign-miniprogram 版本

1.4.5

### 重现步骤

 <t-dialog visible="{{dialogVisible}}" bind:visible-change="onVisibleChangeDialog" class="dialog-wrapper" close-on-overlay-click="{{ true }}" prevent-scroll-through></t-dialog>
点击蒙层不生效

**Comment by jarmywang** [comment]
@luoxin59420 麻烦提供复现代码片段
