### ISSUE TITLE
TabBar 标签栏 支持 Skyline 的问题

### ISSUE THREAD

**Issue by sk142857** [Tencent/tdesign-miniprogram#2999]
### tdesign-miniprogram 版本

1.4.5

### 重现步骤

微信官方：https://developers.weixin.qq.com/miniprogram/dev/framework/ability/custom-tabbar.html

使用 skyline 渲染模式的时候，需要进行如下适配：
```
.tab-bar {
  pointer-events: auto;
  position: absolute;
}
```
似乎，这个版本并没有适配。导致，会出现点击穿透的问题。

**Comment by jarmywang** [comment]
@sk142857 现阶段skyline适配我们还不太想改组件内部代码，写`if(skyline)...else...`这样的逻辑，因为skyline目前还在不断完善中，后续可能会有变动，建议业务侧先通过样式覆盖（.t-tab-bar）的方式增加
