### ISSUE TITLE
[NoticeBar] 随机出现奇怪的跑马灯效果

### ISSUE THREAD

**Issue by pdog18** [Tencent/tdesign-miniprogram#3007]
### tdesign-miniprogram 版本

1.4.4

### 重现步骤

https://developers.weixin.qq.com/s/RIbMAXmg7ASr

不断进入对应使用 notice-bar 的界面，会偶现对应 bug 

https://github.com/user-attachments/assets/d1ef5c18-002e-4a2f-93f1-7aada9e38d75

### 期望结果

NoticeBar 正常展示，不要出现滚动效果

### 实际结果

偶尔出现滚动效果

**Comment by pdog18** [comment]
备注，原视频 50 多秒，因视频过大，有裁剪，可以内测群找我要原视频

**Comment by jarmywang** [comment]
@pdog18 麻烦更新版本再看看
