### ISSUE TITLE
[t-cell] 希望 t-cell 也可以支持 open-type 功能或者支持传入按钮的 button-props

### ISSUE THREAD

**Issue by narukeu** [Tencent/tdesign-miniprogram#3013]
### 这个功能解决了什么问题

因为 cell 是可以点击的嘛，有的时候使用 cell 代替按钮会很美观，但是按钮的一些特性，比如 `open-type`， cell 是不支持的，这样开发的时候会带来一定困难，所以希望组件库支持。

### 你建议的方案是什么

支持 open-type 功能或者支持传入按钮的 button-props。

**Comment by anlyyao** [comment]
@narukeu cell是cell、button是button。如果你想在cell的基础上使用button按钮的open-type功能，暂时只能提供两个思路，思路一：在cell中使用插槽，引入button按钮；思路二：尝试用button包裹cell组件（未验证）
