### ISSUE TITLE
[link] 动态生成的链接数组对象在初始化时候 报黄色警告

### ISSUE THREAD

**Issue by Qing1** [Tencent/tdesign-miniprogram#3020]
### tdesign-miniprogram 版本

1.5.0

### 重现链接

https://github.com/Qing1/TDesignUIminiLearningTest/tree/main

### 重现步骤

在表格中动态生成链接时候 有黄色警告
![image](https://github.com/user-attachments/assets/20d9f498-aa45-4bff-b2fa-e4cfa25254eb)

### 期望结果

去除该黄色警告

### 基础库版本

3.5.1

**Comment by anlyyao** [comment]
@Qing1 提供的重现链接地址不存在。

告警原因已经被你圈出来了😅。大概率是在初始化阶段，你传入的navigatorProps是一个非对象，提示让你用null代替。

**Comment by Qing1** [comment]
Hello  美女大佬  不好意思 之前仓库是私人状态  。开始时候 我也觉得是因为我传的对象不对 因为data中 linkOederList:[], 是这样的 后来 我修改成 linkOrderList1:{},还是没有解决问题 初始化时候 在onLoad{this.link1()}中  在对应的页面 < t-link navigator-props="{{linkOrderList1[item.employeeId]}}",还是没有解决这个问题

**Comment by betavs** [comment]
@Qing1 可以等数据处理完再显示即可

```html
<t-link
  wx:if="{{ visible }}"
  size="small"
  theme="primary"
  content="详情"
  navigator-props="{{ linkOrderList[index] }}"
  prefixIcon="link"
  t-class="linkStyle"
  hover
  bindcomplete="onNav"
  data-id="{{ item.employeeId }}"
/>
```

```javascript
this.setData(
  {
    linkOrderList: linkList,
  },
  () => {
    this.setData({ visible: true });
  }
);
```

**Comment by Qing1** [comment]
谢谢大佬 非常效率。这个修改后 确实可以去除那个黄色警告。就想知道有没有更优雅的方法【不用前端来考虑这个问题】 来实现这个效果……哈哈，有点贪心

**Comment by betavs** [comment]
@Qing1 

```html
<t-link
  wx:if="{{ linkOrderList[index] }}"
  size="small"
  theme="primary"
  content="详情"
  navigator-props="{{ linkOrderList[index] }}"
  prefixIcon="link"
  t-class="linkStyle"
  hover
  bindcomplete="onNav"
  data-id="{{ item.employeeId }}"
/>
```
