### ISSUE TITLE
[<t-step-item>] 如何给t-design的组件添加自定义的class

### ISSUE THREAD

**Issue by Austin-Ming** [Tencent/tdesign-miniprogram#3022]
### tdesign-miniprogram 版本

1.4.5

### 重现步骤

<t-step-item class="custom-class"></t-step-item>

custom-class设置不到t-design的组件中

### 期望结果

custom-class可以设置到t-design的组件中

### 实际结果

custom-class设置不到t-design的组件中

**Comment by anlyyao** [comment]
@Austin-Ming 贴一下你的实际使用代码？因为外部样式类未生效一般有两种情况，一种是使用错误，一种是使用正确，但因优先级问题未生效，大部分是第二种。

**Comment by Austin-Ming** [comment]
> @Austin-Ming 贴一下你的实际使用代码？因为外部样式类未生效一般有两种情况，一种是使用错误，一种是使用正确，但因优先级问题未生效，大部分是第二种。

在代码中设置的样式生效了，但是在微信开发工具查看wxml中并没有查看到设置的自定义class，搜索red-loading结果为空

**Comment by anlyyao** [comment]
@Austin-Ming 个人理解哈， 外部样式类并不会直接显示在DOM上，因为它是被组件内部使用的。 比如：t-class-loading 是t-button组件内部预先定义的样式类，类的具体样式是空的。然后，在使用组件时，通过属性的形式将外部的样式类传入组件，组件会将这些外部样式类的内容应用到内部预先定义的空样式类上，从而实现样式的修改。
