### ISSUE TITLE
[Popup] 深色模式下关闭按钮颜色不正确

### ISSUE THREAD

**Issue by Nero978** [Tencent/tdesign-miniprogram#3028]
### tdesign-miniprogram 版本

1.4.5

### 重现步骤

在`深色模式`下，`close-btn="{{true}}"`时右上角的关闭按钮颜色不正确
<img width="326" alt="image" src="https://github.com/user-attachments/assets/f0048342-6edb-4cdb-a2c6-d30c260b05a8">

### 期望结果

应该是白色

### 实际结果

黑色

### 基础库版本

最新

**Comment by jarmywang** [comment]
@Nero978 新增--td-popup-close-btn-color变量
