### ISSUE TITLE
[分页器] 微信小程序版本增加分页器

### ISSUE THREAD

**Issue by TCroods** [Tencent/tdesign-miniprogram#3029]
### 这个功能解决了什么问题

在小程序中，当数据量较大时，触底翻页可能会导致操作变得繁琐。

### 你建议的方案是什么

目标是创建一个分页器，以便在处理大量数据时提供更流畅的用户体验。

**Comment by anlyyao** [comment]
@TCroods 感谢反馈，我们讨论一下～，如果对这个组件有更详细的需求/场景，也可以继续在下方补充，我们会持续跟进的

**Comment by TCroods** [comment]
好的，感谢！

**Comment by RADWIMPS426** [comment]
感谢你的建议，在移动端，用户更倾向于使用手势滑动来浏览内容，通过无限滚动或瀑布流等方式，可以减少页面加载次数，提高数据加载效率，而分页器需要用户进行额外的点击操作，可能会打断用户的阅读流程，影响用户体验。
在一些特定场景下，如需要精确控制内容展示或具有特殊导航需求的场景中，分页器仍然具有一定的应用价值，但组件开发设计需优先考虑其应用场景是否通用，因此，我们暂不支持。
