### ISSUE TITLE
SwipeCell 滑动,请问这个确认删除是怎么实现的呢？文档实在每看明白

### ISSUE THREAD

**Issue by luoxin59420** [Tencent/tdesign-miniprogram#3030]
![image](https://github.com/user-attachments/assets/5b4fa346-ab9c-4991-9b65-53feea14a497)

**Comment by jarmywang** [comment]
配合`opened`属性，第一次点击`删除`把right改为只有一个`确认删除`,`opened`改为`true`，再次点击删除才删除

**Comment by luoxin59420** [comment]
> @luoxin59420 配合`opened`属性，第一次点击`删除`把right改为只有一个`确认删除`,`opened`改为`true`，再次点击删除才删除

但是这个opened是控制列表所有的列的呢？有无实际案例可查看下呢？

**Comment by luoxin59420** [comment]
> @luoxin59420 配合`opened`属性，第一次点击`删除`把right改为只有一个`确认删除`,`opened`改为`true`，再次点击删除才删除

![image](https://github.com/user-attachments/assets/72aa200a-841b-41fb-8490-03c08686b8ce)
加上[false, true]后全部打开了

**Comment by luoxin59420** [comment]
> @luoxin59420 配合`opened`属性，第一次点击`删除`把right改为只有一个`确认删除`,`opened`改为`true`，再次点击删除才删除

![image](https://github.com/user-attachments/assets/7ce69f14-1352-4b5e-a706-06fc90209c60)
代码在这

**Comment by luoxin59420** [comment]
> @luoxin59420 配合`opened`属性，第一次点击`删除`把right改为只有一个`确认删除`,`opened`改为`true`，再次点击删除才删除

这是我的所有代码，点击之后设置open为true后，滑块还是自动关闭了，并且所有的列都变成了一个删除按钮，像请教下怎么单独控制每一条，并且控制它打开或者关闭呢？

**Comment by luoxin59420** [comment]
![image](https://github.com/user-attachments/assets/064a3856-9563-4c29-96dd-85a26d68143a)

**Comment by luoxin59420** [comment]
> @luoxin59420 配合`opened`属性，第一次点击`删除`把right改为只有一个`确认删除`,`opened`改为`true`，再次点击删除才删除

点击第一个删除后，设置opened为true，但滑块还是关闭了，需要二次滑动才显示刚才显示的

**Comment by luoxin59420** [comment]
![image](https://github.com/user-attachments/assets/d2a2cfee-6372-47d5-b9ec-04d3970b96a1)


> @luoxin59420 配合`opened`属性，第一次点击`删除`把right改为只有一个`确认删除`,`opened`改为`true`，再次点击删除才删除

点击第一个删除后，设置opened为true，但滑块还是关闭了，需要二次滑动才显示刚才显示的，是跟下面的有关系吗、
![image](https://github.com/user-attachments/assets/a244918b-e8a4-46c6-8449-bc4e67fb2de5)

**Comment by jarmywang** [comment]
@luoxin59420 没关系，贴一下你代码？

**Comment by luoxin59420** [comment]
> @luoxin59420 没关系，贴一下你代码？
openCell: [false, false, false],
right: [
      [{
        text: '重命名',
        className: 'btn edit-btn',
      },
      {
        text: '删除',
        className: 'btn delete-btn',
      },],
      [{
        text: '重命名',
        className: 'btn edit-btn',
      },
      {
        text: '删除',
        className: 'btn delete-btn',
      },],
      [{
        text: '重命名',
        className: 'btn edit-btn',
      },
      {
        text: '删除',
        className: 'btn delete-btn',
      },]
    ],
<t-swipe-cell
          wx:for="{{ testList }}"
          wx:for-index="index"
          wx:key="id"
          right="{{right[index]}}"
          opened="{{openCell[index]}}"
          data-index="{{index}}"
          data-row="{{item}}"
          bind:click="onActionClick"
          bind:dragend="onDragend"
        ></t-swipe-cell>
// 滑块
  async onActionClick ({ detail, currentTarget }) {
    const { index, row } = currentTarget.dataset
    // 删除
    if (detail.text === '删除') {
      await this.setData({
        [`right[${index}]`]: [{ text: '确认删除', className: 'btn-confirm-del delete-btn' }],
        [`openCell[${index}]`]: true
      })
    }
    // 重命名
    if (detail.text === '重命名') {
      await this.setData({ showWithRename: true, isRename: true, currentMyDevice: row })
    }
    // 真正删除
    if (detail.text === '确认删除') {
      this.confirmDialogDel(row)
    }
  },
现在换种方式写，可以弹出确认删除了，但是有个新问题：当右滑关闭滑块的时候，需要还原初始化的两个按钮，目前监听不到滑块关闭，请帮忙看下
