### ISSUE TITLE
[TreeSelect] 树形选择 对应的选择值 在多级列表切换时候 由三级向二级 一级列表切换时候 没有去掉之前多级列表的值

### ISSUE THREAD

**Issue by Qing1** [Tencent/tdesign-miniprogram#3031]
### tdesign-miniprogram 版本

1.5.0

### 重现链接

https://github.com/Qing1/TDesignUIminiLearningTest1/tree/master

### 重现步骤

![image](https://github.com/user-attachments/assets/7c7ca11e-937e-4fdf-a94e-bfa2cc750cc8)

 打开项目后  添加编译 选择 test1页面  编译 即可出现对应的页面

### 期望结果

由三级向一级列表切换时候 ，能去掉之前 三级列表中的选中值

### 基础库版本

3.5.1

**Comment by anlyyao** [comment]
@Qing1 @jarmywang 这个问题 似乎不是一个bug，原本设计如此。刚刚也特意咨询了一下设计同学 + 参考了其他组件库同名组件，大家都默认保留了上一次的选中子项。实际上，保留上一次选中子项是不影响该组件整体交互的，如果业务上必须清空，可以通过change事件返回的level值，通过判断level变更自行清理value。

**Comment by Qing1** [comment]
明白了  感谢大佬们解惑
