### ISSUE TITLE
[fab] fab组件不能自定义按钮的样式，例如更改颜色、大小等，建议加入外部样式类

### ISSUE THREAD

**Issue by MuseumMage** [Tencent/tdesign-miniprogram#3033]
### 这个功能解决了什么问题

fab组件不能自定义按钮的样式，例如更改颜色、大小等。style属性最多只能更改组件的位置，buttonprop的属性也有限。

### 你建议的方案是什么

建议加入外部样式类或者css变量，能够灵活更改

**Comment by anlyyao** [comment]
@MuseumMage 原t-button组件的css var同样适用
