### ISSUE TITLE
[navbar] 导航栏标题和图片位置错位的问题

### ISSUE THREAD

**Issue by qxpf666** [Tencent/tdesign-miniprogram#3047]
### tdesign-miniprogram 版本

1.5.0

### 重现步骤

![Screenshot_20240805_141722_com tencent mm](https://github.com/user-attachments/assets/9290290d-78b9-4e4e-8430-4922288aad33)

[system] WeChatLib: 3.5.3 (2024.8.1 14:44:53)
[system] Subpackages: N/A
[system] LazyCodeLoading: true
Lazy code loading is enabled. Only injecting required components.
[skyline] skyline 版本号: 1.3.0, 版本记录: ebe62ebe6adb1a5817ad24ff81a9d6e3a0884ba6
app.ts:13 0e307u000sYcBS1JoI100zCgz7407u0i
[system] Launch Time: 10571 ms

如图所示，苹果系统没有测试，安卓系统会出现这个问题，手动调整很麻烦，希望大佬在下个版本更新修正

### 基础库版本

3.5.3

**Comment by qxpf666** [comment]
skyline 会出现这个问题，我再问WebView的情况下，一切正常

**Comment by anlyyao** [comment]
开了 defaultContentBox 配置项吗 @qxpf666 

"rendererOptions": {
    "skyline": {
      "defaultDisplayBlock": true,
      "defaultContentBox": true,
    }
  }

**Comment by Episode233** [comment]
同样的问题，在app.json中添加"defaultContentBox": true,即可

**Comment by qxpf666** [comment]
好的，已经解决
