### ISSUE TITLE
[TreeSelect] 多选模式下，点击存在空下级的节点时会报错

### ISSUE THREAD

**Issue by 13457772277** [Tencent/tdesign-miniprogram#3048]
### tdesign-miniprogram 版本

1.5.0

### 重现链接

https://developers.weixin.qq.com/s/RfA4EdmX7wTc

### 重现步骤

JS截图
![js](https://github.com/user-attachments/assets/bca1f414-ddba-49ea-a2e9-66d0d05ad7d0)

JSON截图
![json](https://github.com/user-attachments/assets/fa38f3a4-072e-482b-97b9-3914dffea028)

WXML截图
![xml](https://github.com/user-attachments/assets/6d2abd9f-124d-4cd3-92f1-df832257acdf)

### 期望结果

点击不报错，同时最好能支持非末尾节点也可以多选

### 实际结果

报错截图
![errr](https://github.com/user-attachments/assets/6e1d76bc-dcbd-4b49-a463-ff61e362e6d4)

**Comment by 13457772277** [comment]
这是来自QQ邮箱的自动回复邮件。你好，您的邮件已接收到，可能目前还不能及时回复您。我将在看过邮件后，尽快给你回复。谢谢谅解

**Comment by jby0107** [comment]
@13457772277 组件里从每一个根结点出发到叶节点的层数需要相等。在你的复现代码中‘选项一’有三层，‘选项二’有两层：
![355007713-bca1f414-ddba-49ea-a2e9-66d0d05ad7d0](https://github.com/user-attachments/assets/5eb18b31-a5cf-45fe-96b8-d8d11da120e8)
根据代码期望效果有两种方法可以修复你的问题：
1. 两层树形结构，删除‘选项一’两个字选项的children：
![355007713-bca1f414-ddba-49ea-a2e9-66d0d05ad7d0-1](https://github.com/user-attachments/assets/25608f47-9d45-4403-bff8-45b032b69417)
2. 三层树形结构，‘选项二’添加一层字选项，同时修改value结构：
<img width="492" alt="截屏2024-08-06 15 25 34" src="https://github.com/user-attachments/assets/ef4c5c21-fc07-42db-ba4d-1a181efa6d61">
