### ISSUE TITLE
[picker-item] 希望能增加 slot 支持

### ISSUE THREAD

**Issue by tangyouge** [Tencent/tdesign-miniprogram#3053]
### 这个功能解决了什么问题

<img width="334" alt="iShot_2024-08-06_23 34 13" src="https://github.com/user-attachments/assets/035de4ea-eef2-4ac5-83bf-11bf36db34d2">

最近有一个需求，需要给每一项 picker-item 的后面，打不同的标签，但是目前 picker-item 并不支持 slot 的形式，自定义每一项的内容。

### 你建议的方案是什么

希望 picker-item 能增加 slot 支持

**Comment by tangyouge** [comment]
希望能尽快支持下，picker-item 支持 slot 后，可以极大的提升组件使用的灵活性。

**Comment by apexracing** [comment]
同样希望能尽快picker-item 支持 slot
