### ISSUE TITLE
[Badge 微标] 添加角标后页面样式不正确

### ISSUE THREAD

**Issue by HuiDreamer** [Tencent/tdesign-miniprogram#3063]
### tdesign-miniprogram 版本

1.5.1

### 重现步骤

[Badge 微标] 再单元格cell上面添加了角标后，页面可以左右滑动，会把页面的布局大小给更改

### 期望结果

请修复

**Comment by anlyyao** [comment]
@HuiDreamer 提供代码片段

**Comment by HuiDreamer** [comment]
> @HuiDreamer 提供代码片段

您好，官方演示的TDesign UI的小程序中，就可以演示出来。在开发工具中是正常的，但是上线到小程序客户端后，手机IOS端打开便会有这样的问题

**Comment by anlyyao** [comment]
> > @HuiDreamer 提供代码片段
> 
> 您好，官方演示的TDesign UI的小程序中，就可以演示出来。在开发工具中是正常的，但是上线到小程序客户端后，手机IOS端打开便会有这样的问题
还真是😂 我们处理一下

**Comment by anlyyao** [comment]
@HuiDreamer  1.6.0 版本的badge角标使用clip-path，能避免你所提的问题，但该属性在 skyline render中不支持， 1.6.1 版本暂时会回退成伪元素处理，你的问题会在次出现，需要给cell组件手动加下溢出隐藏 overflow: hidden 。 (很抱歉带来不好的体验，在 skyline 支持clip-path属性的过程中，我们也会尝试寻找其他更优的解决方案～)

<img width="1032" alt="截屏2024-09-12 19 49 02" src="https://github.com/user-attachments/assets/0c5405b0-f403-43f7-980a-50c5b82e49ab">
