### ISSUE TITLE
t-slider组件的可触碰范围

### ISSUE THREAD

**Issue by luoxin59420** [Tencent/tdesign-miniprogram#3065]
t-slider组件的可触碰范围能否在上下两边扩大？目前感觉触碰范围较小，不容易拖动

**Comment by anlyyao** [comment]
@luoxin59420 是指那条滑轨？还是滑块？都提供了css vars，可以自行调整
<img width="391" alt="截屏2024-08-13 10 48 37" src="https://github.com/user-attachments/assets/ac383933-1c49-4799-a2ab-997bd421eaba">
