### ISSUE TITLE
[t-picker] skyline下深色模式选择器样式问题

### ISSUE THREAD

**Issue by runoob-coder** [Tencent/tdesign-miniprogram#3072]
### tdesign-miniprogram 版本

1.5.1

### 重现链接

无

### 重现步骤

t-picker__mask的background在深色模式下显示异常

### 期望结果

webview渲染，深色模式

![IMG_7656](https://github.com/user-attachments/assets/95cd35db-e60a-4b51-9b33-924b6ad7c533)

### 实际结果

skyline渲染，深色模式

![IMG_7654](https://github.com/user-attachments/assets/ea2762c0-2de6-4776-b799-b7f2bf6abc70)

**Comment by jarmywang** [comment]
linear-gradient在Skyline下有些问题，我们反馈给微信一下，目前picker暂未适配Skyline
