### ISSUE TITLE
t-radio边框失真

### ISSUE THREAD

**Issue by luoxin59420** [Tencent/tdesign-miniprogram#3075]
在真机上，选中的边框周边会失真
![image](https://github.com/user-attachments/assets/77815184-00b5-47f2-929a-df106a61daba)

**Comment by jarmywang** [comment]
我看demo还好，能麻烦提供一个最小复现的代码片段吗？

**Comment by luoxin59420** [comment]
> 我看demo还好，能麻烦提供一个最小复现的代码片段吗？

<t-radio-group value="{{ selectSensRange || 3 }}" t-class="radio-group" bind:change="handleRangeSet">
          <t-radio
            wx:for="{{ rangList }}"
            wx:key="index"
            class="radio-item"
            icon="dot"
            block="{{false}}"
            label="{{ item.label }}"
            value="{{ item.order }}"
            placement="right"
          />
        </t-radio-group>

![image](https://github.com/user-attachments/assets/e05ee303-710e-4d75-8002-4346c43b8afd)

在真机上边框就变得像虚线一样，不饱满

**Comment by jarmywang** [comment]
![image](https://github.com/user-attachments/assets/639fc0e5-29bf-4c2f-bc96-9c9518a02e15)
官方demo在真机看着没问题：
https://developers.weixin.qq.com/s/GW6DrimI7hSV

没有看到你那边的代码，猜测是box-sizing的原因？@luoxin59420
