### ISSUE TITLE
[Slide] dragend 拿不到值

### ISSUE THREAD

**Issue by CrossLee** [Tencent/tdesign-miniprogram#3082]
### tdesign-miniprogram 版本

1.5.1

### 重现步骤

wxml
`<t-slider bind:dragend="dragendAge" id="sliderAge" slot="note" t-class-bar-active="filterSlideActive" min="18" max="100" step="2" theme="capsule" label="true" defaultValue="{{ [20, 30] }}" range />
`

js
```
  dragendAge(event){
console.log(event);
  },
```

### 期望结果

能获取到滑动的值

### 实际结果

<img width="338" alt="image" src="https://github.com/user-attachments/assets/78038415-28ce-4735-ada1-ea769e4bd95c">
<img width="715" alt="image" src="https://github.com/user-attachments/assets/1884f302-016b-45bb-8491-c6969f38ba7e">

### 补充说明

change 事件是可以获取到的

<img width="679" alt="image" src="https://github.com/user-attachments/assets/f8e7ee38-533a-4921-a6c3-fc91dee5e819">

**Comment by anlyyao** [comment]
我们讨论一下 dragend 事件是否也带上变更值、
