### ISSUE TITLE
[Toast] 代码质量检查异常

### ISSUE THREAD

**Issue by hqzh** [Tencent/tdesign-miniprogram#3086]
### tdesign-miniprogram 版本

1.5.1

### 重现步骤
```js
import Toast from 'tdesign-miniprogram/toast/index'
```

组件内有使用，代码质量检查还是有下图的提示

![image](https://github.com/user-attachments/assets/32826ae0-e3a6-402c-b381-57ec0a13ffab)

### 期望结果

代码质量不报警

### 实际结果

会报警

### 基础库版本

3.5.1

**Comment by jarmywang** [comment]
@hqzh 所有引入的地方改成 `import { Toast } from 'tdesign-miniprogram';`

**Comment by hqzh** [comment]
@anlyyao

**Comment by anlyyao** [comment]
@hqzh 重新看了一下项目包，确实是主包内没有使用 Toast，仅在分包使用了，质量告警时对的。message 没带来告警是因为 在主包内部也刚好使用了==
