### ISSUE TITLE
[badge][drawer][side-bar-item][tag] 微信小程序开始替换成skyline引擎后疯狂报错。

### ISSUE THREAD

**Issue by anran-young** [Tencent/tdesign-miniprogram#3087]
### tdesign-miniprogram 版本

1.5.1

### 重现步骤

微信小程序开始替换成skyline引擎后疯狂报错。
badge有两行重复的属性
drawer，tag，side-bar-item有无效属性渲染也异常

### 期望结果

配合skyline别再报错了

### 实际结果

- /miniprogram_npm/tdesign-miniprogram/badge/badge.wxml:28:4-28:15: Warn: duplicated attribute
- /miniprogram_npm/tdesign-miniprogram/badge/badge.wxml:29:4-29:14: Warn: duplicated attribute
- /miniprogram_npm/tdesign-miniprogram/drawer/drawer.wxml:25:8-25:10: Warn: invalid attribute prefix
- /miniprogram_npm/tdesign-miniprogram/side-bar-item/side-bar-item.wxml:11:2-11:12: Warn: duplicated attribute
- /miniprogram_npm/tdesign-miniprogram/tag/tag.wxml:20:10-20:13: Warn: invalid attribute

**Comment by anran-young** [comment]
喵

**Comment by anlyyao** [comment]
@anran-young Warn 叫做告警
