### ISSUE TITLE
[Tabs] 可否添加一个css变量用来控制字体的大小？

### ISSUE THREAD

**Issue by Zlianxin** [Tencent/tdesign-miniprogram#3089]
### 这个功能解决了什么问题

现在是有一个变量`--td-tab-font-size`是控制文字大小的，但是实际的业务中会出现选中项目的字体大小会比未选中项目大的情况，所以希望添加css变量去单独控制选中项目和未选中项目。

### 你建议的方案是什么

现在的css变量`--td-tab-font-size`是写在最外层的css样式类`.t-tabs`中的，可以在`t-tabs__item--active`和`t-tabs__item`这两个样式类中去控制字体的大小。

**Comment by jarmywang** [comment]
@Zlianxin 暂不考虑增加此变量，已经提供了t-class-active的外部样式，你还可以直接覆盖 .t-tabs__item--active
