### ISSUE TITLE
Checkbox 多选框 css示例代码

### ISSUE THREAD

**Issue by herohql521** [Tencent/tdesign-miniprogram#3090]
### tdesign-miniprogram 版本

是

### 重现步骤

父元素flex，子元素flex1而且是靠margin-left设置间距的，示例只循环了3个不会有问题。当数量一多 只想一行三个，示例的css代码几乎需要删了重写

### 期望结果

父元素可以justify-content: flex-start;flex-wrap: wrap;  子元素通过宽度自动换行

**Comment by anlyyao** [comment]
@herohql521 先不讨论示例代码样式问题。 你意思就是，直接cv到业务代码中，100%符合你的场景需求，才能不被你叫做"一塌糊涂"，是这个意思吗？

**Comment by herohql521** [comment]
好吧你说的有道理，感觉选项根据自己的宽度和个数 换行比较好，flex1挤在一行 适用选项数量较少的情况，通常都会超过3个以上

**Comment by anlyyao** [comment]
> 好吧你说的有道理，感觉选项根据自己的宽度和个数 换行比较好，flex1挤在一行 适用选项数量较少的情况，通常都会超过3个以上

👌 我们会尽快做出调整以适应更多的使用场景。这是一个开源项目，欢迎直接提 pr 到仓库，欢迎 🏹～
