### ISSUE TITLE
[t-tag] 使用icon不能显示

### ISSUE THREAD

**Issue by burningimlam** [Tencent/tdesign-miniprogram#3091]
### tdesign-miniprogram 版本

1.5.1

### 重现步骤

按照文档的说法

直接添加icon名就可以显示图标 实测只有类似discount单个单词的情况才能显示图标 其他的均不能显示在我这里已经尝试过（user-password，user-search，user-safety，pen-quill）

### 期望结果

正常显示

### 实际结果

未显示

**Comment by anlyyao** [comment]
@burningimlam 测试没有问题，请确认版本是否正确。

这里是代码片段 https://developers.weixin.qq.com/s/0A0UMFmj70Tt
效果：<img width="359" alt="截屏2024-08-23 15 32 34" src="https://github.com/user-attachments/assets/85ca9565-8fa5-4773-8287-e05259e043a3">

**Comment by vaint** [comment]
直接使用t-icon也遇到了同样的问题，带有-的icon不显示。比如：name="app"能显示，name="sound-mute"则不行。

**Comment by burningimlam** [comment]
> 直接使用t-icon也遇到了同样的问题，带有-的icon不显示。比如：name="app"能显示，name="sound-mute"则不行。

遇到这个问题的时候我也没采取什么措施 你可以试试看重启系统或者清一下微信开发者软件的缓存 我现在是可以正常使用了

**Comment by vaint** [comment]
> > 直接使用t-icon也遇到了同样的问题，带有-的icon不显示。比如：name="app"能显示，name="sound-mute"则不行。
> 
> 遇到这个问题的时候我也没采取什么措施 你可以试试看重启系统或者清一下微信开发者软件的缓存 我现在是可以正常使用了

好的，我试试。多谢。
