### ISSUE TITLE
t-tabs带内容区选项卡切换延迟卡顿

### ISSUE THREAD

**Issue by herohql521** [Tencent/tdesign-miniprogram#3095]
### tdesign-miniprogram 版本

1.4.2

### 重现步骤

官网示例中带内容区选项卡，在开发者工具中打开的示例存在切换延迟卡顿的问题，约3秒的时间响应。开始以为是我自己的问题，结果发现官方提供的代码演示也存在

**Comment by herohql521** [comment]
开发者工具的问题，真机无此问题。

**Comment by anlyyao** [comment]
@herohql521 以真机效果为准，那我这边就先close了， 有新的问题再重新开issue
