### ISSUE TITLE
[t-upload] 真机draggable属性异常

### ISSUE THREAD

**Issue by Dounyl** [Tencent/tdesign-miniprogram#3097]
### tdesign-miniprogram 版本

1.5.0

### 重现步骤

带有**draggable**的t-upload的标签在**安卓真机端**有两个问题。
1. 无法正常拖拉拽，长按图片后就会卡住
2. files指定的图片第一次不会显示，只有触发上传后才会显示

### 补充说明

非skyline渲染

**Comment by Dounyl** [comment]
发现了问题，app.json配置"lazyCodeLoading": "requiredComponents"会导致该问题

**Comment by jby0107** [comment]
> 发现了问题，app.json配置"lazyCodeLoading": "requiredComponents"会导致该问题

@Dounyl lazyCodeLoading不太应该会导致这个问题。之前排查过，设置"ComponentFramework": "glass-easel"会导致这个问题，因为glass-easel不支持wxs响应事件

**Comment by Dounyl** [comment]
> > 发现了问题，app.json配置"lazyCodeLoading": "requiredComponents"会导致该问题
> 
> @Dounyl lazyCodeLoading不太应该会导致这个问题。之前排查过，设置"ComponentFramework": "glass-easel"会导致这个问题，因为glass-easel不支持wxs响应事件。可以看看这下边的讨论 #2580

是的，我发现在项目中，只要同时含有
  "lazyCodeLoading": "requiredComponents",
  "componentFramework": "glass-easel",
就会有这个问题，而只包含一个没有该问题，所以我应该删掉  "componentFramework": "glass-easel"配置吗？
