### ISSUE TITLE
t-tabs 设置了 animation 之后，如果挨着点击tab，t-tab-panel 的内容能显示，但是如果间隔点击tab，t-tab-panel的内容就不显示

### ISSUE THREAD

**Issue by guoyutao** [Tencent/tdesign-miniprogram#3098]
### tdesign-miniprogram 版本

1.5.1

### 重现步骤

t-tabs 设置了 animation 之后，如果挨着点击tab，t-tab-panel
的内容能显示，但是如果间隔点击tab，t-tab-panel的内容就不显示

**Comment by jarmywang** [comment]
@guoyutao 麻烦来个最小复现片段与视频
