### ISSUE TITLE
[Upload] Upload上传后，点击图片的事件，能否完全给开发者自定义

### ISSUE THREAD

**Issue by dadtakesmefly** [Tencent/tdesign-miniprogram#3099]
### 这个功能解决了什么问题

因为有的业务需求，点击图片后，实现预览，需要有删除按钮。这样可以和ImageViewer结合。但是现在因为官方默认使用了preview API，所以这个没办法自定义。

### 你建议的方案是什么

建议将图片点击的事件完全暴露出来。给一个配置，默认使用官方的预览或者开发者自定义实现预览。

**Comment by dadtakesmefly** [comment]
目前我自己打了一个patches，实现了想要的效果。

**Comment by dadtakesmefly** [comment]
目前我自己打了一个patches，实现了想要的效果。

**Comment by jarmywang** [comment]
感谢建议，目前暂不考虑，可以通过hook onProofTap方法改掉原来的处理方式

**Comment by supermebing** [comment]
> hook onProofTap

hook onProofTap  麻烦问下这个具体怎么实现的
