### ISSUE TITLE
Tabs: t-tabs__track has a  wrong default position

### ISSUE THREAD

**Issue by herohql521** [Tencent/tdesign-miniprogram#3104]
### tdesign-miniprogram 版本

1.4.2

### 重现步骤

popup中含有一个tabs切换，当点开popup后，选项卡的默认选中状态正常，但是t-tabs__track异常，样式中transform: translateX(0px); 并未进行初始化。
![image](https://github.com/user-attachments/assets/fdd563a2-7b9a-464e-aee9-f1c9276613bc)

**Comment by herohql521** [comment]
已解决
解决方案在popup显示的回调中，获取tabs示例，然后手动调取一下计算方法，代码如下
 const child = this.selectComponent('.my_tab');
 child.setTrack()

**Comment by jarmywang** [comment]
@herohql521 感谢分享
