### ISSUE TITLE
[t-image] loading时图片加载错位

### ISSUE THREAD

**Issue by hqzh** [Tencent/tdesign-miniprogram#3107]
### tdesign-miniprogram 版本

1.6.0

### 重现代码
```js
<t-image src="https://transpaas.sutpc.com/transpaas/api/v1/file/upload-common/314097b81f9546dbba7405cb0f4481ef.jpg" mode="aspectFill" width="160rpx" height="160rpx" aria-label="collect-file"></t-image>
```

### 重现步骤

加载至渲染的时候
![130f0523320784e69612fda84f5724d](https://github.com/user-attachments/assets/96b924c3-bba4-4d35-9f32-398b9ff24ed1)
加载成功的时候
![44079f8b1e1726021a5388c7a06129f](https://github.com/user-attachments/assets/44884535-3a3c-4811-b0ea-399edbe49085)

### 期望结果

不要错位

### 实际结果

错位

### 基础库版本

3.5.1

**Comment by huxinhai** [comment]
未加载完成的时候 给图片添加opacity:0 或者  transform:scale(0)

**Comment by anlyyao** [comment]
其实不是 host选择器没生效， 是加载中时图片定位问题，可以试试覆盖组件内部 .t-image--lazy 样式

```css
 .t-image--lazy {
    position: absolute;
    top: -100%;
    left: 0;
  }

```

**Comment by huxinhai** [comment]
我试了一下 通过在最外层包了一个view标签 写上position: relative  是没问题的

**Comment by anlyyao** [comment]
> 我试了一下 通过在最外层包了一个view标签 写上position: relative 是没问题的

这是最好的方式。实际上当时选用 host 选择器的原因就是 TImage 组件没有根节点 😅，为了不产生DOM改动，所以当时拒绝了组件补充根节点而建议用 host。 我们会重新评估是否给组件增加根节点、

**Comment by huxinhai** [comment]
> > 我试了一下 通过在最外层包了一个view标签 写上position： relative 是没问题的
> 
> 这是最好的方式。实际上当时选用 host 选择器的原因就是 TImage 组件没有根节点 😅 ，为了不产生DOM改动，所以当时拒绝了组件补充根节点而建议用 host。我们会重新评估是否给组件增加根节点、

其实我还想知道为啥你们不同意使用opacity:0 或者 transform:scale（0） 哈哈哈  这样有什么不好的地方么  学习一下

**Comment by anlyyao** [comment]
> > > 我试了一下 通过在最外层包了一个view标签 写上position： relative 是没问题的
> > 
> > 
> > 这是最好的方式。实际上当时选用 host 选择器的原因就是 TImage 组件没有根节点 😅 ，为了不产生DOM改动，所以当时拒绝了组件补充根节点而建议用 host。我们会重新评估是否给组件增加根节点、
> 
> 其实我还想知道为啥你们不同意使用opacity:0 或者 transform:scale（0） 哈哈哈 这样有什么不好的地方么 学习一下

没有不好！ 也可以的。 目前的情形下  不管是 opacity 、transform 还是top left ，目的都是为了加载中的时候 图片节点可以"消失"。 但其实"错位"的原因还是 图片节点 定位不准，没有处于预期的加载中/失败占位节点的下方。

**Comment by hqzh** [comment]
> > 我试了一下 通过在最外层包了一个view标签 写上position: relative 是没问题的
> 
> 这是最好的方式。实际上当时选用 host 选择器的原因就是 TImage 组件没有根节点 😅，为了不产生DOM改动，所以当时拒绝了组件补充根节点而建议用 host。 我们会重新评估是否给组件增加根节点、

那不是业务代码就要嵌套一层父节点，万一我父节点需要比如float:let呢？

**Comment by hqzh** [comment]
![image](https://github.com/user-attachments/assets/ee9c5fa0-1209-4048-88e8-9288a0f5ba01)
```
    <view class="usermotto" style="position: relative;">
      <text class="user-motto">{{motto}}</text>
      <t-button size="large" variant="outline" theme="primary" bind:tap="showText" block>错误提示</t-button>
      <t-image src="https://transpaas.sutpc.com/transpaas/api/v1/file/upload-common/314097b81f9546dbba7405cb0f4481ef.jpg" mode="aspectFill" width="160rpx" height="160rpx" aria-label="collect-file"></t-image>
    </view>
```js
我试了一下，还是会错位，看起来错位是从父元素的top：0开始的，这是不是说明套一层还不能有其它元素。

**Comment by huxinhai** [comment]
> ![图像](https://private-user-images.githubusercontent.com/26128706/363083705-ee9c5fa0-1209-4048-88e8-9288a0f5ba01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMDM4NDgsIm5iZiI6MTcyNTAwMzU0OCwicGF0aCI6Ii8yNjEyODcwNi8zNjMwODM3MDUtZWU5YzVmYTAtMTIwOS00MDQ4LTg4ZTgtOTI4OGEwZjViYTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDA3MzkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwYjQ0NTdhZjBjYTUxOTc3NGFkZDBjMGQyNDQ3YmFlZmI5Yjg3YzIzOTZjNDY3NjlhNzJiZDc3M2YxN2YxNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iXcqCJF8xAxlWFhH38lFuWp6q1oUpbPdLVnxlEQJbxQ)
> 
> ```
> <view class="usermotto" style="position: relative;">
>       <text class="user-motto">{{motto}}</text>
>       <t-button size="large" variant="outline" theme="primary" bind:tap="showText" block>错误提示</t-button>
>       <t-image src="https://transpaas.sutpc.com/transpaas/api/v1/file/upload- 
>       common/314097b81f9546dbba7405cb0f4481ef.jpg" mode="aspectFill" width="160rpx" height="160rpx"></t-image>
> </view>
> ```
> 
> 我试了一下，还是会错位，看起来错位是从父元素的top：0开始的，这是不是说明套一层还不能有其它元素。

  我觉得是你理解错了  我们说的是在image组件源码里面套 并不是说在业务代码里套 哈哈哈

**Comment by hqzh** [comment]
那我还是mini_npm里面opacity:0 应急先，希望1.6.1能修复这个问题

**Comment by anlyyao** [comment]
@hqzh 下个版本会修复的，或者提供一个通用处理方案 🤔

**Comment by anlyyao** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/26128706/363083705-ee9c5fa0-1209-4048-88e8-9288a0f5ba01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMDM4NDgsIm5iZiI6MTcyNTAwMzU0OCwicGF0aCI6Ii8yNjEyODcwNi8zNjMwODM3MDUtZWU5YzVmYTAtMTIwOS00MDQ4LTg4ZTgtOTI4OGEwZjViYTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDA3MzkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwYjQ0NTdhZjBjYTUxOTc3NGFkZDBjMGQyNDQ3YmFlZmI5Yjg3YzIzOTZjNDY3NjlhNzJiZDc3M2YxN2YxNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iXcqCJF8xAxlWFhH38lFuWp6q1oUpbPdLVnxlEQJbxQ)
> > ```
> > <view class="usermotto" style="position: relative;">
> >       <text class="user-motto">{{motto}}</text>
> >       <t-button size="large" variant="outline" theme="primary" bind:tap="showText" block>错误提示</t-button>
> >       <t-image src="https://transpaas.sutpc.com/transpaas/api/v1/file/upload- 
> >       common/314097b81f9546dbba7405cb0f4481ef.jpg" mode="aspectFill" width="160rpx" height="160rpx"></t-image>
> > </view>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我试了一下，还是会错位，看起来错位是从父元素的top：0开始的，这是不是说明套一层还不能有其它元素。
> 
> 我觉得是你理解错了 我们说的是在image组件源码里面套 并不是说在业务代码里套 哈哈哈

在严谨一点， 其实只要能在业务代码中覆盖组件内部  .t-image--lazy 类样式就行  👀👀

**Comment by anlyyao** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/26128706/363083705-ee9c5fa0-1209-4048-88e8-9288a0f5ba01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMDM4NDgsIm5iZiI6MTcyNTAwMzU0OCwicGF0aCI6Ii8yNjEyODcwNi8zNjMwODM3MDUtZWU5YzVmYTAtMTIwOS00MDQ4LTg4ZTgtOTI4OGEwZjViYTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDA3MzkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwYjQ0NTdhZjBjYTUxOTc3NGFkZDBjMGQyNDQ3YmFlZmI5Yjg3YzIzOTZjNDY3NjlhNzJiZDc3M2YxN2YxNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iXcqCJF8xAxlWFhH38lFuWp6q1oUpbPdLVnxlEQJbxQ)
> > ```
> > <view class="usermotto" style="position: relative;">
> >       <text class="user-motto">{{motto}}</text>
> >       <t-button size="large" variant="outline" theme="primary" bind:tap="showText" block>错误提示</t-button>
> >       <t-image src="https://transpaas.sutpc.com/transpaas/api/v1/file/upload- 
> >       common/314097b81f9546dbba7405cb0f4481ef.jpg" mode="aspectFill" width="160rpx" height="160rpx"></t-image>
> > </view>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我试了一下，还是会错位，看起来错位是从父元素的top：0开始的，这是不是说明套一层还不能有其它元素。
> 
> 我觉得是你理解错了 我们说的是在image组件源码里面套 并不是说在业务代码里套 哈哈哈

要不要再来个pr哦 👀，TImage外层加一个父节点吧，节点上写相对定位吧，no other way···

**Comment by huxinhai** [comment]
> > > ![图像](https://private-user-images.githubusercontent.com/26128706/363083705-ee9c5fa0-1209-4048-88e8-9288a0f5ba01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMDM4NDgsIm5iZiI6MTcyNTAwMzU0OCwicGF0aCI6Ii8yNjEyODcwNi8zNjMwODM3MDUtZWU5YzVmYTAtMTIwOS00MDQ4LTg4ZTgtOTI4OGEwZjViYTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDA3MzkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwYjQ0NTdhZjBjYTUxOTc3NGFkZDBjMGQyNDQ3YmFlZmI5Yjg3YzIzOTZjNDY3NjlhNzJiZDc3M2YxN2YxNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iXcqCJF8xAxlWFhH38lFuWp6q1oUpbPdLVnxlEQJbxQ)
> > > ```
> > > <view class="usermotto" style="position: relative;">
> > >       <text class="user-motto">{{motto}}</text>
> > >       <t-button size="large" variant="outline" theme="primary" bind:tap="showText" block>错误提示</t-button>
> > >       <t-image src="https://transpaas.sutpc.com/transpaas/api/v1/file/upload- 
> > >       common/314097b81f9546dbba7405cb0f4481ef.jpg" mode="aspectFill" width="160rpx" height="160rpx"></t-image>
> > > </view>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 我试了一下，还是会错位，看起来错位是从父元素的top：0开始的，这是不是说明套一层还不能有其它元素。
> > 
> > 
> > 我觉得是你理解错了 我们说的是在image组件源码里面套 并不是说在业务代码里套 哈哈哈
> 
> 要不要再来个pr哦 👀，TImage外层加一个父节点吧，节点上写相对定位吧，no other way···

 好 我晚点来个pr吧

**Comment by huxinhai** [comment]
套父节点的话 是不是你们的t-class 也要改

**Comment by anlyyao** [comment]
> 套父节点的话 是不是你们的t-class 也要改

是的 class t-class 移到父节点上， 对应补充 t-class-error、t-class-image 外部样式类
