### ISSUE TITLE
[side-bar] 编译出错

### ISSUE THREAD

**Issue by guanzongjiang** [Tencent/tdesign-miniprogram#3110]
### tdesign-miniprogram 版本

1.6.0

### 重现步骤

1. https://tdesign.tencent.com/miniprogram/components/side-bar 按照文档sidebar操作
2. 用的小程序模板tdesign模板 版本1.0.0，发现原模板没有sidebar组件，于是升级tdesign
3. npm i tdesign-miniprogram -S --production 使用这种方式只能升级到1.6.0
4. 升级完后可以找到sidebar组件，miniprogram_npm/tdesign-miniprogram/side-bar/side-bar.js，但是重新构建npm，编译后报错，"miniprogram_npm/tdesign-miniprogram/side-bar/side-bar" (using by "components/goods-list-side-bar/index")

### 期望结果

正常展示sidebar效果

### 实际结果

Component is not found in path "miniprogram_npm/tdesign-miniprogram/side-bar/side-bar" (using by "components/goods-list-side-bar/index")(env: macOS,mp,1.06.2405020; lib: 3.5.4)

Component is not found in path "miniprogram_npm/tdesign-miniprogram/side-bar-item/side-bar-item" (using by "components/goods-list-side-bar/index")(env: macOS,mp,1.06.2405020; lib: 3.5.4)

### 基础库版本

1.6.0

**Comment by jarmywang** [comment]
个例问题，解决参考：
1、清全部缓存，重新构建npm，重新编译，重启ide
2、目录不对，查文档了解miniprogramRoot相关知识
