### ISSUE TITLE
[t-NavBar] 当微信小程序右上角胶囊按钮收回时，TDesign NavBar 为防止遮挡元素而淡出的导航栏标题文字未能成功恢复原状，导致标题栏空白

### ISSUE THREAD

**Issue by ArcticFoxPro** [Tencent/tdesign-miniprogram#3126]
### tdesign-miniprogram 版本

1.6.0

### 重现链接

微信搜一搜“TDesign组件库”（即你们自家的示例小程序会复现此问题）

### 重现步骤

前置条件：**微信侧向测试设备的微信客户端云控了微信小程序全局翻译能力**，且被调试小程序是 WebView 模式

1. 打开被调试小程序，右上角胶囊按钮伸长以显示全局翻译功能
2. 等待若干秒，右上角胶囊按钮缩回原状，此时即可看到导航栏无法恢复原状的 Bug

### 期望结果

导航栏恢复原状

此外，希望在页面代码内可以通过 TD 提供的 API 自定义是否启用胶囊遮挡自动规避能力

### 实际结果

导航栏文字为空白

![IMG_20240906_103553.jpg](https://github.com/user-attachments/assets/448415aa-9177-4065-b88b-2a08d0d10e6f)

![Screenshot_2024-09-06-11-38-24-581_com.tencent.mm-edit.jpg](https://github.com/user-attachments/assets/ae215d16-6931-4f49-a0fb-4fafb781578d)

### 基础库版本

3.5.6

### 补充说明

微信 Android 客户端：8.0.51
真机设备：Xiaomi 14 Pro 附带 Android 14 七月补丁

与此问题相关的 issue：#2802

**Comment by ArcticFoxPro** [comment]
我这里打了下 leftRect.right、centerRect.right 和 capsuleRect.left 的日志，应该是 TD 这里：

https://github.com/Tencent/tdesign-miniprogram/blob/develop/src%2Fnavbar%2Fnavbar.ts#L119-L120

```TypeScript
        getRect(this, `.${this.data.classPrefix}__left`),
        getRect(this, `.${this.data.classPrefix}__center`),
```

通过 getRect() 获取 TD 导航栏标题组件边距的选择器出了问题。无论标题长度是多少，是否是 slot 插入标题，都获取到的是固定值，都大于胶囊收回态左坐标，因此导航栏标题就都被隐藏了。

![928D806C6CD1003AD9CF18F138797A7B](https://github.com/user-attachments/assets/e5817bfb-ea0e-474e-9647-3c7a1c9e150f)

**Comment by Mengfanpro** [comment]
什么时候能修好

**Comment by anlyyao** [comment]
@ArcticFoxPro @Mengfanpro sorry 久等了～，刚看了一下安卓上确实有问题，我本周处理完，下个版本可带（本周or下周发版）

**Comment by ArcticFoxPro** [comment]
> sorry 久等了～，刚看了一下安卓上确实有问题，我本周处理完，下个版本可带（本周or下周发版）

好可怕的公司，这么晚还加班
