### ISSUE TITLE
[t-badge] skyline渲染下ribbon样式异常

### ISSUE THREAD

**Issue by runoob-coder** [Tencent/tdesign-miniprogram#3130]
### tdesign-miniprogram 版本

1.6.0

### 期望结果

![IMG_8043](https://github.com/user-attachments/assets/9a1f94de-73a6-41e0-a1a8-c7f186315e55)

### 实际结果

![IMG_8044](https://github.com/user-attachments/assets/99d7fb5d-940c-4ea7-89c4-78376a9b732e)

### 补充说明

该问题时由1.6.0的[#3074](https://github.com/Tencent/tdesign-miniprogram/pull/3074) 提交引起的，在skyline模式下未测试过

**Comment by anlyyao** [comment]
#3074 中为了处理角标溢出的问题改用clip-path实现， skyline不支持 clip-path
