### ISSUE TITLE
[组件名称] t-textarea__placeholder 设置覆盖无效

### ISSUE THREAD

**Issue by cfping** [Tencent/tdesign-miniprogram#3135]
### tdesign-miniprogram 版本

^1.4.5

### 重现步骤

  <view class="textarea-section">
    <t-textarea value="{{evaluateVal}}"placeholder="满意你就夸一夸，点击这里输入评价"
    placeholder-style="font-weight: 400;font-size: 32rpx;color: red;" 
    disableDefaultPadding bind:change="handleEvaluateInputChange"/>
  </view>
  

  .textarea-section  .t-textarea__placeholder {
  color: blue !important; 
}

### 基础库版本

3.5.4

**Comment by cfping** [comment]
<view class="textarea-section">
    <t-textarea value="{{evaluateVal}}"placeholder="点击这里输入评价"
    placeholder-style="font-weight: 400;font-size: 32rpx;color: red;" 
    disableDefaultPadding bind:change="handleEvaluateInputChange"/>
  </view>
  

  .textarea-section  .t-textarea__placeholder {
  color: blue !important; 
}

**Comment by cfping** [comment]
` <view class="textarea-section">
    <t-textarea value="{{evaluateVal}}"placeholder="满意你就夸一夸，点击这里输入评价"
    placeholder-style="font-weight: 400;font-size: 32rpx;color: red;" 
    disableDefaultPadding bind:change="handleEvaluateInputChange"/>
  </view>`

**Comment by anlyyao** [comment]
> ` <view class="textarea-section"> <t-textarea value="{{evaluateVal}}"placeholder="满意你就夸一夸，点击这里输入评价" placeholder-style="font-weight: 400;font-size: 32rpx;color: red;" disableDefaultPadding bind:change="handleEvaluateInputChange"/> </view>`

页面的json文件，加一下 "styleIsolation": "apply-shared",

**Comment by cfping** [comment]
在webview模式下是可以的,skyline模式下是无效的

**Comment by anlyyao** [comment]
> 在webview模式下是可以的,skyline模式下是无效的


[placeholder-class 是WebView 特有属性](https://developers.weixin.qq.com/miniprogram/dev/component/textarea.html)，skyline本身就不支持。如果只有修改占位符颜色需求，可以使用 
placeholder-style。
