### ISSUE TITLE
DropdownMenu 下拉菜单 中如何使用 TreeSelect

### ISSUE THREAD

**Issue by ks3dev** [Tencent/tdesign-miniprogram#3145]
### 这个功能解决了什么问题

https://tdesign.tencent.com/miniprogram/components/dropdown-menu?tab=api  
文档中提到 
**options-layout           | String | columns | 已废弃。选项排列；不再支持 tree 布局，可与 treeSelect 配合使用**
请提供一下示例，谢谢！

### 你建议的方案是什么

示例不完整，请提供示例

**Comment by anlyyao** [comment]
有默认插槽的，支持自定义菜单内容，使用如下：

```
// 关键代码
<t-dropdown-menu>
  <t-dropdown-item label="测试1">
    <t-tree-select options="{{options}}" value="{{value}}" bind:change="onTreeChange" />
  </t-dropdown-item>
  <t-dropdown-item label="测试2" />
</t-dropdown-menu>
```
