### ISSUE TITLE
[t-popup] 弹出层组件的遮罩层不能覆盖全屏

### ISSUE THREAD

**Issue by yinhexianyin** [Tencent/tdesign-miniprogram#3147]
### tdesign-miniprogram 版本

1.6.0

### 重现步骤

<t-popup
  visible="{{visible}}"
  usingCustomNavbar
  bind:visible-change="onVisibleChange"
  placement="{{cur.value || 'top'}}"
>
  <view class="block block--{{cur.value}}">{{cur.text}}</view>
</t-popup>

<t-button
  wx:for="{{position}}"
  wx:key="index"
  block
  size="large"
  variant="outline"
  theme="primary"
  bind:tap="handlePopup"
  data-item="{{item}}"
  t-class="wrapper"
>
  {{item.text}}
</t-button>

![微信截图_20240913155450](https://github.com/user-attachments/assets/202b21a7-f8b5-4169-934e-226ef99949a7)

### 期望结果

能像官网演示实例一样遮罩层覆盖全屏

### 实际结果

顶部有一段区域无法被遮住。在调试器当中看到一个aria-label="关闭"的view组件，其style属性中有top=60rpx，勾选掉该属性后可以覆盖全屏。从1.5.4版本升级到最新的1.6.0后返现问题依然存在

### 基础库版本

3.5.7

**Comment by anlyyao** [comment]
@yinhexianyin 非使用自定义导航的页面，不要开启usingCustomNavbar属性，我们的示例使用的是自定义导航

**Comment by yinhexianyin** [comment]
> @yinhexianyin 非使用自定义导航的页面，不要开启usingCustomNavbar属性，我们的示例使用的是自定义导航

你说的对，去掉这个属性就好了
