### ISSUE TITLE
[fab] 无法去掉边框

### ISSUE THREAD

**Issue by kubamya** [Tencent/tdesign-miniprogram#3150]
### tdesign-miniprogram 版本

1.6.0

### 重现步骤

通过custom-style和重写 .t-button--primary的样式都无法去掉边框
![image](https://github.com/user-attachments/assets/f76f5d23-c40c-4810-9df6-e24fd74fb430)
![image](https://github.com/user-attachments/assets/cfd50ce3-98d6-4ef9-8309-7811356448ba)
![image](https://github.com/user-attachments/assets/7b351e5d-4cf8-4d5e-bd96-6fd88505b483)

### 期望结果

提供相关配置项或修复

### 基础库版本

3.3.5

**Comment by anlyyao** [comment]
@kubamya 边框是::after实现的。

```
.t-button--primary::after {
  border: none !important;
}
```

更推荐的方式：
```
page {
  --td-button-primary-bg-color: green;
  --td-button-primary-border-color: green;
}
```

**Comment by kubamya** [comment]
感谢解答
