### ISSUE TITLE
[Tabs] t-tab 选项卡内容面板的顺序错乱

### ISSUE THREAD

**Issue by zhelingwang** [Tencent/tdesign-miniprogram#3153]
### tdesign-miniprogram 版本

"tdesign-miniprogram": "^1.6.1"  基础库版本: 3.3.5

### 重现链接

https://developers.weixin.qq.com/s/s7MwDjmw7pUN

### 重现步骤

![image](https://github.com/user-attachments/assets/241763f7-cc1d-4d7a-8908-8f218c9667da)

1.说明: 如代码片段所示, 只有第三个tab下是空数据, 其他tab下均有数据; 
2.在页面加载完后, 直接点击第四个tab"跑一趟腿"(或点击第五个tab), 显示的是空白, 此时再点击第三个tab"帮取送", 本应显示在"跑一趟腿"tab-panel下的内容跑到"帮去送"的tab-panel下了;
3.重新来回切换第三个tab"帮取送"之后再切换到第四第五个tab后才是正常的展示对应的内容数据

### 期望结果

对应tab展示对应数据内容

### 实际结果

tab内容面板的顺序出现错乱

### 基础库版本

3.5.5

**Comment by zhelingwang** [comment]
关闭动画, 就没有这个问题
animation="{{ { duration: 0.6 } }}"

**Comment by huxinhai** [comment]
> 关闭动画, 就没有这个问题 animation="{{ { duration: 0.6 } }}"

可以改一下源码把那个原来的display:none 改为height:0;overflow:visible; 就可以了 后续等官方大大修复了

**Comment by huxinhai** [comment]
> > 关闭动画, 就没有这个问题 animation="{{ { duration: 0.6 } }}"
> 
> 可以改一下源码把那个原来的display:none 改为height:0;overflow:visible; 就可以了 后续等官方大大修复了

但是这样改就不使用动画就有问题了 看你取舍了

**Comment by zhelingwang** [comment]
> > 关闭动画, 就没有这个问题 animation="{{ { duration: 0.6 } }}"
> 
> 可以改一下源码把那个原来的display:none 改为height:0; 就可以了 后续等官方大大修复了

我使用样式覆盖的方式好像也可以
`
view.t-tab-panel:not(.t-is-active) {
  display: block !important;
  height: 0 !important;
}
`
