### ISSUE TITLE
[t-slider] Win10系统，滑块无法拖动

### ISSUE THREAD

**Issue by china-live** [Tencent/tdesign-miniprogram#3158]
### tdesign-miniprogram 版本

1.4.1

### 重现链接

无

### 重现步骤

无法确定如果重现

### 期望结果

滑块可以拖动

### 实际结果

滑块无法拖动

### 补充说明

奇怪的问题，在家里台式机上，Win10系统，模拟器和真机调试均无法拖动，但可以看到值是有变化的。
相同的代码，在办公室两台机器上和笔记本上均正常工作（Win11系统）。
一开始以为是基础库版本问题或开发者工具问题，配置成一致，问题还是存在。
不存在用法错误问题，屏蔽自己的代码，完全拷贝的 https://tdesign.tencent.com/miniprogram/components/slider 示例同样无法正常拖动。

![动画](https://github.com/user-attachments/assets/a069802a-986f-474e-a123-8db0a46cdbc0)

**Comment by anlyyao** [comment]
@china-live 真机机型、系统提供一下

**Comment by china-live** [comment]
iphone12  iOS 17.7  
感觉这个和手机机型和系统没关系
我没有更多的环境可以测试，两台Win11上的开发者工具中均能正常工作，只有家里Win10上的这样。

**Comment by anlyyao** [comment]
@china-live 主要是因为我这边没有win系统😅，而我在mac上无法复现该问题，因此我只能尝试通过真机先复现问题，在进行定位和修复

**Comment by anlyyao** [comment]
无法复现······，暂时关闭·····
