### ISSUE TITLE
进度条，可以自定义总共有多少，而不是默认100

### ISSUE THREAD

**Issue by 2352413035** [Tencent/tdesign-miniprogram#3161]
### 这个功能解决了什么问题

进度条，可以自定义总共有多少，而不是默认100

### 你建议的方案是什么

进度条，可以自定义总共有多少，而不是默认100

**Comment by anlyyao** [comment]
@2352413035 percentage 是一个百分比，你可以根据业务场景换算在传入。

或者你可以具体描述一下你的业务场景 ～
