### ISSUE TITLE
微信小程序基础库版本 2.20.1 起已废弃wx.getSystemInfoSync 这个API，请问后续有计划更新没？

### ISSUE THREAD

**Issue by lihua0103** [Tencent/tdesign-miniprogram#3162]
### tdesign-miniprogram 版本

最新版本

### 重现步骤

基础库版本 2.20.1 起已废弃，请使用 wx.getSystemSetting、wx.getAppAuthorizeSetting、wx.getDeviceInfo、wx.getWindowInfo、wx.getAppBaseInfo 替换 wx.getSystemInfo 的同步版本

### 期望结果

同步替换成最新的api

### 实际结果

还是旧有的api获取设备信息

### 补充说明

当前获取微信设备相关信息还是旧有API，微信已经提示替换新的API，后续不更新会不会影响产品使用

**Comment by anlyyao** [comment]
@lihua0103 下个版本会全局处理

**Comment by lihua0103** [comment]
好的，谢谢
