### ISSUE TITLE
[Steps 步骤条] 自定义不了icon

### ISSUE THREAD

**Issue by qianggewudi6666** [Tencent/tdesign-miniprogram#3164]
### tdesign-miniprogram 版本

最新

### 重现步骤

![22520d01096e6c62b052dd04f3edb71](https://github.com/user-attachments/assets/99d157e4-2ef7-463b-ade4-4b0a719a52a2)

### 期望结果

图标更换

### 实际结果

未更换

### 补充说明

自定义icon

**Comment by betavs** [comment]
https://github.com/Tencent/tdesign-miniprogram/blob/673dee2fa5222073273f81ee42b2ce08ef1339cb/src/steps/README.md?plain=1#L98

```html
<t-step-item wx:for="{{4}}" wx:key="index" title="{{_.getText(first, index)}}" content="辅助信息" icon="slot">
```
