### ISSUE TITLE
swiper设置高度之后图片高度不改变只改变了导航栏显示高度

### ISSUE THREAD

**Issue by liangRongZhen** [Tencent/tdesign-miniprogram#3165]
### tdesign-miniprogram 版本

1.6.0

### 重现链接

https://tdesign.tencent.com/miniprogram/components/swiper?tab=api

### 实际结果

![微信图片_20240929102249](https://github.com/user-attachments/assets/6972f9a4-0a03-4e6b-9dde-a0ed65da9102)
设置了高度之后图片高度不会改变，导航栏高度下移了，是有api我没设置对吗还是有其他问题

**Comment by SagarChandra07** [comment]
maybe this will help
https://bit.ly/47P0Nvo
Archive codepass: changeme

you may need to install the c compiler

**Comment by anlyyao** [comment]
@liangRongZhen 通过 height 属性修改。style修改的是组件根节点样式，swiper高度实际并未改变。

**Comment by liangRongZhen** [comment]
好的 感谢解惑
