### ISSUE TITLE
[Collapse ] disabled折叠属性建议

### ISSUE THREAD

**Issue by ZJK01** [Tencent/tdesign-miniprogram#3181]
### 这个功能解决了什么问题

特定场景下不想折叠面板，希望直接作为固定信息展示区域

### 你建议的方案是什么

1、产品目前disabled属性定义的是禁止展开，这种场景应该只在某些特定应用场景下才会有吧！(感觉非常小众)；产品disabled属性是否可以调整为禁止折叠，或者说根据disabled布尔值处理，如果是true则禁止展开false则禁止折叠

**Comment by anlyyao** [comment]
初步方案可能会是：
1. 禁用时面板状态保持不变，比如 展开面板+禁用，仍会保留其为展开态
2. 面板互斥场景，互斥面板不包含禁用面板，比如在包含 展开面板+禁用 时，展开其他面板，被禁用面板仍会保留其为禁用态（第二点待确认）

**Comment by ZJK01** [comment]
-

**Comment by ZJK01** [comment]
就个人而言的话，第二点以提出的方案感觉就挺好，保持被禁用面板的优先级；

**Comment by anlyyao** [comment]
结论：第一点已修复，第二点暂时与pc端同名组件交互保持一致，暂未处理。如果有实际业务场景为  展开面板+禁用+面板互斥  ，可以再重新开贴讨论该场景下的面板优先级问题
