### ISSUE TITLE
[DateTimePicker 时间选择器] 时间选择器选项只能是带年吗？

### ISSUE THREAD

**Issue by BigCleverXu** [Tencent/tdesign-miniprogram#3185]
### 这个功能解决了什么问题

当我只想要【月-日-时】的时间选项，不想要年的选项，当前组件就不支持了，只能单独写picker好像有点麻烦

### 你建议的方案是什么

通过修改返回格式，自定义显示时间的选项

**Comment by anlyyao** [comment]
https://tdesign.tencent.com/miniprogram/components/date-time-picker?tab=api

是的，目前仅支持 year = 年；month = 年月；date = 年月日；hour = 年月日时； minute = 年月日时分。和 format 也是对应关系

**Comment by BigCleverXu** [comment]
以后会有单独控制年月日的属性吗
