### ISSUE TITLE
[t-icon] 在微信小程序中大部分官网示例的t-icon无法展示

### ISSUE THREAD

**Issue by zhao134387** [Tencent/tdesign-miniprogram#3191]
### tdesign-miniprogram 版本

 1.6.1

**Comment by anlyyao** [comment]
@zhao134387  如果组件库版本为最新，图标是和官网表现一致的。 在官网的“代码演示“部分的 [在开发者工具中预览效果](https://developers.weixin.qq.com/s/wMINibmJ7WSQ)，这是完整的示例代码片段，可以导入开发者工具运营，定位下是否为版本问题～

**Comment by anlyyao** [comment]
@oqughin 楼上不是已经回复了吗？ 有代码片段有问题切入点。有控制台的字体加载报错没有关系，效果如下：<img width="1239" alt="截屏2024-10-22 20 09 11" src="https://github.com/user-attachments/assets/232abe63-b42f-46f5-8659-dd7b7f2e9d5c">

**Comment by zhanglinqian** [comment]
<img width="935" height="730" alt="Image" src="https://github.com/user-attachments/assets/70fc63f9-4606-4add-8df1-18fbfd8e320c" />

<img width="1303" height="753" alt="Image" src="https://github.com/user-attachments/assets/1124c20e-b6d3-499c-85e8-de0c325ea85d" />

您好，我安装的最新版的，但是还是会有icon展示不出来的情况，这个具体需要做些什么才能正常展示？ @anlyyao
