### ISSUE TITLE
[Navbar] 导航组件小米平板层级bug

### ISSUE THREAD

**Issue by lihua0103** [Tencent/tdesign-miniprogram#3193]
### tdesign-miniprogram 版本

可以复现

### 重现步骤

使用小米平板（xiaomi pad5 pro 5g）该设备使用Navbar组件，点击左侧箭头因为层级问题，不能触发返回事件

### 期望结果

使用小米平板（xiaomi pad5 pro 5g）该设备使用Navbar组件，点击左侧箭头因为层级问题，触发返回事件返回上一页

### 实际结果

使用小米平板（xiaomi pad5 pro 5g）该设备使用Navbar组件，点击左侧箭头因为层级问题，不能触发返回事件

### 补充说明

使用小米平板（xiaomi pad5 pro 5g）该设备使用Navbar组件，点击左侧箭头因为层级问题，不能触发返回事件
```[tasklist]
### Tasks
```

**Comment by lihua0103** [comment]
同步在当前设备title内容超长会导致溢出遮挡左侧返回按钮以及右侧胶囊区域

**Comment by lihua0103** [comment]
wx.getMenuButtonBoundingClientRec 该API获取的胶囊位置{bottom: 79,height: 32,left: 571,right: 667,top: 47,width: 96}
wx.getSystemInfo 该API获取的整体宽度
{
  screenHeight: 818，
  screenTop: 0，
  screenWidth: 533，
  statusBarHeight: 27，
  system: "Android 11"，
  version: "8.0.51"，
  wifiEnabled: true，
  windowHeight: 818，
  windowWidth: 533
} 不知道是不是因为这个原因导致的

**Comment by anlyyao** [comment]
我来一并看看👀

**Comment by anlyyao** [comment]
@lihua0103 辛苦贴下使用代码或者真机上的效果图哇！title内容是做了超出省略的，左侧内容可能会被遮挡，右侧胶囊区域应该是不会有遮挡问题。因为左右两边全部留出了小程序默认胶囊按钮的距离

**Comment by anlyyao** [comment]
#3217 中优化了左侧间距计算。后续可以通过更新版本验证该问题是否还存在～

**Comment by lihua0103** [comment]
<t-navbar
    t-class-placeholder="t-navbar-placeholder"
    t-class-content="t-navbar-content"
    class="block"
    title="106-评分8 (For each item, please indicate your OVERALL level during the PAST WEEK, including
TODAY.))文字"
    left-arrow
    bind:go-back="handleBack"
  /> 就是title文案查查英文很长的时候，左侧箭头区域被遮挡，导致返回按钮不能点击

**Comment by lihua0103** [comment]
<t-navbar
    t-class-placeholder="t-navbar-placeholder"
    t-class-content="t-navbar-content"
    title="1063248 (For each item, please indicate your OVERALL level during the PAST WEEK, including
TODAY.))"
    t-class-title="nav-title"
  />

**Comment by lihua0103** [comment]
<t-navbar
    t-class-placeholder="t-navbar-placeholder"
    t-class-content="t-navbar-content"
    title="10111-评分8 (For each item, please indicate your OVERALL level during the PAST WEEK, including
TODAY.))"
    t-class-title="nav-title"
  />

**Comment by anlyyao** [comment]
> 就是title文案查查英文很长的时候，左侧箭头区域被遮挡，导致返回按钮不能点击

理论上左侧的 left-arrow 图标按钮不会被遮挡，标题左侧默认留出了和右侧胶囊一样的宽度 🤔。 还是等发版后，你在验证一下问题是否还存在吧

**Comment by lihua0103** [comment]
好的，谢谢
