### ISSUE TITLE
[t-upload]  首次上传后图片没有预览显示

### ISSUE THREAD

**Issue by danielyangfei** [Tencent/tdesign-miniprogram#3194]
### tdesign-miniprogram 版本

1.6.1

### 重现步骤

 .wxml
 <t-upload
  draggable
  media-type="{{['video','image']}}"
    files="{{originFiles}}"
    gridConfig="{{gridConfig}}"
    bind:add="handleAdd"
    bind:remove="handleRemove"
    bind:click="handleClick"
  ></t-upload>
  
  .js
data:{
 originFiles: [

    ],
    gridConfig: {
      column: 3,
      width: 180,
      height: 180,
    },
}

handleAdd(e){
    const { files } = e.detail;
    console.log(e)
    this.setData({originFiles:e.detail.files})
  },

### 期望结果

上传并展示

### 实际结果

首次不能展示预览 第二次又可以

### 补充说明

无

**Comment by danielyangfei** [comment]
https://github.com/user-attachments/assets/0e00517a-44d9-407c-8ee5-d0b72ad5570d

**Comment by danielyangfei** [comment]
https://github.com/user-attachments/assets/03ead2e6-8323-4a42-baf3-63d006c86ce1

**Comment by jarmywang** [comment]
@danielyangfei 感谢反馈，不过我按照你的代码没有复现，麻烦你参考[文档示例](https://developers.weixin.qq.com/s/jz6CGimj7NSG)再看看

**Comment by danielyangfei** [comment]
> @danielyangfei 感谢反馈，不过我按照你的代码没有复现，麻烦你参考[文档示例](https://developers.weixin.qq.com/s/jz6CGimj7NSG)再看看

模拟器上面没问题，但是真机上会有问题。
表现：
1. 首次上传图片 loading 后不展示
2. 再次上传后，会重复展示上次上传的结果

issue 中我看很多人也在反馈相同的问题

**Comment by danielyangfei** [comment]
> @danielyangfei 感谢反馈，不过我按照你的代码没有复现，麻烦你参考[文档示例](https://developers.weixin.qq.com/s/jz6CGimj7NSG)再看看

采用了https://github.com/Tencent/tdesign-miniprogram/issues/3015 中说的 去掉 draggable 解决了问题  感觉这个属性应该是有啥影响的

**Comment by anlyyao** [comment]
Duplicate of #3015
