### ISSUE TITLE
tabs选项卡的swipeable属性设置成false不生效，怎么都可以滑动

### ISSUE THREAD

**Issue by wyh4444** [Tencent/tdesign-miniprogram#3201]
### tdesign-miniprogram 版本

1.6.0

### 重现步骤

<t-tabs
  defaultValue="{{0}}"
  swipeable="false"
  bind:change="onTabsChange"
  bind:click="onTabsClick"
  t-class="custom-tabs"
  t-class-content="custom-panel"
>

**Comment by betavs** [comment]
```html
<t-tabs swipeable="{{false}}"></t-tabs>
```
