### ISSUE TITLE
[Calendar ] type为range时，新增限制选择长度属性

### ISSUE THREAD

**Issue by k186** [Tencent/tdesign-miniprogram#3210]
### 这个功能解决了什么问题

当type为range 是 允许设置 limitRange 属性，值为Number,默认不限制，用户可选天数范围限制；

### 你建议的方案是什么

用户选中一个时间后，当前时间的前后 在LimitRange 范围内可选，其他时间均为disabled

**Comment by jarmywang** [comment]
我们内部讨论了一下，认为可以在confirm或者change事件里自行处理做限制或者提示用户即可，暂时不加了，感谢反馈
