### ISSUE TITLE
t-icon 默认图标是一个锁吗？

### ISSUE THREAD

**Issue by luoxin59420** [Tencent/tdesign-miniprogram#3212]
<t-icon class="blue-item-icon fadeIn" name="{{ ossBaseUrl + 'wifi@2x.png' }}" size="56rpx" />
加载cdn的图标失败后，会默认出现一个锁的图标吗？

![image](https://github.com/user-attachments/assets/375f34e3-0c10-4e11-9cb8-be946331f0e4)

**Comment by anlyyao** [comment]
@luoxin59420  TIcon 组件没有兜底值，贴一下你的代码看看～

**Comment by luoxin59420** [comment]
> @luoxin59420 TIcon 组件没有兜底值，贴一下你的代码看看～

`<t-cell
            bordered="{{false}}"
            title="{{ item.deviceTagName || item.deviceName }}"
            image="{{ ossBaseUrl + '1315-AI@2x.png' }}"
            data-row="{{ item }}"
            catch:tap="connectBlue"
            data-type="my"
          >
            <view slot="note" class="lanya-icon">
              <t-icon wx:if="{{ item.onlineStatus == 1 }}" class="blue-item-icon fadeIn" name="{{ ossBaseUrl + 'wifi@2x.png' }}" size="56rpx" />
              <t-icon class="blue-item-icon fadeIn" name="{{ ossBaseUrl + (item.connectable ? 'lanya_on@2x.png' : 'lanya_off@2x.png') }}" size="56rpx" />
            </view>
            <view catch:tap="handleMore" data-index="{{index}}" slot="note" class="more-icon">
              <t-icon name="{{ ossBaseUrl + 'more@2x.png' }}" size="56rpx" />
            </view>
          </t-cell>`

![image](https://github.com/user-attachments/assets/f95027b7-04cf-4cf2-b4ad-9d27d6437103)

**Comment by luoxin59420** [comment]
> @luoxin59420 复现不出你的问题，我这边使用是正常的。你看你能想办法在这个代码片段链接里面复现吗～，复现之后在重新分享给我
> 
> https://developers.weixin.qq.com/s/bz7aGimL72S2

这个问题是一闪而过，不是一直存在的，看来服务器的资源，也是没有锁这个图标的

**Comment by luoxin59420** [comment]
> > @luoxin59420 复现不出你的问题，我这边使用是正常的。你看你能想办法在这个代码片段链接里面复现吗～，复现之后在重新分享给我
> > https://developers.weixin.qq.com/s/bz7aGimL72S2
> 
> 这个问题是一闪而过，不是一直存在的，看来服务器的资源，也是没有锁这个图标的


https://github.com/user-attachments/assets/486fb95a-b2bb-42d7-b4f4-d51fc7525ccf

**Comment by anlyyao** [comment]
@luoxin59420  从截图/录屏中看确实出现lock图标，但我这边无法直接复现。你可以把录屏中这段代码分享成代码片段链接给我吗？我这边先尝试复现

**Comment by luoxin59420** [comment]
> @luoxin59420 从截图/录屏中看确实出现lock图标，但我这边无法直接复现。你可以把录屏中这段代码分享成代码片段链接给我吗？我这边先尝试复现

好的
用下面这个demo:
<t-icon name="{{ 'https://jp-iot-sit.oss-cn-shenzhen.aliyuncs.com/wx-mini/icon/' + 'wifi@2x.png' }}" size="48rpx" />

**Comment by luoxin59420** [comment]
> @luoxin59420 从截图/录屏中看确实出现lock图标，但我这边无法直接复现。你可以把录屏中这段代码分享成代码片段链接给我吗？我这边先尝试复现

`<t-icon name="{{ 'https://jp-iot-sit.oss-cn-shenzhen.aliyuncs.com/wx-mini/icon/' + 'wifi@2x.png' }}" size="48rpx" />`

**Comment by anlyyao** [comment]
> > @luoxin59420 复现不出你的问题，我这边使用是正常的。你看你能想办法在这个代码片段链接里面复现吗～，复现之后在重新分享给我
> > https://developers.weixin.qq.com/s/bz7aGimL72S2
> 
> 没有加载会不会和这个有关系呢？ ![image](https://private-user-images.githubusercontent.com/69165743/378781053-469602a2-274e-4abb-a5e4-edfeb97bbe9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2Njg3NTgsIm5iZiI6MTcyOTY2ODQ1OCwicGF0aCI6Ii82OTE2NTc0My8zNzg3ODEwNTMtNDY5NjAyYTItMjc0ZS00YWJiLWE1ZTQtZWRmZWI5N2JiZTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA3MjczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjOTBkMDZhOTJiODI1ZmI4NzUxZGE3NzkwYmFlNjZkMjg2NjQ2NzNmMTVlNTY1YjUyZTVmZWY3YjcwZDQwMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hrsz3Tz6SpT1JAht1ZgVbkJAShllPWc7VFLBmTnCR5E)

是的，使用网络地址时，偶发性出现图标的原因确实是因为刚好有个图标名称为“https”，已修复该问题，下个版本可带，感谢反馈～

**Comment by luoxin59420** [comment]
> > > @luoxin59420 复现不出你的问题，我这边使用是正常的。你看你能想办法在这个代码片段链接里面复现吗～，复现之后在重新分享给我
> > > https://developers.weixin.qq.com/s/bz7aGimL72S2
> > 
> > 
> > 没有加载会不会和这个有关系呢？ ![image](https://private-user-images.githubusercontent.com/69165743/378781053-469602a2-274e-4abb-a5e4-edfeb97bbe9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2Njg3NTgsIm5iZiI6MTcyOTY2ODQ1OCwicGF0aCI6Ii82OTE2NTc0My8zNzg3ODEwNTMtNDY5NjAyYTItMjc0ZS00YWJiLWE1ZTQtZWRmZWI5N2JiZTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA3MjczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjOTBkMDZhOTJiODI1ZmI4NzUxZGE3NzkwYmFlNjZkMjg2NjQ2NzNmMTVlNTY1YjUyZTVmZWY3YjcwZDQwMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hrsz3Tz6SpT1JAht1ZgVbkJAShllPWc7VFLBmTnCR5E)
> 
> 是的，使用网络地址时，偶发性出现图标的原因确实是因为刚好有个图标名称为“https”，已修复该问题，下个版本可带，感谢反馈～

好的，不客气
