### ISSUE TITLE
[icon] icon字体文件加载有误导致无法正常使用TDesign内置的icon字体

### ISSUE THREAD

**Issue by oqughin** [Tencent/tdesign-miniprogram#3214]
### tdesign-miniprogram 版本

1.6.2

### 实际结果

[渲染层网络层错误] Failed to load font https://tdesign.gtimg.com/icon/0.1.2/fonts/t.woff
net::ERR_CACHE_MISS 
(env: Windows,mp,1.06.2405010; lib: 2.20.2)

### 基础库版本

2.20.2

**Comment by oqughin** [comment]
用微信开发者工具新建一个Tdesign模板也会报这个错误
![image](https://github.com/user-attachments/assets/bac1aced-33d4-4cfa-b9c8-d4e5a26960c6)

**Comment by anlyyao** [comment]
@oqughin 官网组件页面有做说明，见 https://tdesign.tencent.com/miniprogram/components/icon，
<img width="497" alt="截屏2024-10-22 19 31 59" src="https://github.com/user-attachments/assets/af7f6431-2768-4b2d-b520-27ebbac30f8c">

微信官方解释见：https://developers.weixin.qq.com/miniprogram/dev/api/ui/font/wx.loadFontFace.html

**Comment by oqughin** [comment]
这个应该是内置的icon样式文件里的文件无法正常加载导致的，这个应该TDesign来修吧😄
就下面引入官方字体的这里有问题导致的
![image](https://github.com/user-attachments/assets/74ecde61-eaa4-4fba-b7d2-ea7b7fd5620f)

**Comment by NeedQianNanYou** [comment]
我也遇到同样的问题了，所以应该如何解决呢，换其他的组件库吗

**Comment by kkcode24** [comment]
> [@oqughin](https://github.com/oqughin) 官网组件页面有做说明，见 [https://tdesign.tencent.com/miniprogram/components/icon，](https://tdesign.tencent.com/miniprogram/components/icon%EF%BC%8C) <img alt="截屏2024-10-22 19 31 59" width="497" src="https://private-user-images.githubusercontent.com/51158141/378819957-af7f6431-2768-4b2d-b520-27ebbac30f8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTM3NTgyMjIsIm5iZiI6MTc1Mzc1NzkyMiwicGF0aCI6Ii81MTE1ODE0MS8zNzg4MTk5NTctYWY3ZjY0MzEtMjc2OC00YjJkLWI1MjAtMjdlYmJhYzMwZjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzI5VDAyNTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxZDJjMWI5ZjIwZjQzYjVmOTA0MGI3NGYzMGQyNmJhMjk3NzE0NGRjNmE5YjE0MWI3MTBjNGVlYTZhMTU4MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PToiWXtC79smz2QOjTuebFFW9wU9ALLor7gcfJN5d7Y">
> 
> 微信官方解释见：https://developers.weixin.qq.com/miniprogram/dev/api/ui/font/wx.loadFontFace.html

哪里用到wx.loadFontFace了
