### ISSUE TITLE
[t-upload] 上传组件预览图无法居左对齐 目前只能两端对齐

### ISSUE THREAD

**Issue by LawyerLu** [Tencent/tdesign-miniprogram#3221]
### 这个功能解决了什么问题

编写发帖页面时，图片预览方格居左对齐，符合视觉习惯。

### 你建议的方案是什么

目前默认是两端对齐，设置为每行4张图片间距正常，但是如果设置为3张，间距就会过大，因为是两端对齐，目前只能通过调整根容器的边距来从视觉上满足需求，但考虑到兼容性问题，建议像grid宫格组件一样，增加align属性，可选 left/center.
![image](https://github.com/user-attachments/assets/871a4dfd-aa3b-4588-8c94-b74a3b01d541)

**Comment by LawyerLu** [comment]
目前临时的解决方案是：设置gridConfig的固定宽高后，如100，然后再设置
```
.t-upload__drag-item {
  width: 110rpx !important;
}
```
其中多出来的间距就是gutter的值。

**Comment by anlyyao** [comment]
@LawyerLu column取3的时候，实际上已经将容器宽度均分3份啦，所以这里最好的处理方式是根据gridConfig调整图片的宽高
