### ISSUE TITLE
[ActionSheet] cancel-text默认值为空，与旧版本不同，旧版本默认为取消，默认值为空导致取消那栏是空白的

### ISSUE THREAD

**Issue by nanhupatar** [Tencent/tdesign-miniprogram#3227]
### tdesign-miniprogram 版本

1.7.0

### 期望结果
cancel-text 默认值为取消
_No response_

**Comment by anlyyao** [comment]
大概是我上次更新API文档的时候，给干掉了，我重新补一下，感谢反馈～
