### ISSUE TITLE
[Fab 悬浮按钮] 支持透明度以及长时间无点击增加透明度

### ISSUE THREAD

**Issue by myifeng** [Tencent/tdesign-miniprogram#3232]
### 这个功能解决了什么问题

悬浮按钮，经常悬浮在主页或者其他主要页面，在长时间不使用时建议增加透明度，保证不影响主页面。

### 你建议的方案是什么

1. API支持透明度设置
2. API支持过期时间设置以及过期后自动改变透明度

**Comment by RADWIMPS426** [comment]
感谢你的建议，这个组件后续会进行优化升级，通过缩小并贴边的功能解决遮挡主屏的问题，敬请期待👍

**Comment by RADWIMPS426** [comment]
<img width="955" alt="image" src="https://github.com/user-attachments/assets/a8e85e02-af28-45ff-b177-95691b6b60c4">
