### ISSUE TITLE
[Search] 外部样式类t-class-clear无法改变图标大小

### ISSUE THREAD

**Issue by desmondboom** [Tencent/tdesign-miniprogram#3234]
### tdesign-miniprogram 版本

1.7.0

### 重现链接

t-class-clear="icon"

### 重现步骤

t-class-clear 无法实现font-size的样式覆盖

**Comment by desmondboom** [comment]
```
    <view
      wx:if="{{value !=='' && clearable}}"
      class="{{classPrefix}}__clear {{prefix}}-class-clear"
      catch:tap="handleClear"
      aria-role="button"
      aria-label="清除"
    >
      <t-icon name="close-circle-filled" size="48rpx" />
    </view>
```
这里的{{prefix}}-class-clear是不是应该直接给 t-icon？像是前置icon一样保持一致？

**Comment by desmondboom** [comment]
@anlyyao thanks for changing the title.

**Comment by anlyyao** [comment]
> ```
>     <view
>       wx:if="{{value !=='' && clearable}}"
>       class="{{classPrefix}}__clear {{prefix}}-class-clear"
>       catch:tap="handleClear"
>       aria-role="button"
>       aria-label="清除"
>     >
>       <t-icon name="close-circle-filled" size="48rpx" />
>     </view>
> ```
> 
> 这里的{{prefix}}-class-clear是不是应该直接给 t-icon？像是前置icon一样保持一致？

或者 icon 的 size 和 color 属性用 inherit

**Comment by desmondboom** [comment]
@anlyyao @jarmywang 👍 Thanks!
