### ISSUE TITLE
Calendar,Popup弹出层相关

### ISSUE THREAD

**Issue by lzxanti** [Tencent/tdesign-miniprogram#3256]
### tdesign-miniprogram 版本

最新版

### 重现链接

官方示例中就有问题

### 重现步骤

官方示例中,实际使用中,遮罩无效,背后仍然可以上下滑动

### 期望结果

弹出日历或者Popup,背后无法上下滑动

### 实际结果

弹出日历或者Popup,背后仍然可上下滑动,导致分页操作触发

**Comment by anlyyao** [comment]
@lzxanti 请以真机效果为准
