### ISSUE TITLE
咨询小程序组件和vue组件差异

### ISSUE THREAD

**Issue by herohql521** [Tencent/tdesign-miniprogram#3258]
### 这个功能解决了什么问题

请问小程序端已经开发完成，要做一版移动端vue的，迁移或者改造注意事项有哪些，组件本身的使用没太大变化吧？

### 你建议的方案是什么

希望可以给些改造建议

**Comment by anlyyao** [comment]
TDesign 整个移动端（h5、小程序）同名组件的API功能、使用理论上都应该表现一致。

如果有不一致的地方，可以随时给我们提issue，我们会尽快修复！！

**Comment by anlyyao** [comment]
如果是基于原生小程序，利用跨端框架做多端应用，官方暂时没有计划，无法保证在跨端框架中组件功能的完整性～

**Comment by herohql521** [comment]
噢 明白，再问一个，微信小程序迁移到企业微信小程序使用，组件的支持程度要根据企业微信这个表来确定吗
![image](https://github.com/user-attachments/assets/6d42f050-abcb-4515-9b96-34d1212390b9)
，还是已经做了兼容

**Comment by anlyyao** [comment]
sorry～，我们是TDesign组件库开发者，不是微信/企微官方，不能为该部分功能做担保。

理论上微信小程序迁移到企微，是应该根据该表来确定组件是否支持，但该表似乎许久未更新，可以多尝试一下，可能实际已支持只是文档未更新、
