### ISSUE TITLE
[Navbar] 设置样式不生效

### ISSUE THREAD

**Issue by Fluox-Etine** [Tencent/tdesign-miniprogram#3267]
### tdesign-miniprogram 版本

最新版

### 重现链接

无

### 重现步骤

采用官方例子；我使用带图片的导航栏，发现  .t-navbar__left 自带的margin-left 几个rpx。但是我尝试用class把置为0但是不生效。

这是代码，css就是置为0；不生效，无论写在什么class上都无生效。

```
<t-navbar left-arrow t>
    <view slot="left" class="navbar-view">
        <t-avatar image="{{avatar}}" size="30px"/>
        <view class="nickname">{{nickName}}</view>
    </view>
</t-navbar>
```

### 实际结果

可以设置把这个margin-left取消掉。

**Comment by anlyyao** [comment]
@Fluox-Etine  你贴的代码里 没看到你修改/覆盖 `.t-navbar__left ` 类中的样式。 

建议：
1. 使用 t-class-left 外部样式类， 使 margin-left: 0 !importan;
2. 页面中覆盖  .t-navbar__left {
  margin-lef: 0 !important;
}。如果是自定义组件，需要先开启 styleIsolation: 'shared'。 参考官网方案2 https://tdesign.tencent.com/miniprogram/custom-style
