### ISSUE TITLE
[Rate] Rate组件点击事件没有向上传递

### ISSUE THREAD

**Issue by dlxbcn** [Tencent/tdesign-miniprogram#3270]
### tdesign-miniprogram 版本

1.7.0

### 重现链接

https://github.com/Tencent/tdesign-miniprogram/blob/b193a61b3da6afd98bb5b75e2254ea2befca6ba5/src/rate/rate.ts#L73

### 重现步骤

列表页加了Rate 控件，但Rate 组件点击没反应，也不能传递点击事件，导致列表页无法跳转到详情页

### 期望结果

就算Rate控件设置了disalbe，也可以向上传递点击事件

### 补充说明

可以向上传点击事件，类似this.triggerEvent('click', e); 
见
https://github.com/Tencent/tdesign-miniprogram/blob/b193a61b3da6afd98bb5b75e2254ea2befca6ba5/src/tag/tag.ts#L85C7-L85C37

**Comment by anlyyao** [comment]
@dlxbcn 什么叫做“就算Rate控件设置了disalbe，也可以向上传递点击事件”， 禁用就是禁用

**Comment by dlxbcn** [comment]
@anlyyao 我来解释一下这个场景，看这段代码
`<view bind:tap="gotTap">
      {{text}}
      <input value="123" disabled/>
      <t-rate value="{{4}}" disabled />
</view>`

`Page({
    data: {
      text:""
    },
    gotTap(e){
      this.setData({text:"clicked"});
      setTimeout(()=>{
        this.setData({text:""});
      }, 3000)
    },
})`

这段代码在点击【input】的时候，父控件是可以收到点击事件的，但点击【t-rate】控件就远法收到点击事件了，通过这个实验，我觉得 disabled 可以理解为【禁用】，但只是这个控件不响应，并不应该阻止事件冒泡。
