### ISSUE TITLE
[打包] 小程序包限制。组件使用分析功能

### ISSUE THREAD

**Issue by Fluox-Etine** [Tencent/tdesign-miniprogram#3271]
### 这个功能解决了什么问题

是否能提供分析就是当前使用组件占用大小或者可以给出安全的删除无用组件方法；官方组件构建出来就占用了1.04MB大小，就占用了主包2M一半了。

### 你建议的方案是什么

安全删除无用组件的文档

**Comment by anlyyao** [comment]
问题1: 微信开发者工具中能看到 代码依赖分析
问题2: 没有用到的组件在构建时会过滤，勾选“上传时过滤无依赖文件”。或者你可以本地引入miniprogram-ci，看了一下打包产物，验证一下无依赖的组件是否被正确过滤
