### ISSUE TITLE
[swipe-cell] 真机无法滑动问题

### ISSUE THREAD

**Issue by zhouruiqiang** [Tencent/tdesign-miniprogram#3274]
### tdesign-miniprogram 版本

1.7.1

### 重现步骤

<t-swipe-cell>
  <view class="" style="width: 100%; line-height: 80rpx; background: lightblue;">123123123123sdafasdfasdfasef</view>

  <view slot="right" class="btn-wrapper">
    <view class="btn edit-btn column" >
      编辑
    </view>
    <view class="btn delete-btn column" >
      删除
    </view>
  </view>
</t-swipe-cell>

### 补充说明

<t-swipe-cell>
  <view class="" style="width: 100%; line-height: 80rpx; background: lightblue;">123123123123sdafasdfasdfasef</view>

  <view slot="right" class="btn-wrapper">
    <view class="btn edit-btn column" >
      编辑
    </view>
    <view class="btn delete-btn column" >
      删除
    </view>
  </view>
</t-swipe-cell>

**Comment by anlyyao** [comment]
这个组件没有兼容 glass-easel 框架，移除相关配置哈

**Comment by zhouruiqiang** [comment]
不错不错👍👍
