### ISSUE TITLE
[t-stepper] 值设置为0，但显示的值是最小值

### ISSUE THREAD

**Issue by wh230308** [Tencent/tdesign-miniprogram#3275]
### tdesign-miniprogram 版本

1.0.0

### 期望结果

t-stepper的value属性设置为0，min属性设置为-20，页面初次加载时，t-stepper显示的是value属性值，即0

### 实际结果

t-stepper的value属性设置为0，min属性设置为-20，页面初次加载时，t-stepper显示的是min属性值，即-20

### 补充说明

查看t-stepper代码，发现attached方法中value值为0时，被设置为min值

**Comment by wh230308** [comment]
你好，最新1.7.1版本中也有这个问题
[cid:1875c8a4-70e2-4f3c-bd33-4988636d5f4f]
当value属性值为0时，展示的是min属性值
________________________________
发件人: Y. ***@***.***>
发送时间: 2024年11月12日 21:18
收件人: Tencent/tdesign-miniprogram ***@***.***>
抄送: wh230308 ***@***.***>; Mention ***@***.***>
主题: Re: [Tencent/tdesign-miniprogram] [t-stepper] 值设置为0，但显示的值是最小值 (Issue #3275)


@wh230308<https://github.com/wh230308> 1.0.0 版本？？？ 现在已经到1.7.1版本的哦，你可能需要更新下版本

―

**Comment by anlyyao** [comment]
@wh230308  https://developers.weixin.qq.com/s/peoPBFmN7WV1

<img width="1220" alt="企业微信截图_5f92ca3a-1a04-407b-9db4-8297341f3414" src="https://github.com/user-attachments/assets/2967a399-8ad8-4e63-a515-8cc1689081f0">
