### ISSUE TITLE
[message] message无法遮盖 search 组件 input 输入的文字

### ISSUE THREAD

**Issue by 52Hertz-1** [Tencent/tdesign-miniprogram#3277]
### tdesign-miniprogram 版本

lastest

### 重现步骤

页面同时引入 search 和 message 时，message 触发展示后无法遮住 search 组件输入框的文字，尝试设置了 zIndex 未能解决，仅在安卓手机有问题，苹果和 pc 显示正常

### 补充说明

![2024_11_12_17_21_00](https://github.com/user-attachments/assets/520fc5bd-f7ba-47d3-a8c7-c37837415632)
![7db2d45b1e8edd6f0f54deefc2799e47_compress](https://github.com/user-attachments/assets/41332377-d644-4c83-bffc-d0b0696fd5b5)

**Comment by anlyyao** [comment]
是微信官方的老问题了，原生组件层级很高，无法覆盖 😅
