### ISSUE TITLE
[icon] 引入iconfont的bug

### ISSUE THREAD

**Issue by zwsn** [Tencent/tdesign-miniprogram#328]
### tdesign-miniprogram 版本

0.7.2

### 重现步骤

按例引入iconfont后(前缀和font family分别设备为icon- icon),在小程序中使用下面代码不会显示icon:
 <t-icon prefix="icon" name="icon-shouye"> </t-icon>
但是在name的值前面加个空格就可以正常显示
  <t-icon prefix="icon" name=" icon-shouye"> </t-icon>
![Uploading image.png…]()

### 期望结果

希望修复此问题,另外在tabbar组件中无法使用引入的iconfont图标,望支持

### 实际结果

按例无法正常显示,需在name的值前加空格才正常显示

### 系统版本

macOS(12.2.1)

### Node版本

v17.8.0

**Comment by LeeJim** [comment]
图片没上传成功，看不到

**Comment by zwsn** [comment]
<img width="736" alt="image" src="https://user-images.githubusercontent.com/42889307/162379733-948e365b-942e-4a2d-82ec-f84f2c381578.png">

**Comment by anlyyao** [comment]
@zwsn 你说的，`name的值前加空格正常显示`，我无法复现。 正常来说，name属性值中不需要在加图标前缀， 比如你的图标className是 `icon-shouye`, 那么`prefix='icon' name='shouye'`。 此外我们更新了自定义图标模块的文档，希望能帮到你～～
