### ISSUE TITLE
[t-progress] plump 主题在 Skyline 渲染模式下，存在 label 文字排版偏移的问题

### ISSUE THREAD

**Issue by caijiehong** [Tencent/tdesign-miniprogram#3282]
### tdesign-miniprogram 版本

1.7.1

### 重现步骤

```
<t-progress theme="plump" percentage="80" label="test" />
```
<img width="330" alt="image" src="https://github.com/user-attachments/assets/48e4fb77-6952-4b8c-b0df-0d31a0b5be5c">

<img width="333" alt="image" src="https://github.com/user-attachments/assets/71ca1ba3-6af2-4a11-9608-5ebed52aa3f4">

### 期望结果

Skyline 渲染模式下，期望对齐 webview 模式

### 基础库版本

3.6.4

**Comment by anlyyao** [comment]
感觉还是skyline不支持bfc的问题......
