### ISSUE TITLE
[t-cascader] option数据是接口获取的，点击选项因为下一级数据是异步的，导致组件自动关闭了。

### ISSUE THREAD

**Issue by Newul** [Tencent/tdesign-miniprogram#3284]
### 这个功能解决了什么问题

关闭时机应该可控的，适配异步的场景。

### 你建议的方案是什么

增加Props控制
## IssueShoot
- 预估时长: 3
- 期望完成时间: 2024-11-20 00:00:00 +0000 UTC
- 开发难度: 中
- 参与人数: 1
- 需求对接人: jeannehuang;anlyyao;jarmywang
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by anlyyao** [comment]
@Newul  感谢反馈，有计划新增 checkStrictly 属性，父子节点选中状态不再关联，可各自选中或取消

**Comment by anlyyao** [comment]
@Newul 按照 cascader 组件设计，遇到 children 为 null/undefind 时，会结束。 需要保证  children 是数组 （children: [] as any[] ）
