### ISSUE TITLE
[组件名称] 滑动模块无法使用

### ISSUE THREAD

**Issue by hanweidong** [Tencent/tdesign-miniprogram#3289]
### tdesign-miniprogram 版本

1.7.1

### 重现步骤

index.wxml:
<t-swipe-cell right="{{right}}" left="{{left}}" bind:click="onActionClick">
  <t-cell title="左右滑操作" note="辅助信息" bordered="{{false}}" />
</t-swipe-cell>
index.js:
Component({
  data: {
    right: [
      {
        text: '删除',
        className: 'btn delete-btn',
      },
    ],
    left: [
      {
        text: '选择',
        className: 'btn favor-btn',
      },
    ],
  },

  methods: {
    onActionClick({ detail }) {
      wx.showToast({ title: `你点击了${detail.text}`, icon: 'none' });
    },
  },
});

提示异常：
TypeError: Cannot read property 'nv_getState' of undefined

**Comment by anlyyao** [comment]
@hanweidong issue请按照规范填写完整。 swipe-cell 组件未适配 glass-easel，相关配置请先移除。 

Duplicate of #3274

**Comment by hanweidong** [comment]
那如果其他页面需要skyline的话，是把配置放到每个页面的index.json里么

**Comment by anlyyao** [comment]
> 那如果其他页面需要skyline的话，是把配置放到每个页面的index.json里么

是的

**Comment by hanweidong** [comment]
好的，问题已修复，谢谢
