### ISSUE TITLE
[t-color-picker] 和t-popup嵌套无法使用

### ISSUE THREAD

**Issue by xiaoshangmin** [Tencent/tdesign-miniprogram#3290]
### tdesign-miniprogram 版本

1.8.0

### 重现步骤

	<t-popup visible="{{ visible }}" placement="bottom"> 
	<t-color-picker enableAlpha type="multiple" swatch-colors="{{ swatchColors }}"  bind:change="onChange" />
	</t-popup>
	
	因为我需要在color-picker下面再加一些其他的元素 没有用官方的use-popup属性
	直接在page里面用t-popup和t-color-picker嵌套 但是无法使用   
	看官方源码也是两个组件嵌套 不明白是哪里的问题 
	求解答 感谢

### 期望结果

可以使用

### 基础库版本

3.6.0

**Comment by anlyyao** [comment]
@xiaoshangmin 页面上直接使用popup+colorpicker，touch事件垂直方向偏移量是0，导致垂直方向位置不正确，外部并不好处理。如果你的需求是在color-picker上方/下方再加一些其他的元素，我们可以尝试提供顶部/底部插槽让你去自定义、

**Comment by anlyyao** [comment]
> swatch-colors设置为[]

感谢反馈， swatch-colors设置为[]时下方空白问题，我们尽快处理， 同时会提供丰富的插槽来支持自定义内容
