### ISSUE TITLE
[SwipeCell] 与Popup组件配合使用时t-swipe-cell__right无法正常获取宽度

### ISSUE THREAD

**Issue by dancelion** [Tencent/tdesign-miniprogram#3295]
### tdesign-miniprogram 版本

1.7.1

### 重现步骤

t-swipe-cell 嵌套在t-popup里使用
![image](https://github.com/user-attachments/assets/31c8428c-0608-4424-82e5-9ca66b804d33)

### 期望结果

当嵌套使用时也能正常获取t-swipe-cell__right的宽度

### 实际结果

<img width="362" alt="image" src="https://github.com/user-attachments/assets/80360668-0a11-4b0d-9ca2-acdbb693c32d">

### 基础库版本

3.6.5

**Comment by anlyyao** [comment]
@dancelion  popup有一个动画 duration是300ms，因此在获取dom前，你需要确保swipecell已经渲染完毕了

**Comment by anlyyao** [comment]
@dancelion 或者可以在popup visible为true时，手动调用SwipeCell组件的 setSwipeWidth()，然后再去获取 right 节点信息。 我这边就暂时关闭issue了～
