### ISSUE TITLE
[t-upload] 点击上传没有反应。版本号1.1.0和1.8.0都没有反应。文档里的示例点击上传图片也没有任何反应

### ISSUE THREAD

**Issue by baohaojie123** [Tencent/tdesign-miniprogram#3298]
### tdesign-miniprogram 版本

1.8.0

### 重现链接

https://tdesign.tencent.com/miniprogram/components/upload

### 重现步骤

 ```<t-upload media-type="{{['video','image']}}" files="{{originFiles}}" gridConfig="{{gridConfig}}" bind:success="handleSuccess" bind:remove="handleRemove" bind:click="handleClick" bind:sort-end="handleSortEnd" />```

**Comment by betavs** [comment]
目前示例均为禁用态，使用时请自行取消禁用态，以便正常使用上传动能。

**Comment by baohaojie123** [comment]
我取消禁用状态了。微信小程序基础库3.6.5，点击没有任何反应 <t-upload media-type="{{['video','image']}}" files="{{originFiles}}" gridConfig="{{gridConfig}}" bind:success="handleSuccess" bind:remove="handleRemove" bind:click="handleClick" bind:sort-end="handleSortEnd" />

**Comment by baohaojie123** [comment]
好的 谢谢 是我小程序的权限的问题
