### ISSUE TITLE
[Steps步骤条] 文档错误+竖向双层级只读步骤条的subStep状态不同步

### ISSUE THREAD

**Issue by wangsansi** [Tencent/tdesign-miniprogram#330]
### tdesign-miniprogram 版本

0.7.2

### 重现步骤

1. 按文档改变步骤条方向应该是layout，有两个示例没有改过来
<img width="530" alt="image" src="https://user-images.githubusercontent.com/25080434/162135795-7c6f1f22-58bf-481e-b2dc-c9ce56f66489.png">
<img width="541" alt="image" src="https://user-images.githubusercontent.com/25080434/162136011-fe8d9d2c-37af-496e-9896-3d39c1d1fdab.png">
2. current的用法文档没写清楚，按照示例用current="1.0"这种写法不起作用，看了代码，应该用‘-’表示二级状态？？我试了一下，改成current="1-1"这种写法成功了。但是status起什么作用？修改了几个值，没有看到变化。
<img width="554" alt="image" src="https://user-images.githubusercontent.com/25080434/162136201-229b83bf-b474-4eb7-a799-448bca2074eb.png">
<img width="671" alt="image" src="https://user-images.githubusercontent.com/25080434/162137309-209fbb9b-c6d8-4765-b089-2e1d88a7c90e.png">

貌似只能通过current="1-1"来控制步骤条，status不起作用
<img width="221" alt="image" src="https://user-images.githubusercontent.com/25080434/162137188-8f400660-8c56-4533-8445-4a428b615d39.png">
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/25080434/162138214-d2f8fb2f-939c-4794-b26b-d0b1e7deb982.png">

### 期望结果

文档能再详细点，谢谢

### 框架版本

微信小程序

**Comment by anlyyao** [comment]
👌 文档的确有问题，我跟进一下
