### ISSUE TITLE
微信小程序开发使用dilog确认类对话框  改变了主题色，但在点击那一瞬间，确定按钮反馈的颜色是旧的

### ISSUE THREAD

**Issue by LeiXBin** [Tencent/tdesign-miniprogram#3300]
### tdesign 版本

1.8.0

### 重现步骤

微信小程序开发使用dilog确认类对话框  并且使用 --td-brand-color改变了主题色，但在点击那一瞬间，确定按钮反馈的颜色是默认的

**Comment by anlyyao** [comment]
@LeiXBin 看上是使用的问题，button的背景和点击态颜色是两个css vars控制的，官网文档有列出组件级别css vars，建议查看文档后，按需修改主题色～

see： https://tdesign.tencent.com/miniprogram/components/button?tab=api

**Comment by LeiXBin** [comment]
是的，学习到了，我以为只要修改了主题色就可以全局修改，包括这些点击态效果。感谢
