### ISSUE TITLE
[Calendar] 开发环境显示正常，在真机下不显示月份

### ISSUE THREAD

**Issue by kevinjang** [Tencent/tdesign-miniprogram#3303]
### tdesign-miniprogram 版本

1.8.0

### 重现链接

 [<t-calendar visible="{{true}}" bind:confirm="handleConfirm" bind:close="onClose" />](https://github.com/kevinjang/tdesign-quickstart5/blob/master/pages/index/index.wxml)

### 重现步骤

开发环境点击预览，进入小程序弹出日历组件，不显示月份
![b918844c294498c310e2d88d1a07973](https://github.com/user-attachments/assets/e6d24834-e4a0-4c6d-b411-4f3540970532)

### 期望结果

期望正常显示显示月份信息

### 基础库版本

3.6.5

### 补充说明

新建小程序，没有其他业务场景和上下文

**Comment by kevinjang** [comment]
重现链接 https://github.com/kevinjang/tdesign-quickstart5/blob/master/pages/index/index.wxml

**Comment by betavs** [comment]
由于 [[正在支持] glass-easel 下，暂不支持 WXS 事件响应](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/glass-easel/migration.html#JSON-%E9%85%8D%E7%BD%AE)，请暂时移除 `app.json` 中 `"componentFramework": "glass-easel",` 配置即可

**Comment by kevinjang** [comment]
> 由于 [[正在支持] glass-easel 下，暂不支持 WXS 事件响应](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/glass-easel/migration.html#JSON-%E9%85%8D%E7%BD%AE)，请暂时移除 `app.json` 中 `"componentFramework": "glass-easel",` 配置即可

感谢支持，问题已解决！
