### ISSUE TITLE
[button] 在uniapp vue3里面使用button click事件为什么不生效呢，是不能在uniapp中使用吗

### ISSUE THREAD

**Issue by niki571** [Tencent/tdesign-miniprogram#3305]
### tdesign-miniprogram 版本

最新版

### 期望结果

我本来用的vant-weapp 最近想换tdesign，但是button按钮 click事件都不生效，是不支持uniapp vue3吗？用的人感觉也不多，搜索不到。

**Comment by nikolamht** [comment]
修复了吗，我在微信小程序里 bind:click 点击也没反应
