### ISSUE TITLE
[DropdownMenu] 自定义内容不生效

### ISSUE THREAD

**Issue by rider369** [Tencent/tdesign-miniprogram#3307]
### tdesign-miniprogram 版本

1.8.0

### 重现链接

https://developers.weixin.qq.com/s/wEKdv0mL7CWp

### 重现步骤

1. npm install
2. 工具 - 构建npm
3. 打开页面后点击日期下拉菜单，无法显示自定义内容

### 期望结果

正常显示自定义内容

### 实际结果

无法显示自定义内容

### 补充说明

tdesign-miniprogram 1.6版本还可以正常显示自定义内容，1.7及之后版本无法正常显示，可能和 [#3235](https://github.com/Tencent/tdesign-miniprogram/pull/3235) 更新有关

**Comment by anlyyao** [comment]
Duplicate of #3288
