### ISSUE TITLE
[Input] skyline模式下，输入的情况下，在真机上不会显示光标

### ISSUE THREAD

**Issue by jingwei-lgtm** [Tencent/tdesign-miniprogram#3318]
### tdesign-miniprogram 版本

1.8.1

### 重现步骤

下图是模拟器的截图，有光标，但是真机没有
![image](https://github.com/user-attachments/assets/f2d3bca7-1efe-4438-86fa-9dd63b1f9d6c)

### 期望结果

真机情况下也出现光标

### 实际结果

真机情况下没有出现光标

### 基础库版本

3.6.6

**Comment by jingwei-lgtm** [comment]
指定cursor-color后在真机上出现

**Comment by betavs** [comment]
![image](https://github.com/user-attachments/assets/3dff1d16-a71d-4cfb-b55b-932a1155d33a)

目前是输入状态下能正常显示光标

**Comment by chaganuur** [comment]
不指定颜色没光标，真tm恶心

**Comment by anlyyao** [comment]
@jingwei-lgtm 1.8.0 中修复过 cursorColor 属性无默认值的问题，理论上1.8.0版本及以上都不会有这个问题， 我这边在 13pro上测试没有问题。 如果你确定版本为  1.8.1 ， 请提供一下真机机型、系统版本，我们会继续跟进处理

**Comment by anlyyao** [comment]
> 不指定颜色没光标，真tm恶心

喷子绕道哈
