### ISSUE TITLE
CSS Variables为啥都不好使？

### ISSUE THREAD

**Issue by Hassan-bai** [Tencent/tdesign-miniprogram#3343]
### tdesign-miniprogram 版本

1.8.1

### 重现步骤

    <t-calendar 
      visible="{{true}}" 
      bind:select="onSelect" 
      value="{{value}}"
      type="single"
      minDate="{{minDate}}"
      maxDate="{{maxDate}}"
      usePopup="{{false}}"
      t-class="calendar-panel"
      showTitle="{{false}}"
    />
    
    
    
    .calendar-panel {
  --td-calendar-days-color: #333;
  --td-calendar-item-height: 100rpx;
  --td-calendar-title-color: #333;
  --td-calendar-active-color: #0052d9;
  --td-calendar-selected-color: #0052d9;
  --td-calendar-title-font-size: 32rpx;
}

试了好几个组件都不行，样式覆盖不了？？？why？？？

### 基础库版本

3.6.6

**Comment by anlyyao** [comment]
@Hassan-bai  我们没有提供 --td-calendar-item-height 这个变量吧？  --td-calendar-active-color 可能是命名错误了，它表示 '选择项背景色'， 其他我测试了没有问题，这里是代码片段，https://developers.weixin.qq.com/s/TcDO7kmf7QWr
