### ISSUE TITLE
t-upload不能自定义上传样式

### ISSUE THREAD

**Issue by Hassan-bai** [Tencent/tdesign-miniprogram#3344]
### 这个功能解决了什么问题

我想用其他的方式  比如button去点击上传，但是目前的t-upload并不支持自定义样式，很不灵活

### 你建议的方案是什么

建议参考vant，超越vant

**Comment by anlyyao** [comment]
@Hassan-bai 支持 add-content 属性同名插槽，你用 add-content  插槽去自定义上传样式

see：https://tdesign.tencent.com/miniprogram/components/upload?tab=api

**Comment by Hassan-bai** [comment]
用了，点击事件那些都不好使了

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月11日 17:01 |
| 收件人 | Tencent/tdesign-miniprogram ***@***.***> |
| 抄送人 | Hassan-bai ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [Tencent/tdesign-miniprogram] t-upload不能自定义上传样式 (Issue #3344) |

Closed #3344 as completed.
