### ISSUE TITLE
[calendar] 真机上不显示年月

### ISSUE THREAD

**Issue by iamdaning** [Tencent/tdesign-miniprogram#3345]
### tdesign-miniprogram 版本

1.8.1

### 重现步骤

真机上不显示年月，开发者工具正常。
判定引用错误：
miniprogram_npm\tdesign-miniprogram\calendar\calendar.wxml中引用```<wxs src="./calendar.wxs" module="this" />```
修复方法：
miniprogram_npm\tdesign-miniprogram\calendar\template.wxml中添加引用```<wxs src="./calendar.wxs" module="this" />```

**Comment by anlyyao** [comment]
@iamdaning 提供一下真机机型

**Comment by iamdaning** [comment]
> @iamdaning 提供一下真机机型

redmi k60，Xiaomi HyperOS, WeChat Version 8.0.54

**Comment by anlyyao** [comment]
> > @iamdaning 提供一下真机机型
> 
> redmi k60，Xiaomi HyperOS 1.0.14.0.UMNCNXM, WeChat Version 8.0.54

🫡收到反馈

**Comment by anlyyao** [comment]
@iamdaning 我这边没有k60机型，只在k30和k50 pro上面测试了一下，没有复现出你的问题。 另外需要注意的是，calendar组件没有去适配 [glass-easel](https://github.com/wechat-miniprogram/glass-easel)， 相关配置请先移除～

按照微信文档对 <include> 的描述，<wxs>模块放在 calendar.wxml 应该是正确的。

参考文档：
1. https://developers.weixin.qq.com/miniprogram/dev/reference/wxml/import.html
2. https://developers.weixin.qq.com/miniprogram/dev/reference/wxs/01wxs-module.html#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

**Comment by iamdaning** [comment]
有一个新的问题，auto-close

> @iamdaning 我这边没有k60机型，只在k30和k50 pro上面测试了一下，没有复现出你的问题。 另外需要注意的是，calendar组件没有去适配 [glass-easel](https://github.com/wechat-miniprogram/glass-easel)， 相关配置请先移除～
> 
> 按照微信文档对 `<include>` 的描述，`<wxs>`模块放在 calendar.wxml 应该是正确的。
> 
> 参考文档：
> 
> 1. https://developers.weixin.qq.com/miniprogram/dev/reference/wxml/import.html
> 2. https://developers.weixin.qq.com/miniprogram/dev/reference/wxs/01wxs-module.html#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

谢谢，我删除了```app.json```中的```"componentFramework": "glass-easel"```问题得以修复。但我又发现了新的问题：
文档中提到了 ```auto-close```并未生效，我这这个位置添加了如下代码进行尝试
![image](https://github.com/user-attachments/assets/a9ec00ef-89a8-4aa1-9d07-092b4961497e)

**Comment by iamdaning** [comment]
有一个新的问题，auto-close

> @iamdaning 我这边没有k60机型，只在k30和k50 pro上面测试了一下，没有复现出你的问题。 另外需要注意的是，calendar组件没有去适配 [glass-easel](https://github.com/wechat-miniprogram/glass-easel)， 相关配置请先移除～
> 
> 按照微信文档对 `<include>` 的描述，`<wxs>`模块放在 calendar.wxml 应该是正确的。
> 
> 参考文档：
> 
> 1. https://developers.weixin.qq.com/miniprogram/dev/reference/wxml/import.html
> 2. https://developers.weixin.qq.com/miniprogram/dev/reference/wxs/01wxs-module.html#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

谢谢，我删除了```app.json```中的```"componentFramework": "glass-easel"```问题得以修复。但我又发现了新的问题：
文档中提到了 ```auto-close```并未生效，我这这个位置添加了如下代码进行尝试
![image](https://github.com/user-attachments/assets/a9ec00ef-89a8-4aa1-9d07-092b4961497e)

**Comment by iamdaning** [comment]
> @iamdaning autoClose 逻辑，calendar组件在内部处理了，
> 
> https://github.com/Tencent/tdesign-miniprogram/blob/e5e1a1bb2a31e9e214c98e13d3fb0bc521351c2b/src/calendar/calendar.ts#L216
> 
> 
> 我们在官网的每个示例页面都放了示例代码片段，你可以直接参考： **site**： https://tdesign.tencent.com/miniprogram/components/calendar?tab=demo
> 
> **代码片段入口**：<img alt="截屏2024-12-10 16 19 35" width="1161" src="https://private-user-images.githubusercontent.com/51158141/394185307-67e6d007-5015-42d9-b3a1-fa166daf637f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MTk1MTUsIm5iZiI6MTczMzgxOTIxNSwicGF0aCI6Ii81MTE1ODE0MS8zOTQxODUzMDctNjdlNmQwMDctNTAxNS00MmQ5LWIzYTEtZmExNjZkYWY2MzdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDA4MjY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmZWE5MTZlYmVkY2UwZjEyYzc0ODQzMzk4ZjVhMjM5ZDFjMWQ0ODljOWZmOWUwZDU3NjZkYjE5YmQyZGU2YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WqlReRyALzKFsozTPxuElBuTwbNhjaPIpAUc0_9n3SQ">
> 
> 代码片段： https://developers.weixin.qq.com/s/jhQLMkmJ7JWM

抱歉，我确实没仔细看文档，下意识认为 auto-close 与 Popup close-on-overlay-click 的属性相同，如果是我封装，我会沿用 Popup 的思路把遮罩层独立出来，保证组件的风格一致性。

感谢你们为开源做出的贡献，我会认真看文档的。

**Comment by anlyyao** [comment]
@iamdaning 受其他端影响，td小程序端也引入了受控和非受控用法。而 popup 中的 visible 是完全受控的，它的visible不会在组件内部处理，而是通过 visible-change 事件传递传来，使用时需要主动更新。 至于风格，其实是保持一致的，当你关闭 autoClose，所有的关闭操作会走 close 事件，你需要基于 close 去主动关闭
