### ISSUE TITLE
[icon] 部分图标不展示

### ISSUE THREAD

**Issue by qiyaozu** [Tencent/tdesign-miniprogram#3347]
### tdesign-miniprogram 版本

1.8.1

**Comment by anlyyao** [comment]
@qiyaozu 辛苦提供一下具体图标名称，我这边针对性看看、

**Comment by scottfly189** [comment]
@qiyaozu 应该更新到1.8.0就可以了,我就是这样处理的。

**Comment by anlyyao** [comment]
> @qiyaozu 应该更新到1.8.0就可以了,我就是这样处理的。

你提供的有问题的版本是 1.8.1， 然后回退到 1.8.0图标正常了？ 是这个意思吗？

**Comment by anlyyao** [comment]
@qiyaozu 1.8.0 版本新增了 900+ 图标，理论上 1.8.0 版本及以上，新图标都会可见

详情见官网日志 https://tdesign.tencent.com/miniprogram/changelog
