### ISSUE TITLE
[dialog] dialog组件取消按钮不显示

### ISSUE THREAD

**Issue by qiyaozu** [Tencent/tdesign-miniprogram#3352]
### tdesign-miniprogram 版本

1.8.1

### 重现步骤

![image](https://github.com/user-attachments/assets/264a7561-035b-4e43-8869-0ec66c2fbae8)
![image](https://github.com/user-attachments/assets/fd116030-cdbc-43ff-af38-5fe31031e0bc)

**Comment by anlyyao** [comment]
@qiyaozu 朋友 用法不对哇～

你要传对象就传对象 ===>  ```cancel-btn="{{ {content: '取消'} }}"```
要传字符串就直接传字符串 ===> ```cancel-btn="取消"```
