### ISSUE TITLE
[picker] 啥也不显示

### ISSUE THREAD

**Issue by qiyaozu** [Tencent/tdesign-miniprogram#3353]
### tdesign-miniprogram 版本

1.8.1

### 重现步骤

![image](https://github.com/user-attachments/assets/a986b725-54bd-4c0e-977a-1377bda55435)
![image](https://github.com/user-attachments/assets/ba8c11f4-d142-4a4f-95db-9f17a0f6eb8b)

### 基础库版本

3.7.0

**Comment by anlyyao** [comment]
@qiyaozu 开了 glass-easel ？

**Comment by anlyyao** [comment]
> @qiyaozu 开了 glass-easel ？

@qiyaozu 建议使用时参考下示例
