### ISSUE TITLE
文档文字错误

### ISSUE THREAD

**Issue by rzdong** [Tencent/tdesign-miniprogram#3361]
### tdesign-miniprogram 版本

1.8.2

### 重现链接

https://tdesign.tencent.com/miniprogram/components/upload

### 重现步骤

<img width="392" alt="image" src="https://github.com/user-attachments/assets/8af91325-cd60-40b1-869c-b6bf048f33ca" />

**Comment by anlyyao** [comment]
@rzdong 感谢反馈，我们会尽快修正文案，也欢迎直接来 pr 修复，一起共建开源～
