### ISSUE TITLE
小程序开发工具中如何升级TDesign组件版本

### ISSUE THREAD

**Issue by farsunset-com** [Tencent/tdesign-miniprogram#3363]
### 这个功能解决了什么问题

  "dependencies": {
    "tdesign-miniprogram": "^1.8.2"
  }

### 你建议的方案是什么

升级了版本 小程序开发工具如何操作能拉到最新的包呢

**Comment by anlyyao** [comment]
@farsunset-com  
<img width="660" alt="截屏2024-12-17 14 45 13" src="https://github.com/user-attachments/assets/67a622ef-ba9c-4732-8956-974347e6f8f4" />
