### ISSUE TITLE
[t-popup] 和t-navbar一起使用有bug

### ISSUE THREAD

**Issue by Eug620** [Tencent/tdesign-miniprogram#3373]
### tdesign-miniprogram 版本

1.8.0

### 重现步骤

在使用了t-navbar的页面使用t-popup的时候，t-popup的遮罩层无法盖到t-navbar上面，
![1734590208682](https://github.com/user-attachments/assets/096cc655-e441-481c-ae52-8b2ce67ce4a9)

### 期望结果

t-popup的遮罩层可以盖在t-navbar上面

### 实际结果

t-popup的遮罩层未能盖在t-navbar上面

### 基础库版本

3.7.0

**Comment by anlyyao** [comment]
@Eug620 using-custom-navbar 属性取false。 

提 issue 请按规范提供信息，需要贴可复现代码片段或者实际使用代码，贴一张图定位不到问题、

**Comment by Eug620** [comment]
感谢回复，刚才去翻以往issue发现就是using-custom-navbar这个设置给配置了产生的问题
