### ISSUE TITLE
[fab] fab 可以自由拖动时，希望能在onMove方法中对外抛出事件，以便于外部记录当前fab组件的位置，持久化保存

### ISSUE THREAD

**Issue by rzdong** [Tencent/tdesign-miniprogram#3374]
### 这个功能解决了什么问题

我拖动fab组件到新位置，它没有办法记住自己的位置，导致下次刷新或者其他页面在使用时，无法记录上一次位置

### 你建议的方案是什么

对外抛出move事件，或者有其他方法能通知外部组件当前fab的位置。

**Comment by anlyyao** [comment]
@rzdong 可以的。 刚发完 1.8.3， 这个需求预计下个版本带上哈～
