### ISSUE TITLE
[t-avatar] 头像尺寸传 rpx 单位时，font-size 计算结果是 NaN

### ISSUE THREAD

**Issue by wangming-0215** [Tencent/tdesign-miniprogram#3375]
### tdesign-miniprogram 版本

1.8.2

### 补充说明

![image](https://github.com/user-attachments/assets/d4ef6aea-f03b-4c34-a7c8-79bb51938f90)
![image](https://github.com/user-attachments/assets/512d2f8c-d97c-43be-9066-71f55e683338)
这里是不是也要处理一下rpx单位？

**Comment by anlyyao** [comment]
@wangming-0215 只支持了 px，倒是也符合api描述 😂。  rpx 单位 我们下个版本处理，感谢反馈～

**Comment by wangming-0215** [comment]
> @wangming-0215 只支持了 px，倒是也符合api描述 😂。 rpx 单位 我们下个版本处理，感谢反馈～

好的好的，非常感谢！我先自己处理转成px先用着

**Comment by anlyyao** [comment]
> > @wangming-0215 只支持了 px，倒是也符合api描述 😂。 rpx 单位 我们下个版本处理，感谢反馈～
> 
> 好的好的，非常感谢！我先自己处理转成px先用着

已处理。 本周没有发版计划，预计下周 1.8.4 版本可带
