### ISSUE TITLE
[calendar] 增加switchMode切换月份事件

### ISSUE THREAD

**Issue by prprprPro** [Tencent/tdesign-miniprogram#3378]
### 这个功能解决了什么问题

能够在切换月份时返回到页面上进行处理，在数据量较大或需要动态加载每个月的单独数据时非常有效。

### 你建议的方案是什么

在`canlendar.js`的`handleSwitchModeChange`方法的最后加上
```
this._trigger('switch', {
	value: newValue
});
```

**Comment by anlyyao** [comment]
@prprprPro 下个版本将补充一个 panel-change 事件，事件类型为 (year: number, month: number) => void
