### ISSUE TITLE
[fab][cell][自定义主题] 自定义主题后，cell和fab的颜色在不同的小程序基础库中的表现不一致

### ISSUE THREAD

**Issue by xiguazhiPrince** [Tencent/tdesign-miniprogram#3382]
### tdesign-miniprogram 版本

"tdesign-miniprogram": "^1.8.2"

### 重现链接

https://developers.weixin.qq.com/s/SqtXWEmt71Wt

### 重现步骤

# 环境:

开发工具：nightly 1.06.2412182

项目运行：

npm i
构建npm

# 主题色配置：
```
/**app.wxss**/
page {

    background-color: #f6f6f6;
    
    --td-primary-color-1: #b3b3b3;
    --td-primary-color-2: #999999;
    --td-primary-color-3: #808080;
    --td-primary-color-4: #737373;
    --td-primary-color-5: #666666;
    --td-primary-color-6: #525252;
    --td-primary-color-7: #333333;
    --td-primary-color-8: #292929;
    --td-primary-color-9: #1f1f1f;
    --td-primary-color-10: #0d0d0d;
}
```

# 问题
在3.7.2基础库版本中，可以看到首页的按钮图标是黑色的，这个是复合预期的
在3.3.5基础库版本中，可以看到首页的按钮图标是蓝色的，这个不符合预期

### 基础库版本

3.3.5

**Comment by anlyyao** [comment]
@xiguazhiPrince 可能要排查一下是否为样式隔离问题， 看上去是全局样式在开启了 apply-shared 的页面中未生效，这不是组件问题

**Comment by anlyyao** [comment]
@xiguazhiPrince 你的代码片段运行在我自己的开发工具中（stable 1.06.2407120），3.7.2 和 3.3.5 基础调试库下，cell组件的图标都是蓝色的。

目前有以下几个方案： 1. 移除页面中的  "styleIsolation" : "apply-shared"；2. 不使用全局样式，样式改成页面级； 3. 补充一个同级类选择器：.page ，在需要的组件上通过外部样式类class手动添加 .page 类名，具体操作如下：

```
// 页面

// app.wxss
/**app.wxss**/
page {

    background-color: #f6f6f6;
    
    --td-primary-color-1: #b3b3b3;
    --td-primary-color-2: #999999;
    --td-primary-color-3: #808080;
    --td-primary-color-4: #737373;
    --td-primary-color-5: #666666;
    --td-primary-color-6: #525252;
    --td-primary-color-7: #333333;
    --td-primary-color-8: #292929;
    --td-primary-color-9: #1f1f1f;
    --td-primary-color-10: #0d0d0d;
}

**Comment by xiguazhiPrince** [comment]
> @xiguazhiPrince 你的代码片段运行在我自己的开发工具中（stable 1.06.2407120），3.7.2 和 3.3.5 基础调试库下，cell组件的图标都是蓝色的。
> 
> 目前有以下几个方案： 1. 移除页面中的 "styleIsolation" : "apply-shared"；2. 不使用全局样式，样式改成页面级； 3. 补充一个同级类选择器：.page ，在需要的地方手动添加 .page 类名，具体操作如下：
> 
> ```
> // 页面
> <scroll-view class="scrollarea page" scroll-y type="list" />
> 
> // app.wxss
> 
> page, .page {
> 
>     background-color: #f6f6f6;
>     
>     --td-primary-color-1: #b3b3b3;
>     --td-primary-color-2: #999999;
>     --td-primary-color-3: #808080;
>     --td-primary-color-4: #737373;
>     --td-primary-color-5: #666666;
>     --td-primary-color-6: #525252;
>     --td-primary-color-7: #333333;
>     --td-primary-color-8: #292929;
>     --td-primary-color-9: #1f1f1f;
>     --td-primary-color-10: #0d0d0d;
> }
> ```
@anlyyao 感谢你的帮助，我试了下添加.page的方案是有效的，styleIsolation的方式无效，最终采用了.page的方案
