### ISSUE TITLE
DateTimePicker 时间选择器 如何指定日期范围

### ISSUE THREAD

**Issue by lijunen2009** [Tencent/tdesign-miniprogram#339]
### tdesign-miniprogram 版本

0.5.4

### 重现步骤

DateTimePicker 时间选择器 如何指定日期范围 如何设定日期范围  ，现在默认的是从2000年到 2030年

### 框架版本

Vue 2.0

**Comment by anlyyao** [comment]
可以通过disableDate指定范围，具体用法参考API使用文档：https://tdesign.tencent.com/miniprogram/components/date-time-picker?tab=api

**Comment by LeeJim** [comment]
如 anlyyao 所说，可以使用 disableDate
