### ISSUE TITLE
[calendar] 日历设置switch-mode后，IOS预览和真机不显示calendar-header中间的月份

### ISSUE THREAD

**Issue by prprprPro** [Tencent/tdesign-miniprogram#3391]
### tdesign-miniprogram 版本

1.8.3

### 重现步骤

简单实现
`<t-calendar switch-mode="month" use-popup="{{false}}" />`
请观察切换月份header的中间标题
PC端正常
![image](https://github.com/user-attachments/assets/1074f1e6-bd17-4d78-954f-abcbb3ab325b)
IOS端不显示中间的月份，左右切换后也没有
![dfa91e245c28b6d5707fb9b3b5dca24](https://github.com/user-attachments/assets/d519823b-04e7-44de-93e3-48b734a2a55f)

### 期望结果

经核查，template.wxml文件缺少了对calendar.wxs的引用
`<wxs src="./calendar.wxs" module="this" />`
导致line 25和line 42的this.getMonthTitle无法返回正确的title
请在template.wxml最前面补充该引用

### 实际结果

template.wxml文件的this.getMonthTitle无效引用

### 补充说明

我感觉这是不是基础库的问题...电脑端是好的说明能跨文件引用wxs，IOS端就不行

**Comment by prprprPro** [comment]
我感觉这是不是基础库的问题...电脑端是好的说明能跨文件引用wxs，IOS端就不行

**Comment by prprprPro** [comment]
> @prprprPro 看下是不是 #3345 问题， 需要移除配置："componentFramework": "glass-easel"

可以解决，谢谢。现在新建项目app.json默认都带这个配置，要不要考虑文档里提一下，不然默认配置都加载不出的。

**Comment by anlyyao** [comment]
> > @prprprPro 看下是不是 #3345 问题， 需要移除配置："componentFramework": "glass-easel"
> 
> 可以解决，谢谢。现在新建项目app.json默认都带这个配置，要不要考虑文档里提一下，不然默认配置都加载不出的。

🫡，正准备给文档再加一个 FAQ

**Comment by anlyyao** [comment]
> > > @prprprPro 看下是不是 #3345 问题， 需要移除配置："componentFramework": "glass-easel"
> > 
> > 
> > 可以解决，谢谢。现在新建项目app.json默认都带这个配置，要不要考虑文档里提一下，不然默认配置都加载不出的。
> 
> 🫡，正准备给文档再加一个 FAQ

😂 挣扎了一下 ，我会在 template.wxml 文件中，重新加入对 calendar.wxs 文件引用

**Comment by prprprPro** [comment]
> > > > @prprprPro 看下是不是 #3345 问题， 需要移除配置："componentFramework": "glass-easel"
> > > 
> > > 
> > > 可以解决，谢谢。现在新建项目app.json默认都带这个配置，要不要考虑文档里提一下，不然默认配置都加载不出的。
> > 
> > 
> > 🫡，正准备给文档再加一个 FAQ
> 
> 😂 挣扎了一下 ，我会在 template.wxml 文件中，重新加入对 calendar.wxs 文件引用

哈哈哈哈保险点！感谢！
