### ISSUE TITLE
[picker-item] 选项过长时文本直接截断，没有正确应用省略号

### ISSUE THREAD

**Issue by prprprPro** [Tencent/tdesign-miniprogram#3405]
### tdesign-miniprogram 版本

1.8.4

### 期望结果

picker-item.wxml line 23 给`{{option[labelAlias]}}`套个text标签
`<text style="overflow: hidden;text-overflow: ellipsis;white-space: nowrap;">{{option[labelAlias]}}</text>`
这样就可以正确应用省略号了
![image](https://github.com/user-attachments/assets/fcc25c66-9e91-4804-9491-e771198908a3)

### 实际结果

选项过长时文本直接截断，没有正确应用省略号

**Comment by anlyyao** [comment]
@prprprPro 为何不直接来个 pr 尼 🤔

**Comment by prprprPro** [comment]
> @prprprPro 为何不直接来个 pr 尼 🤔

没有必要的话我不是很想打开这团代码（哈哈哈哈总之下次一定
