### ISSUE TITLE
[Upload] 属性 request-method

### ISSUE THREAD

**Issue by chowhugh** [Tencent/tdesign-miniprogram#341]
### tdesign-miniprogram 版本

 "tdesign-miniprogram": "^0.7.3"

### 重现步骤

customizeUpload: function(files){
 console.log("hello")
}

 <t-upload
                media-type="{{['image']}}"
                request-method="{{customizeUpload}}"
 />

### 期望结果

执行customizeUpload

### 实际结果

不执行

upload/upload.js 103行
   startUpload(files) {
        // 如果传入了上传函数，则进度设为0并开始上传，否则跳过上传
        if (typeof this.data.requestMethod === 'function') {
            return this.uploadFiles(files);
        }
        this.handleLimit(this.data.customFiles, this.data.max);
        return Promise.resolve();
    }
typeof this.data.requestMethod 为object

**Comment by LeeJim** [comment]
小程序好像不支持 function props，只能支持 object 然后子字段才可以是 function

**Comment by chowhugh** [comment]
是否可以暴露event，而不是作为prop传进去

**Comment by Winfans** [comment]
> 小程序好像不支持 function props，只能支持 object 然后子字段才可以是 function。
> 关联文档：https://developers.weixin.qq.com/miniprogram/dev/reference/api/Component.html

目前是可以的，props设置null，传进去function就是function了

**Comment by Winfans** [comment]
> 是否可以暴露event，而不是作为prop传进去

这里能否贴一下调用方的代码看看？

**Comment by chowhugh** [comment]
```js
customizeUpload: function(files){
      console.log("hello")
      return Promise.resolve({})
}
```

```xml
<t-upload media-type="{{'image'}}"
          request-method="{{customizeUpload}}"
>
</t-upload>
```

**Comment by Winfans** [comment]
> ```js
> ```js
> customizeUpload: function(files){
>       console.log("hello")
>       return Promise.resolve({})
> }
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```
> <t-upload media-type="{{'image'}}"
>           request-method="{{customizeUpload}}"
> >
> </t-upload>
> ```
> ```

这里customizeUpload是定义在data里面的吗？得定义在data里面的才能用{{ customizeUpload }} 传入request-method
