### ISSUE TITLE
[tag] build:dist 失败，提示无导入的 CSSProperties

### ISSUE THREAD

**Issue by mouyong** [Tencent/tdesign-miniprogram#351]
### tdesign-miniprogram 版本

master

### 重现链接

暂时不用提供连接。

### 重现步骤

git clone git@github.com:Tencent/tdesign-miniprogram.git

yarn build:dist

### 期望结果

能正常构建出 dist 包

### 实际结果

![image](https://user-images.githubusercontent.com/10336437/163240084-2c07ed32-948c-4347-bb8e-d5a83789b3c8.png)

### 框架版本

小程序开发者工具 Nightly 1.06.2204082

### Node版本

16.14.0

**Comment by Winfans** [comment]
<img width="466" alt="image" src="https://user-images.githubusercontent.com/40023619/163297569-e3399ff4-576a-4e14-bd33-733ab5c98116.png">
这里确实有问题，小程序应该没有CSSProperties。tag组件的type.ts有问题。

**Comment by LeeJim** [comment]
已修复
