### ISSUE TITLE
[Picker] 滚动 items 延迟

### ISSUE THREAD

**Issue by CrossLee** [Tencent/tdesign-miniprogram#355]
### tdesign-miniprogram 版本

0.7.3

### 重现步骤

官方示例里面体验

![image](https://user-images.githubusercontent.com/4584905/163516594-98c74e19-752d-4f52-bafb-a67e417060c7.png)

视频录制

https://user-images.githubusercontent.com/4584905/163516634-21933bbe-5205-4ee5-9bac-a72dab1184ed.mp4

### 期望结果

滚动不要延迟，参考系统自带滚动体验。

### 实际结果

滚动 items 延迟

### 框架版本

小程序 2.14.1

**Comment by CrossLee** [comment]
另外官方的例子里面默认「取消」「确定」按钮也没有，需手动填写后才会出现，和属性描述不一致。

**Comment by jin0209** [comment]
> 另外官方的例子里面默认「取消」「确定」按钮也没有，需手动填写后才会出现，和属性描述不一致。

优化引入bug导致，新版本已修复

**Comment by CrossLee** [comment]
我在开发者工具里录制测试用例发现个现象，Picker 切换 item 的时候，疯狂录制多条同样的记录，这里就切换了一个 item（即 Picker 里只有两个选项，从「横版」切换到「竖版」），结果 touchmove 记录了接近 30 次。而且测试回放时无法正确的切换 item，不知道对这个 issue 有没有帮助？

<img width="654" alt="image" src="https://user-images.githubusercontent.com/4584905/164617319-ff1492bc-fbe4-4306-a3d9-9c2a34cdaf73.png">

https://user-images.githubusercontent.com/4584905/164617588-4c911c00-be65-4ce8-8459-23e78a4d5b60.mov

**Comment by LeeJim** [comment]
我来跟进下。
