### ISSUE TITLE
[Input] Android 点击输入框会闪烁，输入法也跟着闪烁

### ISSUE THREAD

**Issue by CrossLee** [Tencent/tdesign-miniprogram#359]
### tdesign-miniprogram 版本

0.7.3

### 重现步骤

使用的官方示例测试，所以没有加 CodePen 代码。

扫码进入表单里的 Input 可以测试。
![image](https://user-images.githubusercontent.com/4584905/163661692-5b63f8d8-0aa9-44aa-9dc5-5c30ea87558f.png)

Android 测试视频：

https://user-images.githubusercontent.com/4584905/163661716-e706336c-3a7d-4e5d-aa38-ac124ba3a109.mp4

iOS 测试视频：

https://user-images.githubusercontent.com/4584905/163661725-416c22a1-322b-4963-bdb4-5343d0d24e4b.mp4

### 期望结果

单次点击即进入输入（focus）状态，并且切换 Input 键盘不要关闭再打开（闪烁）

### 实际结果

点击输入框会闪烁，输入法也跟着闪烁。

iOS有时候点击多次才能进入编辑状态。

### 补充说明

感觉是处理 confirm-type 时导致的。

**Comment by zhenzhencai** [comment]
感谢反馈，但是小程序方提供的input组件在安卓端本身就存在这个闪烁的问题，已向微信方反馈。

**Comment by CrossLee** [comment]
> 感谢反馈，但是小程序方提供的input组件在安卓端本身就存在这个闪烁的问题，已向微信方反馈。

@zhenzhencai iOS 下也有问题，你用上面贴的那个小程序码测试一下输入框，特别是在表单里有多个input的时候，很难点击，键盘也是有时候弹有时候不弹

**Comment by LeeJim** [comment]
input 处于 focus 状态之后，点击其他地方都是会收起键盘的，
如果想不收起键盘，可以考虑使用这个熟悉：hold-keyboard
https://developers.weixin.qq.com/miniprogram/dev/component/input.html
