### ISSUE TITLE
[Loading] 增加全屏遮罩 Loading

### ISSUE THREAD

**Issue by CrossLee** [Tencent/tdesign-miniprogram#364]
### 这个功能解决了什么问题

进入新的页面为了在数据加载出来前不让用户操作，需要通过全屏遮罩的 loading 覆盖。

### 你建议的方案是什么

实现 wx.showLoading 类似全屏遮罩功能，嫁接 TDesign-Miniprogram 的现有特性（可以自定义样式，文字可以较多等），可以满足需求。

**Comment by JJunYang** [comment]
好的哈，感谢建议！

**Comment by LeeJim** [comment]
我的建议是，抽象出一个 overlay 组件，然后 loading 依赖于 overlay 即可

**Comment by LeeJim** [comment]
使用 preventScrollThrough 即可满足你的需要
