### ISSUE TITLE
[PickerItem] 支持不可选中项目

### ISSUE THREAD

**Issue by CrossLee** [Tencent/tdesign-miniprogram#367]
### 这个功能解决了什么问题

下拉框提示用户这个下拉框里「总共有这些选项」，但是有的选项暂时不支持选择。若不支持选择的选项不显示在 items 里面，那么用户可能以为总的选项就这么多，就算未来开放了用户潜意识里还是以前那么多选项。

### 你建议的方案是什么

添加 disabeld 值进行判断，类似：
usages: [
      { label: "个人商务", value: "personalbusiness"},
      { label: "个人社交", value: "personalsocial" },
      { label: "企业商务", value: "companybusiness", disabled: true  },
    ],

**Comment by LeeJim** [comment]
因为 picker 是受控的。
因此可以将所有的展示处理，当用户选择了不可选的值，你toast提示即可
