### ISSUE TITLE
[Picker] 选择子组件命名不一致

### ISSUE THREAD

**Issue by JJunYang** [Tencent/tdesign-miniprogram#368]
### tdesign-miniprogram 版本

0.8.0

### 重现步骤

picker组件的子组件使用的是t-picker-column，实际应该是t-picker-item子组件，多端应该统一规范命名

### 期望结果

改用t-picker-item

### 实际结果

t-picker- column

### 框架版本

miniprogram

**Comment by LeeJim** [comment]
我来处理一下
