### ISSUE TITLE
[Steps] 步骤组件名字不一致

### ISSUE THREAD

**Issue by JJunYang** [Tencent/tdesign-miniprogram#371]
### tdesign-miniprogram 版本

0.8.0

### 重现步骤

步骤的子组件名应该为step-item，希望多端统一名称

### 期望结果

子组件改名使用t-step-item

### 实际结果

t-step

### 框架版本

miniprogram

**Comment by LeeJim** [comment]
组件确实是叫 step-item，不过示例代码里没这么用，确实可以改一下
