### ISSUE TITLE
[Tabs] 支持 click 事件

### ISSUE THREAD

**Issue by wutianSweet** [Tencent/tdesign-miniprogram#374]
### 这个功能解决了什么问题

现目前只支持change 已经被选中的tab 如果触发点击， 无法获取到点击事件

### 你建议的方案是什么

建议新增click 事件

**Comment by JJunYang** [comment]
好的哈！感谢建议

**Comment by JJunYang** [comment]
点击已选中的tab触发click事件有什么场景需求么？

**Comment by LeeJim** [comment]
已了解大概场景。
现在如果点击 active 的 tab 是不会触发 change 事件的，因此没办法知道用户点击了 active 的 tab

**Comment by JJunYang** [comment]
这理解了，但是点击非active的tab有必要触发click事件么？添加的话相当于触发click和change，不添加的话又似乎不统一，使用起来可能又困惑为什么不触发click事件
