### ISSUE TITLE
message：Error: tdesign-miniprogram/example/components/demo-block/index.js does not exists

### ISSUE THREAD

**Issue by arbraces** [Tencent/tdesign-miniprogram#376]
### tdesign-miniprogram 版本

^0.8.0

### 重现步骤

小程序真机调试的时候出现的这个问题，正常开发过程也没有其他报错

### 系统版本

Windows10

**Comment by anlyyao** [comment]
你是用什么方式引入的组件呢？ 以及开发环境和调试工具？  我这边尝试了0.8.0版本的 npm包和本地构建两种方式引入，调用 Message都是正常的～～

**Comment by arbraces** [comment]
npm的方式引入的，不是调用组件出了问题，是使用微信开发者工具里面的真机调试出现的问题
![image](https://user-images.githubusercontent.com/54385113/164168489-4de5b7b2-19a5-4987-aa1c-6c3c1c20623d.png)

**Comment by anlyyao** [comment]
@arbraces  可以提供一下你的项目目录结构吗？

**Comment by anlyyao** [comment]
@arbraces 我这边真机调试也都是正常的～～

**Comment by LeeJim** [comment]
使用 npm 安装的么，应该不存在 example 的代码
