### ISSUE TITLE
组件引入样式跟文档不一致，如何调整

### ISSUE THREAD

**Issue by synctimes163** [Tencent/tdesign-miniprogram#383]
### tdesign-miniprogram 版本

0.9.0

### 重现步骤

小程序开发工具新建项目，
[](https://tdesign.tencent.com/miniprogram/getting-started#%E4%BD%BF%E7%94%A8-npm)

使用 NPM
小程序已经支持使用 NPM 安装第三方包，详见 [NPM 支持](https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html?search-key=npm)

npm i tdesign-miniprogram -S --production
安装完之后，需要在微信开发者工具中对 npm 进行构建：工具 - 构建 npm

但是引入代码后，预览的样式字体很模糊，而且样式显示与文档不一致
{
  "usingComponents": {
    "t-button": "tdesign-miniprogram/button/button",
    "t-rate": "tdesign-miniprogram/rate/rate"
  }
}

![image](https://user-images.githubusercontent.com/78259973/164417201-f073441b-459d-46b4-a01b-80c6078a6470.png)

### 期望结果

样式统一能正常使用，字体明显过于模糊

**Comment by jin0209** [comment]
@synctimes163 麻烦提供下小程序代码片段，或者贴一下wxml和wxss的内容

**Comment by synctimes163** [comment]
代码片段 https://developers.weixin.qq.com/s/qkx3IGm276y6
字体识别很模糊
![image](https://user-images.githubusercontent.com/78259973/164419543-916530e8-32a4-4fcf-bcd2-0b22b0ecbf69.png)

**Comment by LeeJim** [comment]
看样子并不是组件库的问题。是不是有什么遮罩层？

**Comment by synctimes163** [comment]
并没有用到遮罩层，你应该是没有使用代码片段尝试。 麻烦抽空再看下 t-radio 是正常的字体颜色，虽然样式有点偏差
![image](https://user-images.githubusercontent.com/78259973/164420800-0e25b981-c134-4097-8446-f90d26da0190.png)

**Comment by LeeJim** [comment]
这个 button 的代码看看？ 是不是加了 disabled

**Comment by synctimes163** [comment]
是的，那我这样引入使用是正确的对吧

**Comment by LeeJim** [comment]
对的。那就没问题了
