### ISSUE TITLE
Grid 宫格

### ISSUE THREAD

**Issue by coderdp** [Tencent/tdesign-miniprogram#385]
### 这个功能解决了什么问题

t-grid-item 用于布局，很多情况下需要搭配  t-icon 来使用。目前经过测试，嵌套在 t-grid-item 内部时，无法正常显示 t-icon

### 你建议的方案是什么

建议 t-grid-item 组件内支持 t-icon

**Comment by LeeJim** [comment]
是 grid-item 不支持 default slot 的意思么？

**Comment by hull123** [comment]
宫格代码片段开始：<t-grid class="t-grid badge" wx:if="{{GoodsList.length > 0}}">
          <t-grid-item wx:for="{{GoodsList}}" wx:key="index" text="{{item.text}}" data-item-data="{{item}}" bindtap="clickGridItem" t-class-text="text">
            <t-badge count="{{item.badge}}" slot="image" show-zero="false" t-class="badge-item">
              <view class="grid-icon">
                <image class="image-icon" src="{{item.img}}" />
              </view>
            </t-badge>
          </t-grid-item>
      </t-grid>
宫格代码片段结束

报错data field "layout" is overwritten by property with the same name。    GoodsList一直为空数组 不清楚是什么原因 有没有解决方法

**Comment by hull123** [comment]
代码片段：<t-grid class="t-grid badge" wx:if="{{GoodsList.length > 0}}">
          <t-grid-item wx:for="{{GoodsList}}" wx:key="index" text="{{item.text}}" data-item-data="{{item}}" bindtap="clickGridItem" t-class-text="text">
            <t-badge count="{{item.badge}}" slot="image" show-zero="false" t-class="badge-item">
              <view class="grid-icon">
                <image class="image-icon" src="{{item.img}}" />
              </view>
            </t-badge>
          </t-grid-item>
      </t-grid>

报错data field "layout" is overwritten by property with the same name。 GoodsList一直为空数组 不清楚是什么原因 有没有解决方法
