### ISSUE TITLE
upload  上传成功后，能否把当前的临时地址返回来？

### ISSUE THREAD

**Issue by synctimes163** [Tencent/tdesign-miniprogram#386]
### 这个功能解决了什么问题

upload  上传成功后，能否把当前的临时地址返回来？这有利于，返回当前选中的图片可以将临时地址立马进行上传或通过阿里云校验该图片是否重复。

### 你建议的方案是什么

![image](https://user-images.githubusercontent.com/78259973/164589047-502c1de9-5ffe-449d-bfe2-2ec31179cdd6.png)

**Comment by LeeJim** [comment]
url 就是临时地址
