### ISSUE TITLE
[Drawer] items 的属性错误

### ISSUE THREAD

**Issue by myliweihao** [Tencent/tdesign-miniprogram#387]
### tdesign-miniprogram 版本

0.7.3

### 重现步骤

1）drawer组件items属性文档写着interface DrawerItem { title: string; icon: string; }，而组件代码title没用，用着name。
2）https://tdesign.tencent.com/miniprogram/components/drawer?tab=demo代码演示里sidebar属性是没用属性。

**Comment by anlyyao** [comment]
@myliweihao  感谢反馈， 我跟进一下
