### ISSUE TITLE
[Tabs] 超过屏幕宽度自动滑动无效

### ISSUE THREAD

**Issue by xteabag** [Tencent/tdesign-miniprogram#393]
### tdesign-miniprogram 版本

0.6.2

### 重现步骤

当TAB选项较多时，超过屏幕宽度，自动滑动无效

**Comment by LeeJim** [comment]
试下最新版本 0.9.0 ？我这边是 OK 的

**Comment by JJunYang** [comment]
我这边也是可以的，是不是你另外设置了什么阻止了呢？
