### ISSUE TITLE
[steps] 选中和未选中的点支持自定义样式或者完善slot

### ISSUE THREAD

**Issue by Winfans** [Tencent/tdesign-miniprogram#398]
### 这个功能解决了什么问题

<img width="801" alt="image" src="https://user-images.githubusercontent.com/40023619/165210859-340e3537-45cd-441c-92b5-9021b2731265.png">
目前stpes选中的点如右图所示，想要实现成左侧的样式。使用slot不可行，会导致竖线和点错位，需要自行调整css

### 你建议的方案是什么

希望可以传入外部样式类或者其他方式来自定义样式完善slot

**Comment by Winfans** [comment]
1.希望可以传入外部样式类或者其他方式来自定义样式  2.完善slot

**Comment by LeeJim** [comment]
好的。我来看下
