### ISSUE TITLE
[Image] 使用t-image的时，传入正确的相对路径，路径显示映射错误

### ISSUE THREAD

**Issue by feiwenqiang** [Tencent/tdesign-miniprogram#401]
### tdesign-miniprogram 版本

0.4.2

### 重现步骤

微信小程序中使用t-image组件，src中传入正确的相对路径，控制台却显示路径异常。

### 期望结果

图片加载正常，页面显示正常。

### 实际结果

图片加载异常，页面显示异常。
![mp](https://user-images.githubusercontent.com/84109720/165266470-89e89828-a0b2-4863-a606-1683ee4a1411.png)

**Comment by LeeJim** [comment]
这个确实是微信的问题，没法解决。
建议使用绝对路径，比如 `/images/1.jpg`，或者改为在线资源

**Comment by bb8401** [comment]
当前 @tdesign/uniapp@0.10.3 的 t-image 根节点尺寸在微信小程序的百分比宽度场景中出现异常，资源虽然加载成功但不可见。
