### ISSUE TITLE
[DateTimePicker] defaultValue

### ISSUE THREAD

**Issue by coderdp** [Tencent/tdesign-miniprogram#406]
### tdesign-miniprogram 版本

0.9.0

### 补充说明

![image](https://user-images.githubusercontent.com/12269641/165493716-58d6d9d8-ef38-4a15-80c2-9c4a16274db5.png)

默认时间不生效，且[文档](https://tdesign.tencent.com/miniprogram/components/date-time-picker?tab=api#datetimepicker-props)与[源码](https://github.com/Tencent/tdesign-miniprogram/blob/develop/src/date-time-picker/type.ts#L91)中的参数名称不一致

**Comment by LeeJim** [comment]
收到，我来看下

**Comment by LeeJim** [comment]
确实有问题，我来看看
