### ISSUE TITLE
https://tdesign.gtimg.com/icon/0.0.3/fonts/t.woff net::ERR_CACHE_MISS 

### ISSUE THREAD

**Issue by pengyinghao** [Tencent/tdesign-miniprogram#412]
### tdesign-miniprogram 版本

0.9.0

### 补充说明

经常报这个错，为啥会出现链接哦。

**Comment by LeeJim** [comment]
这是开发者工具报的错吧，是开发者工具的问题，可以忽略。

<img width="976" alt="image" src="https://user-images.githubusercontent.com/7017290/165872198-05d8ad8e-011a-4178-8b1c-ce58d6a17e5f.png">

https://developers.weixin.qq.com/miniprogram/dev/api/ui/font/wx.loadFontFace.html
