### ISSUE TITLE
[Avatar] icon 不随头像尺寸相应改变

### ISSUE THREAD

**Issue by CrossLee** [Tencent/tdesign-miniprogram#421]
### tdesign-miniprogram 版本

0.10.0

### 重现步骤

`<t-avatar t-class="" size="228rpx" shape="circle" alt="1" icon="user" image="{{cuser.userInfo.avatarUrl}}" />`

### 期望结果

希望 icon 尺寸相应变大。

### 实际结果

实际效果：

<img width="331" alt="image" src="https://user-images.githubusercontent.com/4584905/166701490-f674ba5d-405b-45c2-b372-c6569314f46f.png">

**Comment by LeeJim** [comment]
确实有问题
