### ISSUE TITLE
[tdesign-miniprogram] 无法在最新的微信开发者工具中正常显示

### ISSUE THREAD

**Issue by Roc-00** [Tencent/tdesign-miniprogram#436]
### tdesign-miniprogram 版本

官网提供的版本

### 重现步骤

第一次使用TDesign，跟着官网的步骤构建了npm以后，用了几个组件在电脑显示都很奇怪，但是用手机调试就正常
用的是最新的开发者工具，win10
![830cef8d22a8c30df48e2b71bb4bec3](https://user-images.githubusercontent.com/84842773/167418873-405472ac-aaaf-4678-b7c6-8cfca90accfd.jpg)
![image](https://user-images.githubusercontent.com/84842773/167418909-42d83571-eebc-4575-928c-fa431c0766a5.png)

**Comment by qiaoly521** [comment]
重新构建一下就好了
