### ISSUE TITLE
部分组件不支持传入 customStyle 属性来控制组件样式

### ISSUE THREAD

**Issue by pillys** [Tencent/tdesign-miniprogram#44]
【现状】有的组件比如 `t-icon` 可以传入 `customStyle` 属性来控制组件样式，但是有的组件不支持，比如 `t-button`，目前传入 `customStyle` 无效。
【期望】所有组件都支持该属性

**Comment by LeeJim** [comment]
其实我们所有组件都支持 `externalClass`，可以通过这个来覆盖样式的。
而且 `externalClass` 可以支持多个，功能更加强大。
> 因为很多组件不像 icon 这样简单，DOM 比较复杂，通过 customStyle 只能改单一元素。

**Comment by pillys** [comment]
> 

特定场景下可能不方便传入 class 来控制样式，比如可视化编辑器之类的是通过传入各个 style 参数来控制组件的样式，还望能够支持

**Comment by chaishi** [comment]
印象中确实有些组件没有入库 externalClass

**Comment by LeeJim** [comment]
等有场景缺乏 externalClass 的时候，再讨论吧。先 close 了
