### ISSUE TITLE
[Input] borderless把无边框加上吧，否则还要用CSS去覆盖它

### ISSUE THREAD

**Issue by VictorSniper** [Tencent/tdesign-miniprogram#441]
### tdesign-miniprogram 版本

8.0

**Comment by LeeJim** [comment]
已发布于 v 0.11.2，麻烦试用

**Comment by VictorSniper** [comment]
谢谢，已经给同事推荐tdesign-miniprogram，观察以后决定是否使用。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月15日(星期天) 晚上9:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tencent/tdesign-miniprogram] [Input] borderless把无边框加上吧，否则还要用CSS去覆盖它 (Issue #441)





 
已发布于 v 0.11.2，麻烦试用
