### ISSUE TITLE
[t-search] 使用action-click事件，函数无返回值

### ISSUE THREAD

**Issue by shine-lzx** [Tencent/tdesign-miniprogram#442]
### tdesign-miniprogram 版本

^0.11.1

### 重现步骤
```
 <t-search t-class-input-container="t-class__input-container" value="{{searchValue}}" placeholder="搜索你需要的商品" focus action="搜索" bind:action-click="handleSearch" /> 
handleSearch(e: WechatMiniprogram.CustomEvent) {
    console.log('e: ', e)
  },
```

### 期望结果

正常得到输入后的值

### 实际结果

changedTouches: undefined
currentTarget:
dataset:
__proto__: Object
id: ""
__proto__: Object
detail: undefined
mark: {}
mut: false
target: {id: "", dataset: {…}}
timeStamp: 694055
touches: undefined
type: "action-click"
_requireActive: undefined

**Comment by LeeJim** [comment]
我来处理下
