### ISSUE TITLE
[Tabs 选项卡] 用Sticky 吸顶容器吸顶后无法左右滑动

### ISSUE THREAD

**Issue by syq2930644833** [Tencent/tdesign-miniprogram#463]
### tdesign-miniprogram 版本

0.11.2

**Comment by LeeJim** [comment]
试了下，并没有遇到你说的问题。
能否提供下代码片段？

**Comment by syq2930644833** [comment]
> 试了下，并没有遇到你说的问题。 能否提供下代码片段？

抱歉啊，尝试无果删掉啦～手写了一个，我先关掉issues了，之后遇到了什么问题再提，谢谢～

**Comment by LeeJim** [comment]
通过反馈，了解了具体的情况。
建议：使用 sticky 包裹需要吸顶的组件，而不是所有组件即可。
