### ISSUE TITLE
input 组件 使用了即将废弃的属性 “auto-focus”

### ISSUE THREAD

**Issue by wutianSweet** [Tencent/tdesign-miniprogram#47]
![image](https://user-images.githubusercontent.com/11713735/147375793-6108ac63-d960-4340-aa2a-ea6f6dbc7a89.png)

使用 audits 评分的时候会提示异常

![image](https://user-images.githubusercontent.com/11713735/147375819-1bde35df-78b5-4b3a-8988-b5a85ecb0e58.png)

**Comment by chaishi** [comment]
<img width="306" alt="image" src="https://user-images.githubusercontent.com/11605702/147376057-b3b16f9d-2f1f-406a-bc3e-be11e5892277.png">

因为还没有完全废弃，所以当前的做法是：
autofoucs 对应 auto-focus
focus 对应 focus

可以忽略 auto-focus，直接使用 focus

**Comment by LeeJim** [comment]
OK 我来处理下
