### ISSUE TITLE
[t-button] 无法加入自定义的icon

### ISSUE THREAD

**Issue by ws2003gq** [Tencent/tdesign-miniprogram#476]
### 这个功能解决了什么问题

button 没法加入自定义icon

### 你建议的方案是什么

button 可以加入自定义icon

**Comment by LeeJim** [comment]
能否提供代码片段？

**Comment by ws2003gq** [comment]
这个也不是bug，咋提供一个不存在的东西。。
就是在button主键里面 button.wxml里面我看没法给t-icon 配置前缀的属性，所以导致 个人自定义的icon无法插入到button里面去。希望button增加可以添加自定义icon的途径
 ` <t-icon wx:if="{{icon}}" name="{{icon}}" class="{{classPrefix}}__icon {{prefix}}-class-icon"></t-icon>`

**Comment by ws2003gq** [comment]
icon 组件是有这个属性的【prefix】：
`<t-icon prefix="icon" name="a-1h" size="xl" bind:click="someFunction" />`
