### ISSUE TITLE
[Popup]弹出层包含input输入框placeholder显示的时候会抖动

### ISSUE THREAD

**Issue by xiaofeng1998025** [Tencent/tdesign-miniprogram#489]
### tdesign-miniprogram 版本

0.11.2

### 重现步骤

<t-popup visible="{{show}}" placement="center" >
        <view  slot="content" class="x_add_con">
                <input class="inputs" placeholder="asdasda"  />
            </view>
        </view>
    </t-popup>

### 期望结果

显示时input不要抖动

### 实际结果

隐藏显示时input会抖动

### 框架版本

微信2.24.2库

**Comment by LeeJim** [comment]
这个问题我查了一下，是 popup 的 scale 动画引起的，没办法直接处理好。
现在新增了一个 transition-end 事件用于处理，可以在 transition-end 触发之前先隐藏 placeholder或者input，然后在 触发 transition-end 触发之后再展示 placeholder 或者 input

**Comment by xieerduos** [comment]
> 这个问题我查了一下，是 popup 的 scale 动画引起的，没办法直接处理好。 现在新增了一个 `transition-end` 事件用于处理，可以在 `transition-end` 触发之前先隐藏 placeholder 或者 input，然后在 `transition-end` 触发之后再展示 placeholder 或者 input


感谢提供思路，以下是我解决抖动的方案具体代码

就是添加一个css 去掉 动画即可  `animation: none;transition: none`

```html
<t-dialog style="animation: none;transition: none"></t-dialog>
```

**Comment by zeb9518** [comment]
这个方案，好像只是把t-dialog通过css的方式隐藏了起来，确实会不抖动了，但是会让元素仍然存在，导致无法穿透事件
