### ISSUE TITLE
支持taro吗

### ISSUE THREAD

**Issue by zhucheng1991** [Tencent/tdesign-miniprogram#49]
按照说明clone下来 build后 复制到根目录 运行小程序 复制了tbutton作为demo 提示 ["usingComponents"]["t-button"] 未找到
![image](https://user-images.githubusercontent.com/33744918/147452096-97af718c-55e1-4c9f-a714-9a5e37cabaf4.png)
![image](https://user-images.githubusercontent.com/33744918/147452186-eebca5ba-a6d1-4070-ab85-45cbed0ff7e8.png)

**Comment by LeeJim** [comment]
taro 没试过。
但你这个 usingComponent 的路径就不对了

**Comment by Qchail** [comment]
去 button 组件那看一下路径
![image](https://user-images.githubusercontent.com/66625812/147518582-e01e7a88-8d0c-4d70-a681-4560eb215153.png)
