### ISSUE TITLE
[tdesign-miniprogram]希望支持全局定制组件颜色

### ISSUE THREAD

**Issue by baidonghui** [Tencent/tdesign-miniprogram#490]
### 这个功能解决了什么问题
各应用有自己的主色调，希望支持组件库的全局颜色覆写，给出颜色覆写的示例文档

### 你建议的方案是什么？
可参考其他组件库实现方法，https://vant-contrib.gitee.io/vant-weapp/#/theme#ding-zhi-quan-ju-zhu-ti-yang-shi

**Comment by LeeJim** [comment]
这个正在计划当中
