### ISSUE TITLE
[input] maxcharacter设置不起作用

### ISSUE THREAD

**Issue by amoywood** [Tencent/tdesign-miniprogram#493]
### tdesign-miniprogram 版本

0.11.2

### 重现步骤

placeholder="最大输入10个字符，汉字算两个" maxcharacter="{{10}}"

### 期望结果

最大输入10个字符，汉字算两个

### 实际结果

没有任何限制

### 框架版本

微信开发者工具稳定版1.06.2204250

### 浏览器版本

微信APP IOS版8.0.22

### 系统版本

MacOS(12.4)

### Node版本

v18.2.0

### 补充说明

使用微信开发者工具自建的tdesign，input的maxcharacter是起作用的，把input文件夹覆盖替换0.11.2版本后也是可以起作用

**Comment by LeeJim** [comment]
我来看下
