### ISSUE TITLE
[popup] 使用弹出层的close-btn时关闭符号不显示

### ISSUE THREAD

**Issue by yaoyue47** [Tencent/tdesign-miniprogram#499]
### tdesign-miniprogram 版本

0.11.2

### 重现步骤

<t-popup visible="true" placement="top" close-btn="true">
</t-popup>
正常使用官网中关于Popup 弹出层的例子, 设置close-btn="true".

### 期望结果

Popup正常弹出，右上角显示“x”关闭符号

### 实际结果

Popup正常弹出，右上角显示“口”符号
报错信息：

[渲染层网络层错误] Failed to load font https://tdesign.gtimg.com/icon/0.0.3/fonts/t.woff
net::ERR_CACHE_MISS 
(env: Windows,mp,1.06.2205231; lib: 2.24.2)

### 补充说明

尝试这个组件时可以确保网络正常，点击这个woff文件链接可以正常下载

**Comment by LeeJim** [comment]
有问题后面再麻烦提新的 issue
