### ISSUE TITLE
[Navbar 导航栏]配合 Message  组件使用存在 bug

### ISSUE THREAD

**Issue by coderdp** [Tencent/tdesign-miniprogram#503]
### tdesign-miniprogram 版本

0.12.1

### 重现步骤

wxml:

`<t-navbar title="标题" t-class-title="nav-title" />
<t-message id="t-message" />`

js:

`Message.info({
      offset: ['20rpx', '32rpx'],
      duration: 5000,
      icon: 'error-circle',
      content: '这是一条带图标的消息通知 5s消失',
    });`

只用 message  组件是可以正常显示，加上 navbar  组件后无法显示 Message

### 期望结果

解决bug

**Comment by LeeJim** [comment]
收到，这边调整下 mesage 的层级
