### ISSUE TITLE
[Common] QQ小程序编译失败（旧版本可用）

### ISSUE THREAD

**Issue by fi6** [Tencent/tdesign-miniprogram#504]
### tdesign-miniprogram 版本

0.12.1

### 重现步骤

按照readme运行npm I和nom run dev后，使用qq小程序开发工具打开_example文件夹，会提示
```
编译QML文件出错，错误信息：./miniprogram_npm/tdesign-miniprogram/common/template/button.wxml:4:5: Bad attr "class" with message: Unexpected token, expected "{" (1:12) at 4:14.
```

tdesign-miniprogram-starter-retail模板中使用的0.7.1版本编译运行正常。

删除对应文件中的`class="{{class}}"`后运行正常，但样式错误。QQ小程序IDE的开发人员表示可能是template语法版本问题，但近期不一定能更新。如果不好改的话，如果有任何临时解决办法也行……

### 期望结果

tdesign可以在QQ小程序中正常使用

**Comment by LeeJim** [comment]
目前只支持微信小程序，qq 小程序还没正式发布

**Comment by LeeJim** [comment]
可以使用 tdesign-qq-miniprogram

**Comment by fi6** [comment]
2026年又来回复啦，还是相同的问题， tdesign-qq-miniprogram也不再维护了，我觉得还是值得修复一下，不然用了tdesign-miniprogram的包都会在qq里无法使用
