### ISSUE TITLE
[Textarea] 使用该组件后代码质量扫描中出现报错

### ISSUE THREAD

**Issue by yaoyue47** [Tencent/tdesign-miniprogram#508]
### tdesign-miniprogram 版本

0.11.2

### 重现步骤

在json页面引入Textarea组件后
"usingComponents": {
  "t-textarea": "tdesign-miniprogram/textarea/textarea"
}
代码质量审查时报错:

不应存在无使用的组件：
miniprogram_npm/tdesign-miniprogram/cell/cell.json

项目已经确认过，没有在其他地方引用和使用cell组件

**Comment by LeeJim** [comment]
移除 json 文件的 cell 引用即可

**Comment by yaoyue47** [comment]
> 移除 json 文件的 cell 引用即可

项目确认过，没有引用cell。而且把Textarea组件的引用删除后就不再报错了
