### ISSUE TITLE
[input] type设置为number或digit不起作用

### ISSUE THREAD

**Issue by kangyanbin** [Tencent/tdesign-miniprogram#521]
### tdesign-miniprogram 版本

0.12.1

### 重现步骤

placeholder="价格" model:value="{{price}}" type="digit" 
placeholder="价格" model:value="{{price}}" type="number"

### 期望结果

限制只能输入数字或正整数

### 实际结果

没有限制

### 框架版本

微信开发者工具

**Comment by webwyb** [comment]
我来跟进
