### ISSUE TITLE
【t-textarea】external-classes下的t-class-placeholder设置字体大小无效

### ISSUE THREAD

**Issue by xiaofeng1998025** [Tencent/tdesign-miniprogram#523]
### tdesign-miniprogram 版本

0.11.2

### 系统版本

微信版本库2.24.3

**Comment by anlyyao** [comment]
你试试在t-class-placeholder样式外在套一层，应该是权重不够，样式没生效～～ 目前版本已升到0.13.1，建议使用新版本哦

**Comment by xiaofeng1998025** [comment]
> 你试试在t-class-placeholder样式外在套一层，应该是权重不够，样式没生效～～ 目前版本已升到0.13.1，建议使用新版本哦

placeholder是这个描述字体大小不是输入文本的，版本我已经升级0.13.1了，权重我已经加最大了important都加了的

**Comment by LeeJim** [comment]
我测试了下 placeholder 好像不生效，可能外部样式类的方式不太行

**Comment by anlyyao** [comment]
@xiaofeng1998025  用名为 `t-textarea__placeholder` 的Class选择器，直接覆盖组件内部样式吧～～
