### ISSUE TITLE
button 按钮组件在 "style":"v2" 下 “点击后样式” 失效

### ISSUE THREAD

**Issue by Qchail** [Tencent/tdesign-miniprogram#53]
导入 button 按钮组件后发现点击没有出现 “点击后状态样式”（即按钮变暗），百思不得其解，准备放弃 tdesign 的按钮尝试使用 vant-weapp 的按钮，发现其文档 快速上手部分 的 步骤二 说明如下：

将 app.json 中的 "style": "v2" 去除，小程序的新版基础组件强行加上了许多样式，难以覆盖，不关闭将造成部分组件样式混乱。 

按照其说法去除 "style": "v2" 后发现 tdesign 按钮样式恢复，重新加上 "style": "v2" 按钮的 “点击后样式” 失效。
建议在文档中也补充相关说明。

**Comment by LeeJim** [comment]
可以的。感谢反馈
