### ISSUE TITLE
[tabs] 建议tabs组件加一个可以禁用左右滑动的选择

### ISSUE THREAD

**Issue by yaoyue47** [Tencent/tdesign-miniprogram#540]
### 这个功能解决了什么问题

当tabs组件和SwipeCell组件一起使用时滑动操作会相互干扰

### 你建议的方案是什么

建议tabs组件加一个可以禁用左右滑动的选择

**Comment by LeeJim** [comment]
需要增加属性禁止滑动切换是吧？
