### ISSUE TITLE
npm 包中存在 esm 和 comonjs 两种格式

### ISSUE THREAD

**Issue by sufuwang** [Tencent/tdesign-miniprogram#544]
### tdesign-miniprogram 版本

0.13.1

### 补充说明

我在小程序框架中以拷贝 tdesign-miniprogram 包中源码的形式使用，框架仅支持 commonjs ，我看到 npm 包中，有的文件是 es 规范，有的文件又是 commonjs 格式，能规范一下嘛？

**Comment by LeeJim** [comment]
收到，我来跟进下。

**Comment by LeeJim** [comment]
这边建议使用 npm 的方式

**Comment by sufuwang** [comment]
> 这边建议使用 npm 的方式

因为 uniapp 不能以 npm 方式使用。请问打包格式后面会统一嘛
