### ISSUE TITLE
[picker] 能否增加滚动反馈事件

### ISSUE THREAD

**Issue by amoywood** [Tencent/tdesign-miniprogram#551]
### 这个功能解决了什么问题

想要做成跟小程序官方的picker一样滚动过程有震动反馈

### 你建议的方案是什么

滚动过程改变几次value就触发几次的事件，让用户自行添加wx.vibrateShort，又或者写死直接调用，现在只有触发最后一次value的事件无法实现该功能

**Comment by amoywood** [comment]
@LeeJim 试了bindpick事件是只触发最后一次（比如手指滑动一下从1快速滚到6，pick事件会到6的时候才触发，滚动过程2\3\4\5都不会触发事件），版本0.13.2，滚动停止触发bindpick，点击确认触发bindchange，点击取消触发bindcancel，文档中有个bindconfirm不知道用在什么地方

官方自带的pick，在iphone下滚动过程会有哒哒哒的反馈，快速滚动过程也一样有哒哒哒的反馈

**Comment by LeeJim** [comment]
明白你的诉求了，我来看看
