### ISSUE TITLE
[ChecTag] 缺少选中类标签

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-miniprogram#554]
### 这个功能解决了什么问题

<img width="319" alt="image" src="https://user-images.githubusercontent.com/11605702/175957182-140be104-27de-4c1d-b162-215310aca5b1.png">

### 你建议的方案是什么

在 tag 的基础上，补充实现一下 CheckTag。Web 侧已实现。

**Comment by LeeJim** [comment]
已实现了的

<img width="574" alt="image" src="https://user-images.githubusercontent.com/7017290/176816015-0a2d813b-8cf7-43c0-b830-642a74be0332.png">
