### ISSUE TITLE
[Tabs] 需要激活状态改变颜色

### ISSUE THREAD

**Issue by CRECOHE** [Tencent/tdesign-miniprogram#570]
### 这个功能解决了什么问题

选项卡底部的线条，希望能够改变颜色或者提供slot自定义，现在是默认setTrack的颜色到view的内嵌style，优先级比较高，通过强制也没办法改变

### 你建议的方案是什么

希望单独一个接口，可以一键设置激活颜色以及单独自定义激活下标线条的颜色甚至可以自定义下标线条单独设置slot

**Comment by anlyyao** [comment]
@CRECOHE  外部样式改变字体和下标线条颜色～

**Comment by LeeJim** [comment]
可以用过外部样式类：`t-class-track`;
或者直接覆盖 `.t-tabs__track` 的样式

由于样式的优先级，记得加上 `!important`
