### ISSUE TITLE
✍🏼  示例代码改造

### ISSUE THREAD

**Issue by LeeJim** [Tencent/tdesign-miniprogram#591]
由于很多用户反馈 “示例代码 和DEMO 不一致”，因此最近对官网进行了改造升级。
之后，示例代码中会展示所有的代码，包括 WXML/JS/CSS/JSON。
同步也要改造对应的 DEMO，可以参考 Collapse 进行改造。

> 感兴趣的朋友可以直接评论认领

## ⚠️ 注意

修改完代码，需要做一下测试：
- 在微信开发者工具测试：
  - 能否正常展示
  - 交互是否正常
- 通过 `npm run site:dev` 测试官网的示例代码是否符合预期

> 官网右侧的示例是在线版的，不是本地代码

## 进度
> 已完成 = 45；CR = 4；进行中 = 1； 

| 所属类别 | 组件名 | 状态 | 负责人 | 关联PR |
|----- | ----- | ----- | ----- | -----|
| 基础 | Button 按钮| 🔵 已完成 | @wangyuan0108 | #607  |
| 基础 | Divider 分割线 | 🔵 已完成 | @wangyuan0108 | #608 |
| 基础 | Fab 悬浮按钮 | 🔵 已完成 | @wangyuan0108 | #602  |
| 基础 | Icon 图标 |  🔵 已完成 | @anlyyao  | #642 |
| 导航 | Drawer 抽屉 |  🔵 已完成 | @wangyuan0108  | #613  |
| 导航 | Indexes 索引 | 🔵 已完成 | @anlyyao  | #649 |
| 导航 | Navbar 导航栏 | 🔵 已完成 | @anlyyao | #636  |
| 导航 | Steps 步骤条 |  🔵 已完成 | @anlyyao |  #609  |
| 导航 | TabBar 标签栏 |  🔵 已完成 | @LeeJim | #601 |
| 导航 | Tabs 选项卡 | 🔵 已完成 |  @wangyuan0108 | #616  |
| 输入 | Checkbox 复选框 | 🔵 已完成 | @wangyuan0108 | #668 |
| 输入 | DateTimePicker 时间选择器 | 🔵 已完成 | @anlyyao  | #652
| 输入 | Input 输入框 | 🔵 已完成 | @anlyyao  | #651  | 
| 输入 | Picker 选择器 |  🔵 已完成 | @anlyyao | #606 |
| 输入 | Radio 单选框 | 🔵 已完成 | @wangyuan0108|  #667 |
| 输入 | Rate 评分 | 🔵 已完成| @anlyyao  | #653 | 
| 输入 | Search 搜索框 | 🔵 已完成 | @anlyyao | #654  |
| 输入 | Slider 滑动选择器 | 🔵 已完成  | @anlyyao  | #671
| 输入 | Stepper 步进器 |🔵 已完成 | @anlyyao  | #670 
| 输入 | Switch 开关 |  🔵 已完成 | @wangyuan0108 | #615 |
| 输入 | Textarea 多行文本框 |  🔵 已完成 | @anlyyao  | #625 |
| 输入 | Upload 上传 |  🔵 已完成 | @anlyyao | #595  |
| 数据展示 | Avatar 头像 |  🔵 已完成  | @anlyyao  | #665
| 数据展示 | Badge 徽标 | 🔵 已完成 | @wangyuan0108 | #717 
| 数据展示 | Cell 单元格 | 🔵 已完成 | @CodingOnStar | #675
| 数据展示 | Collapse 折叠面板 |  🔵 已完成 | @LeeJim  | #462
| 数据展示 | CountDown 倒计时 | 🔵 已完成 | @AntzyMo | #714 
| 数据展示 | DropdownMenu 下拉菜单 | 🔵 已完成 | @LeeJim  | #721
| 数据展示 | Empty 空内容 |🔵 已完成 | @AntzyMo | #709 
| 数据展示 | Result 结果 | 🔵 已完成 | @anlyyao | #589 |
| 数据展示 | Footer 页脚 |  🔵 已完成 | @wangyuan0108 | #593 |
| 数据展示 | Grid 宫格 | 🔵 已完成 | @anlyyao | #635  |
| 数据展示 | Image 图片 |  🔵 已完成 | @anlyyao | #637  |
| 数据展示 | ImageViewer 图片预览 | 🔵 已完成 | @anlyyao  | #712 
| 数据展示 | Skeleton 骨架屏 | 🔵 已完成 | @anlyyao  | #617 |
| 数据展示 | Sticky 吸顶容器 | 🔵 已完成 | @anlyyao | #720 
| 数据展示 | Swiper 轮播图 | 🔵 已完成  | @anlyyao  | #669 
| 数据展示 | Tag 标签 | 🔵 已完成 | @anlyyao  | #622 |
| 消息提醒 | ActionSheet 动作面板 | 🔵 已完成 | @LeeJim  | #716
| 消息提醒 | BackTop 返回顶部 | 🔵 已完成 | @anlyyao  | #710 
| 消息提醒 | Dialog 对话框 | 🔵 已完成 | @AntzyMo | #704 
| 消息提醒 | Loading 加载 | 🔵 已完成  | @anlyyao | #691 |
| 消息提醒 | Message 消息通知 | 🔵 已完成 | @AntzyMo | #695 
| 消息提醒 | NoticeBar 消息通知 |  🔵 已完成 | @anlyyao | #610  |
| 消息提醒 | Overlay 遮罩层 |  🔵 已完成 | @LeeJim  | #655 
| 消息提醒 | Popup 弹出层 |  🔵 已完成 | @LeeJim  | #599 |
| 消息提醒 | Progress 进度条 | 🔵 已完成  | @anlyyao | #690 
| 消息提醒 | PullDownRefresh 下拉刷新 | 🔵 已完成 | @anlyyao  | #699 
| 消息提醒 | SwipeCell 滑动操作 | 🔵 已完成 | @anlyyao | #698
| 消息提醒 | Toast 轻提示 | 🔵 已完成 | @CodingOnStar | #676

**Comment by wangyuan0108** [comment]
footer

**Comment by anlyyao** [comment]
认领：upload  navbar  picker

**Comment by wangyuan0108** [comment]
Fab

**Comment by wangyuan0108** [comment]
Button

**Comment by wangyuan0108** [comment]
Divider

**Comment by wangyuan0108** [comment]
Drawer

**Comment by anlyyao** [comment]
认领 grid

**Comment by anlyyao** [comment]
@wangyuan0108  hello 我在处理input组件issue时 顺便完成了demo改造问题  辛苦关注一下 不要重复～～

**Comment by wangyuan0108** [comment]
> @wangyuan0108 hello 我在处理input组件issue时 顺便完成了demo改造问题 辛苦关注一下 不要重复～～

好的，现在demo改造出现乱码，你们有这个问题吗？
![image](https://user-images.githubusercontent.com/22407253/180904217-cbd09b1b-a0e6-4522-9092-b583a1a87cc4.png)

**Comment by anlyyao** [comment]
> > @wangyuan0108 hello 我在处理input组件issue时 顺便完成了demo改造问题 辛苦关注一下 不要重复～～
> 
> 好的，现在demo改造出现乱码，你们有这个问题吗？ ![image](https://user-images.githubusercontent.com/22407253/180904217-cbd09b1b-a0e6-4522-9092-b583a1a87cc4.png)

我这边是正常的～～ 你同步一下代码试试

**Comment by CodingOnStar** [comment]
认领cell

**Comment by LeeJim** [comment]
> > @wangyuan0108 hello 我在处理input组件issue时 顺便完成了demo改造问题 辛苦关注一下 不要重复～～
> 
> 好的，现在demo改造出现乱码，你们有这个问题吗？ ![image](https://user-images.githubusercontent.com/22407253/180904217-cbd09b1b-a0e6-4522-9092-b583a1a87cc4.png)

npm install 重新装下

**Comment by AntzyMo** [comment]
认领 Message

**Comment by anlyyao** [comment]
认领 PullDownRefresh SwipeCell

**Comment by AntzyMo** [comment]
认领 CountDown  Empty

**Comment by LeeJim** [comment]
🎉 感谢 @AntzyMo @wangyuan0108 @CodingOnStar @anlyyao 的贡献。

示例代码改造已全部完成～

**Comment by LeeJim** [comment]
Hello  @AntzyMo @wangyuan0108 @CodingOnStar，非常感谢您参与 TDesign 协同共建。TDesign 团队为您准备了一份定制周边礼品以表谢意，请填写贡献者联系方式收集问卷（问卷地址：https://wj.qq.com/s2/10618394/1671/），TDesign 收到此问卷后会尽快安排周边礼品发放，请稍等待。

**Comment by china-live** [comment]
NoticeBar  示例代码拷到页面中没有样式
