### ISSUE TITLE
[t-navbar] 使用t-navbar组件，会占用页面高度，并且遮挡页面中的模块

### ISSUE THREAD

**Issue by yeyongxi** [Tencent/tdesign-miniprogram#597]
### tdesign-miniprogram 版本

0.14.0

### 期望结果

用户使用t-navbar后，不遮挡页面

**Comment by LeeJim** [comment]
我来处理下

**Comment by LeeJim** [comment]
我在当前最新版本 0.15.1 试了下。
默认情况下，navbar 会有一个展位元素，所以并没有遮挡页面的情况发生。

**Comment by LeeJim** [comment]
已沟通，确实没问题，有问题麻烦再提新 issue
