### ISSUE TITLE
[Picker] 获取的label与value值不对应

### ISSUE THREAD

**Issue by shine-lzx** [Tencent/tdesign-miniprogram#611]
### tdesign-miniprogram 版本

"tdesign-miniprogram": "^0.15.1"

### 重现步骤

![127D474F-CD2D-4b22-BA3E-60402E7B4436](https://user-images.githubusercontent.com/45986102/178926307-9aa38034-19d6-40c6-be4f-66b71650d115.png)
![90CF8A0D-E396-47aa-8D26-95EAFB66CDDF](https://user-images.githubusercontent.com/45986102/178926332-689a3196-1a74-4c3b-aaa8-a6f106363ae5.png)

### 期望结果

picker选中项的value与label保持一致

### 框架版本

"tdesign-miniprogram": "^0.15.1"

**Comment by LeeJim** [comment]
我来处理下
