### ISSUE TITLE
TreeShaking 还是很有必要的！

### ISSUE THREAD

**Issue by jkiss** [Tencent/tdesign-miniprogram#62]
我只引用了一个Button组件，但把所有代码都打包了，不知是否有tree-shaking设置？

![image](https://user-images.githubusercontent.com/3231326/147554733-f72d0f6d-9491-4973-9a5a-2226e3df4cab.png)

**Comment by esky** [comment]
tree-shaking得由构建来处理，你应该需要的是gulp插件，https://github.com/cong-min/gulp-mp-npm

**Comment by jin0209** [comment]
后续会考虑将每个组件分别打包，支持单个独立引用～

**Comment by jkiss** [comment]
> tree-shaking得由构建来处理，你应该需要的是gulp插件，https://github.com/cong-min/gulp-mp-npm

@esky 真是奇怪，官方说小程序 npm 包拷贝所有文件到 miniprogram_npm 中，而其他npm包就会走一遍依赖分析，为啥不全走一遍依赖分析。。。

**Comment by jkiss** [comment]
> 后续会考虑将每个组件分别打包，支持单个独立引用～

@jin0209 太棒了，类似于 @tdesign-miniprogram/button 这样，是能接受的

**Comment by LeeJim** [comment]
> > tree-shaking得由构建来处理，你应该需要的是gulp插件，https://github.com/cong-min/gulp-mp-npm
> 
> @esky 真是奇怪，官方说小程序 npm 包拷贝所有文件到 miniprogram_npm 中，而其他npm包就会走一遍依赖分析，为啥不全走一遍依赖分析。。。

组件库作为其中一个 npm 包，怎么做到去分析你的依赖？

**Comment by jkiss** [comment]
> > > tree-shaking得由构建来处理，你应该需要的是gulp插件，https://github.com/cong-min/gulp-mp-npm
> > 
> > 
> > @esky 真是奇怪，官方说小程序 npm 包拷贝所有文件到 miniprogram_npm 中，而其他npm包就会走一遍依赖分析，为啥不全走一遍依赖分析。。。
> 
> 组件库作为其中一个 npm 包，怎么做到去分析你的依赖？ 后续会开发或者推荐一些小程序的构建插件，用于 tree-shaking

不是说让组件库去分析，而是在吐槽开发者工具的构建功能，本来每个组件都有usecomponents的声明，非要打包全部 😢

**Comment by Rabbitzzc** [comment]
本身应该就是支持单独打包，不然包大小会有问题。。。

**Comment by Rabbitzzc** [comment]
而且构建和打包本身也是小程序的一部分吧

**Comment by jkiss** [comment]
> 而且构建和打包本身也是小程序的一部分吧

写了小程序之后真是不想再写小程序，每个厂子都搞一套自己的api标准，不得不说格局跟国外差的太远

**Comment by Rabbitzzc** [comment]
> 

这倒是没有吧，api 标准还是比较统一的。如果是跨端，可以试试 Taro 等呀，然后搬家工具也可以用。

**Comment by jkiss** [comment]
> 这倒是没有吧，api 标准还是比较统一的。如果是跨端，可以试试 Taro 等呀，然后搬家工具也可以用。

第一次想用原生写，第二次试试taro。之前调研过，如果平台差异，需要自己手动去适配，就感觉很不智能

**Comment by vhxubo** [comment]
微信开发者工具 1.05.2112301 RC 增加了 **小程序无依赖文件过滤能力**

[微信开发者工具 1.05.2112301 RC 更新说明 | 微信开放社区](https://developers.weixin.qq.com/community/minihome/doc/0006266d77ce78786b4d3fcd15b801)

> 工具依赖分析小程序项目中无依赖的文件，在本地开发过程、预览上传时对无依赖文件进行过滤，会自动过滤无依赖的文件，从而减少小程序包体积；如果出现误过滤的情况，可以在 project.config.json 的 setting 字段中添加 ignoreDevUnusedFiles 为 false，也可以在 packOptions 的 include 字段中手动将被忽略的文件引入，同时欢迎发帖反馈误报的情况并提交代码片段帮助我们完善此功能。相关配置开关可参考下面的文档 https://developers.weixin.qq.com/miniprogram/dev/devtools/projectconfig.html

![代码依赖分析](https://user-images.githubusercontent.com/17352372/149604329-f9b83bc1-dd4b-406b-9149-7cdd2fb16395.png)
![本地设置](https://user-images.githubusercontent.com/17352372/149604335-efee9cea-12a4-4383-8e86-243f7984ff46.png)

偶尔依赖分析会出错, 清除编译缓存, 重新编译即可

**Comment by Rabbitzzc** [comment]
厉害呀，原理有分享么

**Comment by LeeJim** [comment]
结论就是：将开发者工具升级到 1.05.2112301
然后打开 ”上传时过滤无依赖文件“ 即可

**Comment by wanpan11** [comment]
🐂顶呱呱
