### ISSUE TITLE
steps 文档错误

### ISSUE THREAD

**Issue by hongfs** [Tencent/tdesign-miniprogram#63]
**Describe Framework**
- [x] tdesign-miniprogram

**Describe Environment**

Add browser version here

**Describe the bug**
引入的 `usingComponents` 中缺少了 `t-` 前缀。

还有 stepper 组件

**Comment by hongfs** [comment]
还有 steps 的 step 注册地址应该是 `tdesign-miniprogram/steps/step-item` ，而不是 `tdesign-miniprogram/step-item/step-item`

**Comment by LeeJim** [comment]
确实有问题。感谢反馈。

**Comment by LeeJim** [comment]
已修复，对应 commit: 8a1fc31
