### ISSUE TITLE
[PullDownRefresh] 页面滚动事件传递到组件

### ISSUE THREAD

**Issue by ws2003gq** [Tencent/tdesign-miniprogram#630]
### tdesign-miniprogram 版本

0.15.1

### 重现步骤

               this.pullDownRefresh0 && this.pullDownRefresh0.onPageScroll(e);抛错

### 补充说明
自己试了一下如何解决。
增加  bindscrolltolower="onScrollToBottom"

            onScrollToBottom() {
              this.triggerEvent('scrolltolower');
            },
这样就可以在page里面去监听 scroll-view的触底事件。完成下拉分页，求采纳或者有更好的办法
_No response_

**Comment by LeeJim** [comment]
既然已经阅读了源码，也给出了方案，可以直接给我们贡献 PR 的哦。我们这边再进行 Code Review
