### ISSUE TITLE
t-tabs 左右滑动时不会触发change事件

### ISSUE THREAD

**Issue by BeanCookie** [Tencent/tdesign-miniprogram#64]
**Describe Framework**

tdesign-miniprogram

**Describe Environment**

Add browser version here

**Describe the bug**
t-tabs 左右滑动时不会触发change事件

**Comment by LeeJim** [comment]
确实有问题，我来看看

**Comment by BeanCookie** [comment]
> 确实有问题，我来看看

我已经提交MR了
