### ISSUE TITLE
[input] 建议支持修改背景颜色

### ISSUE THREAD

**Issue by jell0w** [Tencent/tdesign-miniprogram#644]
### 这个功能解决了什么问题

开发者适配darkmode

### 你建议的方案是什么

external-classes属性里可以加个能控制背景颜色的属性嘛……（或者说本来就有我没注意到？）

**Comment by LeeJim** [comment]
@anlyyao 参考 Tabbar 使用 CSS Variable 支持并更新文档

**Comment by anlyyao** [comment]
@jell0w  目前可以借助external-classes属性里面的t-class、 t-class-input修改背景色，placeholder的内容需要使用t-input__control去覆盖下组件内部样式～ ～ 可以关注一下这个[PR](https://github.com/Tencent/tdesign-miniprogram/pull/651)
