### ISSUE TITLE
[avatar-group] class写法有问题

### ISSUE THREAD

**Issue by liziwork** [Tencent/tdesign-miniprogram#661]
### tdesign-miniprogram 版本

^0.17.0

### 重现步骤

 <view class="{{classPrefix}}__collapse--slot {{collapseAvatar ? '{{prefix}}-is-hidden' : ''}}">
    <slot name="collapseAvatar" />
  </view>
prefix无法被识别

### 期望结果

t-avatar-group__collapse--slot prefix t-is-hidden

### 实际结果

t-avatar-group__collapse--slot prefix -is-hidden

### 框架版本

小程序

**Comment by liziwork** [comment]
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/19724731/180831355-0f417890-4887-41f7-89ad-761e20419e1f.png">

**Comment by anlyyao** [comment]
收到。 感谢反馈 🫡～～ 我来跟进一下
