### ISSUE TITLE
t-popup问题

### ISSUE THREAD

**Issue by zyajm** [Tencent/tdesign-miniprogram#662]
还有个问题，如果不是自定义tabbar，用t-popup底部模式有问题，不是从底部，而是从tabbar之上

**Comment by LeeJim** [comment]
我看了下，这个问题是没办法处理的。
使用了原生 tabbar 之后，tabbar上面的部分才是可渲染的部分，因此popup只能从 tabbar 上面出现。

**Comment by zyajm** [comment]
weui是能实现的，怎么理解您这做不到？
