### ISSUE TITLE
希望添加支持字节小程序的需求

### ISSUE THREAD

**Issue by liziwork** [Tencent/tdesign-miniprogram#664]
### 这个功能解决了什么问题

通过简单的改动可以适配字节小程序

### 你建议的方案是什么

https://microapp.bytedance.com/docs/zh-CN/mini-app/develop/framework/npm/#%E5%BC%80%E5%8F%91-npm
修改package.json，添加exports和miniprogramType字段，适配字节小程序的npm构建。

**Comment by LeeJim** [comment]
目前官方没有这个规划哦。
现在 TDesign 已经开源的了，其实很欢迎你直接去开发一个字节小程序的版本，后续可以收录进 Awesome TDesign 中。

**Comment by liziwork** [comment]
好的，目前只能通过相对路径引入了。
