### ISSUE TITLE
Message提示组件无法使用

### ISSUE THREAD

**Issue by dsbruce** [Tencent/tdesign-miniprogram#67]
**Describe Framework**

tdesign-miniprogram

**Describe Environment**

Add browser version here

**Describe the bug**
在使用Page.js 引入
import Message from 'tdesign-miniprogram/message/index';

并在触发事件中使用该API， 报错，无法显示； 报错信息如下：
VM5634 WAService.js:2 Unhandled promise rejection (env: Windows,mp,1.05.2111051; lib: 2.19.4)

**Comment by LeeJim** [comment]
我来看看

**Comment by LeeJim** [comment]
应该是使用的错误，还需要引用组件才行：

```html
<t-message id="t-message" />
```

另外，报错的信息需要完善一下。
