### ISSUE TITLE
用ts使用组件库使用api调用组件 没有ts类型声明

### ISSUE THREAD

**Issue by AntzyMo** [Tencent/tdesign-miniprogram#679]
### tdesign-miniprogram 版本

0.17.0-beta.1

### 重现步骤

我在小程序用到了ts+scss开发，也在用这个组件库，当我在用的`Toast `组件，用 API `Toast` 方法调用轻提示，当在vscode引用了这段代码`import Toast from 'tdesign-miniprogram/toast/index' `提示说没有类型声明,然后看了看源码看到`build`s是去掉dts的有点不理解，是生成出来不能用吗

**Comment by iClouds** [comment]
问题解决了吗 我也用的ts+sass 也是找不到模块“tdesign-miniprogram/toast/index”或其相应的类型声明

**Comment by AntzyMo** [comment]
解决了 现在最新版本已经支持了

**Comment by AntzyMo** [comment]
> 问题解决了吗 我也用的ts+sass 也是找不到模块“tdesign-miniprogram/toast/index”或其相应的类型声明

解决了 现在最新版本已经支持了

**Comment by matianhe3** [comment]
> > 问题解决了吗 我也用的ts+sass 也是找不到模块“tdesign-miniprogram/toast/index”或其相应的类型声明
> 
> 解决了 现在最新版本已经支持了

1.4.1还是有这个问题, 新版本解决的是哪个版本啊?

**Comment by zty42** [comment]
> > > 问题解决了吗 我也用的ts+sass 也是找不到模块“tdesign-miniprogram/toast/index”或其相应的类型声明
> > 
> > 
> > 解决了 现在最新版本已经支持了
> 
> 1.4.1还是有这个问题, 新版本解决的是哪个版本啊?

https://tdesign.tencent.com/miniprogram/getting-started#%E4%BF%AE%E6%94%B9-tsconfig-json
