### ISSUE TITLE
[tabs] 希望支持选中的下标改色

### ISSUE THREAD

**Issue by CRECOHE** [Tencent/tdesign-miniprogram#681]
### 这个功能解决了什么问题

![image](https://user-images.githubusercontent.com/57332732/181702966-348b5b0e-4993-4ad2-b68e-c672c7206ddc.png)
现在每次改色，都要手动去修改，极其不方便，希望能支持两种模式，纯改色，和slot的

### 你建议的方案是什么

把设置单独做成组件属性

**Comment by LeeJim** [comment]
我来支持下
