### ISSUE TITLE
Avatar Props 文档中 external-classes 显示不完全

### ISSUE THREAD

**Issue by vhxubo** [Tencent/tdesign-miniprogram#69]
## 参数不完全文档

| 名称                | 类型          | 默认值 | 说明     | 
| ------------------- | ------------- | ------ | -----|
| external-classes    | Array         | -      | 组件类名，用于设置组件外层元素类名。`['t-class']`                                                                                                                                               | N    |

[README.md](https://github.com/Tencent/tdesign-miniprogram/blob/efbb04e4b99f333f1f247cc61eee9c2173833078/src/avatar/README.md?plain=1#L117)

## 源码参数完全部分

```typescript
externalClasses = ['t-class', 't-class-image', 't-class-icon', 't-class-alt'];
```

[avatar.ts](https://github.com/Tencent/tdesign-miniprogram/blob/efbb04e4b99f333f1f247cc61eee9c2173833078/src/avatar/avatar.ts#L10)

望更新, 避免造成困扰

**Comment by chaishi** [comment]
收到，我们尽快更新 @LeeJim
