### ISSUE TITLE
🚥  小程序测试覆盖率提升

### ISSUE THREAD

**Issue by LeeJim** [Tencent/tdesign-miniprogram#701]
目前在推进小程序的测试覆盖，需要覆盖基本的场景。具体要求：
- **行覆盖率达80%+**
- 基本展示相关的组件，只需要 snapshots 测试
- 有交互的组件，需要覆盖所有场景，**要求函数覆盖率 80+%**

#### Tips
- 避免踩坑，可以参考 Checkbox 的测试用例
- 使用 vscode 的话，可以安装 Jest 插件

> 认领方式：直接评论 “我来负责xxx组件” 即可。

认领任务之前，强烈推荐先查看下 [《如何编写单元测试（快速指南）》](https://github.com/Tencent/tdesign-miniprogram/wiki/%E5%A6%82%E4%BD%95%E5%86%99%E5%8D%95%E5%85%83%E6%B5%8B%E8%AF%95%EF%BC%88%E5%BF%AB%E9%80%9F%E6%8C%87%E5%8D%97%EF%BC%89)

## 激励

参与共建的开发者，将可以获得 [TDesign 周边](https://github.com/Tencent/tdesign/wiki/TDesign-%E5%91%A8%E8%BE%B9)（贴纸、鼠标垫、工卡套等）；

成为核心贡献者，将会拥有 TDesign 专属头像。

### 基础
- [x] Button @LeeJim #726 
- [x] Fab @LeeJim #740 
- [x] Icon @LeeJim #741 

### 布局
- [x] Cell @LeeJim #742 
- [x] Divider @Perisiguiendo #771 
- [x] Grid @LeeJim #752 

### 导航
- [x] DropdownMenu @LeeJim #848
- [x] Indexes @CodingOnStar #850
- [x] NavBar @LeeJim #829 
- [x] Steps @isanxia #792 
- [x] Sticky @Perisiguiendo #852
- [x] TabBar @LeeJim #846
- [x] Tabs @LeeJim #831

### 输入

- [x] Checkbox @LeeJim #724 
- [x] DateTimePicker @LeeJim #855
- [x] Input @anlyyao #775 
- [x] Picker @LeeJim #854
- [x] Radio @LeeJim #729 
- [x] Rate @isanxia #767 
- [x] Search @Perisiguiendo #790 
- [x] Slider @LeeJim #853
- [x] Stepper @anlyyao #773
- [x] Switch @Perisiguiendo #791 
- [x] Textarea @anlyyao #774 
- [x] Upload @anlyyao #847 

### 数据展示
- [x] Avatar @Perisiguiendo #812
- [x] Badge @Perisiguiendo #776
- [x] Collapse @LeeJim #825
- [x] CountDown @LeeJim #824
- [x] Empty @AntzyMo #801
- [x] Footer @zhangpaopao0609 #794 
- [x] Image @LeeJim #820 
- [x] ImageViewer @LeeJim #826
- [x] Result @CodingOnStar #769 
- [x] Skeleton @Perisiguiendo #803 
- [x] Swiper @anlyyao #864
- [x] Tag @anlyyao #743

### 消息提醒
- [x] ActionSheet @anlyyao #832 
- [x] Backtop @anlyyao #728 
- [x] Dialog @LeeJim #816
- [x] Drawer @anlyyao #732
- [x] Loading @anlyyao #733 
- [x] Message @anlyyao #859 
- [x] NoticeBar @anlyyao #821
- [x] Overlay @LeeJim #818
- [x] Popup @LeeJim #746 
- [x] Progress @anlyyao #731
- [x] PullDownRefresh @anlyyao #835 
- [x] SwipeCell @webwyb #861
- [x] Toast @LeeJim #797

### 7.30 - 8.5

- 跑通单元测试
- 流水线增加单元测试，通过才能合并
- 增加脚本，自动生成所有 demo 的 snapshots 测试
- 增加脚本，自动生成每个组件的测试覆盖率徽章
- 完成 `Checkbox` & `Button`，进度 4%

### 8.6 - 8.12

- 新增文档 [《如何编写单元测试（快速指南）》](https://github.com/Tencent/tdesign-miniprogram/wiki/%E5%A6%82%E4%BD%95%E5%86%99%E5%8D%95%E5%85%83%E6%B5%8B%E8%AF%95%EF%BC%88%E5%BF%AB%E9%80%9F%E6%8C%87%E5%8D%97%EF%BC%89)
- 累计完成 13 个组件；进度 `26%`
- 目前测试覆盖率 `22%`
- 新增 3 个贡献者

### 8.13 - 8.19
- 累计完成 20 个组件；进度 `40%`
- 目前测试覆盖率 `28%`
- 新增 1 个贡献者

### 8.20 - 8.26
- 累计完成 25 个组件；进度 `51%`
- 目前测试覆盖率 `31%`

### 8.27 - 9.2
- 累计完成 35 个组件；进度 `70%`
- 目前测试覆盖率 `55%`

### 9.3 - 9.9
- 累计完成 44 个组件；进度 `88%`
- 目前测试覆盖率 `76%`

**Comment by Perisiguiendo** [comment]
认领 divider Search Switch Badge

**Comment by CodingOnStar** [comment]
认领Result

**Comment by AntzyMo** [comment]
认领Message

**Comment by isanxia** [comment]
认领Rate

**Comment by isanxia** [comment]
认领Steps

**Comment by zhangpaopao0609** [comment]
认领 Footer

**Comment by AntzyMo** [comment]
![微信图片_20220824115047](https://user-images.githubusercontent.com/45410431/186324856-5e6e3bdf-3a63-4f18-bf17-6b9cc87f5a27.jpg)  
`npx jest empty`报这个错导致运行不下去

**Comment by anlyyao** [comment]
> ![微信图片_20220824115047](https://user-images.githubusercontent.com/45410431/186324856-5e6e3bdf-3a63-4f18-bf17-6b9cc87f5a27.jpg) `npx jest empty`报这个错导致运行不下去
重装下依赖试试、

**Comment by anlyyao** [comment]
@AntzyMo 重装下依赖试试、

**Comment by AntzyMo** [comment]
> @AntzyMo重装下依赖尝试、
试过了 node的版本也换过

**Comment by LeeJim** [comment]
> ![微信图片_20220824115047](https://user-images.githubusercontent.com/45410431/186324856-5e6e3bdf-3a63-4f18-bf17-6b9cc87f5a27.jpg) `npx jest empty`报这个错导致运行不下去

只有这个组件还是所有？

**Comment by AntzyMo** [comment]
> > ![微信图片_20220824115047](https://user-images.githubusercontent.com/45410431/186324856-5e6e3bdf-3a63-4f18-bf17-6b9cc87f5a27.jpg) `npx jest empty`报这个错导致运行不下去
> 
> 只有这个组件还是所有？

所有 运行写好的也报这个问题了

**Comment by Perisiguiendo** [comment]
认领Skeleton、Avatar、Sticky

**Comment by webwyb** [comment]
认领SwipeCell

**Comment by anlyyao** [comment]
认领Upload

**Comment by LeeJim** [comment]
> 认领Message Empty

Empty 我来跟进好了

**Comment by AntzyMo** [comment]
> > 认领Message Empty
> 
> Empty 我来跟进好了

Empty我记得已经合并了的

**Comment by LeeJim** [comment]
> > > 认领Message Empty
> > 
> > 
> > Empty 我来跟进好了
> 
> Empty我记得已经合并了的

哦哦，好的

**Comment by CodingOnStar** [comment]
认领indexes

**Comment by anlyyao** [comment]
认领 swiper

**Comment by LeeJim** [comment]
感谢大家的贡献，目前 测试覆盖率工作 已圆满完成

测试覆盖率已达 **93%+**  🎉🎉
