### ISSUE TITLE
page泛型写了DataOption不应该强制传CustomOption

### ISSUE THREAD

**Issue by AntzyMo** [Tencent/tdesign-miniprogram#705]
### tdesign-miniprogram 版本

0.17.0-beta.1

### 期望结果

我的用途是想限制`data`的类型，方法那些不强制传`CustomOption`泛型

### 实际结果

我限制`data`的类型，方法不想限制提示报错要传两个类型参数

**Comment by LeeJim** [comment]
没看懂是什么问题
