### ISSUE TITLE
[DateTimePicker] 引入即报错

### ISSUE THREAD

**Issue by EddyAnd** [Tencent/tdesign-miniprogram#708]
### tdesign-miniprogram 版本

0.18.0

### 重现步骤

引入"t-date-time-picker": "tdesign-miniprogram/date-time-picker/date-time-picker"就能复现

### 期望结果

正常使用

### 实际结果

报错：“ 'miniprogram_npm/tdesign-miniprogram/common/utils.js' is not defined, require args is '../common/utils'”

### Node版本

8.11.0

**Comment by LeeJim** [comment]
感谢反馈，我来看看

**Comment by LeeJim** [comment]
我这边没法复现，是正常使用的。
是不是开发者工具的问题，重启试试可能就好了

**Comment by Phecda** [comment]
勾选 `将 JS 编译成 ES5` 试试

**Comment by fllyyou** [comment]
应该在开发者工具 把 JS 编译成 ES5 这个选项去掉勾选后看看,就会报错了
