### ISSUE TITLE
[Toast轻提示] prevent-scroll-through设置无效

### ISSUE THREAD

**Issue by synctimes163** [Tencent/tdesign-miniprogram#727]
### tdesign-miniprogram 版本

0.9.0

### 重现步骤

![48cb5f573f344f5657097914a8d2520](https://user-images.githubusercontent.com/78259973/183014361-7cb7c347-18ae-435f-9dd8-0db2ed231be4.jpg)

<t-toast id="t-toast"  prevent-scroll-through="{{true}}"/>

我按官方文档使用，发现 prevent-scroll-through 设置无效。

### 期望结果

prevent-scroll-through 设置有效，并期望Toast 轻提示 **示例**给出对应 代码模块

**Comment by LeeJim** [comment]
升级最新版即可

**Comment by synctimes163** [comment]
目前已经是最新版本 0.18.0 了，就是在0.18.0 版本上发现的，我看到官方文档最新版本就是0.18.0 .让我升级最新版是哪个版本？怎么执行升级最新版本命令



在 2022-08-06 00:12:06，"leejimqiu" ***@***.***> 写道：

升级最新版即可

**Comment by synctimes163** [comment]
![image](https://user-images.githubusercontent.com/78259973/183355998-49e7f18c-f0ca-4d2d-9a38-09ae7a8f914e.png)
已经是最新版了啊，仍然复现，麻烦看看呢

**Comment by LeeJim** [comment]
npm 安装之后，还需要用开发者工具 “构建”

**Comment by synctimes163** [comment]
> npm 安装之后，还需要用开发者工具 “构建”
不构建 怎么运行示例给你看？ npm 安装了，不成功，怎么给你演示图？你试下啊

**Comment by LeeJim** [comment]
和位置有关，应该是和你代码里其他节点的 z-index 有关了。

**Comment by synctimes163** [comment]
ok 那组件里面的文字和 宽度可以设置吗？怎么设置？ 现在默认最大是 374rpx.如果文字想换行可以吗

.t-toast__content {
  position: fixed;
  right: -50%;
  left: 50%;
  transform: translate(-50%, -50%);
  background-color: rgba(0, 0, 0, 0.6);
  align-items: center;
  border-radius: 8rpx;
  font-size: 28rpx;
  color: white;
  max-width: 374rpx;
  width: fit-content;
  line-height: 44rpx;
  box-sizing: border-box;
  z-index: 12001;
}

**Comment by LeeJim** [comment]
> ok 那组件里面的文字和 宽度可以设置吗？怎么设置？ 现在默认最大是 374rpx.如果文字想换行可以吗
> 
> .t-toast__content { position: fixed; right: -50%; left: 50%; transform: translate(-50%, -50%); background-color: rgba(0, 0, 0, 0.6); align-items: center; border-radius: 8rpx; font-size: 28rpx; color: white; max-width: 374rpx; width: fit-content; line-height: 44rpx; box-sizing: border-box; z-index: 12001; }

你可以直接给 `.t-toast__content` 写样式，会覆盖当前的样式的

**Comment by LeeJim** [comment]
目前看起来没什么问题了，我就先关掉 issue，后续要问题可以提新的 issue 反馈给我们
