### ISSUE TITLE
check-box content slot doesn't work

### ISSUE THREAD

**Issue by vhxubo** [Tencent/tdesign-miniprogram#74]
**Describe Framework**

tdesign-miniprogram

**Describe Environment**

any

**Describe the bug**
check-box `slot="content"` doesn't work.

```html
<t-checkbox>
    <!-- doesn't work -->
    <view slot="content">
    </view>

    <!-- work -->
    <view></view>
</t-checkbox>
```

**Additional context**

https://github.com/Tencent/tdesign-miniprogram/blob/9d703b29577a9c44b3a87569d7f82f6d8088b70f/src/checkbox/README.md#L61
https://github.com/Tencent/tdesign-miniprogram/blob/9d703b29577a9c44b3a87569d7f82f6d8088b70f/src/checkbox/checkbox.wxml#L34-L40

**Comment by LeeJim** [comment]
let me check

**Comment by LeeJim** [comment]
@amberlwan 麻烦跟进一下咯
