### ISSUE TITLE
[upload] 上传失败无状态

### ISSUE THREAD

**Issue by luchuanqi** [Tencent/tdesign-miniprogram#748]
### tdesign-miniprogram 版本

latest

### 重现步骤

![企业微信截图_1108f326-b247-4dbb-b405-044ac5752e50](https://user-images.githubusercontent.com/64452728/183861044-de435b4d-ae26-40be-ac39-46e8b5ef59d0.png)
上传失败，无法触发重试

### 实际结果

上传失败，无法触发重试

**Comment by LeeJim** [comment]
@Winfans 在跟进

**Comment by LeeJim** [comment]
确实有问题，目前提供的解决方案是，增加 click 事件，返回当前文件的信息
