### ISSUE TITLE
[upload] 组件API

### ISSUE THREAD

**Issue by luchuanqi** [Tencent/tdesign-miniprogram#749]
### 这个功能解决了什么问题

![企业微信截图_ebf58790-daf2-481c-a4bb-c25e71b493fb](https://user-images.githubusercontent.com/64452728/183861682-c147b1eb-f623-4a79-9b6d-0d4cc3867935.png)
upload组件， success、 fail状态与文件上传状态无关

### 你建议的方案是什么

建议成功失败状态， 关联文件上传状态

**Comment by LeeJim** [comment]
@Winfans 在跟进

**Comment by Winfans** [comment]
这里的关联成功失败状态指的是关联自定义上传函数吗？ @luchuanqi
