### ISSUE TITLE
官方小程序版示例的选择器为什么会错位呢？你们测试的时候没有发现这个问题嘛？

### ISSUE THREAD

**Issue by mistyrain-jiangnan** [Tencent/tdesign-miniprogram#75]
![image](https://user-images.githubusercontent.com/66396394/148015758-b6f1459b-c2b8-4f35-81b1-b6271bd67720.png)

**Comment by LeeJim** [comment]
> 这里要先说一下，这个小程序在线预览是个试验性能力，所以和实际渲染是有所差异的。

另外，官网有这样的问题，确实会让用户误解，因此我这边会处理一下。
