### ISSUE TITLE
[Swiper]动态修改 图片个数，当图片个数少于修改前会出现白色轮播

### ISSUE THREAD

**Issue by xiaodongjava** [Tencent/tdesign-miniprogram#753]
### tdesign-miniprogram 版本

0.16.0

### 期望结果

正常轮播

**Comment by anlyyao** [comment]
我来跟进～

**Comment by xiaodongjava** [comment]
> 我来跟进～
感谢支持，刚我更新最新版本  "tdesign-miniprogram": "^0.19.1"  一样会有空白出现；
    <t-swiper autoplay="true">
      <t-swiper-item wx:for="{{bannerList}}" wx:key="index">
        <t-image src="{{item.url}}" t-class="banner_image"/>
      </t-swiper-item>
      <t-swiper-nav minShowNum="2" slot="nav" type="dots-bar" />
    </t-swiper>

**Comment by xiaodongjava** [comment]
> 我来跟进～
感谢支持，刚我更新最新版本  "tdesign-miniprogram": "^0.19.1"  一样会有空白出现；
    <t-swiper autoplay="true">
      <t-swiper-item wx:for="{{bannerList}}" wx:key="index">
        <t-image src="{{item.url}}" t-class="banner_image"/>
      </t-swiper-item>
      <t-swiper-nav minShowNum="2" slot="nav" type="dots-bar" />
    </t-swiper>

**Comment by xiaodongjava** [comment]
> 我来跟进～

@anlyyao  动态改变的时候，还是有错误，请将判断如果自动播放为true 就重新初始化一下自动播放

**Comment by anlyyao** [comment]
@xiaodongjava  我新起了一个项目，但没能复现你的问题，我这边是正常的，目前的逻辑是item变化，更新数组，current回到0。 请确认版本是否为 0.19.1，如果还有问题，可以提交代码片段给我，我会继续跟进的～

**Comment by xiaodongjava** [comment]
@anlyyao  感谢支持，刚刚重新删除所有组件，重新安装 已经成功了，非常感谢
