### ISSUE TITLE
[微信小程序 - 动作面板] 真机调试，引入组件失败，程序报错

### ISSUE THREAD

**Issue by HuziG** [Tencent/tdesign-miniprogram#754]
### tdesign-miniprogram 版本

0.19.0

### 重现步骤

app.json - 全局引入了组件
`"usingComponents": {
    "t-action-sheet": "tdesign-miniprogram/action-sheet/action-sheet"
  },`

index.js - 使用组件
`import ActionSheet, {
  ActionSheetTheme,
} from "tdesign-miniprogram/action-sheet/index";`

index.wxml - 使用组件
`<t-action-sheet id="t-action-sheet" bind:selected="handleSelected" bind:cancel="handleCancel" />`

在开发工具中正常运行，真机调试报错

### 期望结果

真机调试正常

### 实际结果

具体报错内容，如下 ~

`MiniProgramError
Error
Error: Error
line:1,column:751571,Error: module 'miniprogram_npm/tdesign-miniprogram/actionSheet/action-sheet.js' is not defined, require args is './action-sheet'`

### 框架版本

微信小程序 2.25.2

### 系统版本

MacOS(11.6)

### Node版本

16.13.1

### 补充说明

我的项目文件目录如下~

<img width="257" alt="image" src="https://user-images.githubusercontent.com/28282506/184471760-faf70649-2ebf-43fc-b88c-96df5281d440.png">

_No response_

**Comment by gxujin** [comment]
代码片段：
https://developers.weixin.qq.com/s/J2CKizmS7UBH

windows10环境

1、预览运行正常

2、模拟器运行，显示没有反应，控制台提示以下错误
Component is not found in path "miniprogram_npm/tdesign-miniprogram/action-sheet/action-sheet"

3、真机调试，提示以下错误：
Error: module 'miniprogram_npm/tdesign-miniprogram/action-sheet/action-sheet.js' is not defined, require args is './action-sheet'
Component is not found in path "components/action-sheet/index" (using by "index/index")

**Comment by LeeJim** [comment]
我看下。

**Comment by zlsam** [comment]
不是缓存导致，我也遇到这个问题，只出现于首次编译运行到有该组件的页面会出现这个问题，刷新后就好了，暂时不用该组件，用了其他解决方案

**Comment by ElanYoung** [comment]
> 我发生情况刚好相反，如果我在页面配置引入该组件就会提示两个错误。 ![image](https://user-images.githubusercontent.com/70793915/207298651-80340005-9b7c-4b03-967c-235475002dd4.png) 如果在全局配置引入该组件就没有问题。与你们的情况完全相反

同样遇到

**Comment by wolf-leo** [comment]
> 我这边偶尔出发生，但重启开发者工具就没有这个问题。 我怀疑是开发者工具的缓存导致的

这个问题还没解决啊

**Comment by dorthl** [comment]
@LeeJim 或许这里不应该这样导出它 import ActionSheet from './action-sheet';

**Comment by 941477276** [comment]
我也遇到这个问题了，在苹果手机上真机调试就报错，在安卓手机上不会报错，真是奇怪

**Comment by minr** [comment]
一样遇到了，还没解决这个问题。

**Comment by hoveyLee** [comment]
我也遇到了，还没解决这个问题。

**Comment by hoveylee** [comment]
我测了一下。不使用按需注入就没有这个问题了。

**Comment by brainee** [comment]
<img width="1563" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/5361813/2a1604f7-a3a2-4d7c-98db-2ae3f9781629">

![image](https://github.com/Tencent/tdesign-miniprogram/assets/5361813/09cd94d9-092a-4551-9645-f413f35fa512)

**Comment by ayuday** [comment]
同样遇这样问题，按官方的示例不成功

**Comment by oqughin** [comment]
我也遇到了，不知道该怎么解决。。。
