### ISSUE TITLE
[action-sheet] 引入导致报错

### ISSUE THREAD

**Issue by CRECOHE** [Tencent/tdesign-miniprogram#755]
### tdesign-miniprogram 版本

0.19.0

### 重现链接

https://developers.weixin.qq.com/s/tWEbrumk7aBA

### 重现步骤

<img width="829" alt="image" src="https://user-images.githubusercontent.com/57332732/184508682-332c3fd6-777d-4ea2-90dc-25714169919a.png">
测试多次，特别特别奇怪的事，另外一个小程序项目是正常的（同node环境，同小程序基础库，同tdesign组件库，同组件代码），当前这个小程序之前也是好的（加入了接口服务请求），突然就不行了，然后我把两边的版本甚至文件都对齐了，但是还是会报错，只要取消掉action-sheet，就没事，现在弄成代码片段，删除掉项目相关的信息，只保留了最基础的引用，还是报错

**Comment by LeeJim** [comment]
我来看下

**Comment by CRECOHE** [comment]
不知道怎么的，重新又引入了一次，又正常了。特别奇怪，难道是编译器的缓存？在期间，我彻底删除开发者工具重装，发现又可以了

**Comment by LeeJim** [comment]
和 #754  是同个问题，我就先关闭了
