### ISSUE TITLE
[Fab]浮动按钮遮挡左滑操作按钮

### ISSUE THREAD

**Issue by chenxiaolong8023** [Tencent/tdesign-miniprogram#756]
### 这个功能解决了什么问题
防止浮动按钮遮挡左滑操作按钮或文字
![image](https://user-images.githubusercontent.com/33304073/184530673-8be72647-841a-4ed1-8b29-2e96b5c9b36a.png)

### 你建议的方案是什么？
浮动按钮可以自由移动拖拽

**Comment by LeeJim** [comment]
这个特性不属于 fab 组件的范畴。
你可以使用 https://developers.weixin.qq.com/miniprogram/dev/component/movable-view.html 实现

**Comment by chenxiaolong8023** [comment]
好嘞，我去试试
