### ISSUE TITLE
使用tabbar当作底部导航栏切换时激活颜色的bug

### ISSUE THREAD

**Issue by shylockWu** [Tencent/tdesign-miniprogram#757]
### tdesign-miniprogram 版本

0.19.0

### 重现链接

https://github.com/shylockWu/tdesin-wechat

### 重现步骤

把tabbar作为了组件进行使用，点击底部导航栏 页面会跳转 但是tabbar激活的颜色需要点两下才会显示正确

### 期望结果

<img width="421" alt="image" src="https://user-images.githubusercontent.com/108790041/184532170-85feb1aa-cfd2-4f59-8393-403955eead44.png">

### 实际结果

<img width="416" alt="image" src="https://user-images.githubusercontent.com/108790041/184532196-a63ff678-ef7c-4a70-9a19-0e40f637a419.png">

### 框架版本

vue2

### 系统版本

12.4

### Node版本

16

**Comment by LeeJim** [comment]
可以参考：https://github.com/LeeJim/miniprogram-starter

**Comment by sjalvforsett** [comment]
> 可以参考：https://github.com/LeeJim/miniprogram-starter

你好，我的是 hover 效果问题。点击其他的字体颜色切换正常，但是 hover 第一次是显示原来的。

**Comment by shylockWu** [comment]
thank you

**Comment by bingdian1314** [comment]
你好，楼主，使用t-tab-bar，在【首页】和【我的】之间切换，怎么切换到不同的页面？
