### ISSUE TITLE
[Tabs] 滑动切换使底部激活线条和选择项不在屏幕内

### ISSUE THREAD

**Issue by waney** [Tencent/tdesign-miniprogram#759]
### tdesign-miniprogram 版本

0.19.0

### 重现步骤

1、左右滑动tabs
2、选中一项后，动画效果，选中项被移到屏幕外。

`<t-tabs t-class="t-tabs" t-class-active="t-class-item" t-class-track="t-class-track" swipeable="{{false}}" value="{{tabIndex}}" bind:change="tabChangeHandle">
		<t-tab-panel wx:for="{{tabList}}" wx:for-index="index" wx:key="index" label="{{item.text}}" value="{{item.key}}" />
	</t-tabs>`

### 期望结果

希望滑动后选中项保持在画面内。

**Comment by waney** [comment]
![image](https://user-images.githubusercontent.com/69211/184562384-6323b55b-9da9-42fb-a2bd-d49051c00e25.png)
![image](https://user-images.githubusercontent.com/69211/184562402-d43eaa03-df21-4c6c-8d1d-faaddba6aecd.png)

**Comment by anlyyao** [comment]
@waney  是指，选中后，滑动tabs，仍希望选中项在可视区域内吗？

**Comment by waney** [comment]
> 
不是的，是指滑动后再选择一个之后，选中项会在动画之后移动到画面之外。

**Comment by CodingOnStar** [comment]
> @waney 是指，选中后，滑动tabs，仍希望选中项在可视区域内吗？

这里我们要不要用原生scroll-view标签的scroll-into-view属性来修复一下呢

**Comment by waney** [comment]
升级 0.19.3，问题仍然存在。

**Comment by xiaodongning** [comment]
正式版1.0.0问题仍然存在。

**Comment by TSiven** [comment]
正式版1.1.1问题仍然存在。

**Comment by anlyyao** [comment]
@waney @xiaodongning @TSiven 各位有空贴一下实际代码哈～，方便我们复现和定位问题。（ 刚刚有位用户朋友私聊了我这个问题，最后发现是因为在t-tab-item上给了margin值导致
