### ISSUE TITLE
[dropdown] dropdown-item 的 popup 错位

### ISSUE THREAD

**Issue by Phecda** [Tencent/tdesign-miniprogram#779]
### tdesign-miniprogram 版本

0.19.1

### 重现步骤

dropdown 的位置改变之后，其下拉选项会错位。比如页面滚动之后
``` html
<view>other elements</view>
<t-dropdown-menu>
  <t-dropdown-item />
</t-dropdown-menu>
<view>other elements long enough to make the view scrollable</view>
```

### 期望结果

下拉选项列表应紧贴 dropdown 下端

### 实际结果

选项列表与 dropdown-item 初始位置相匹配，但与当前位置有错位

### 补充说明

dropdown-item 只在 linked 时调用了 `getParentBottom` 计算 top。猜测在把 show 置为 true 前[比如这里](https://github.com/Tencent/tdesign-miniprogram/blob/e304f20920c1f9769be0cbbc86429b952c56215b/src/dropdown-menu/dropdown-menu.ts#L67)重新计算 top 可解决这个问题。

**Comment by LeeJim** [comment]
收到反馈，我来处理下
