### ISSUE TITLE
[tabs] 多个tab-panel超出屏幕，当选择最后一个tab-panel ，组件会自动向左滚动，无法在屏幕中显示被选中的tab-panel

### ISSUE THREAD

**Issue by xiaodongjava** [Tencent/tdesign-miniprogram#783]
### tdesign-miniprogram 版本

   "tdesign-miniprogram": "^0.19.1"

**Comment by CodingOnStar** [comment]
[https://github.com/Tencent/tdesign-miniprogram/issues/759](url)
