### ISSUE TITLE
dialog组件内 overlay组件z-index问题

### ISSUE THREAD

**Issue by Zoeking5113** [Tencent/tdesign-miniprogram#787]
### tdesign-miniprogram 版本

0.18.0

### 重现步骤

popup组件和dialog组件同时使用时 dialog设置z-index dialog里的overlay组件的z-index还是默认值

### 期望结果

组件内的z-index跟随 dialogz-index

**Comment by CodingOnStar** [comment]
没明白你这个是什么场景，popup、overlay和dialog三个组件一起用？

**Comment by Zoeking5113** [comment]
> 

对的 popup上面使用dialog

**Comment by CodingOnStar** [comment]
> > 
> 
> 对的 popup上面使用dialog

这两个组件目前都开放了zIndex属性，看看一起设置能不能满足你的场景

**Comment by Zoeking5113** [comment]
> > > 
> > 
> > 
> > 对的 popup上面使用dialog
> 
> 这两个组件目前都开放了zIndex属性，看看一起设置能不能满足你的场景

dialog里的遮罩是写在dialog组件里的 我改不了的，只能用样式强制去改

**Comment by LeeJim** [comment]
我大概理解你的诉求，是需要 property 来控制 dialog 内置的 overlay 的 z-index。
目前 overlay 的 z-index 是受 dialog 控制的，应该满足大部分场景。
可以补充一下什么场景需要另外控制 overlay 的 z-index 么？

**Comment by Zoeking5113** [comment]
> 我大概理解你的诉求，是需要 property 来控制 dialog 内置的 overlay 的 z-index。 目前 overlay 的 z-index 是受 dialog 控制的，应该满足大部分场景。 可以补充一下什么场景需要另外控制 overlay 的 z-index 么？

popup 和 dialog组合使用的时候

**Comment by Zoeking5113** [comment]
> > 我大概理解你的诉求，是需要 property 来控制 dialog 内置的 overlay 的 z-index。 目前 overlay 的 z-index 是受 dialog 控制的，应该满足大部分场景。 可以补充一下什么场景需要另外控制 overlay 的 z-index 么？
> 
> popup 和 dialog组合使用的时候

popup上需要弹出确认框这样子

**Comment by LeeJim** [comment]
> > 我大概理解你的诉求，是需要 property 来控制 dialog 内置的 overlay 的 z-index。 目前 overlay 的 z-index 是受 dialog 控制的，应该满足大部分场景。 可以补充一下什么场景需要另外控制 overlay 的 z-index 么？
> 
> popup 和 dialog组合使用的时候

我大概知道了。你的 zindex 需要控制成 dialog > popup > dialog's overlay | popup's overlay ?

**Comment by Zoeking5113** [comment]
> 

dialog>dialog's overlay>popup>popup's overlay 最好设置dialog时候 dialog‘s overlay z-index可以跟随变化

**Comment by Zoeking5113** [comment]
> 我大概理解你的诉求，是需要 property 来控制 dialog 内置的 overlay 的 z-index。 目前 overlay 的 z-index 是受 dialog 控制的，应该满足大部分场景。 可以补充一下什么场景需要另外控制 overlay 的 z-index 么？

没注意到你说dialog's overlay 受dialog控制的
![image](https://user-images.githubusercontent.com/24286904/187640956-6edb74ec-a2d9-4f50-94ed-5a729fb9d19f.png)
设置dialog zindex 20000 但是dialog'overlay还是默认的11000
