### ISSUE TITLE
[dialog] 文档或示例中缺少open-type-event的调用案例

### ISSUE THREAD

**Issue by hsk1995** [Tencent/tdesign-miniprogram#788]
### 这个功能解决了什么问题

dialog的确认键如果想使用button的开放能力获取手机号，用哪个字段、如何声明getPhoneNumber呢

### 你建议的方案是什么

示例中给个使用的案例吧

**Comment by LeeJim** [comment]
收到反馈。使用 confirm-btn ，传入对象时，所有属性都会透传至 t-button
