### ISSUE TITLE
图片上传回显问题#很糟糕的体验图片不显示，若不是提供了模板，定不会用这个xxx

### ISSUE THREAD

**Issue by zhaosheng0000** [Tencent/tdesign-miniprogram#789]
图片上传回显问题
1
![CD4BE9D1-FDA7-4fb5-8603-B26A67B4D2B7](https://user-images.githubusercontent.com/27938307/186133470-8d80be38-5ef2-4b51-b526-f07b9b2375df.png)
下面显示的是原生的image
2
![000ED1D0-9EB2-40b2-AB6E-A1CE441F9C7C](https://user-images.githubusercontent.com/27938307/186133584-36f81bd2-e55c-4c61-a661-9dfdb103797e.png)
.
？？？what

**Comment by LeeJim** [comment]
没看懂问题在哪，麻烦提供更完整的信息
