### ISSUE TITLE
[ Tabs ]定位滚动、渲染时出现脏数据

### ISSUE THREAD

**Issue by xgbnl** [Tencent/tdesign-miniprogram#793]
### tdesign-miniprogram 版本

0.19.2

### 重现链接

无

### 重现步骤

- 定位滚动
> 当Tabs被scroll-view组件所包裹时，子元素超出scroll-view组件时，点击内部子按钮时，按钮无法像正常情况那样滑动到当前按钮，而且它也不会自动滑动调整当前位置
- 脏数据现象
> 两个Tabs组件配合使用时，子Tabs会出现脏数据（即渲染数据会把上一个数组末尾的元素追加到当前tabs的末尾），用普通的view就无此现象。

### 期望结果

希望出个解决方法

### 实际结果

目前没有解决，官方也没人鸟我

### 补充说明

小程序零售模板使用`this.createSelectQuery`获取的dom对象为null，不管是在组件或是Page里使用此方法获取的均为null

**Comment by LeeJim** [comment]
收到，我来看下

**Comment by xgbnl** [comment]
> 

大佬，我记得你是在微信群里的。我在里面发有提问。不过你们的小伙伴好像都忙不过来。我只好上github上提issue了。不知道我描述的问题清不清楚。

**Comment by xgbnl** [comment]
> 收到，我来看下



> 收到，我来看下

大佬，我记得你是在微信群里的。我在里面发有提问。不过你们的小伙伴好像都忙不过来。我只好上github上提issue了。不知道我描述的问题清不清楚。

**Comment by LeeJim** [comment]
稍等哈，今天解决，顺便发布个 beta 版本

**Comment by LeeJim** [comment]
看完你的描述，还是不知道具体问题，能否提供代码片段？
