### ISSUE TITLE
[tabbar]文档显示的 自定义主体颜色变量错误

### ISSUE THREAD

**Issue by lanxiao-fang** [Tencent/tdesign-miniprogram#795]
### tdesign-miniprogram 版本

0.19.1

### 重现链接

https://tdesign.tencent.com/miniprogram/components/tab-bar

### 重现步骤

![Uploading image.png…]()
css里面的自定义变量写错了，是--td而不是--t

**Comment by LeeJim** [comment]
收到。感谢反馈
