### ISSUE TITLE
提示组件找不到

### ISSUE THREAD

**Issue by dx01259** [Tencent/tdesign-miniprogram#81]
用微信小程序工具创建项目，直接npm i tdesign-miniprogram -S --production 下载下来，拷贝的目录下面。
在全局引入的时候，提示组件找不到内部自己的组件，为什么？
![image](https://user-images.githubusercontent.com/13490100/148320546-a87c52f3-2734-4889-ba0f-32d231db3143.png)

**Comment by LeeJim** [comment]
你需要执行下开发者工具的 `工具 - 构建npm`

**Comment by LeeJim** [comment]
后面在文档也补充一下文案吧。会更清晰
