### ISSUE TITLE
组件 Typescript 内置类型

### ISSUE THREAD

**Issue by zhangyuan722** [Tencent/tdesign-miniprogram#810]
<img width="472" alt="image" src="https://user-images.githubusercontent.com/62751963/187348085-ea184c7c-3fc1-4824-9897-92d00ac01bb4.png">
是否能够暴露一组 ts 事件参数类型的 interface 和 type

**Comment by AntzyMo** [comment]
如果用的是模板，小程序的类型都会在`typings`里面 这个是在`lib.wx.event.d.ts`里面

**Comment by LeeJim** [comment]
这个 event 的类型是小程序官方提供的，
可以安装 `miniprogram-api-typings` 然后使用 `WechatMiniprogram.TouchEvent`
