### ISSUE TITLE
[icon] 希望这里面可以直接使用第三方的图片

### ISSUE THREAD

**Issue by Zlianxin** [Tencent/tdesign-miniprogram#815]
### 这个功能解决了什么问题

因为在做一个新的项目的时候，往往会使整个项目的图标保持统一。
而且有的时候根据甲方的需求，图标可能还是渐变的颜色，图标样式也会很复杂，这个时候，使用TDesign提供的图标，是不够用的。
这个时候，需要UI去对每个图标进行制作。
在前段时间，都是把图标传到阿里的iconfont上，之后直接引用阿里的cdn链接，但是不久前，阿里的iconfont出现了一些问题，时隔很久之后才恢复功能，这大大的影响了开发进度。
所以，提供这样一个直接引用图片的功能是很必要的，这样的话，如果图标更换，就只需要更改服务器中的图片就可以了。
而且，我之前做小程序的时候，都是用的 vant 的组件，它是提供这个功能的，现在正在考虑技术方案的转型，如果这部分无法实现，我还需要想另外的对应策应该怎么办。

### 你建议的方案是什么

判断 API 中 name 的值是什么，如果是图标名称的话，则显示对应的图标，如果是链接的话，则显示所对应的图片。

**Comment by LeeJim** [comment]
收到反馈，我来看看如何处理

**Comment by LeeJim** [comment]
name 支持图片地址
@anlyyao 跟进下吧
