### ISSUE TITLE
官方h5演示 Dialog   UI错位/无取消按钮

### ISSUE THREAD

**Issue by zcjunblog** [Tencent/tdesign-miniprogram#82]
**Describe Framework**

tdesign-miniprogram

**Describe Environment**

官方h5演示

**Describe the bug**
UI错位/无取消按钮
![Snipaste_2022-01-06_10-45-26](https://user-images.githubusercontent.com/45475778/148320819-78e7c16c-f7df-41ec-be62-02e149d18506.png)

**Additional context**

**Comment by LeeJim** [comment]
收到。正在跟进处理中

**Comment by LeeJim** [comment]
已解决，请更新至 v0.4.1 试试
