### ISSUE TITLE
[tabs] 希望事件能够获取label的名称

### ISSUE THREAD

**Issue by CRECOHE** [Tencent/tdesign-miniprogram#827]
### 这个功能解决了什么问题

现在只是单一的获取选项卡的值，label名称是获取不到的，如果在不用循环出tab panel时候，pannel中的内容是不一样的，所以需要获取更多值会更好一些

### 你建议的方案是什么

增加官方提供的属性的值，或则还能拓展data-x得值

**Comment by LeeJim** [comment]
希望的是 click 事件还是 change？

**Comment by CRECOHE** [comment]
> 希望的是 click 事件还是 change？

change就可以了

**Comment by LeeJim** [comment]
OK 我来处理
