### ISSUE TITLE
[t-tabs] t-tab-panel 里面内容绑定事件没有触发

### ISSUE THREAD

**Issue by xiaofeng1998025** [Tencent/tdesign-miniprogram#834]
### tdesign-miniprogram 版本

0.19.3

### 重现步骤

<t-tabs value="{{typeid}}" placement="left" bind:change="onTabsChange">
        <t-tab-panel wx:for="{{list}}" wx:key="id" label="{{item.text}}" value="{{item.id}}">
                <view bindtap="onchange">内容这里事件无法触发</view>
        </t-tab-panel>
</t-tabs>

### 补充说明

请尽快修复，完全不能用影响挺大的

**Comment by LeeJim** [comment]
垂直模式下确实有问题，@anlyyao 在跟进
