### ISSUE TITLE
[Indexes 索引] 需要检索的内容，不支持插槽自定义样式吗

### ISSUE THREAD

**Issue by 15162652914** [Tencent/tdesign-miniprogram#849]
### 这个功能解决了什么问题

比如选择城市，城市可以展开，这里不能自定义样式
![image](https://user-images.githubusercontent.com/34590228/188823435-9ea62dca-7d84-4b3c-9adc-43de33b6771f.png)

### 你建议的方案是什么

![image](https://user-images.githubusercontent.com/34590228/188823421-5708d609-0a2b-4793-a496-30e65d1fd253.png)

**Comment by 15162652914** [comment]
![image](https://user-images.githubusercontent.com/34590228/188823235-a1348b7c-91b5-4a1f-9f8c-c4b9e60d4396.png)

**Comment by LeeJim** [comment]
和 #751 是同个问题，我们这边正在研究如何实现
