### ISSUE TITLE
[tabs] 希望在选项卡名称旁边增加标签

### ISSUE THREAD

**Issue by CRECOHE** [Tencent/tdesign-miniprogram#860]
### 这个功能解决了什么问题

选项卡现在遇到情况：
1.分选项卡的消息，显示不同页卡的数量，并且有样式（现在仅仅能显示数量）
2.该选项卡，用于商品，新品，热卖等有样式标签，无法设置

### 你建议的方案是什么

单独设置一个badge，可以支持slot，标签可以放在名称的前面或后面

**Comment by LeeJim** [comment]
这个已经在设计中了。预计 10 月可以上线

**Comment by LeeJim** [comment]
已在 10.31 发布于 v0.24.0。
可以体验试试
