### ISSUE TITLE
cell 单元格组件 api image slot方式无法实现 & sring方式报错

### ISSUE THREAD

**Issue by yiyechuxia** [Tencent/tdesign-miniprogram#87]
string 方式：

![CC171A46-1CB7-4bc6-8BCE-F2021629491D](https://user-images.githubusercontent.com/33221535/148383922-e6122515-e7e7-40ab-9de6-291140b5ccbc.png)

slot 方式：
![7C0E0817-D3D8-4e4d-9124-0FCDA101BA34](https://user-images.githubusercontent.com/33221535/148383985-d4f74edd-1ad7-4175-bfe9-106606b56089.png)

**Comment by LeeJim** [comment]
报错信息说的很清楚了，是因为你使用了本地图片，而不是组件的问题。
