### ISSUE TITLE
TS项目使用tabbar当作底部导航栏切换时激活颜色的bug，只有黑色

### ISSUE THREAD

**Issue by greenking19** [Tencent/tdesign-miniprogram#872]
### tdesign-miniprogram 版本

0.21.0

### 重现链接

https://github.com/greenking19/tab-bar-ts-bug

### 重现步骤

`npm install`
然后 构建npm运行就看到

### 期望结果

参考这个例子做的
https://github.com/LeeJim/miniprogram-starter
![image](https://user-images.githubusercontent.com/43332372/191083795-e50358db-b74e-47e8-93ad-d124a125c55c.png)

### 实际结果

tab-bar是黑色的不是 TDeisgn的蓝色主题色
<img width="432" alt="image" src="https://user-images.githubusercontent.com/43332372/191083210-14f040ee-a04a-463e-ba9b-444f15a43837.png">

### Node版本

v16.13.1

### 补充说明

好像只有ts版本才有这个问题。

**Comment by LeeJim** [comment]
我来看下
