### ISSUE TITLE
DateTimePicker 时间选择器 日无法改变

### ISSUE THREAD

**Issue by pitilesszgw** [Tencent/tdesign-miniprogram#876]
### tdesign-miniprogram 版本

0.17.0-beta.1

### 重现步骤

时间选择器无法选择日
picker日时松开手后会回到原始位置

### 期望结果

时间选择器选择到指定日

### 实际结果

无法选择

### 框架版本

微信小程序基础库2.25.4

### Node版本

v16.14.0

**Comment by LeeJim** [comment]
我看看

**Comment by LeeJim** [comment]
升级到最新版本试试？
