### ISSUE TITLE
[Tabs] tabs无法手动设置默认选中项

### ISSUE THREAD

**Issue by csshjh** [Tencent/tdesign-miniprogram#877]
### tdesign-miniprogram 版本

^0.20

### 重现步骤

tabs无法手动设置默认选中项

### 期望结果

希望可以手动设置tabs默认选中项

### 框架版本

微信小程序1.05

### 浏览器版本

Chrome105.0.5195.102

### 系统版本

win7

**Comment by CodingOnStar** [comment]
defaultValue本身非受控，可以通过value来控制。官网有受控用法的实例

**Comment by LeeJim** [comment]
如 @CodingOnStar  所说，是没问题了。我先关了 issue 了
