### ISSUE TITLE
TabBar

### ISSUE THREAD

**Issue by ysshull** [Tencent/tdesign-miniprogram#878]
### 这个功能解决了什么问题

TabBarItem Props中的icon无法使用image图片

### 你建议的方案是什么

希望可以支持icon使用图片

**Comment by LeeJim** [comment]
我来看看

**Comment by LeeJim** [comment]
是不是版本太低了。
icon 是从 0.20.0 才开始支持 image 图片的

**Comment by yuboabc** [comment]
icon使用图片后, 如何区分 选中和未选中的图片呢?
