### ISSUE TITLE
button，tabs，input等基础组件

### ISSUE THREAD

**Issue by 862755519** [Tencent/tdesign-miniprogram#881]
### 这个功能解决了什么问题

为什么这类基础组件都不支持自定义主题呢，难道说我们要改变一个颜色，还要自己样式覆盖吗，腾讯作为一个中国的互联网大厂写个组件库还那么垃圾吗，麻烦不要只知道圈钱，也要为互联网行业做点贡献。

### 你建议的方案是什么

支持所有组件统一的主题定制

**Comment by LeeJim** [comment]
@862755519 有问题就提，请注意语气

**Comment by LeeJim** [comment]
在计划与进展 #574 里有主题定制的规划，预计年底可以上线，因此先 close 了
