### ISSUE TITLE
[DateTimePicker] 点击取消后，再次弹出，时间变成区间起始值

### ISSUE THREAD

**Issue by jonsonCai** [Tencent/tdesign-miniprogram#882]
### tdesign-miniprogram 版本

是

### 重现链接

https://tdesign.tencent.com/miniprogram/components/date-time-picker?tab=demo

### 重现步骤

第一条demo,点击弹出日期选择弹窗后，点击取消隐藏弹窗，再次点击弹出，默认的弹出时间会变成指定选择区间的起始值，如果是点击空白处隐藏弹窗的，则不会触发该bug

**Comment by LeeJim** [comment]
我来处理下

**Comment by CodingOnStar** [comment]
> 我来处理下

我处理啦，可以直接看看
