### ISSUE TITLE
[t-steps] 提示内存溢出

### ISSUE THREAD

**Issue by misscheng** [Tencent/tdesign-miniprogram#884]
### tdesign-miniprogram 版本

0.21.1

### 重现链接

https://t.wss.ink/f/9dq8e69vs97

### 重现步骤

使用t-steps组件，直接就提示内存溢出
steps-item中赋值parent，报错，提示内存溢出，自行注释掉，就不报错了
截图地址：https://t.wss.ink/f/9dq8e69vs97
使用开发者工具，没复现这种情况

### 期望结果

不报内存溢出

### 实际结果

输出： Maximum call stack size exceeded

### 框架版本

0.21.1

### 浏览器版本

谷歌浏览器 版本 103.0.5060.66（正式版本） （64 位）

### 系统版本

Windows

### Node版本

14.16.0

### 补充说明

在我项目中存在问题，单独代码片段没复现

**Comment by LeeJim** [comment]
感觉使用的是旧的版本，是不是下载了新版本但是没有执行”构建npm“
