### ISSUE TITLE
统一文档代码演示部分与右侧预览部分的代码

### ISSUE THREAD

**Issue by vhxubo** [Tencent/tdesign-miniprogram#89]
**Is your feature request related to a problem? Please describe.**
文档示例中的代码演示与预览部分大多数对不上号

**Describe the solution you'd like**
- 统一文档代码演示部分与右侧预览部分的代码, 确保左侧代码复制完整后, 可以实现与右侧预览相同的功能与样式
- 或者提供查看完整代码的 GitHub 链接等指引

**Describe alternatives you've considered**
对比示例代码与组件源码

**Additional context**
![why](https://user-images.githubusercontent.com/17352372/148500802-1472a20d-998f-4cfa-94c2-e4ab43aef90e.png)

**Comment by LeeJim** [comment]
这个问题我们也发现了，正在想方案处理。
之前是代码和文档是两份，后面会统一成一份。

**Comment by LeeJim** [comment]
经过讨论，觉得示例代码 和 预览部分 是没有必要严格一致的。
但目前确实需要完善 示例代码

**Comment by vhxubo** [comment]
> 经过讨论，觉得示例代码 和 预览部分 是没有必要严格一致的。
> 但目前确实需要完善 示例代码

好👌🏻辛苦了
