### ISSUE TITLE
[Dialog] Dialog.confirm创建后，点确定了，如何关闭Dialog呢

### ISSUE THREAD

**Issue by dxReader** [Tencent/tdesign-miniprogram#893]
### tdesign-miniprogram 版本

当前最新0.21

### 重现步骤

const dialogConfig1 = {
            title: '弹窗标题',
            content: '告知当前状态、信息和解决方法等内容。',
            cancelBtn: '取消',
            confirmBtn: {
                // openType: 'getPhoneNumber',
                content: '获取手机',
                bindtap() {
                    console.log('获取手机');
                },
            },
        }

        Dialog.confirm(dialogConfig1).then(() => {
            console.log('点击确认');
        }).catch(() => {
            console.log('点击取消');
        });

### 期望结果

期望能异步关闭Dialog

**Comment by dxReader** [comment]
但在 bindgetphonenumber 事件中 无法执行 close

**Comment by dxReader** [comment]
我发现是 id (selector) 不能修改，因为我可能有多个dialog，可以考虑给 一个 selector 的属性吗

**Comment by anlyyao** [comment]
<img width="880" alt="企业微信截图_18fcc64a-1daa-4897-b984-6816f1b916cc" src="https://user-images.githubusercontent.com/51158141/192917310-a8e201a6-3679-4ffe-b4a5-69325cb29fad.png">
@dxReader  可以自定义selector的哈～

**Comment by dxReader** [comment]
> <img alt="企业微信截图_18fcc64a-1daa-4897-b984-6816f1b916cc" width="880" src="https://user-images.githubusercontent.com/51158141/192917310-a8e201a6-3679-4ffe-b4a5-69325cb29fad.png">
> 
> @dxReader 可以自定义选择器的哈～

Dialog.close()  不能关闭自定义的呢

**Comment by anlyyao** [comment]
@dxReader  🫡了解了～  我这边跟进一下
