### ISSUE TITLE
[CountDown 倒计时] time参数设置毫秒值，时分秒显示的为什么不能超过24小时

### ISSUE THREAD

**Issue by han-guang-chuan** [Tencent/tdesign-miniprogram#895]
### tdesign-miniprogram 版本

0.21.2

### 重现步骤

功能是需要时分秒显示，比如30:20:15这种，但是time毫秒设置超过24小时，时分秒的显示就会变成00:20:15

**Comment by LeeJim** [comment]
收到，我来看看

**Comment by LeeJim** [comment]
超过24小时，应该是天数了，可以在 format 里使用 `DD` 代表日期
