### ISSUE TITLE
Popup visible-change 事件中的 visible 与 visiable

### ISSUE THREAD

**Issue by vhxubo** [Tencent/tdesign-miniprogram#90]
**Describe Framework**

tdesign-miniprogram

**Describe Environment**

Any

**Describe the bug**
文档中 `visible-change` 事件返回的参数应为 **visible**, 而在示例代码和组件源码中实际使用的是 **visiable**

**Additional context**
https://github.com/Tencent/tdesign-miniprogram/blob/e80b1097c214d7d2f2d29ebbb62a933e3c5ae9b9/src/popup/README.md#L97

https://github.com/Tencent/tdesign-miniprogram/blob/e80b1097c214d7d2f2d29ebbb62a933e3c5ae9b9/example/pages/popup/popup.ts#L48-L57

https://github.com/Tencent/tdesign-miniprogram/blob/e80b1097c214d7d2f2d29ebbb62a933e3c5ae9b9/src/popup/popup.ts#L66-L75

**Comment by LeeJim** [comment]
收到，立马处理一下
