### ISSUE TITLE
[t-icon]  name 指向图片地址不生效

### ISSUE THREAD

**Issue by clukboy** [Tencent/tdesign-miniprogram#901]
### tdesign-miniprogram 版本

0.21.2

**Comment by anlyyao** [comment]
@clukboy [官网](https://tdesign.tencent.com/miniprogram/components/icon)提供了图片链接用法的示例，可以参考下，确保使用无误，如果还是有问题，辛苦提供一下可复现代码片段～ 我这边跟进一下
<img width="1177" alt="截屏2022-10-09 14 22 42" src="https://user-images.githubusercontent.com/51158141/194741427-369932fd-5d2d-498f-8e97-d8a90a058d19.png">

**Comment by LeeJim** [comment]
时间过长没有回复，先暂时关闭了
