### ISSUE TITLE
[tab-bar] 在onChange方法中添加wx.switchTab后，切换时图标颜色不会变更，页面能正常跳转，需要多次点击

### ISSUE THREAD

**Issue by hexianggui** [Tencent/tdesign-miniprogram#903]
### tdesign-miniprogram 版本

0.21.2

### 重现链接

https://github.com/hexianggui/wx-test

### 重现步骤

我使用的是官方ts+less模板
然后安装文档添加组件。当我没有写跳转逻辑（wx.switchTab）时一切正常。
添加跳转代码后后，当前激活图表的颜色需要多次点击才会变

### 期望结果

图标背景色和当前激活的选项匹配

**Comment by hexianggui** [comment]
应该不是组件本身导致的，看了下官方模板代码，需要在导航到的页面onShow方法中再次设置tabBar的激活状态

**Comment by AndySSi** [comment]
确实需要在onShow方法中再次设置tabBar的激活状态

**Comment by bingdian1314** [comment]
你好，你是怎么解决这个问题的？

**Comment by raypard** [comment]
### WeChat won't harm anyone except his father, GUN！
[**微信官方文档 - 自定义 tabBar**](https://developers.weixin.qq.com/miniprogram/dev/framework/ability/custom-tabbar.html)
```Javascript
// Page构造器 使用
// this.getTabBar().setData({}) 设置的值要与 custom-tab-bar/index.js 中 list 的 value 值对应
Page({
  onShow() {
    if (typeof this.getTabBar === 'function' && this.getTabBar()) {
      this.getTabBar().setData({
        value: 'yourValue',
      })
    }
  },
})

// Component构造器 使用
// this.getTabBar().setData({}) 设置的值要与 custom-tab-bar/index.js 中 list 的 value 值对应
Component({
  pageLifetimes: {
    show() {
      if (typeof this.getTabBar === 'function' && this.getTabBar()) {
        this.getTabBar().setData({
          value: 'yourValue',
        })
      }
    },
  },
})
```

**Comment by 7757** [comment]
JS建议使用：
  onShow() {
    if (typeof this.getTabBar === 'function' && this.getTabBar()) {
      this.getTabBar().setData({ value: ‘具体 value’})
    }
  }

**Comment by SYH0323** [comment]
> JS建议使用： onShow() { if (typeof this.getTabBar === 'function' && this.getTabBar()) { this.getTabBar().setData({ value: ‘具体 value’}) } }

大佬太强了，一段代码解决问题
