### ISSUE TITLE
[Button] 无障碍支持

### ISSUE THREAD

**Issue by LeeJim** [Tencent/tdesign-miniprogram#913]
## 优先级
> P0 最高，数字越小优先级越高

P0

### iOS 表现
> 测试机：iPhone 11Pro（iOS 15.2） + 旁白

1. 视频定位00：01——示例中纯图标按钮未加标签
2. 视频定位00：06——禁用按钮未播报状态信息

### Android 表现

> 测试机：nova 5 pro，HarmonyOS 2.0.0 + 屏幕朗读<与TalkBack可能存在细小差异>
主要补充与iOS表现存在差异的地方

如 iOS

## 参考信息

录屏：https://share.weiyun.com/wBaUmOUS

## 改造建议

1. 建议示例中使用一个更具标识性的图标，并赋予一个有意义的标签（例如：个人中心、返回等图标按钮）
2. 声明了 `disabled` 的按钮在iOS下会将此状态播报为“变暗”，这里需要进一步确认是小程序的 bug，还是组件问题

## 改造参考示例

> 截图或录屏链接（参考 WeUI Web、小程序组件库、手机原生系统应用等）

暂无

## 验收标准

真机效果是无障碍改造验收通过的依据之一，请开发者在发起 `pull request` 时附上相应组件示例页分别在 iOS、Android下录屏效果，录屏示例及要求可分别查看 [iOS录屏指引](https://docs.qq.com/sheet/DRnBBVFFBWmZuYmRh?tab=ti9wxn)、[Android录屏指引](https://docs.qq.com/sheet/DRnBBVFFBWmZuYmRh?tab=icmj6f)。

最终 `pull request` 验收通过会以 iOS、Android 两个平台都满足无障碍要求为准，**同时**这两个平台的录屏链接有助于加快 `pull request` 通过效率哦：） 

## 常见无障碍 Q&A

[点我查看](https://docs.qq.com/sheet/DRnBBVFFBWmZuYmRh?tab=7b6unt&u=ebb77e942ee0425d878186af79e5ec6d)

## 其他说明
如果您准备修复此问题，请您在发起 `pull request` 之前先在 issue 中评论，以便其他开发者知道这个问题已经有人在跟进：）

最终激励以实际提交 `pull request` 并合并为准

## TDesign 开发者交流群
![待补充二维码](https://camo.githubusercontent.com/81e382234a4be1d5e773af94e298bcc50aec70fa85ecd5a84f29044415566ac7/68747470733a2f2f6f7465616d2d7464657369676e2d313235383334343730362e636f732e61702d6775616e677a686f752e6d7971636c6f75642e636f6d2f736974652f646f632f5444657369676e253230494d2e706e67)

## IssueShoot
- 预估时长: 4
- 期望完成时间: 2022-12-05
- 开发难度: 低
- 参与人数: 1
- 验收标准: 实现期望改造效果，提MR并通过验收
- 备注：最终激励以实际提交 pull request 并合并为准

**Comment by zhangpaopao0609** [comment]
已认领
