### ISSUE TITLE
[Input] 弹窗里的Input在设置suffix属性时，内容会有一个明显右移的情况

### ISSUE THREAD

**Issue by quxiaodong** [Tencent/tdesign-miniprogram#915]
### tdesign-miniprogram 版本

0.22.0

### 重现链接

https://developers.weixin.qq.com/s/AZpOJ0mw7wDc

### 重现步骤

1. 打开弹窗时，input设置了suffix属性，内容会向右移动。即使手动设置align=right也还是会突然向右移动
2 .打开弹窗时，input里面的内容一开始没有居中对齐，会闪一下才会居中对齐

**Comment by anlyyao** [comment]
@quxiaodong  因为弹窗的动画完成时间是300ms， 动画期间窗体的宽度是变化的。 你可以考虑 300ms后在显示input

**Comment by quxiaodong** [comment]
> @quxiaodong 因为弹窗的动画完成时间是300ms， 动画期间窗体的宽度是变化的。 你可以考虑 300ms后在显示input

那为什么input的suffix部分没有明显的右移呢

**Comment by anlyyao** [comment]
> > @quxiaodong 因为弹窗的动画完成时间是300ms， 动画期间窗体的宽度是变化的。 你可以考虑 300ms后在显示input
> 
> 那为什么input的suffix部分没有明显的右移呢

根本原因是小程序的input有问题，而suffix内容是独立于input，所以不受影响、
