### ISSUE TITLE
输入框的特殊文本类型代码示例错误

### ISSUE THREAD

**Issue by zhouhaoyiu** [Tencent/tdesign-miniprogram#922]
### 重现链接
https://tdesign.tencent.com/miniprogram/components/input?tab=demo
![image](https://user-images.githubusercontent.com/67226385/196329963-0177eed0-e2e8-4c97-9eac-7061a033a6d4.png)

### 重现步骤
找到特殊文本类型的WXML代码价格处

### 期望结果
 value="{{price}}"

### 实际结果
 vlaue="{{price}}"

| Environment | Info |
|---|---|
| 相关版本 | 0.23.0 |
| 框架版本 / 基础库版本 | 小程序 |
| 系统、浏览器 | Chrome |
| Node版本 |  |

**Comment by anlyyao** [comment]
@zhouhaoyiu 收到～ 拼写错误 我改一下
