### ISSUE TITLE
[Dialog] 可以不通过 visible 来控制 dialog 的显示与隐藏

### ISSUE THREAD

**Issue by Zlianxin** [Tencent/tdesign-miniprogram#926]
### 这个功能解决了什么问题

需求是，我想在共通的js里面去触发Dialog的弹出。
但是看现在的例子是，需要通过改变visible的状态来控制Dialog的弹出与隐藏。问题在于，在共通的js里面，我应该是没有办法通过this.setData去给data里面的属性赋值。那我就没有办法在共通js里面做这件事了。
希望可以有解决案，或者说，其实现在的功能可以实现，麻烦指教~

### 你建议的方案是什么

之前用vant的组件时，他们是这么干的。
在需要用到弹窗的画面引入组件，在wxml里面会加上<van-dialog id="van-dialog" />
之后，在共通js里面
先导入
import dialog from '@vant/weapp/dialog/dialog';
之后在需要的地方使用
dialog.alert({
  title: "当前服务不可用，请稍后尝试。",
  customStyle: 'font-size: 18px; padding: 0 15px; color: #333;',
}).then(() => {
  // on close
});

**Comment by Zlianxin** [comment]
@anlyyao 啊，确实是没有注意到，非常感谢你们的答复~

**Comment by LeeJim** [comment]
看起来没问题了，就先关闭了
