### ISSUE TITLE
组件能否支持设置style属性用来配置组件的样式

### ISSUE THREAD

**Issue by mvpdongdong** [Tencent/tdesign-miniprogram#934]
如题，组件能否支持设置style属性用来配置组件的样式，就像tdesign移动端h5组件就能通过给组件设置style配置组件样式，例如可以通过```<t-button style="backgroud-color: red;">按钮</t-button>```设置按钮颜色。

**Comment by LeeJim** [comment]
我来研究一下

**Comment by LeeJim** [comment]
从 v0.25.0 开始，
全体组件支持 custom-style 属性来透传样式至根节点。

**Comment by LeeJim** [comment]
后续发布正式版，可能会考虑将 custom-style 改成 style，同时开始 vitualHost = true
