### ISSUE TITLE
[快速开始文档错误] 文档错误

### ISSUE THREAD

**Issue by coderdp** [Tencent/tdesign-miniprogram#936]
### tdesign-miniprogram 版本

0.23.0

### 重现步骤

下载源码 tag:0.23.0，按照[教程](https://tdesign.tencent.com/miniprogram/getting-started#%E5%9C%A8%E5%BC%80%E5%8F%91%E8%80%85%E5%B7%A5%E5%85%B7%E4%B8%AD%E9%A2%84%E8%A7%88),在开发工具中预览，`npm run dev` 后，导入`_example`目录，提示错误`Component is not found in path "..../components/demo-block/index" (using by "components/demo-block/index")`,错误原因是 app.json 的 usingComponents 节点：t-demo 的路径错误，应为`"./components/demo-block/index",`

### 期望结果

build 后修复 app.json 路径问题

### 实际结果

build 后修复 app.json 路径问题

### 框架版本

0.23.0

**Comment by LeeJim** [comment]
重启开发者工具就OK了

**Comment by coderdp** [comment]
重新打开也不行，还是要修改路径

**Comment by shengzhou1216** [comment]
无语了，弄了半天，总是提升组件找不到。重启开发工具解决了。希望天堂没有微信小程序。
