### ISSUE TITLE
[Picker] 选择数据多列的时候，怎么可以实现级联啊？

### ISSUE THREAD

**Issue by Zlianxin** [Tencent/tdesign-miniprogram#949]
### 这个功能解决了什么问题

我知道现在有了一个级联的组件，但有的时候，可能也需要用piker去实现这一功能。

### 你建议的方案是什么

希望可以在文档里面有一个demo，可以告诉我们怎么去实现这个~

**Comment by LeeJim** [comment]
是不是类似地址选择这样的级联选择？

**Comment by Zlianxin** [comment]
> 是不是类似地址选择这样的级联选择？

是的

**Comment by LeeJim** [comment]
0.31.0 已添加。
by #1248
