### ISSUE TITLE
从来没有见过设计得如此烂的UI框架。

### ISSUE THREAD

**Issue by china-live** [Tencent/tdesign-miniprogram#951]
### 这个功能解决了什么问题

下拉选择器没有多选组件，居然叫什么下拉菜单，归类为导航。
文本框、选择器，单/多选放到一个表单时，居然找不到统一的排版布局方式。
绑定数据极其不方便，简单的一个编辑功能要写好多代码才能实现。

### 你建议的方案是什么

组件缺失，操作不方便，连官网示例都他妈有bug   真是神了，还官方组件库，比烂哇。

**Comment by LeeJim** [comment]
下拉菜单是支持多选的，有问题可以好好讨论，没必要

<img width="236" alt="image" src="https://user-images.githubusercontent.com/7017290/198495565-901496d5-7291-48fe-9f4e-460f329692ab.png">

**Comment by li781825965** [comment]
烂不烂自己看看吧，都懒得吐槽了，要不是一开始用了这套UI，绝对不可能再用

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/18167608/198532078-4e2b609b-639b-497b-9d0f-f2e41b2e9032.png">

**Comment by LeeJim** [comment]
> 烂不烂自己看看吧，都懒得吐槽了，要不是一开始用了这套UI，绝对不可能再用
> 
> <img alt="image" width="1243" src="https://user-images.githubusercontent.com/18167608/198532078-4e2b609b-639b-497b-9d0f-f2e41b2e9032.png">

0.22.0 才支持 Calendar。你自己看下版本对不对

**Comment by DayDayUp3000years** [comment]
日历组件需要更新版本
