### ISSUE TITLE
[Radio] 提供的 t-class-icon 不能修改radio中icon的样式

### ISSUE THREAD

**Issue by Zlianxin** [Tencent/tdesign-miniprogram#953]
### tdesign-miniprogram 版本

0.23.1

### 重现步骤

**在wxml中引用t-radio-group和t-radio**
` <t-radio-group t-class="cabinet-fifth-radio" bind:change="onChange" defaultValue="radio1">
        <t-radio t-class="fifth-radio" color="#15BE71" t-class-icon="radio-icon" t-class-border="radio-border" value="radio1" label="取" defaultChecked />
      </t-radio-group>`
**在wxss中指定icon的样式**
`.radio-icon {
  width: 30rpx !important;
  height: 20rpx !important;
}`

样式指定之后，icon的样式并不能发生变化

### 期望结果

从上述代码中，期待的是icon的宽高发生变化。

### 实际结果

但实际上icon的宽高并没有发生变化，而是包裹icon的view发生了变化。
经测试，添加背景颜色的属性，也是包裹的view的背景颜色发生了变化，没有修改icon。
而且从源码来看，{{prefix}}-class-icon 指定的样式也是在icon的外层，没有直接指向icon本身。
`  <view
    class="{{classPrefix}}__icon {{classPrefix}}__icon--{{align}} {{prefix}}-class-icon"
    data-target="icon"
    bind:tap="handleTap"
  >
    <view wx:if="{{customIcon}}" class="{{classPrefix}}__image">
      <image src="{{active ? iconVal[0] : iconVal[1]}}" class="{{classPrefix}}-icon__image" webp />
    </view>
    <t-icon
      wx:elif="{{active && iconVal[0] || !active && iconVal[1]}}"
      color="{{active && !disabled ? color : ''}}"
      name="{{active ? iconVal[0] : iconVal[1]}}"
      class="{{classPrefix}}__btn {{disabled ? classPrefix + '-is-disabled' : ''}} {{active ? classPrefix + '-is-checked' : ''}}"
    />
  </view>`

### 框架版本

小程序

**Comment by LeeJim** [comment]
确实是个问题，我来处理下

**Comment by LeeJim** [comment]
后面可以使用 CSS Variables 来修改，会方便一些
