### ISSUE TITLE
[Calendar] 在真机iPhone 12 promax上日期错位

### ISSUE THREAD

**Issue by lanseria** [Tencent/tdesign-miniprogram#956]
### tdesign-miniprogram 版本

0.23.1

### 重现步骤

在组件里使用 `Calendar` 组件

### 期望结果

在真机中星期与日期不错位

### 实际结果

在真机中星期与日期错位
![IMG_8239](https://user-images.githubusercontent.com/14802764/198955668-e88836ae-11c4-49fe-9ebd-f80c48925a8b.png)

**Comment by LeeJim** [comment]
我尽快处理下，感谢反馈
