### ISSUE TITLE
[button] 可否提供一个属性直接修改按钮的背景颜色

### ISSUE THREAD

**Issue by Zlianxin** [Tencent/tdesign-miniprogram#973]
### 这个功能解决了什么问题

通过t-class改颜色有点烦，主要是得important才能生效。。。

### 你建议的方案是什么

加一个color属性之类的，或者能通过CSS Variables改也可以

**Comment by LeeJim** [comment]
这个正在处理中

**Comment by LeeJim** [comment]
预计下周一 与 0.25.0 带上此特性
