### ISSUE TITLE
[upLoad]无法通过slot="deleteBtn"自定义删除按钮

### ISSUE THREAD

**Issue by GitLe2019** [Tencent/tdesign-miniprogram#975]
### tdesign-miniprogram 版本

0.24.0

### 期望结果

能够支持自定义删除按钮

**Comment by LeeJim** [comment]
由于小程序的限制，每个插槽只能渲染一次，因此 close-btn 这种渲染多个的插槽就只能渲染一个，是不符合需要的。
我将文档修改一下吧。
后续可以通过 CSS Variables 或者 外部样式类来定制样式
