### ISSUE TITLE
[picker] auto-close置为false不起作用。

### ISSUE THREAD

**Issue by mar105** [Tencent/tdesign-miniprogram#979]
### tdesign-miniprogram 版本

能

### 重现步骤

auto-close置为false，随便点遮罩层时，还是没控制住。

### 期望结果

功能正常即可。

### 框架版本

微信小程序

### 浏览器版本

微信小程序

**Comment by LeeJim** [comment]
我来看看

**Comment by LeeJim** [comment]
使用的什么版本？

**Comment by LeeJim** [comment]
0.16.0 版本开始支持，需要升级到这个版本之后
