### ISSUE TITLE
Input 组件是否可以支持双向绑定

### ISSUE THREAD

**Issue by vhxubo** [Tencent/tdesign-miniprogram#98]
**Is your feature request related to a problem? Please describe.**
在处理用户输入时, 会使用到多个 Input 组件, 而每个 Input 都需要监听 change 事件, 并完成数据的更新

**Describe the solution you'd like**
使用 model:value 实现数据的双向绑定

```html
<t-input model:value="{{ title }}" />
```

**Describe alternatives you've considered**

```html
<t-input value="{{ title }}" />
```

```js
handleChange(e) {
  const { value } = e.detail
  this.setData({ title: value })
}
```

**Additional context**

[简易双向绑定 | 微信开放文档](https://developers.weixin.qq.com/miniprogram/dev/framework/view/two-way-bindings.html)

**Comment by LeeJim** [comment]
收到，感谢反馈。我来跟进一下

**Comment by Vixcity** [comment]
> 收到，谢谢反馈。我来跟进一下

有结果希望可以通知一声，多谢啦

**Comment by nightmaring** [comment]
> 收到，谢谢反扑。我来跟进一下

@LeeJim 你好，我看组件input的value双向绑定功能在[这次提交](https://github.com/Tencent/tdesign-miniprogram/blob/fd5734cb3ea7924f74e5a945ef4799f8fab147c2/src/input/input.wxml)中去除了，请问是故意去除的吗，后期每个input的value都是需要通过change事件去修改它的值吗？
