### ISSUE TITLE
🚀 组件视觉升级

### ISSUE THREAD

**Issue by LeeJim** [Tencent/tdesign-miniprogram#980]
发布正式版本之前，需要对所有组件的视觉、交互、示例进行全新升级。

设计稿：[【腾讯 CoDesign】TDesign移动端设计稿](https://codesign.qq.com/s/RG6X0kXNObZxEPB)

#### Tips
- 避免踩坑，可以参考 Tabs 组件
- 每次只能认领一个组件
- 有不懂的地方可以随时联系 @LeeJim

> 认领方式：直接评论 “我来负责xxx组件” 即可。

## 激励

参与共建的开发者，将可以获得 [TDesign 周边](https://github.com/Tencent/tdesign/wiki/TDesign-%E5%91%A8%E8%BE%B9)（贴纸、鼠标垫、工卡套等）；

成为核心贡献者，将会拥有 TDesign 专属头像。

### 基础
- [x] Button @LeeJim #993
- [x] Fab @LeeJim #995
- [x] Icon
- [x] Link @anlyyao #1236

### 布局
- [x] Cell @LeeJim #1003
- [x] Divider @LeeJim #1035
- [x] Grid @LeeJim #1006

### 导航
- [x] DropdownMenu @LeeJim #1259
- [x] Indexes @LeeJim #1267
- [x] NavBar @LeeJim #1010
- [x] Steps @LeeJim #1225
- [x] Sticky @LeeJim 
- [x] TabBar @LeeJim #987 
- [x] Tabs @LeeJim #957 
- [x] SideBar @LeeJim #974 

### 输入
- [x] Cascader @LeeJim  #966 
- [x] Calendar @LeeJim #989
- [x] Checkbox @LeeJim #1100
- [x] DateTimePicker @LeeJim #1248
- [x] Input @anlyyao #1109
- [x] Picker @LeeJim #1248
- [x] Radio @LeeJim #1098
- [x] Rate @LeeJim #1177
- [x] Search @LeeJim #1103
- [x] Slider @LeeJim #1192
- [x] Stepper @anlyyao #1191 
- [x] Switch @LeeJim #1080
- [x] Textarea @anlyyao #1097
- [x] TreeSelect @LeeJim #1262
- [x] Upload @LeeJim #1034

### 数据展示
- [x] Avatar @anlyyao #1076 
- [x] Badge @LeeJim #1004
- [x] Collapse @LeeJim #1039
- [x] CountDown @anlyyao #1085 
- [x] Empty @anlyyao #1041
- [x] Footer @anlyyao #1042 
- [x] Image @LeeJim #1038
- [x] ImageViewer @anlyyao #1074 
- [x] Result @anlyyao #1040 
- [x] Skeleton @anlyyao #1037 
- [x] Swiper @LeeJim #1282 
- [x] Tag @LeeJim #997 

### 消息提醒
- [x] ActionSheet @LeeJim #1142
- [x] Backtop @anlyyao #1151 
- [x] Dialog @LeeJim #1240
- [x] Drawer @LeeJim #1147
- [x] Loading @LeeJim #1152
- [x] Message @anlyyao #1153 
- [x] NoticeBar @anlyyao #1036 
- [x] Overlay #1258
- [x] Popup @LeeJim #1257 
- [x] Progress @anlyyao #1178 
- [x] PullDownRefresh @LeeJim 
- [x] SwipeCell @anlyyao #1201 
- [x] Toast @LeeJim #1073

### 12.16 - 12.22

总进度 **98%** (54/55)

### 12.9 - 12.15

总进度 **82%** (45/55)

### 12.2 - 12.8

总进度 **80%** (44/55)

### 11.25 - 12.1

总进度 **69%** (38/55)

### 11.18 - 11.24

总进度: **56%** (31/55)

### 11.11 - 11.17

总进度：**40%** (22/55)

### 11.4 - 11.10

总进度：**16%** (9/55)

### 10.28 - 11.3

- 完成 Tabs、Cascader 的视觉升级
- 新增 SideBar 侧边导航

总进度 **5%** (3/55)

**Comment by anlyyao** [comment]
认领 noticebar

**Comment by LeeJim** [comment]
12月26日完结 🚀
