### ISSUE TITLE
[toast] 希望可以提供文本的换行功能

### ISSUE THREAD

**Issue by Zlianxin** [Tencent/tdesign-miniprogram#981]
### 这个功能解决了什么问题

假设我想弹出的文言是【验证码有误，请重新输入！】
我期望toast里面的效果是
=============
验证码有误，
请重新输入！
=============
但实际上是
=============
验证码有误，请重新
输入！
=============
这样，画面的感觉会很怪

### 你建议的方案是什么

在传入的message中，可以支持通过\n换行。

**Comment by LeeJim** [comment]
我来看看

**Comment by A164759920** [comment]
0.23.0版本遇到了这个\n换行的需求，要自己到toast.wxss里加一下white-space: pre-line 解决问题
