### ISSUE TITLE
[Upload] 上传图片成功后，缩略图仍然显示为0%

### ISSUE THREAD

**Issue by CharlieCho2017** [Tencent/tdesign-miniprogram#983]
### tdesign-miniprogram 版本

0.24.0

### 重现链接

官方小程序

### 重现步骤

1、打开tDesign微信小程序组件示例小程序；
2、进入Upload组件，上传一张图片；
3、上传成功后，缩略图仍旧显示0%。
![image](https://user-images.githubusercontent.com/28870006/200106067-5786829b-d829-4e50-9e7a-2edc557a9386.png)

### 期望结果

上传成功后，可以预览图片

### 实际结果

图片显示0%，无法预料

**Comment by LeeJim** [comment]
#1034 已修复此问题。
如果需要展示进度的话，需要将 status = 'loading' 且 percent 表示当前进度

**Comment by mooremok** [comment]
关于`t-upload`组件还有以下”特点“：

**Comment by mooremok** [comment]
关于`<t-upload>`组件的`request-method`还有以下”特点“：

**Comment by mooremok** [comment]
通过使用，推测`request-mehtod`绑定的方法是`bind:success`的一个中间件，如果定义了`request-mehtod`可以在中间截获当前所上传的图片对象，比如可以上传图片到服务器并修改图片的percent和status。但如果`request-mehtod`返回的是`Promise`会导致`bind:success`失效，不知何故，可能我用的方式不正确。
