### ISSUE TITLE
t-calendar 日历组件

### ISSUE THREAD

**Issue by leesunner** [Tencent/tdesign-miniprogram#988]
### tdesign-miniprogram 版本

0.24.0-beta.0

### 重现步骤

开发者工具上，在日历弹出后，可以通过鼠标滚轮滚动进行日期的上下翻页查看，但是不能通过触摸滑动进行类似的操作，这样导致真机上无法进行日历的上下操作

### 期望结果

希望添加触摸事件的操作，真机上可以进行日历的上下操作

### 框架版本

原生小程序

### 浏览器版本

微信开发者工具 stable 1.06.2206090

### 系统版本

win10家庭中文版

### Node版本

16.13.1

**Comment by LeeJim** [comment]
刚好修复别的问题，也顺便处理了。今晚发布 v0.25.0 带上
