### ISSUE TITLE
为 Button 组件添加自定义点击事件, 以便于处理 disabled 时的点击事件

### ISSUE THREAD

**Issue by vhxubo** [Tencent/tdesign-miniprogram#99]
**Is your feature request related to a problem? Please describe.**
当为 Button 组件设置 disabled 时, 尽管组件颜色变淡, 但是 tap 事件依旧可以正常执行, 需要自行在函数中处理

**Describe the solution you'd like**
- 自定义点击事件, 组件设置 disabled 后, 在组件内部处理
- 文档中指明在组件设置 disabled 后, tap 事件依旧会正常触发, 提醒用户处理
- 希望两者都能实现:pray: 

**Describe alternatives you've considered**
在 tap 事件函数中处理, 但是很容易忘记

**Comment by chaishi** [comment]
disabled 状态，确实不应该触发 tap 事件

**Comment by LeeJim** [comment]
确实不应该触发，没想到有什么场景需要这样处理
