### ISSUE TITLE
[Input] 增加快速填写昵称

### ISSUE THREAD

**Issue by CRECOHE** [Tencent/tdesign-miniprogram#994]
### 这个功能解决了什么问题

因为微信小程序收回获取用户的昵称，官方提供了input的快捷输入type
![image](https://user-images.githubusercontent.com/57332732/200681840-17cb7851-af38-4f2a-89e2-dd276f5148d5.png)
![image](https://user-images.githubusercontent.com/57332732/200681882-815f08fa-e462-4620-9e34-7004b5431045.png)

### 你建议的方案是什么

基于现有的type增加一个type = nickname

**Comment by LeeJim** [comment]
好建议，是一个简单的改动，欢迎直接给我们提 PR
