### ISSUE TITLE
[Popup] 内容区域无法滚动

### ISSUE THREAD

**Issue by quxiaodong** [Tencent/tdesign-miniprogram#996]
### tdesign-miniprogram 版本

0.25.0

### 重现链接

https://developers.weixin.qq.com/s/46LQEDm77qD4

### 重现步骤

内容区域已经设置overflow: auto，但是仍无法滚动，应该是修复了 #943 导致的

**Comment by LeeJim** [comment]
需要滚动的内容，是不是用的 view 而不是 scroll-vue ？

**Comment by quxiaodong** [comment]
> 需要滚动的内容，是不是用的 view 而不是 scroll-vue ？

替换成scroll-view后可以正常滑动了，因为我之前用的0.23.0版本，用的view可以滑动
