### ISSUE TITLE
[upload] 在文档中，可以提供较全的写法吗？

### ISSUE THREAD

**Issue by Zlianxin** [Tencent/tdesign-miniprogram#998]
### 这个功能解决了什么问题

看这个文档，其实有点不太会写。
例如api中的api的request-method是应该怎么定义的。
图片上传的那个0%，他是根据什么来判断的，他又是根据什么显示的100%。

### 你建议的方案是什么

希望可以有一个完整一点的，和后台交互的代码例子。。。

**Comment by LeeJim** [comment]
可以关注一下 #1034
